### ISSUE TITLE
Refactor CI/CD testing

### ISSUE THREAD

**Issue by mloning** [sktime/sktime#1032]
The automated unit tests would benefit from:
* Cleaning and restructuring 
* Migrating appveyor Windows builds to GitHub Actions
* Separating standard tests that are run on every PR and accuracy tests that are run periodically (cron jobs)
* Combine basic API tests on fitted objects to avoid having to call `fit` multiple times
* Making them importable from other packages (see https://github.com/pytest-dev/pytest/issues/421)
* Making them run on objects rather than classes (see #1027)

**Comment by TonyBagnall** [comment]
I would like a mapping overview of all the testing that goes on in sktime, then work towards a simple guide to tests, where to put them, what to test for each module etc etc. Improving classifier testing (removing excluded etc) is a mid term goal for me, but its more likely to happen sooner if its easier and intuitive to do

**Comment by fkiraly** [comment]
Agreed - I've put a simple testing guide in the extension guidelines, at the end of the forecaster tutorial

**Comment by fkiraly** [comment]
And appveyor and azure build take ages (2-3 hours??), speeding up is indeed a great suggestion.

**Comment by Lovkush-A** [comment]
I recently saw this video giving whirlwind tour of unittesting using UnitTests. 

[Ned Batchelder: Getting Started Testing - PyCon 2014 - YouTube](https://www.youtube.com/watch?v=FxSsnHeWQBY) 

My summary of main ideas. Might be useful:

* First chunk (~20 mins) is basics of unittests.
* Goes a tiny bit under-the-hood of UnitTests
* Big tip/opinion: treat unittesting the same way as you do rest of software engineering. should refactor it, should write helper functions, if appropriate should have tests for tests
* Idea of mock objects, to isolate what a test is testing, and to remove slow parts of tests (if appropriate). but big downside is that mock objects have to be manualyl updated if there are any interface changes
* use coverage tools to check which lines have/have not been tested
* things to read up on in your own time: dependency injection, ddt (data driven tests), jenkins and travis for continuous testing (I think this is for software in deployment?), integration tests, load testing

**Comment by Lovkush-A** [comment]
Been skimming through some of Ted Kaminski's essays on software engineering, and in this one https://www.tedinski.com/2018/05/01/designing-imperative-code-with-properties-in-mind.html they argue for 'property testing' and recommend the package [Hypotheis](https://hypothesis.readthedocs.io/en/latest/).

(Apologies - I realise I am not directly helping with the key steps given in the issue description, but this seems like best place to share knowledge about unittests)

**Comment by fkiraly** [comment]
>Just to clarify. Do you want a fix for appveyor or is the idea to anyway move away from appveyor and use the CI of Github

Yes, @corvusrabus, to both.

There was the *urgent problem* to get windows CI/CD to run again by whatever means necessary, this would have been solved by either and/or removing C/cython requirements.

Mid-term, we want to move to GitHub actions consistently, see #1032 and @mloning's incomplete attempt in #1319.

@mloning I think has paused on this after a myriad of issues appeared, so more pair of eyes would be appreciated.

**Comment by fkiraly** [comment]
I think all of the points at the top have been now addressed by various improvements over time, see here for an overview of the consolidated testing framework:
https://www.sktime.org/en/stable/developer_guide/testing_framework.html
