### ISSUE TITLE
[ENH] principled interface to infer seasonal periodicity from data

### ISSUE THREAD

**Issue by mloning** [sktime/sktime#1056]
Users currently have to set the seasonal periodicity `sp`. We should provide an option to estimate it from the data or infer it from the date time index.

There may be some existing related functionality in pycaret and statmodels already.

**Comment by fkiraly** [comment]
isn't this easily achieved already with doing tuning over the `sp` parameter?

**Comment by mloning** [comment]
Yes, but there may be some other heuristics which are less computationally expensive, e.g. using information on time index or seasonality tests.

**Comment by fkiraly** [comment]
so what's "done" for this issue then? Identify one or two methods that can infer seasonality parameter, and implement them as forecaster?

Also, do we need another scitype "parameter estimator"?

**Comment by mloning** [comment]
Yes, I think that would be an interesting case to see if we can come up with a good `ParameterEstimator` design.

**Comment by Lovkush-A** [comment]
One tool for detecting seasonality is via auto-correlations. I read about it in the [AutoTheta paper](https://www.researchgate.net/publication/338507620_Generalizing_the_Theta_method_for_automatic_forecasting). See first ~8 lines of Page 5 of the paper for brief description and references for further details.

Roughly: calculate autocorrelations and if an autocorrelation is particularly big (see paper for exact formula to determine the cutoff) then we say there is seasonality.

**Comment by mloning** [comment]
Yes, in think in the M4 study they used a similar heuristic based on a hypothesis test, there's some code for it [here](https://github.com/mloning/sktime-m4/blob/2b51b9c41968c2065b26e655df70a41c0a414e3a/scripts/utils.py#L314).

**Comment by RNKuhns** [comment]
Another option is to use fast-fourier transformation. I believe that's what Hyndman's packages use.

**Comment by aiwalter** [comment]
There is also an implementation:
```python
from seasonal.seasonal import fit_seasons
```
https://github.com/welch/seasonal

**Comment by RNKuhns** [comment]
Nice! The periodogram there is the fft method I was referring to.

**Comment by fkiraly** [comment]
design-wise and implementation-wise, this is now resolved by `BaseParamFitter` - at least as an experimental prototype.

Regarding the `seasonal` package, I will open a new issue, which will allow us to develop the `BaseParamFitter` interface further.

**Comment by fkiraly** [comment]
Issue for `seasonal` is here: https://github.com/sktime/sktime/issues/3835
