### ISSUE TITLE
TransformedTargetForecaster should also work as a transformer pipeline without any forecaster

### ISSUE THREAD

**Issue by aiwalter** [sktime/sktime#1090]
**Is your feature request related to a problem? Please describe.**
`TransformedTargetForecaster` inherits from `_SeriesToSeriesTransformer` and should therefore also be able to just receive transformers only in `steps`.

**Describe the solution you'd like**
Catching cases when last step of `steps` is not a forecaster. This would have to rise an exception when `predict()` is called as a transformer only has `fit()` and `transform()`.

**Additional context**
After having a multivariate interface where `y` can also be a `pd.DataFrame`, we can do the same for the new `ForecastingPipeline` (this would also inherit then from `_SeriesToSeriesTransformer`). See #967 
___
Martin Walter <martin_friedrich.walter@daimler.com>, Mercedes-Benz AG on behalf of Daimler TSS GmbH.
https://github.com/Daimler/daimler-foss/blob/master/LEGAL_IMPRINT.md

**Comment by fkiraly** [comment]
This would need a polymorphic pipeline, related to this PR on polymorphic base class:
https://github.com/sktime/sktime/pull/3108

Currently, we can do this more simply, using `make_pipeline` - similar to `sklearn`.

I suggest to close this, or alternatively reopen as an issue to implement a polymorphic pipeline.
