### ISSUE TITLE
[ENH] Adding sktime to mlflow

### ISSUE THREAD

**Issue by aiwalter** [sktime/sktime#1215]
**Is your feature request related to a problem? Please describe.**
I got the idea to add `sktime` as a package to `mlflow` like the following packages that are already included:
https://www.mlflow.org/docs/latest/python_api/index.html

**Describe the solution you'd like**
Fot this we would have to contribute to `mlflow` ofc, but I thought anyway to open the issue here first as we might find here someone to work on it more likely maybe. We could also open an issue at `mlfow`.

**Additional context**
Outreach. We might also think of other packages where we could integrate `sktime` similarly to `mlflow`.

**Comment by fkiraly** [comment]
nice! Welcome, @kirilral!
Might need a plan of attack and/or a design, since this is a larger project?

**Comment by aiwalter** [comment]
might be worth to look into this doc: https://www.mlflow.org/docs/latest/models.html#custom-flavors

**Comment by aiwalter** [comment]
@kirilral are you still working on this?

**Comment by benjaminbluhm** [comment]
@aiwalter Would be happy to work on this FR as I will soon have some capacity to contribute

**Comment by benjaminbluhm** [comment]
@aiwalter thanks for the opportunity to contribute!

If we want to create a mlflow custom flavor I  guess we should implement this in a separate repo `mlflow-sktime` as suggested in the mlflow docs. Probably best place to host this repo would be under https://github.com/sktime - would you agree?

Will be happy to start working on it once we have a repo in place.

Later we could also add this as a community plugin to mlflow docs under [MLflow Plugins](https://mlflow.org/docs/latest/plugins.html#community-plugins)

**Comment by aiwalter** [comment]
@benjaminbluhm I would actually prefer to have it in `sktime` main repo bcz then it will be better maintained and run with the same CI/CD and release process. We can have it probably best in path `sktime/utils/mlflow.py` and we can have `mlflow` as a soft-dependency. Instruction how to do that is [here](https://www.sktime.org/en/stable/developer_guide/dependencies.html?#adding-a-soft-dependency)

Otherwise I can also support here with this soft-dependency mechanism!

**Comment by benjaminbluhm** [comment]
@aiwalter where you suggest should documentation live for mlflow-sktime custom model flavor?

I will probably raise a draft PR some time next week

**Comment by aiwalter** [comment]
Great! Depends a bit on the size of the doc. A short doc can definitely go directly in the docstring and some code snippets in the docstring examples would also be nice. A longer doc could go in a separate notebook in the "examples" folder which we can then add to the sphinx somewhere and it will be rendered automatically 🙂

**Comment by benjaminbluhm** [comment]
Okay sounds good, thanks for guidance :-) will follow your suggestions, guess we can align more on docs once draft PR is raised
