### ISSUE TITLE
[MNT] Remaining issues with conda max-dependency recipe

### ISSUE THREAD

**Issue by fkiraly** [sktime/sktime#1227]
Thanks to @freddyaboulton we now have a max-dependency recipe on `conda-forge`, but there are some minor drawbacks to it due to other packages' restrictions. From issue #1142:

>it's impossible to install all dependencies via conda:
>- `pmdarima` causes version conflicts, you can see the conda output in the failed ci runs of the first commits.
>- Even if `pmdarima` did not cause conflicts, it's not available on windows
>- tbats and catch-22 do not have a package on conda forge

>I filed an issue for `tbats` to create a `conda` package here: https://github.com/intive-DataScience/tbats/issues/29 . Once that's done, I don't expect any problems adding tbats to the conda recipe.
>
>If `catch-22` will be removed sometime in the future, I think that just leaves `pmdarima`. We would need to figure out what's causing the version conflicts during the build and that could take some time. We can also file an issue for `catch-22` to create a conda package but I leave it up to your judgment since you have a better understanding of the timeline for deprecating its use. 

>So in short:

- [x] adding `tbats` to the recipe once they create a package. 
- [ ] adding `pmdarima` to the `conda` recipe after resolving the above issues.
- [ ] resolve `catch-22` situation - deprecate, move out, or help move to `conda`.

**Comment by fkiraly** [comment]
@lmmentel, @freddyaboulton, which of these are resolved by now, do you know?

**Comment by lmmentel** [comment]
`tbasts` got added in https://github.com/conda-forge/sktime-feedstock/pull/33

**Comment by lmmentel** [comment]
`pmdarima` has a conda package https://anaconda.org/conda-forge/pmdarima

**Comment by lmmentel** [comment]
catch-22 does not seem actively maintained...

**Comment by fkiraly** [comment]
@lmmentel, there seems to be a maintained version of catch-22?
https://github.com/chlubba/catch22/
last release 2021, but seems relatively stable

**Comment by lmmentel** [comment]
It seems we have different definitions of _active_. Nevertheless I thought this issue is about conda packages. I couldn't find a conda package for catch22.

**Comment by fkiraly** [comment]
ah, you are right! no conda...

**Comment by fkiraly** [comment]
this is fixed for now.

The `conda` recipe has comments for all soft dependencies not available on `conda`.
