### ISSUE TITLE
[ENH] forecasting: "naive supervised prediction" reducer

### ISSUE THREAD

**Issue by fkiraly** [sktime/sktime#1280]
We should have a shorthand for the reducer where `y` is simply predicted from `X`, possibly including the index.

This is generally not a good forecaster in isolation, but useful as a component for instance in #1279, in anomaly detection or other annotation tasks.

It's also a special case of the direct regression strategy with exogeneous variables, where there are zero lags.

Question for @ltsaprounis, @angelpone, @mloning: in the composition of this and #1279, could we use the "reconciler" somehow?

**Comment by mloning** [comment]
We could add this as a new option for strategy argument in `make_reduction`.

**Comment by fkiraly** [comment]
>We could add this as a new option for strategy argument in make_reduction.

yes, good idea!

**Comment by fkiraly** [comment]
I think this is now a special case of `DirectReductionForecaster` - using `X_treatment=concurrent` and no lags.
