### ISSUE TITLE
Implement modular ThetaForecaster

### ISSUE THREAD

**Issue by GuzalBulatova** [sktime/sktime#1299]
**References re-design of Theta Forecaster #854**

Implements ThetaLinesTransformer #923
Implements ColumnEnsembleForecaster #1082

**Describe the solution you'd like**

Implement modular `Theta Forecaster` that will
1. Decompose original data (univariate series) into theta lines (implementation of `ThetaLinesTransformer`, returns transformed time series in DataFrame);
2. Forecast each of these theta lines with different forecasters (implementation of `ColumnEnsembleForecaster`, returns predicted DataFrame)
3. Then aggregate the forecasts into one resulting prediction (return univariate pd.Series)

Users should be able to pass theta values for the transformation step, forecasters and aggregation function as parameters.

**Related issues:**
Poor Theta model predictions #421
Implementation of AutoTheta Forecaster #738

Existing implementations:
in sktime `sktime/forecasting/theta.py` (theta parameter is assumed)

**Comment by fkiraly** [comment]
done in #1300
