### ISSUE TITLE
[ENH] Unifying and refactoring sub-module structure across modules

### ISSUE THREAD

**Issue by RNKuhns** [sktime/sktime#1338]
**Is your feature request related to a problem? Please describe.**

As I've been going through looking at docstrings, I've noticed that sktime has a variety of "top-level" modules (e.g. forecasting, annotation, classification, etc). The sub-modules within these modules tend to have different "structures". 

For instance forecasting/classification provide access to "all" functionality related to those learning tasks via the "all" sub-module. 

In forecasting and transformation modules individual algorithms (for the most part) are in their own sub-modules (e.g. `from sktime.forecasting.arima import AutoArima`). In classification there is another level (e.g.: dictionary_based) and the files with the algorithms are non-public (e.g. `_cboss.py`).

In clustering the algorithms are imported from the top-level package (and the files they are implemented in are non-public). 

In annotation there is an `adapters` sub-module, but in forecasting we have adapter code that is imported in the individual algorithm sub-modules (e.g. prophet is in its own module that imports its adapter as opposed to being in an adapter module). 

Having so many different structures is not ideal. There is the Python idiom about having one clear way to do something. And importantly having all these different layouts can cause confusion to new users about where functionality should be imported from.

**Describe the solution you'd like**
Following the docsprint I think propose we have a developer meeting to build consensus on how we think sktime sub-modules should be structured. 

I'd propose that developers agree on a general sub-module format and then we create a summary issue to track each module's refactoring to align with the format we agree on. This will of course involve some "pain" in refactoring modules and adding deprecations (I'd propose we deprecate for a release before removing). But doing it now makes things much easier down the road. I also think that it might not be too bad to do because we are not changing anything beyond filenames/locations and then of course imports. 

**Describe alternatives you've considered**
An alternative would be to try and have a module restructuring sprint and milestone where we try to do all the restructuring in a week or two.

**Additional context**
I'm partial to the way the classification module is set up (individual code files are non-public and related algorithms are all imported from the same sub-module). This has the added benefit that in many cases the sub-modules don't match 100% with the code file that implemented the algorithm. This makes it easier if we need to rename, refactor or otherwise move around those code files. For example, as long a user can use `from sktime.classification.dictionary_based import BOSSEnsemble` we can potentially rename the underlying file, condense it with another file, etc and not impact the user.

**Comment by mloning** [comment]
Yes, I fully agree with that!

**Comment by aiwalter** [comment]
I was thinking about this before also and came to conclusion that some structures are like this bcz of soft dependencies. But happy to discuss it e.g. in next dev call?

**Comment by fkiraly** [comment]
>Following the docsprint I think propose we have a developer meeting to build consensus on how we think sktime sub-modules should be structured.

I think what you are proposing is the quickest way to get murdered by other sktime developers.

Jokes aside, I support you 😄

**Comment by fkiraly** [comment]
done with the base class rework in 2022
