### ISSUE TITLE
[DOC] Add documentation on datatypes, conversions and checking to developer guide

### ISSUE THREAD

**Issue by RNKuhns** [sktime/sktime#1434]
#### Describe the issue linked to the documentation

Our developer guide does not currently include any information on our basic datatypes, how to check for the input datatype, how to convert between acceptable datatypes, etc. 

This makes it hard to extend sktime in cases where this functionality is needed. 

#### Suggest a potential alternative/fix

We should prioritize adding this documentation to our online docs. I think that it should go in the developer guide for now (and eventually related information from a user perspective in a user guide).

**Comment by RNKuhns** [comment]
@fkiraly I'm up for helping make this happen (I think it is helpful for others and it will make the things I want to work on go much smoother), but we probably need to talk through how all that works before I can go ahead with it.

**Comment by fkiraly** [comment]
There actually is such documentation, as part of the data types tutorial, here:
https://github.com/alan-turing-institute/sktime/blob/main/examples/AA_datatypes_and_datasets.ipynb

I think it can be adapted from there, or - as a fallback option - the full notebook can be embedded in the documentation.

**Comment by avm19** [comment]
I've just started looking into `sktime` and I believe the said notebook must be given a higher priority than it currently has:

> https://github.com/alan-turing-institute/sktime/blob/main/examples/AA_datatypes_and_datasets.ipynb

1. Understanding sktime's data conventions and terminology is prerequisite to using algorithms.
2. There have been several changes to the conventions (e.g., relaxed requirements to "pd-multiindex"). Had the notebook been explicitly listed in [Tutorials](https://www.sktime.org/en/stable/tutorials.html), those changes would have been probably reflected in it.

**Comment by fkiraly** [comment]
@avm19, I think you are right.

There is some confusion and duplication going on, and the "tutorials" section of the docs is a bit of a mess.
An issue exists, we are looking for volunteers to help us improve this 😄 
https://github.com/alan-turing-institute/sktime/issues/2127

I'll look into updating the "datatypes" notebook, I can do that quickly, the rest is more of a project - would appreciate help here!

**Comment by fkiraly** [comment]
Regarding priority, I think there is a trade-off - new users would like to see a "quickstart" tutorial first, and only then a deeper dive. Most algorithmic functionality can be explained using the pandas `DataFrame` based mtypes, and going to deep into the different formats can be "too much information" if it comes too early.

My strategy would be "start on the surface but give pointers in later sections".

**Comment by fkiraly** [comment]
@avm19, I've updated the notebook with the changes to `pd-multiindex`, and the added `pd_multiindex_hier` hierarchical mtype:
https://github.com/alan-turing-institute/sktime/pull/2492

**Comment by avm19** [comment]
@fkiraly Thanks, I'll have a look! I am not sure I will participate yet, but might likely do so in the future! 

(I understand your logic, I am just one of those atypical new users who want to see the outline of the framework first.)

**Comment by fkiraly** [comment]
> I understand your logic, I am just one of those atypical new users who want to see the outline of the framework first.

Don't think you are "atypical" - we had internal discussions and I also wanted to place the "datatypes" notebook as the first "number zero" notebook.
I was outvoted - and also convinced by the argument - that most users probably want to see a quick start, because at that point it's not clear to them yet whether it's worth investing 10-20min into reading up on the data container framework.

If you have a suggested structure or alternative in mind, let us know.
