### ISSUE TITLE
[ENH] Adding a Featureizer as _SeriesToSeriesTransformer

### ISSUE THREAD

**Issue by aiwalter** [sktime/sktime#1443]
**Is your feature request related to a problem? Please describe.**
When doing feature engineering, we want to calculate new features by means of any transformer and add them to existing ones. For this there is a need for a new transformer composition called `Featurizer` which gets any `_SeriesToSeriesTransformer` and appends the transformed data as new columns instead of overwriting the input data. `Featurizer` could either get a single transformer or a list of transformers (advanced implementation), this two cases look as follows.

Related: #1174

**Describe the solution you'd like**
A clear and concise description of what you want to happen, ideally taking into consideration the existing toolbox design, classes and methods.

**Describe alternatives you've considered**
Use case when getting a single transformer:
```python
pipe = ForecastingPipeline(steps=[
    ("imputer", Imputer(method="mean")),
    ("minmaxscaler", Featurizer(TabularToSeriesAdaptor(MinMaxScaler(feature_range=(1,2))))),
    ("boxcox", Featurizer(TabularToSeriesAdaptor(PowerTransformer(method="box-cox")))),
    ("forecaster", AutoARIMA(suppress_warnings=True))])
pipe.fit(y=y_train, X=X_train)
```
In this case, the `boxcox` gets also the newly added features from `minmaxscaler`, whereas below the features are appended in parallel and not in sequence.
Use case when getting a list of transformers:
```python
pipe = ForecastingPipeline(steps=[
    ("imputer", Imputer(method="mean")),
    ("featurizer", Featurizer(
        ("minmaxscaler", TabularToSeriesAdaptor(MinMaxScaler(feature_range=(1,2)))),
        ("boxcox", TabularToSeriesAdaptor(PowerTransformer(method="box-cox"))),
    )),
    ("forecaster", AutoARIMA(suppress_warnings=True))])
pipe.fit(y=y_train, X=X_train)
```
The `Featurizer` would by default add the new columns by means of a suffix which is derived from the name of the transformer. Otherwise there could be a praram `suffix` and `prefix` so that user can also define this optionally.

**Additional context**
Pipelining

Any opinions @RNKuhns @mloning @fkiraly @ViktorKaz

**Comment by RNKuhns** [comment]
@aiwalter I think it is an interesting concept and I'm generally supportive of it. But what's a concrete use case? 

The example (which I know is just for illustrative purposes), adds a scaled version of the input data exeogenous data (minmaxscalar), it doesn't seem like that would add value in AutoArima (since I believe it is performing regression with ARIMA error structure when there is exogenous data). 

Would be good to have a specific example that could be used to give an idea of good use cases.

**Comment by aiwalter** [comment]
@RNKuhns there are other models that might benefit from having more exog features, also especially tree-based models that we can use via `make_reduction`

**Comment by fkiraly** [comment]
Solved by one of:

* `FeatureUnion` and the `Id` transformer
* using `ColumnEnsembleTransformer` and the `remainder` argument
