### ISSUE TITLE
[ENH] Implement `get_fitted_params` for pipelines and heterogeneous ensembles

### ISSUE THREAD

**Issue by boukepostma** [sktime/sktime#1468]
**Is your feature request related to a problem? Please describe.**
After a BaseForecaster is fitted using model.fit(y_train), we can extract information about the fitted forecaster using forecaster-specific attributes and methods. For example, when AutoARIMA from sktime.forecasting.arima is fitted, we can generate a summary using the summary() method. 
When the same forecaster is used as part of a TransformedTargetForecaster, we can no longer access this information. 

**Describe the solution you'd like**
The fitted BaseForecaster is saved and accessible through .best_estimator_.named_steps['model_name']. In scikit-learn this functionality already exists, as demonstrated in the following example:

```python
from sklearn.decomposition import PCA
from sklearn.linear_model import LogisticRegression
from sklearn.pipeline import Pipeline
from sklearn.model_selection import GridSearchCV

# Define a pipeline to search for the best combination of PCA truncation
# and classifier regularization.
pca = PCA()
# set the tolerance to a large value to make the example faster
logistic = LogisticRegression(max_iter=10000, tol=0.1)
pipe = Pipeline(steps=[('pca', pca), ('logistic', logistic)])

X_digits, y_digits = datasets.load_digits(return_X_y=True)

# Parameters of pipelines can be set using ‘__’ separated parameter names:
param_grid = {
    'pca__n_components': [5, 15, 30, 45, 64],
    'logistic__C': np.logspace(-4, 4, 4),
}
grid = GridSearchCV(pipe, param_grid, n_jobs=-1)
grid.fit(X_digits, y_digits)

# THIS PART DOES NOT WORK SIMILARLY IN SKTIME
logistic_fitted = grid.best_estimator_.named_steps['logistic']
logistic_fitted.coef_
```

**Describe alternatives you've considered**

**Additional context**
Basic example of the desired outcome that now generates an AttributeError: 'NoneType' object has no attribute 'summary':
```python
from sktime.datasets import load_airline
from sktime.forecasting.arima import AutoARIMA
from sktime.forecasting.compose import TransformedTargetForecaster
from sktime.forecasting.model_selection import ForecastingGridSearchCV
from sktime.transformations.series.boxcox import LogTransformer
from sktime.forecasting.model_selection import ExpandingWindowSplitter

y_train = load_airline()

forecaster = AutoARIMA(start_P=1, start_Q=0, sp=1, seasonal=False, suppress_warnings=True)

pipe = TransformedTargetForecaster([
    ('logtrans', LogTransformer()),
    ('forecaster', forecaster),
])

cv = ExpandingWindowSplitter(
    step_length=12, fh=[1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12], initial_window=72
)

param_grid ={'forecaster__information_criterion': ['aic', 'bic']}

grid = ForecastingGridSearchCV(
    forecaster = pipe,
    cv = cv,
    param_grid = param_grid,
)
grid.fit(y_train)

best_forecaster = grid.best_forecaster_.named_steps['forecaster']
best_forecaster.summary()
```

While fitting above `forecaster` directly does give us access to a summary:
```python
forecaster.fit(y_train)
forecaster.summary()
```

P.S. Thanks a lot for the hard work on this great package! 

I'd be happy to help with a PR. That would be my first, so I would very much appreciate some pointers in the right direction :). Very interested to hear what you think about this feature!

**Comment by fkiraly** [comment]
>P.S. Thanks a lot for the hard work on this great package!

You're welcome, much appreciated! 😄 

>I'd be happy to help with a PR.

@aiwalter, can you have a look at this, since it concerns your components?
I thought we already had sth like this?

**Comment by boukepostma** [comment]
What you're proposing, @fkiraly, may be one step more advanced than my proposal. If I understand well, you would like the get_fitted_params interface to return a predefined subset of information from the fitted Estimator that the end user likely wants to obtain. E.g. the .coef_ of an ARIMA model.

I meant to propose to make the full fitted Estimator accessible, without the need to define per Estimator which information should be returned. Then, the end user can decide for him/herself what information to obtain, using attributes and methods of the fitted Estimator. (e.g. using model.coeff_ or model.summary())

**Comment by boukepostma** [comment]
As you mention in #1486, the coefficients of a reduced regressor can be obtained by forecaster.estimator_.coef_ or forecaster.estimators_[0].coef_ 

This is no longer the case when using a Transformedtargetforecaster or GridSearchCV

**Comment by fkiraly** [comment]
Ok, so you have a workaround for this, @boukepostma - should have mentioned that you can just dig into the estimator and get it out - that always works if you know what the attribute is called.

But, this is also a case where `get_fitted_params` would be useful, so changing the title to that.

There is perhaps also a documentation issue here, @aiwalter?

**Comment by fkiraly** [comment]
Update: the `get_fitted_params` interface has been reworked, now there is a separation into `get_fitted_params` (boilerplate) and `_get_fitted_params`.

The correct locus for implementing this functionality would now be in `_HeterogenousMetaEstimator` rather than in the specific pipeline class.
