### ISSUE TITLE
[BUG] dependency bug in tsfresh causing tests to fail

### ISSUE THREAD

**Issue by fkiraly** [sktime/sktime#1478]
Suggested fix:

- [x] set an upper bound on the last `statsmodels` version that still worked in `setup.py`, see #1478
- [x] same for the binder/build requirements
- [ ] wait for `tsfresh` to resolve the issue
- [ ] remove the version bound on `statsmodels` and test whether things run again

---

The CI tests are breaking, due to a `tsfresh` import now fails, which is required for `TSfreshClassifier`.

Error as below.

Looks like this is coming from an interface change in `statsmodels`, as a `tsfresh` dependency?
Where `tsfresh` is calling `stattools.acf` which no longer has an `unbiased` argument in 0.13.0, but used to have?

Not sure how to best fix this, it seems it needs to be fixed in `tsfresh`? Can someone check whether the diagnosis is correct?

```
070     >>> from sktime.classification.feature_based import TSFreshClassifier
071     >>> from sktime.datasets import load_italy_power_demand
072     >>> X_train, y_train = load_italy_power_demand(split="train", return_X_y=True)
073     >>> X_test, y_test = load_italy_power_demand(split="test", return_X_y=True)
074     >>> clf = TSFreshClassifier()
075     >>> clf.fit(X_train, y_train)
UNEXPECTED EXCEPTION: TypeError("acf() got an unexpected keyword argument 'unbiased'")
multiprocessing.pool.RemoteTraceback: 
"""
Traceback (most recent call last):
  File "/opt/_internal/cpython-3.7.12/lib/python3.7/multiprocessing/pool.py", line 121, in worker
    result = (True, func(*args, **kwds))
  File "/opt/_internal/cpython-3.7.12/lib/python3.7/site-packages/tsfresh/utilities/distribution.py", line 43, in _function_with_partly_reduce
    results = list(itertools.chain.from_iterable(results))
  File "/opt/_internal/cpython-3.7.12/lib/python3.7/site-packages/tsfresh/utilities/distribution.py", line 42, in <genexpr>
    results = (map_function(chunk, **kwargs) for chunk in chunk_list)
  File "/opt/_internal/cpython-3.7.12/lib/python3.7/site-packages/tsfresh/feature_extraction/extraction.py", line 337, in _do_extraction_on_chunk
    return list(_f())
  File "/opt/_internal/cpython-3.7.12/lib/python3.7/site-packages/tsfresh/feature_extraction/extraction.py", line 317, in _f
    result = func(x, param=parameter_list)
  File "/opt/_internal/cpython-3.7.12/lib/python3.7/site-packages/tsfresh/feature_extraction/feature_calculators.py", line 404, in agg_autocorrelation
    a = acf(x, unbiased=True, fft=n > THRESHOLD_TO_USE_FFT, nlags=max_maxlag)[1:]
TypeError: acf() got an unexpected keyword argument 'unbiased'
```

**Comment by fkiraly** [comment]
if correct, it may require us to update our dependency version requirements

**Comment by aiwalter** [comment]
yes I have seen this as well, yesterday there was a `statsmodels` release, I guess we have to exclude this until `tshfresh` has fixed this? probably we should report this issue to `tsfresh`?

**Comment by fkiraly** [comment]
what do you mean, thumbs up, @aiwalter - have you confirmed the reason?

**Comment by aiwalter** [comment]
are you going to report this issue to `tsfresh`? Otherwise, I can also open an issue there

**Comment by yairbeer** [comment]
Last version to have unbias is 0.11.1 https://www.statsmodels.org/v0.11.1/generated/statsmodels.tsa.stattools.acf.html

**Comment by fkiraly** [comment]
my diagnosis seems incorrect then!

Thanks for looking into this, @yairbeer - I am at a loss then what is happening, since we had a minimum `statsmodels` of 0.12.1 already?

**Comment by fkiraly** [comment]
... what's going on here?

**Comment by fkiraly** [comment]
is the culprit `tsfresh` then, e.g., have they activated or added some bad code?

Or is sth happening in the reconciliation of package bounds for us?

**Comment by aiwalter** [comment]
no, but they have `statsmodels>=0.9.0` and probably didnt notice a deprecation notice from `statsmodels`.

**Comment by aiwalter** [comment]
so, yes the issue is `tsfresh` but we have to resolve it by excluding recent `statsnodels` version for now

**Comment by fkiraly** [comment]
that wouldn't work, because @yairbeer has localized the `statsmodels` interface change to between 0.11 and 0.12.
But we were using a lower bound of 0.12.1 already on `statsmodels`, and yesterday's update was to 0.13.

So an upper bound of 0.11.1 would conflict with our current lower bound of 0.12.1.

**Comment by aiwalter** [comment]
but before yesterday release its was fine, so excluding this should be the solution

**Comment by fkiraly** [comment]
#1481 just removes the failing tests - it won't fix the `tsfresh` related estimators from failing.

**Comment by fkiraly** [comment]
>but before yesterday release its was fine, so excluding this should be the solution

That's what I thought, but why does #1479 fail then?

**Comment by fkiraly** [comment]
forgot to update the build requirements, notebook installed 0.13.0, let's try again

**Comment by fkiraly** [comment]
ok, work hypothesis is that it was indeed the `statsmodels` upgrade to 0.13.0 that broke things - perhaps there was a silent lapse of deprecation which left it for longer in the code than there was in the docs.

**Comment by fkiraly** [comment]
that seems to have been the cause, since downgrade to 0.12.1 resolved the problem.

**Comment by fkiraly** [comment]
>are you going to report this issue to tsfresh? Otherwise, I can also open an issue there

Yes, I just wanted to do it after we've verified the source (so it's no longer a working hypothesis) but it looks like @wjsi was 3 minutes faster.

**Comment by MatthewMiddlehurst** [comment]
Ah, I see `statsmodels` still has an upper bound #1484

**Comment by MatthewMiddlehurst** [comment]
All `check_estimator(TSFreshClassifier)` tests pass for both the lowest possible and latest versions of `tsfresh` and `statsmodels`, and there is no longer an upper bound for `statsmodels` versioning.
