### ISSUE TITLE
[ENH] implement get_fitted_params for make_reduction forecaster

### ISSUE THREAD

**Issue by asksteph** [sktime/sktime#1486]
This is a feature request with a good idea inside: the reduction strategies called by `make_reduction` should provide access to internal models via the `get_fitted_params` method.

Direct loopthrough does not work though, since `scikit-learn` does not provide a `get_fitted_params` method - however, the fitted estimators could be returned simply.

---

I want to output the regression coefficients from a make_reduction forecaster. The get_fitted_params() gives NotImplementedError: abstract method. I also cannot use the .coef_ attribute to get coefficients like I could on a regular sklearn linear model. Is this the expected behavior? How can we output the fitted parameters?

Advice is greatly appreciated. Thanks!

**To Reproduce**

```python
import numpy as np
import pandas as pd
import statsmodels.api as sm
from sktime.forecasting.model_selection import temporal_train_test_split
from sktime.forecasting.compose import make_reduction
from sklearn.linear_model import LinearRegression

df = sm.datasets.macrodata.load_pandas()['data']
df['q_date'] = df.apply(lambda x: str(int(x['year'])) + '-Q' + str(int(x['quarter'])), axis=1)
df['date'] = pd.PeriodIndex(df['q_date'], freq='Q').to_timestamp()
df = df.set_index('date').to_period("Q")

y = df['realgdp']
y_train, y_test = temporal_train_test_split(y, test_size=30)

regressor = LinearRegression()
forecaster = make_reduction(estimator=regressor, strategy='recursive', window_length=4)
forecaster.fit(y_train)

forecaster.get_fitted_params()
```

**Expected behavior**

**Additional context**

**Versions**
<details>

System:
    python: 3.8.11 (default, Aug  6 2021, 09:57:55) [MSC v.1916 64 bit (AMD64)]
executable: C:\Users\szipk\anaconda3\envs\py38\python.exe
   machine: Windows-10-10.0.19042-SP0

Python dependencies:
          pip: 21.0.1
   setuptools: 52.0.0.post20210125
      sklearn: 0.23.2
       sktime: 0.7.0
  statsmodels: 0.12.2
        numpy: 1.19.5
        scipy: 1.5.4
       Cython: 0.29.14
       pandas: 1.3.3
   matplotlib: 3.1.2
       joblib: 1.0.1
        numba: 0.54.0
     pmdarima: 1.8.2
      tsfresh: 0.18.0
</details>

**Comment by fkiraly** [comment]
more of a feature request than a bug - but I agree it´s a good idea!

**Comment by asksteph** [comment]
Does that mean it may be a while before this will be on the roadmap? Is there a workaround solution for now? 
Thank you,
Stephanie

**Comment by fkiraly** [comment]
I've turned it into a "good first issue", so a member of the community might pick this up and implement it.

Regarding your request: there is, in general, not a single set of coefficients in a reduction forecaster. Even if you are using linear regression inside, the reduced method may end up with multiple trained models inside. You would have to manually implement the `get_fitted_params` for each reduction strategy.

As a workaround - depending on the reduction strategy, you can try `forecaster.estimator_.coef_` or `forecaster.estimators_[0].coef_` and so on - which attributes are present depends on the reduction strategy. Inside, there will be one or multiple copies of the model you wrap. You can see the available attributes by `dir(forecaster)`.
