### ISSUE TITLE
[ENH] Make unit tests for API compliance portable

### ISSUE THREAD

**Issue by mloning** [sktime/sktime#1524]
**Is your feature request related to a problem? Please describe.**
Related issues: #1032 #1505 https://github.com/pytest-dev/pytest/issues/421

**Describe the solution you'd like**
I've sketched out a possible solution here: https://github.com/mloning/minimal-python-project-portable-pytest

Major changes:
* collect estimator tests in classes, one class for the `BaseEstimator` and one for each scitype 
* define test classes discoverable by pytest, inheriting from collection classes, possibly using multiple inheritance

Minor changes:
* add `configure_get_estimators` so that it can be easily reused/configured in companion packages 
* rename `all_estimators` to `get_estimators` for readability
* rename `estimator_instance` to `estimator_object` in line with common class/object distinction and avoiding ambiguity with "instance" as an i.i.d. data sample 

Notes:
* If we use multiple inheritance for the class that collects the tests, we need to make sure that the parent classes have unique method names to avoid overriding methods
* There still is a lot of duplication  in https://github.com/mloning/minimal-python-project-portable-pytest between the base package and companion package, especially regarding `configure_pytest_generate_tests`

**Comment by fkiraly** [comment]
Implemented in the `TestAll` classes and `check_estimator`.
