### ISSUE TITLE
[DOC] Update and improve notebooks for classification

### ISSUE THREAD

**Issue by TonyBagnall** [sktime/sktime#1549]
#### Describe the issue linked to the documentation
Update the classification notebooks along the following lines

1. merge and fix univariate and multivariate

https://github.com/alan-turing-institute/sktime/issues/1536

2. Make the data formatting clearer with use cases for 2D, 3D numpy and dataframes

3. Use rocket and HC2 in examples

4. Include comparison to other algorithms and drawing a CD diagram

other suggestions welcome

**Comment by OliverMatthews** [comment]
With #1536 hopefully fixed now, I'll take a look at point 2 (making the data formatting clearer).

**Comment by MatthewMiddlehurst** [comment]
1, 2 and 3 are done. Unsure if 4 should be included, it should probably be a separate notebook if so. Thoughts @TonyBagnall?

**Comment by TonyBagnall** [comment]
Yes let's do it as another note book
