### ISSUE TITLE
[BUG] `RuntimeError` when `SignatureTransformer` is run on large datasets

### ISSUE THREAD

**Issue by MatthewMiddlehurst** [sktime/sktime#1591]
SignatureTransformer throws a RuntimeError when calling fit on the DuckDuckGeese dataset. I assume this is an issue with the number of dimensions?

```
File "E:\_ProgramFiles\Anaconda3\envs\sktime-workshop-boss\lib\site-packages\esig\backends.py", line 118, in compute_signature
    return tosig.stream2sig(stream, depth)
RuntimeError: Legitimate width 2 <-> 256 exceeded
```

Dataset | Train | Test | Class | Length | Dimension 
-- | -- | -- | -- | -- | -- 
DuckDuckGeese | 50 | 50 | 5 | 270 | 1345

**Comment by MatthewMiddlehurst** [comment]
For some more context, we are running signatures on the whole UEA multivariate archive. I would like to include the method in our future evaluations.

Pinging @jambo6 as they may know more.

**Comment by jambo6** [comment]
This is actually an error thrown by `esig` to help prevent memory errors down the line. 

Signature feature dimension increases exponentially with the input dimension of the data. The input dimension here is `1345`, a signature of `depth=2` would then have on the order of `1345 ** 2` features (nearly 2 million). You can see how this quickly becomes horrible. 

Without additional modifications (e.g. using random projections) signatures do not scale well to large input dimensions. My advice would be to skip any examples where dimension exceeds 256 and chalk signatures down as DNF.

**Comment by MatthewMiddlehurst** [comment]
That's fine, I think these limitations should be noted in the docs, however. Could maybe be handled a bit better than a RuntimeError in the esig package as well, but that's less important. 

I stopped after the first dataset error, but quite a few more also seem to have problems. Some examples:


Dataset | Train | Test | Class | Length | Dimension | Error
-- | -- | -- | -- | -- | -- | --
FingerMovements | 316 | 100 | 2 | 50 | 28 | `RuntimeError: Legitimate depth of 2<->3 for records with width 29 exceeds limit`
Heartbeat | 204 | 205 | 2 | 405 | 61 | `RuntimeError: Legitimate depth of 2<->2 for records with width 62 exceeds limit`
FaceDetection | 5890 | 3524 | 2 | 62 | 144 | `RuntimeError: Legitimate width 2 <-> 256 exceeded`

I assume this is still dimension related, the limit seems to be ~20 ish.

**Comment by sz85512678** [comment]
I encountered the same problem in my work. What I did was to replace the backend of the esig by iisignature in _compute(see https://github.com/datasig-ac-uk/esig), which can handle paths with more dimensions. Note that this requires iisignature, in addition to esig, to be installed on your machine. Happy to write a patch for this issue if that's useful.

**Comment by fkiraly** [comment]
> Happy to write a patch for this issue if that's useful.

Sure, that would be appreciated!

Do you have any insight on the conditions for the runtime error to surface?

**Comment by sz85512678** [comment]
> > Happy to write a patch for this issue if that's useful.
> 
> Sure, that would be appreciated!
> 
> Do you have any insight on the conditions for the runtime error to surface?

Okay, I can start working on that. 

Yes, from my experiment the error seems to surface whenever the dimension of the original time series is larger than 24/25, as @MatthewMiddlehurst has noted.
