### ISSUE TITLE
[ENH] Fix estimators in the EXCLUDE_ESTIMATORS category in unit tests

### ISSUE THREAD

**Issue by TonyBagnall** [sktime/sktime#1627]
currently the following classifiers do not undergo the full suite of tests

EXCLUDE_ESTIMATORS = [
    "ProximityForest",
    "ProximityStump",
    "ProximityTree",
]
this is undesirable, the classifiers should be made to conform and be properly assimilated or they should die.      done:
"ElasticEnsemble", "ShapeDTW

**Comment by TonyBagnall** [comment]
ShapeDTW fails on a parameter check.
EE passes, but is fearful slow

**Comment by TonyBagnall** [comment]
testing on my as yet unmerged branch. PF family fail 8 tests. 

ProxStump fails test_fit_idempotent, slightly concerningly!
PF, PS, PT all fail test_fit_does_not_overwrite_hyper_params, test_persistence_via_pickle, test_multiprocess_idempotent

I think some of these will be solved by fit/fit refactor.

**Comment by TonyBagnall** [comment]
> ShapeDTW fails on a parameter check. 

caused by a typo in the constructor, American and correct spelling mixup 
![image](https://user-images.githubusercontent.com/9594042/142621009-ee60c8d2-d17d-4009-aefa-ff976be082df.png)

**Comment by TonyBagnall** [comment]
ShapeDTW has been removed from the list

**Comment by fkiraly** [comment]
> classifiers should be made to conform and be properly assimilated or they should die.

Not how I would have formulated it exactly, but I support the underlying sentiment.

**Comment by fkiraly** [comment]
> American and correct spelling mixup

Indeed, the tests fail whenever one does not use Her Majesty's English as one properly should.

**Comment by fkiraly** [comment]
the mentioned estimators are no longer fully skipped.

Partial skips are in https://github.com/sktime/sktime/issues/2490, closing in favour of that issue.
