### ISSUE TITLE
[ENH] Separate the tests for soft and hard dependences in test_all_estimators and test_panel_estimators

### ISSUE THREAD

**Issue by TonyBagnall** [sktime/sktime#1639]
**Is your feature request related to a problem? Please describe.**

running test_all_estimators requires all of the soft dependencies be installed. This is annoying when new ones are introduced, particularly when reinstalling all_extras causes fbprophet to reinstall wrong versions of things and it all needs resetting.  I am getting strange bugs with the testing results passing locally but not on the repo, so need to do some testing, but would rather not deal with fpbprophet and  dtw_python issues. It would also speed up my development time, testing takes an age

**Describe the solution you'd like**
I would like to be able to run tests locally on hard and soft dependency modules with test_all_estimators and test_all_panel_estimators. Simply splitting the files and iterating over different lists would be fine.

 
**Describe alternatives you've considered**
I can locally hack out the tests into a separate file, but would rather not

**Comment by lmmentel** [comment]
One way to do it might be by _marking_ the relevant tests https://docs.pytest.org/en/6.2.x/example/markers.html#mark-examples, let's say with a `core` and `extra` or `all_extras` to match the pip flag. It might not be optimal to implement since I saw that a lot of the test are parameterized and don't always distinguish between dependency sets.

**Comment by fkiraly** [comment]
Hmmm - if we introduce `pytest_generate_tests` throughout, we could inside separate by estimators with extra dependencies or not.

**Comment by fkiraly** [comment]
@TonyBagnall, on the current code base, this could be solved by a combination of the `check_estimator` utility and `registry.all_estimators` if we were to introduce a tag for dependency.

Should we introduce a tag for dependency?

**Comment by TonyBagnall** [comment]
I dont think this issue is relevant anymore, the testing has completely revised and fbprophet has been sorted out, so I will close this
