### ISSUE TITLE
[ENH] Add holiday transformer 

### ISSUE THREAD

**Issue by mloning** [sktime/sktime#1675]
**Is your feature request related to a problem? Please describe.**
While there is a `DateTimeFeatures` transformer to get date/time features from a time series (see https://github.com/alan-turing-institute/sktime/issues/1273), we don't have a transformer for handling holidays. 

**Describe the solution you'd like**
A `HolidaysFeatures` transformer that creates dummies for holidays based on a date-time index.

**Comment by mloning** [comment]
I'm working on this.

**Comment by mloning** [comment]
Someone else can take this if interested, some preliminary work is in #1722

**Comment by VyomkeshVyas** [comment]
I'm working on this.
