### ISSUE TITLE
[ENH] Add Fourier featurizer

### ISSUE THREAD

**Issue by mloning** [sktime/sktime#1693]
**Is your feature request related to a problem? Please describe.**
There is no Fourier featurizer to model seasonality in forecasting pipelines.

**Describe the solution you'd like**
Add a `FourierFeatures` transformer, similar to the `DateTimeTransformer` (#1273)

**Additional context**
Related issues: #1675

**Comment by fkiraly** [comment]
implemented in https://github.com/sktime/sktime/pull/3374
