### ISSUE TITLE
[ENH] Probability Distributions in probabilistic forecasters

### ISSUE THREAD

**Issue by kejsitake** [sktime/sktime#1746]
**Is your feature request related to a problem? Please describe.**

We are currently working on refactoring the forecasting interfaces to allow probabilistic and interval predictions as described here https://github.com/alan-turing-institute/sktime/issues/1687 and a high level summary included here https://github.com/sktime/enhancement-proposals/blob/main/steps/13_proba_forecasting/step.md

**Describe the solution you'd like**

We would like to include a way to return the probability distributions. We briefly discussed using methods from tensorflow, but are open to other suggestions.

**Potential issues**
This would introduce a new dependency.

**Comment by fkiraly** [comment]
The STEP suggests `tensorflow-probability`, but other options are `pytorch` and probabilistic programming languages.

The key requirement is that we don't just want to sample from them, but call functions like `pdf`, `cdf`, etc, and vectorize over them.

**Comment by kejsitake** [comment]
Notes on this topic from meeting with @ltsaprounis @eenticott-shell @fkiraly 

The things we need from the new dependency are:
- symbolic representation of return distributions
- methods pdf, cdf, quantile (of distributions)
- composability of distributions
- optimally: vectorization of pdf, cdf calls and parameter constructor

Options we are looking at are:
- [ ] tensorflow-probability
- [ ] pytorch
- [ ] pyro
- [ ] pymc3

**Comment by fkiraly** [comment]
Done in https://github.com/alan-turing-institute/sktime/pull/2100

**Comment by fkiraly** [comment]
reopening this - `tensorflow-probability` has proven clunky to use, and a heavy dependency (>300MB in the env!) just for users who want probabilistic forecasting.

I think we need to move to a back-end agnostic approach.

**Comment by fkiraly** [comment]
STEP is here:
https://github.com/sktime/enhancement-proposals/pull/31

prototype:
https://github.com/sktime/sktime/pull/4190

**Comment by fkiraly** [comment]
closing in favour of https://github.com/sktime/sktime/issues/1746
