### ISSUE TITLE
[BUG] `ValueError` when using `TSFreshRelevantFeatureExtractor` related to `impute_function` argument in a case where no imputation is needed or intended

### ISSUE THREAD

**Issue by curtisraymond** [sktime/sktime#1824]
**Describe the bug**

It appears as though the **impute_function** parameter within the **TSFreshRelevantFeatureExtractor** function isn't working as it should be. My custom **impute_dataframe_zero** function for the **impute_function** parameter  should be converting all the NAN values to 0.

![1](https://user-images.githubusercontent.com/57142499/148068121-ace40e35-b57b-4f61-9f03-3ff3d9acd1e2.png)
![3](https://user-images.githubusercontent.com/57142499/148068134-575503fd-1200-423b-9223-17248728078d.png)
![2](https://user-images.githubusercontent.com/57142499/148068143-ba1dbab5-ddd4-4c93-896d-d3ab35770023.png)

**Versions**
<details>

System:
    python: 3.8.5 (default, Sep  3 2020, 21:29:08) [MSC v.1916 64 bit (AMD64)]
executable: C:\Users\curtis\anaconda3\python.exe
   machine: Windows-10-10.0.22000-SP0

Python dependencies:
          pip: 20.2.4
   setuptools: 50.3.1.post20201107
      sklearn: 1.0.1
       sktime: 0.8.1
  statsmodels: 0.13.1
        numpy: 1.20.3
        scipy: 1.7.1
       Cython: 0.29.26
       pandas: 1.3.3
   matplotlib: 3.3.2
       joblib: 1.1.0
        numba: 0.51.2
     pmdarima: None
      tsfresh: 0.19.0

</details>

**Comment by fkiraly** [comment]
Thanks, can you kindly provide some code that we can run to reproduce this?

On a superficial glance, it seems like this is an issue with `tsfresh` that is interfaced here, and not with the `sktime` interface?

To "safely" impute, I'd suggest you use a pipeline where you *first* run the `sktime` imputer, `sktime.transformations.series.Imputer`, then the `tsfresh` extractor.

**Comment by curtisraymond** [comment]
It's first worth mentioning that my data set (before running it through the pipeline) does not contain any missing values. Anyway, I tried your suggestion of adding the `sktime` imputer before the `TSFreshRelevantFeatureExtractor` function but I'm still running into the same `ValueError: Column must not contain NaN values: value` error.  

From my understanding the `TSFreshRelevantFeatureExtractor` function combines both the `tsfresh.extract_features` and the `tsfresh.transformers.feature_selector` methods together. Running different scenarios I have figured out that the NaN values are being generated from within the `tsfresh.extract_features` stage and that the `ValueError: Column must not contain NaN values: value` error is coming from within the `tsfresh.transformers.feature_selector` method. 

It appears as though sktime's `TSFreshRelevantFeatureExtractor` function has a `impute_function` parameter built into the `TSFreshRelevantFeatureExtractor` function but when I try to use it, it doesn't seem like this parameter does anything. Also, looking at the tsfresh documentation I don't see any "impute" parameters within either the `tsfresh.extract_features` and the `tsfresh.transformers.feature_selector` methods.  Therefore, I am assuming this is an added parameter by the sktime team. Is this true?

**Comment by fkiraly** [comment]
>It's first worth mentioning that my data set (before running it through the pipeline) does not contain any missing values.

Wait, it doesn't? Then I don't fully understand what's going on.

Can you then, kindly, post a minimal example of code that we can run to verify this?

Pinging @Ayushmaanseth, @mloning, @alwinw who are listed as authors on the `TSFreshRelevantFeatureExtractor`.

**Comment by curtisraymond** [comment]
Here is my script and also my data sets:
[sample.zip](https://github.com/alan-turing-institute/sktime/files/7816907/sample.zip)

The script is not really "minimal" but I specifically receive the error within the 3rd iteration of the last cell's "for loop".

**Comment by fkiraly** [comment]
Would you kindly mind providing us with a single cell of code, using markdown code block? Without imports or notebook. 
So we can copy-paste and run (I expect multiple people will have to look at this, so let's make it as easy as possible). Gist also works.

**Comment by fkiraly** [comment]
(sorry to ask for this ... if you look at the bugfixing board https://github.com/alan-turing-institute/sktime/projects/18#card-75567601 there's a lot on our plate. Taking 30 min, multiplied by number of people investigating, off this bug report really makes a difference here. It is much appreciated if you can help cut it down so we can start working on it more easily)

**Comment by MatthewMiddlehurst** [comment]
We do not do anything with `impute_function`, just pass it directly to `tsfresh`. I tend to agree that this is not a problem we can readily fix if it is one.

I can run the following code without issue on the same version of `tsfresh` (not that it verifies the function is actually doing anything), so maybe the problem lies elsewhere?

```
import numpy as np

from sktime.datasets import load_basic_motions
from sktime.transformations.panel.tsfresh import TSFreshFeatureExtractor, \
    TSFreshRelevantFeatureExtractor

def impute_dataframe_zero(df_impute):
    """
    Replaces all ``NaNs``, ``-infs`` and ``+infs`` from the DataFrame `df_impute` with 0s.
    The `df_impute` will be modified in place. All its columns will be into converted into dtype ``np.float64``.

    :param df_impute: DataFrame to impute
    :type df_impute: pandas.DataFrame

    :return df_impute: imputed DataFrame
    :rtype df_impute: pandas.DataFrame
    """
    if len(df_impute) == 0:
        return df_impute

    df_impute.replace([np.PINF, np.NINF], 0, inplace=True)
    df_impute.fillna(0, inplace=True)

    # Ensure a type of "np.float64"
    df_impute.astype(np.float64, copy=False)
    return df_impute


if __name__ == "__main__":
    X_train, y_train = load_basic_motions(split="train")

    ts1 = TSFreshFeatureExtractor(show_warnings=False, disable_progressbar=True, impute_function=impute_dataframe_zero)
    print(ts1.fit_transform(X_train, y_train))

    ts2 = TSFreshRelevantFeatureExtractor(show_warnings=False, disable_progressbar=True, impute_function=impute_dataframe_zero)
    print(ts2.fit_transform(X_train, y_train))
```

If there are no more comments on this issue after a while I will close it, so do post if you are interested in keeping it open.
