### ISSUE TITLE
[DOC] How to contribute docs

### ISSUE THREAD

**Issue by chrisholder** [sktime/sktime#1925]
#### Describe the issue linked to the documentation

Since updating our cicd the to contribution document hasn't been updated so now I don't know how to reinstall my dev version of sktime.

For example here: https://www.sktime.net/en/stable/get_involved/contributing.html#continuous-integration
there are the steps given:

![image](https://user-images.githubusercontent.com/4674372/150871658-244a1151-d68d-4fcb-a36a-69add87310d4.png)

However, build_tools/requirements.txt doesnt exist anymore.

#### Suggest a potential alternative/fix

Update.

**Comment by fkiraly** [comment]
What do you mean, "the hot"?

**Comment by lmmentel** [comment]
Hi @chrisholder, the docs were updated however the link you are referring to points to `stable` i.e. last tagged/release version of the docs. If you want to access the most recently build docs you need to go the `latest` i.e. https://www.sktime.org/en/latest/installation.html notice the difference in the url after  https://www.sktime.org/en/.

**Comment by fkiraly** [comment]
Hm, should we add a remark on the top of the contribution related pages that `latest` may be correct in a situation where a recent update to the dev installation, CI, or release process has happened? But that would probably be quite rare?

**Comment by fkiraly** [comment]
has ben updated in 2022.
