### ISSUE TITLE
[ENH] Improvements to estimator overview

### ISSUE THREAD

**Issue by fkiraly** [sktime/sktime#1930]
`sktime` currently has a nice estimator overview table which allows for searching estimators by type.

A couple things would be nice to have and nice to do:

- [x] add proper sub-setting by column value ranges, e.g., "show me all forecasters". Currently this is just done by substring search, so users can't see easily what the possible values are.
- [x] add display of tags. There may be some design that has to be done, since a display of 10-20 tags may blow up the table. E.g., a sub-selection has to be made, or that display may have to fold somehow to avoid having giant cells.
- [x] allow easy subsetting and search by tags, e.g., "show me all multivariate forecasters". Currently, this can be done using `all_estimators`, but not via the table.
- [ ] add more tables *like* the estimator overview, which allow to list tags, or types of estimators. This table could be also linked from the estimator table. These tables already exist in the `registry` module, as output of `all_tags`, or as `BASE_CLASS_REGISTER`.
- [x] remove the legacy `ESTIMATOR_OVERVIEW.md` and replace it with a link to the current estimator overview.
- [x] ideas from the legacy `ESTIMATOR_OVERVIEW.md` which have not made it into the current estimator. Algorithm owners (from CODEOWNERS files); primary publication reference; listing reduction with a type that is "from" and "to". For each of these, there probably needs to be a bit of design how it should look like (and not clutter the tables).

The current estimator table is generated via `source.conf._make_estimator_overview`, which can be used as starting point.

**Comment by EMUL8ER** [comment]
Hi I am a beginner I would like to contribute in this issue, could u point me the way to do so?

**Comment by fkiraly** [comment]
> Hi I am a beginner I would like to contribute in this issue, could u point me the way to do so?

Sure!

I think the main places would be:
* `source.conf._make_estimator_overview` to generate the current table
* `registry.all_estimators`, `registry.all_tags` utilities
* documentation guidelines on doc build, https://www.sktime.org/en/latest/developer_guide/documentation.html#documentation-build

**Comment by jaivanti** [comment]
Hi! Can I contribute to this?

**Comment by jaivanti** [comment]
Hello! So sorry was stuck with exams....Just wanted to know ...That, Will a google Doc file work for this documentation?

**Comment by duydl** [comment]
I just checked the `sktime/registry/_tags.py` and there seemed to be a lot. The current info from the table is all extracted from the registry module in `docs/source/conf.py`. So I think instead of generating md then HTML file, we could export all registry data into a db format and then display it interactively on the page.

**Comment by fkiraly** [comment]
> So I think instead of generating md then HTML file, we could export all registry data into a db format and then display it interactively on the page.

The function `registry.all_tags` is meant to do that, as the connection point to whichever GUI/display we choose. Would appreciate your opinion on whether that's convenient enough?

**Comment by duydl** [comment]
I constructed a json from all_tags() and all_estimator(). Could you check if it is appropriate?  
[estimator_overview_db.json](https://github.com/sktime/sktime/files/14560845/estimator_overview_db.json)

**Comment by fkiraly** [comment]
done by @duydl and others
