### ISSUE TITLE
[BUG] Fix or remove `colalign` arg in `ScipyDist`

### ISSUE THREAD

**Issue by fkiraly** [sktime/sktime#1942]
The docstring of `ScipyDist` has a `colalign` argument, but in fact it is not internally used in `_transform`.
Columns are also not aligned with each other if they appear in different order, in `X` and `X2`.

Hence, the argument should either be removed, or - better - the described functionality should be added.

Currently, columns are not being aligned, which will lead to unexpected and hard-to-detect incorrect behaviour, given the docstring.

**Comment by Saransh-cpp** [comment]
Hi, @fkiraly!

Can I work on this issue? I plan on implementing the functionality described in the docstring in the `ScipyDist` class.

**Comment by fkiraly** [comment]
sure, thanks! all yours.
