### ISSUE TITLE
[ENH] single problem loaders: what should the return format be (and how many)?

### ISSUE THREAD

**Issue by TonyBagnall** [sktime/sktime#1983]
this is for discussion really, if its not thought a good idea I will scrap it. Currently, the data loaders in _single_problem_loaders either return a pd.Series or a nested pd.DataFrame. I would like to change this so that they return the best data structure for the problem: for multiple instance problems (aka panel data), univariate equal length should return 2D numpy, multivariate equal length 3D numpy, unequal length should return nested pandas.

This is part of my general push to reduce entry barriers to classification. Nested dataframes confuse people, and now all classifiers and clusterers can handle numpy through their base classes, and the data loader is configurable via load_from_tsfile, would like to promote numpy use where ever possible.

**Comment by fkiraly** [comment]
I agree with the sentiment and original observation, that confusion may be caused by the current setting.

*However* I would argue that the resulting data type should be (a) a common format, and (b) always the same.

This is in line with recent discussion on "one output type" design.
Also, the user would be confused wny in one case they get a `pandas`, in another case they get `numpy3D`, if they call the same function on the same file type.

So, I would suggest to present the loaded data *always* in `pd-multiindex` mtype format.

**Comment by TonyBagnall** [comment]
its not the same function though, it is a problem specific function and they are already polymorphic in return type. Some return pd.Series, some pd.DataFrame. I am in favour of encouraging numpy arrays where ever possible. I dont want to use pd-multiindex.

**Comment by TonyBagnall** [comment]
I have conceded the polymorphic return types for load_ts, despite wanting it quite a lot. However, load_gunpoint, for example, should return a 2d numpy array, as that is the best container for the data. Why would anyone be confused by that? They can pass it to a classifier. It seems much more confusing to return some obscure nested data frame or a pd-multiindex. Everyone knows numpy

**Comment by TonyBagnall** [comment]
but that already happens! Some loaders return Series, some DataFrames, which are not the same data structure. If you understand what the data represents, which you really should if you are loading it, you understand the differences. However, I am not willing to argue this again, I will just gibve it as an option and default to DataFrame. Is that acceptable?

**Comment by fkiraly** [comment]
>I will just give it as an option and default to DataFrame. Is that acceptable?

Yes, sure! That would work!

**Comment by TonyBagnall** [comment]
this is how data loading now works, so I am closing this issue. 
![image](https://user-images.githubusercontent.com/9594042/194015833-370bfbc2-4a5a-4908-8290-4efdb270946e.png)
