### ISSUE TITLE
[DOC] fix broken "unix-like OS" link in docs

### ISSUE THREAD

**Issue by TonyBagnall** [sktime/sktime#2017]
update: with the below, this just needs to fix the broken link "Unix-like OS"

---

two things:
https://www.sktime.org/en/stable/installation.html#id17

the double use of install is wrong (at least on my machines), should be 
conda install -c conda-forge pystan

and also the link to [`Unix-like OS`](https://www.sktime.org/en/stable/installation.html#id17) goes nowhere. 

![image](https://user-images.githubusercontent.com/9594042/152854981-230f9a76-416b-4708-8508-97476ad77895.png)

**Comment by lmmentel** [comment]
The double `install` is already fixed https://www.sktime.org/en/latest/installation.html#id17

**Comment by youssefkhalil320** [comment]
Hello, I wanna contribute to this. Also please provide me the link should [Unix-like OS] refers to and if you can give me a guide how to contribute because I am new.

**Comment by mihirneal** [comment]
Hey, I'd like to work on this issue. Could you assign this to me?

**Comment by fkiraly** [comment]
Related to this
https://github.com/alan-turing-institute/sktime/issues/2329
there does not seem to be a section this points to.

Removing the "good first issue" tag since it does not seem obvious what the fix should be (see #2329)

**Comment by fkiraly** [comment]
independently spotted by @julia-kraus recently and removed
