### ISSUE TITLE
[DOC] adding dataset instructions not very comprehensive, and incorrect for new file extensions

### ISSUE THREAD

**Issue by fkiraly** [sktime/sktime#2019]
The "adding datasets" page is a bit brief/incomprehensible, and it also misses the `MANIFEST.in` for adding files with new extensions, see the discussion here in the PR.

This should be improved.

Current "adding datasets" documentation:
https://www.sktime.org/en/stable/developer_guide/add_dataset.html

**Comment by chicken-biryani** [comment]
Hey, can I work on this?

**Comment by fkiraly** [comment]
Sure, @chicken-biryani!
I would also advise you also link up with @rakshitha123, who recently tried to add a new dataset - she should have direct experience with trying to make use the docs, so might be able to advise how to improve them.

**Comment by rakshitha123** [comment]
We need to follow the steps available at https://www.sktime.org/en/stable/developer_guide/add_dataset.html to add a new dataset.

In particular, if the dataset has a new extension which has not been previously used in the sktime context, then the extension needs to be added to MANIFEST.in.

**Comment by miraep8** [comment]
Just wondering if this issue would be a good one to add to our upcoming doc sprint! :) If it hasn't been fully resolved yet is it ok if I add it to a "still open" list?

**Comment by fkiraly** [comment]
yes, sounds like a good first issue!

I think this has been abandoned since last activity is Feb.

**Comment by templierw** [comment]
Hello,
If it is still open, I shall have a look!
