### ISSUE TITLE
[BUG] in colab, pip install sktime hangs after statsmodels download for `scipy=1.8.0`

### ISSUE THREAD

**Issue by oguiza** [sktime/sktime#2033]
Update by @fkiraly: the issue seems to be resolved by the introduction of the upper bound `scipy<1.8.0` in `sktime` v0.10.1, as suspected. The bug is probably still there for `scipy 1.8.0`, and we should understand how to resolve it in order to relax the upper bound again.

---
**Describe the bug**

I've tried to pip install sktime in Google Colab but it hangs and installation doesn't complete

**To Reproduce**

```python
!pip install sktime
```

**Expected behavior**

**Additional context**

The issue seems to be related to the upgrade of statsmodels to 0.13.2.
However, I can run:
```python
!pip install statsmodels
```
which correctly installs that version of the library

**Versions**
<details>

Collecting sktime
  Downloading sktime-0.10.0-py3-none-any.whl (6.4 MB)
     |████████████████████████████████| 6.4 MB 8.0 MB/s 
Collecting numpy<1.22,>=1.21.0
  Downloading numpy-1.21.5-cp37-cp37m-manylinux_2_12_x86_64.manylinux2010_x86_64.whl (15.7 MB)
     |████████████████████████████████| 15.7 MB 59.5 MB/s 
Requirement already satisfied: scikit-learn>=0.24.0 in /usr/local/lib/python3.7/dist-packages (from sktime) (1.0.2)
Requirement already satisfied: pandas<1.5.0,>=1.1.0 in /usr/local/lib/python3.7/dist-packages (from sktime) (1.3.5)
Collecting deprecated>=1.2.13
  Downloading Deprecated-1.2.13-py2.py3-none-any.whl (9.6 kB)
Collecting statsmodels>=0.12.1
  Downloading statsmodels-0.13.2.tar.gz (17.9 MB)
     |████████████████████████████████| 17.9 MB 583 kB/s

**Comment by fkiraly** [comment]
Thanks for reporting this, @oguiza!

Can you kindly let us know what exactly happens in colab?
I just started it, and for me it seems to hang after `statsmodels`.

**Comment by fkiraly** [comment]
`pip install sktime -v` should help diagnose it, but there´s a lot of output to go through...

**Comment by oguiza** [comment]
> Thanks for reporting this, @oguiza!
> 
> Can you kindly let us know what exactly happens in colab? I just started it, and for me it seems to hang after `statsmodels`.

Same thing for me. 
I reported it in the details section of the bug description.

**Comment by fkiraly** [comment]
@oguiza, `sktime` should run again in colab in v0.10.1.
We haven't tracked down the root cause or its location, but the upper bound on `statsmodels` seems to have done the trick.

**Comment by oguiza** [comment]
Thanks for the info @fkiraly. I've tested it too and it's resolved.

**Comment by fkiraly** [comment]
welllllll - not entirely resolved. The problem is probably still there if you remove the `scipy<1.8.0` bound, and the reason for that is not entirely inderstood. I'll re-open this issue since we need to ensure that we don't have the problem with `scipy 1.8.0` and higher.

**Comment by oguiza** [comment]
I understand. 
I just closed it as the issue as originally described no longer occurs. You can now pip install sktime in Colab.

**Comment by fkiraly** [comment]
> I just closed it as the issue as originally described no longer occurs. You can now pip install sktime in Colab.

Yes, and that was perfectly fair - when I reopened it, I changed the title, since what remains is to sort it out under `scipy=1.8.0`. I could have opened a new issue, but I thought it's better to have it in one place since it's still the same problem.
