### ISSUE TITLE
[ENH] file format specification for ts and tsf

### ISSUE THREAD

**Issue by fkiraly** [sktime/sktime#2043]
We should have file format specifications for the `ts` and `tsf` files used in `sktime`.

The speifications can be linked (if exist elsewhere), or part of `sktime`.

Update:
from #3303, there seem to be inconsistencies in the code in referencing `@classlabels` vs `@class_labels`, and `@equallength` vs `@equalLength`.

**Comment by fkiraly** [comment]
putting this on the benchmarking workstream since that´s what the benchmark data sets are going to be in (probably?)

**Comment by fkiraly** [comment]
FYI @paulbauriegel, @achieverordie, @TNTran92.

Related discussion: https://github.com/alan-turing-institute/sktime/pull/3303
write/load were inconsistent since they seemed to assume minimally different format specificaitons (identifier strings).

I think we should document the file format properly.

@paulbauriegel, @achieveordie, you looked recently into loaders/writers, so you are probably the resident experts on the ts, tsf file formats? The original authors have disengaged, unfortunately.

The output could be a formal rst page in the docs - or a markdown, if rst is too much of a hassle. We can convert it to "nice" doc format later, I feel it would be key to have the format written down somewhere or we will keep discovering bugs like #3303 ...

**Comment by paulbauriegel** [comment]
It should be noted that the current implementation supports both `@classlabel` and `@classLabel` due to 

```python
line = line.strip().lower()
```

in `_read_header` (line 247) in `sktime/datasets/_data_io.py`. 

As @fkiraly mentioned there is no common standard for instance most datasets from [tseregression.org](http://tseregression.org/) like `AppliancesEnergy` uses all lowercase notation. 
And most classification datasets from [www.timeseriesclassification.com](http://www.timeseriesclassification.com/index.php) like `ArrowHead`  use the CamelCase notation. The `UnitTest` dataset for this module does also use CamelCase.

I think this is because all the classification datasets where made for this code initially: https://github.com/uea-machine-learning/tsml/blob/master/src/main/java/experiments/data/TSReader.java

And the regression datasets where made for this library initially: https://github.com/ChangWeiTan/TS-Extrinsic-Regression/blob/master/utils/data_loader.py

**Comment by paulbauriegel** [comment]
I checked all datasets from here: [Regression](https://zenodo.org/record/3902651) & [Classification](http://www.timeseriesclassification.com/dataset.php). I don't understand the specification completely but this is what I got so far:

### Specification for Regression datasets

|metadata name |data type|comment|
|--------------|----------|----------|
|`@problemname`|`string`     |Name of the data-set|
|`@timestamps`|`false`/`true`|Contains a time-series column|
|`@missing`|`false`/`true`|Contains missing values|
|`@univariate`|`false`/`true`|One variable data-set|
|`@dimension`|`integer`|Only if `univariate=false`, specifies the number of variables |
|`@equallength`|`false`/`true`|All observations have the same number of timestamps |
|`@serieslength`|`integer`|Only if `equallength=true`, specifies the number of timestamps |
|`@targetlabel`|`false`/`true`| Has a target label |


### Specification for Classification datasets

|metadata name |data type|comment|
|--------------|----------|----------|
|`@problemName`|`string`     |Name of the data-set|
|`@timeStamps`|`false`/`true`|I've only seen it false in all the classification datasets|
|`@missing`|`false`/`true`|Contains missing values, I've only seen it false in all the classification datasets|
|`@univariate`|`false`/`true`|One variable data-set|
|`@dimensions`|`integer`|Only if `univariate=false`, specifies the number of variables |
|`@equalLength`|`false`/`true`|All observations have the same number of timestamps |
|`@seriesLength`|`integer`|Only if `equallength=true`, specifies the number of timestamps |
|`@classLabel`|`false`/`true` - **if classLabel=true* `list[string, space seperated]`  | Has/Hasn't a class column - if yes specification of possible class label values (list of space separated strings) |

### Key differences in the datasets
- `dimension` vs `dimensions`
- `targetlabel` vs `classLabel`
- `lowercase` vs `camelCase`
- `@data` field is structured differently

**Comment by fkiraly** [comment]
@paulbauriegel, very helpful!

Looks like we will have to work with aliases here, to agree with all existing data files - apparently they have been handled inconsistently

> `@data` field is structured differently

How is the `@data` field structured?

Other questions:
Can the data format currently store:

* the time index for a collection of time series of different length, or with different index set?
* a single time series (in constrast to a collection with 1 instance)
* a hierarchical index

?

**Comment by paulbauriegel** [comment]
Will try to answer those questions in detail as soon as I get to it. Linking existing documentation on the topic here for now:
- https://github.com/alan-turing-institute/sktime/blob/main/examples/loading_data.ipynb
- https://github.com/alan-turing-institute/sktime/blob/main/examples/AA_datatypes_and_datasets.ipynb
