### ISSUE TITLE
[ENH] Adding DynamicFactor from statsmodels as a forecaster

### ISSUE THREAD

**Issue by aiwalter** [sktime/sktime#2059]
**Is your feature request related to a problem? Please describe.**
Adding `DynamicFactor` from `statsmodels` as a forecaster. 

https://www.statsmodels.org/devel/generated/statsmodels.tsa.statespace.dynamic_factor.DynamicFactor.html
**Describe the solution you'd like**
Using the class `_StatsModelsAdapter ` to add this forecaster, should be straight forward and equivalent to other forecasters that already inherit from this class.

**Comment by Ris-Bali** [comment]
@aiwalter  Can I work on this ? .  It should have similar structure to `https://github.com/alan-turing-institute/sktime/blob/main/sktime/forecasting/exp_smoothing.py` which also inherits from _StatsModelsAdapter right ?

**Comment by aiwalter** [comment]
@Ris-Bali sure, yes exactly. Also it might help to look into the enhancement template: https://github.com/alan-turing-institute/sktime/blob/main/extension_templates/forecasting.py

**Comment by fkiraly** [comment]
@Ris-Bali, the latest sktime docs include detail instructions on how to add estimators:
https://www.sktime.org/en/latest/developer_guide/add_estimators.html

**Comment by fkiraly** [comment]
was finished by @lbventura in https://github.com/sktime/sktime/pull/2859 but we forgot to close the issue
