### ISSUE TITLE
[DOC] write proper docstrings for `tsfresh` interface estimators

### ISSUE THREAD

**Issue by fkiraly** [sktime/sktime#2073]
The two `tsfresh` interfaces do not have proper docstrings, these should be written. The estimators in question are:
- [ ] `TSFreshFeatureExtractor`, and 
- [ ] `TSFreshRelevantFeatureExtractor`.

The docstring should point to the methods in `tsfresh` interfaced, and can translate the parameters 1:1 from `tsfresh` docstrings.
For `TSFreshRelevantFeatureExtractor`, the method of identifying relevant features needs to be described in addition

**Comment by MatthewMiddlehurst** [comment]
Docstrings for both classes were added in #3636 and #3785.
