### ISSUE TITLE
[BUG] `AutoARIMA.predict` fails on `np.ndarray` `fh` argument

### ISSUE THREAD

**Issue by kifbell** [sktime/sktime#2120]
Hello!

I use sktime.forecasting.arima.AutoARIMA to fit and predict time series 
(the model is already fitted )

However, when  want to pass my **np.array** of points as fh argument of  sktime.forecasting.arima.AutoARIMA.predict, it says
AttributeError: The `freq` attribute of the time index is required, but found: None. Please specify the `freq` argument when setting the time index.

I've tried to set .freq = '1722S' explicitly (all successive points have the same relative delta) -> same issue

points to predict:
                 ...        
780757   2014-01-30 21:30:00
780758   2014-01-30 21:58:42
780759   2014-01-30 22:27:24
780760   2014-01-30 22:56:06
780761   2014-01-30 23:24:48
Name: ds, Length: 301, dtype: datetime64[ns]

please, tell me how I should fix it

**Comment by fkiraly** [comment]
@KIFBELL, sounds a little odd - can you kindly post some code that reproduces the issue, and your `sktime` version?

**Comment by mrtkp9993** [comment]
Hello, I have similar problem. I am on sktime 0.10.1. Here is the example code and data [t1.csv](https://github.com/alan-turing-institute/sktime/files/8311221/t1.csv):

````python
df = pd.read_csv("t1.csv", index_col=0, parse_dates=True, infer_datetime_format=True)
df.dropna(axis=1, how='all', inplace=True)
y_train, y_test = temporal_train_test_split(df, test_size=0.1)
plot_series(y_train, y_test, labels=["y_train", "y_test"])
fh = ForecastingHorizon(y_test.index, is_relative=False)
d = ndiffs(y_train, max_d=10, test="adf")
D = nsdiffs(y_train, m=12, max_D=10, test="ch")
model = AutoARIMA(d=d, D=D, max_order=10, maxiter=100, n_fits=100, trace=True)
model.fit(y_train)
model.predict(fh)
```

**Comment by fkiraly** [comment]
@mrtkp9993, thanks for posting the code!

Can you kindly post code that does not include an external file? E.g., can you please replace the `read_csv` with either an explicit construction of a `pandas.DataFrame`, or sth like `load_airline`?

**Comment by fkiraly** [comment]
closed for inactivity
