### ISSUE TITLE
[ENH] add tests for classifier compatibility with scikit model selection

### ISSUE THREAD

**Issue by TonyBagnall** [sktime/sktime#2132]
we should automatically test that all classifiers (and subsequently, clusterers) are completely compatible with scikit learn model selection and evaluation tools, and document recommended parameter/hyper parameter candidates for tuning. It would also be interesting to find out if tuning actually improves and o the core classifiers, I suspect it does not.  

https://scikit-learn.org/stable/model_selection.html

**Comment by fkiraly** [comment]
Related: #2116, I don´t think they currently are compatible?

**Comment by MatthewMiddlehurst** [comment]
We have some tests (not all classifiers, but the interface) for classification. I don't think there is anything for clustering?
