### ISSUE TITLE
[ENH] statsmodels AutoReg and SARIMAX

### ISSUE THREAD

**Issue by fkiraly** [sktime/sktime#2357]
We should interface `AutoReg` and `SARIMAX` from `statsmodels` as forecasters.

- [x] `SARIMAX`
- [ ] `AutoReg`

SARIMAX is currently not available in `sktime`, so having it would be nice.

`AutoReg` would be good to use in `sktime` `VAR` (which interfaces `statsmodels` `Var`) in a case where the `y` passed is univariate.
Currently `VAR` erros out when a univariate `y` is passed; mathematically, AR is the univariate special case of VAR, so it would be natural to use the AR implementation from the same package instead of returning an error.

Should be an easy, good first issue task with these instructions:
https://www.sktime.org/en/stable/developer_guide/add_estimators.html

For `AutoReg`, I would recommend implementation as a separate estimator; in a second step, we can make `Var` default to it for univariate `y`.

**Comment by biologioholic** [comment]
😄 @fkiraly Looks interesting! Sure, I will take on this work

**Comment by ryali1** [comment]
I'd like to get started on adding SARIMAX functionality to sktime if you haven't already worked on that part @biologioholic! Please let me know, and I can get started right away.

**Comment by biologioholic** [comment]
Hello @ryali1, I'm already half way through Sarimax. Debugging atm

**Comment by ryali1** [comment]
Hi @biologioholic, that sounds good, appreciate your response! Have you worked on AutoReg already? If not, maybe I could get started on that. I'm still familiarizing myself with contributing to sktime, so maybe we could collaborate on this, or I could come to you with questions about how to properly test/debug the code I write with the sktime framework?

**Comment by biologioholic** [comment]
Sure, you can go ahead and do the AutoReg. You can look at sktime/forecasting for some interface examples

https://github.com/alan-turing-institute/sktime/tree/main/sktime/forecasting

**Comment by ryali1** [comment]
Great! I'll get started on the AutoReg functionality. I'll start with creating a separate estimator as @fkiraly mentioned and will get feedback on it before working on step 2 (getting VAR to default to it).

**Comment by fkiraly** [comment]
excellent, thanks!

**Comment by TNTran92** [comment]
@fkiraly SARIMAX.py is in testing phase. I have test_sarimax.py in  sktime/forecasting/tests and it works locally. How can I include it in pytest so that it becomes a part of check_estimator?

**Comment by TNTran92** [comment]
@fkiraly Draft PR submitted 😊

**Comment by ryali1** [comment]
@fkiraly I submitted a Draft PR for the AutoReg forecaster

**Comment by ryali1** [comment]
I am not working on this anymore. @TNTran92 if you would like to work on this, I have a closed PR with some preliminary progress. There's a version which works without exogenous factors and some code that should help you with exogenous factors, but is not passing some of the tests. Link is here to the closed PR: https://github.com/alan-turing-institute/sktime/pull/2407

**Comment by TNTran92** [comment]
Thanks, I will take over from here

**Comment by fkiraly** [comment]
Implemented as `AutoREG` by @JonathanBechtel, @mgazian000, @CTFallon.
