### ISSUE TITLE
[BUG] ShapeletTransformClassifier numba error when dtype is not float64

### ISSUE THREAD

**Issue by srggrs** [sktime/sktime#2397]
**Describe the bug**
Seems that when using `ShapeletTransformClassifier` there is some Numba accelerated functions that break if the data in the input data frame are of type `int32`.

**To Reproduce**
MRE as below:

```python
import warnings
warnings.simplefilter('ignore', category=FutureWarning)

import numpy as np
import pandas as pd

from sklearn.model_selection import train_test_split

from sktime.classification.shapelet_based import ShapeletTransformClassifier
from sktime.contrib.vector_classifiers._rotation_forest import RotationForest

# make fake data
data = pd.DataFrame(np.random.random((5000, 250))).astype(np.float32)

# reshape to input into Shapelet Classifier
data4train = data.apply(lambda row: pd.Series({
  'time-series': pd.Series(row.values)
}), axis=1)

# make targets
targets = pd.Series(2500 * [1] + 2500 * [0])

# train test split
X_train, X_test, y_train, y_test = train_test_split(
  data4train, targets, test_size=0.7, random_state=42
)

# train
clf = ShapeletTransformClassifier(
    estimator=RotationForest(n_estimators=3),
    n_shapelet_samples=500,
    max_shapelets=20,
    batch_size=100,
)

clf.fit(X_train, y_train)
```

**Expected behavior**
will not throw an error, and also enforce conversion to float32 or float64 within the classifier?
**Additional context**
removing conversion to `float32` (hence `dtype == float64`) will make the code running without issues.

**Versions**
numba 0.55.1
sklearn 0.24.1
sktime 0.11.0
pandas 1.4.2
python 3.8.10

**Stacktrace output**
```bash
TypingError: Failed in nopython mode pipeline (step: nopython frontend)
Cannot unify array(float64, 1d, C) and array(float32, 1d, C) for 'X_n.2', defined at /path_to_mypython/python/lib/python3.8/site-packages/sktime/utils/numba/general.py (39)

File "../python/lib/python3.8/site-packages/sktime/utils/numba/general.py", line 39:
def z_normalise_series(X):
    <source elided>

    return X_n
```

**Comment by fkiraly** [comment]
Yes, indeed. I think we should look at all the `numba` based code and ensure conversion to float?

**Comment by TonyBagnall** [comment]
Thanks for that we will take a look @MatthewMiddlehurst might be best placed, I think you wrote it?

**Comment by chrisholder** [comment]
The numba function is cache'd using float64. Removing the cache=true will fix this or having two functions one for floatt64 and one for float32 and do an if check before function call to call the correct function.

If you choose the latter happy to show you how to specify the type for a numba function to specify float32 or float64 for a function.
