### ISSUE TITLE
[ENH] probabilistic predictions for `VAR`

### ISSUE THREAD

**Issue by fkiraly** [sktime/sktime#2417]
The `VAR` forecaster which interfaces `statsmodels` can apparently not predict probabilistically, but the `statsmodels` native forecaster can do that, via `forecast_cov`. This should be integrated in the `VAR` class.

**Comment by ryali1** [comment]
Hi Dr. @fkiraly , Happy to work on this! I'm also working on adding a method to VAR that would automatically enable VAR to default to the univariate AutoReg forecaster in case a univariate input is passed to VAR, so I can work on this issue in conjunction.

**Comment by fkiraly** [comment]
Sure!

I had started to work on this already, but had to drop it before I got it to work, due to other issues I needed to prioritize.

Since I will probably not work on this soon: I've pushed my partial work so far in the branch `VAR-predict_var`, please feel free to take it over, use parts of it, or ignore it.

**Comment by ryali1** [comment]
I am not working on this anymore, so it's open for anyone else to take up!

**Comment by fkiraly** [comment]
done, this was added at some point in the past
