### ISSUE TITLE
[ENH] Implement `TimeBinner` transformer, regular binning with aggregation for irregular time series

### ISSUE THREAD

**Issue by mloning** [sktime/sktime#242]
Update (@fkiraly): we should implement a `TimeBinner` transformer, which takes as parameters: `bins`, a `pandas.IntervalIndex`, or an iterable of int or timedelta (of bin start/ends); `aggfunc`, a function with signature (1D iterable) -> float. 

Bins time series into the bins, and aggregates by `aggfunc`.

---
Tabularizer implicitly assumes a bin width of 1, creating a column from each time point. TimeBinner generalises the Tabularizer by allowing users to specify (and tune) the bin width and aggregation function.

**Comment by mloning** [comment]
The Tabularizer is a transformer, but effectively reduces the series-as-features setting to the tabular setting. It takes in a nested data frame (or whatever data format we use for the series-as-feature setting) and returns a tabular array which is compatible with the tabular setting of scikit-learn. It thereby breaks the transformer scitype, which should have the same type for input and output. It would be more consistent to encapsulate the Tabularizer as a meta-estimator similar to the reduced forecaster meta-estimators.

**Comment by sparkingdark** [comment]
Are we going to create a classifier for binned data or want to create bin in graphs @mloning

**Comment by mloning** [comment]
@sparkingdark this is meant to be a transformer for binning time series data.

**Comment by sparkingdark** [comment]
Is this up for working

**Comment by mloning** [comment]
In principle yes, but there are some complications around the data container. You can give it a try focusing on 3d numpy arrays where you would up/down sample the third dimension (time points).

**Comment by sparkingdark** [comment]
Okay basically  I can assume it as a f(x,y,time)

**Comment by mloning** [comment]
For panel data in the 3d numpy format, it's `(n_instances, n_variables, n_timepoints)` - this describes the panel data version of the familiar feature matrix `X` from scikit-learn.

**Comment by fkiraly** [comment]
@kcc-lion, are you going to implement the series-to-series version?
