### ISSUE TITLE
[ENH] ensure `Prophet` can deal with `PeriodIndex`

### ISSUE THREAD

**Issue by fkiraly** [sktime/sktime#2475]
Currently, `Prophet` errors out when given data frames with `PeriodIndex`, due to the interfaced facebook prophet not liking that index (and catch statements in our interface).

We may want to add some intermediate functionality to enable `Prophet` to also deal with `PeriodIndex`? In that case, I'd simply convert it to the first time stamp in a period, then apply `Prophet` as is, and at the end convert back to `PeriodIndex`.

Good first issue, the one non-obvious thing perhaps is that the places to look at includes the `_ProphetAdapter` class as well.

**Comment by aiwalter** [comment]
back in the days we have decided to accept only `pd.DatatimeIndex` and not do the conversion as not for all `freq` values you can convert back and forth without loss of `freq` information. I even opened 2 bug issues for this on `pandas` GitHub which are still open:

https://github.com/pandas-dev/pandas/issues/38914
https://github.com/pandas-dev/pandas/issues/38885

So we might have to implement a custom dummy index conversion:

**Comment by fkiraly** [comment]
> back in the days we have decided to accept only `pd.DatatimeIndex` and not do the conversion

But already our example datasets violate this input assumption, e.g., `load_longley` used above.
This is programmed to cause user frustration...

**Comment by aiwalter** [comment]
yes, we should actually open an issue at `prophet` about this

**Comment by fkiraly** [comment]
with last release over a year ago? Can try, but sounds unlikely...
We'll probably need to find a way to work around it
