### ISSUE TITLE
[ENH] Add VARMAX statespace model in sktime

### ISSUE THREAD

**Issue by Ris-Bali** [sktime/sktime#2499]
**Is your feature request related to a problem? Please describe.**
I was just going through the code base and couldn't find VARMAX model in the forecasting submodule.

**Describe the solution you'd like**
Add or interface VARMAX model into sktime.

**Additional context**
This can be interfaced through statsmodels . 
https://www.statsmodels.org/dev/generated/statsmodels.tsa.statespace.varmax.VARMAX.html
Forecasting Template (for reference)
https://github.com/alan-turing-institute/sktime/blob/main/extension_templates/forecasting.py

**Comment by juanitorduz** [comment]
I thinks the implementation could be similar to the [`UnobservedComponents`](https://github.com/alan-turing-institute/sktime/blob/main/sktime/forecasting/structural.py) model  implementation right? I could take this one maybe in a couple of weeks (I'm a bit busy at the moment) or support someone ini the process as it seems a good first issue :)

**Comment by fkiraly** [comment]
yes, it probably will be, although the devil is always in the details... thanks!

**Comment by juanitorduz** [comment]
> yes, it probably will be, although the devil is always in the details... thanks!

Totally agree! I will come back to this issue in a couple of weeks if no one has taken over :)

**Comment by fkiraly** [comment]
was done by @KatieBuc in https://github.com/sktime/sktime/pull/2763 but forgot to close
