### ISSUE TITLE
[ENH] data loaders for single file types should not require file ending specified

### ISSUE THREAD

**Issue by fkiraly** [sktime/sktime#2576]
data loaders such as `load_from_tsfile` should not requires specification of the file ending, since there is only one file ending the function accepts.

for instance, it would be good if load_from_ts assumed the file extension .ts if none was given, so that these two worked equivalently 

```python
X, y = load_from_tsfile("C:\Temp\Chinatown\Chinatown_TRAIN.ts",
                        return_data_type="numpy2d")
X, y = load_from_tsfile("C:\Temp\Chinatown\Chinatown_TRAIN",
                        return_data_type="numpy2d")
```

**Comment by SaiRevanth25** [comment]
is this issue still open?

**Comment by fkiraly** [comment]
yes, you're welcome to it!
