### ISSUE TITLE
[ENH] can function `_calc_cost_cell` in `distances._msm` be removed?

### ISSUE THREAD

**Issue by TonyBagnall** [sktime/sktime#2635]
there is I think a redundant function in move split merge function (file distances/_msm.py) , I cannot find any uses of it, but I just want to double check in case in plays a role somewhere I cannot see, e.g. notebooks. 

![image](https://user-images.githubusercontent.com/9594042/168258903-5eedeb89-fa52-4dfc-a67f-260cc9734ed6.png)

**Comment by fkiraly** [comment]
this is ... very ... blue?

**Comment by TonyBagnall** [comment]
I have the blues

**Comment by chrisholder** [comment]
This has been fixed in pr #3484 which fixed some bugs and cleaned up msm.
