### ISSUE TITLE
[ENH] type convention clash between transformers and classifiers in case of 2D numpy input

### ISSUE THREAD

**Issue by fkiraly** [sktime/sktime#2640]
There is a type convention clash between transformers and classifiers, as currently in sktime.
😱 

Transformers are consistent with the forecasting module and the datatypes module (convention A), but classifiers are not (convention B).

The clash is as how 2D `numpy` arrays are being interpreted.

Classifiers (convention B) interpret them as a panel of univariate series, (n_series, n_timepoints).
This is in accordance with the `numpyflat` mtype that I thought we were using only internally.

Everything else (convention A) interpret them as a single multivariate series, (n_timepoints, n_variables).
This is in accordance with the `numpy2D` mtype.

Convention A is also consistent with the datatypes notebook that contains the preferred specifications.

What should we do?

I think we need to be consistent here, or we get weirdness in pipelines, such as in https://github.com/alan-turing-institute/sktime/issues/2637. Non-uniform conventions on data representations will leave us in a situation where transformers are either compatible with one or the other, but they cannot be with both.

**Comment by fkiraly** [comment]
FYI @ngupta23, @TonyBagnall

**Comment by fkiraly** [comment]
FYI @tvdboom

**Comment by fkiraly** [comment]
from slack:

I see 2 major options and one family of minor ones

* option A: 2D numpy is always numpyflat (Panel)
* option B: 2D numpy is always numpy2D  (Series)
* option C: depends on scitype, and then you need to say for classifiers, transformers, and forecasters what it should be

I think at least temporary, we need to have option C with numpyflat for classifiers and numpy2D for forecasters, everything else is a deprecation nightmare

transformers had numpy2D as intention but a bug with anything numpy

**Comment by TonyBagnall** [comment]
So panel transformers should assume rows are cases imo, anything else is counter intuitive. Series transformers assume a single multivariate series

**Comment by TonyBagnall** [comment]
Can you not just tag the internal data type meaning?

**Comment by fkiraly** [comment]
> Can you not just tag the internal data type meaning?

That wouldn't work with transformers, where it has to be either or.

**Comment by fkiraly** [comment]
> So panel transformers should assume rows are cases imo, anything else is counter intuitive. Series transformers assume a single multivariate series

There is no such thing anymore as panel/series transformers - all transformers accept series and panel data now, and the default behaviour to switch between the two is "iterate over series" (if panel) or "interpret as one-series panel" (if series).

**Comment by fkiraly** [comment]
current, broken behaviour of transformers: if given 2D numpy array of shape (m, n), interpret this as m instances, n variables, 1 time point

**Comment by TonyBagnall** [comment]
> > So panel transformers should assume rows are cases imo, anything else is counter intuitive. Series transformers assume a single multivariate series
> 
> There is no such thing anymore as panel/series transformers - all transformers accept series and panel data now, and the default behaviour to switch between the two is "iterate over series" (if panel) or "interpret as one-series panel" (if series).

well I was not party to that, we always used to have panel and series transformers, which seemed sensible to me. I would have been against the change if I had time to form an opinion, this being one use case why.  I thought you had reassured me I could throughput 2D numpy, so I left transformers well alone, but perhaps that is only 3D numpy. I have enough to do on distances, classification, clustering and regression, transformers is not my current priority. I dont want you to change my classification notebook though

**Comment by fkiraly** [comment]
>  I thought you had reassured me I could throughput 2D numpy

That's for classifiers only.

What will work with 2D numpy as you intend:

* any classifier in sktime
* including a `ClassifierPipeline` with any transformer and any classifier in it
* including pipelines constructed with dunder methods `*`

The one case that doesn't work is using `sklearn` (not sktime) pipelines with `sktime` transformers if you are passing panel data.

**Comment by fkiraly** [comment]
> I dont want you to change my classification notebook though

That's why I made some changes to help.

Besides the 2D/3D numpy thing, I think there are also a few other useful additions there.

**Comment by fkiraly** [comment]
we have now settled on ensuring consistency of type representations across learning tasks, so transformers will always interpet 2D numpy input as a single time series.
