### ISSUE TITLE
[ENH] sktime-pywatts integration - draft STEP for first integration prototype

### ISSUE THREAD

**Issue by fkiraly** [sktime/sktime#2656]
We should write a draft STEP before the onboarding week, so we have something to present for ideas discussion on the pipeline topic.

@benheid has kindly agreed to coordinate this.

**Comment by benHeid** [comment]
There is a PR for the enhancement protocol, which we unfortunately forgot to merge...

https://github.com/sktime/enhancement-proposals/pull/33


I close this issue, since the graphical pipeline is implemented.
