### ISSUE TITLE
[BUG] Sktime installation with numpy 1.22

### ISSUE THREAD

**Issue by chrisholder** [sktime/sktime#2663]
**Describe the bug**

Numba only supports up to numpy 1.21
![image](https://user-images.githubusercontent.com/4674372/169277932-888b0ba3-242f-4dd9-bc53-233cd1f918bd.png)

**To Reproduce**

pip install sktime

Try importing anything that requires numba for example:

```
from sktime.distances import distance_alignment_path
dtw_path = distance_alignment_path(x, y, metric='dtw')
```

**Expected behavior**

**Additional context**

I dont know for a fact but id imagine you fix this by editing the pyproject.toml to specify 1.21 or less:

```
dependencies = [
    "deprecated>=1.2.13",
    "numba>=0.53",
    "numpy<=1.21.0",
    "pandas>=1.1.0,<1.5.0",
    "scikit-learn>=0.24.0,<1.2.0",
    "statsmodels>=0.12.1",
    "scipy<1.9.0",
]

```

**Versions**
<details>

</details>

**Comment by fkiraly** [comment]
Why would we introduce a version bound on `numpy`? Since we install `numba` as a dependency, the correct upper bound should be inferred from the `numpy` version bound in `numba`, no?

Hence, in no instance should an installation of `sktime` break due to `numpy`/`numba` incompatibility. Or am I missing something?

**Comment by chrisholder** [comment]
I made a new project, pip installed sktime and got the above error because it by default installed the highest version of numpy it could find im assuming

**Comment by fkiraly** [comment]
that´s weird, dependency resolution should prevent that.
Can you post a minimal user journey to obtain the problem, and your OS version?

**Comment by farhana-dansic** [comment]
I am getting a similar error. 

_ImportError: Numba needs NumPy 1.22 or less_

```
tuts) C:\Users\User>conda list numpy
# packages in environment at D:\anaconda\envs\tuts:
#
# Name                    Version                   Build  Channel
numpy                     1.21.1           py39h6635163_0    conda-forge/label/main

(tuts) C:\Users\User>conda list numba
# packages in environment at D:\anaconda\envs\tuts:
#
# Name                    Version                   Build  Channel
numba                     0.55.2           py39hb8cd55e_0    conda-forge
```
Tried many alternative solutions found on several pages. Nothing resolved the issue. Can anyone please guide?

**Comment by fkiraly** [comment]
obsolete as `numba` is no longer a core dependency
