### ISSUE TITLE
[ENH] Refactor/simplify `sktime.forecasting.model_selection._split.BaseSplitter._split_vectorized`

### ISSUE THREAD

**Issue by khrapovs** [sktime/sktime#2695]
`sktime.forecasting.model_selection._split.BaseSplitter._split_vectorized` is very hard to read and understand.

This method was introduced in https://github.com/alan-turing-institute/sktime/pull/2599. During the review I proposed the following refactoring idea: https://github.com/alan-turing-institute/sktime/pull/2599#issuecomment-1126736598 (see comments that followed). For convenience, I copy my main suggestion here:

> I looked a bit closer inside of the sktime.forecasting.model_selection._split.BaseSplitter._split_vectorized. Again, I completely understand the result, for each series in the hierarchy you want to get train/test windows with numeration in the context of one big stacked time series. But I am worried about the implementation of this method. There are several enclosed loops, several temporary objects.

> For each time series in hierarchy you can easily get train/test windows that start counting from zero in isolation for each series. What you want to do next is shift those windows by the iloc indices of each series beginning. Say you have two windows in isolation: [0, 1, 3] (out of [0, 1, 2, 3]), and [0, 2] (out of [0, 1, 2]). The index of the whole series is [0, 1, 2, 3, 4, 5, 6]. The "anchors" are then 0 and 4. So your final windows are [0, 1, 3] + 0 = [0, 1, 3], and [0, 2] + 4 = [4, 6]. I know, it is just a toy example, but isn't it easy to get those iloc "anchors"?

**Comment by fkiraly** [comment]
agreed. There must be an easier way to do this...

**Comment by mateuja** [comment]
Hi, I would like to work on this. I will try to create a PR in the next few days.

**Comment by fkiraly** [comment]
nice, thanks, @mateuja! Let me know if have any questions (since I wrote the original code).
