### ISSUE TITLE
[ENH] "Squaring residual" forecaster compositor

### ISSUE THREAD

**Issue by eenticott-shell** [sktime/sktime#2698]
Design and implement a wrapper for forecasters that fits a model to the residuals to allow for quantile/interval estimation. Have the option for both in-sample and rolling residuals. 

**Two methods**
1. Square the residuals and fit a gaussian
2. Take the absolute values of the residual and fit a laplace distribution

**Comment by fkiraly** [comment]
Quick note: `update_predict` should be very useful in the case of `"rolling"`.

**Comment by ltsaprounis** [comment]
Is bootstrapping residuals a good fit for method number 3 here? 
https://otexts.com/fpp3/prediction-intervals.html#prediction-intervals-from-bootstrapped-residuals

That would result in an empirical distribution for the residuals

**Comment by fkiraly** [comment]
Bootstrapping is a different kind of estimator, I think that should be in a separate class.

**Comment by fkiraly** [comment]
> For `"rolling"` I want out of sample predictions, but unless I do some form of CV on the data given in `fit` I can't obtain these until the first `update` call. 

In my imagination, you would specify a `fit_range`, which specifies a sub-set of the data seen in `fit`, then you run `update_predict` on the rest. That produces rolling out-of-sample forecasts on the data seen in `fit`.

The solution is simply to take the data seen in `fit` and split into a fitting and rolling-update part, if uncertainty intervals are queried.

Would that work?

**Comment by fkiraly** [comment]
This should have been closed by https://github.com/sktime/sktime/pull/3378 which implements the `SquaringResiduals` estimator.
