### ISSUE TITLE
[ENH] Add support to get_slice for multi-index and hierarchical data

### ISSUE THREAD

**Issue by bethrice44** [sktime/sktime#2757]
**Is your feature request related to a problem? Please describe.**
A clear and concise description of what the problem is.

In order to deal with [this issue ](https://github.com/alan-turing-institute/sktime/issues/2702), a function called `get_slice` has been created [here](https://github.com/alan-turing-institute/sktime/pull/2706) so slicing objects is always inclusive at the start and exclusive at the end. 

**Describe the solution you'd like**
As in `get_window` ([link](https://github.com/alan-turing-institute/sktime/blob/a761368f32b12913f2d7c22d87776e6112cc785d/sktime/datatypes/_utilities.py#L222)) we need to add some additional conditional logic to deal with multi-index and hierarchical data structures. 

We should also expand the tests in [datatypes/tests/test_utils.py](https://github.com/alan-turing-institute/sktime/blob/main/sktime/datatypes/tests/test_utils.py) to cover these cases.

**Comment by fkiraly** [comment]
solved by @bethrice44 in #2761, forgot to close
