### ISSUE TITLE
[ENH] An ensemble type forecaster for panel/hierarchical data

### ISSUE THREAD

**Issue by ciaran-g** [sktime/sktime#2764]
**Is your feature request related to a problem? Please describe.**
For forecasting in a hierarchy it would be nice to be able to use different forecasters for each individual node

**Describe the solution you'd like**
A class similar to `ColumnEnsembleForecaster` but instead of applying a different univariate forecaster per-column, it applies a different univariate forecaster per-level on panel-type data

**Describe alternatives you've considered**
One option is to run a loop or something but it would be difficult to adapt this into #2157

**Comment by fkiraly** [comment]
We should also check whether `VectorizedDF` can be used for this productively. Probably yes?

**Comment by VyomkeshVyas** [comment]
> **Is your feature request related to a problem? Please describe.** For forecasting in a hierarchy it would be nice to be able to use different forecasters for each individual node
> 
> **Describe the solution you'd like** A class similar to `ColumnEnsembleForecaster` but instead of applying a different univariate forecaster per-column, it applies a different univariate forecaster per-level on panel-type data
> 
> **Describe alternatives you've considered** One option is to run a loop or something but it would be difficult to adapt this into #2157

Hi @ciaran-g , @fkiraly  I am currently working on this problem.

**Comment by fkiraly** [comment]
excellent, @VyomkeshVyas! Looking forward to your PR.
