### ISSUE TITLE
[BUG] `KNeighborsTimeSeriesClassifier` fails with any algorithm except `brute`

### ISSUE THREAD

**Issue by fkiraly** [sktime/sktime#2774]
`KNeighborsTimeSeriesClassifier` has one of two bugs:

* a docstring that incorrectly claims that an `algorithm` can be set. Currently, it is set to `brute` internally (when calling the sklearn algorithm), no matter what the hyperparameter is.
* failing with algorithms other than `brute`, e.g., `auto` (the sklearn default) when the implementation is fixed to match the docstring.

So, either, the docstring should be corrected and refrain from claiming that more than one algorithm can be used internally; or, the `algorithm` needs to be properly passed through, and the failures with algorithms other than `brute` fixed.

**Comment by AurumnPegasus** [comment]
@fkiraly I was actually editing the ```KNeighborsTimeSeriesClassifier``` according to #2733 (to remove the kwargs) and noticed the same! For now I simply added ```algorithm``` as a parameter (which can simply be removed for the sake of this bug). Please update me on the approach taken for this bug so that I could reflect it as well.

**Comment by fkiraly** [comment]
I have changed the default to `brute`, so one can set the algorithm, but it will break when choosing anything different

**Comment by MatthewMiddlehurst** [comment]
This was fixed in the refactor, correct?

**Comment by fkiraly** [comment]
hm, I see that the test parameters do not check for this, so we don't really know
