### ISSUE TITLE
[BUG] evaluate method y_true y_pred inconsistency

### ISSUE THREAD

**Issue by ilkersigirci** [sktime/sktime#2846]
**Describe the bug**

After upgrading to 0.12.0, in `evaluate` method,  I got the warning: `UserWarning: y_pred and y_true do not have the same column index`. I guess it is because, `y_pred` doesn't have `y_true` ' s column name in its name. It is somehow removed during inner convertion processes. 

**To Reproduce**

```python
from sktime.datasets import load_longley
from sktime.forecasting.arima import ARIMA
import numpy as np
from sktime.forecasting.model_evaluation import evaluate
from sktime.forecasting.model_selection import ExpandingWindowSplitter

y, X = load_longley()

fh = np.arange(1,3)

model = ARIMA()

df = evaluate(
    forecaster=model,
    cv=ExpandingWindowSplitter(fh=fh),
    y=y,
    X=X,
)
```

**Expected behavior**

No warning should be given

**Additional context**

**Versions**
<details>

System:
python: 3.8.13 | packaged by conda-forge | (default, Mar 25 2022, 06:04:18)  [GCC 10.3.0]
executable: /miniconda3/envs/predy-ts/bin/python3.8
machine: Linux-5.13.0-51-generic-x86_64-with-glibc2.10

Python dependencies:
pip: 22.1.2
setuptools: 62.3.4
sklearn: 1.0
sktime: 0.12.0
statsmodels: 0.13.2
numpy: 1.21.6
scipy: 1.8.1
pandas: 1.3.5
matplotlib: 3.5.2
joblib: 1.1.0
numba: 0.55.2
pmdarima: 1.8.5
tsfresh: None

</details>

**Comment by fkiraly** [comment]
confirmed on current main, python 3.8, windows.

Indeed this was a warning that we introduced recently to catch some common errors. It would seem that indeed column names are being changed somewhere in there, we need to investigate this.

Does this happen only with `ARIMA`, would be another question.

**Comment by ilkersigirci** [comment]
Arima was just an example. The warning exists in all the forecasters

**Comment by hazrulakmal** [comment]
I don't seem to be able to reproduce the same error anymore in the current main. this error may have been fixed in the latest version. @fkiraly Please double-check this and if things are ok, then I suggest we can close this issue.

**Comment by fkiraly** [comment]
Yes, you are right, this no longer triggers the warning.

It probably disappeared as a side effect of the forecasting metrics refactor, without a direct intention to fix this bug. I think we can close this.

Thank you for pointing this out, @hazrulakmal!
