### ISSUE TITLE
[BUG] contributors.md not updating?

### ISSUE THREAD

**Issue by fkiraly** [sktime/sktime#2905]
Update: there's a "hard" and an "easy" (good first issue) problem here.

easy = running the cmdline tool locally and making a PR with the generated contributors.md

hard = automating this in the CI (e.g., release script)

(and we close it only once we have automation done)

---

It seems the contributors.md has not updated since 0.9.0 - are we doing sth wrong with the release?

Did we accidentally drop sth from the release script when we moved to GHA that re-generated the contributors.md?

FYI @lmmentel, @freddyaboulton

**Comment by lmmentel** [comment]
Good catch, do you know how were they updated in the past? I've checked the history and those updates are a part of release PR but it's hard to say if this was a manual or automated edit.

**Comment by fkiraly** [comment]
> Good catch, do you know how were they updated in the past? I've checked the history and those updates are a part of release PR but it's hard to say if this was a manual or automated edit.

I suspect, one of these:
https://allcontributors.org/docs/en/tooling

@mloning might know more.

**Comment by fkiraly** [comment]
Docs are still here:
https://allcontributors.org/docs/en/cli/installation

>Think it's still manual. 

Do you mean manual, as there is something you can locally and commit - or, manual as in having to translate the all-contributors line by line??

**Comment by mloning** [comment]
> Do you mean manual, as there is something you can locally and commit - or, manual as in having to translate the all-contributors line by line??

Using their command line client.

**Comment by fkiraly** [comment]
hm, looks straighforward enough - so someone should be able to do that locally and simply make a PR with the updated file, until we figure out how to automate it.

**Comment by achieveordie** [comment]
I think the most direct solution will be to have a GitHub bot perform this operation whenever it notices a change in `.all_contributorsrc`. There's already a [bot](https://allcontributors.org/docs/en/bot/overview) that they provide but even that requires a cue to perform a PR so we might as well create one for added flexibility.
