### ISSUE TITLE
[MNT] fix automatic releases on `conda-forge`

### ISSUE THREAD

**Issue by fkiraly** [sktime/sktime#2921]
0.12.1 has not been released on `conda-forge`, even though this should have happened by automation.

@lmmentel was investigating, this is to track the issue.

I also think it is a must-have to solve before 0.13.0 mid-July, or the debt will accumulate - especially since we want to move to 3.10 support.

issue on `sktime-feedstock`: https://github.com/conda-forge/sktime-feedstock/issues/44

**Comment by lmmentel** [comment]
Currently the build on linux py39 fails with

```
The reported errors are:
- Encountered problems while solving:
-   - package sktime-0.12.1-py39h5a03fae_1 requires python >=3.9,<3.10.0a0, but none of the providers can be installed
```
more logs
[https://dev.azure.com/conda-forge/feedstock-builds/_build/results?buildId=530943&vi[…]413-330699242c05&t=c10fa5f2-fdf6-5338-3bdb-c4bea7c23412&l=3135](https://dev.azure.com/conda-forge/feedstock-builds/_build/results?buildId=530943&view=logs&j=517fe804-fa30-5dc2-1413-330699242c05&t=c10fa5f2-fdf6-5338-3bdb-c4bea7c23412&l=3135)

**Comment by fkiraly** [comment]
py38 says something different:
```
package sktime-all-extras-0.12.1-ha770c72_1 requires numba >=0.53, but none of the providers can be installed
```

**Comment by fkiraly** [comment]
actually, py39 says the same

**Comment by lmmentel** [comment]
I am trying to debug, so making changes to the PR

**Comment by fkiraly** [comment]
ah, makes sense.

**Comment by lmmentel** [comment]
more logs 
```
failed to get install actions, retrying.  exception was: Unsatisfiable dependencies for platform linux-64: {"hcrystalball[version='>=0.1.9']", "prophet[version='>=1.1']", "scikit-posthocs[version='>=0.6.5']", "tbats[version='>=1.1.0']"}
```

**Comment by lmmentel** [comment]
I found a config that works for `sktime` but there are still conflicts for `sktime-all-extras`

**Comment by lmmentel** [comment]
Adding `prophet` to a successful CI run, works for 
- linux py37
but fails for 
- linux py38
- linux py39

with:
```

The reported errors are:
- Encountered problems while solving:
-   - package sktime-0.12.1-py39h5a03fae_1 requires numba >=0.53, but none of the providers can be installed
```

**Comment by lmmentel** [comment]
It seems that prophet is the problem... I think we can merge and release without prophet which then can be installed through pip, Appreciate some comments here @fkiraly @freddyaboulton @dhirschfeld 

An alternative would be to debug what goes wrong in deps resolution with prophet but conda-forge build is not very straightforward and was wasn't able to reproduce the build process locally yet and I'm not sure if it's worth investing time into this.

**Comment by dhirschfeld** [comment]
> *I think we can merge and release without prophet which then can be installed through pip*

I think that's fine & probably the best you can do for now. I'd say merge with this workaround and the `prophet` install can be debugged in a separate PR so as to not hold up this release.

**Comment by lmmentel** [comment]
Thanks @dhirschfeld. I managed to further restrict prophet install by platform and python version so prophet will be a dependency for `sktime-all-extras` for all platforms except linux with py38 or py39. I agree, we should push the release out and debug separately.

**Comment by lmmentel** [comment]
Here's a short summary and current status of the issues affecting conda release:
1. conda bot not creating a PR after the release on PyPI - AFAIK it is unresolved and undiagnosed, I looked into it but didn't get far
2. source url changing in the meta.yaml and now requiring and extra . after the v of the version - updated in the PR
3. `prophet >=1.1`  creating dependency resolution error on linux py38 and py39 - worked around by skipping this conda dep in the CI for the specific platforms
4. unnecessary deps specified in host section - cleaned up in the PR

**Comment by fkiraly** [comment]
0.12.1 is now released (manually), but we haven´t yet understood what is preventing automatic releases - renaming issue and downgrading importance from "must" to "should" for release board

**Comment by fkiraly** [comment]
@lmmentel made an observation, possibly the cause?

> It seems the link to the github release assets changed. The assets are now under https://github.com/alan-turing-institute/sktime/archive/refs/tags/v0.13.1.tar.gz url so the template in the `meta.yml` would need to be updated.

**Comment by christopherbunn** [comment]
Hello! Is there any progress on this issue or plans for a manual release for version 0.14.0? Especially since pandas 1.5 support is introduced in 0.13.3 it would be great to have a more up-to-date version installable through conda.

**Comment by lmmentel** [comment]
There's been an effort to fix conda release (see [here](https://github.com/conda-forge/sktime-feedstock/pull/49)) but it's quite hard to put together a recipe with all dependencies taking into account platform support and the fact that some of our soft deps don't bother with conda release or their conda release lag far behind their pypi releases.

Is there anything you cannot do though pip/pypi that would be enabled with conda @christopherbunn?

**Comment by fkiraly** [comment]
could we simply ignore the soft dependencies, @lmmentel?

Just release with the core dependencies?

Since the time the problem originally occurred, the soft dependencies should be fully isolated, i.e., the test suite will run with the core dependencies only.

**Comment by dhirschfeld** [comment]
> *could we simply ignore the soft dependencies*

+:100:

IMHO it's very low priority to release a package with the soft-dependencies and it really shouldn't hold up releasing the core package. If it works, it's a nice convenience for users but if not, users can easily install the extra deps they need via conda or pip

**Comment by fkiraly** [comment]
well, let's do that then. The soft dependencies should be fully isolated as soon as this PR passes:
https://github.com/sktime/sktime/pull/3760

**Comment by christopherbunn** [comment]
Hi! Now that we have the soft dependencies separated out, is there anything else blocking a conda release? If not, I'm happy to give updating the feedstock a shot if no one else is working on that already.

**Comment by lmmentel** [comment]
I don't see why not @christopherbunn. Go ahead and fee free to reach out if there's anything I can help with.
