### ISSUE TITLE
[ENH] sktime-pywatts integration - package and class dependency mechanics

### ISSUE THREAD

**Issue by fkiraly** [sktime/sktime#2956]
Part of [pywatts integration design questions](https://github.com/alan-turing-institute/sktime/issues/2653).

To discuss how inter-dependency between classes in `sktime` and `pywatts` are going to work.

**Comment by fkiraly** [comment]
from issue https://github.com/alan-turing-institute/sktime/issues/2654, initial suggestion by @fkiraly

here's a suggestion on this question:

> whether `__call__` should live directly in `sktime`, or in `pywatts`. If not in `sktime`, how could it possibly work after import?

I think a good solution would be the following:
* `GraphPipeline` lives in `pywatts`, but is `sktime` compatible
* `pywatts` is an `sktime` soft dependency, localized to `__call__`
* `sktime` is a `pywatts` soft dependency, for base class (parent of `GraphPipeline`?) and testing
* testing for `GraphPipeline` uses `sktime` `check_estimator`
* `sktime` base classes implement high-level `__call__` logic, i.e., constructing the `GraphPipeline`
* `sktime` base classes import `pywatts` `GraphPipeline` internally in `__call__`, errors are raised via `_check_soft_dependency`. This is similar to how the other dunders import a specific compositor class, e.g., `*` of `BaseTransformer` importing the `TransformerPipeline`.

**Comment by fkiraly** [comment]
@kalebphipps and pywatts team thought:

good idea, *but* `pywatts` has a lot of stuff and dependencies.

So, in addition, there should be a refactor within `pywatts` that factors out pipeline specific functionality, separate from specific algorithms or utilities with lots of dependencies.

**Comment by kalebphipps** [comment]
@fkiraly, thanks for creating the issue - you can assign me, and I'll include some more information :)

**Comment by kalebphipps** [comment]
The integration should take place in two stages:

1. Preparation of new Git structure by pyWATTS:
    - Separate pyWATTS into pyWATTS-pipeline Repo and pyWATTS-features Repo.
    - Possibly further separation of the features Repo at a later date.
    - Ensure the core GraphPipline functionality is included in the pyWATTS-pipeline Repo with as few dependencies as possible.
    - Check that all workflows, tests, etc., still work.
2. Integration with sktime:
    - When the above structure is stable, we can work together to ensure the Graphpipeline is integrated into sktime, following the suggestion from Franz above.

A note on credits:
- Since pyWATTS is funded by various programs in Germany, the pyWATTS-pipeline will include acknowledgements thinking these programs for their funding.
- All contributions from sktime will also be credited accordingly in the pyWATTS-pipeline repository.

**Comment by fkiraly** [comment]
update from meeting Mar 3 - `skbase` is now almost mature, it contains base class and testing utilities.
https://github.com/sktime/skbase

Going forward, the base class issue can be solved by having both `sktime` and the graph pipeline package depending on `skbase`

**Comment by benHeid** [comment]
I close this issue since, the graphical pipeline is now directly implemented in sktime.
