### ISSUE TITLE
[ENH] TruncationTransformer should preserve index and column names of initial pandas dataframe 

### ISSUE THREAD

**Issue by mccrinbc-ss** [sktime/sktime#2998]
**Is your feature request related to a problem? Please describe.**

TruncationTransformer is a very useful function, but it become hard to use in conjunction with an sklearn ColumnTransformer if you want the Pipeline to be interpretable. After the transform, the new truncated dataframe loses all feature and index name conventions. The image below illustrates what occurs after the transform: 
![image](https://user-images.githubusercontent.com/83707037/178787184-5ef0be61-894d-4022-af92-ad432df29521.png)

**Describe the solution you'd like**

It is highly desirable that the truncated dataframe preserve the labelling convention of the initial dataframe. In this way, the user is less prone to error and avoid unnecessary bugs. For example, if I'm attempting to create an interpretable pipeline that utilizes a ColumnTransformer and the names given of the initial dataframe, the pipeline will break:
```
    ct = ColumnTransformer(
        [
            (sensor_col, univariate_pipeline, [sensor_col]) for sensor_col in sensor_cols
        ]
    )

    multivariate_pipeline = Pipeline(
        [
            ('truncator', TruncationTransformer()), #apply truncation across all periods in the panel_df
            ('univariate_model', ct),
        ]
    )
```

```
KeyError: 's1' 
....

File ~/projects/PdM/PdM/lib/python3.8/site-packages/sklearn/compose/_column_transformer.py:357, in ColumnTransformer._validate_column_callables(self, X)
    355         columns = columns(X)
    356     all_columns.append(columns)
--> 357     transformer_to_input_indices[name] = _get_column_indices(X, columns)
    359 self._columns = all_columns
    360 self._transformer_to_input_indices = transformer_to_input_indices

File ~/projects/PdM/PdM/lib/python3.8/site-packages/sklearn/utils/__init__.py:424, in _get_column_indices(X, key)
    421             column_indices.append(col_idx)
    423     except KeyError as e:
--> 424         raise ValueError("A given column is not a column of the dataframe") from e
    426     return column_indices
    427 else:

ValueError: A given column is not a column of the dataframe

```

**Describe alternatives you've considered**
Solutions include iterating over range(0, num_sensor_columns), but this shouldn't be considered a clean and interpretable option. Is there anyway to have the Transformer preserve the labels?

**Comment by mccrinbc-ss** [comment]
Good to see there is a solution in the works, I will wait until it's merged to test it on my machine. Will this solution also keep the names of the multiindex (in my case, 'id' and 'time', rather than converting to 'instance' and 'timepoints')?

**Comment by fkiraly** [comment]
Fix doesn't include the issue with the index names yet, will look into this after the 0.13.0 release.

**Comment by fkiraly** [comment]
Now it does, this was a more general issue in the conversions, if the internal type did not have multiindex index names.

**Comment by fkiraly** [comment]
oh, it kills the *index*!

The column name issue has been resolved though.

**Comment by seanbyrne226** [comment]
Wait, its completely my fault :( 


 I must of done a view of a copy as I split the data for training and test first, when I don't do that, the same code produces this: 
<img width="752" alt="Screenshot 2022-10-06 at 19 36 07" src="https://user-images.githubusercontent.com/50303858/194392429-33524375-811c-431e-9f5f-0c52568b134b.png">

Apologies I never use pandas :(

**Comment by fkiraly** [comment]
yes, I just tested it and could not reproduce the bug.

But at least I wrote a test https://github.com/sktime/sktime/pull/3535
