### ISSUE TITLE
[BUG] sporadic test failure in `test_classifier_output[TEASER-ClassifierFitPredict]`

### ISSUE THREAD

**Issue by fkiraly** [sktime/sktime#3033]
It seems there is a sporadic test failure in `test_classifier_output[TEASER-ClassifierFitPredict]` which crashes the worker without any further information. The reason could be, for instance, a memory leak or an infinite recursion.

Example: https://github.com/alan-turing-institute/sktime/runs/7371344857

FYI @MatthewMiddlehurst

**Comment by MatthewMiddlehurst** [comment]
Has this appeared since the original issue? The link no longer shows the broken test, so it is difficult to assess.

**Comment by fkiraly** [comment]
`TEASER` is still on the test exclusion list, I think?

**Comment by MatthewMiddlehurst** [comment]
The tests excluded are different from the one in this issue, we know why those break, and it's (mostly) reasonable that they do so.

```   
    # Early classifiers intentionally retain information from previous predict calls
    #   for #1.
    # #2 amd #3 are due to predict/predict_proba returning two items and that breaking
    #   assert_array_equal
    "TEASER": [
        "test_methods_do_not_change_state",
        "test_fit_idempotent",
        "test_persistence_via_pickle",
    ],
```

**Comment by MatthewMiddlehurst** [comment]
I don't think this has ever reappeared, and we don't have any information to reproduce it. Most likely just an issue with the node or similar. Suggesting we close.

**Comment by TonyBagnall** [comment]
I have not seen this sporadic fail, and the linked logs have expired, Can we close this @fkiraly?

**Comment by fkiraly** [comment]
I suppose so.
