### ISSUE TITLE
[DOC] improvements on local linting/precommit setup developer documentation

### ISSUE THREAD

**Issue by fkiraly** [sktime/sktime#3100]
Update: content has been added, but the lists are formatted badly due to typos in the code. Would be appreciated if someone could fix this!

---

From #3086, by @jelc53, in reference to https://github.com/alan-turing-institute/sktime/pull/3089 and the current developer doc on local linting and precommit setup:

> Great to hear! Appreciate you helping me through it. Re feedback on https://github.com/alan-turing-institute/sktime/pull/3089, the pre-commit setup made life much easier for me so I think that’ll be helpful for others too. Only question for me is whether you also make clear that another option is to configure the ide to flag black and flake8 conventions for those who don’t want to use pre-commit. Not sure. Might be one of those things where more info is more confusing than helpful.

@jelc53, not sure I understand - what is that other option you are referring to, i.e., "configure the ide to flag black and flake8 conventions"?
I added an entire section called "Integrating with your local developer IDE" in #3089, so do you think this is not detailed enough, or is there a different option?

Here: https://www.sktime.org/en/latest/developer_guide/coding_standards.html#integrating-with-your-local-developer-ide
(you need to go to `latest` documentation to see the one on current `main`, the `stable` will always show the state at the last release)

Pull requests to improve the docs are also always appreciated!
The file in question is `developer_guide/coding_standards.rst`

**Comment by jelc53** [comment]
Yep I was defintely looking at an older version. The section on integrating with local developer ide is exactly what I was thinking.

**Comment by fkiraly** [comment]
Excellent! If you have anything to add, PR are appreciated. Closing for now, since it looks like the requirements are met.

**Comment by fkiraly** [comment]
actually, the bullet points in various lists are going over lines and are badly formatted, with lines starting in the middle of other lines. Would be great if someone could fix this before the next release 😄 

(good first issue since it just requires adding spaces in the above-mentioned file)

**Comment by C-mmon** [comment]
I will take this up.

**Comment by C-mmon** [comment]
Do I have to look in developer_guide/coding_standards.rst?

**Comment by fkiraly** [comment]
Thanks, @C-mmon!

>Do I have to look in `developer_guide/coding_standards.rst`?

Yes, correct!

**Comment by C-mmon** [comment]
created a pull request

**Comment by miraep8** [comment]
Just wondering if this issue has been resolved?  If so can we close the issue?

**Comment by jelc53** [comment]
Yes I think so!

**Comment by fkiraly** [comment]
yes, here: https://github.com/sktime/sktime/pull/3111
