### ISSUE TITLE
[BUG] Inconsistent `dtype` when converting from nested to long dataframe

### ISSUE THREAD

**Issue by hamzahiqb** [sktime/sktime#311]
**Describe the bug**

The `dtype` of the time index changes when I convert a nested dataframe to long format using the `from_nested_to_long()` function.

**To Reproduce**

```python
import numpy as np
import pandas as pd
from sktime.utils.data_container import from_nested_to_long
from sktime.utils._testing import generate_df_from_array, _assert_almost_equal

# Create a nested array
n_obs_X = 20
n_cols_X = 3
X = generate_df_from_array(np.random.normal(size=n_obs_X), n_rows=10,n_cols=n_cols_X)
```

```
# Turn it into long format
Y = from_nested_to_long(X)

Y.head()
```
|    |   index |    value | column   |   time_index |
|---:|--------:|---------:|:---------|-------------:|
|  0 |       0 | 0.379048 | col0     |            0 |
|  1 |       1 | 0.379048 | col0     |            0 |
|  2 |       2 | 0.379048 | col0     |            0 |
|  3 |       3 | 0.379048 | col0     |            0 |
|  4 |       4 | 0.379048 | col0     |            0 |

The output of the `dtype` for X and Y are as follows:

```
X.iloc[0,0].index # RangeIndex(start=0, stop=20, step=1)
X.iloc[0,0].index.dtype # dtype('int64')

Y.time_index.dtype # dtype('O')
type(Y.time_index.iloc[0]) # str
```

**Expected behavior**

The dtype for Y should be `int64`

Y.time_index.dtype # dtype('int64')
type(Y.time_index.iloc[0]) # dtype('int64')

**Additional context**

From what I understand, line 127 in https://github.com/alan-turing-institute/sktime/blob/master/sktime/utils/data_container.py#L127 is where the index is converted to a string.

**Versions**
<details>

Darwin-18.7.0-x86_64-i386-64bit
Python 3.6.10 |Anaconda, Inc.| (default, Jan  7 2020, 15:01:53) 
[GCC 4.2.1 Compatible Clang 4.0.1 (tags/RELEASE_401/final)]
NumPy 1.18.4
SciPy 1.4.1
Pandas 1.0.4
sktime 0.4.0

</details>

**Comment by mloning** [comment]
Thanks for raising the issue @hiqbal2, would appreciate a PR!

**Comment by hiqbal2** [comment]
take

**Comment by nielsuit227** [comment]
This bug is not only in this function, but also in `from_multi_index_to_nexted`, `from_3d_numpy_to_nested`. Shall I raise a separate ticket for that or is it the same underlying bug?

**Comment by eyjo** [comment]
This issue is no longer reproducible. The imports might have been moved/renamed or are no longer present in sktime. I did not find an obvious replacement for these imports:
```python
from sktime.utils.data_container import from_nested_to_long
from sktime.utils._testing import generate_df_from_array, _assert_almost_equal
```

**Comment by fkiraly** [comment]
This is an ancient bug report, thanks for looking into it, @eyjo!

Here's where the functionality has moved:

* `generate_df_from_array` has been replaced or can be replaced by `_make_panel`, I think
* `from_nested_to_long` is now in the datatypes module, and should be interfaced only via `convert` or `convert_to`, specifically when converting to the mtype `"pd-long"`

**Comment by fkiraly** [comment]
Trying a convnersion of the code:

```python
import numpy as np
import pandas as pd
from sktime.utils.data_container import from_nested_to_long
from sktime.utils._testing.panel import _make_panel_X
from sktime.utils._testing import _assert_almost_equal

# Create a nested array
n_obs_X = 20
n_cols_X = 3
X = _make_panel_X(n_instances=10, n_columns=n_cols_X)

Y = convert_to(X, "pd-long")
```

**Comment by eyjo** [comment]
Now the dtype of the corresponding variable is:
```bash
dtype('int64')
```
I would think this is resolved ... ?

**Comment by fkiraly** [comment]
Yes, indeed, looks like it got fixed since then - thanks for checking!
