### ISSUE TITLE
[BUG] ARIMA and AutoARIMA not working within ConformalIntervals

### ISSUE THREAD

**Issue by mateocomba123** [sktime/sktime#3194]
When I try to generate predict intervals with ConformalIntervals it gives an error.
You would say I'd directly use the predict_interavals method, but in my case the idea is to obtain the intervals from a Time Series Ensemble model. And when I pass that ensemble to the ConformalIntervals, and the enemble contains ARIMA or AutoArima model, it fails.
Any idea to get prediction intervals for an ensemble model?

<img width="553" alt="image" src="https://user-images.githubusercontent.com/72084989/183140746-d227918a-0139-402b-8c69-58558a4b04cf.png">

Error:
---------------------------------------------------------------------------
IndexError                                Traceback (most recent call last)
Input In [25], in <cell line: 7>()
      5 forecaster = ARIMA()
      6 conformal_forecaster = ConformalIntervals(forecaster)
----> 7 conformal_forecaster.fit(y, fh=[1,2,3])
      8 pred_int = conformal_forecaster.predict_interval()

File ~\.conda\envs\sktime_arima\lib\site-packages\sktime\forecasting\base\_base.py:270, in BaseForecaster.fit(self, y, X, fh)
    268 # we call the ordinary _fit if no looping/vectorization needed
    269 if not vectorization_needed:
--> 270     self._fit(y=y_inner, X=X_inner, fh=fh)
    271 else:
    272     # otherwise we call the vectorized version of fit
    273     self._vectorize("fit", y=y_inner, X=X_inner, fh=fh)

File ~\.conda\envs\sktime_arima\lib\site-packages\sktime\forecasting\conformal.py:140, in ConformalIntervals._fit(self, y, X, fh)
    137 self.forecaster_.fit(y=y, X=X, fh=fh)
    139 if self.fh_early_:
--> 140     self.residuals_matrix_ = self._compute_sliding_residuals(
    141         y=y,
    142         X=X,
    143         forecaster=self.forecaster,
    144         initial_window=self.initial_window,
    145         sample_frac=self.sample_frac,
    146     )
    148 return self

File ~\.conda\envs\sktime_arima\lib\site-packages\sktime\forecasting\conformal.py:290, in ConformalIntervals._compute_sliding_residuals(self, y, X, forecaster, initial_window, sample_frac)
    287 X_test = get_slice(X, start=id, end=None)
    289 try:
--> 290     forecaster.fit(y_train, X=X_train, fh=y_test.index)
    291 except ValueError:
    292     warn(
    293         f"Couldn't fit the model on "
    294         f"time series window length {len(y_train)}.\n"
    295     )

File ~\.conda\envs\sktime_arima\lib\site-packages\sktime\forecasting\base\_base.py:270, in BaseForecaster.fit(self, y, X, fh)
    268 # we call the ordinary _fit if no looping/vectorization needed
    269 if not vectorization_needed:
--> 270     self._fit(y=y_inner, X=X_inner, fh=fh)
    271 else:
    272     # otherwise we call the vectorized version of fit
    273     self._vectorize("fit", y=y_inner, X=X_inner, fh=fh)

File ~\.conda\envs\sktime_arima\lib\site-packages\sktime\forecasting\base\adapters\_pmdarima.py:52, in _PmdArimaAdapter._fit(self, y, X, fh)
     50     X = X.loc[y.index]
     51 self._forecaster = self._instantiate_model()
---> 52 self._forecaster.fit(y, X=X)
     53 return self

File ~\.conda\envs\sktime_arima\lib\site-packages\pmdarima\arima\arima.py:597, in ARIMA.fit(self, y, X, **fit_args)
    594         X = safe_indexing(X, slice(0, n_exog - cv))
    596 # Internal call
--> 597 self._fit(y, X, **fit_args)
    599 # now make a forecast if we're validating to compute the
    600 # out-of-sample score
    601 if cv_samples is not None:
    602     # get the predictions (use self.predict, which calls forecast
    603     # from statsmodels internally)

File ~\.conda\envs\sktime_arima\lib\site-packages\pmdarima\arima\arima.py:520, in ARIMA._fit(self, y, X, **fit_args)
    518         fit, self.arima_res_ = _fit_wrapper()
    519 else:
--> 520     fit, self.arima_res_ = _fit_wrapper()
    522 # Set df_model attribute for SARIMAXResults object
    523 sm_compat.bind_df_model(fit, self.arima_res_)

File ~\.conda\envs\sktime_arima\lib\site-packages\pmdarima\arima\arima.py:508, in ARIMA._fit.<locals>._fit_wrapper()
    504 # kwargs that might be in fit args, but if not we override the
    505 # defaults
    506 disp = fit_args.pop("disp", 0)
--> 508 return arima, arima.fit(start_params=start_params,
    509                         method=method,
    510                         maxiter=_maxiter,
    511                         disp=disp,
    512                         **fit_args)

File ~\.conda\envs\sktime_arima\lib\site-packages\statsmodels\tsa\statespace\mlemodel.py:650, in MLEModel.fit(self, start_params, transformed, includes_fixed, cov_type, cov_kwds, method, maxiter, full_output, disp, callback, return_params, optim_score, optim_complex_step, optim_hessian, flags, low_memory, **kwargs)
    530 """
    531 Fits the model by maximum likelihood via Kalman filter.
    532 
   (...)
    647 statsmodels.tsa.statespace.structural.UnobservedComponentsResults
    648 """
    649 if start_params is None:
--> 650     start_params = self.start_params
    651     transformed = True
    652     includes_fixed = True

File ~\.conda\envs\sktime_arima\lib\site-packages\statsmodels\tsa\statespace\sarimax.py:953, in SARIMAX.start_params(self)
    949     params_exog = []
    951 # Non-seasonal ARMA component and trend
    952 (params_trend, params_ar, params_ma,
--> 953  params_variance) = self._conditional_sum_squares(
    954     endog, self.k_ar, self.polynomial_ar, self.k_ma,
    955     self.polynomial_ma, self._k_trend, trend_data,
    956     warning_description='ARMA and trend')
    958 # If we have estimated non-stationary start parameters but enforce
    959 # stationarity is on, start with 0 parameters and warn
    960 invalid_ar = (
    961     self.k_ar > 0 and
    962     self.enforce_stationarity and
    963     not is_invertible(np.r_[1, -params_ar])
    964 )

File ~\.conda\envs\sktime_arima\lib\site-packages\statsmodels\tsa\statespace\sarimax.py:843, in SARIMAX._conditional_sum_squares(endog, k_ar, polynomial_ar, k_ma, polynomial_ma, k_trend, trend_data, warning_description)
    839     residuals = Y - np.dot(X, params_ar)
    841 # Run an ARMA(p,q) model using the just computed residuals as
    842 # data
--> 843 Y = endog[r:]
    845 X = np.empty((Y.shape[0], 0))
    846 if k_trend > 0:

IndexError: too many indices for array: array is 0-dimensional, but 1 were indexed

**Comment by fkiraly** [comment]
Can you please post self-contained code which triggers the error?

**Comment by fkiraly** [comment]
Might be the same as https://github.com/alan-turing-institute/sktime/issues/3194 and simply due to a too small training set in the `ConformalIntervals` - each wrapper reduces the number of training points, so ensembling inside the conformal interval wrapper might reduce the training set size to zero and trigger the error.

**Comment by fkiraly** [comment]
reporter did not engage (did not post code), so cannot reproduce this
