### ISSUE TITLE
[BUG] `TrendForecaster` gives incorrect output

### ISSUE THREAD

**Issue by eggboy42** [sktime/sktime#3230]
**Describe the bug**
The TrendForecaster produces unusual outputs on levels different from the target series.

**To Reproduce**

```python
from sktime.datasets import load_airline
from sktime.forecasting.trend import TrendForecaster
from sktime.utils.plotting import plot_series

y = load_airline()
forecaster = TrendForecaster()

y_preds = []
for last_train in [20, 40, 60, 80]:
    forecaster.fit(y[:last_train])
    y_pred = forecaster.predict(fh=[1,2,3,4,5])
    y_preds.append(y_pred)

plot_series(y, *y_preds)
```

**Expected behavior**
The forecasts should be straight lines extrapolating the linear historical trend.

**Additional context**
Would expect that the default behaviour is similar to the default behaviour of the `PolynomialTrendForecaster`. In `TrendForecaster`, the `X` is calculated as
```python
X = y.index.astype("int").to_numpy().reshape(-1, 1)
```
whereas in the polynomial version, it is calculated as
```python
n_timepoints = _get_duration(self._y.index, coerce_to_int=True) + 1
X = np.arange(n_timepoints).reshape(-1, 1)
```

**Versions**
<details>

System:
    python: 3.8.13 (default, Apr 19 2022, 00:53:22)  [GCC 7.5.0]
executable: /usr/bin/python3.8
   machine: Linux-5.4.72-microsoft-standard-WSL2-x86_64-with-glibc2.27

Python dependencies:
          pip: 22.0.4
   setuptools: 56.0.0
      sklearn: 1.1.2
       sktime: 0.13.0
  statsmodels: 0.13.2
        numpy: 1.22.4
        scipy: 1.8.1
       pandas: 1.4.3
   matplotlib: 3.5.2
       joblib: 1.1.0
        numba: 0.56.0
     pmdarima: None
      tsfresh: None

</details>

**Comment by fkiraly** [comment]
This should be fixed now here: https://github.com/sktime/sktime/pull/4133

Cause is the same as bug https://github.com/sktime/sktime/issues/4131 - conversion to integer was erroneous for time stamp indexed time series.

**Comment by fkiraly** [comment]
WIth #4133, the plot looks now as it should:
![image](https://user-images.githubusercontent.com/7985502/214433921-b14959de-4b4b-438a-986f-1d4c5d4c9c98.png)
