### ISSUE TITLE
[BUG] `WindowSummarizer` error when used in recursive reducer

### ISSUE THREAD

**Issue by fkiraly** [sktime/sktime#3253]
From stackoverflow here:
https://stackoverflow.com/questions/73325333/call-windowsummarizer-from-sktime-recursively-to-the-forecasting-target-y-in

original message on stackoverflow:

---

I need help on how to use the WindowSummarizer function from the SKTIME library recursively in the future.

Because in the training and test data it is easy to generate the variables of moving averages and moving standard deviations.

But for future predictions, the WindowSummarizer function has to work interactively, with each new predicted observation, WindowSummarizer must recalculate all variables and thus make the next prediction, recursively, until the end.

Can anyone help me?

Follow a reproducible example:

```python
#!pip install sktime[all_extras]

import pandas as pd
import numpy as np
from sktime.transformations.series.summarize import WindowSummarizer
from sktime.forecasting.base import ForecastingHorizon
from sktime.forecasting.compose import ForecastingPipeline
from sklearn.linear_model import LinearRegression
from sktime.datasets import load_airline
from sktime.forecasting.model_selection import temporal_train_test_split
from sktime.forecasting.compose import make_reduction, TransformedTargetForecaster

y = load_airline()

kwargs = {
        "lag_feature": {
            "lag": [0,1],
            "mean": [[0, 7], [0, 14],[0, 28]],
            "std": [[0, 7], [0, 14],[0, 28]],
            "kurt": [[0, 7], [0, 14],[0, 28]],
            "skew": [[0, 7], [0, 14],[0, 28]]
        }
    }


forecaster = make_reduction(
    LinearRegression(),
    scitype="tabular-regressor",
    transformers=[WindowSummarizer(**kwargs, n_jobs=1,truncate = "bfill")],
    window_length=None,
    strategy="recursive"
)

pipe = ForecastingPipeline(
    steps=[
        ("forecaster", forecaster),
    ]
)

model = pipe.fit(y)

model.predict(fh = np.arange(1,100,1))
```

This code return the error message:

`Input contains NaN, infinity or a value too large for dtype('float64').`

**Comment by fkiraly** [comment]
FYI @danbartl

**Comment by fkiraly** [comment]
I wonder, would we expect this to not break?

For reduced regression, the `WindowSummarizer` would need to produce values far enough in the future (up to 100 periods) - but from the settings it looks like that it does not?

**Comment by mairassa** [comment]
Hello guys.

I was trying to use WindowSummarizer() in the same style as recursive() command from modeltime library in R, like showed in this link:  https://business-science.github.io/modeltime/articles/recursive-forecasting.html

**Comment by fkiraly** [comment]
Hm, I might not fully understand the algorithm that you are trying to run here.
From a very naive inspection, your exogeneous lags are not compatible with the forecasting horizon values.
Could you explain?

Here's my understanding so far:

For recursive regression with exogeneous data (coming from the `WindowSummarizer`, do you not need exoeneous data (actual/observed, or lagged) being present at all the future indices that you want to forecast at?

E.g., if you try to forecast 100 periods ahead, would you not have to choose lags in the `WindowSummarizer` so you have summaries available for 100 periods ahead, which, say, for the mean, requires you to have `X` windows being observed between 73 and 100 periods ahead?

**Comment by fkiraly** [comment]
>Hello guys

PS: we're not just guys.

**Comment by danbartl** [comment]
Hi the issue here is that you use kurtosis and skewness over a window for which your forecasting model(linear regression) creates all constant values. 

Kurtosis and skewness are not defined for constant values however if I am not mistaken, so pandas kurtosis and skewness function return NAs, which in turn are not handled by linear regression - leading to the error. 

So either pass your own function definition for skewness and kurtosis that can handle those values, or choose a different forecasting model.

**Comment by fkiraly** [comment]
@danbartl are you saying that kurtosis and skewness need more than 7 values?

**Comment by danbartl** [comment]
@fkiraly NO kurtosis and skewness are not defined for constant values (since you divide by deviation to the power of 4). And since the forecast generates constant values, you will get NA.

![image](https://user-images.githubusercontent.com/19947407/190957740-d0bc60dd-d7e7-4797-b548-76b399bf5b17.png)

**Comment by fkiraly** [comment]
oh, of course. Not a bug.
