### ISSUE TITLE
[DOC] Document tags

### ISSUE THREAD

**Issue by lmmentel** [sktime/sktime#3280]
#### Describe the issue linked to the documentation

Tags are increasingly used in estimators but are not documented anywhere. Neither what tags are available (in use), how to use them, when to use which tag, how to add new tags, how to remove obsolete tags etc.

#### Suggest a potential alternative/fix

Add documentation for tags.

**Comment by fkiraly** [comment]
made an effort in the forecasting extension template here: https://github.com/alan-turing-institute/sktime/pull/3334

What do you think, @lmmentel?

**Comment by fkiraly** [comment]
Forecaster and transformer tags are now explained in their respective extension templates. Would appreciate review and comments.
