### ISSUE TITLE
[ENH] Data Loader for M5 Dataset

### ISSUE THREAD

**Issue by TNTran92** [sktime/sktime#3296]
**Is your feature request related to a problem? Please describe.**

At the moment, there is no data loader for M5 dataset. Addition of this dataset will help greatly enhance our bench marking ability. The M5 dataset gives historical sales data and asked users to predict sales for two 28-day time periods. The dataset contains the following files:
* calendar.csv - Contains information about the dates on which the products are sold.
* sales_train_validation.csv - Contains the historical daily unit sales data per product and store [d_1 - d_1913]
* sample_submission.csv - The correct format for submissions.
* sell_prices.csv - Contains information about the price of the products sold per store and date.
* sales_train_evaluation.csv - Includes sales [d_1 - d_1941] (labels used for the Public leaderboard)

Original data can be found at [Kaggle](https://www.kaggle.com/competitions/m5-forecasting-accuracy/data)

**Describe the solution you'd like**
A dataset loader for M5 dataset. It'll work as follows:
`load_M5()`
The result will be (a) Dataframe(s) in memory or a Callable that fetches data as the forecasting goes on. The dataset loader will prepare the dataset so that it's ready for use.

**Describe alternatives you've considered**
N/A

**Additional context**

**Comment by fkiraly** [comment]
(could you kindly add descriptive issue text?)

**Comment by TNTran92** [comment]
> 

Added some descriptive text

**Comment by TNTran92** [comment]
> (could you kindly add descriptive issue text?)

Added some descriptive text

**Comment by TNTran92** [comment]
There are 5 .csv files regarding this dataset: 
`calendar.csv`: (1969 records) full time series from 2011-01-29 to 2016-06-19 with event names, event type and other events 
`sales_train_evaluation.csv`: (1942 records) unit sale for each product across department, category, store and state
`sales_train_validation.csv`: (1914 records) unit sale for each product across department, category, store and state
`sample_submission.csv`: example submission
'sell_prices.csv': unit price for each product

The goal is to predict unit sale of each product in 2 2-weeks periods. The first period is between `validation` and `evaluation` dataset. `evaluation` will be used as test set for this period. The second 2-week period is between `evaluation` and `calendar`. There is no test data.

The goal is to make 2 types of predictions: point forecast (accuracy) and prediction interval (uncertainty)

**Comment by TNTran92** [comment]
`calendar.csv`
![image](https://user-images.githubusercontent.com/55965636/189561351-af764f17-ef53-439c-bd7a-4b827fe35793.png)

**Comment by TNTran92** [comment]
`sale_train_evaluation.csv`
![image](https://user-images.githubusercontent.com/55965636/189561391-22361b5b-28d4-4a35-a565-be8ffe6f9118.png)

**Comment by TNTran92** [comment]
`sale_train_validation.csv`
![image](https://user-images.githubusercontent.com/55965636/189561446-686326ca-c041-4512-a073-def414d35ed6.png)

**Comment by TNTran92** [comment]
Both `sale_train_evaluation.csv` and `sale_train_validation.csv` can be processed as follows:
- MultiIndex DataFrame with level 0 being `item_id` and level ` being time series
- Each level 0 is combined with `calendar` to bring in spot demand information
- One hot encoded dept_id, cat_id, store_id, and state_id

**Comment by topher-lo** [comment]
@TNTran92 I have this simple utility function for joining panel, time-series, and cross-sectional data that might help:
```python
def reshape_X_into_panel(
    panel_idx: pd.MultiIndex,
    X_static: Optional[pd.DataFrame] = None,
    X_ts: Optional[pd.DataFrame] = None,
    X_panel: Optional[pd.DataFrame] = None,
) -> Union[pd.DataFrame, None]:
    """Combines cross-sectional, time-series, and panel data into single
    panel DataFrame with (time, entity) multi-index ready for use in
    Global forecasters

    Parameters
    ----------
    panel_idx : pd.MultIndex[DatetimeIndex, CategoricalIndex]
        (time, entity) multi-index.
    X_static : pd.DataFrame, optional (default=None)
      Cross-sectional data with single (entity) CategoricalIndex.
    X_ts : pd.DataFrame, optional (default=None)
      Time-series data with single (time) DatetimeIndex.
    X_panel : pd.DataFrame, optional (default=None)
      Panel data with multi-index ordered by (time, entity).

    Returns
    -------
    X_transf : pd.DataFrame panel data.

    Raises
    ------
    ValueError : if index names are not equal
    """

    panel_df = None
    entity_col, time_col = panel_idx.names

    if X_panel is not None:
        X_panel = X_panel.reindex(panel_idx)

    if X_static is not None:
        panel_df = panel_idx.to_frame(index=True).loc[:, [time_col]]
        X_static = panel_df.join(X_static, how="left", on=entity_col).pipe(
            lambda df: df.loc[~df.index.duplicated()]
        )

    if X_ts is not None:
        panel_df = panel_idx.to_frame(index=True).loc[:, [entity_col]]
        X_ts = panel_df.join(X_ts, how="left", on=time_col).pipe(
            lambda df: df.loc[~df.index.duplicated()]
        )

    X_transf = pd.concat([X_static, X_ts, X_panel], axis=1)
    return X_transf
```

**Comment by fkiraly** [comment]
@tntran92, @topher-lo, are you still working on this?

FYI @kishmanani, since you said you were loading the M5 data set recently.

**Comment by KishManani** [comment]
I saw that some of the smaller datasets are [stored in the package itself](https://github.com/sktime/sktime/tree/main/sktime/datasets/data). Out of curiosity, where would the data be stored? Some files are 120 MB.

**Comment by fkiraly** [comment]
> Out of curiosity, where would the data be stored?

Well, hopefully not in the repo itself.

The solution could be just as for the classification data sets, see, e.g., `load_UCR_UEA_dataset` which loads from a third party repository that follows a unified data set structure.

I would simply generalize that if it were me starting to do it naively, but there might be some difficulties which I might not be seeing.

**Comment by topher-lo** [comment]
@fkiraly @KishManani if you preprocess the data's dtypes into their most efficient form (strings to category, shrink numerical columns) and save it as a parquet file. It's only a few MiB at most.

**Comment by fkiraly** [comment]
>@fkiraly @KishManani if you preprocess the data's dtypes into their most efficient form (strings to category, shrink numerical columns) and save it as a parquet file. It's only a few MiB at most.

Ouch. Really? That seems like very inefficient compression in its native form. Or, whatever the opposite of "data compression" is. Data inflation? Data bloat?

**Comment by topher-lo** [comment]
The original file is CSV. And the most memory inefficient column are the string IDs. These are be converted to category dtype in parquet and with significant compression. In parquet, the values in the column array of a categorical column are actually integer IDs in memory.

**Comment by topher-lo** [comment]
I used to have the file itself somewhere, but Im sure I can dig out the code to generate it direct from source. Will update this thread on Monday

**Comment by RNKuhns** [comment]
> @fkiraly @KishManani if you preprocess the data's dtypes into their most efficient form (strings to category, shrink numerical columns) and save it as a parquet file. It's only a few MiB at most.

I believe parquet also uses run-length encoding so that it doesn't have to store every value when there are consecutive values. In most efficient case with constant values it essentially stores value and count of contiguous values. So for low-cardinality columns, even if they are string values, parquet can be very efficient (assuming same values are contiguous).

Storing the dataset with sorted values (so that columns with larger storage format and low-ish cardinality are sorted for contiguous values) also leads to good compression. Doing that and using categorical dtypes (or mapping to integer lookup values) can result in even smaller sizes. For most efficiency, can also cast type to lower storage requirement (e.g., int8 or int16 instead of int64, if cardinality is low enough to allow those types to be used).

**Comment by RNKuhns** [comment]
> > @fkiraly @KishManani if you preprocess the data's dtypes into their most efficient form (strings to category, shrink numerical columns) and save it as a parquet file. It's only a few MiB at most.
> 
> I believe parquet also uses run-length encoding so that it doesn't have to store every value when there are consecutive values. In most efficient case with constant values it essentially stores value and count of contiguous values. So for low-cardinality columns, even if they are string values, parquet can be very efficient (assuming same values are contiguous).
> 
> Storing the dataset with sorted values (so that columns with larger storage format and low-ish cardinality are sorted for contiguous values) also leads to good compression. Doing that and using categorical dtypes (or mapping to integer lookup values) can result in even smaller sizes. For most efficiency, can also cast type to lower storage requirement (e.g., int8 or int16 instead of int64, if cardinality is low enough to allow those types to be used).

We don't really need it for our use case, but pyarrow (Python bindings to Apache Arrow) has good tools for this.

**Comment by SaiRevanth25** [comment]
Hey! I'm interested in working on this issue.

**Comment by fkiraly** [comment]
Reassigning - @TNTran92 is disengaged since 2022.

I think the two main questions to answer are:

* data source: where do we store it? We can use GitHub large file storage, <1 GB is free, or hugging face, or kaggle.
    * we should check whether hugging face or kaggle allow downloads from there directly
* formatting questions. Some code snippets and issues above.

**Comment by SaiRevanth25** [comment]
*  [Huggingface](<https://huggingface.co/docs/huggingface_hub/en/guides/download>) allows direct downloads using the Hugging Face datasets library.
* Kaggle supports direct downloads via the Kaggle API.

**Comment by fkiraly** [comment]
oh, Makridakis uploaded it to hugging face? That solves hte problem of hosting. We then just need a utility to convert to `sktime` format. I suppose we want the users to be able to access the series individually, with an index?
