### ISSUE TITLE
[ENH]

### ISSUE THREAD

**Issue by R470R** [sktime/sktime#3347]
**Is your feature request related to a problem? Please describe.**
Can't use my normal stored locally csv

**Describe the solution you'd like**
Is there some simple way for me to turn a normal csv file (ex Date Open High Low Close) to the required format for multivariate timeseries classification?

**Describe alternatives you've considered**
tried multiple ways to reshape but still receive error

**Additional context**
I think would be very useful for a lot of people

**Comment by fkiraly** [comment]
please describe the format of your `csv` file, after you loaded it via `pandas`.
Optimally, please provide code that constructs a dummy data container similar to the format you have.

**Comment by R470R** [comment]
Hello Sir, here is dummy data constructor
import random
import pandas as pd

Open = []
High = []
Low = []
Close = []
MA = []
Volume = []
Minute = []
Hour = []
Day = []
Week = []
Selected = []
is_beg = []

for i in range(1000):
    Open.append(random.uniform(-0.55258, 1.68521))
    High.append(random.uniform(-0.55350, 1.70000))
    Low.append(random.uniform(-0.55258, 1.68321))
    Close.append(random.uniform(-0.55350, 1.69000))
    MA.append(random.uniform(-0.55258, 1.68521))
    Volume.append(random.random())
    Minute.append(random.randint(0, 60))
    Hour.append(random.randint(0, 24))
    Day.append(random.randint(0, 30))
    Week.append(random.randint(1, 48))
    Selected.append(random.randint(0, 7))
    is_beg.append(random.randint(0, 1))
    
my_pd=pd.DataFrame(data=[Open,High,Low,Close,MA,Volume,Minute,Hour,Day,Week,Selected,is_beg]).T 
my_pd.columns=['Open','High','Low','Close','MA','Volume','Minute','Hour','Day','Week','Selected','is_beg']
my_pd

**Comment by R470R** [comment]
Label to predict is Selected &| is_beg

**Comment by fkiraly** [comment]
hm, this does not look like time series classification?
Time series classification is one label per time series, and having multiple time series.
You have only one time series, and one lable per time stamp.

So, this looks like supervised time series annotation, on a single time series.

**Comment by R470R** [comment]
Yes it is!
How do I tune this data to use those incredible sktime tools?
