### ISSUE TITLE
[ENH] Migrate from `sphinx-panels` to `sphinx-design`

### ISSUE THREAD

**Issue by achieveordie** [sktime/sktime#3370]
**Is your feature request related to a problem? Please describe.**
Currently, we're using `sphinx-panel` as an [extension](https://github.com/alan-turing-institute/sktime/blob/3c56f535dc1d060c0053ab6c7f1a1a7199133539/docs/source/conf.py#L51) to build documentation. However, in the current state, `sphinx-panel` is not being actively [maintained](https://github.com/executablebooks/sphinx-design/issues/51) and they suggest using [`sphinx-design`](https://github.com/executablebooks/sphinx-design) instead.

**Describe the solution you'd like**
There is a migration [guide](https://sphinx-design.readthedocs.io/en/latest/get_started.html#migrating-from-sphinx-panels) which can be followed. Changes involve replacing `panel`, `link-button` etc. directives with their updated versions. It might not be as simple as refactoring the names since there seem to be some differences in their formatting as well.

**Comment by miraep8** [comment]
Is this issue now close-able?

**Comment by fkiraly** [comment]
Yes, the PR https://github.com/sktime/sktime/pull/3575 was merged, so this is resolved.
