### ISSUE TITLE
[ENH] DOBIN transformer implementation

### ISSUE THREAD

**Issue by KatieBuc** [sktime/sktime#3371]
Distance based Outlier BasIs using Neighbors (DOBIN).
    
DOBIN is a pre-processing algorithm that constructs a set of basis
vectors tailored for outlier detection as described by _[1]. DOBIN
has a simple mathematical foundation and can be used as a dimension
reduction tool for outlier detection tasks. 

Currently (only) implemented in R.

Reference:
[1] Kandanaarachchi, Sevvandi, and Rob J. Hyndman. "Dimension reduction
for outlier detection using DOBIN." Journal of Computational and Graphical
Statistics 30.1 (2021): 204-219.

Paper: 
https://robjhyndman.com/papers/dobin.pdf

Code to re-write:
https://github.com/sevvandi/dobin/blob/master/R/dobin.R

**Comment by lmmentel** [comment]
closed by #3373
