### ISSUE TITLE
[ENH] ForecastingBayesianSearchCV, skopt interface

### ISSUE THREAD

**Issue by hliebert** [sktime/sktime#3390]
Would it be possible to add support for Bayesian search, e.g. make skopt.BayesSearchCV accessible through ForecastingBayesSearchCV? Similar to how ForecastingGridSearchCV provides an interface to GridSearchCV from sklearn. 

This would be a great help to tune more complex models with large parameter space.

**Comment by fkiraly** [comment]
Yes, great idea!

Perhaps we could, in a second step, also add an abstraction step to what search algorithm is being used.

**Comment by GigaMoksh** [comment]
Hi, I'd like to work on this. Just need a quick tip on where to start

**Comment by fkiraly** [comment]
thanks, @GigaMoksh!

This would be very similar to `ForecastingGridSearchCV`, that would be a good place to start.

You may also like the "implementing estimators" guide, which has a link to a tutorial video:
https://www.sktime.org/en/stable/developer_guide/add_estimators.html
