### ISSUE TITLE
[ENH] Fourier transform

### ISSUE THREAD

**Issue by fkiraly** [sktime/sktime#3406]
We have Fourier features now (for forecasting), but we should also interface the simple Fourier transform, which transforms a series from time domain to frequency domain.

That would be useful for time series classification, or for seasonality parameter estimation.

**Comment by silvererudite** [comment]
Hi is this issue up for grabs? I'd love to contribute...would love to dive into any references or pointers to get started as well...thanks

**Comment by fkiraly** [comment]
up for grabs indeed!

A good starting point would be https://numpy.org/doc/stable/reference/routines.fft.html which we may simply want to interface.

**Comment by silvererudite** [comment]
> up for grabs indeed!
> 
> A good starting point would be https://numpy.org/doc/stable/reference/routines.fft.html which we may simply want to interface.

Thanks for the pointer...getting on it

**Comment by blazingbhavneek** [comment]
Is this issue sorted or can I take this on? I would love to with a little guidance @fkiraly

**Comment by fkiraly** [comment]
I suppose silence for a month may mean @silvererudite is no longer working on this - are you still on this?

Either way, there are *two* potential things to implement:
* a transformer, which given a series outputs the fourier spectrum
* a parameter estimator, which estimates the seasonality parameter by a spectrum power related test

Here's the developer guide for adding a new estimator: https://www.sktime.org/en/stable/developer_guide/add_estimators.html

**Comment by blazingbhavneek** [comment]
Hey! I am back from my holiday break. Hopefully, you are doing well @fkiraly ! I got a general idea of what I must do for this, but I need help with where to start. Can you point me to the file(s) for starting points/examples of implementation?

**Comment by fkiraly** [comment]
Of course!

* Here's the developer guide for adding a new estimator: https://www.sktime.org/en/stable/developer_guide/add_estimators.html
* A good starting point could be https://numpy.org/doc/stable/reference/routines.fft.html which we may simply want to interface.

**Comment by blazingbhavneek** [comment]
Hi! @fkiraly. I have a question related to the task; fft requires evenly-spaced signal samples; should I assume the user knows this? Or should I implement something as below

1.  take user input for the frequency of sampling and the start date(can be the default), then filter out the periodic data and ignore the rest. (Also giving user warning that some data is not used), if filtered data's size<some value % of original, return an error.
2. A simple checker, if data is not filtered well by the user, then returns an error
3. implementing a non-equispaced Fourier transformer

**Comment by fkiraly** [comment]
hm, @blazingbhavneek, that's indeed an interesting question.

I would go ahead and first just interface the `numpy` method, and use the `iloc` index rather than the `loc` index. This should be said clearly in the docstring, and it will result in an evenly-spaced sequence/signal.

Discrete Fourier transforms are defined on a non-equally-spaced signal as well, typically this is generalized by taking the delta signal supported at the indices in the general form of the (non-discrete) Fourier transform, although it is less common in practice afaik.

For the latter, I would suggest:

* start with the `iloc` one first, this is a straightforward interfacing task
* in a second step, if you like, you can add non-equally spaced DFT. My approach would actually be a little "trick" where you stick the additional phase from the unequal spacing in the complex part of the coefficients. As `numpy` can deal with complex coefficients, that should (I hope) work? I would switch via a transformer parameter, e.g., `indexing` that can be `"iloc"` or `"loc"`.

**Comment by fkiraly** [comment]
Resolved by #4214
