### ISSUE TITLE
[BUG] `ConformalIntervals` update does not update residuals_matrix

### ISSUE THREAD

**Issue by bethrice44** [sktime/sktime#3419]
**Describe the bug**

`ConformalIntervals` update only updates the forecaster, not the residuals_matrix for predicting intervals or quantiles.

**To Reproduce**

`_update` is defined as:

```
    def _update(self, y, X=None, update_params=True):
        self.forecaster_.update(y, X, update_params=update_params)
        return self
```

which is only updating the forecaster and no the residuals_matrix. Since the forecaster is already fitted when `update` is called, the residuals_matrix is set to the fitted one with:

```
  if self.fh_early_:
      residuals_matrix = self.residuals_matrix_
```

**Expected behavior**

The residuals_matrix should be updated with the new data.

**Comment by fkiraly** [comment]
Hm, I think both options are valid, but updating the residuals matrix should probably be the default.
Should we introduce a parameter `update_residuals` or similar?

**Comment by bethrice44** [comment]
> Hm, I think both options are valid, but updating the residuals matrix should probably be the default. Should we introduce a parameter `update_residuals` or similar?

Yes that makes sense to me (with `True` as default). Just figuring out the cleanest way to extend it without recalculating the whole thing (since there is a good chance a large portion of it has already been calculated).

**Comment by fkiraly** [comment]
I think a pain point that some forecaster fitted states have already been reached in `fit`, so there's a tradeoff between memorizing (memory use) and recomputing (compute use)
