### ISSUE TITLE
[DOC] Broken rendering of html docs in developer documentation

### ISSUE THREAD

**Issue by lmmentel** [sktime/sktime#3421]
#### Describe the issue linked to the documentation

Dependency types should be rendered as a list (see https://www.sktime.org/en/stable/developer_guide/dependencies.html): 

![image](https://user-images.githubusercontent.com/8989838/189866612-087a61fb-c981-4e68-a286-6a45d0bafd5c.png)

**Comment by EmptySet-Exe** [comment]
Would it be alright that I contribute to this issue?

**Comment by fkiraly** [comment]
dependentiae sunt omnes divisae in partes tres

**Comment by templierw** [comment]
I'm on it
