### ISSUE TITLE
[MNT] Move repo to sktime org

### ISSUE THREAD

**Issue by aiwalter** [sktime/sktime#3424]
**To do's**
before next release we need to do:
- [x] Bulk replace all "alan-turing-institute/sktime" in main repo
- [ ] Bulk replace all "alan-turing-institute/sktime" in all other repos
- [x] Change read-the-docs
- [x] Move to sktime org
- [ ] Share new repo via social media

**Comment by fkiraly** [comment]
ref changes here: https://github.com/alan-turing-institute/sktime/pull/2926

I also think we should make two releases in short succession - so one release increases MINOR and the only change is the change of refs
