### ISSUE TITLE
[BUG]’write_dataframe_to_tsfile‘ doesn't work for length-unequal series

### ISSUE THREAD

**Issue by dirtypuddin** [sktime/sktime#3499]
**Describe the bug**
I'm trying to make my own .ts format dataset using the function write_dataframe_to_tsfile.
There is no clear statement about whether length-unequal time series is  supported in the definition of function 'write_dataframe_to_tsfile'. 
There is a parameter named 'equal_lenth', which indicates whether each series is of equal length. And this parameter is 'False' in default. So I think it means this fuction support length-uneuqal series. 
 However, if I provide **a time series with 2 variates, 250 cases in different length**,  this function will returns '**ValueError: all input arrays must have the same shape'**.If I keep those cases in same length, it works. 
I think it maybe a bug? 

**To Reproduce**
I provide the following code to reproduce the bug.
PS: one of length-equal variable df1 has been commented out.

```python
import pandas as pd
from sktime.datasets import write_dataframe_to_tsfile
from sktime.datatypes._panel._convert import from_multi_index_to_nested

##df1=pd.DataFrame([[1,1,1,1],[1,2,2,2],[2,3,3,3],[2,4,4,4],[2,5,5,5],[3,6,6,6]],columns=['a','b','c','d'])
df1=pd.DataFrame ([[1,1,1,1],[1,2,2,2],[2,3,3,3],[2,4,4,4],[3,5,5,5],[3,6,6,6]],columns=['a','b','c','d'])

df1.set_index(keys=['a','b'],inplace=True)
print(df1)

Y_nested = from_multi_index_to_nested(df1)
##print(Y_nested.head())
write_dataframe_to_tsfile(data=Y_nested,equal_length= False,fold='_TRAIN',path='./path')
```

**Expected behavior**

**Additional context**
Providing length-unequal time series is important, because even the same motion may cost time more or less. 
Besides, there are some length-unequal time series archieve in UCR archieve, such like Basic_Motions so  i think sktime is supposed to provide a way for user to create a length-unequal time series in .ts format. 

**Versions**
sktime 0.13.2

</details>

**Comment by dirtypuddin** [comment]
About the func write_dataframe_to_tsfile, I linked this issue to #438 #1278

**Comment by TonyBagnall** [comment]
hi, thanks for that, I'll look into it

**Comment by dirtypuddin** [comment]
In fact, I've generated .ts format data correctly with length-equal data. And since sktime do not support generate  .ts format length-unequal time series for now, I'd like to give a temporary way to realize it. This way uses TimeseriesResampler module from tslearn to convert time series to equal length. Although this way may cause slower computing speed and complicate transfer between DataFrame and Ndarray format, it works well in my computer. I'm not a expert in coding but I'd like to share it if it does help anyone.
