### ISSUE TITLE
[BUG] ColumnEnsembleForecaster fails with `str` indices

### ISSUE THREAD

**Issue by canbooo** [sktime/sktime#3502]
**Describe the bug**
`ColumnEnsembleForecaster` raises an error, when defined over `str` indices (of a dataframe). Specifically [this](https://github.com/sktime/sktime/blob/4194aacaa105ef59807ea56c1bb3497b37eb1613/sktime/forecasting/compose/_column_ensemble.py#L397-L400) error is raised, since the logic there does not account for string indice.

**To Reproduce**

```python
>>> df = pd.DataFrame({"a": [1, 2, 3], "b": [4, 5, 6]})
>>> fc = ColumnEnsembleForecaster([(f"trans_{col}", NaiveForecaster(), col) for col in "ab"])
>>> fc.fit(df)

ValueError: One estimator per column required. Found 2
```

**Expected behavior**
Being able to use `str` indices as describe in the [docstring](https://github.com/sktime/sktime/blob/4194aacaa105ef59807ea56c1bb3497b37eb1613/sktime/forecasting/compose/_column_ensemble.py#L23-L24)
>     forecasters : sktime forecaster, or list of tuples (str, estimator, int or str)
        if tuples, with name = str, estimator is forecaster, index as str or int

**Additional context**
I suspect that the same error will be produced with other `ColumnEnsemble...` objects but I did not check.

**Versions**
<details>
System:
    python: 3.9.5 (default, Nov 23 2021, 15:27:38)  [GCC 9.3.0]
executable: .../bin/python
   machine: Linux-5.4.0-1084-aws-x86_64-with-glibc2.31

Python dependencies:
          pip: 21.2.4
   setuptools: 58.0.4
      sklearn: 0.24.2
       sktime: 0.13.4
  statsmodels: 0.12.2
        numpy: 1.20.3
        scipy: 1.7.1
       pandas: 1.3.4
   matplotlib: 3.4.3
       joblib: 1.0.1
        numba: 0.56.2
     pmdarima: None
      tsfresh: None

</details>

**Comment by fkiraly** [comment]
Thanks for reporting!

I think I've fixed the bug: https://github.com/sktime/sktime/pull/3504
While looking at it, I've also extended the `ColumnEnsembleForecaster` to allow multivariate forecasters too.

**Comment by canbooo** [comment]
Thanks for the quick response!

**Comment by fkiraly** [comment]
not completed yet! This will be closed once the PR is merged.

**Comment by fkiraly** [comment]
now 😄
