### ISSUE TITLE
[ENH] `tsfresh` transformers - improved signature, custom features, docstring

### ISSUE THREAD

**Issue by juliencarponcy** [sktime/sktime#3526]
update by @fkiraly:

`TSFreshFeatureExtractor` is not in a good state, we need:

* a clean and clear docstring, which also describes parameters, and explains pre-defined and user specified parameter sets.
* a parameter that allows the user to specify the features they would like to extract (this may already exist)
* possibly some changes in what the parameters are to make it more user friendly (may need deprecation)
* `get_test_params` with at least two test cases, one with prespecified parameter set and one with a custom specified parameter set.

---

**Is your feature request related to a problem? Please describe.**

Hi, I'm not sure if my issue is related to something not implemented or if I just don't know how to perfom it.
Basically, I would like to use the extract_features() method of tsfresh just to extract a subset of features defined in a dictionary, which would be different than the 'minimal','efficient' or 'comprehensive' option. 
If possible still using default parameters for this subset of features: 

```
from sktime.transformations.panel.tsfresh import TSFreshFeatureExtractor

features_to_calc = [
    'absolute_sum_of_changes',
    'absolute_maximum',
    'agg_linear_trend',
    'large_standard_deviation',
    'longest_strike_above_mean',
    'longest_strike_below_mean',
    'mean_abs_change',
    'mean_change',
    'quantile',
    'variance_larger_than_standard_deviation',
    'variance',
]

features_dict = dict.fromkeys(features_to_calc, None)
```

If I try the following, it extracts every features of the default or other settings (which is obviously very long except for minimal setting), without considering my dictionary (name of features as keys, None as values)

```
from sktime.transformations.panel.tsfresh import TSFreshFeatureExtractor
tsfresh = TSFreshFeatureExtractor(kind_to_fc_parameters=features_dict)

X_transform = tsfresh.fit_transform(panel_data)
```

Am I missing something or is it just not implemented yet for consistency with other transformers?

**Describe the solution you'd like**

Would it be possible to extend tsfresh extract_features() method to panel dataset in sktime, for instance using the following:

```
from sktime.transformations.panel.tsfresh import TSFreshFeatureExtractor
tsfresh = TSFreshFeatureExtractor(kind_to_fc_parameters=features_dict)

X_transform = tsfresh.extract_features(panel_data)
```

**Describe alternatives you've considered**
I referred to  https://github.com/blue-yonder/tsfresh/blob/main/notebooks/examples/03%20Feature%20Extraction%20Settings.ipynb
but only the not so convenient tsfresh dataformat are supported, so maybe instead I should transform my data to fit in one of the tsfresh format? If this case is the easiest, I could use a few lines to help since it is not clear how could i get there with the page https://www.sktime.org/en/stable/examples/AA_datatypes_and_datasets.html

**Additional context**
Relative to that alternative solution, completing the datasets types notebook referred previously with a canva, to convert from one or a few tsfresh format to one or a few sktime format would be ideal (only for a few ultivariate options which are more convenient from one package to the other...)

Thanks very much in advance for your help, and for your work,

Julien

**Comment by fkiraly** [comment]
ok, I think there are two issues here:
* support for user specified feature set
* support for panel data (features per instance)

The second should be out-of-the-box, if you pass a panel data container to the transformer, it applies the transformation to each instance separately.

From a glance at the code, the first is indeed not implemented, and the transformer itself is badly documented, this needs to be improved.

**Comment by fkiraly** [comment]
I turned this issue into an "improve the tsfresh feature extractor" one since imo we need to do that.

**Comment by fkiraly** [comment]
I looked into it more, the parameter passing logic resides in `_get_extraction_params`, by that it appears that the `tsfresh` default of `default_fc_parameters=None` is overridden by `"efficient"`, perhaps that is the root cause?

Either way, having a docstring with examples, and also test parameters in `get_test_params` would be great.
