### ISSUE TITLE
[BUG] Broken link to slack

### ISSUE THREAD

**Issue by pranavvp16** [sktime/sktime#3530]
update from @GianlucaGuarroSonos:
The link in the README works but the link available after clicking "New Issue" does not

---

**The link of Slack channel link in Readme seems to be incomplete or has a typo **

Whenever I try to open the link error message "can't reach this page" prompts on my browser  

**To Reproduce**

Try opening the link of Slack channel in other browser's, also try to paste the link in Slack's android app, there it pops up with error message "Something's amiss with your invitation. Please contact your Org Owner and ask them to resend it "

**Expected behavior**

If working fine the link should direct the user to sktime's slack channel.

**Comment by TonyBagnall** [comment]
thanks for spotting that, we will fix it

**Comment by TonyBagnall** [comment]
hi, this works when I click on it, is this the link you mean? 
![image](https://user-images.githubusercontent.com/9594042/194003274-1e96ca57-40ad-49b7-93c9-9cb8e8e05d7f.png)

**Comment by pranavvp16** [comment]
After brainstorming for a while, I found that slack isn't available to load on some networks. In my case, I had a local network provider which didn't allow slack workspaces to load.

Solution : Try using networks that allow slack workspaces , or use your mobile data on your desktop via hotspot it works. If possible ask your network service provider to approve slack workspaces on the network

Slack(help) has elaborated this issue: https://slack.com/intl/en-in/help/articles/360024821873-Approve-Slack-workspaces-for-your-network

**Comment by GianlucaGuarroSonos** [comment]
The link in the README works but the link available after clicking "New Issue" does not

**Comment by fkiraly** [comment]
ahhhh, thanks for reporting

**Comment by TonyBagnall** [comment]
the new issue button here
![image](https://user-images.githubusercontent.com/9594042/196142529-694d7340-110c-4c55-940e-0d7d7dc416b6.png)
takes you to the sktime slack if you have already joined. However, I asked a friend who is not in our slack to try, and he says "when I clicked on the github link it took me to a page that says: This link is no longer active. To join this workspace, you’ll need to ask the person who originally invited you for a new link."
@fkiraly @aiwalter @GuzalBulatova I think one of the slack owners needs to update the link here

**Comment by pranavvp16** [comment]
@TonyBagnall  as I told ,there's no issue with the link try through our mobile data instead of  wifi , of on PC you hotspot of mobile and open the link it works there's some issue of slack with not verified local service providers. This solution worked for me . I also got the same error message as you mentioned above

**Comment by fkiraly** [comment]
@pranavvp16, thanks for cleaning up - indeed, we have moved to discord now.
