### ISSUE TITLE
[BUG] Prophet forecaster does not work with non-integer forecast horizon during prediction

### ISSUE THREAD

**Issue by GianlucaGuarroSonos** [sktime/sktime#3537]
**Describe the bug**
When attempting to use the prophet forecaster to predict at a non-relative forecasting horizon, it throws an error saying "TypeError: periods must be a number, got 1964-01"

**To Reproduce**
```python
from sktime.forecasting.fbprophet import Prophet
from sktime.datasets import load_airline
from sktime.forecasting.base import ForecastingHorizon
import pandas as pd

y = load_airline().to_timestamp(freq='M')

fh = ForecastingHorizon(
    pd.PeriodIndex(pd.date_range("1961-01", periods=36, freq="M")), is_relative=False
)

forecaster = Prophet(  
    seasonality_mode='multiplicative',
    n_changepoints=int(len(y) / 12),
    add_country_holidays={'country_name': 'UnitedStates'},
    yearly_seasonality=True
)

forecaster.fit(y)

y_pred = forecaster.predict(fh) # ERROR HERE
```

**Expected behavior**
To return the forecasts at the specified forecast horizon the same way it would if it was a relative forecast horizon.

**Additional context**
Relative forecast horizon with integer representation indeed seems to work fine.

**Versions**
System:
    python: 3.8.13 (default, Mar 28 2022, 06:16:26)  [Clang 12.0.0 ]
executable: /Users/gguarro/miniconda3/envs/strategic-finance-forecasts/bin/python
   machine: macOS-10.16-x86_64-i386-64bit

Python dependencies:
          pip: 22.2.2
   setuptools: 59.8.0
      sklearn: 1.1.2
       sktime: 0.13.4
  statsmodels: 0.13.2
        numpy: 1.22.4
        scipy: 1.8.1
       pandas: 1.4.3
   matplotlib: 3.6.0
       joblib: 1.2.0
        numba: 0.56.2
     pmdarima: 2.0.1
      tsfresh: None

**Comment by fkiraly** [comment]
I think I accidentally fixed this bug while reworking the `Prophet` index logic here: https://github.com/sktime/sktime/pull/3995
