### ISSUE TITLE
[BUG] `CNNRegressor` missing essential initializing parameters

### ISSUE THREAD

**Issue by achieveordie** [sktime/sktime#3538]
**Describe the bug**

`CNNRegressor` misses parameters like `optimizer` in its constructor. There might be more things which don't coincide with `CNNClassifier` which should be added but since I'm not sure what all things might be missing, I'm opening this issue to bring it to notice.

**Comment by fkiraly** [comment]
apart from interface homogeneity, are there other reasons to have these parameters?

does it break the save/load interface of neural networks?

**Comment by achieveordie** [comment]
There are three reasons we should have an `optimizer` parameter.
1. save/load interface tries to find and load it, so it does break. We could modify load/save such that it doesn't fail when optimizer is not found but I'd suggest keeping that as it is if we consider points 2 and 3 below.
2. Interface Homogeneity.
3. More flexibility for the user.

**Comment by fkiraly** [comment]
I don't undestand what you are saying. Can you please explain and be more precise here? What object is the problem with?

How is that related to having an `optimizer` parameter. And what object is "we" that should have an `optimizer` parameter?

**Comment by achieveordie** [comment]
Ah, I must have made that comment in a rush, leading to some confusion. Let me start over.

If you compare `CNNClassifier` and `CNNRegressor`, you'd see that parameters like `optimizer` is not present in the latter. On the surface, this implies that the current interface of `CNNClassifier` and `CNNRegressor` is not homogenous and that the user doesn't have the freedom to choose a different optimizer for `CNNRegressor`, they are stuck with the default one. This is what point 2 and 3 was meant to convey.

IMO, these two reasons together warrant us to add an `optimizer` parameter (and any other that may be missing). But there's an additional reason. Save/load assumes that an `optimizer` parameter exists for all DL estimators even if it is `None` (see `__setstate__()` for reference). We probably could modify it to not complain, but then bugs like this might go unnoticed.

I hope things are more clear now.

**Comment by fkiraly** [comment]
not sure, still.
Could you please outline precisely, (explanation or a statement that you aren't entirely clear about it)

1. the precise property that you think `CNNRegressor` does not have and should have
2. the reason why it should have that property, e.g., to confirm with an interface requirement
3. how that relates to the test failure in in #3425, e.g., interface requirement tested by a spefici test?

**Comment by fkiraly** [comment]
> Save/load assumes that an `optimizer` parameter exists for all DL estimators even if it is `None` (see `__setstate__()` for reference).

Is that an interface assumption we want to make for all deep learning estimators?

This might not be a good idea, since some deep learning estimators might hard-code the optimizer or not have a parameter like that.

**Comment by achieveordie** [comment]
> the precise property that you think `CNNRegressor` does not have and should have

`CNNRegressor` should have an `optimizer` parameter in its constructor; even if it's `None`.

> the reason why it should have that property

It gives the user more flexibility to choose which optimizer to use for training and not being stuck with `Adam`.

> how that relates to the test failure

save/load interface expects `optimizer` to be present in it's constructor. I could change it to not complain when not found but the downside would be bugs like this would go unnoticed (at least in the case of `CNNRegressor` it is certainly undesirable to not have an `optimizer`).

Even though this issue is related to `CNNRegressor`, could you give me an example of a DL estimator that doesn't require an optimizer AND is also supported by the current interface that `sktime` provides? I'm failing to see those cases.

**Comment by AurumnPegasus** [comment]
Hey @achieveordie ,
So the reason for difference in `CNNClassifier` was because of the issue/PR at #2935
I had added some parameters which we could add and give user more chances for customisations.
I started of with classifiers and did not do it for regressors as my plan was to finish the migration of classifiers first, but since the migration looks at a good place currently, either me or you can create an issue/pr based on #2935  and update the structure of `CNNRegressor` as well

**Comment by achieveordie** [comment]
I see, thank you. So let me take up this issue. Do you suggest more changes that I should incorporate?
