### ISSUE TITLE
[BUG] check_estimator tests_to_exclude doesn't exclude the specified tests

### ISSUE THREAD

**Issue by ltsaprounis** [sktime/sktime#3565]
**Describe the bug**

Specifying a list of tests in the `tests_to_exclude` variable in `check_estimator` doesn't exclude the specified tests.

**To Reproduce**

```python
from sktime.utils.estimator_checks import check_estimator
from sktime.forecasting.naive import NaiveForecaster

log = check_estimator(
    NaiveForecaster, return_exceptions=True, tests_to_exclude=["test_predict_residuals"]
)

should_be_empty = [key for key in log.keys() if "test_predict_residuals" in key]

assert len(should_be_empty) == 0
```

**Expected behavior**

Any tests in the tests_to_excluded should be actually excluded!
(FYI for whoever takes this on. The problem is somewhere [here](https://github.com/sktime/sktime/blob/fe6f43c2e06e586c2dd16102aef5eef4bd4b6ce6/sktime/tests/test_all_estimators.py#L378))

**Versions**
<details>

sktime==0.13.4  
python==3.8.5
</details>

**Comment by fkiraly** [comment]
Fix here: https://github.com/sktime/sktime/pull/3566

Parameters were not passed on for non-base tests (see the fix). There was a test covering the exclude parameter, but it was tested only on base tests which were excluded fine.
