### ISSUE TITLE
[BUG] CI fails on win with no code changes

### ISSUE THREAD

**Issue by lmmentel** [sktime/sktime#3604]
**Describe the bug**

CI fail on windows with only changes being to sphinx documentation rst files and no code changes. Noticed in  https://github.com/sktime/sktime/pull/3603

![image](https://user-images.githubusercontent.com/8989838/196434625-6fbb1d66-41a6-4d85-8204-d2df8e068923.png)

**To Reproduce**

```python
<Paste your code here>
```

**Expected behavior**

**Additional context**

**Versions**
<details>

</details>

**Comment by TonyBagnall** [comment]
this is odd, failing on mine too, and I ran all tests locally on windows and it all passed
![image](https://user-images.githubusercontent.com/9594042/196446691-29cbee22-b763-46dc-9efa-b0cec43dba59.png)

**Comment by lmmentel** [comment]
Thanks for sharing. The error seems to be coming from the `coverage` github action so you won't see it locally unless you are running the whole CI workflow.

**Comment by miraep8** [comment]
I also noticed this, and anecdotally it seems to only be showing up for Windows 3.7?

**Comment by TonyBagnall** [comment]
not sure if this is related, but running pytest on test_all_estimators locally generates a large number of files called .coverage during the run which persist on my machine. There is also a directory htmlcov. Is it meant to do this? Perhaps this might cause I/O issues ?
![image](https://user-images.githubusercontent.com/9594042/196676469-a4d627a5-b1e2-4e4b-9bc4-8e149a78f7e6.png)

**Comment by TonyBagnall** [comment]
and further to this, I am writing a small test and when I run pytest I get all this, and it creates this htmlcov files locally 
![image](https://user-images.githubusercontent.com/9594042/196746694-e5adcfae-e81a-457b-af20-910f6c5c2adf.png)
