### ISSUE TITLE
[BUG] `FourierFeatures` with `pd.DatetimeIndex`

### ISSUE THREAD

**Issue by eenticott-shell** [sktime/sktime#3605]
**Describe the bug**
When using data with a `pd.DatetimeIndex` in the `FourierFeatures` transformer, it gets converted into nanoseconds. This means you have to specify all of your sp in terms of nanoseconds which is not clear.

**To Reproduce**

```python
from sktime.datasets import load_airline
from sktime.transformations.series.fourier import FourierFeatures
from sktime.utils.plotting import plot_series

df = load_airline()
df.index = df.index.to_timestamp(freq="M")
from sktime.transformations.series.fourier import FourierFeatures
F_transform = FourierFeatures(sp_list = [12], fourier_terms_list=[2]) # should be yearly
sp1 = F_transform.fit_transform(df)

# Convert seasonality to nanoseconds to get correct result
F_transform = FourierFeatures(sp_list = [12*30*24*3600000000000], fourier_terms_list=[2])
sp2 = F_transform.fit_transform(df)

plot_series(sp1["sin_12_1"], sp2["sin_31104000000000000_1"])
```

**Expected behavior**
Would expect it to work from the frequency of the index in the `DatetimeIndex` case. 

**Additional context**
Have added functionality for the expected behaviour in #3606.

**Comment by ltsaprounis** [comment]
Thanks for spotting this @eenticott-shell. 
This is indeed an annoying bug!

On a side note @fkiraly, isn't the "enforce_index_type" tag, supposed to **enforce the index** type?
Cause it looks like although in the tags we have  `"enforce_index_type": [pd.PeriodIndex]` an evil `pd.Datatime` index manages to wiggle its way into `_fit` and `_predict` 😮. 

FYI - @topher-lo and @danbartl for our discussion on enforcing index types earlier.

**Comment by fkiraly** [comment]
@ltsaprounis, the `enforce_index_type` is coming from ancient code that was refactored into the tag system to have 1:1 logic parity.

It does not coerce (which it probably should, fro ma design perspective) but instead acts as a "pass list" is supposed to raise an error for index types not on the pass list - at least this is my understanding and what the contract description in the extension template says.

If it lets other things pass (that are not subtypes), the actual logic does not agree with the contract, and it would be a bug.

**Comment by fkiraly** [comment]
> This means you have to specify all of your sp in terms of nanoseconds which is not clear.

All is quantum physics

**Comment by ltsaprounis** [comment]
OK - we have ourselves a bug then!
