### ISSUE TITLE
[BUG] Missing `get_test_params()` class method for DL estimators 

### ISSUE THREAD

**Issue by achieveordie** [sktime/sktime#3633]
**Describe the bug**

The default values of DL estimators are chosen as per the recommendation by the author of that estimator. This often results in classifiers/regressors that are big, making it more difficult to test its interface / binding contract in `sktime`. To reduce the testing time, a class method `get_test_param()` is to be used which contains 'smaller' values that will be fed to the constructor for testing purposes.

Take a look at TapNet's [classifier](https://github.com/sktime/sktime/blob/main/sktime/classification/deep_learning/tapnet.py#L235) and [regressor](https://github.com/sktime/sktime/blob/main/sktime/regression/deep_learning/tapnet.py#L216) for how this can be done.

**To Reproduce**

The errors due to the lack of this method are sporadic in nature but have been caught in various runners like #3525, and #3562, where one of the estimators cause the workers to crash. See #3620 for discussion.

**Additional context**

- Apart from decreasing the testing time by decreasing the model size, one also needs to take care of the fact there is significant code coverage from the choices of parameters.
- At least two sets of params should be provided for this. Kindly check the link provided for tapnet for clarity.

**Comment by fkiraly** [comment]
Thanks!

would it be worthwhile to add the two recommendations (low test tim, two param set) to the extension templates?

**Comment by achieveordie** [comment]
> would it be worthwhile to add the two recommendations (low test tim, two param set) to the extension templates?

That'd be great, I don't see an extension template for regression though. I'll quickly add this information to the classification's extension template.

**Comment by fkiraly** [comment]
> That'd be great, I don't see an extension template for regression though.

Oh, that's right! I've opened an issue here so we don't forget.
https://github.com/sktime/sktime/issues/3638
