### ISSUE TITLE
[BUG] HTTP error in Clearsky test

### ISSUE THREAD

**Issue by MatthewMiddlehurst** [sktime/sktime#3663]
The `test_clearsky_trafo_vals` test in PR #3636 is failing due to a HTTP Error. The PR just changes TSFresh, so it seems unrelated.

![image](https://user-images.githubusercontent.com/25731235/198579377-6ebba372-0dd7-47d9-9543-f9c70f25f1fa.png)

https://github.com/sktime/sktime/actions/runs/3344117231/jobs/5538243324

**Comment by MatthewMiddlehurst** [comment]
This is likely due to the `load_solar` An option to load local data has been added to the load function in #3652 and the test in the original post uses it.

Other uses of `load_solar` such as `test_load_solar` may still have this issue, however.

**Comment by ltsaprounis** [comment]
Got it in the CI for #3462 as well.
[FAILED sktime/transformations/series/tests/test_clear_sky.py::test_clearsky_trafo_vals - urllib.error.HTTPError: HTTP Error 503: SERVICE UNAVAILABLE](https://github.com/sktime/sktime/actions/runs/3344084474/jobs/5538139324#step:7:1689)

**Comment by MatthewMiddlehurst** [comment]
https://github.com/sktime/sktime/actions/runs/3437607638/jobs/5733800691
```
FAILED sktime/datasets/tests/test_data_io.py::test_load_solar[True] - urllib.error.URLError: <urlopen error [WinError 10061] No connection could be made because the target machine actively refused it>
FAILED sktime/datasets/tests/test_data_io.py::test_load_solar[False] - urllib.error.URLError: <urlopen error [WinError 10061] No connection could be made because the target machine actively refused it>
```
