### ISSUE TITLE
[BUG] `statsmodels` interfaces break for `X` containing more indices than forecasting horizon

### ISSUE THREAD

**Issue by fkiraly** [sktime/sktime#3670]
Same as #3657, but for `SARIMAX` and `statsmodels` adapter when `X` is present.

Also see #3667 and #3668.

The obvious fix, in https://github.com/sktime/sktime/pull/3669, seems to fail on python 3.10, and not on 3.9 or lower.

**Comment by GianlucaGuarroSonos** [comment]
I am using python version 3.8.13 and run into this issue (for both statsmodel and pmdarima)

**Comment by fkiraly** [comment]
Any good guesses why #3669 fails on 3.10 but not on 3.9 or lower?

**Comment by fkiraly** [comment]
I think this is now fixed by #3972.
