### ISSUE TITLE
[BUG] Rocket test sporadic CI failure due to strict equality requirement in test

### ISSUE THREAD

**Issue by ltsaprounis** [sktime/sktime#3694]
**Describe the bug**
A an unrelated to the PR unit test failed in #3606.
The test is `test_rocket_on_gunpoint` which is not related to the PR in anyway. 
here are the CI logs: 
[FAILED sktime/transformations/panel/rocket/tests/test_Rocket.py::test_rocket_on_gunpoint - assert 0.9933333333333333 == 1.0](https://github.com/sktime/sktime/actions/runs/3379230667/jobs/5610684533#step:7:814)

Looks like this would be avoided if we replace `==` with `np.isclose` with an appropriate level of tolerance e.g. 0.01 if that's applicable. Otherwise we can control the random seed in the test.

**Comment by MatthewMiddlehurst** [comment]
I think it would be better to set the `random_state` of the transformer. It's all that's really needed as you say.
