### ISSUE TITLE
[DOC] `pd.DataFrame` output schema of `evaluate` needs to be documented properly in docstring

### ISSUE THREAD

**Issue by fkiraly** [sktime/sktime#3698]
The docstring of `evaluate` in the `forecasting.model_evaluation` module only tells the user that the return is `pd.DataFrame` without further description of the schema.

Best way to glean the schema is to run the example; alternatively, the schema is tested by calls to `_check_evaluate_output` in the tests.

**Comment by topher-lo** [comment]
@fkiraly done in #3709
