### ISSUE TITLE
[MNT] PyPi publish action for 0.14 failed

### ISSUE THREAD

**Issue by jorenham** [sktime/sktime#3715]
Summary by @fkiraly:
The attempted 0.14.0 release has failed at pypi upload of successfully built wheels.

Help on diagnosing and solving this is appreciated.

Original post:
---
Just to let you know: 0.14 has not been published on PyPI yet:

https://github.com/sktime/sktime/actions/runs/3402037795

**Comment by fkiraly** [comment]
You are right 😱 

The error happens right after it attempts to upload to `pypi`, this is it:

```
 ERROR    HTTPError: 400 Bad Request from https://upload.pypi.org/legacy/        
         '=?utf-8?b?RnJhbnogS2lyw6FseSA8...YWxsIDxhamJAdWVhLmFjLnVrPg==?=' is an
         invalid value for Author-email. Error: Use a valid email address See   
         https://packaging.python.org/specifications/core-metadata for more     
         information.   
```

**Comment by fkiraly** [comment]
any ideas what this is, @jorenham? Haven't seen it before, and Professor Google doesn't seem to help...

**Comment by jorenham** [comment]
@fkiraly I'm guessing something with the email address in the `setup.py` or `pyproject.toml`,  but I can't seem to find anything at first glance

**Comment by jorenham** [comment]
@fkiraly It might be easiest to merge the `author` and `author_email` in the `pyproject.toml` and `setup.py`, formatted like a `RFC-822 From: header`, as specified in: https://packaging.python.org/en/latest/specifications/core-metadata/#author-email

**Comment by fkiraly** [comment]
let's keep this open until we are sure it works...

**Comment by fkiraly** [comment]
> @fkiraly I'm guessing something with the email address in the setup.py or pyproject.toml, but I can't seem to find anything at first glance

I had the same guess, though I did sth slightly different. If that does not work, I will try your suggestion next, @jorenham.

Other guess: `sktime` still seems to run on the pypi account on one of the founders, @mloning, who isn't very active anymore.
Could it be that he forgot about this and changed his password, so it no longer agrees with the secret?

Although the wouldn't fit the message which spews something about UTF8.

**Comment by fkiraly** [comment]
my attempt at fix: https://github.com/sktime/sktime/pull/3718

**Comment by fkiraly** [comment]
actually, @jorenham, if you have 10min, it would be appreciated if you could make a draft PR that implements your suggested change? I don't know what exactly I would change.

I was on the page you linked just 10min ago, and it isn't 100% clear to me how to change it and where.

**Comment by fkiraly** [comment]
Other question: what explains that it was fine for 0.13.4 but isn't fine now?

**Comment by jorenham** [comment]
@fkiraly In the meantime python 3.11 was released, so perhaps they also changed the strictness of the packaging metadata?

**Comment by jorenham** [comment]
@fkiraly your build succeeded and 0.14 has been published on pypi now. So I suppose this issue is now resolved, although I'm not sure why this did the trick 🤷🏻

**Comment by fkiraly** [comment]
>@fkiraly In the meantime python 3.11 was released, so perhaps they also changed the strictness of the packaging metadata?

Sounds vaguely plausible.

>@fkiraly your build succeeded and 0.14 has been published on pypi now. So I suppose this issue is now resolved, although I'm not sure why this did the trick 🤷🏻

This is my general experience with `pyproject.toml`.
If it stops working, fiddle around with the lines that seem related until it works again.
Better than `setup.py` though...
