### ISSUE TITLE
[DOC] Add hall-of-fame widget to README

### ISSUE THREAD

**Issue by GuzalBulatova** [sktime/sktime#3716]
#### Describe the issue linked to the documentation

We'd like to celebrate our contributors and make the most active / recent ones more visible. After discussion in https://github.com/sktime/community-org/issues/36 , community decided to go with this option for improvement in README.

#### Suggest a potential alternative/fix

Add https://github.com/sourcerer-io/hall-of-fame widget to sktime/README.md

**Comment by GigaMoksh** [comment]
Hello, I'd like to solve this issue.

**Comment by GigaMoksh** [comment]
https://github.com/sourcerer-io/sourcerer-app/issues/632 see this. I think sourcerer isn't available now.

**Comment by GuzalBulatova** [comment]
Hi @GigaMoksh , I see, I thought that this widget didn't require sourcerer, but apparently it does. Thanks for looking into this. Do you maybe have alternative in mind?

**Comment by GigaMoksh** [comment]
I couldn't find anything, but I'll be happy to solve the issue if someone can find any alternatives.

**Comment by KaustubhUp025** [comment]
Hello, I will try to solve this issue

**Comment by fkiraly** [comment]
nice, that would be great!

Btw, I just checked the sourcerer tool, but it seems it is no longer widely used? For instance, the three repositories, linked as example, seem to have removed it again.

That is not a good sign.

However, two of the three examples have a nice contributor portrait list in their README, e.g., dvc (which is a popular data versioning tool).
How about we try to see whether we can implement that? https://github.com/iterative/dvc
