### ISSUE TITLE
[DOC] fix Slack greetbot message - correct channel ref, fix broken CoC link

### ISSUE THREAD

**Issue by fkiraly** [sktime/sktime#3734]
The Greetbot message on slack has two mistakes:

* it directs new contributors to `#general` for introductions (announcements only) and not to `#contributors` (contributor Q and intro)
* the code of conduct link in the message still points to the old CoC location

I have tried to access the greetbot config, but I do not see where to set the greeting message. I suppose I do not have app manager rights?

**Comment by miraep8** [comment]
I think I may have found a way to do it in the "workflow builder"

Trying out this message when anyone joins the # general channel:

<img width="407" alt="image" src="https://user-images.githubusercontent.com/10511777/200850686-d8f221d4-9de5-42f4-b5c0-88afab466197.png">

Can edit it as needed

**Comment by miraep8** [comment]
My labmate was kind enough to try joining, looks like it has replaced the previous welcome message: 
<img width="718" alt="Screen Shot 2022-11-09 at 9 08 35 AM" src="https://user-images.githubusercontent.com/10511777/200852088-8a9d3912-379e-41e3-963f-739b85e4fbe8.png">

**Comment by miraep8** [comment]
I will probably change it so it says welcome to sktime not welcome to # general.

**Comment by fkiraly** [comment]
I think it would be nice to keep the link to the CoC as well

**Comment by miraep8** [comment]
Sure, added a link to the [Code of Conduct page](https://www.sktime.org/en/latest/get_involved/code_of_conduct.html) on the website. 

![image](https://user-images.githubusercontent.com/10511777/200978480-29ba33b3-9269-41d2-8968-e9eecef535b5.png)

By the way - I believe anyone else should be able to access this too by going to the sktime dropdown -> Tools -> Workflow Builder. Just in case anyone else wants to play around with it.  I would also be happy to make more changes.

**Comment by fkiraly** [comment]
ooohhhhh - I've never been there! I tried via the app manager.

**Comment by fkiraly** [comment]
My original issue is resolved, thanks @miraep8!

This does not prevent us from making further changes, of course.
