### ISSUE TITLE
[BUG] Unable to transform dataset using MiniRocket when parallelized via `ray`

### ISSUE THREAD

**Issue by bdewilde** [sktime/sktime#3757]
**Describe the bug**

I am trying to fit+transform data using an `sklearn` pipeline, with `sktime`'s MiniRocket transformer as a component, using `ray` to parallelize the transform step. Fitting (which is not performed in parallel) works as expected; transforming raises an unexpected error about the dataset's type/shape: `TypeError: No matching definition for argument type(s) array(float32, 2d, C), Tuple(readonly array(int32, 1d, C), readonly array(int32, 1d, C), readonly array(float32, 1d, C))` . I've seen issues related to this error before, just none in this context.

I've manually confirmed that the data passed into the minirocket transformer looks structurally identical at both `.fit()` and `.transform()` calls, and wasn't able to identify any ways that `ray` was modifying the data under the hood when it called transform in parallel. I've already filed an issue there — https://github.com/ray-project/ray/issues/30178 — but am cross-posting here, because I'm unsure about which side of the fence the actual error is arising.

**To Reproduce**

```python
import random

import pandas as pd
import ray.data
import sklearn.base
from sktime.datatypes._panel._convert import from_2d_array_to_nested
from sktime.transformations.panel import rocket


class MyPreprocessor(ray.data.Preprocessor):

    @property
    def estimator(self) -> sklearn.base.BaseEstimator:
        return rocket.MiniRocket()

    def _fit(self, dataset: ray.data.Dataset) -> ray.data.Preprocessor:
        X = dataset.to_pandas()
        self.estimator_ = self.estimator.fit(X, None)
        return self

    def _transform_pandas(self, df: pd.DataFrame) -> pd.DataFrame:
        return self.estimator_.transform(df)


df = (
    pd.DataFrame(
        columns=[str(i) for i in range(10)],
        data=[[random.randint(0, 10) for _ in range(10)] for _ in range(100)],
    )
    .pipe(from_2d_array_to_nested)
    .rename(columns={0: "ts"})
)
dataset = ray.data.from_pandas(df)
preprocessor = MyPreprocessor().fit(dataset)

_ = preprocessor._transform_pandas(dataset.to_pandas())  # OK
_ = [preprocessor._transform_pandas(batch) for batch in dataset.iter_batches()]  # OK
_ = dataset.map_batches(preprocessor._transform_pandas)  # FAILS!
_ = preprocessor.transform(dataset)  # FAILS!
```

**Expected behavior**
I should be able to transform the data using minirocket when it's split up into "batches" and executed in parallel.

**Additional context**

**Versions**
<details>

System:
    python: 3.9.13 (main, Jul  7 2022, 11:59:57)  [Clang 13.1.6 (clang-1316.0.21.2.5)]
executable: /Users/burtondewilde/.pyenv/versions/3.9.13/envs/foo/bin/python3.9
   machine: macOS-12.4-x86_64-i386-64bit

Python dependencies:
          pip: 22.3
   setuptools: 58.1.0
      sklearn: 1.1.3
       sktime: 0.13.4
  statsmodels: 0.13.2
        numpy: 1.21.6
        scipy: 1.8.1
       pandas: 1.4.4
   matplotlib: 3.5.2
       joblib: 1.1.0
        numba: 0.56.3
     pmdarima: None
      tsfresh: None

</details>

**Comment by patrickzib** [comment]
@TonyBagnall @MatthewMiddlehurst I think, we had a similar issue before and suspect it is the readonly array as in joblib parallelization. I do not know any specifics about ray, though

> (_map_block_nosplit pid=77950) TypeError: No matching definition for argument type(s) array(float32, 2d, C), Tuple(**readonly** array(int32, 1d, C), **readonly** array(int32, 1d, C), **readonly** array(float32, 1d, C))

**Comment by patrickzib** [comment]
Digging deeper, there is some documentation regarding read-only and ray:

> Because Ray puts numpy arrays in the object store, when deserialized as arguments in remote functions they will become read-only. For example, the following code snippet will crash:

https://docs.ray.io/en/latest/ray-core/objects/serialization.html?highlight=read%20only#numpy-arrays

By changing transform() of minirocket form

```python
X_ = _transform(X, self.parameters)
```

to 

```python
X_ = _transform(X,
                        (self.parameters[0].copy(),
                         self.parameters[1].copy(),
                         self.parameters[2].copy()
                        ))
```

The above error vanishes and a non-mini-rocket related error pops up:

> ValueError: A Pandas DataFrame with column names of non-str types is not supported by Ray Dataset. Column names of this DataFrame:

**Comment by bdewilde** [comment]
Thanks for digging, @patrickzib ! I'd homed in on the read-only issue, but hadn't identified the specific cause or a decent workaround. Much appreciated. 🙇‍♂️

That next error you hit is familiar: minirocket's transform returns a dataframe with integer column names (one for each feature), assigned automatically based on the underlying numpy array ([here](https://github.com/sktime/sktime/blob/main/sktime/transformations/panel/rocket/_minirocket.py#L125)), but that functionality isn't supported by ray datasets. In fact, there's already a ticket: https://github.com/ray-project/ray/issues/29288

**Comment by patrickzib** [comment]
@bdewilde 

I did some more investigation, and the test finally succeeds using the following code:

 ```python
   class MyPreprocessor(ray.data.Preprocessor):
        @property
        def estimator(self) -> sklearn.base.BaseEstimator:
            return rocket.MiniRocket()

        def _fit(self, dataset: ray.data.Dataset) -> ray.data.Preprocessor:
            X = dataset.to_pandas()
            self.estimator_ = self.estimator.fit(X, None)
            return self

        def _transform_pandas(self, df: pd.DataFrame) -> pd.DataFrame:
            self.estimator_.parameters = \
                        (self.estimator_.parameters[0].copy(),
                         self.estimator_.parameters[1].copy(),
                         self.estimator_.parameters[2].copy())

            return self.estimator_.transform(df).rename(columns=str)

```

I am not sure, if it makes sense to modify MiniRocket. The problems seem to be - to a large extend - related to RAY.

**Comment by patrickzib** [comment]
I am closing the bug for now. Feel free to comment, if any issues remain.
