### ISSUE TITLE
[BUG] Unrelated tests failing for no reason [test_load_solar]

### ISSUE THREAD

**Issue by lmmentel** [sktime/sktime#3758]
**Describe the bug**

In #3375 I noticed tests are failing unrelated to any code changes I made. Obviously this is a bad idea to test code that relies on external services being up and running. This has little to do with sktime and should probably be removed. 

```
FAILED sktime/datasets/tests/test_data_io.py::test_load_solar[False] - urllib.error.HTTPError: HTTP Error 504: Gateway Time-out
FAILED sktime/datasets/tests/test_data_io.py::test_load_solar[True] - urllib.error.HTTPError: HTTP Error 504: Gateway Time-out
```

see https://github.com/sktime/sktime/actions/runs/3437085117/jobs/5733604844 for more details

**To Reproduce**

```python
<Paste your code here>
```

**Expected behavior**

**Additional context**

**Versions**
<details>

</details>

**Comment by lmmentel** [comment]
@ciaran-g :point_up: it seems that you've added the offending test. Any change you could refactor to not fetch from an external service and maybe use locally available data? Otherwise I would recommend removing the test entirely.

**Comment by MatthewMiddlehurst** [comment]
Related #3663

**Comment by MatthewMiddlehurst** [comment]
An option to load a local version was added in #3652, this test should probably be removed however as its only functionality is to test the external loading I think.

**Comment by fkiraly** [comment]
yes, I think we should not include this in the regular test suite, this can lead to request bombing through anyone who on a fork runs the test suite.

We could move it into a "once in a while" test or a permanent diagnostic?

**Comment by ciaran-g** [comment]
I will have a look to change it today, just wondering how you would change it to a once in a while test? Are there any examples in the package already?

**Comment by TonyBagnall** [comment]
we removed tests based on external websites, specifically tests of load_from_ucr_tsv_to_dataframe for this very reason. I am in favour of just removing these tests.
