### ISSUE TITLE
[ENH] Extend minirocket_multivariate to unequal / variable length time series

### ISSUE THREAD

**Issue by michaelfeil** [sktime/sktime#3769]
**Is your feature request related to a problem? Please describe.**

Currently, just a few unequal length multivariate models exist. From the minirocket_multivariate the authors implemented a option for variable length time series data. (https://github.com/angus924/minirocket/blob/main/code/minirocket_multivariate_variable.py)

**Describe the solution you'd like**
Implement a MiniRocketMultivariate under as `sktime.transformations.panel.rocket` . While the original author's code is already used in the other rocket implementations.
From sktime only a small interface is needed to convert the X (sktime-compatible Panel data format)
into n 1-D series with a additional vector on length information.
```
def fit(X, y=None):
     """
     X : sktime-compatible Panel data format, with n_samples series
```
Variable-Length Input (Experimental)

**Describe alternatives you've considered**
Using the minirocket_multivariate using trunancation or padding transformers. 

**Additional context**

**Comment by michaelfeil** [comment]
I would like to submit a PR on this.

I would include the following:
- interface to https://github.com/angus924/minirocket/blob/main/code/minirocket_multivariate_variable.py as `MiniRocketMultivariateVariable`, essentially converting a `"X_inner_mtype": "df-list"` to a 

 ```
 X : df-list (list of dataframes, with multivariate ts
 
 Returns
        np.array: 2D array of shape = [n_dimensions, sum(length_series(i) for i in n_instances)], np.float32
        np.array: 1D array of shape = [n_instances] with length of each series, np.int32
```
- test on JapaneseVowels (multivariate and unequal length time-series)
- the authors code, as in https://github.com/sktime/sktime/blob/main/sktime/transformations/panel/rocket/_multirocket_multivariate.py, with no modifications except for seeding.

```
accs = []
    for i in range(100):
        classifier = make_pipeline(
            MiniRocketMultivariateVariable(random_state=i),
            StandardScaler(with_mean=False),
            RidgeClassifierCV(alphas=np.logspace(-3, 3, 10)),
        )
        classifier.fit(X_training, Y_training)
        accs.append(
            classifier.score(X_test, Y_test)
        )
```
`[0.9891, 0.9864, 0.9837, 0.9945, 0.9891]`
I get a mean acc of ca. `0.987` and variance of `8.77e-06`.

JapaneseVowels reported results https://arxiv.org/pdf/1711.11343.pdf
SMTS LPS mvARF DTWi ARKernel gRSF MLSTMFCN MUSE
96.9% 95.1% 95.9% 96.2% 98.4% 80% 100% 97.6%

That is pretty State-of-the-Art, consider also the training time ~5 seconds including the RidgeClassifierCV.

Open questions are:
- how to submit a PR?
- @angus924 can we add the code from https://github.com/angus924/minirocket/blob/main/code/minirocket_multivariate_variable.py here?

**Comment by michaelfeil** [comment]
This would be the modified code so far, please leave some initial feedback!

https://github.com/michaelfeil/sktime/commit/c31c0c6ef0fd2b9048fbe2b4fb9f37785cc9c4b9

**Comment by fkiraly** [comment]
Thanks, general idea makes sense, looks great!

could you kindly open a PR to sktime to review?
