### ISSUE TITLE
[BUG] Lag transformer returns a dataframe with more rows than the input dataframe

### ISSUE THREAD

**Issue by KishManani** [sktime/sktime#3779]
**Describe the bug**
 I noticed that if you have a dataframe with a non uniform time stamp that the Lag transformer will resample the dataframe and return more rows than the original dataframe. 

**To Reproduce**

```python
import numpy as np
import pandas as pd

from sktime.transformations.series.lag import Lag
from sktime.transformations.series.fourier import FourierFeatures

# Create dataframe with non-uniform integer index
data = {'ix': [1,2,3,4,5,9,10], 'y': [1,4,5,5,21,1,1]}
df_int_idx = pd.DataFrame(data=data["y"], index=data["ix"], columns=["y"])

# Apply transformers
print(Lag(lags=[1,2,3]).fit_transform(df_int_idx))
```

Output:

```python
    lag_1__y  lag_2__y  lag_3__y
1        NaN       NaN       NaN
2        1.0       NaN       NaN
3        4.0       1.0       NaN
4        5.0       4.0       1.0
5        5.0       5.0       4.0
6       21.0       5.0       5.0
7        NaN      21.0       5.0
8        NaN       NaN      21.0
9        NaN       NaN       NaN
10       1.0       NaN       NaN
11       1.0       1.0       NaN
12       NaN       1.0       1.0
13       NaN       NaN       1.0 
```

**Expected behavior**
A dataframe which has the same index as the original dataframe with the lag features.

**Versions**

System:
python: 3.8.7 (default, May  6 2021, 21:53:45)  [Clang 12.0.0 (clang-1200.0.32.29)]
executable: /Users/kishan_manani/.pyenv/versions/3.8.7/envs/sktime-dev/bin/python
machine: macOS-11.6.6-x86_64-i386-64bit

Python dependencies:
pip: 22.1.2
setuptools: 49.2.1
sklearn: 1.1.1
sktime: 0.14.0
statsmodels: 0.13.2
numpy: 1.21.6
scipy: 1.8.1
pandas: 1.4.2
matplotlib: 3.5.2
joblib: 1.1.0
numba: 0.55.2
pmdarima: 1.8.5
tsfresh: 0.19.0

**Comment by fkiraly** [comment]
This is very odd. I can confirm this on current main, python 3.8, windows.

What works as expected if you set the parameter `index_out="original"` in `Lag`.

Why it creates those extra rows is unclear to me, I suspect it is some `pandas` secret magic around `freq`?

**Comment by fkiraly** [comment]
actually, I think it's not a bug at all - it is *expected behaviour*.

Why: the default setting for `index_out` is `"extend"`, which gives you the union of the indices in the input, and any shifted indices with values. In your case, it happens to be all the integers from 1 to 13.

The behaviour you expect is probably `"original"` or `"shifted"`, e.g.,

```python
import numpy as np
import pandas as pd

from sktime.transformations.series.lag import Lag
from sktime.transformations.series.fourier import FourierFeatures

# Create dataframe with non-uniform integer index
data = {'ix': [1,2,3,4,5,9,10], 'y': [1,4,5,5,21,1,1]}
df_int_idx = pd.DataFrame(data=data["y"], index=data["ix"], columns=["y"])

# Apply transformers
print(Lag(lags=[1,2,3], index_out="original").fit_transform(df_int_idx))
```

**Comment by fkiraly** [comment]
I think it's not a bug - please reopen if you think it's otherwise (or, counterintuitive).
