### ISSUE TITLE
[BUG] FeatureUnion.get_params() causes infinite loop

### ISSUE THREAD

**Issue by hoesler** [sktime/sktime#3789]
**Describe the bug**
The `get_params()` method of FeatureUnion causes an infinite loop if created by magic `+` method.

Both the `get_params()` and `set_params()` methods should access the tuples in `_transformer_list` instead of the list of transformers in `transformer_list`.

**To Reproduce**
```python
from sktime.transformations.compose import Id
(Id() + Id()).get_params()
```

**Expected behavior**
The method call should return the dict of params.

**Additional context**

**Versions**
<details>

System:
    python: 3.10.8 (main, Oct 13 2022, 09:48:40) [Clang 14.0.0 (clang-1400.0.29.102)]
executable: .venv/bin/python3
   machine: macOS-12.6.1-arm64-arm-64bit

Python dependencies:
          pip: 22.0.4
   setuptools: 65.5.0
      sklearn: 1.1.2
       sktime: 0.13.4
  statsmodels: 0.13.2
        numpy: 1.22.4
        scipy: 1.8.1
       pandas: 1.5.1
   matplotlib: None
       joblib: 1.2.0
        numba: 0.56.3
     pmdarima: None
      tsfresh: None
>>>

</details>

**Comment by fkiraly** [comment]
yes, that's correct, thanks!!

Do you have an explanation why this was not caught by the current tests? We do `test_get_params`, naively I would think it should fix this?

I incorporated the fix in this refactor here:
https://github.com/sktime/sktime/pull/3708

**Comment by hoesler** [comment]
Thanks for the fast response. I think you're right, that the non-tuple args are causing this.

But the root cause might be something different:

The execution got stuck [here](https://github.com/sktime/sktime/blob/0ce1b838bd9837b7f80f8e6ddce2fa912059b881/sktime/base/_meta.py#L46).

PyCharm doc on the dict.update method says (can't find it in the official docs):
> D.update([E, ]**F) -> None. Update D from dict/iterable E and F. If E is present and has a .keys() method, then does: for k in E: D[k] = E[k] If E is present and lacks a .keys() method, then does: for k, v in E: D[k] = v In either case, this is followed by: for k in F: D[k] = F[k]

So my guess is, that it is calling the `__getitem__` method of the transformer (because D[k] = E[k]) and this creates a new new pipeline with `return ColumnSelect(key) * self` and `__mul__` calls itself infinitly with `self_as_pipeline * other`.

**Comment by fkiraly** [comment]
ahhhhh, makes sense. Thanks, this explains it!

**Comment by fkiraly** [comment]
> So, I guess the lesson here is, be careful by implementing the __getitem__ method, isn't it? Because all of a sudden, you support iteration by the sequence protocol.

Hm - how do we avoid this? Is there a smart way to throw an exception?

**Comment by hoesler** [comment]
I guess, the best would be to exclude int as key type of `__getitem__(self, key)`, if we misuse that method for something different from getting elements of a sequence. If that is not possible, I don't see anything we can do to avoid unexpected iteration, as with the `dict.update` methods. So, the best we can do is testing.

**Comment by fkiraly** [comment]
I think `int` needs to be possible, since `int` can be a column index type in subsetting...

> So, the best we can do is testing.

Yes, the new test case catches the error. I'd say coverage was just too low in this case.
