### ISSUE TITLE
[BUG] 'evaluate' method cannot handle TransformedTargetForecaster where the time series data is transformed into several features

### ISSUE THREAD

**Issue by GianlucaGuarroSonos** [sktime/sktime#3795]
**Describe the bug**
'evaluate' method expects a univariate pd.DataFrame with one column. However the point of featurizers like `FourierFeatures` is to transform the univariate time series into a set of features and feed that into the model. Thus the 'evaluate' method is not generalized to these use cases.

**To Reproduce**

```
from sktime.forecasting.model_selection import ExpandingWindowSplitter
from sktime.forecasting.arima import ARIMA
from sktime.forecasting.compose import TransformedTargetForecaster
from sktime.transformations.series.fourier import FourierFeatures
from sktime.datasets import load_airline
from sktime.forecasting.base import ForecastingHorizon

y_airline = load_airline()
sp = 4
cv = ExpandingWindowSplitter(step_length=1, fh=list(range(1,15)), initial_window=30)
forecaster = TransformedTargetForecaster(
    [
        ("fourier", FourierFeatures(sp_list=[sp], fourier_terms_list=[int(sp//2)])),
        ("forecaster", ARIMA(order=(1, 1, 1), suppress_warnings=True)),
    ]
)
res = evaluate(forecaster, cv, y=y_airline, strategy='update', scoring=mse, error_score='raise')  
```

**Expected behavior**

For the evaluate method to run without issue.

**Additional context**

This is the call stack trace

> ---------------------------------------------------------------------------
> ValueError                                Traceback (most recent call last)
> /Users/gguarro/Documents/Team Repos/Strategic-Finance-Forecasts/code/notebooks/longterm_forecasts.ipynb Cell 136' in <cell line: 10>()
>       [3](vscode-notebook-cell:/Users/gguarro/Documents/Team%20Repos/Strategic-Finance-Forecasts/code/notebooks/longterm_forecasts.ipynb#ch0000151?line=2) v = yesfourier_results_dict[()]
>       [4](vscode-notebook-cell:/Users/gguarro/Documents/Team%20Repos/Strategic-Finance-Forecasts/code/notebooks/longterm_forecasts.ipynb#ch0000151?line=3) forecaster = TransformedTargetForecaster(
>       [5](vscode-notebook-cell:/Users/gguarro/Documents/Team%20Repos/Strategic-Finance-Forecasts/code/notebooks/longterm_forecasts.ipynb#ch0000151?line=4)     [
>       [6](vscode-notebook-cell:/Users/gguarro/Documents/Team%20Repos/Strategic-Finance-Forecasts/code/notebooks/longterm_forecasts.ipynb#ch0000151?line=5)         ("fourier", FourierFeatures(sp_list=[sp], fourier_terms_list=[int(sp//2)])),
>       [7](vscode-notebook-cell:/Users/gguarro/Documents/Team%20Repos/Strategic-Finance-Forecasts/code/notebooks/longterm_forecasts.ipynb#ch0000151?line=6)         ("forecaster", ARIMA(order=v['order'], suppress_warnings=True)),
>       [8](vscode-notebook-cell:/Users/gguarro/Documents/Team%20Repos/Strategic-Finance-Forecasts/code/notebooks/longterm_forecasts.ipynb#ch0000151?line=7)     ]
>       [9](vscode-notebook-cell:/Users/gguarro/Documents/Team%20Repos/Strategic-Finance-Forecasts/code/notebooks/longterm_forecasts.ipynb#ch0000151?line=8) )
> ---> [10](vscode-notebook-cell:/Users/gguarro/Documents/Team%20Repos/Strategic-Finance-Forecasts/code/notebooks/longterm_forecasts.ipynb#ch0000151?line=9) res = evaluate(forecaster, cv, y=y_week_train['NUM_NEW_USERS'], strategy='update', scoring=mse, error_score='raise')
> 
> File ~/miniconda3/envs/strategic-finance-forecasts/lib/python3.8/site-packages/sktime/forecasting/model_evaluation/_functions.py:180, in evaluate(forecaster, cv, y, X, strategy, scoring, return_data, error_score)
>     [178](file:///Users/gguarro/miniconda3/envs/strategic-finance-forecasts/lib/python3.8/site-packages/sktime/forecasting/model_evaluation/_functions.py?line=177) except Exception as e:
>     [179](file:///Users/gguarro/miniconda3/envs/strategic-finance-forecasts/lib/python3.8/site-packages/sktime/forecasting/model_evaluation/_functions.py?line=178)     if error_score == "raise":
> --> [180](file:///Users/gguarro/miniconda3/envs/strategic-finance-forecasts/lib/python3.8/site-packages/sktime/forecasting/model_evaluation/_functions.py?line=179)         raise e
>     [181](file:///Users/gguarro/miniconda3/envs/strategic-finance-forecasts/lib/python3.8/site-packages/sktime/forecasting/model_evaluation/_functions.py?line=180)     else:
>     [182](file:///Users/gguarro/miniconda3/envs/strategic-finance-forecasts/lib/python3.8/site-packages/sktime/forecasting/model_evaluation/_functions.py?line=181)         warnings.warn(
>     [183](file:///Users/gguarro/miniconda3/envs/strategic-finance-forecasts/lib/python3.8/site-packages/sktime/forecasting/model_evaluation/_functions.py?line=182)             f"""
>     [184](file:///Users/gguarro/miniconda3/envs/strategic-finance-forecasts/lib/python3.8/site-packages/sktime/forecasting/model_evaluation/_functions.py?line=183)         Fitting of forecaster failed, you can set error_score='raise' to see
>    (...)
>     [189](file:///Users/gguarro/miniconda3/envs/strategic-finance-forecasts/lib/python3.8/site-packages/sktime/forecasting/model_evaluation/_functions.py?line=188)             FitFailedWarning,
>     [190](file:///Users/gguarro/miniconda3/envs/strategic-finance-forecasts/lib/python3.8/site-packages/sktime/forecasting/model_evaluation/_functions.py?line=189)         )
> 
> File ~/miniconda3/envs/strategic-finance-forecasts/lib/python3.8/site-packages/sktime/forecasting/model_evaluation/_functions.py:168, in evaluate(forecaster, cv, y, X, strategy, scoring, return_data, error_score)
>     [165](file:///Users/gguarro/miniconda3/envs/strategic-finance-forecasts/lib/python3.8/site-packages/sktime/forecasting/model_evaluation/_functions.py?line=164)     scitype = None
>     [166](file:///Users/gguarro/miniconda3/envs/strategic-finance-forecasts/lib/python3.8/site-packages/sktime/forecasting/model_evaluation/_functions.py?line=165)     metric_args = {}
> --> [168](file:///Users/gguarro/miniconda3/envs/strategic-finance-forecasts/lib/python3.8/site-packages/sktime/forecasting/model_evaluation/_functions.py?line=167) y_pred = eval(pred_type[scitype])(fh, X_test, **metric_args)
>     [170](file:///Users/gguarro/miniconda3/envs/strategic-finance-forecasts/lib/python3.8/site-packages/sktime/forecasting/model_evaluation/_functions.py?line=169) pred_time = time.perf_counter() - start_pred
>     [172](file:///Users/gguarro/miniconda3/envs/strategic-finance-forecasts/lib/python3.8/site-packages/sktime/forecasting/model_evaluation/_functions.py?line=171) # score
> 
> File ~/miniconda3/envs/strategic-finance-forecasts/lib/python3.8/site-packages/sktime/forecasting/base/_base.py:364, in BaseForecaster.predict(self, fh, X)
>     [361](file:///Users/gguarro/miniconda3/envs/strategic-finance-forecasts/lib/python3.8/site-packages/sktime/forecasting/base/_base.py?line=360)     y_pred = self._vectorize("predict", X=X_inner, fh=fh)
>     [363](file:///Users/gguarro/miniconda3/envs/strategic-finance-forecasts/lib/python3.8/site-packages/sktime/forecasting/base/_base.py?line=362) # convert to output mtype, identical with last y mtype seen
> --> [364](file:///Users/gguarro/miniconda3/envs/strategic-finance-forecasts/lib/python3.8/site-packages/sktime/forecasting/base/_base.py?line=363) y_out = convert_to(
>     [365](file:///Users/gguarro/miniconda3/envs/strategic-finance-forecasts/lib/python3.8/site-packages/sktime/forecasting/base/_base.py?line=364)     y_pred,
>     [366](file:///Users/gguarro/miniconda3/envs/strategic-finance-forecasts/lib/python3.8/site-packages/sktime/forecasting/base/_base.py?line=365)     self._y_mtype_last_seen,
>     [367](file:///Users/gguarro/miniconda3/envs/strategic-finance-forecasts/lib/python3.8/site-packages/sktime/forecasting/base/_base.py?line=366)     store=self._converter_store_y,
>     [368](file:///Users/gguarro/miniconda3/envs/strategic-finance-forecasts/lib/python3.8/site-packages/sktime/forecasting/base/_base.py?line=367)     store_behaviour="freeze",
>     [369](file:///Users/gguarro/miniconda3/envs/strategic-finance-forecasts/lib/python3.8/site-packages/sktime/forecasting/base/_base.py?line=368) )
>     [371](file:///Users/gguarro/miniconda3/envs/strategic-finance-forecasts/lib/python3.8/site-packages/sktime/forecasting/base/_base.py?line=370) return y_out
> 
> File ~/miniconda3/envs/strategic-finance-forecasts/lib/python3.8/site-packages/sktime/datatypes/_convert.py:263, in convert_to(obj, to_type, as_scitype, store, store_behaviour)
>     [257](file:///Users/gguarro/miniconda3/envs/strategic-finance-forecasts/lib/python3.8/site-packages/sktime/datatypes/_convert.py?line=256)             raise TypeError(
>     [258](file:///Users/gguarro/miniconda3/envs/strategic-finance-forecasts/lib/python3.8/site-packages/sktime/datatypes/_convert.py?line=257)                 "to_type contains no mtype compatible with the scitype of obj,"
>     [259](file:///Users/gguarro/miniconda3/envs/strategic-finance-forecasts/lib/python3.8/site-packages/sktime/datatypes/_convert.py?line=258)                 f"which is {as_scitype}"
>     [260](file:///Users/gguarro/miniconda3/envs/strategic-finance-forecasts/lib/python3.8/site-packages/sktime/datatypes/_convert.py?line=259)             )
>     [261](file:///Users/gguarro/miniconda3/envs/strategic-finance-forecasts/lib/python3.8/site-packages/sktime/datatypes/_convert.py?line=260)         to_type = same_scitype_mtypes[0]
> --> [263](file:///Users/gguarro/miniconda3/envs/strategic-finance-forecasts/lib/python3.8/site-packages/sktime/datatypes/_convert.py?line=262) converted_obj = convert(
>     [264](file:///Users/gguarro/miniconda3/envs/strategic-finance-forecasts/lib/python3.8/site-packages/sktime/datatypes/_convert.py?line=263)     obj=obj,
>     [265](file:///Users/gguarro/miniconda3/envs/strategic-finance-forecasts/lib/python3.8/site-packages/sktime/datatypes/_convert.py?line=264)     from_type=from_type,
>     [266](file:///Users/gguarro/miniconda3/envs/strategic-finance-forecasts/lib/python3.8/site-packages/sktime/datatypes/_convert.py?line=265)     to_type=to_type,
>     [267](file:///Users/gguarro/miniconda3/envs/strategic-finance-forecasts/lib/python3.8/site-packages/sktime/datatypes/_convert.py?line=266)     as_scitype=as_scitype,
>     [268](file:///Users/gguarro/miniconda3/envs/strategic-finance-forecasts/lib/python3.8/site-packages/sktime/datatypes/_convert.py?line=267)     store=store,
>     [269](file:///Users/gguarro/miniconda3/envs/strategic-finance-forecasts/lib/python3.8/site-packages/sktime/datatypes/_convert.py?line=268)     store_behaviour=store_behaviour,
>     [270](file:///Users/gguarro/miniconda3/envs/strategic-finance-forecasts/lib/python3.8/site-packages/sktime/datatypes/_convert.py?line=269) )
>     [272](file:///Users/gguarro/miniconda3/envs/strategic-finance-forecasts/lib/python3.8/site-packages/sktime/datatypes/_convert.py?line=271) return converted_obj
> 
> File ~/miniconda3/envs/strategic-finance-forecasts/lib/python3.8/site-packages/sktime/datatypes/_convert.py:172, in convert(obj, from_type, to_type, as_scitype, store, store_behaviour)
>     [167](file:///Users/gguarro/miniconda3/envs/strategic-finance-forecasts/lib/python3.8/site-packages/sktime/datatypes/_convert.py?line=166) else:
>     [168](file:///Users/gguarro/miniconda3/envs/strategic-finance-forecasts/lib/python3.8/site-packages/sktime/datatypes/_convert.py?line=167)     raise RuntimeError(
>     [169](file:///Users/gguarro/miniconda3/envs/strategic-finance-forecasts/lib/python3.8/site-packages/sktime/datatypes/_convert.py?line=168)         "bug: unrechable condition error, store_behaviour has unexpected value"
>     [170](file:///Users/gguarro/miniconda3/envs/strategic-finance-forecasts/lib/python3.8/site-packages/sktime/datatypes/_convert.py?line=169)     )
> --> [172](file:///Users/gguarro/miniconda3/envs/strategic-finance-forecasts/lib/python3.8/site-packages/sktime/datatypes/_convert.py?line=171) converted_obj = convert_dict[key](obj, store=store)
>     [174](file:///Users/gguarro/miniconda3/envs/strategic-finance-forecasts/lib/python3.8/site-packages/sktime/datatypes/_convert.py?line=173) return converted_obj
> 
> File ~/miniconda3/envs/strategic-finance-forecasts/lib/python3.8/site-packages/sktime/datatypes/_series/_convert.py:82, in convert_MvS_to_UvS_as_Series(obj, store)
>      [79](file:///Users/gguarro/miniconda3/envs/strategic-finance-forecasts/lib/python3.8/site-packages/sktime/datatypes/_series/_convert.py?line=78)     raise TypeError("input is not a pd.DataFrame")
>      [81](file:///Users/gguarro/miniconda3/envs/strategic-finance-forecasts/lib/python3.8/site-packages/sktime/datatypes/_series/_convert.py?line=80) if len(obj.columns) != 1:
> ---> [82](file:///Users/gguarro/miniconda3/envs/strategic-finance-forecasts/lib/python3.8/site-packages/sktime/datatypes/_series/_convert.py?line=81)     raise ValueError("input must be univariate pd.DataFrame, with one column")
>      [84](file:///Users/gguarro/miniconda3/envs/strategic-finance-forecasts/lib/python3.8/site-packages/sktime/datatypes/_series/_convert.py?line=83) if isinstance(store, dict):
>      [85](file:///Users/gguarro/miniconda3/envs/strategic-finance-forecasts/lib/python3.8/site-packages/sktime/datatypes/_series/_convert.py?line=84)     store["columns"] = obj.columns[[0]]
> 
> ValueError: input must be univariate pd.DataFrame, with one column

**Versions**
System:
    python: 3.8.13 (default, Mar 28 2022, 06:16:26)  [Clang 12.0.0 ]
executable: /Users/gguarro/miniconda3/envs/strategic-finance-forecasts/bin/python
   machine: macOS-10.16-x86_64-i386-64bit

Python dependencies:
          pip: 22.2.2
   setuptools: 59.8.0
      sklearn: 1.1.2
       sktime: 0.14.0
  statsmodels: 0.13.2
        numpy: 1.22.4
        scipy: 1.8.1
       pandas: 1.4.3
   matplotlib: 3.6.0
       joblib: 1.2.0
        numba: 0.56.2
     pmdarima: 2.0.1
      tsfresh: None

</details>

**Comment by LoicRaillon** [comment]
If you want to use Fourier series as features you need to replace `TransformedTargetForecaster` by `ForecastingPipeline`.

**Comment by aiwalter** [comment]
Can you try to mimimize te example by just fitting the forecaster? I think `ARIMA` cant do a vector forecast but seems the created features are given as `y` to it? Might that answer your question?

**Comment by fkiraly** [comment]
I think this is a special case of this known bug in the `pmdarima` interface: https://github.com/sktime/sktime/issues/3657

**Comment by GianlucaGuarroSonos** [comment]
Following @LoicRaillon advice fixes the problem. Using `ForecastingPipeline` seems to do the trick. Maybe I can suggest a bit of discussion regarding when to use `ForecastingPipeline` vs `TransformedTargetForecaster` in the 01_forecasting.ipynb example?
