### ISSUE TITLE
[BUG] testing deep learning base class fails due to optimizer type

### ISSUE THREAD

**Issue by TonyBagnall** [sktime/sktime#3816]
**Describe the bug**

 test_deep_estimator_full[keras-adamax] is failing due to a type check in keras. See, for example

https://github.com/sktime/sktime/actions/runs/3495913658/jobs/5855642783

"ValueError: `optimizer` of type <class 'keras.optimizers.optimizer_v2.adamax.Adamax'> cannot be serialized, it should either be absent/None/str/tf.keras.optimizers.Optimizer object"

it could be that the wrong type of Optimizer is being used, output states

Optimizer  = <class 'keras.optimizers.optimizer_experimental.optimizer.Optimizer'>
whereas it is expecting
tf.keras.optimizers.Optimizer

![image](https://user-images.githubusercontent.com/9594042/202723857-05d98e12-f03b-40e5-a4ac-97405b330638.png)

I don't want to hack around in the testing suite, I'll let someone who understands it better do that,

**Comment by TonyBagnall** [comment]
I assume so, since nothing has changed our side.

**Comment by fkiraly** [comment]
temporarily skipped here:
https://github.com/sktime/sktime/pull/3817

not resolved - still needs a bugfix.

@achieveordie, I think you wrote the test so might have a good idea on what´s going on?

**Comment by RikStarmans** [comment]
@fkiraly, the bug pointed out by @TonyBagnall  is on sktime its side.
The problem resides in your build system. I would you use https://python-poetry.org/. This would raise an error if you have an incompatible version of keras installed.

**Comment by achieveordie** [comment]
Things seem to be breaking after their update. To ensure smooth sailing, we could replace `keras.optimizers` with `tf.keras.optimizers` in our import statement.

Of course, one can argue that our build should hold more specific versions as said by @RikStarmans, but I'm not sure what would be the "right" approach. On one hand, the current code enables us to catch and correct such changes while on the other we'd ensure the test suite works without fail.

We should choose the latter for releases but the case here is for dev.

**Comment by fkiraly** [comment]
> You should fix your external packages as you wrap them and they change all the time.
I also received warnings that "things" have changed.

@RikStarmans, there is a longer discussion on fixing bounds for package versions
https://github.com/sktime/sktime/issues/1480
this has only posts by me, but I remember there being long discussions, possibly in issues referencing this or on slack.
