### ISSUE TITLE
[DOC] fix incomplete `ForecastingPipeline` docstring

### ISSUE THREAD

**Issue by fkiraly** [sktime/sktime#3826]
The docstring of `ForecastingPipeline` seems very incomplete.

I remembered this being better, but I must have misremembered.

Much can be copy-pasted from `TransformedTargetForecaster`, see there.

FYI @aiwalter

**Comment by darshitsharma** [comment]
Hi @fkiraly,
May I work on this issue (#3826)?

**Comment by fkiraly** [comment]
Of course, @darshitsharma, all yours! Let us know if you need help to get started.

**Comment by advinsuryavanshi** [comment]
@fkiraly 
May I work on this issue (https://github.com/sktime/sktime/issues/3826)?

**Comment by fkiraly** [comment]
@darshitsharma, are you still working on this PR? https://github.com/sktime/sktime/pull/3840

**Comment by darshitsharma** [comment]
Yes @fkiraly, I am on it.

**Comment by fkiraly** [comment]
> May I work on this issue (https://github.com/sktime/sktime/issues/3826)?

As @darshitsharma is still working on it, @advinsuryavanshi, you could either pick another good first issue, or help with #3840 by giving a review.

**Comment by advinsuryavanshi** [comment]
Ok sir
