### ISSUE TITLE
[BUG] Ensemble model cant be loaded after pickle

### ISSUE THREAD

**Issue by mateocomba123** [sktime/sktime#3831]
I have .pkl files generated from EnsembleForecaster class models of Sktime, pickled them with:

pickle.dump(model, 'final_ensemble.pkl', 'wb')

and then load it with:

pickled_model = pickle.load(open('final_ensemble.pkl', 'rb'))

But when I call the .predict method it says that 'Series' object has no attribute 'predict'

I think the model somehow was serialized but couldnt be unserialized

Is there anything I am doing wrong or workaround to solve this issue?

**Comment by aiwalter** [comment]
Pls provide minimal code to repepduce

**Comment by mateocomba123** [comment]
It was my bad, trying to open the pickle file without the .load() method. You can close the issue.Thanks so much! El 24 nov. 2022, a la(s) 13:54, Martin Walter ***@***.***> escribió:﻿
Pls provide minimal code to repepduce
