### ISSUE TITLE
[ENH] interface the `seasonal` package as a parameter estimator for seasonality (`BaseParamFitter` descendant)

### ISSUE THREAD

**Issue by fkiraly** [sktime/sktime#3835]
We now have an interface design for generic parameter estimators, with `BaseParamFitter`.
(original design issue: https://github.com/sktime/sktime/issues/1056)

Still experimental, we should further explore it by interfacing useful parameter estimators.

@mloning suggested the methods in the `seasonal` package in https://github.com/sktime/sktime/issues/1056, given the existing base class interface and seasonality examples it seems like a good first issue.

**Comment by das-ankur** [comment]
Can I work on this issue?

**Comment by fkiraly** [comment]
of course, all yours!

**Comment by das-ankur** [comment]
okay. Thanks.

**Comment by blazingbhavneek** [comment]
Hey! I see this issue is pending for a lot time now! Can I take this? (Also, I need to create a new file or change seasonality.py-SeasonalityACF ?)

**Comment by fkiraly** [comment]
> Can I take this? 

Yes, it is more than a month, so it's open again!

> I need to create a new file or change seasonality.py-SeasonalityACF

You should start with a new file, but you can copy `seasonality.py` and take it as a template (just a suggestion).

**Comment by blazingbhavneek** [comment]
Hey! I did the task, but I have a few questions,
1. Does seasonalityACF and seasonal have to return the same result? (because the one I interfaced gave a negative `sp` on airline_data)
2. What to name the new file? What should be the class name? Or should I keep that in the same file with a different class name?
3. Should I also write the test function for it the test file?

**Comment by fkiraly** [comment]
> Does seasonalityACF and seasonal have to return the same result? (because the one I interfaced gave a negative sp on airline_data)

Not necessarily, there are different algorithms inside. Although I'm surprise to see negative `sp`, shouldn't seasonality parameter be an integer strictly larger than 1?

> What to name the new file? What should be the class name? Or should I keep that in the same file with a different class name?

Not sure - could be in the same file (`seasonality`), or `seasonal` after the package name being interfaced. The class name could be the interfaced method, in UpperCamelCase.

> Should I also write the test function for it the test file?

There are some default test for parameter estimators, a test to add would be checking of the output of the `sktime` interface against the interfaced logic (should give same output on same/comparable data)

**Comment by blazingbhavneek** [comment]
Hey! I ran some tests on my own (pardon my naive approach):

![image](https://user-images.githubusercontent.com/86467990/216127159-e7947e47-4728-4a88-9fdd-43a0fe36d7ed.png)

![image](https://user-images.githubusercontent.com/86467990/216129394-0184f906-1ad0-4364-92dc-fa4e4966d9b7.png)

![image](https://user-images.githubusercontent.com/86467990/216129508-8c4709a9-37fe-4127-a7b1-19b74327e363.png)

Should I still make a PR for this? Or should I properly research the working of  `seasonal` and our implementations for trends/seasonality?

**Comment by fkiraly** [comment]
> Hey! I ran some tests on my own (pardon my naive approach, Should I still make a PR for this? 

PR would be much appreciated! Even if it's not done, we can always discuss in a draft!

Regarding the output, I think what you wrote is close to a transformer than a parameter estimator:

* a parameter estimator would tell you at which periodicities the estimator detected a seasonality. That would be integers, e.g., 2 (months), 12 (months), etc. Example for this is `SeasonalityACF`.
* a transformer is sth that removes seasonality, or produces the seasonal component. An example for this is `STLTransformer`, or `Deseasonalizer`

From your printout, I suspect that you could easily turn your current class into the first one, you just need to return the seasonality that is fitted instead of the deseasonalized series as the `sp` fitted parameter.

**Comment by blazingbhavneek** [comment]
Hey! I forgot to create a new PR for this, but [here's the link](https://github.com/sktime/sktime/pull/4146/commits/1e3ccfd2c9e1c2c97b325b171d284394201b66ac) to it; I have college exams in a few days, so I will make changes and create a new PR after that only.

**Comment by fkiraly** [comment]
@blazingbhavneek, could you kindly make a separate pull request for the seasonal estimator?
Instead of putting it in the same PR as the fourier transform.
