### ISSUE TITLE
 [GOV] Evolution of sktime governance

### ISSUE THREAD

**Issue by aiwalter** [sktime/sktime#3865]
**Is your feature request related to a problem? Please describe.**
This issue aims to identify sections in sktime governance that are "undemocratic". General idea of this discussion is to give more power to the core developers to avoid that individuals can take hostage of sktime. 

Undemocratic in this context are for example current gov items:
- Single individuals can block nomination of CC or CoC members, 
see #3939
- CC can supersede core dev votes. This can lead to offending majority of core devs,
see #3937
- CC and CoC nominations are currently for lifetime. This should be changed, so a nomination ends e.g. after 2 years. Then another core dev vote has to happen. This is common practice in any org that claims to have a democratic governance. 
see #3868
- Separation of power between CC and CoC, currently there is no separation on member level.
see #3870

**Describe the solution you'd like**
I will make separate PRs for the different topics. Discussion can happen at PR. General discussion can happen at this issue.

**Comment by fkiraly** [comment]
@aiwalter, I think the implication that sktime governance is undemocratic is wholly inappropriate. We have a representative decision making system and voting.

This is also not sufficiently addressing problems we have seen recently emerge in discussion culture.

I think these parallel issues that wikipedia is seeing, especially things like hounding, single-issue vote piling by people who do not really contribute to the community.

The key parallel concept would be "clearly not being here to build a package":
https://en.wikipedia.org/wiki/Wikipedia:Here_to_build_an_encyclopedia#Clearly_not_being_here_to_build_an_encyclopedia

Related issues:

* https://en.wikipedia.org/wiki/Wikipedia:Civil_POV_pushing
* https://en.wikipedia.org/wiki/Wikipedia:POV_Railroad

**Comment by aiwalter** [comment]
I didnt say the governance in undemocratic in general, but there are parts of it that are clearly undemocratic as mentioned above. The general idea of this issue is to give more power to the core developers, who are the main representatives of the community.

**Comment by fkiraly** [comment]
You are making PR that abolish separation of duties/powers and strongly imply that we are currently undemocratic.

**Comment by fkiraly** [comment]
"clearly undemocratic" is a misrepresentation of how representative democracies and multi-chamber systems work.

Democratic does not mean that a given person always get what they want. In representative democracies like the one you live in, it does not even mean that the majority always gets what it wants.

**Comment by fkiraly** [comment]
This is a populist move, and possibly plan to seize control of sktime.

Given [current conflicts of interest](https://github.com/sktime/community-org/blob/main/community_council/previous_meetings/20221108-meeting.md) I ask you to refrain from trying to completely rewrite the decision making mechanisms of sktime.

Especially:

* trying to effectively remove independence of the entity that investigate CoC incidents
* trying to rewrite the rules that allow you to kick other people out quickly

**Comment by aiwalter** [comment]
@fkiraly can you pls kindly not rename my PR titles, thx. If you think the title is not appropriate, pls comment here why.

**Comment by fkiraly** [comment]
> @fkiraly can you pls kindly not rename my PR titles, thx. If you think the title is not appropriate, pls comment here why.

Description should refer to the specific proposed changes and not just vaguely label this as "democratization".

There is also an implication that governance is not democratic, which is inappropriate.

Please do not revert the title change, or at least address the inappropriate implication.

**Comment by aiwalter** [comment]
>  major change proposal to sktime governance

does not say anything about the content, "Democratization of sktime governance" does, also is it not abit childish what you are doing? Its an issue I have opened, so can you not respect it that I decide what its written in the title?

**Comment by fkiraly** [comment]
With respect, you want to abolish separation of powers/duties. That is not democratic.

**Comment by fkiraly** [comment]
> bit childish what you are doing?

stop the insults please.

this is just basic "title should accurately reflect the content" policy, I have also explained to you the negative impication of the title.

**Comment by patrickzib** [comment]
I recall: „Remove questionable HIVE-COTE2 classifier“

**Comment by fkiraly** [comment]
@aiwalter, @patrickzib, kindly take note of the last paragraph in this issue on how I will enforce the code of conduct in public discussion spaces such as this: https://github.com/sktime/sktime/issues/3882#issuecomment-1336287948

**Comment by patrickzib** [comment]
Just to understand this: You are using your power as CoC to block discussions on @fkiraly breaking the code of conduct, correct?

**Comment by aiwalter** [comment]
renamed issue after discussion in CC

**Comment by KatieBuc** [comment]
@aiwalter, these suggestions make a lot of sense in my opinion. 

@fkiraly "This is a populist move, and possibly plan to seize control of sktime."
There's quite a lot to unpack here, I hope that with a bit of time you'll come to understand the irony of this statement.

**Comment by fkiraly** [comment]
superseded by aiwalter moving to the project fork
