### ISSUE TITLE
[ENH] DTW_D algorithm

### ISSUE THREAD

**Issue by pabhidnya15** [sktime/sktime#3891]
I need the DTW_D classifier used in 'The great multivariate time series classification bake off: a review and experimental evaluation of recent algorithmic advances' for 26 UEA datasets. In the current sktime package, I see only ShapeDTW. Where can I find only DTW_D to process the datset?

**Comment by fkiraly** [comment]
I cannot find a reference for DTW-D that isn't behind a paywall, but I think this is just DTW where you plug in the multi-variate Euclidean distance? Is that correct?

In that case you could plug it together as follows:

```python
from sktime.alignment import AlignerDTWfromDist
from sktime.dists_kernels.scipy_dist import ScipyDist
from sktime.dists_kernels.compose_from_align import DistFromAligner

# multivariate euclidean distance
eucl_dist = ScipyDist()
# ddtw alignment = DTW alignment using multivariate euclidean distance
ddtw_align = AlignerDTWfromDist(eucl_dist)
# ddtw distance = distance matrix of the ddtw aligner
ddtw_dist = DistFromAligner(ddtw_align)
```

**Comment by fkiraly** [comment]
not sure though whether dtw_d is simply the multivariate alignment distance. If you could paste a formula from the paper behind the paywall, that would be appreciated.

**Comment by pabhidnya15** [comment]
I am referring to 'Dependent Warping' here. [https://link.springer.com/article/10.1007/s10618-020-00727-3](url)
Please refer to the definition in the paper. 
[https://link.springer.com/article/10.1007/s10618-020-00727-3/tables/6](url) has a table with accuracies for different algorithms. One of the algorithms is DTW_D. I am just wondering if the KNNClassifier in sktime considers DTW_D (Dependent warping distance) for multivariate time series classification.

**Comment by TonyBagnall** [comment]
hi, the current default DTW distance function uses DTW_D, @chrisholder, I'll post a simple example later

**Comment by fkiraly** [comment]
> hi, the current default DTW distance function uses DTW_D, @chrisholder, I'll post a simple example later

Documentation in the docstrings of what happens in the multivariate case would be better.

**Comment by chrisholder** [comment]
Hi @pabhidnya15 - The implementations for all these distance is avaliable from sktime.distances. Unfortunatly we have some internal issue that mean some don't want these to be public facing functions and instead wrapped in classes (don't ask me why I strongly disgree with this).

However, you can still access all this code even though it is on the public API:


```
import numpy as np
from sktime.distances import distance

x_2d = np.array(
    [[2, 35, 14, 5, 68, 7.5, 68, 7, 11, 13], [5, 68, 7.5, 68, 7, 11, 13, 5, 68, 7]]
)
y_2d = np.array(
    [[8, 19, 10, 12, 68, 7.5, 60, 7, 10, 14], [15, 12, 4, 62, 17, 10, 3, 15, 48, 7]]
)

distance(x_2d, y_2d, metric='dtw')
```

This will perform the dependent dtw which is implemented and checking against 'The great multivariate time series classification bake off: a review and experimental evaluation of recent algorithmic advances'.

In addition we have implementations of all of the distances from that paper that can be used in the same way:

distance(x_2d, y_2d, metric='dtw')
distance(x_2d, y_2d, metric='dtw')
distance(x_2d, y_2d, metric='dtw')
distance(x_2d, y_2d, metric='dtw')
distance(x_2d, y_2d, metric='dtw')
distance(x_2d, y_2d, metric='dtw')
distance(x_2d, y_2d, metric='dtw')

**Comment by pabhidnya15** [comment]
Your comments help a lot! Thanks

**Comment by TonyBagnall** [comment]
this also works for DTW_D. 

```from sktime.distances import dtw_distance
import numpy as np
instance1 = np.array([[1,2,3,4], [4,3,2,1]])
instance2 = np.array([[2,3,4,5], [5,4,3,2]])
print(" shape is [n_dimensions, series_length] = ", instance1.shape)
print(" DTW_D is = ", dtw_distance(instance1, instance2))
```
The distance API PR is here,  https://github.com/sktime/sktime/pull/3852, currently blocked, we will work towards resolving

**Comment by fkiraly** [comment]
to resolve: the dtw algorithms are by default dependent.

PR https://github.com/sktime/sktime/pull/4498 supplies a generic wrapper to create arbitrary independent distances, which terefore should resolve the request.
