### ISSUE TITLE
[ENH] DummyRegressor for straw man comparison when benchmarking

### ISSUE THREAD

**Issue by TonyBagnall** [sktime/sktime#3899]
**Is your feature request related to a problem? Please describe.**

There is a DummyClassifier in the classification package. It would be useful to have an equivalent straw man in the Regression package for those who think they are a sensible benchmark. 

**Describe the solution you'd like**

A class DummyRegressor that extends BaseRegressor using the template that predicts the mean of the response variable in the train file. Other dummy settings could be possible. 

**Describe alternatives you've considered**
We can just work out the mean and use it as a benchmark, as we could with class distribution, but since there is a DummyClassifier, seems there should be a DummyRegressor.

**Comment by fkiraly** [comment]
added good first issue label - should be extremely easy, almost a copy-paste of the `DummyClassifier` in `sktime`
