### ISSUE TITLE
[BUG]

### ISSUE THREAD

**Issue by Dabs212** [sktime/sktime#3929]
Import Error
1
import warnings
2
import numpy as np
3
import pandas as pd
4
# hide warnings
5
warnings.filterwarnings("ignore")
6
from sktime.datasets import load_airline
7
from sktime.utils.plotting import plot_series
8
from sktime.forecasting.base import ForecastingHorizon
9
from sktime.forecasting.compose import ReducedRegressionForecaster
10
from sktime.utils.plotting import plot_series
11
#from sktime.utils.plotting.forecasting import plot_series
12
from sklearn.svm import SVR
13
from sklearn.linear_model import LinearRegression
14
from sklearn.neighbors import KNeighborsRegressor
15
from sklearn.ensemble import RandomForestRegressor
16
from sklearn.tree import DecisionTreeRegressor
17
from sktime.forecasting.naive import NaiveForecaster
18
from sktime.performance_metrics.forecasting import smape_loss
19
#
20
from sktime.forecasting.model_selection import temporal_train_test_split
21
from sktime.datasets import load_airline
22
import matplotlib.pyplot as plt
23
airline = load_airline()
24
y_train,y_test = temporal_train_test_split(airline, test_size=36)
25
fh = list(range(1,37))
26
listOfRegressors = [DecisionTreeRegressor(), RandomForestRegressor(n_estimators=30),
27
                   LinearRegression(), KNeighborsRegressor(n_neighbors=2), 
28
                   SVR()]
29
from sktime.forecasting.model_selection import temporal_train_test_split
30
from sktime.datasets import load_airline
31
import matplotlib.pyplot as plt
32
airline = load_airline()
33
y_train,y_test = temporal_train_test_split(airline, test_size=36)
34
fh = list(range(1,37))
35
listOfRegressors = [DecisionTreeRegressor(), RandomForestRegressor(n_estimators=30),
36
                   LinearRegression(), KNeighborsRegressor(n_neighbors=2), 
37
                   SVR()]
38
list_of_smape = []
39
​
40
for regressor in listOfRegressors:
41
    reduced_reg = ReducedRegressionForecaster(regressor = regressor, window_length=10)
42
    reduced_reg.fit(y_train)
43
    y_pred = reduced_reg.predict(fh)
44
    list_of_smape.append(smape_loss(y_test, y_pred))
45
list_of_smape
46
reduced_reg = ReducedRegressionForecaster(regressor = LinearRegression(), window_length=10)
47
reduced_reg.fit(y_train)
48
y_pred = reduced_reg.predict(fh)
49
plot_series(y_train, y_test, y_pred, labels = ["Training Values", "Testing Values", "Predicted Values"])
---------------------------------------------------------------------------
ImportError                               Traceback (most recent call last)
Cell In[1], line 9
      7 from sktime.utils.plotting import plot_series
      8 from sktime.forecasting.base import ForecastingHorizon
----> 9 from sktime.forecasting.compose import ReducedRegressionForecaster
     10 from sktime.utils.plotting import plot_series
     11 #from sktime.utils.plotting.forecasting import plot_series

ImportError: cannot import name 'ReducedRegressionForecaster' from 'sktime.forecasting.compose' (C:\Users\suche\AppData\Roaming\Python\Python38\site-packages\sktime\forecasting\compose\__init__.py)

**Comment by aiwalter** [comment]
Hi, do you mind to follow the bug report issue template? You can there "Issue" --> "New Issue" --> "Bug report"

**Comment by Dabs212** [comment]
Surely, thanks
Vivek R. Dabholkar 

    On Tuesday, December 13, 2022 at 01:24:26 PM CST, Martin Walter ***@***.***> wrote:  
 
 


Hi, do you mind to follow the bug report issue template? You can there "Issue" --> "New Issue" --> "Bug report"

**Comment by arnavrneo** [comment]
@aiwalter Hello sir,

I looked into the source code and found that there was no function named `ReducedRegressionForecaster` in `compose_init_.py`.
I also found an old bug #668 that looks similar to this one.

## Workaround
Doing `git checkout v0.5.2` seems to solve the issue (downgrading to v0.5.2).
