### ISSUE TITLE
[ENH]Plot Title

### ISSUE THREAD

**Issue by Dabs212** [sktime/sktime#3944]
**Is your feature request related to a problem? Please describe.**
A clear and concise description of what the problem is.
Currently plot_series has no place to enter plot title
**Describe the solution you'd like**
A clear and concise description of what you want to happen, ideally taking into consideration the existing toolbox design, classes and methods.
It would be nice to introduce a user-defined parameter title that user can fill in.
**Describe alternatives you've considered**
None
**Additional context**
None

**Comment by chillerobscuro** [comment]
This would be a straightforward fix, check out my PR where I [add color](https://github.com/sktime/sktime/pull/3908) as an argument to `plot_series` if you'd like to give it a go.

In the meantime, you can set the title after calling the function like so:
```
fig, ax = plot_series(ytrain[-12:], ytest, labels=['ytrain', 'ytest']);
ax.set_title('Test Title')
```

**Comment by Dabs212** [comment]
Thanks a lot, I will definitely give it a try

**Comment by miraep8** [comment]
Agree that this would be a good change!  In case you are new @Dabs212 [here is our contribution guide](https://www.sktime.org/en/v0.14.1/get_involved/contributing.html).  Please reach out in the slack if you get stuck.  Sometimes the first PR can be a bit tricky as there are a few things you need to set up on your end.  Good luck and thanks for working on this solution!

**Comment by arnavrneo** [comment]
Hi @miraep8,

As this issue is still open, I would like to work on this. Can you assign it to me?

**Comment by miraep8** [comment]
Sure thing!  Ping us when you have a PR to review :)
