### ISSUE TITLE
[ENH] python 3.11 support

### ISSUE THREAD

**Issue by fkiraly** [sktime/sktime#3963]
update, Feb 23, 2023: `numba` is now fully isolated, and `sktime` release 0.16.1 has been released with experimental 3.11 support.
Issues that remain to fix before full support in 0.17.0:

* soft dependencies need to be checked with 3.11, and restrictions removed where appropriate https://github.com/sktime/sktime/pull/4269
* conda issues with 3.11 need to be fixed https://github.com/conda-forge/sktime-feedstock/issues/66
  this is waiting for migration, and is not necessarily blocking 0.17.0

---
Umbrella issue for discussing python 3.11 support, to direct frequent questions to.

Current blockers to the "naive" solution of releasing `sktime` for 3.11 as-is, as far as I know:

* `numba` is a core dependency and not python 3.11 compatible
* a number of soft dependencies do not have python 3.11 support

Potential solutions:

* soft dependencies are all isolated, so conditional install in `pyproject.toml` would fix the issue. This would require us to check python 3.11 support for soft dependencies periodically and potentially remove the condition at a later point in time.
* `numba` could be solved by "wait for python 3.11 support". When that happens is unclear.
* or, we can turn `numba` into a soft dependency right now, and deal with it as with the other soft dependencies. This is entirely feasible - the PR here could be merged and enable python 3.11 https://github.com/sktime/sktime/pull/3856. But, it is a very contentious issue with some core developers.
* a third option keeps `numba` as core dependency, but makes it optional *only on python 3.11*, until it becomes compatible. This option is implemented here, ready for merge and enable: https://github.com/sktime/sktime/pull/4000. As it turns out, this is also very contentious.

**Comment by fkiraly** [comment]
FYI @alexanderreschjedox, I tried to summarize the situation above.

**Comment by jplatipus** [comment]
The github page should be updated: currently https://github.com/sktime/sktime says sktime works with python 3.11, but I get a conflict report:

> (sktimeTests) C:\Users\jacqu>conda install -c conda-forge sktime
Collecting package metadata (current_repodata.json): done
Solving environment: failed with initial frozen solve. Retrying with flexible solve.
Solving environment: failed with repodata from current_repodata.json, will retry with next repodata source.
Collecting package metadata (repodata.json): done
Solving environment: failed with initial frozen solve. Retrying with flexible solve.
Solving environment: |
Found conflicts! Looking for incompatible packages.
This can take several minutes.  Press CTRL-C to abort.
failed

> UnsatisfiableError: The following specifications were found
to be incompatible with the existing python installation in your environment:

> Specifications:

>   - sktime -> python[version='>=3.6,<3.7.0a0|>=3.7,<3.8.0a0|>=3.8,<3.9.0a0|>=3.9,<3.10.0a0']

> Your python: python=3.11

> If python is on the left-most side of the chain, that's the version you've asked for.
When python appears to the right, that indicates that the thing on the left is somehow
not available for the python version you are constrained to. Note that conda will not
change your python version to a different minor version unless you explicitly specify
that.

**Comment by fkiraly** [comment]
@jplatipus, as far as I know `sktime` works on 3.11 from version 0.16.1 onwards. Support is currently experimental.

3.11 compatibility is tested in the CI/CD pipeline, and I just checked `pip install` from `conda` and I do not get the message.
`pip` (e.g., from `conda`) is how the majority of users are installing `sktime`, and this works as intended.

Now you are using `conda-forge`, i.e., `conda install -c conda-forge sktime`.
I just tried in a python 3.11 environment, on Windows OS, and it seems to get stuck (not getting an `UnsatisfiableError`)

I will open an issue to track this.

**Comment by fkiraly** [comment]
FYI @dhirschfeld, @freddyaboulton - any good ideas?
(I will also try to look into this later after work)

**Comment by fkiraly** [comment]
Issue is here: https://github.com/sktime/sktime/issues/4254

**Comment by nhoening** [comment]
Can this issue be closed? 

sktime is now at  version 33, while this issue discusses version 16.

The project description claims support for 3.11 and 3.12 and several more recent issues are claiming they use 3.12

**Comment by fkiraly** [comment]
yes, this has accidentally remained open. We support python 3.11 since ages ago. Due to dependency isolation, we typically support a new python version a few weeks after all core deps do (sklearn and pandas, are the bottlenecks, typically).

Thanks for reporting, @nhoening!
