### ISSUE TITLE
[BUG] TSFreshFeatureExtractor does not handle unequal length data

### ISSUE THREAD

**Issue by artdgn** [sktime/sktime#397]
**Describe the bug**
Not sure if this is a bug or documentation issue but I can't figure out what's the correct format for using this library.

**To Reproduce**
The tutorial with `load_arrow_head` examples work, but I can't figure out how to get my own data into the right format.

I'm trying to work with an already existing dataframe, in which I already have series vectors. 

### 1st attempt, numpy arrays:
```py
import pandas as pd
import numpy as np

from sktime.transformers.series_as_features.summarize import TSFreshFeatureExtractor

transformer = TSFreshFeatureExtractor(default_fc_parameters="minimal")

# most natural, arrays?
df_arrs = pd.DataFrame({'id': ['a', 'b'],
                        'values': [np.array([1, 2]), np.array([3, 4, 5])]})
"""
>>> df_arrs
  id     values
0  a     [1, 2]
1  b  [3, 4, 5]

>>> type(df_arrs.iloc[0, 1])
 <class 'numpy.ndarray'>
"""

transformer.fit_transform(df_arrs[['values']])
"""
...
    f"Length mismatch: Expected axis has {old_len} elements, new "
ValueError: Length mismatch: Expected axis has 1 elements, new values have 2 elements
"""
```
### 2nd attempt, maybe vectors need to be Series like in tutorials?:
```py
# maybe series?
df_sers = pd.DataFrame({'id': ['a', 'b'],
                        'values': [pd.Series([1, 2]), pd.Series([3, 4, 5])]})
"""
>>> df_sers.iloc[0, 1]
0    1
1    2
dtype: int64

>>> type(df_sers.iloc[0, 1])
<class 'pandas.core.series.Series'>
"""

transformer.fit_transform(df_sers[['values']])
"""
    f"Length mismatch: Expected axis has {old_len} elements, new "
ValueError: Length mismatch: Expected axis has 1 elements, new values have 2 elements
"""

```
### 3rd attempt, maybe dataframes?:
```py
# maybe dataframes?
df_dfs = pd.DataFrame({'id': ['a', 'b'],
                       'values': [pd.DataFrame([1, 2]), pd.DataFrame([3, 4, 5])]})
"""
>>> df_dfs.iloc[0, 1]
   0
0  1
1  2

>>> type(df_dfs.iloc[0, 1])
<class 'pandas.core.frame.DataFrame'>
"""

extracted_features = transformer.fit_transform(df_dfs[['values']])
"""
    f"Length mismatch: Expected axis has {old_len} elements, new "
ValueError: Length mismatch: Expected axis has 1 elements, new values have 2 elements
"""

```

In the existing examples I've only found the `from_long_to_nested` function and example. But it seems a convoluted and specific format, and would require exploding the vectors and adding the additional specific tripple-index columns manually.

**Versions**

`sktime` version is 0.4.1 and there seems to be no `show_versions` in this version.

**Comment by mloning** [comment]
Hi @artdgn, thanks for raising the issue! 

Looks like our TSFreshTransformer doesn't support unequal-length data yet, mainly because we rely on our `tabularize` function internally when going from the nested input format to the long format expected by tsfresh, even though we could represent unequal length data in the long format. 

I also noted that the index name is hard coded in the data conversion. 

This code works for me. 
```python
import pandas as pd
import numpy as np

from sktime.transformers.series_as_features.summarize import TSFreshFeatureExtractor

transformer = TSFreshFeatureExtractor(default_fc_parameters="minimal")

# equal length data
X = pd.DataFrame({'id': ['a', 'b'], 'values': [pd.Series([1, 2, 2]), pd.Series([3, 4, 5])]}).set_index("id")

# change index name
X.index.name = "index"

transformer.fit_transform(X)
```

**Comment by artdgn** [comment]
@mloning Thanks, I didn't consider the possibility it expects equal lengths. I've now tried my dummy example with equal length vectors and it works (even without the need to set the index name).

This is helpful, because knowing this limitation it is still possible to use this transformer with various truncating / padding strategies (depends on what makes sense for the time series domain), so it's not too bad.

Maybe worth to consider these options as short time fixes:
1. Might be worth to mention that fact in both the docs, and more importantly in the classification tutorial (where it is the first example).
2. Until you have time to refactor and fix this, I think a simple detection and warning / ValueError about trying to pass unequal length data to `tabularize` might prevent this kind of confusion. A somewhat more complex version of this "safer" behaviour might be together with the waning to just truncate the the vectors to same length (and warn about this behaviour).

**Comment by mloning** [comment]
Thanks @artdgn, we're currently working on a better way to store and handle unequal length (and other time heterogenous) data, what data containers do you usually use for that type of data?

**Comment by artdgn** [comment]
Sounds great, will be interesting to see what you come up with. I'm using mostly boring structures like flat dataframes (I think you refer to them as "long"), or nested and grouped intro vectors (as in this example). I think due to the complexity of representing data in this problem space, it would be good to have a clear dedicated set of functionality in your package to transform data between different formats, and also a specific tutorial / docs on working with them.

**Comment by MatthewMiddlehurst** [comment]
This no longer seems to be an issue, both versions of the TSFresh transformer can transform the univariate and multivariate example datasets.
