### ISSUE TITLE
[BUG] build tag in README looks odd, possibly needs fixing

### ISSUE THREAD

**Issue by fkiraly** [sktime/sktime#3983]
The build tag in the README looks strange and should be fixed:

![image](https://user-images.githubusercontent.com/7985502/209253787-40ce6a56-671d-4115-8006-90a18276cf30.png)

Not sure what's going on there or since when. It is also odd that a click on it leads back to year old build runs.

**Comment by Rishav1707** [comment]
Do you want to remove the build tag from the readme? or something else you want @fkiraly

**Comment by fkiraly** [comment]
I'd prefer to have it fixed. It should be just a small tag that says whether the latest build on `main` was successful.

**Comment by Saumya-ranjan** [comment]
I'd like to take this up. I would really appreciate some clarification on the same

**Comment by fkiraly** [comment]
> I would really appreciate some clarification on the same

Sure! For those who have experience in tags (I do not count myself among those fortunate individuals), it should be a one-line fix.

I remember that, a while ago, it used to be a very small tag and be either green or red, and possibly say sth like "failed" or "succeeded", rather than containing an URL that links to an issue in the `badges` repository.

Perhaps there is some information on deprecation or a recent change if you follow that URL, I have not checked.
