### ISSUE TITLE
[BUG] ForecastX is returning wrong predictions

### ISSUE THREAD

**Issue by aiwalter** [sktime/sktime#3986]
**Describe the bug**
`ForecastX` returns weird predictions, when I recreate the composition manually I get different results, see below.

**To Reproduce**

```python
from sktime.datasets import load_longley
from sktime.forecasting.arima import ARIMA
from sktime.forecasting.base import ForecastingHorizon
from sktime.forecasting.compose import ForecastX
from sktime.forecasting.var import VAR
from sktime.forecasting.model_selection import temporal_train_test_split
import pandas as pd

y, X = load_longley()
y_train, y_test, X_train, X_test = temporal_train_test_split(y, X, test_size=3)
fh = ForecastingHorizon([1, 2, 3])
columns=["ARMED", "POP"]

# ForecastX
pipe = ForecastX(  
    forecaster_X=VAR(),
    forecaster_y=ARIMA(),
    columns=columns,
)
pipe = pipe.fit(y_train, X=X_train, fh=fh) 
# dropping ["ARMED", "POP"] as those are the columns where we expect not to have future values
y_pred = pipe.predict(fh=fh, X=X_test.drop(columns=columns))
y_pred.to_frame()
```
<html>
<body>

  | 0
-- | --
-285606.156664
-276594.299226
-267325.354023

</body>
</html>

**Expected behavior**

Expected would be following, recreated manually:
```python
# fit y forecaster
arima = ARIMA().fit(y_train, X=X_train)

# fit and predict X forecaster
var = VAR()
var.fit(X_train[columns])
var_pred = var.predict(fh)

# predict y forecaster with predictions from VAR
X_pred = pd.concat([X_test.drop(columns=columns), var_pred], axis=1)
arima.predict(fh=fh, X=X_pred).to_frame()
```
<html>
<body>

  | 0
-- | --
70085.541848
70073.339809
72665.367272

</body>
</html>

This makes more sense if we look into what plain `ARIMA` is forecasting:
```python
arima = ARIMA()
arima.fit(y=y_train, X=X_train, fh=fh)
arima.predict(X=X_test).to_frame()
```
<html>
<body>

  | 0
-- | --
70372.810378
70873.888217
73678.534405

</body>
</html>

**Additional context**
I am wonderind how I can use `ForecastX` in `evaluate`? The `X` will be always given with all columns but I want to be sure that `ForecastX` is overwriting the given `columns` in `X` in `predict` so that `forecaster_y` gets the predictions of `forecaster_X` appended with the other columns as input (see above where I reproduced the `ForecastX` coposition manually and use `append`). So even if `X` is given in `predict` with all columns it should overwrite the `columns` specified in `ForecastX(columns=[...])`- is that already like that?

**Versions**
<details>

System:
    python: 3.8.10 (default, Jun 22 2022, 20:18:18)  [GCC 9.4.0]
executable: /local_disk0/.ephemeral_nfs/envs/pythonEnv-8a6aed3a-d844-4ca9-bc34-194086d0db32/bin/python
   machine: Linux-5.4.0-1090-azure-x86_64-with-glibc2.29

Python dependencies:
          pip: 21.0.1
   setuptools: 52.0.0
      sklearn: 0.24.1
       sktime: 0.15.0
  statsmodels: 0.13.5
        numpy: 1.22.4
        scipy: 1.6.2
       pandas: 1.2.4
   matplotlib: 3.4.2
       joblib: 1.0.1
        numba: 0.56.4
     pmdarima: 2.0.2
      tsfresh: None

</details>

**Comment by aiwalter** [comment]
I have just realized that I could not find any unit test for `ForecastX`, I am wondering why this was even released? The above example could be used as a start to write unit tests for this composition to make sure its doing what it should do. 
@fkiraly i think you wrote that composition? Why is there no unit test or am I missing sth?

**Comment by fkiraly** [comment]
> Why is there no unit test or am I missing sth?

There are currently 420 unit tests for `ForecastX` (counting fixture multiplicities):

```python
from sktime.forecasting.compose import ForecastX
from sktime.utils.estimator_checks import check_estimator

res = check_estimator(ForecastX)
len(res)
```

> I am wondering why this was even released?

This is a volunteer driven open source project, so I would advise a more constructive attitude here.

**Comment by fkiraly** [comment]
Here's what a constructive attitude could look like:

> The above example could be used as a start to write unit tests for this composition to make sure its doing what it should do.

Suggestion: do this, then try to diagnose the bug.
I fix bugs in code of others (including yours) plenty of times without pointing blame.

We should appreciate contributions of anyone.
If code is buggy, as core developers, we give advice and help making it better.

**Comment by aiwalter** [comment]
yes there are generic tests (which is nice) but no test to actually test the logic that this `ForecastX` is aiming to provide.

**Comment by fkiraly** [comment]
> yes there are generic tests (which is nice) but no test to actually test the logic that this ForecastX is aiming to provide.

Yes, you are probably right. So, I suggest to proceed with a constructive attitude.

**Comment by aiwalter** [comment]
yes, my constructive contribution was to open this issue already 😸 . Are going to work on this?

**Comment by fkiraly** [comment]
well, in the future you may want to watch your tone and formulations like "why this was even released"

**Comment by aiwalter** [comment]
I think estimators should only be released if the logic is tested at least with minimal custom tests. There is not any custom test for `ForecastX` thats why it might come with a risk for the package reputation if the package gets too buggy due to bugs that could easily be avoided. So I basically still think that this particular estimator should not have been released without some custom tests. This particular bug is even a quite tricky bug as its a silent bug and only advanced users might be able to identify it.

**Comment by fkiraly** [comment]
here's what would be a huge help, @aiwalter: go through the package and write logic/consistency tests for all estimators that don't have any. That would be great.

**Comment by aiwalter** [comment]
Sure, actually `ForecastX` is the first one I have seen that does not have any custom test. I already fixed one bug in `Imputer`, but due to "there is not enough description in the PR head and missing GitHub tags" it didnt make it to new release. So was not too motivating for me to continue debugging and make PRs.

**Comment by fkiraly** [comment]
let's not have this discussion here, this is going off-topic.

**Comment by aiwalter** [comment]
so can you let me know if you plan to work on that? Otherwise I might do so, thx a lot!

**Comment by fkiraly** [comment]
The issue is with the base framework or the base contract, it leaves ambiguous what happens if columns get permuted.

**Comment by fkiraly** [comment]
fix: https://github.com/sktime/sktime/pull/3987

**Comment by aiwalter** [comment]
question regading `ForecastX` using in `evaluate`, as mentioned above already. In `evaluate(y=y, X=X, forecaster=ForecastX(..., columns=["A," "B"])` can you verify that the given columns `["A", "B"]` are overwritten in `predict` with the predictions from `forecaster_X`? Would be great to have a test for that as well if we aggree that overwriting should be the desired behavior?

**Comment by fkiraly** [comment]
>can you verify that the given columns `["A", "B"]` in `X` are overwritten in `predict` with the predictions from `forecaster_X`?

Yes, I think so - line 1265

> Would be great to have a test for that as well if we agree that overwriting should be the desired behavior?

I know I might be repeating myself here - this is a volunteer driven open source project, so usually the best way to get something you want is to make a PR.
