### ISSUE TITLE
[BUG] PerformanceWarning while loading multivariate dataset.

### ISSUE THREAD

**Issue by haskarb** [sktime/sktime#4076]
**Describe the bug**
Warning while loading Duckduckgeese dataset.

```
PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead.  To get a de-fragmented frame, use `newframe = frame.copy()`
  data["dim_" + str(dim)] = instance_list[dim]
```

**To Reproduce**

```python
from sktime.datasets import load_UCR_UEA_dataset
train_x, train_y = load_UCR_UEA_dataset("DuckDuckGeese")
```

**Expected behavior**

Shouldn't be any warning.

**Additional context**

**Versions**
<details>

![Screenshot 2023-01-06 at 15 16 04](https://user-images.githubusercontent.com/20501023/210975230-6937be96-faef-4167-8df0-d6e41d0577e8.png)

</details>

**Comment by wayneadams** [comment]
The PerformanceWarning also comes up with the "FaceDetection" and "PEMS-SF" datasets.

**Comment by fkiraly** [comment]
Might be coming from the `tsf` loader, FYI @hazrulakmal.

**Comment by NealJun** [comment]
@fkiraly Hello, I still have this bug when reading DuckDuckGeese in UEA datasets using the latest version 0.30.1, whether using load_from_tsfile_to_dataframe or load_from_arff_to_dataframe

**Comment by fkiraly** [comment]
I can confirm that this is indeed still the case. Reproduced on windows, python 3.11, current `main`.

FYI @ericjb, perhaps you have an idea since you looked most recently at the loaders?
