### ISSUE TITLE
[BUG] BOSS classifier class names truncated during prediction

### ISSUE THREAD

**Issue by erjieyong** [sktime/sktime#4090]
**Describe the bug**
When calling `predict_proba` on IndividualBOSS classifier, sktime returns KeyError

**To Reproduce**

```
import pandas as pd
import numpy as np
x = pd.Series(np.arange(1.0,10.0))
nested_X = pd.DataFrame({
  "nested_X":[x, x, x]
})
y = pd.Series(['01A', '02A', '01A'], dtype="string", name="classes")

from sktime.transformations.panel.padder import PaddingTransformer
from sktime.classification.dictionary_based import IndividualBOSS

iboss = IndividualBOSS()
iboss.fit(nested_X, y)
iboss.predict_proba(nested_X[0:1])
```

** Output behavior **
```
---------------------------------------------------------------------------
KeyError                                  Traceback (most recent call last)
Cell In[5], line 1
----> 1 iboss.predict_proba(nested_X[0:1])

File c:\Users\anaconda3\envs\env\lib\site-packages\sktime\classification\base.py:262, in BaseClassifier.predict_proba(self, X)
    259     return self._single_class_y_pred(X, method="predict_proba")
    261 # call internal _predict_proba
--> 262 return self._predict_proba(X)

File c:\Users\anaconda3\envs\env\lib\site-packages\sktime\classification\base.py:572, in BaseClassifier._predict_proba(self, X)
    570 dists = np.zeros((n_pred, self.n_classes_))
    571 for i in range(n_pred):
--> 572     dists[i, self._class_dictionary[preds[i]]] = 1
    574 return dists

KeyError: '0'
```

**Expected behavior**
It should return 1 of the 2 unique classes instead of '0'

**Additional context**
I manage to find out that this is due to numpy behavior of changing `str` type to '<U1' which truncates any string to only length of 1.  The particular line of code is at [link](https://github.com/sktime/sktime/blob/8fe509628405eaeaa6cbc26351e946c4a8a54687/sktime/classification/dictionary_based/_boss.py#L619)

Suggest to change it to the following:

```
classes = np.zeros(test_bags.shape[0], dtype=(lambda dtype: "object" if dtype == str else dtype)(type(self._class_vals[0])))
```

Need advise here if I should submit a pull request? Not sure if there's any test cases to run through? Thanks. 

**Versions**
<details>

System:
    python: 3.8.15 (default, Nov 24 2022, 14:38:14) [MSC v.1916 64 bit (AMD64)]
executable: c:\Users\kyunomi\anaconda3\envs\cogpilot\python.exe
   machine: Windows-10-10.0.22621-SP0

Python dependencies:
          pip: 22.3.1
   setuptools: 65.5.0
      sklearn: 1.2.0
       sktime: 0.15.0
  statsmodels: 0.13.5
        numpy: 1.23.5
        scipy: 1.10.0
       pandas: 1.3.5
   matplotlib: 3.5.3
       joblib: 1.1.1
        numba: 0.56.4
     pmdarima: 2.0.1
      tsfresh: 0.20.0

</details>

**Comment by fkiraly** [comment]
I can confirm the bug (python 3.10, windows).

a pull request with a fix would be much appreciated!
Re testing, here is how to run the test suite for the estimator locally:
https://www.sktime.org/en/stable/developer_guide/add_estimators.html#how-to-test-interface-conformance

Although it should be noted that the tests already pass on `main` and did not detect this, so we may like to think about adding a test on dummy data that would cause the issue. This means the test coverage is probably too small here.

Separately, a `pytest` based test for the fix would be appreciated, which we then could turn later into a data scenario or an extra test for all classifiers.
(if you are interested, the general framework is described here:
https://www.sktime.org/en/stable/developer_guide/testing_framework.html
and the data scenarios are in `utils._testing.scenarios_classification`, maybe it suffices to change column names in one scenario)

**Comment by erjieyong** [comment]
Noted. I will submit a pull request first to make the change for the bug and will write the test subsequently.

**Comment by erjieyong** [comment]
Got it. Let me try and do up both the fix as well as the test. First time doing it and thanks for your help!
