### ISSUE TITLE
[DOC] Broken link in glossary - user_guide_forecasting

### ISSUE THREAD

**Issue by romanlutz** [sktime/sktime#4117]
#### Describe the issue linked to the documentation

The glossary refers to `user_guide_forecasting` which is meant to be a reference to somewhere, but that particular link wasn't generated since the term `user_guide_forecasting` doesn't exist elsewhere. I suspect it existed at some point, but was removed later on.

![image](https://user-images.githubusercontent.com/10245648/212937979-d03c6fbe-0b5e-4c0a-ba8d-4a201ace3825.png)

#### Suggest a potential alternative/fix

Update the destination location to include that tag, or update the link to point at the destination.

[note: If you comment with the destination I'm happy to submit a PR myself]

**Comment by fkiraly** [comment]
> note: If you comment with the destination I'm happy to submit a PR myself

Thanks!

I think it should go to `docs/source/user_guide.rst`, or to the forecasting user guide linked from there.

I've just also noticed an orphaned, very old version of the user guide in `docs/source/user_guide/introduction.rst` which I think isn't linked from anywhere anymore (or should be, because we have all those tutorials?)

Also, it's an honour to get a PR by such a prominent open source contributor 😁 

[fairlearn](https://github.com/fairlearn/fairlearn) is great!

May I interest you in this [nice package for `sklearn` compoatible base classes, systematic testing, tagging, composition and look-up](https://github.com/sktime/skbase) ?

**Comment by romanlutz** [comment]
Thanks for the warm welcome, @fkiraly ! 🙂 
I created #4125 for now. Feel free to suggest changes.

`skbase` looks interesting. While I don't want to go off-topic on this issue... any particular reason why `skbase` lives under `sktime` rather than `scikit-learn` since it seems to be generic?

**Comment by fkiraly** [comment]
> any particular reason why `skbase` lives under `sktime` rather than `scikit-learn` since it seems to be generic?

ok, going off-topic here a little...

reason is very simple and historic - `skbase` grew out of `sktime` as the module implementing `scikit-learn` compatibility, slowly turning into a model encapsulating `scikit-learn` generics and new ideas (like a streamlined tag system or fitted parameter interface). It's also developed by `sktime` developers primarily. Ultimately, it could make sense as a joint base for `scikit-learn`itself, but that would of course need to follow discussions with `scikit-learn` developers.

Currently we are still in a phase where we are testing how easy it is to base `sktime` on `skbase`, or to carry out a rebasing refactor.

**Comment by romanlutz** [comment]
> Ultimately, it could make sense as a joint base for `scikit-learn`itself, but that would of course need to follow discussions with `scikit-learn` developers.

Makes sense! The scikit-learn folks I've interacted with are really nice and reasonable. They might be open to this sort of effort. If you ever want to check with them you can probably just open an issue with them and if it seems worth discussing further they have a repo with scikit-learn enhancement proposals (SLEPs). Anyway, I'll have to look at this in more detail to see if it could be used for some of the things I work on...
