### ISSUE TITLE
[DOC] table of contents formatting is broken

### ISSUE THREAD

**Issue by romanlutz** [sktime/sktime#4118]
#### Describe the issue linked to the documentation

The TOC on https://www.sktime.org/en/stable/examples/01_forecasting.html shows the following:

![image](https://user-images.githubusercontent.com/10245648/212939206-172504e4-edc9-444b-b34b-2ace02d5519c.png)

I suspect this should have been `fit` followed by a link to another section (?)

#### Suggest a potential alternative/fix

That depends mostly on the intended output (see my question above).

**Comment by fkiraly** [comment]
well, that's weird, it doesn't look like that to me in VS code.

![image](https://user-images.githubusercontent.com/7985502/212988437-7a2127c3-a3a4-4668-b5aa-d8f7d590d2cf.png)

but I can also see this in readthedocs.

I suspect the quote from `fit` is interacting somehow with the rendering, specifically in readthedocs.

removing the quotes may hence fix it?
