### ISSUE TITLE
[ENH] `GridSearchCV` for time series classification

### ISSUE THREAD

**Issue by fkiraly** [sktime/sktime#4129]
There are some good reasons to write an `sktime` native grid search for time series classification (and regression):

* discussion in https://github.com/sktime/sktime/issues/4128 which highlights that classifiers not compatible with `pickle` persistence cannot be combined with `sklearn` grid search (but the `sktime` serialization interface could replace this)
* input/output checks would wokr properly, and more mtypes such as `pd-multiindex` would become compatible with the grid search
* this would provide a basis for scaling and distributed computing, e.g., via `dask`, see https://github.com/sktime/sktime/issues/4013

Opening this for design discussion.

Of course, `sklearn` `GridSearchCV` would remain compatible with `sktime` when used with `sklearn` compatible mtypes and estimators that are persistence compatible with `sklearn` contracts.

**Comment by achieveordie** [comment]
It seems like a good feature to add and I've been meaning to take on a medium-sized issue. This seems like a task for me. I'll add an informal design proposal in the upcoming days followed by a STEP after our initial discussion concludes.
