### ISSUE TITLE
[BUG] `PolynomialTrendForecaster` stalls when fit on timeseries with datetime index

### ISSUE THREAD

**Issue by KishManani** [sktime/sktime#4131]
**Describe the bug**
My computer stalls when running `fit` on a dataframe with a `DatetimeIndex` with the `PolynomialTrendForecaster`.

**To Reproduce**
```python
from sktime.datasets import load_airline
from sktime.forecasting.trend import PolynomialTrendForecaster  

df = load_airline()
df.index = df.index.to_timestamp()

trafo = PolynomialTrendForecaster()
trafo.fit(df)
```

**Expected behavior**
The fitting time shouldn't be orders of magnitude different from using a `PeriodIndex`. 

**Versions**
<details>

System:
    python: 3.8.7 (default, May  6 2021, 21:53:45)  [Clang 12.0.0 (clang-1200.0.32.29)]
executable: /Users/kishan_manani/.pyenv/versions/3.8.7/envs/udemy-ts/bin/python3.8
   machine: macOS-11.6.6-x86_64-i386-64bit

Python dependencies:
          pip: 22.3.1
   setuptools: 49.2.1
      sklearn: 1.2.0
       sktime: 0.15.0
  statsmodels: 0.13.2
        numpy: 1.21.6
        scipy: 1.8.1
       pandas: 1.5.2
   matplotlib: 3.6.2
       joblib: 1.2.0
        numba: 0.56.4
     pmdarima: 1.8.5
      tsfresh: 0.19.0

</details>

**Comment by fkiraly** [comment]
```
Unable to allocate 2.74 TiB for an array with shape (376012800001,) and data type int64
```
???

This is certainly a bug.

**Comment by fkiraly** [comment]
Hope this fixes it: https://github.com/sktime/sktime/pull/4133
