### ISSUE TITLE
[DOC] `STLForecaster` docs not rendered correctly.

### ISSUE THREAD

**Issue by KishManani** [sktime/sktime#4148]
#### Describe the issue linked to the documentation
The documentation doesn't appear to have rendered correctly here: https://www.sktime.org/en/v0.15.1/api_reference/auto_generated/sktime.forecasting.trend.STLForecaster.html

<img width="710" alt="image" src="https://user-images.githubusercontent.com/30973056/214697850-8557fbfc-b58c-4d63-8414-cf8286469eb4.png">

**Comment by blazingbhavneek** [comment]
Hey! I wanna fix this! @KishManani  , please tell me what do you want to see fixed? ( I am new, I don't have eyes for it yet :)

**Comment by fkiraly** [comment]
Thanks, @blazingbhavneek!

I think:
* the content in the grey boxes should simply continue the previous line instead of being in grey boxes.
* the list points 1., 2., 3. should render aligned
