### ISSUE TITLE
[BUG] `ForecastingGridSearchCV` returns `AttributeError` `get_class_tag` on non-`BaseObject` input - docstring is wrong

### ISSUE THREAD

**Issue by albert-queralto** [sktime/sktime#4149]
@fkiraly update:

the underlying problem is two-fold:

* the docstring(s) are wrong for the `scoring` argument of tuners
* @albert-queralto passed a string instead of a function or class (but it is easy to get confused by the docstring, since it was wrong)

---
**Describe the bug**
I am using the make_pipeline method with the StandardScaler from sklearn, the NaiveForecaster with a dictionary of parameters and the `ForecastingGridSearchCV`. However, I am getting the following AttributeError: 'str' object has no attribute 'get_class_tag'.  The traceback seems to indicate that the issue is in the fit method.

**To Reproduce**

```python
import numpy as np
import pandas as pd

from sklearn.preprocessing import StandardScaler
from sktime.forecasting.compose import ForecastingPipeline
from sktime.transformations.series.adapt import TabularToSeriesAdaptor
from sktime.forecasting.model_selection import (ExpandingWindowSplitter,
                                                temporal_train_test_split,
                                                ForecastingGridSearchCV)
from sktime.pipeline import make_pipeline as sktime_make_pipeline
from sktime.forecasting.base import ForecastingHorizon
from sktime.forecasting.naive import NaiveForecaster
from sktime.forecasting.compose import TransformedTargetForecaster


start_date = '2022-01-01'
end_date = '2022-03-01'
date_rng = pd.date_range(start=start_date, end=end_date, freq='15T')
df = pd.DataFrame(date_rng, columns=['date'])
df['temperature'] = np.random.randint(low=10, high=50, size=(len(date_rng)))
df['wind_speed'] = np.random.randint(low=0, high=50, size=(len(date_rng)))
df['pressure'] = np.random.randint(low=1000, high=1050, size=(len(date_rng)))
df.set_index('date', inplace=True)

models_dict = {
    'naive_forecaster': NaiveForecaster()
}

params_dict = {
                'naive_forecaster': {
                                    'NaiveForecaster__strategy': ['last', 'mean', 'drift'], 
                                    'NaiveForecaster__sp': [12, 24],
                                    'NaiveForecaster__window_length': [100],
                                }
                }

best_estimators = {}
best_cv_scores = {}
    
X = df.drop('temperature', axis=1)
Y = df['temperature']

Y_train, Y_test, X_train, X_test = temporal_train_test_split(X=X, y=Y, 
                                                            test_size=0.2)
for model_name, model in models_dict.items():
        pipeline = sktime_make_pipeline(TabularToSeriesAdaptor(StandardScaler()), model)
        grid_search = ForecastingGridSearchCV(pipeline, param_grid=params_dict[model_name],
                                    cv=5, scoring='neg_root_mean_squared_error', verbose=1)
        grid_search.fit( Y_train, X_train)

        print(f'{model_name} - Best parameters: {grid_search.best_params_}, Best score: {grid_search.best_score_}')
```

**Expected behavior**
The code should train the forecaster with the data and return the model parameters and score.

**Additional context**
GridSearchCV seems to work properly.

**Versions**
<details>

System:
    python: 3.9.15 (main, Nov 24 2022, 14:39:17) [MSC v.1916 64 bit (AMD64)]
executable: c:\Users\albert.queralto\Anaconda3\envs\datasci\python.exe
   machine: Windows-10-10.0.19045-SP0

Python dependencies:
          pip: 22.3.1
   setuptools: 65.6.3
      sklearn: 1.0.2
       sktime: 0.15.1
  statsmodels: 0.13.2
        numpy: 1.23.5
        scipy: 1.9.3
       pandas: 1.5.2
   matplotlib: 3.6.2
       joblib: 1.1.1
        numba: 0.56.4
     pmdarima: 2.0.2
      tsfresh: 0.20.0

</details>

**Comment by fkiraly** [comment]
Thanks for reporting!

Could you kindly add all the import, and creating of some dummy data (e.g., using `sktime.datasets` or a `pandas` constructor), so copy-paste of the code block into a notebook runs and generates the error?

That would help massively with debugging, thanks!

**Comment by albert-queralto** [comment]
Good morning,
I have updated the code generating a dummy dataset. I hope it helps!

Best wishes

**Comment by fkiraly** [comment]
Thanks a lot, @albert-queralto!

Just tried to put it into the debugger, but your code breaks in a part unrelated to `sktime`, could you please check?

It's the line + `X, Y = df.drop(target_var), df[target_var]`

**Comment by albert-queralto** [comment]
Hi @fkiraly,
now it should work. Thanks!

**Comment by fkiraly** [comment]
Ah, thanks!

I think I understand what's going on: `scoring` must be a class inheriting from `BaseMetric`, not a string.
This is unclear in the docstring (which is wrong), and it also seems it does not allow a function to be passed.

I'll fix the docstring and ensure that metric callables (like your negative RMSE) can be passed.

**Comment by fkiraly** [comment]
Addressed here: https://github.com/sktime/sktime/pull/4178

The nan issue is not addressed yet, I'll have to think about that.
I think removing nan in metrics and producing a warning would address it.

**Comment by albert-queralto** [comment]
> Ah, thanks!
> 
> I think I understand what's going on: `scoring` must be a class inheriting from `BaseMetric`, not a string, as per current code logic.
> This is unclear in the docstring (which is wrong), which claims it must be a function.
> However, thet logic does not allow a function to be passed.
> 
> I'll fix the docstring and ensure that metric callables (like your negative RMSE) can be passed.
> (a string still wouldn't work, you'll have to pass the function)

Hi@fkiraly ,
Thanks a lot, I will pass a function or a class inheriting from BaseMetric. 

Best regards.

**Comment by fkiraly** [comment]
Note: currently, on `main`, only metric classes from `sktime.performance_metrics` are supported, not functions - the docstring is wrong.
The PR fixes this so functions are also possible arguments, but this won't be in the package until the next release, 0.16.1 (or 0.17.0).
