### ISSUE TITLE
[BUG] `AutoETS`,  `UnobservedComponents`: `predict_quantiles` and `predict_intervals` does not work when index does not start at 0

### ISSUE THREAD

**Issue by ngupta23** [sktime/sktime#4173]
@fkiraly update: same bug occurs with `UnobservedComponents`, added to description

---

**Describe the bug**
AutoETS `predict_quantiles` and `predict_intervals` does not work with Int64Index when index does not start at 0

**To Reproduce**
```python
from sktime.forecasting.ets import AutoETS
from sktime.forecasting.arima import ARIMA

def check_forecasts(forecaster, data):
    forecaster.fit(data["y"], fh=[1, 2, 3])
    try:
        y_pred = forecaster.predict()
    except KeyError as e:
        print(f"Error with {forecaster.__class__()} predict(): {e}")
    try:
        y_pred = forecaster.predict_quantiles()
    except KeyError as e:
        print(f"Error with {forecaster.__class__()} predict_quantiles(): {e}")
    try:
        y_pred = forecaster.predict_interval()
    except KeyError as e:
        print(f"Error with {forecaster.__class__()} predict_interval(): {e}")


data = pd.DataFrame({"y": np.arange(100)})
data.index = list(data.index)  # Change RangeIndex to Int64Index
data.index = data.index + 1  # Make index start at 1 instead of 0
check_forecasts(AutoETS(), data)
check_forecasts(ARIMA(), data)

# You can use the M4 dataset for more valuation instead of the mock data above
# Indexing in this dataset starts at 1 instead of 0

!pip install datasetsforecast
from datasetsforecast.m4 import M4

Y_df, *_ = M4.load(".", "Weekly")

data = Y_df.query("unique_id == 'W1'")
data.set_index("ds", inplace=True)

check_forecasts(AutoETS(), data)
check_forecasts(ARIMA(), data)
```

```python-traceback
Error with AutoETS() predict_quantiles(): '[101] not in index'
Error with AutoETS() predict_interval(): '[101] not in index'
```

**Expected behavior**
Since `predict()` works correctly, I am assuming Int64Index is supported. Hence, I would expect `predict_quantiles()` and `predict_intervals()` to work in this case as well.

**Versions**
sktime == 0.15.0

**Comment by ltsaprounis** [comment]
In the closed PR for forecast simulations (#3462 ) I had some code that fixes this in sktime, was supposed to be temporary until it was fixed upstream in statsmodels:
https://github.com/ltsaprounis/sktime/blob/b54df6c2ad2c6472c73b7f8154c88a48d560cdc9/sktime/forecasting/base/adapters/_statsmodels.py#L153-L168

You can try adding this logic in these methods as well.

**Comment by fkiraly** [comment]
> In the closed PR for forecast simulations (https://github.com/sktime/sktime/pull/3462 ) I had some code that fixes this in sktime, was supposed to be temporary until it was fixed upstream in statsmodels:

I looked at it and it does not seem like there is any related code in #3462.
One would expect logic in the `predict_intervals` or `_predict_intervals` method or similar, I am unable to spot anything of the kind. The additions are restricted to the `simulate` methods only.

Pointers are appreciated if I just missed it.

**Comment by fkiraly** [comment]
Can confirm the problem on python 3.10, windows.

Here's shorter code that produces the error:

```python
from sktime.forecasting.ets import AutoETS
from sktime.datasets import load_airline

y = load_airline()
y = y.reset_index(drop=True)
y = y[12:]

f = AutoETS()
f.fit(y, fh=[1, 2, 3])
f.predict_interval()
```

**Comment by fkiraly** [comment]
Here's a fix: https://github.com/sktime/sktime/pull/4180
Hopefully none of the other estimators have the same problem (as it is now tested generally)

**Comment by fkiraly** [comment]
It would appear `SquaringResiduals` and `UnobservedComponents` have the same problem...

FYI @juanitorduz, @kcc-lion
