### ISSUE TITLE
[DOC] class and function references are rendering as plain text - ideas for improvement

### ISSUE THREAD

**Issue by romanlutz** [sktime/sktime#4189]
#### Describe the issue linked to the documentation

Example:
![image](https://user-images.githubusercontent.com/10245648/216436394-49d7f9ec-1266-48eb-965a-9ba11f8a5877.png)
from https://www.sktime.org/en/stable/examples/02_classification.html?highlight=nested%20dataframe#Datasets-and-Problem-Types

This looks kind of odd and doesn't do a good job of showing that `pandas` and `DataFrame` belong together.

#### Suggest a potential alternative/fix

Instead of `pandas` `DataFrame`, why not at least `pandas.DataFrame`?

Better yet, have you considered using something like [intersphinx](https://www.sphinx-doc.org/en/master/usage/extensions/intersphinx.html)? I'm happy to submit a PR to convert a few of these every time I read through a page, but wanted to hear from maintainers if there's a reason this hasn't been done yet.

**Comment by fkiraly** [comment]
I think you are completely right, in general - PR appreciated.
Intersphinx also sounds like a good idea, although I suspect most references would be to a few places in `pandas` and `numpy`, and a couple in `scikit-learn`.

Regarding the specific tutorial you are referencing, the classification one is a bit old and may need some restructuring, similar to the forecasting tutorial that got reworked in 2022.

I'd hope we can do that and then record a tutorial video (like with a number of other tutorials).

Either way, any feedback and contribution is much appreciated!

**Comment by fkiraly** [comment]
> but wanted to hear from maintainers if there's a reason this hasn't been done yet.

Limited time, and `sktime` being mostly a volunteer driven effort

**Comment by romanlutz** [comment]
That makes perfect sense, of course. Same as with most projects 🙂 I'll submit PRs for such changes when I see them then. I don't think I have time to add intersphinx support but as you said it's not necessarily a huge improvement.

**Comment by fkiraly** [comment]
thanks!
