### ISSUE TITLE
[ENH] kinematics feature transformer

### ISSUE THREAD

**Issue by fkiraly** [sktime/sktime#4256]
From Yuri Skylakhter on discord:

There should be a transformer that computes, for a 3D time series of location, kinematic features.
There are actually two transformers in here, one that is series-to-features:

* min/max velocity
* min/max acceleration
* max radial/turning angles

and one series-to-series:

* velocity
* acceleration
* turning angle

This might exist somewhere, but I'm not aware of a package.
It should not be too difficult to implement though, using smoothing or quadrature rules.

**Comment by fkiraly** [comment]
Thinking about it, I would say the transformer can assume that the trajectories that are input are already sufficiently smoothed - if not, it can be pipelined with the Kalman filter in `KalmanFilterTransformerPK` or `KalmanFilterTransformerFP`.

For a smooth trajectory - a 2D or 3D time series $x(t)$ - we can obtain velocity, acceleration as finite differences (or smoothed finite differences). Curvature and radius of curvature can be obtained from these, via known equations using determinants or cross product: https://en.wikipedia.org/wiki/Radius_of_curvature

Probably not too hard to implement, if we can assume the smoothing is already done and we work with finite differences only.

**Comment by fkiraly** [comment]
quick update: the first (to features min/max) can be obtained by pipelining the second with a `SummaryTransformer`, so we need to implement only the first.

**Comment by shlyakhter1** [comment]
> 

Velocity and acceleration should be calculated using timestamp (or constant time update interval if series is equidistant).
