### ISSUE TITLE
Sktime.org never connected

### ISSUE THREAD

**Issue by ZhaoyuanQiu** [sktime/sktime#4258]
I was trying to read some documents on www.sktime.org from my PC, but it kept telling me ERR_TUNNEL_CONNECTION_FAILED.
I also tried with safari or chrome on my phone, it failed either.

I checked my VPN or firewall but found nothing wrong, as I can access to any other web resources except sktime.org.
Is there an issue with your domain recently?

**Comment by fkiraly** [comment]
yes - the domain has been hijacked, see this issue: https://github.com/sktime/sktime/issues/4237

we've moved the docs to www.sktime.net, but google still indexes the sktime.org. This should be resolved over time, with .net showing up in search results.
