### ISSUE TITLE
[DOC]Column Concatenator Provides insufficient examples in documentation

### ISSUE THREAD

**Issue by JonathanBechtel** [sktime/sktime#4262]
#### Describe the issue linked to the documentation
The documentation for the column concatenator does not provide any code example about how to use it, and lacks a little bit of detail about how its transformations are made

There's no source code provided about how to use it.  Even though it's mechanism is simple, it still makes sense to include starter code for others to see if they're new to the library.  Being able to quickly observe how the dimensions of your data change going into and out of an operation is useful for people who are working with sktime for the first time.

#### Suggest a potential alternative/fix

I can add a simple example to the docstring demonstrating its use, as well as a bit more detail about the order series are concatenated in.

**Comment by fkiraly** [comment]
> I can add a simple example to the docstring demonstrating its use, as well as a bit more detail about the order series are concatenated in.

Excellent idea - this has come up frequently and is quite valuable to do, since volunteer contributors don't like to work on documentation. Much much appreciated!

I've opened an umbrella issue:
https://github.com/sktime/sktime/issues/4264

**Comment by fkiraly** [comment]
resolved by a generous soul in #4272
