### ISSUE TITLE
[ENH] prototype approaches for polymorphic graph pipeline - duck typing

### ISSUE THREAD

**Issue by fkiraly** [sktime/sktime#4281]
One of two prototype approaches to investigate for polymorphic graph pipelines: duck typing:

* same approach as `sklearn` `Pipeline` - switches on methods on demand, i.e., if estimator thinks it should have method
* use dispatcher to base class methods, with methods of pipeline having only `args`, `kwargs`

implement as prototype only for a linear pipeline, transformers plus one end element that can be transformer, forecaster, or classifier (`BaseTransformer`, `BaseForecaster`, `BaseClassifier`)

the current pipeline logic is in `make_pipeline`, works via dispatch on dunder

**Comment by benHeid** [comment]
I can work on it :)

**Comment by benHeid** [comment]
The graphical pipeline is implemented using ducktyping to enable polymorphism. So, we can close this issue.
