### ISSUE TITLE
[ENH] prototype approaches for polymorphic graph pipeline - polymorphic class

### ISSUE THREAD

**Issue by fkiraly** [sktime/sktime#4282]
One of two prototype approaches to investigate for polymorphic graph pipelines: polymorphic class

relying on https://github.com/sktime/sktime/pull/3108

implement as prototype only for a linear pipeline, transformers plus one end element that can be transformer, forecaster, or classifier (`BaseTransformer`, `BaseForecaster`, `BaseClassifier`)

the current pipeline logic is in `make_pipeline`, works via dispatch on dunder

**Comment by benHeid** [comment]
Close since graph pipeline is implemented
