### ISSUE TITLE
[BUG] TypeError when using the evaluate_by_index method of error/metric classes like MeanAbsolutePercentageError with hierarchical inputs

### ISSUE THREAD

**Issue by marrov** [sktime/sktime#4298]
**Describe the bug**
The `evaluate_by_index` method of classes such as `MeanAbsolutePercentageError` and other error metrics is not working to obtain granular/disaggregated by-time-index errors when using hierarchical data as it raises a `TypeError`.

**To Reproduce**
```python
import numpy as np
import pandas as pd

from sktime.forecasting.naive import NaiveForecaster
from sktime.forecasting.base import ForecastingHorizon
from sktime.forecasting.model_evaluation import evaluate
from sktime.forecasting.model_selection import ExpandingWindowSplitter
from sktime.performance_metrics.forecasting import MeanAbsolutePercentageError
from sktime.performance_metrics.forecasting._functions import _percentage_error
from sktime.utils._testing.hierarchical import _make_hierarchical

# Define the target variable
y = _make_hierarchical()

# Define the CV strategy and get the number of folds
cv = ExpandingWindowSplitter(initial_window=6, fh=ForecastingHorizon([1]), step_length=1)
n_folds = cv.get_n_splits(y.index.unique(level=-1))

# Run the evaluate function
results = evaluate(
    forecaster=NaiveForecaster(strategy="last"),
    y=y,
    cv=cv,
    return_data=True,
    scoring=[MeanAbsolutePercentageError()],
    error_score=np.nan,
)

# Extract each of y_test and y_pred for all folds into separate hierarchical/multiindex dataframes by concatenation
y_true = pd.concat([results.loc[fold, "y_test"] for fold in range(n_folds)]).sort_index()
y_pred = pd.concat([results.loc[fold, "y_pred"] for fold in range(n_folds)]).sort_index()

# Calculate the percentage error (PE) and absolute percentage error (APE) for each time-index
pe = _percentage_error(y_true=y_true, y_pred=y_pred)
ape = np.abs(_percentage_error(y_true=y_true, y_pred=y_pred))

# Attempt to calculate the "APE" with MeamAbsolutePercentageError class by time-step
mape = MeanAbsolutePercentageError()
mape.evaluate_by_index(y_true=y_true, y_pred=y_pred)
```

**Expected behavior**
Using the `mape.evaluate_by_index` I would expect to obtain the same results as is stored in the `ape` variable, in my previous example. 

**Additional context**
I believe the culprit may be in the type checking. Particularly, the TypeError raised prints: 
```
TypeError: {'pd.DataFrame': "y_true must be a pandas.DataFrame, found <class 'sktime.datatypes._vectorize.VectorizedDF'>", 'pd.Series': "y_true must be a pandas.Series, found <class 'sktime.datatypes._vectorize.VectorizedDF'>", 'np.ndarray': "y_true must be a numpy.ndarray, found <class 'sktime.datatypes._vectorize.VectorizedDF'>", 'xr.DataArray': "y_true must be a xarray.DataArray, found <class 'sktime.datatypes._vectorize.VectorizedDF'>", 'dask_series': "y_true must be a dask DataFrame, found <class 'sktime.datatypes._vectorize.VectorizedDF'>", 'df-list': "y_true must be list of pd.DataFrame, found <class 'sktime.datatypes._vectorize.VectorizedDF'>", 'numpy3D': "y_true must be a numpy.ndarray, found <class 'sktime.datatypes._vectorize.VectorizedDF'>", 'pd-multiindex': "y_true must be a pd.DataFrame, found <class 'sktime.datatypes._vectorize.VectorizedDF'>", 'nested_univ': "y_true must be a pd.DataFrame, found <class 'sktime.datatypes._vectorize.VectorizedDF'>", 'dask_panel': "y_true must be a dask DataFrame, found <class 'sktime.datatypes._vectorize.VectorizedDF'>", 'pd_multiindex_hier': "y_true must be a pd.DataFrame, found <class 'sktime.datatypes._vectorize.VectorizedDF'>", 'dask_hierarchical': "y_true must be a dask DataFrame, found <class 'sktime.datatypes._vectorize.VectorizedDF'>"}
```
In particular, I believe the type `<class 'sktime.datatypes._vectorize.VectorizedDF'>` should be interpreted as `pd.DataFrame` for the purposes of the `pd-multiindex` type. Nevertheless, my understanding of `mtypes`and `scitypes` in `sktime` is not great and I may be mistaken here.

**Versions**
<details>
System:
    python: 3.8.10 (default, Nov 14 2022, 12:59:47)  [GCC 9.4.0]
executable: /local_disk0/.ephemeral_nfs/envs/pythonEnv-8008d4a2-4273-4edf-98e4-2bbf794381ad/bin/python
   machine: Linux-5.4.0-1100-azure-x86_64-with-glibc2.29

Python dependencies:
          pip: 21.0.1
   setuptools: 52.0.0
      sklearn: 0.24.1
       sktime: 0.16.1
  statsmodels: 0.13.5
        numpy: 1.22.4
        scipy: 1.10.1
       pandas: 1.5.3
   matplotlib: 3.4.2
       joblib: 1.0.1
        numba: 0.56.4
     pmdarima: 2.0.2
      tsfresh: 0.20.0
</details>

**Comment by fkiraly** [comment]
Yes, this is a bug, I can reproduce it on py 3.10, windows.

The issue has its source as you say:

* the function `evaluate_by_index` does not expect `VectorizedDF` as input
* yet this happens if two conditions are met: (a) it is called from `evaluate`'s default implementation, and (b) vectorization is needed in a case where the metric does not implement its own logic.

This should be an easy fix, along the lines you suggest.

However, there is a bigger issue at hand, which is more of an enhancement piece for the roadmap:
the way we enabled hierarchical data for metrics was via the boilerplate layer in the base class, and especially `evaluate_by_index` tries to invert the mean which can be inefficient.

What we should do is, for all metrics, implement efficient versions of `evaluate_by_index` (in the underscore method).
The reason this isn't there is "`scikit-learn` didn't do it" when we designed the metrics, i.e., the sklearn metrics only compute a mean over indices, but not the individual loss/metric sample per index.

I'll open a new issue on the enhancement.

**Comment by fkiraly** [comment]
Issues here on the "bigger issue" (unrelated to thet bug):

* documentation/docstring https://github.com/sktime/sktime/issues/4303
* `_evaluate_by_index` https://github.com/sktime/sktime/issues/4304

**Comment by fkiraly** [comment]
Much simpler way to provoke the error, this should probably be used as a test:

```python
from sktime.performance_metrics.forecasting import MeanAbsolutePercentageError
from sktime.utils._testing.hierarchical import _make_hierarchical

y = _make_hierarchical()
m = MeanAbsolutePercentageError()
m.evaluate_by_index(y, y)
```
