### ISSUE TITLE
[MNT] Forgotten deprecation in `_cboss` module

### ISSUE THREAD

**Issue by SamiAlavi** [sktime/sktime#4313]
https://github.com/sktime/sktime/blob/d85102ffd10f6531316015a1ac6c80c0b1687801/sktime/classification/dictionary_based/_cboss.py#L66-L73

https://github.com/sktime/sktime/blob/d85102ffd10f6531316015a1ac6c80c0b1687801/sktime/classification/dictionary_based/_cboss.py#L221-L225

**Comment by fkiraly** [comment]
thanks for flagging, this should be actioned for the next release.
