### ISSUE TITLE
[DOC] unclear documentation of `sktime` input type for transformers

### ISSUE THREAD

**Issue by IKetchup** [sktime/sktime#4325]
I have a dataset of 1000 time series in input and output. My input time series have the shape : 644 * 36 and my output time series have the shape 644*1008.

To resume my training data look like this : 

```
x_train shape : (800, 644, 36)
x_test shape  : (200, 644, 36)
y_train shape : (800, 644, 1008)
y_test shape  : (200, 644, 1008)
```

Because classical machine learning only take 2d data I ca also transformed then by concatening the first and second dimensions : 

```
x_train shape : (515200, 36)
x_test shape  : (128800, 36)
y_train shape : (515200, 1008)
y_test shape  : (128800, 1008)
```

I realised that there is not a lot of exemple in sktime on how to use extrenal data and how to load them into a sktime dataset.

I tried using my data as it is with a `MiniRocketMultivariate` transformation model. However the `transform` function does not return the same number of row as the original data but I guess it is beacause I do not have the right format.

```
print(X.shape)  >> 64400 * 36 (batch of data)
model = MiniRocketMultivariate(num_kernels=100)
model.fit(X)
x_trf = model.transform(X)
print(x_trf.shape) >> 1 * 84
```

How can transform my data (3d or 2d format) into a sktime dataset than can be used for regression with the `MiniRocketMultivariate` transformation model ?

**Comment by fkiraly** [comment]
The quick answer is, you should leave your data in the original 3D format, or, more precisely, ensure it is in 3D of shape (n_instance, n_variables, n_timepoints), so you may want to switch dimension 1 and 2 (if 644 is the number of time points).

`sktime` will understand that the three dimensions are instances, variables, time points.

I think the classificaiton or transformer tutorial could be clearer about this, apologies.

**Comment by fkiraly** [comment]
I think the main problem here is that the docstrings for transformers are unclear, especially when it comes to `numpy` based types.

A 2D numpy array is interpreted as a single time series by transformers (time points, variables), I've updated the method docstrings of all transformers to be really clear about this: https://github.com/sktime/sktime/pull/4328

Hope this helps?

**Comment by IKetchup** [comment]
Thanks for the quick reply.

I found a solution using your hint that seem to work to use X_transformed in a model like regression or a classifier after: 

- Reshape X to `(n_instances, n_features, n_timestep)`
- Flatten Y to `(n_instances, n_timestep * n_feature) `
