### ISSUE TITLE
[DOC] Incorrect `TimeSeriesKMean` default parameter.

### ISSUE THREAD

**Issue by marcosousapoza** [sktime/sktime#4345]
The documentation says that `TimeSeriesKMeans` defaults to `random`. However, in the actual code, it defaults to `forgy`.
Here is the incorrect line: https://github.com/sktime/sktime/blob/main/sktime/clustering/k_means.py#L23

**Comment by fkiraly** [comment]
thanks for the report! bugfix is appreciated, if you would like to make a PR.

I think we want to fix the *documentation* not the *code*, in order to not break or change potential behaviour in deployment.
