### ISSUE TITLE
[ENH] pass `statsmodels` `fit_params` to constructor

### ISSUE THREAD

**Issue by fkiraly** [sktime/sktime#4377]
From discord, indirect request by ckwan48.

The `SARIMAX` model interfacing `statmodels` does not allow to specify the parameters that `statsmodels` would receive in `fit`. These should be specified in the `sktime` constructor.
Good first issue as a recipe is available, here:
(similar to #2344)

---

Recipe for interfacing models with `fit_params` or any other `fit` args, in sktime:

* pass the parameter(s) to the constructor (the `__init__` method), using explicit parameter names and default, not `**kwargs`
* write it to `self` in the constructor
* in `_fit`, read it from `self` and pass it to the wrapped model's `fit` method
* ensure docstring is complete and defaults documented (optimally same as in wrapped estimator)

This allows to expose all parameter choices via the scikit-learn compatible interface (which relies on the constructor to expose all parameter choices).

For an example of this, you can look at `smoothing_level` in `ExponentialSmoothing`.

**Comment by AishwaryaSatpute1** [comment]
I would Like to work on this issue , will you please assign this issue to me ?

**Comment by fkiraly** [comment]
Sure, it's all yours!

**Comment by fkiraly** [comment]
@AishwaryaSatpute1, are you still working on this?
If so, as @yarnabrina noted here https://github.com/sktime/sktime/pull/4439#issue-1656568085, it might make sense to add `simple_differencing` in the same PR.

**Comment by yarnabrina** [comment]
Noting the list of available `fit` parameters for easy reference in future.

https://www.statsmodels.org/dev/generated/statsmodels.tsa.statespace.sarimax.SARIMAX.fit.html#statsmodels.tsa.statespace.sarimax.SARIMAX.fit-parameters
