### ISSUE TITLE
[ENH] simplify type annotations for float

### ISSUE THREAD

**Issue by SamiAlavi** [sktime/sktime#4379]
As per [PEP 484](https://peps.python.org/pep-0484/#the-numeric-tower), the type annotations do not have to say `Union[int | float]`, just a float is OK.

**Comment by fkiraly** [comment]
good point!

**Comment by abhisek7154** [comment]
@fkiraly @SamiAlavi Hey what should i need to do to solve this issue

**Comment by SamiAlavi** [comment]
Hi @abhisek7154, 

1. Read this [PEP 484](https://peps.python.org/pep-0484/#the-numeric-tower) to know what has to be changed and the reason for the change.
2. Remove the `int` type from all `Union[int | float]` or `int | float` types.

**Comment by abhisek7154** [comment]
abhisek7154:patch-1 i have made the changes

**Comment by abhisek7154** [comment]
Done. You can see it on my repositories. It is my first contribution

**Comment by SamiAlavi** [comment]
1. Fork this repository
2. Create a branch
3. Commit and push your changes
4. Create a pull request

**Comment by abhisek7154** [comment]
sorry my pull request got closed..i'm confused what to do , then i asked @AlexWaygood what will i have to do to make it right
then he replayed me with this...
Your first two changes concern constrained TypeVars. For a constrained TypeVar, e.g. T = TypeVar("T", int, float), the type checker is only allowed to solve the TypeVar as being "exactly int" or "exactly float". It is not allowed to solve the TypeVar as being an arbitrary subtype of int or an arbitrary subtype of float. Therefore T = TypeVar('T', int, float, complex) means something very different to T = TypeVar('T', float, complex), and something very different again to T = TypeVar('T', bound=complex), despite the fact that type checkers consider int to be an implicit subtype of float, and float to be an implicit subtype of complex, in many situations.

Your second change is incorrect, as Generator takes three type parameters, not two. I'm not sure why you thought a change was needed in this instance.

Now i'm more confused

**Comment by AlexWaygood** [comment]
(Also FYI @SamiAlavi, PEP 484 only specifies that type checkers should see int as a subtype of float for _parameter_ annotations — int is not necessarily understood universally to be a subtype of float by type checkers — just something to be aware of, as it's caught me out in the past as well. See e.g. https://github.com/python/mypy/issues/14030.)

**Comment by fkiraly** [comment]
Apologies for the confusion, @abhisek7154, we should have been more specific.

A tutorial on how to contribute to `sktime` via git workflows is here:
https://www.sktime.net/en/latest/developer_guide/git_workflow.html

This issue is about replacing the union annotations in parameter within `sktime` by float annotations, so you would make a PR to `sktime` following the worfklow in the guide.

Thanks for your contribution!

**Comment by abhisek7154** [comment]
Dear @fkiraly @SamiAlavi 
I would like to sincerely apologize for hanging in with you during our previous interaction. It was not my intention to cause any inconvenience or frustration on your end, and I'm sorry if my behavior did not meet your expectations.

**Comment by fkiraly** [comment]
@abhisek7154, no need to apologize! You did not cause any frustration!

Don't worry, we all got started with open source at some point and it is normal to not get everything perfectly right at the start.

Let us know if you need any help with this!
Also feel free to drop in to any one of the community collaboration sessions if you'd like help getting set up or for a screenshare of a partial contribution.
