### ISSUE TITLE
[BUG] `ForecastX` does not pass parameters to proba prediction methods

### ISSUE THREAD

**Issue by fkiraly** [sktime/sktime#4386]
`ForecastX` does not pass parameter to proba prediction methods of the inner forecaster.

It should also be checked why the tests did not capture this, as this results in the wrong column index (and I thought the column index is being checked for being as expected).

An instance of the problem was reported by @yarnabrina here:
https://github.com/sktime/sktime/discussions/4378#discussioncomment-5400582

**Comment by fkiraly** [comment]
@yarnabrina, since the discussion https://github.com/sktime/sktime/discussions/4378 also contains the diagnosis and solution for the bugfix, feel free to add yourself with a bugfixing tag to `allcontributorsrc`.

You can also make a PR to fix the bug it you like, in case you get to it in the next days.

**Comment by yarnabrina** [comment]
@fkiraly, please take a look at the PR #4391. I could not run `pytest`, as it always seems to get stuck on WSL 2 with `TensorRT` and `packaging` related warnings. If you have some suggestions for the same, I can attempt to update the tests.

**Comment by fkiraly** [comment]
Great, thanks!

Not sure what's going on with WSL here...

You could try an environment that does not contain `tensorflow` if your local environment is erroring out with that.

For the tests, your eyes would be appreciated, they should have caught this but apparently don't.

The relevant tests are:

* `test_predict_interval` in `forecasting.tests.test_all_forecasters`
* `test_predict_quantiles` in `forecasting.tests.test_all_forecasters`

On how to read these tests, the class populates the args with estimator instances `estimator_instances` and other scenario parameters.

More details here if you are interested:
https://www.sktime.net/en/latest/developer_guide/testing_framework.html
- but I hope it is self-explanatory enough. You can run the tests by calling `check_estimator` on any forecaster, and you can subset to specific test names by using the `tests_to_run` arg of `check_estimator`..

**Comment by fkiraly** [comment]
Just looking at it, the docstrings are incomplete and/or wrong, e.g., `test_predict_quantiles` is missing some args in the test docstring.

Possibly some silly bug in there.

**Comment by fkiraly** [comment]
So, I looked into it, it turned out to be related to the probabilistic forecasting project I was working on here: https://github.com/sktime/sktime/pull/4290

With this PR, the bug should be covered: https://github.com/sktime/sktime/pull/4393
