### ISSUE TITLE
[BUG] forecasters do not correctly infer `freq` attribute of a specific series

### ISSUE THREAD

**Issue by fkiraly** [sktime/sktime#4405]
From discussion forum - verified bug as reported by @yarnabrina, confirmed under current main, python 3.10.
It seems the `freq` attribute does not get correctly inferred internally.

### Discussed in https://github.com/sktime/sktime/discussions/4403

<div type='discussions-op-text'>

<sup>Originally posted by **yarnabrina** March 28, 2023</sup>
Let's consider the following setup:

```python3
import numpy
import pandas

numpy.random.seed(seed=0)

past_data = pandas.DataFrame(
    {
        "time_identifier": pandas.to_datetime(
            [
                "2024-01-01",
                "2024-01-02",
                "2024-01-03",
                "2024-01-04",
                "2024-01-05",
                "2024-01-06",
                "2024-01-07",
                "2024-01-08",
            ],
            format="%Y-%m-%d",
        ),
        "series_data": numpy.random.random(size=8),
    }
)
past_data = past_data.set_index(["time_identifier"])
```

As far as I can tell, this is in one of the `sktime` compatible format. And, training a model works fine.

```python3
import sktime.forecasting.naive

model = sktime.forecasting.naive.NaiveForecaster()
model.fit(past_data)
```

But I am unable to use this for prediction neither with integer array, nor with timedelta index.

```python3
import sktime.forecasting.base

numeric_horizon = sktime.forecasting.base.ForecastingHorizon(values=[1, 2])
model.predict(fh=numeric_horizon)

future_dates = pandas.to_datetime(["2024-01-09", "2024-01-10"], format="%Y-%m-%d")
past_end_date = past_data.index.max()

timedelta_horizon = sktime.forecasting.base.ForecastingHorizon(values=future_dates - past_end_date)
model.predict(fh=timedelta_horizon)
```

Both attempts fail with the following error, and I'm not sure what value is `None`.

> TypeError: unsupported operand type(s) for *=: 'int' and 'NoneType'

So, I want to know how to use the (successfully) fitted model to predict in such cases.

---

NB: If I try a very similar case with multiple series in a long format, this works fine. Attaching that example below. So, I'm certain that I'm missing something very small but important stuff somewhere, and will really appreciate some guidance.

<details>
<summary>Complete Long Format Example</summary>

```python3
import numpy
import pandas

numpy.random.seed(seed=0)

past_dates = pandas.to_datetime(
            [
                "2024-01-01",
                "2024-01-02",
                "2024-01-03",
                "2024-01-04",
                "2024-01-05",
                "2024-01-06",
                "2024-01-07",
                "2024-01-08",
            ],
            format="%Y-%m-%d",
        )

past_x_data = pandas.DataFrame(
    {
        "series_identifier": "x",
        "time_identifier": past_dates,
        "series_data": numpy.random.random(size=8),
    }
)
past_y_data = pandas.DataFrame(
    {
        "series_identifier": "y",
        "time_identifier": past_dates,
        "series_data": numpy.random.random(size=8),
    }
)

past_data = pandas.concat([past_x_data, past_y_data], ignore_index=True)
past_data = past_data.set_index(["series_identifier", "time_identifier"])

import sktime.forecasting.naive

model = sktime.forecasting.naive.NaiveForecaster()
model.fit(past_data)

import sktime.forecasting.base

numeric_horizon = sktime.forecasting.base.ForecastingHorizon(values=[1, 2])
model.predict(fh=numeric_horizon)

future_dates = pandas.to_datetime(["2024-01-09", "2024-01-10"], format="%Y-%m-%d")
past_end_date = past_data.index.levels[1].max()

timedelta_horizon = sktime.forecasting.base.ForecastingHorizon(values=future_dates - past_end_date)
model.predict(fh=timedelta_horizon)
```

```pycon
>>> numeric_horizon = sktime.forecasting.base.ForecastingHorizon(values=[1, 2])
>>> model.predict(fh=numeric_horizon)
                                   series_data
series_identifier time_identifier             
x                 2024-01-09          0.891773
                  2024-01-10          0.891773
y                 2024-01-09          0.087129
                  2024-01-10          0.087129
>>> 
>>> timedelta_horizon = sktime.forecasting.base.ForecastingHorizon(values=future_dates - past_end_date)
>>> model.predict(fh=timedelta_horizon)
                                   series_data
series_identifier time_identifier             
x                 2024-01-09          0.891773
                  2024-01-10          0.891773
y                 2024-01-09          0.087129
                  2024-01-10          0.087129
```

</details></div>

**Comment by fkiraly** [comment]
The contract violation happens here:

after the `fit`, `model.cutoff` should have `freq="D"`, but has `None`.

**Comment by fkiraly** [comment]
question: is this a bug, or is this an uninformative error message problem?

That is, what *should* happen here, what would the user expect?

**Comment by yarnabrina** [comment]
> question: is this a bug, or is this an uninformative error message problem?
> 
> That is, what _should_ happen here, what would the user expect? Any opinions, @yarnabrina?

My (very biased) opinion is that it's not very intuitive that frequency inferred from past data is failing at prediction step, while training step, where that object is being passed, is working fine.

So, I, as a user, would expect either failure at training step, some warning at the least. And if I get none, I think my expectation is prediction should work.

**Comment by yarnabrina** [comment]
And this may not necessarily be a `sktime` bug. Since `pandas.infer_freq` allows returning `None` when it fails to detect so, it may need to be informed back to user to specify explicitly as a initial validation check sort of action.

**Comment by fkiraly** [comment]
would https://github.com/sktime/sktime/pull/4406 be a reasonable solution?
Coercion maybe better than check, but not sure about unintended consequences.

**Comment by yarnabrina** [comment]
Looked fine to me. Until I learnt this:

> Since `pandas.infer_freq` allows returning `None` when it fails to detect so

See this:

```pycon
>>>
>>> import pandas
>>>
>>> no_missing = pandas.infer_freq(
...     pandas.to_datetime(
...         [
...             "2024-01-01",
...             "2024-01-02",
...             "2024-01-03",
...             "2024-01-04",
...             "2024-01-05",
...             "2024-01-06",
...             "2024-01-07",
...             "2024-01-08",
...         ],
...         format="%Y-%m-%d",
...     )
... )
>>>
>>> missing = pandas.infer_freq(
...     pandas.to_datetime(
...         [
...             "2024-01-01",
...             "2024-01-02",
...             "2024-01-03",
...             "2024-01-04",
...             "2024-01-05",
...             # "2024-01-06",
...             "2024-01-07",
...             "2024-01-08",
...         ],
...         format="%Y-%m-%d",
...     )
... )
>>>
>>> assert no_missing == "D"
>>> assert missing is None
>>>
```

A single missing value led to `None`, so I think some more informative message/warning/error (along with inference attempt) may be a better way. I'm not sure about "right" way to handle this, so will refrain from making a comment, but will share two snippets I found from `prophet` and `Kats`:

https://github.com/facebook/prophet/blob/514a5a29b4d8878f8873ab57dd6be32ee8ec4a47/python/prophet/forecaster.py#L1796-L1801

https://github.com/facebookresearch/Kats/blob/992b95e1a8c34402756ffea2376189568de85a2c/kats/consts.py#L889-L911

**Comment by fkiraly** [comment]
Thanks - interesting things to note:

* the `diff` strategy (in `kats`) looks nice but it is a can of worms. We - or, more precisely, @danbartl through meticulous research - found out that taking `diff` in checking was causing a lot of computational overhead, and we removed it. If we do this regularly, then it will slow down things for the "normal" case!
* sad to see that `kats` looks mostly dead (or more precisely, undead maintenance mode)? Last release 1 year ago? I suppose it is not unexpected with all that is going on with Facebook/Meta (no comment). We did contact them to collaborate, but they wanted "their own thing". Happens too often, possessiveness getting in the way of the greater good...
* the `prophet` snippet is basically the same as #4406, except it just uses the tail. Would be worth a consideration.

From a general perspective, I think the somewhat unsatisfactory trade-off is a costly informative error message vs "heuristics" that can go wrong, vs clean interface conditions. In `sktime`, we usually go with the clean interface and architecture and let the other things follow, but we don't always need to make that decision.

**Comment by fkiraly** [comment]
side note, `pandas.Index` also has all kinds of utility methods, but the can of works there is whether they are precomputed, or whether they are queried each time you ask for them. Depending on what it is, it could/should be used or we may like to avoid using them.

I remember some learnings from PR of @danbartl and @hoesler, but I no longer concretely remember the attributes you can use and the ones you shouldn't. (maybe they have some tipps if reading this)

**Comment by fkiraly** [comment]
Based on the above discussion, I'll just go with the simple fix and not involve any `diff` for now.
We can of course always re-open the discussion, in general the topics around the `freq` are usually a can of worms and not too easy design-wise (especially UX).
