### ISSUE TITLE
[DOC] Version specific docs on readthedocs are not working - "not found"

### ISSUE THREAD

**Issue by jernsting** [sktime/sktime#4407]
Version specific links in the documentation do not work. For example the link to the documentation for v0.16.1 does not work: https://sktime.readthedocs.io/en/v0.16.1/

_Originally posted by @jernsting in https://github.com/sktime/sktime/discussions/4387#discussioncomment-5459132_

**Comment by fkiraly** [comment]
let me split this in two issues

**Comment by fkiraly** [comment]
Thanks for reporting @jernsting, I did not notice that the version specific links were not working.

I do not understand why the links to versions are not working - this all looks like it should be up and it should work.
This also used to work before a recent security incident.

The most likely reason I can imagine is the recent episode where some developers forking off the project destroyed the documentation on readthedocs:
https://github.com/sktime/sktime/issues/4203

Readthedocs support eventually recovered the account for us, but they mentioned that the project ended up in a state full of garbage, as there was an incomplete delete (not exactly remembering the technical terms).

I will contact readthedocs support as it seems like a plausible guess.

**Comment by fkiraly** [comment]
(on the more general issue of asset security, here's a thread, if you have any feedback on how to keep accts like readthedocs safe: https://github.com/sktime/sktime/issues/3836)
