### ISSUE TITLE
[ENH] design issue - `pandas 2` upgrade and deprecation

### ISSUE THREAD

**Issue by fkiraly** [sktime/sktime#4441]
Design/planning issue for `pandas 2` compatibility.
At the likely end state, `sktime` should be able to support both the current range of `pandas 1` versions as well as `pandas 2`.

However, due to some subtle but substantial differences between the `pandas` versions, code built on `pandas 1` dependent `sktime` may break. Further, custom estimators in private `sktime` compatible extensions, written and tested under `pandas 1` `sktime`, may no longer be compatible with a `pandas 2` ecosystem, similar to the many estimators in `sktime` proper which broke due to the upgrade.

This issue is for discussing pros/cons of different upgrade and deprecation policies, after `pandas 2` compatibility of the framework code is ensured.
Options I can see:

1. "fast & risky" - just loosen the `pandas` bound to allow `pandas 2`, keep testing under `pandas 1` and `pandas 2`.
2. "fast & safe(r)" - release the `pandas 2` compatibility patches asap, but keep the `<2.0.0` bound for (2a) half a minor version cycle or (2b) a full minor version cycle. Tell users they can test `pandas 2` by force-installing it, and that `sktime` should be compatible. After the cycle, loosen the `pandas` bound to allow `pandas 2`.
3. "slowest & safest" - release the `pandas 2` compatibility patches only with 0.18.0, and announce the loosening of the bound for 0.19.0. Until 0.18.0, upgrades are tested via using the patch branch; between 0.18.0 and 0.19.0, by force-install of `pandas 2`.
4. "even slower & safer" - any of the above, with longer deprecation/change timelines

**Comment by fkiraly** [comment]
questions:

* would be great if anyone depending on `sktime` could state preferences
* are there any other options that make sense?

**Comment by ngupta23** [comment]
> However, due to some subtle but substantial differences between the pandas versions, code built on pandas 1 dependent sktime may break.

@fkiraly - It is not clear to me what is breaking. Can you provide more details?

Also, with all these options, when you say "loosen" or "loosening" are you implying that both pandas 1.x and 2.x will be supported after these options are implemented? If so, are you saying that after these option(s) are implemented, the algorithms will be robust with both versions of pandas? 

In general, I feel that dependent users that rely on `sktime` may take a while to update their environments to pandas 2.x (since their environments may have many other dependencies that may not work with pandas 2.x), hence 1.x support should be continued for the foreseeable future.

Thanks!

**Comment by marrov** [comment]
I agree with @ngupta23 there. Maybe enable early adopters to force install `pandas 2` with testing in mind but I think stability (i.e. `pandas 1`) should be the default, at least for some time.

**Comment by fkiraly** [comment]
> but I think stability (i.e. `pandas 1`) should be the default, at least for some time. 

@marrov, I see - that would rule out option 1.

**Comment by fkiraly** [comment]
FYI @ngupta23, @marrov, draft release PR with changelog here:
https://github.com/sktime/sktime/pull/4448

This is option 2b, with hopefully clear instructions on how to upgrade to ``pandas 2`` or how to keep using ``pandas 1``.

**Comment by fkiraly** [comment]
2b announced with 0.17.1
