### ISSUE TITLE
[ENH] refactoring of `_predict_interval` inheritance in descendants of `_StatsModelsAdapter`

### ISSUE THREAD

**Issue by fkiraly** [sktime/sktime#4447]
_Originally posted by @yarnabrina in https://github.com/sktime/sktime/issues/4301#issuecomment-1500896007_

@fkiraly I am planning to work on the refactoring of `_predict_interval` over the next week. This is my idea so far before starting:

1. add a `_predict_interval` to `_StatsModelsAdapter`
    1. similar to the common pattern in `ets`, `sarimax` and `structural`
    2. one extra abstract/non-implemented method to get quantile information from corresponding `PredictionResults` class, which seem to vary between above three
3. override that in subclasses:
    1. no override in classes for which `capability:pred_int` is `False`
    2. for estimators other than above the above three, override `_predict_interval` with current methods
    3. for above three estimators, implement the new method

Please let me know if it seems okay, or if you have some other suggestions.

I have few other doubts as well:

1. What can I expect at to be commit order to start with? Shall I start with `main`, or with #4439, or with #4427, or with both of these?
2. Is it safe to assume classes inheriting `_StatsModelsAdapter` are all the estimators in the scope of this refactoring? Or, can there be some others as well?
3. Are #4362 and #4363 related to this refactoring? Or they are indexing bugs in `_predict_interval`, but not affecting this?

**Comment by fkiraly** [comment]
@yarnabrina, thanks a lot for this, this would be much appreciated!
Indeed there is a lot of duplication and not-quite-duplication that a structured refactor would make the code much more robust!

I will comment below on the individual steps.

Regarding strategy, I agree with your proposed refactor plan, really excellent, thanks a lot for taking the time to work this out in detail!
Putting it side by side with the individual classes, it makes much sense to me precisely the way you outline.

**Comment by fkiraly** [comment]
> 1. add a `_predict_interval` to `_StatsModelsAdapter`

agreed. The main question would probably be, `_predict_interval` or `_predict_quantiles`, but choosing the former makes sense as it is the primary interface point in all classes.

> 1. similar to the common pattern in `ets`, `sarimax` and `structural`

agreed. These look like having the most commonalities.

> 2. one extra abstract/non-implemented method to get quantile information from corresponding `PredictionResults` class, which seem to vary between above three

Agreed. This is also more elegant than what I had in mind (a pointer attribute).

> 3. override that in subclasses:

yes, implied by the design.

>1. no override in classes for which `capability:pred_int` is `False`

This could cause a problem with the current tests.
There is one test which checks the value of the interval against whether a custom implementation of the probabilistic methods is available.

I do not know the exact statement (e.g., is it "if and only if" or just a one-way implication), but if it clashes one might have to think about what the tag should mean, and how to test for it. E.g., is it fine if you have a partial implementation but the tag turns it off, in order to enable a parent class with an optional implementation. (currently this might not be allowed, but perhaps it should be allowed)

> 2. for estimators other than above the above three, override `_predict_interval` with current methods

I have not checked whether any other estimator could be made to fit the inherited pattern, but I suppose you'd check that on a case-by-case basis.

> 3. for above three estimators, implement the new method

Yes, implied by the design. Agreed.

**Comment by fkiraly** [comment]
> 1. What can I expect at to be commit order to start with?

I would start with a merge of both #4427 and #4439.
I also hope we can release the `pandas 2` patch soon as it is substantial (review appreciated!) as its own release 0.17.1.

> 2. Is it safe to assume classes inheriting `_StatsModelsAdapter` are all the estimators in the scope of this refactoring? Or, can there be some others as well?

That's a good question. I would start with exactly the classes inheriting from `_StatsModelsAdapter` at first.

I am aware of other classes with a lot of intersection, these are `_StatsForecastAdapter` and `_PmdArimaAdapter`, but I would recommend not to start with these - my gut feeling says, it would cover too much ground in one step.

> 3. Are #4362 and #4363 related to this refactoring? Or they are indexing bugs in `_predict_interval`, but not affecting this?

Also an excellent question. #4362 is definitely related, as `DynamicFactor` inherits from `_StatsModelsAdapter`. Therefore, you might even be able to fix the bug "by inheritance", i.e., as a beneficial side effect of the refactor (although I can't say just from looking how immediate or orthogonal it would be).

On the other hand, #4363 seems unrelated as the code appears disconnected, it is connected to #4362 only indirectly as another estimator that fails the same contract, but for reasons that seem independent from `_StatsModelsAdapter` or any copy-paste around it.

**Comment by yarnabrina** [comment]
Hi, I need a guidance to create a PR.

I've [a branch](https://github.com/yarnabrina/sktime-fork/tree/refactor-statsmodels-predict-intervals) which (hopefully) solves the main issue. It basically does what I suggested in my comment. But it assumes the presence of #4439, and also that of #4452 for my convenience. I can ignore #4452, but #4439 is a must.

How do you suggest me to create the PR? If I create as it is, the commit history in main is going to be messed up, so need some inputs.

---

Other comment: I think one of the major difference between {`ets`, `sarimax`, `structural`} vs {`dynamic_factor`, `var`, `vecm`} is the tag `"scitype:y": "multivariate"`. Since the 2nd set of models are multivariate, the prediction simultaneously have all the required columns, while the first one probably call per column (I failed to find where this logic is written, and that same place is probably also causing `_fitted_forecaster` attribute behaviour difference). So, handling column names have to be significantly different in the two cases.

So, I wonder if it's possible to handle both sets in same function? One possibility (if models in 2nd set have methods, which does not seem to be the case) is to call `_predict_interval_univariate` and `_predict_interval_multivariate` and so on, but I don't know if that's the right way to do it.

Note: ignored other models inheriting from `_StatsModelsAdapter` as they don't support `_predict_interval` as of now.

**Comment by fkiraly** [comment]
> How do you suggest me to create the PR? If I create as it is, the commit history in main is going to be messed up, so need some inputs.

The way I do it is one of two ways:

* option 1, you *branch off*, say, #4439 in the first instance. Then potentially merge #4452 into the branch
* option 2, branch off `main`, and merge #4439 and then #4452 into it. If you do this, there should be no merge conflicts, if there are, the "dependent PR" pattern isn't satisfied

In either case, the PR description should say "depends on #4439 and #4452", to indicate that those must be merged first.

Regarding commit history, there is no messing up as all PR are squashed (into a single commit to `main`) when merged. The important thing is of course to merge them in the right sequence, which a "trusted committer" (`sktime` developer) will usually make sure of.

**Comment by fkiraly** [comment]
> So, I wonder if it's possible to handle both sets in same function? 

I see - what you propose could work, although in both cases you are dealing with `pd.Series` or `pd.DataFrame`, there might be a smart (but not easy to see) way to deal with both without dispatch.

**Comment by yarnabrina** [comment]
@fkiraly I created a draft PR considering the univariate estimators. I know it's going to fail for `Theta`, because it defines `_predict_quantiles` different from everything else which mess up the class hierarchies expected to be called in the new base method I added.

But while I think about how this should be handled for future estimators that use `_predict_quantiles` instead of `_predict_interval`, can you please take a look at the remaining PR for an initial review? Plus, the logic for `ThetaForecaster`'s `_predict_quantiles` really seems strange.

**Comment by fkiraly** [comment]
thanks, I'll have a look!

**Comment by yarnabrina** [comment]
> Can you specify why it looks strange to you

I am not familiar with the theory of `Theta` models actually, so generating interval predictions just by adding noise with point predictions seemed suspicious. From your points above, this seems to be in line with the theory, so I guess this is okay to do.

> what you would expect instead

`statsmodels` does have a method to generate prediction intervals. So, I was hoping that it'd use that, adding an example below. This would have helped me to have all estimators using intervals as base definition and not mix of interval and quantiles. Plus, it may be easier to maintain over long run as `sktime` will be just the framework.

```python3
import numpy
import pandas
from statsmodels.tsa.forecasting.theta import ThetaModel

dates = pandas.date_range(start="2024-01-01", end="2024-01-31", freq="1D")
values = numpy.random.random_sample(size=31)

sample_data = pandas.Series(values, index=dates)

model = ThetaModel(sample_data)
results = model.fit()

results.prediction_intervals(steps=7, alpha=0.1)
```

Just a related question, `statsforecast` have a [`AutoTheta`](https://nixtla.github.io/statsforecast/models.html#autotheta) model. Is there any interest in adding that in `sktime`?

**Comment by fkiraly** [comment]
> so generating interval predictions just by adding noise with point predictions seemed suspicious.

It looks like a homoskedastic i.i.d. noise process that is assumed, it is not an uncommon thing to do in general. Not sure whether this can be backed out of the paper(s) though, I did not check congruence there.
So, if you feel it is suspicious, we may want to have a second, more detailed look.

> `statsmodels` does have a method to generate prediction intervals.

Ok, now I'm getting confused - why are we not using that? Perhaps we should just use that then.

This was implemented 3 years ago, so might have some ancient bugs in it, or it might be that back then `statsmodels` did not have that functionality.

I would say, let's open an issue that we ought to replace the custom functionality with a direct interface.

It is also not clear from the docstring that this is meant to be an interface to `statsmodels`. If you compare with `ExponentialSmoothing`, it says clearly what it interfaces, `ThetaForecaster` should be similar.

> Just a related question, `statsforecast` have a [`AutoTheta`](https://nixtla.github.io/statsforecast/models.html#autotheta) model. Is there any interest in adding that in `sktime`?

Yes, sure!

For a while, nixtla were adding interfaces in `sktime` themselves, but then they stopped doing that.

I suppose it would be a common model that our users would like to use (and combine with the other composition patterns), so - absolutely! If you are happy with becoming the owner by default (as the implementer of the interface).

Should we open a `statsforecast` interface wishlist issue? Another thing that might be nice are the hierarchical forecast reconcilers (not exactly the same as the `sktime` native ones). More generally, there's no reason not to have multiple implementations of the same algorithm.

**Comment by yarnabrina** [comment]
I'll be very interested indeed in adding support for automatic forecasters in `statsforecast`. It'd take some good amount of time (in month(s)) though given the variety of models.

**Comment by fkiraly** [comment]
> I'll be very interested indeed in adding support for automatic forecasters in `statsforecast`. 

Ok - that would be nice!
The interfaces are not very consistent, so indeed it might be some work.

I would suggest, let's track this as a mini-project in an umbrella issue where we also plan.
I hope the extension template is useful and makes it easy to "fill in", have you seen the one for forecasting?

**Comment by yarnabrina** [comment]
I haven't so far, will start after #4465 is complete (even if not merged for due releases).

Let me know what all changes you'd want me add. These are the things we noted already, and lot of these are big scope works, so will try to complete the must-have's this week.

1. generalise `test_pred_int` (#4482)
2. replace custom `_predict_quantiles` for `ThetaForecaster` with `_predict_interval` interface to `statsmodels`
3. attempt generalisation of `_predict_interval` for proper multivariate estimators
4. attempt generalisation between univariate and multivariate estimators

I think 3rd one will be difficult, if possible, given as of now codes don't seem very similar. If this is done, 4th one would be doable.

If I missed something, let me know.

**Comment by fkiraly** [comment]
> Let me know what all changes you'd want me add. 

I'd consider these all as "optional", for the backlog, not as must have.

We should sit down at some point and prioritize on impact per time invested basis (can do this async too).

There, `statsforecast` and deep learning interfaces probably rank better, and there might be other things even further up.
