### ISSUE TITLE
[BUG] `'month_of_quarter'` feature in `DateTimeFeatures` not giving correct output

### ISSUE THREAD

**Issue by VyomkeshVyas** [sktime/sktime#4541]
**Describe the bug**

The 'month_of_quarter' feature of DateTimeFeatures() is not giving correct output. 

**To Reproduce**

```python
# importing functions
from sktime.datasets import load_PBS_dataset
from sktime.transformations.series.date import DateTimeFeatures

#Loading data
y = load_PBS_dataset()

# Defining date time feature
FEATURES = ['month_of_quarter']
dt_trafo = DateTimeFeatures( manual_selection=FEATURES)

dt_trafo.fit_transform(y)[:13]
```

**Expected behavior**

As the name suggest, 'month_of_quarter' should be the month number of quarter having value among [1, 2, 3].

**Additional context**

The output of the above code snippet should look something like below :-
<html>
<body>

  | Number of scripts | month_of_quarter
-- | -- | --
'1991-07' | 1.0 | 1
'1991-08' | 1.0 | 2
'1991-09' | 1.0 | 3
'1991-10' | 0.0 | 1
'1991-11' | 0.0 | 2
'1991-12' | 1.0 | 3

</body>
</html>

**Versions**
<details>

System:
    python: 3.9.0 (default, Nov 15 2020, 08:30:55) [MSC v.1916 64 bit (AMD64)]
executable: [c:\Users\vyomkesh.vyas\Anaconda3\envs\effc\python.exe](file:///C:/Users/vyomkesh.vyas/Anaconda3/envs/effc/python.exe)
   machine: Windows-10-10.0.19041-SP0

Python dependencies:
          pip: 23.0.1
   setuptools: 65.6.3
      sklearn: 1.2.2
       sktime: 0.16.0
  statsmodels: 0.13.5
        numpy: 1.23.5
        scipy: 1.8.1
       pandas: 1.5.3
   matplotlib: 3.6.3
       joblib: 1.2.0
        numba: 0.56.4
     pmdarima: 2.0.3
      tsfresh: None
</details>

**Comment by fkiraly** [comment]
Bug confurmed also on 0.18.0, windows.

The output is this, which is odd.

```
Period
1991-07    2
1991-08    3
1991-09    3
1991-10    3
1991-11    3
1991-12    4
1992-01    1
1992-02    1
1992-03    1
1992-04    2
1992-05    2
1992-06    2
1992-07    2
Freq: M, dtype: int64
```

FYI @KishManani

**Comment by fkiraly** [comment]
it looks like the magic is broken, it happens in lines 292-302

```python
        quarter = date_sequence.quarter
        quarter_start = pd.DatetimeIndex(
            date_sequence.year.map(str)
            + "-"
            + (3 * quarter - 2).map(int).map(str)
            + "-01"
        )
        values = (
            (x["date_sequence"] - quarter_start) / pd.to_timedelta("1D") + 1
        ).astype(int)
        cd = values
```

**Comment by fkiraly** [comment]
fixed. Just changing the modulo magic a bit.

**Comment by fkiraly** [comment]
@danbartl, @Kishmanani, as you wrote the tests - why was this not detected? I haven't looked into the tests in detail.
(My name only shows in the blame by line as I indented them when isolating dependencies.)

**Comment by KishManani** [comment]
@fkiraly - I wrote the tests pertaining to ensuring the method works for panel data and computing `is_weekend`. Having looked at the tests [here](https://github.com/sktime/sktime/blob/3804876caa73ff92fdbbda1316648b687f3ffe25/sktime/transformations/series/tests/test_date.py#L200) I don't think there are explicit tests on the values computed from the transformer, just the column names.  So unless I've missed something, the short answer to your question is that the current tests don't actually test any of the logic of the transformers (i.e., the extraction of quarter of month, month of year, etc.).

**Comment by fkiraly** [comment]
I see - well, they probably should, or we get accidents like the above ... fully agreed to #4555. I made a start with `month_of_quarter` already :-)
