### ISSUE TITLE
[BUG] recent failure to install `tensorflow-probability` on `python 3.7`

### ISSUE THREAD

**Issue by fkiraly** [sktime/sktime#4566]
The recent update of `tensorflow-probability` (0.20.0) seems to causes an error at the installation stage, on `python 3.7`:

```
INTERNALERROR> ImportError: This version of TensorFlow Probability requires TensorFlow version >= 2.12; Detected an installation of version 2.11.0. Please upgrade TensorFlow to proceed.
```

FYI @yarnabrina as we hae discussed python 3.7 recently.

**Comment by fkiraly** [comment]
https://github.com/sktime/sktime/pull/4567 bounds `tensorflow-probability<0.20.0` - once python 3.7 EOL is reached, we can release the bound.

**Comment by yarnabrina** [comment]
Not sure if it exists already, but may be we can create a issue tracker of things to do after EOL? adding pins like this, may be running `pyupgrade --py38-plus`, etc.?

---

Also, I thought not pinning will download latest supported version for each package, and it's dependencies are changed accordingly. Didn't know it fails this way.

**Comment by fkiraly** [comment]
> Not sure if it exists already, but may be we can create a issue tracker of things to do after EOL?

No, it doesn't - great idea!

Do you want to open it? Could be an issue, or a milestone. Perhaps umbrella issue is easier to manage.

**Comment by yarnabrina** [comment]
Created #4569. Please take a look.

**Comment by fkiraly** [comment]
excellent, then we can close this and keep track of the todos there.
