### ISSUE TITLE
[MNT] umbrella issue: actions at python 3.7 EOL (June 2023)

### ISSUE THREAD

**Issue by yarnabrina** [sktime/sktime#4569]
Python 3.7 reaches end of life on 27th June, 2023. (Ref. https://endoflife.date/python)

This issue is to track actions to carry out at and after python 3.7 EOL.

* there are some changes in the codebase to support 3.7, and not necessary for later versions. After EOL is reached, the changes can be reverted.
* some changes are blocked by incompatibility with 3.7. These can be merged after 3.7 EOL

0. deprecation: announce moving away from python 3.7 support in next release, for 0.20.0; remove 3.7 in 0.20.0 https://github.com/sktime/sktime/pull/4717
1. pinned package versions (e.g. #4566)
   * revert https://github.com/sktime/sktime/pull/4567
2. PR blocked by 3.7 specific failures
   * https://github.com/sktime/sktime/pull/4463
4. updated type hints (e.g. `list` instead of `typing.List`, support of `Literal`/`TypedDict`, etc.)
5. new coding styles (e.g. assignment expressions with walrus operator, positional/keyword only parameters, etc.)

(Please update the list with more tasks as required.)

Note: a majority of update of coding styles can be done using [`pyupgrade`](https://github.com/asottile/pyupgrade), with flag `--py38-plus`.

**Comment by fkiraly** [comment]
@yarnabrina, I added #4463 to the list, and a clarification that the outstanding item from #4566 is the revert of #4567
