### ISSUE TITLE
[BUG] `get_fitted_params` fails on a tuned reconciler forecaster

### ISSUE THREAD

**Issue by fkiraly** [sktime/sktime#4574]
Reported by @daniel-torresc in https://github.com/sktime/sktime/discussions/4101.

A `get_fitted_params` call on a highly nested combination of reconciliation and tuning fails where it should work as per interface specification.

reproducible example, fails on 3.10, windows, 0.18.0 for me too:

```python
from sktime.utils._testing.hierarchical import _make_hierarchical
from sktime.forecasting.exp_smoothing import ExponentialSmoothing
from sktime.forecasting.trend import PolynomialTrendForecaster
from sktime.forecasting.model_selection import ForecastingGridSearchCV, ExpandingWindowSplitter
from sktime.transformations.hierarchical.aggregate import Aggregator
from sktime.forecasting.reconcile import ReconcilerForecaster
from sktime.forecasting.compose import TransformedTargetForecaster
from sktime.forecasting.compose import ForecastByLevel

y = _make_hierarchical()
agg = Aggregator()
y_agg = agg.fit_transform(y) 

param_grid = [{"forecaster": [ExponentialSmoothing()],
               "forecaster__trend": ['add','mul']
              },
              {"forecaster": [PolynomialTrendForecaster()],
               "forecaster__degree": [1,2]}
              ]

pipe = TransformedTargetForecaster(steps=[
    ("forecaster", ExponentialSmoothing())])

N_cv_fold = 2
step_cv = 1
fh = [1,2]

initial_window_cv_len = len(y_agg.index.get_level_values(2).unique()) - (N_cv_fold - 1) * step_cv - fh[-1]

cv = ExpandingWindowSplitter(
            initial_window = initial_window_cv_len,
            step_length = step_cv,
            fh = fh)

gscv = ForecastingGridSearchCV(
        forecaster=pipe,
        param_grid=param_grid,
        cv=cv,
        n_jobs=-1,
        verbose = 1
        )

gscv_bylevel = ForecastByLevel(gscv, 'local')

reconciler = ReconcilerForecaster(gscv_bylevel, method="ols")

reconciler.fit(y_agg)

reconciler.get_fitted_params()  # here we get the error when accessing ".get_fitted_params()"
```

**Comment by daniel-torresc** [comment]
Hello, do you have any updates on this bug? Is it possible to solve it easily?

Thank you!

**Comment by fkiraly** [comment]
that must be telepathy. I was just working on this.

**Comment by fkiraly** [comment]
here: #4632

**Comment by daniel-torresc** [comment]
Now that's telepathy! 

I have seen the PR, but I still have some questions. Shouldn't the reconciler access all the best-fitted forecasters for each series? Currently, there is no possibility to access the best forecaster for each one. I believe the get_fitted_params aimed to do that, so I thought this issue was opened to solve that bug. 

Let me know if something doesn't suit you.

**Comment by fkiraly** [comment]
It does so, in the fixed state.

They live under the keys `"forecaster__ForecastByLevel__forecasters.loc[('__total', '__total'),'forecasters']__best_forecaster"]` and so on, e.g.,

```python
reconciler.get_fitted_params()["forecaster__ForecastByLevel__forecasters.loc[('__total', '__total'),'forecasters']__best_forecaster"]
```

gives the best forecaster for the total.

Quick question: do you think it convenient if there were a way to return these in a data frame, or would that be just as fiddly?

**Comment by daniel-torresc** [comment]
Oh, that's awesome, so you are changing both the bug of the Exception and this other. Perfect!

For me it would be easier if the output was a dataframe. Then anyone could access the parameters by just filtering by the column value. If possible, I think it would be better yes.

Thank you again for the hard work

**Comment by fkiraly** [comment]
@daniel-torresc, this is the proposed interface:
https://github.com/sktime/sktime/pull/4107
what do you think?

**Comment by daniel-torresc** [comment]
I don't know if I got it right. I thought the resulting dataframe would have the same information as the dictionary but in form of a DataFrame. I mean, if I would want to access the best parameters for X, Y or Z series forecast, I could access it via a column of the DataFrame.

**Comment by fkiraly** [comment]
> I could access it via a column of the DataFrame.

Yes, although in the data frame you would have the best estimators rather than their parameters.
Maybe that's not as helpful, but you can still convert it to what you want using `applymap`?
