### ISSUE TITLE
[DOC] add examples for loading data from common tabular `csv` formats

### ISSUE THREAD

**Issue by alitirmizi23** [sktime/sktime#4581]
#### Describe the issue linked to the documentation

I haven't been able to see any examples of loading data directly from .csv files into sktime compatible formats. 

There should be an example that shows import of data from csv format to sktime format with e.g each feature having 10 timesteps in each row.

**Comment by fkiraly** [comment]
@alitirmizi23, I've moved the sentene from the issue title into the description.

I agree, that would be great to have!

My feeling would be that it would be a good section 4 to the tutorial `AA_datatypes_and_datasets`.

That is, section 3 should be renamed "loading predefined data sets", and there could be a new section 4, "loading data from csv".
In there, there could be examples for the `pd.DataFrame` series format, the `pd-multiindex` panel format, and so on.

What do you think?

This also looks like a good first issue.

**Comment by alitirmizi23** [comment]
@fkiraly yes I agree. Also, I want to know how exactly I would do it until the section has been added? :P I see in older versions of sktime you could do something like "read_from_file" etc, but now all I see is read from .ts. Any pointers?

**Comment by fkiraly** [comment]
@alitirmizi23, I would just use `pandas` `read_csv` to get a `pandas` `DataFrame`, then `set_index` if necessary.

**Comment by TonyZhangkz** [comment]
Hi! Trying to find a good first issue here. I do not have prior experience working with sktime but some level of experience with pandas. May I attempt on this issue? Also, to make sure, the deliverable should be an added section on the tutorial notebook? Lots of thanks!

**Comment by fkiraly** [comment]
@TonyZhangkz, welcome to sktime!

>May I attempt on this issue?

Sure - I think @alitirmizi23 is not working on this (is that correct?)

> Also, to make sure, the deliverable should be an added section on the tutorial notebook? Lots of thanks!

Yes, that would be the idea - unless you'd like to propose sth else.

**Comment by alitirmizi23** [comment]
Yes, I’m not.

**Comment by TonyZhangkz** [comment]
@alitirmizi23 Hi there. Though my final output should be shown in the tutorial. I'd like to address your problem more specifically (if it's not solved yet).

> There should be an example that shows import of data from csv format to sktime format with e.g each feature having 10 timesteps in each row.

I assume we're talking about a multivariate setting here. May I know what you meant by 10 timesteps each row? I'm a bit confused as most of the formats I've seen so far would typically include one timestep in a row.

**Comment by fkiraly** [comment]
> I'm a bit confused as most of the formats I've seen so far would typically include one timestep in a row.

Yes, you are right, @TonyZhangkz.
I would interpret the request more broadly, just explain how to load to the common (series, panel, etc) formats described in the tutorial.

**Comment by alitirmizi23** [comment]
> @alitirmizi23 Hi there. Though my final output should be shown in the tutorial. I'd like to address your problem more specifically (if it's not solved yet).
> 
> > There should be an example that shows import of data from csv format to sktime format with e.g each feature having 10 timesteps in each row.
> 
> I assume we're talking about a multivariate setting here. May I know what you meant by 10 timesteps each row? I'm a bit confused as most of the formats I've seen so far would typically include one timestep in a row.

Yes you’re right. This is the raw CSV/tabular data that we wanna convert to a multivariate time series format for sktime. By 10 time steps, I meant each row of the output sktime format dataset should have 10 time steps. Consider a 3D numpy array, where the shape is (N, num_fearures, time_steps). This is what I expect in the output, given raw tabular data and some parameters like window_len and so on

**Comment by alitirmizi23** [comment]
Hope this clarifies

**Comment by TonyZhangkz** [comment]
@alitirmizi23 Thanks for clarifying! 

I've made a PR on what I think would solve your problem, but I think the main concern here is really what your csv/other external files look like rather than how the sktime container would translate into some other sktime container format (please correct me if I'm wrong). 

To clarify, this is a broader question to make a tutorial on (i.e. how to load from files and convert accordingly) so I'm not sure how precisely it would be solving YOUR issue per se. But right now I think it would help if you can tell me specifically what does your csv files look like (if that's possible) once they load and we'd be able to solve where you're stuck at right now.

**Comment by fkiraly** [comment]
good point, @TonyZhangkz!

Perhaps in the tutorial, you can also explain what the `csv` look like in that case, and always assume it is simple tabular with some columns being turned into index later, etc.

**Comment by alitirmizi23** [comment]
> @alitirmizi23 Thanks for clarifying!
> 
> I've made a PR on what I think would solve your problem, but I think the main concern here is really what your csv/other external files look like rather than how the sktime container would translate into some other sktime container format (please correct me if I'm wrong).
> 
> To clarify, this is a broader question to make a tutorial on (i.e. how to load from files and convert accordingly) so I'm not sure how precisely it would be solving YOUR issue per se. But right now I think it would help if you can tell me specifically what does your csv files look like (if that's possible) once they load and we'd be able to solve where you're stuck at right now.

example: Here's how my csv data looks like:

`<html xmlns:v="urn:schemas-microsoft-com:vml" xmlns:o="urn:schemas-microsoft-com:office:office" xmlns:x="urn:schemas-microsoft-com:office:excel" xmlns="http://www.w3.org/TR/REC-html40">
<head>

<meta name=Generator content="Microsoft Excel">

<style>

</style>
</head>
<body>



date-time | dim_0 | dim_1 | dim_2 | dim_3 | dim_4 | dim_5
-- | -- | -- | -- | -- | -- | --
1/1/2023 0:01 | 0.775317348 | 0.346879253 | 0.283389102 | 0.555790361 | 0.098197228 | 0.391304324
1/1/2023 0:02 | 0.243642728 | 0.632086774 | 0.70963464 | 0.774455037 | 0.718844574 | 0.506008278
1/1/2023 0:03 | 0.206610632 | 0.395612127 | 0.891511046 | 0.76886991 | 0.653097261 | 0.414721473
1/1/2023 0:04 | 0.09201931 | 0.356232886 | 0.391322331 | 0.869860093 | 0.19456263 | 0.371474754
1/1/2023 0:05 | 0.045957731 | 0.69928187 | 0.180110184 | 0.316870962 | 0.511156718 | 0.345947971
1/1/2023 0:06 | 0.572105914 | 0.601613418 | 0.192329235 | 0.045937578 | 0.069556325 | 0.653089621
1/1/2023 0:07 | 0.995150217 | 0.768886733 | 0.766172579 | 0.191519378 | 0.194558031 | 0.485437308
1/1/2023 0:08 | 0.281583346 | 0.492477888 | 0.192323306 | 0.857891586 | 0.933209475 | 0.203299158
1/1/2023 0:09 | 0.35147239 | 0.69930267 | 0.852265401 | 0.219477406 | 0.77446251 | 0.399369026
1/1/2023 0:10 | 0.492097399 | 0.768890114 | 0.058440505 | 0.803293662 | 0.419331846 | 0.995161451
1/1/2023 0:11 | 0.285316537 | 0.640548186 | 0.203300343 | 0.725557009 | 0.098177899 | 0.07914238
1/1/2023 0:12 | 0.136978548 | 0.396312153 | 0.678450051 | 0.993415247 | 0.203295616 | 0.419323698
1/1/2023 0:13 | 0.002039087 | 0.484294313 | 0.735312043 | 0.747819048 | 0.747811431 | 0.696561573
1/1/2023 0:14 | 0.891529943 | 0.147037539 | 0.315015855 | 0.396309173 | 0.775313337 | 0.420861814



</body>

</html>
`
and here's how I want to process it so that each row becomes a certain number of time steps e.g below - so that I can run something like catch22 or time series regression on top:

![image](https://github.com/sktime/sktime/assets/44982627/7e10cdf8-6efc-408a-a605-37e6d5c86528)

As you see, now there's multiple time steps in a single row (as you would want for a time series  regression/classification/feature extraction task

**Comment by alitirmizi23** [comment]
And you'd want some parameters like window_len and horizon to control over how many time steps make up one row, and what horizon of target (y) they look up until based on the horizon parameter. A very nice example is the SlidingWindow() from [TSAI](https://timeseriesai.github.io/tsai/) (
![image](https://github.com/sktime/sktime/assets/44982627/cce0479b-0272-4973-af97-bb09a385d42d)
)

**Comment by fkiraly** [comment]
@alitirmizi23, which column is time, and which is instance? This looks like an ordinary tabular data set, so like a single time series or a number of independent, non-temporal observations.

**Comment by alitirmizi23** [comment]
> @alitirmizi23, which column is time, and which is instance? This looks like an ordinary tabular data set, so like a single time series or a number of independent, non-temporal observations.

The “index” column is time. And each row is an instance/record (I’m not sure what you mean here by instance). And these are temporal observations of multiple e.g sensors/time series

**Comment by alitirmizi23** [comment]
Basically a conversion from 2D shape dataset (N, num_features) to a 3D shape (N-time_steps,  time_steps, num_features). I don’t know if I’m making sense here but basically I want my multivariate 2D dataset to become 3D multivariate time series dataset, like one you’d feed to an LSTM or something. It’s pretty common. This example is from one of the multivariate datasets in sktime (basic_motions I think)

**Comment by fkiraly** [comment]
what are your labels in your csv?

**Comment by alitirmizi23** [comment]
Imagine dim_5 jis labels

**Comment by fkiraly** [comment]
Ok, I'm getting confused. This looks like tabular regression, not time series regression?

**Comment by TonyZhangkz** [comment]
@alitirmizi23  I think there's a chance that I misunderstood the problem from the beginning as I thought you were asking about the "loading from csv" problem per se. May I confirm that you're trying to do something like a regression with a formula that looks like dim_5 (10 timesteps each record) ~ everything else? In that case, I don't think this is a csv-to-sktime container issue. If this is the case, while @fkiraly I do not have the most extensive knowledge of the container, I'd think this part should rather be a container-to-container (both sktime in-memory ones) process? 

If it's a "yes" to both questions, I think it would be better if we open a new thread. I will try to expand on tutorials related to transformations instead of data-loading to address the issue better.

**Comment by TonyZhangkz** [comment]
> Perhaps in the tutorial, you can also explain what the `csv` look like in that case, 

Yes. I'll show that and update it accordingly. 

> and always assume it is simple tabular with some columns being turned into index later, etc.

I agree with this assumption.

**Comment by Nirbhai** [comment]
Hi, I'm new here and looking for good first issues. It seems the required section (Section 4: loading data from csv files) is already added in the AA_datatypes_and_datasets.ipynb as part of #4612

Does the section need further details or should this issue be closed?

Thanks a lot!

**Comment by fkiraly** [comment]
Yes, I think https://github.com/sktime/sktime/pull/4612 solves this, and this issue can be closed.
