### ISSUE TITLE
[DOC] Include `doctest` section in developer guide

### ISSUE THREAD

**Issue by hazrulakmal** [sktime/sktime#4582]
#### Describe the issue linked to the documentation
The developer guide should include steps for running `doctest` locally. This will help new developers understand how to run a `doctest` to catch any potential doc errors before making commits to a pull request. Currently, the guide only covers `pytest`.

#### Suggest a potential alternative/fix

A suggestion is to add it as a subsection after `Full test suite runs via pytest`.
Here's from `doctest` on running the doctests locally: https://docs.python.org/3/library/doctest.html

**Comment by fkiraly** [comment]
Indeed, good idea! I think this is also a good first issue.

**Comment by mdsaad2305** [comment]
Hi, I would like to work on this issue. Along with demonstrating how to use doctest, are we supposed to include an installation guide?

**Comment by fkiraly** [comment]
> Along with demonstrating how to use doctest, are we supposed to include an installation guide?

There already is a full guide for installation and one for testing, the latter just doesn't include instructions for local doctest.

**Comment by yarnabrina** [comment]
Most of the code snippets in `sktime` has `doctest: +SKIP` flag added. These lines will be skipped. The remaining lines most are assignments, and it's seldom the case that something is actually run without assigning and that value is specified in the docstrings. Will `doctest` really help the users/developers much in this context?

Just to be clear, I am not at all against documenting how to run doctests. I just wanted to share an observation to get the idea about how you are thinking it's going to help.

**Comment by fkiraly** [comment]
@yarnabrina, the `doctest: +SKIP` is not everywhere and only in some cases - it is added *only* in cases where the doctest imports a soft dependency.

Soft dependencies need to be isolated, so the full test suite runs (does not raise import exception) if it is not present, see here:
https://www.sktime.net/en/latest/developer_guide/dependencies.html#adding-a-soft-dependency

This poses a problem with doctests, as there is no way (that I know) that allow conditional execution of doctests based on the _check_soft_dependencies` utility.

So, instead, we skip those doctests and instead test the same code (or code with equivalent or higher coverage) in a `pytest` test that has a conditional skip with `_check_soft_dependencies`.

Slightly complicated, I know - any suggestions are appreciated.

**Comment by mdsaad2305** [comment]
Is it advisable to incorporate specific examples alongside this?
