### ISSUE TITLE
[BUG] incompatibility of `Prophet` with `holidays 0.25.0`

### ISSUE THREAD

**Issue by fkiraly** [sktime/sktime#4595]
`Prophet` with `holidays 0.25.0` crashes in the CI since the `holidays` release - the location of the error or its nature is unclear.

For now, this has been solved by bounding `holidays`, but we should investigate the issue and potentially fix it, if it is localized in `sktime`. At least, it could be caught instead of leaving to an error in contsructing the estimator.

Reference: https://github.com/sktime/sktime/pull/4594

**Comment by tcuongd** [comment]
Yep sorry a fix was merged and a release was made here: https://github.com/facebook/prophet/releases/tag/v1.1.3-patched

New version of prophet should be on PyPI after this workflow finishes: https://github.com/facebook/prophet/actions/runs/5004631722

**Comment by fkiraly** [comment]
hm, any insight what's going on with `holidays` there? Is this a missed deprecation or a bug?
