### ISSUE TITLE
[BUG] `ForecastX` ignores the alpha quantiles argument and only uses the default [0.05, 0.95]

### ISSUE THREAD

**Issue by rokazok** [sktime/sktime#4624]
ForecastX's [predict_quantiles()](https://www.sktime.net/en/latest/api_reference/auto_generated/sktime.forecasting.compose.ForecastX.html?highlight=forecastx#sktime.forecasting.compose.ForecastX.predict_quantiles) and [predict_interval()](https://www.sktime.net/en/latest/api_reference/auto_generated/sktime.forecasting.compose.ForecastX.html?highlight=forecastx#sktime.forecasting.compose.ForecastX.predict_interval) methods ignore quantiles and default to `alpha=[0.05, 0.95]` and `coverage=0.9`, respectively.

Copying the example from ForecastX to illustrate:
```python
from sktime.datasets import load_longley
from sktime.forecasting.arima import ARIMA
from sktime.forecasting.base import ForecastingHorizon
from sktime.forecasting.compose import ForecastX
from sktime.forecasting.var import VAR
y, X = load_longley()
fh = ForecastingHorizon([1, 2, 3])
pipe = ForecastX(
    forecaster_X=VAR(),
    forecaster_y=ARIMA(),
)
pipe = pipe.fit(y, X=X, fh=fh)
y_pred = pipe.predict(fh=fh)
y_pred


quantiles = [0.2, 0.5, 0.8]
pipe.predict_quantiles(fh=fh, alpha=quantiles)
#       Quantiles              
#       0.05          0.95
# 1963  70602.793628  72066.289778
# 1964  71121.279792  72788.556655
# 1965  72450.921393  74174.247432

pipe.predict_interval(fh=fh, coverage=max(quantiles) - min(quantiles))
#         Coverage              
#         0.9              
#         lower         upper
# 1963    70602.793628  72066.289778
# 1964    71121.279792  72788.556655
# 1965    72450.921393  74174.247432

# Compare to ARIMA
ar = ARIMA()
ar.fit(y, fh=fh)
ar.predict_quantiles(fh=fh, alpha=quantiles)
#       Quantiles                            
#       0.2           0.5           0.8
# 1963  69196.407538  70190.893152  71185.378767
# 1964  68498.558177  69856.218508  71213.878839
# 1965  67938.605173  69545.179942  71151.754711

ar.predict_interval(fh=fh, coverage=max(quantiles) - min(quantiles))
#         Coverage              
#         0.6              
#         lower         upper
# 1963    69196.407538  71185.378767
# 1964    68498.558177  71213.878839
# 1965    67938.605173  71151.754711
```

**Comment by fkiraly** [comment]
@rokazok, yes, that's an accident that had happened in earlier `sktime` versions, but the bug should be fixed by this PR https://github.com/sktime/sktime/pull/4391 and therefore since 0.17.0

**Comment by fkiraly** [comment]
duplciate of https://github.com/sktime/sktime/issues/4386, actually

**Comment by rokazok** [comment]
Ah, thanks! I was using an older version of `sktime`, and I should've upgraded before submitting. :facepalm:

**Comment by fkiraly** [comment]
no worries. Always good if the time it takes to fix your bug turns out to be negative, isn't it? :-)
