### ISSUE TITLE
[DOC] ReducerTransform Documentation

### ISSUE THREAD

**Issue by abishalom** [sktime/sktime#4661]
Documentation for ReducerTransform does not exist. 

Link: https://www.sktime.net/en/latest/api_reference/auto_generated/sktime.transformations.series.lag.ReducerTransform.html

**Comment by namita0210** [comment]
> Documentation for ReducerTransform does not exist.
> 
> Link: https://www.sktime.net/en/latest/api_reference/auto_generated/sktime.transformations.series.lag.ReducerTransform.html

Hi, Can I take up this issue ?
I have just joined the sktime community via GSOC, I'm really excited for my first contribution!

**Comment by yarnabrina** [comment]
This exists as of today, so probably was fixed earlier but this issue was not linked. Closing now.

**Comment by fkiraly** [comment]
@namita0210, feel free to ask on discord if you need help picking a good first issue!

**Comment by namita0210** [comment]
> @namita0210, feel free to ask on discord if you need help picking a good first issue!

Sure, thanks. After going through a good number of issues I think I really do need some help in selecting one to get started.

**Comment by fkiraly** [comment]
@namita0210, have you found sth?
How about this? https://github.com/sktime/sktime/issues/3429

If you need further help, pleas ask on dev-chat on discord.

**Comment by namita0210** [comment]
Hi,
Thanks for the suggestion, I think this is a nice first issue and I would
love to get started with it.
