### ISSUE TITLE
[ENH] `SplitterSummarizer` which applies a series-to-primitive transformer per split

### ISSUE THREAD

**Issue by fkiraly** [sktime/sktime#4664]
From discussion with @abishalom on discord.

I infer that it would be great to have a "splitter summarizer", which is a series-to-series transformer.

It takes as a parameter a series-to-primitives transformer `t` and a splitter `cv`.

It transforms a single series `X` into a single series `Xt`, such that: the `i`-th row of `Xt` is `t.fit_transform(cv.split_y(X)[i][0])` (i.e., the `t`-transform of the `i`-th train split of `X`), where all series are `pd.DataFrame` (otherwise equivalent index). The `fit` is empty.

Optionally, there is a parameter that determines the index of `Xt`, it could be the integer index, or the last index of the train split.

FYI @abishalom - if you pipeline `SplitterSummarizer(PCA(), cv=ExpandingWindowSplitter())` with `ARIMA`, it should be what you want?

That is, the forecaster you want (if I understand right?) is

`SplitterSummarizer(PCA(), cv=ExpandingWindowSplitter()) * ARIMA()`

**Comment by BensHamza** [comment]
Hello, I would love to take this PR for a first contribution if possible. Thanks

**Comment by fkiraly** [comment]
of course! Let us know if you need help getting started.

Here's the guide for implementing estimators: https://www.sktime.net/en/stable/developer_guide/add_estimators.html
(this should be a transformer, series to series)
