### ISSUE TITLE
[MNT] update pre-commit hook versions and make appropriate changes in the affected files

### ISSUE THREAD

**Issue by yarnabrina** [sktime/sktime#4676]
Most hook versions in [.pre-commit-config.yaml](https://github.com/sktime/sktime/blob/main/.pre-commit-config.yaml) is quite outdated. These may be updated to the latest verions using `pre-commit autoupdate`.

However, it leads to formatting changes (mostly by `black`) to ~140 files, as per `pre-commit run --all-files`. This will lead to change in Git blame for all of these. While that is useful to keep track of changes and ask for help/guidance in future by newer contributors, this may be worth considering in future.

Ref. https://github.com/sktime/sktime/pull/4673#issuecomment-1575415066

**Comment by fkiraly** [comment]
I'd be fine with updating, if the changes are bunched in a single PR. The standard is blame by line anyway.
