### ISSUE TITLE
[DOC] change default documentation version from `latest` (`main` branch) to `stable` (latest tag) in read-the-docs configuration

### ISSUE THREAD

**Issue by yarnabrina** [sktime/sktime#4677]
Currently the [documentation website](https://www.sktime.net) defaults to `latest`, i.e. the `main` branch. So, it is possible that it shows some estimators or arguments which are not yet released and won't be available for the general users who download from `PyPI` or `conda-forge`.

Read-the docs allow to change the default version, and it can be considered to switch to `stable` to refer to [latest semantic version](https://docs.readthedocs.io/en/stable/versions.html). This is likely to be what's used by most of the direct users of `sktime` (i.e. not through another framework whose dependency is `sktime`).

To make the change, the read-the-docs owner can log in, go to `Admin`, go to `Advanced Settings`, change `Default version` and save the changes. It's likely to trigger a new build and then will be in effect once it's complete.

**Comment by fkiraly** [comment]
I know - it is on `latest` by default, so documentation updates can happen without package releases - e.g., announcements the internships, developer events etc; or, fixes to the documentation.

The downside indeed is that some estimators that aren't available appear as available.

We've never had a proper discussion of pros/cons though as far as I can remember, so it's probably worth having it, i.e., what is better for the user.

**Comment by fkiraly** [comment]
(example: the `stable` release for 0.19.1 had a duplication fo the 0.19.0 release notes by accident. This was easy to fix by a PR post release as we are pointing to `latest`)

**Comment by yarnabrina** [comment]
I see. In that case, is it possible to keep the default as `latest` for your above reasons, but display a FYI banner? An example of that is present in [`elyra` documentation](https://elyra.readthedocs.io/).

> This document is for the development version. For the stable version documentation, see here.

**Comment by fkiraly** [comment]
> In that case, is it possible to keep the default as latest for your above reasons, but display a FYI banner?

Yes, that seems like a great compromise, have your cake and eat it.

**Comment by fkiraly** [comment]
@yarnabrina, where is the banner supposed to be if this worked?

**Comment by yarnabrina** [comment]
It should've appeared at top of the page. You can see the elyra link above for an example.

It didn't work, but I really don't have any idea what did I miss and where.
