### ISSUE TITLE
[BUG] 'no-update_params' strategy not working in evaluate()

### ISSUE THREAD

**Issue by wchen01** [sktime/sktime#4685]
**Describe the bug**

Using 'no-update_params' strategy in evaluate() will raise the following exception.

NotFittedError: This instance of NaiveForecaster has not been fitted yet; please call `fit` first.

**To Reproduce**

```python
import pandas as pd
from sktime.forecasting.naive import NaiveForecaster
from sktime.forecasting.model_selection import ExpandingWindowSplitter
from sktime.forecasting.model_evaluation import evaluate

cv = ExpandingWindowSplitter(
    initial_window=10,
    step_length=1,
    fh=[1]
)

result = evaluate(
    forecaster=NaiveForecaster(),
    y=pd.DataFrame({'data': range(20)}),
    cv=cv,
    strategy='no-update_params',
    error_score='raise',
    return_data=True
)
```

**Expected behavior**
A result returned without exceptions

**Additional context**

**Versions**
<details>

System:
    python: 3.9.2 (default, Feb 28 2021, 17:03:44)  [GCC 10.2.1 20210110]
executable: /usr/bin/python3
   machine: Linux-6.1.0-9-amd64-x86_64-with-glibc2.31

Python dependencies:
          pip: 20.3.4
       sktime: 0.19.0
      sklearn: 1.2.2
        numpy: 1.23.5
        scipy: 1.10.1
       pandas: 1.5.3
   matplotlib: 3.7.1
       joblib: 1.2.0
  statsmodels: 0.14.0
        numba: 0.57.0
     pmdarima: 2.0.3
      tsfresh: 0.20.0
   tensorflow: 2.12.0
tensorflow_probability: 0.20.1

</details>

**Comment by hazrulakmal** [comment]
Thanks for reporting this bug. 

I think the problem lies in the private function `_evaluate_window` specifically when calling the forecaster `update` method. After some debugging, I found that the first cv gets fitted but fails to save the fitted forecast state for the next cv iteration. 

The solution for this is to add another layer of logic in `_evaluate_window` so that it handles `no-update_params` strategy similar to how `update` strategy does. 

<details>
<summary>Full Traceback</summary>

```
Traceback (most recent call last):
  File "c:/Users/hazru/Desktop/github/dev-test/evaluate_bug_test.py", line 12, in <module>
    result = evaluate(
  File "C:\Users\hazru\Desktop\github\open_source_contributions\sktime\sktime\forecasting\model_evaluation\_functions.py", line 416, in evaluate        
    result = _evaluate_window(
  File "C:\Users\hazru\Desktop\github\open_source_contributions\sktime\sktime\forecasting\model_evaluation\_functions.py", line 183, in _evaluate_window
    raise e
  File "C:\Users\hazru\Desktop\github\open_source_contributions\sktime\sktime\forecasting\model_evaluation\_functions.py", line 144, in _evaluate_window
    forecaster.update(y_train, X_train, update_params=update_params)
  File "C:\Users\hazru\Desktop\github\open_source_contributions\sktime\sktime\forecasting\base\_base.py", line 869, in update
    self.check_is_fitted()
  File "C:\Users\hazru\Desktop\github\open_source_contributions\sktime\sktime\base\_base.py", line 380, in check_is_fitted
    raise NotFittedError(
sktime.exceptions.NotFittedError: This instance of NaiveForecaster has not been fitted yet; please call `fit` first.
```
</details>

**Comment by fkiraly** [comment]
hm, my comment would be, is this not tested?

Indeed it was not! It is missing, e.g., in the `mark.parametrize`-s in `test_evaluate.py`, compare line 104 and 219.

It should be easy to develop a bugfix using TDD by just adding the `no-update_params` strategy there.

**Comment by hazrulakmal** [comment]
I'm sorry but what is *TDD*?

**Comment by fkiraly** [comment]
> I'm sorry but what is TDD?

https://en.wikipedia.org/wiki/Test-driven_development

describes the context where you write the test first, and then develop until it passes.

Some people are very religious about it and say, this is how you should always develop.

In my own humble opinion, there's a spectrum between exploration driven (especially when experimental), specification driven (write specs and docstring first), and TDD, where the "best" thing is situational.

**Comment by hazrulakmal** [comment]
oh I see. Thanks for sharing this is really helpful!
