### ISSUE TITLE
[DOC] Add a copy button to the documentation to help copy pasting the documented examples

### ISSUE THREAD

**Issue by yarnabrina** [sktime/sktime#4696]
Currently, all the documented examples need to be manually copied by the users to try for their own. Adding a `copy` button can simplify this task for user convenience. [This](https://github.com/executablebooks/sphinx-copybutton) extension should be able to add this.

Steps required:

- add new `docs` dependency in `pyproject.toml`
- add to list of extensions in `conf.py`
- configure as per [`documentation`](https://sphinx-copybutton.readthedocs.io/en/latest/use.html)

**Comment by yarnabrina** [comment]
I know it's used by [`pandas`](https://github.com/pandas-dev/pandas/blob/a43c2e4962dc186c472f52922dbecf2f93f98aae/doc/source/conf.py#L58), don't know about general adoption.

I think it's maintained, it's latest release is in this April only. Also given it's an extension to Sphinx, I'd personally not be very bothered if releases are infrequent, as there may not be anything significantly worth modifying given very limited goal.

**Comment by fkiraly** [comment]
Well, if `pandas` uses it, I'm happy.

**Comment by yarnabrina** [comment]
Sure @MedAmine-SUDO, go for it 👍🏽

Please go through the [contribution guidelines](https://www.sktime.net/en/latest/get_involved/contributing.html). Let us know if you need any help anywhere.
