### ISSUE TITLE
[BUG] CI failures when loading from UEA time series classification data repo

### ISSUE THREAD

**Issue by fkiraly** [sktime/sktime#4703]
The notebook CI seems to have started failing without any related code change prior.

The failure occurs when attempting to load the `Yoga` dataset, with exception

```
Invalid dataset name =Yoga is not available on extract path =None. Nor is it available on [https://timeseriesclassification.com/.](https://timeseriesclassification.com/)
```

The code snippet that causes the error seems to be

```python
from sktime.datasets import load_UCR_UEA_dataset

X, y = load_UCR_UEA_dataset(name="Yoga", return_X_y=True)
```

but this seems to work fine locally.

Update: most datasets no longer work locally either, see below.

**Comment by fkiraly** [comment]
* seems to be zip corruption? It seems to be a deterministic, certain failure, not stochastic.
* There is only one change in versions that I can spot, since the lats successful CI: `precommit` to 3.3.3

**Comment by fkiraly** [comment]
Hm, it would appear that most of the datasets listed in

`from sktime.datasets.tsc_dataset_names import univariate`

no longer work.

The few ones still working are those used in most notebooks and tests, i.e., `OSULeaf` or `PLAID`, which is probably why this did not raise a test failure earlier.

The most likely explanation seems to be a change on the side of the UEA time series classification data repository.

**Comment by fkiraly** [comment]
Perhaps it got deprecated.

**Comment by fkiraly** [comment]
Exact time where this failure started can be narrowed down:

* the last passing CI on the notebooks I can find started around June 14, 16:50 GMT/UTC, here: https://github.com/sktime/sktime/pull/4700/commits/1db1d7226429ee09c06bcd8317fe454b0a3bd16c
* the first failing CI on the notebooks I can find started around June 15, 5:50 GMT/UTC, here: https://github.com/sktime/sktime/actions/runs/5263257765/attempts/1?pr=4702

**Comment by fkiraly** [comment]
What is quite odd: we are testing the loaders punctually, with the following:

```python
    load_acsf1,
    load_arrow_head,
    load_basic_motions,
    load_italy_power_demand,
    load_japanese_vowels,
    load_osuleaf,
    load_plaid,
    load_unit_test,
```

These are all functioning and passing!

Whereas, the 100 other datasets are now all failing - including one instance in the notebooks ("Yoga") which was not tested in the `pytest` test suite.

**Comment by yarnabrina** [comment]
Is the link correct in `_data_io.py`? It seems to be different from the one used here in `aeon` repo, which works.

https://github.com/sktime/sktime/blob/533ec06eaaa5e1a715e355e23a44d908f9964b7f/sktime/datasets/_data_io.py#L198

vs

https://github.com/aeon-toolkit/aeon/blob/02f9519c614e8ff89395ab8b0e42f6117a5f2b2a/aeon/datasets/_data_loaders.py#L452

**Comment by fkiraly** [comment]
It is exactlz the same:

`url = "https://timeseriesclassification.com/Downloads/%s.zip" % name`

see line 198 in `_load_dataset`

**Comment by fkiraly** [comment]
Does it work for you, locally, @yarnabrina?

**Comment by fkiraly** [comment]
Well, that explains it. Tony Bagnall changed the path to `"https://timeseriesclassification.com/ClassificationDownloads/%s.zip"` without deprecation warning.

**Comment by fkiraly** [comment]
not quite sure what UEA are thinking here - this will not just break `sktime`, but also all earlier versions of their own loader?
Either way, this makes the temporary fix easy.

In the interest of our users, however, I think this highlights an important point: robustness of the data loaders. We may want to introduce, e.g., mirrors. I will open a separate issue.
