### ISSUE TITLE
[BUG] `LSTMFCNClassifier` deserialization from file does not work

### ISSUE THREAD

**Issue by AIofHuman** [sktime/sktime#4706]
**Describe the bug**
Error loading previously saved model

**To Reproduce**

```python
network2 = LSTMFCNClassifier.load_from_path('LSTMFCNClassifier_test.zip')
y_pred = network2.predict(X_test)
```
I had this error:
AttributeError                            Traceback (most recent call last)
<ipython-input-4-2aca12ee5ef2> in <module>
----> 1 network2 = LSTMFCNClassifier.load_from_path('LSTMFCNClassifier_test.zip')
      2 y_pred = network2.predict(X_test)
      3 print(f'accuracy_score={accuracy_score(y_pred, y_test)}')
      4 #

~/.local/lib/python3.8/site-packages/sktime/classification/deep_learning/base.py in load_from_path(cls, serial)
    353         from tensorflow import keras
    354 
--> 355         temp_unzip_loc = serial.parent / "temp_unzip/"
    356         temp_unzip_loc.mkdir()
    357 

AttributeError: 'str' object has no attribute 'parent'

**Expected behavior**
loading a previously saved model and prediction

**Additional context**

**Versions**
System:
    python: 3.8.12 (default, Sep 10 2021, 00:16:05)  [GCC 7.5.0]
executable: /usr/local/bin/python3
   machine: Linux-4.4.0-142-generic-x86_64-with-glibc2.27

Python dependencies:
          pip: 21.3.1
       sktime: 0.19.1
      sklearn: 1.2.2
        numpy: 1.22.4
        scipy: 1.10.1
       pandas: 1.5.3
   matplotlib: 3.1.3
       joblib: 1.2.0
  statsmodels: None
        numba: 0.51.2
     pmdarima: None
      tsfresh: None
   tensorflow: 2.6.0
tensorflow_probability: None

**Comment by fkiraly** [comment]
FYI @achieveordie

**Comment by achieveordie** [comment]
Hey @AIofHuman, thanks for reporting this! The standard way to load the model would be via `sktime.base.load()`. I'm attaching a self-contained code to show you the process:

``` python
from sktime.classification.deep_learning.lstmfcn import LSTMFCNClassifier
from sktime.datasets import load_arrow_head
from sktime.base import load

from sklearn.metrics import accuracy_score

X_train, y_train = load_arrow_head(split="train", return_X_y=True)
X_test, y_test = load_arrow_head(split="test", return_X_y=True)

clf = LSTMFCNClassifier(n_epochs=10, verbose=True)

clf.fit(X_train, y_train)
y_train_pred = clf.predict(X_train)
print("Train accuracy from starting model: ", accuracy_score(y_train, y_train_pred))

clf.save("lstmfcn_model")

loaded_clf = load("lstmfcn_model")
y_test_pred = loaded_clf.predict(X_test)

print("Test Accuracy from loaded model: ", accuracy_score(y_test, y_test_pred))
```

However, if you must use `load_from_path()`, please pass it as:
``` python
from pathlib import Path

...

network2 = LSTMFCNClassifier.load_from_path(Path('LSTMFCNClassifier_test.zip'))
```

I hope that solves your problem.

@fkiraly thanks for tagging me. Do you think it'll be better if we privatize the function to make it more obvious that these class methods are not to be used directly?  We surely need to update the docstrings though.

**Comment by AIofHuman** [comment]
Namaste @achieveordie ! Thank's for answer. It helped me!

**Comment by fkiraly** [comment]
@achieveordie, yes, good point about the public vs private interface.

I think the serialization functionality is not documented well in tutorials either.

We should probably make private the extender methods that are not intended as public.

However, this may required deprecation as people might already use them as public.
