### ISSUE TITLE
[BUG] Column names `predict_interval` output inconsistent between univariate and multivariate case

### ISSUE THREAD

**Issue by benHeid** [sktime/sktime#4709]
**Describe the bug**

When calling `predict_interval` on a pd.Series or pd.Dataframe with only one column, the column name in the result is `Coverage` and not the original column's name

**To Reproduce**

Using a series
```python
y, X = load_longley()
y_train, y_test, X_train, X_test = temporal_train_test_split(y, X)
pipe = Differencer() * ExponentTransformer() ** SARIMAX()
pipe.fit(y=y_train, X=X_train, fh=[1, 2, 3, 4])
pipe.predict_interval(X=X_test)
```

Output: 

```
          Coverage              
               0.9
             lower         upper
1959  66024.326892  68465.109904
1960  66001.646041  70923.894181
1961  65438.989794  72844.058934
1962  66857.619049  76745.554752
```

Using a dataframe with two columns:

```python
y, X = load_longley()
y = pd.concat([y] * 2, ignore_index=True, axis=1)
y_train, y_test, X_train, X_test = temporal_train_test_split(y, X)
pipe = Differencer() * ExponentTransformer() ** SARIMAX()
pipe.fit(y=y_train, X=X_train, fh=[1, 2, 3, 4])
pipe.predict_interval(X=X_test)
```
Output
```
                   0                           1              
                 0.9                         0.9              
               lower         upper         lower         upper
Period                                                        
1959    66024.714431  68466.243863  66024.714431  68466.243863
1960    66002.607821  70926.326488  66002.607821  70926.326488
1961    65440.810411  72848.072287  65440.810411  72848.072287
1962    66860.203253  76751.053796  66860.203253  76751.053796

```

**Expected behavior**
The forecaster should reuse the same column also in the single column case. However, I am unsure if this is a bug or expected behavior.

**Comment by fkiraly** [comment]
It's part of the contract, but I agree it is inconsistent and potentially confusing for the user.

It has also generated repeated pain by introducing an unnecessary case distinction between univariate and multivariate case.

For this reason, I've now regretted being in favour of this, but that's the wisdom of hindsight.

Changing it would require going through a deprecation and change cycle, since it's one of the important interface points.

**Comment by snikch** [comment]
I note that this means that `plot_series` is not compatible with `predict_interval` values from multivariates.

In my case I work around this by renaming my value from `total` to `Coverage` and then building a new column multi index.

```py
coverage = 0.9
y_pred_ints = f.predict_interval(coverage=coverage).rename(columns={'total': 'Coverage'})
y_pred_ints = y_pred_ints[['Coverage']]
y_pred_ints.columns = pd.MultiIndex.from_product([['Coverage'], [coverage], ['lower', 'upper']])
```

**Comment by fkiraly** [comment]
I see - we want to deal with `plot_series` then too, it should not assume that the column header is `"Coverage"`.
