### ISSUE TITLE
[MNT] upgrade CI machines to `latest` versions

### ISSUE THREAD

**Issue by yarnabrina** [sktime/sktime#4727]
Currently, `sktime` CI tests mainly runs on following machines:

* `macos-11`
* `ubuntu-20.04`
* `windows-2019`

The available machines are documented [here](https://docs.github.com/en/actions/using-github-hosted-runners/about-github-hosted-runners#supported-runners-and-hardware-resources). We can consider switching to the `latest` versions, which will check against the operating system versions most users are on.

* `macos-latest`
* `ubuntu-latest`
* `windows-latest`

**Comment by yarnabrina** [comment]
> should we increase the range of versions we test in the release CI

Sorry, not sure what you meant by this. Do you mean testing on multiple versions of same OS?

> manually triggerable CI element

Did you mean that all workflows will have a manual trigger, at least by cc/admin/dev people? Like one can run a specific workflow when desired without a PR? If so, yes I'd agree on that option emphatically.

---

Also, I will also suggest to have a workflow, which takes an estimator name, operating system and python version as inputs, and run all tests on that combination. Running tests take long locally (at least on my system), and by running specific estimators, at least when they are first added, we can check it's support on every single combination. I guess that means I have to modify my suggestion. My modified suggestion of the workflow is something that takes estimator name as input. Operating system and python versions are optional inputs. If specified, all tests are run on them. If unspecified, run all tests on the entire matrix. Given it's for a single estimator, hopefully won't be a very long process.

(You probably meant something other than what I interpreted, but I assumed something and went in another direction. Apologies for that, but this is something I thought before to create an issue for and then didn't for some reason.)

**Comment by fkiraly** [comment]
> Sorry, not sure what you meant by this. Do you mean testing on multiple versions of same OS?

yes, sorry for being unclear

>> manually triggerable CI element

> Did you mean that all workflows will have a manual trigger, at least by cc/admin/dev people? Like one can run a specific workflow when desired without a PR? If so, yes I'd agree on that option emphatically.

Yes, an example would be the various diagnostic PR, such as this one:
https://github.com/sktime/sktime/pull/4534

**Comment by fkiraly** [comment]
> My modified suggestion of the workflow is something that takes estimator name as input. Operating system and python versions are optional inputs. If specified, all tests are run on them. If unspecified, run all tests on the entire matrix. Given it's for a single estimator, hopefully won't be a very long process.

Yes, I think that's a great idea! Design-wise, I think we are moving towards treating individual estimators as packages that can be installed independently or not. Therefore, testing individual estimators within their specific requirements support range is the natural consequence.

> (You probably meant something other than what I interpreted, but I assumed something and went in another direction. Apologies for that, but this is something I thought before to create an issue for and then didn't for some reason.)

I think you got what I meant as you commented on it. I think you also added a related, excellent idea (estimator-wise testing). I suggest we open an issue for this?

However, I do not see how we could do this from a tech/solution perspective.

Should we open an issue for this - both the design (what *should* hpapen) and the realization aspect?

**Comment by yarnabrina** [comment]
> However, I do not see how we could do this from a tech/solution perspective.

I'll give it an attempt at this weekend to add a new workflow with aforementioned properties. I think inatalling all extras along with `check_estimator` should solve this satisfactorily. But let's see if I can reduce the installation using `_check_estimator_deps`.

Given sometime GitHub refuses to acknowledge workflows that do not exist in `main` branch, can you suggest a CC-approved way? Like, how were new workflows tested in the past before adding to `main`?

**Comment by fkiraly** [comment]
> Like, how were new workflows tested in the past before adding to `main`?

This is an open question - your input would be appreciated.
We can then summarize it in a page of the developer guide if we can generalize it - otherwise it's simply ad-hoc approvals subject to the usual PR review protocol.

We  also did it only once before as far as I can remember, that was with the automated contributor showcase generation that @achieveordie added a while ago.

We tested that in a branch first.
