### ISSUE TITLE
[DOC] clarify use of `ELLIPSIS` param in local `doctest`

### ISSUE THREAD

**Issue by fkiraly** [sktime/sktime#4730]
Apparently local `doctest` runs do not turn o nthe `ELLIPSIS` argument by default, see discussion here: https://github.com/sktime/sktime/pull/4679#issuecomment-1578990976 (FYI @yarnabrina)

This should be included in the testing guide, i.e., that the `ELLIPSIS` argument needs to be passed (if this is correct).

Good first issue to add to the docs.

**Comment by mdsaad2305** [comment]
Apologies for not fixing this issue earlier, was busy the past few weeks. Hope I can still take up this issue.

Wanted to ask how should we go about this now
1) should we add `# doctest: +ELLIPSIS` on each necessary line when using ellipsis in each file?
2) or should we update the 'continuous integration' documentation to pass the -o flag in the doctest command for the ellipsis to pass?

**Comment by fkiraly** [comment]
> Hope I can still take up this issue.

Of course!

> Wanted to ask how should we go about this now

I would say, option 2, option 1 seems like a lot of work...

**Comment by fkiraly** [comment]
Closed by https://github.com/sktime/sktime/pull/4768
