### ISSUE TITLE
[DOC] Website redirects to aeon, what is aeon?

### ISSUE THREAD

**Issue by davidgilbertson** [sktime/sktime#4739]
Hi I'm a new user and just went to http://sktime.org (following a link from the original sktime paper) and found myself redirected to Aeon "a fork of the sktime repository". What is this? I found one reference to aeon in the issues but couldn't find any explanation of what it is or guidance on which repo I should be using (is this a rebranding, a rivalry, or something else?).

BTW, from what I've seen so far, sktime is excellent!

**Comment by fkiraly** [comment]
The old domain was hijacked and is potentially a security risk, see here:
https://github.com/sktime/sktime/issues/4203

We've been increasing our security posture and legal standing to prevent this from happening in the future.

"aeon" is a fork who have been falsely claiming they are replacing `sktime` or are a rebranding of `sktime`.

**Comment by fkiraly** [comment]
Let us know if you have any questions, otherwise I'll close this as a duplicate of #4203.

**Comment by davidgilbertson** [comment]
Nope, that answers my question, thanks for the prompt reply!

**Comment by fkiraly** [comment]
@davidgilbertson, can you actually provide more detail what happens when you visit sktime.org?

I just tried to go there and get a security warning from my browser:

![image](https://github.com/sktime/sktime/assets/7985502/5a181681-ab0d-4d7c-bb57-e9faf39f648d)

**Comment by davidgilbertson** [comment]
Sure, my exact steps:
* Clicked this link in the paper: https://github.com/alan-turing-institute/sktime/wiki/Related-software
* Clicked the link on the page it took me to: https://www.sktime.org/en/latest/related_software.html
* Got the security error, so tried changing `https` to `http` got a 404
* Dropped the rest of the path, so just going to `http://sktime.org` - that redirects to Aeon
* Then out of curiosity, googled "sktime.org" and that also points me toward Aeon
* Wondered "what's Aeon" ... and here we are :)

**Comment by fkiraly** [comment]
I see - thanks for the info. I fixed the link in the wiki above.
