### ISSUE TITLE
[DOC] improve formulations and user experience of repo README

### ISSUE THREAD

**Issue by mswat5** [sktime/sktime#4755]
#### Describe the issue linked to the documentation
I would like to enhance certain sections to give them a more professional feel.

**Comment by mswat5** [comment]
@ksachdeva  Could you please assign me to this issue, or should I proceed to raise a pull request directly?

**Comment by fkiraly** [comment]
Sure! Can you expand in more detail which sections you would like to work on?

**Comment by mswat5** [comment]
The introductory lines for the "Features" and "Where to ask questions" section

**Comment by mswat5** [comment]
There appear to be some minor spelling errors that I would be happy to rectify.

**Comment by fkiraly** [comment]
sure, please go ahead!

**Comment by mswat5** [comment]
hey @fkiraly please have a look at #4757 PR
