### ISSUE TITLE
[BUG] `predict_residuals(y=None)` does not work if forecaster is fitted with a Series.

### ISSUE THREAD

**Issue by benHeid** [sktime/sktime#4766]
**Describe the bug**
I fitted a simple pipeline using a `pd.Series` as input for fit. Calling `predict_residuals()` lead to an exception.

**To Reproduce**
``` python
from sktime.datasets import load_longley
from sktime.forecasting.model_selection import temporal_train_test_split
from sktime.forecasting.sarimax import SARIMAX
from sktime.transformations.series.difference import Differencer

y, X = load_longley()
y_train, y_test, X_train, X_test = temporal_train_test_split(y, X)
pipe = Differencer() * SARIMAX()
pipe.fit(y=y_train, X=X_train, fh=[1, 2, 3, 4])
result = pipe.predict_residuals()
```
This raises the following exception

```
TypeError: y must have same type, dims, index as expected predict return. expected type <class 'pandas.core.series.Series'>, but found <class 'pandas.co
re.frame.DataFrame'>
```

Note the following command that should be identical to the above example works:

```
y, X = load_longley()
y_train, y_test, X_train, X_test = temporal_train_test_split(y, X)
pipe = Differencer() * SARIMAX()
pipe.fit(y=y_train, X=X_train, fh=[1, 2, 3, 4])
result = pipe.predict_residuals(y=y_train) # The difference is that here that y_train is passed to the parameter y.
```

**Expected behavior**
The default predict_residuals should also work if the estimator is fitted with a pd.Series. 

**Additional context**

The reason of this bug is that `self.y` is used in the default version, which is a pd.DataFrame. However, the return type of the `predict` is a `pd.Series`. 
I think the underlying is some inconsistencies in the fit method of `_base` line 334 to 338, where y_inner is passed to `_update_y_X`, which is a DataFrame and not a Series anymore. 

```python
X_inner, y_inner = self._check_X_y(X=X, y=y)

# set internal X/y to the new X/y
# this also updates cutoff from y
self._update_y_X(y_inner, X_inner)

```

I see two ways of fixing this bug:
* ensuring that self.y is of the same type, which is passed to fit and not a transformed version, would require either changing the return type of `check_X_y` or to pass `y` instead of `y_inner` to `_update_y_X`
* retransforming self.y to the type of predict or vise versa.

Any considerations or preferences on that?

**Versions**
sktime 19.2
python 3.9.16 (windows)

**Comment by fkiraly** [comment]
Confirmed on current main, python 3.11, windows
