### ISSUE TITLE
update year in copyright statements

### ISSUE THREAD

**Issue by yarnabrina** [sktime/sktime#4804]
As of this issue, `PyPI` shows the copyright as `2019 - 2020 The sktime developers` and `Read The Docs` shows the copyright as `2019 - 2021 (BSD-3-Clause License)`.

Given we are half way into 2023, the year should be updated. But I am unsure if it'd belong to developers or council or something else.

Relevant sources:

https://github.com/sktime/sktime/blob/73657f3ec16de96b5319049ef33d3ba5a99d02a2/LICENSE#L3

https://github.com/sktime/sktime/blob/73657f3ec16de96b5319049ef33d3ba5a99d02a2/docs/source/conf.py#L22

**Comment by fkiraly** [comment]
ah, yes - I am not a legal expert, but I think:

* there is no harm from this as the GitHub terms and conditions imply a release under the same license of any version
* the statement should be 2019 - present, as work on `sktime` is ongoing
