### ISSUE TITLE
[ENH] Extend tagging system to handle dependencies with alias

### ISSUE THREAD

**Issue by hazrulakmal** [sktime/sktime#4820]
Currently, estimator tagging system failed to handle soft dependency that has alias. For example, `AlignerDTW` (dtw-python/dtw) from the alignment module and #4580 (scikit-optimize/skopt). 

The current solution is to use a private validation utility function, `_check_soft_dependencies` before calling `super().__init__()` to handle the shortfall. 

**Solution Descriptions**
Other solution that I have in mind is to add an additional tag, *dependencies_alias* and extend the `_check_estimator_dep` to check for alias and pass the alias to `_check_soft_dependecies` that is used under the hood. A quick code solution may look like

```python
class Estimator(BaseEstimator):

    _tags = {
        ...
        "python_dependencies": ["numpy", "pandas", "scipy", "scikit-learn"],
        "python_dependencies_alias": {"scikit-learn": "sklearn"},
    }

    def __init__(...):
        ...

# Improvement to check_estimator_dep 
# since _check_soft_dependecies already handle the alias, check_estimator_dep should be easy to extend the case.

def _check_estimator_deps(obj, msg=None, severity="error"):
    compatible = True

    ... object iteration check ...
    ... python version check ...

    pkg_deps = obj.get_class_tag("python_dependencies", None)
    pck_alias = obj.get_class_tag("python_dependencies_alias", None)
    if pkg_deps is not None and not isinstance(pkg_deps, list):
        pkg_deps = [pkg_deps]
    if pkg_deps is not None:
        pkg_deps_ok = _check_soft_dependencies(*pkg_deps, severity=severity, obj=obj, package_import_alias=pck_alias)
        compatible = compatible and pkg_deps_ok

    return compatible
```

**Comment by fkiraly** [comment]
Yes, I think this is the way to deal with this!

Nb, I would locate the aliases with the `BaseObject` - since the aliases are not estimator specific but universal.

**Comment by hazrulakmal** [comment]
> I` would locate the aliases with the BaseObject

Noted

> Do you want to make a PR, in which you add the above code, and in which you remove the known workarounds?

Yup, absolutely. Will make a PR soon.
