### ISSUE TITLE
[BUG] make_forecasting_scorer and functools.partial don't mix.

### ISSUE THREAD

**Issue by davidgilbertson** [sktime/sktime#4827]
**Describe the bug**
I have a scoring function that is created using `functools.partial` and the scikit-learn `mean_squared_log_error` function. I'm wrapping this with `make_forecasting_scorer` to use with sktime. There's some logic in sktime that checks the parameters of this function, but there's a mismatch because of the partial application.

**To Reproduce**

```python
import functools
import pandas as pd
from sktime.performance_metrics.forecasting import make_forecasting_scorer
from sklearn.metrics import mean_squared_log_error

rmsle = functools.partial(mean_squared_log_error, squared=False)

scorer = make_forecasting_scorer(rmsle, name="RMSLE")

scorer.evaluate(pd.Series([1, 2, 3]), pd.Series([1, 2, 4]))
```

This produces the error:
```txt
Traceback (most recent call last):
  File "/home/davidg/.pycharm_helpers/pydev/pydevconsole.py", line 364, in runcode
    coro = func()
  File "<input>", line 10, in <module>
  File "/home/davidg/.virtualenvs/learning/lib/python3.10/site-packages/sktime/performance_metrics/forecasting/_classes.py", line 214, in evaluate
    out_df = self._evaluate(y_true=y_true_inner, y_pred=y_pred_inner, **kwargs)
  File "/home/davidg/.virtualenvs/learning/lib/python3.10/site-packages/sktime/performance_metrics/forecasting/_classes.py", line 582, in _evaluate
    params = {key: params[key] for key in func_params}
  File "/home/davidg/.virtualenvs/learning/lib/python3.10/site-packages/sktime/performance_metrics/forecasting/_classes.py", line 582, in <dictcomp>
    params = {key: params[key] for key in func_params}
KeyError: 'squared'
```

**Expected behavior**

**Additional context**
The code that raises the error:
https://github.com/sktime/sktime/blob/80907258adb7df7d3b7e0356c1264ee40bd7d986/sktime/performance_metrics/forecasting/_classes.py#L575-L578

`func_params` contains `squared`, but `params` doesn't. This code should allow for the fact that the `signature` params might not be in the `.get_params()` result.

**Versions**
<details>

</details>

**Comment by davidgilbertson** [comment]
I should add, the workaround is simple enough - don't use `partial`.
```py
def rmsle(y_true, y_pred):
    return mean_squared_log_error(y_true, y_pred, squared=False)


scorer = make_forecasting_scorer(rmsle, name="RMSLE")
```

**Comment by fkiraly** [comment]
confirmed on windows, python 3.11, current `main`

**Comment by fkiraly** [comment]
Temp fix is here: https://github.com/sktime/sktime/issues/4834

I think it would be better if the parameter `squared` becomes a parameter of the `__init__`, but not sure how to do that.
