### ISSUE TITLE
[DOC] `DateTimeFeatures` docstring should document all possible feature names for `manual_selection`

### ISSUE THREAD

**Issue by fkiraly** [sktime/sktime#4829]
The current docstring of the `DateTimeFeatures` transformer does not document all possible feature names for `manual_selection` (e.g., `"day_of_week"`).

As far as I see, this information cannot be gleaned from the current API documentation, only by inspecting the code in the `_calendar_dummies` private function.

Further, the exact values should be documented, e.g., does this result in an integer based column, and if yes, is it 0- or 1- based offset, to what? E.g., to Mondays or Sundays?

FYI @KishManani, @VyomkeshVyas

**Comment by Gigi1111** [comment]
If this issue is not assigned to anyone yet, I'd like to work on this. :)

**Comment by fkiraly** [comment]
all yours! I think the easiest way is to reverse engineer from the `_calendar_dummies` method.

**Comment by Abhay-Lejith** [comment]
Hello, I would like to work on this issue if possible. I am also new to open source so any tips would be really helpful.

**Comment by fkiraly** [comment]
of course! Here's our contribution guide:
https://www.sktime.net/en/latest/get_involved/contributing.html

Let us know if we can help!
If you need help with making a pull request or setting up your local developer setup, feel free to join the Friday meet-ups, we usually do screenshares for new contributors there.

**Comment by Abhay-Lejith** [comment]
The current docstring mentions feature names like 'month_of_year' and 'day_of_month' but these are not present in the `_calendar_dummies ` method. Is this an error or am I missing something here?

**Comment by fkiraly** [comment]
> Is this an error or am I missing something here?

Could be an error - have you tried using them and it breaks? If yes, that's a bug (in this case, congratulations, you can get the `bug` badge!)

**Comment by Abhay-Lejith** [comment]
Never mind, I tried using said feature names and the code works returning the corresponding dataframe/series with correct values. I'll proceed with documenting all the features names with their return values.

**Comment by Abhay-Lejith** [comment]
@fkiraly it seems like the code reviewer on my PR has been inactive on this repo for the past few months. Could you please perhaps take a look at it and do the needful.

**Comment by fkiraly** [comment]
> Could you please perhaps take a look at it and do the needful.

Sure! @danbartl is on a break currently, but I pinged the other file authors which should be active.
