### ISSUE TITLE
[BUG] `evaluate` subroutine `_split` splits multiindex dataframes incorrectly when `X` has more timepoints than `y`

### ISSUE THREAD

**Issue by felipeangelimvieira** [sktime/sktime#4842]
**Describe the bug**
`forecasting.model_evaluation._functions._split` uses `y` integer-location to select the rows of X. However, if the dataframes are multiindex and X has more timepoints than y, it selects rows of X corresponding to the wrong dates.  This affects `evaluate` when using the splitters to backtest a forecasting model.

**To Reproduce**

```python

from sktime.transformations.hierarchical.aggregate import Aggregator
from sktime.forecasting.model_selection import ExpandingWindowSplitter
from sktime.forecasting.model_evaluation._functions import _split
from sktime.utils.validation.series import check_equal_time_index
import pandas as pd
import numpy as np

# A multiindex with level 0 with as "A", and "B" as dates from 2020-01-01 to 2020-01-10
df = pd.DataFrame(
    index=pd.MultiIndex.from_product(
        [["A", "B"], pd.date_range("2020-01-01", "2020-01-10").to_period("D")]
    ),
    data={"target": np.arange(20) % 10},
).sort_index()
df = Aggregator().fit_transform(df)

y = df[df.index.get_level_values(-1) < "2020-01-08"]
X = df.copy()
cv = ExpandingWindowSplitter(initial_window=2, fh=[1], step_length=1)


train, test = next(cv.split(y))
y_train, y_test, X_train, X_test = _split(y=y, X=X, train=train, test=test)
check_equal_time_index(y_train, X_train)
check_equal_time_index(y_test, X_test)

```

**Expected behavior**

_split should have returned y/X pairs with the same time index.

**Additional context**

Although this error can be circumvented by filtering the dates of X before passing it to evaluate, it's common to have an X dataframe with future values and maybe this shouldn't cause trouble when backtesting. If this is the expected behaviour, the error message is not clear.

**Versions**
<details>

System:
    python: 3.8.16 (default, Dec  7 2022, 01:36:11)  [Clang 14.0.0 (clang-1400.0.29.202)]
executable: /Users/felipe/Library/Caches/pypoetry/virtualenvs/app-2GAkMlzy-py3.8/bin/python
   machine: macOS-13.4.1-x86_64-i386-64bit

Python dependencies:
          pip: 23.0.1
       sktime: 0.19.2
      sklearn: 1.2.2
       skbase: 0.4.6
        numpy: 1.22.3
        scipy: 1.7.3
       pandas: 1.3.5
   matplotlib: 3.7.1
       joblib: 1.2.0
  statsmodels: 0.14.0
        numba: None
     pmdarima: 2.0.3
      tsfresh: None
   tensorflow: None
tensorflow_probability: None

</details>

**Comment by fkiraly** [comment]
That is odd - I never spotted or questioned this, but my immediate question is now, why are we not using the `split` of the splitters?

Seems like it was added relatively recently, by @chris-l, any insights?

**Comment by felipeangelimvieira** [comment]
I believe that the splitters don't have a method to split both X and y at the same time, hence the need of another function that receive the integer locations of train/test and iloc them both from X and y. 

Maybe BaseSplitter could have this feature, and could locate by date instead of integer position?

**Comment by fkiraly** [comment]
Hm, very interesting!

In this situation imo it is not actually clear what the "should" state should be.

It is of course clear what *your*  should state is, but I'm worrying about not making too strong assumptions on how the X and the y-splits are related.

You can imagine cases where `X_test/train` and `y_test/train` indices should be equal, or not.

* case 1: `X` is never known in the future and regularly sampled. In this case the `X` and `y` splits are expected to be the same.
* case 2: `X` is always known in the future. In this case, `X_train = X_test = X`, and only `y` should be split.
* case 3-100: only some variables of `X` are known in the future, others not. `y` should be split.
* case 101-1000: we know `X` in the future, but only a certain time ahead (e.g., in case of a 1 week planning horizon). `y` should be split.

**Comment by fkiraly** [comment]
I've thought seriously about this issue and it has given me a headache.

Things I've discarded:

* `y` / `X` split pairs always should have the same time index (that would exclude the case of `X` known in the future)
* `X` always being everything
* more generally: the `X` splits being uniquely determined by `y` split index

What this seems to imply is:

*there should be an option of specifying the `X`-splitter` independently from the `y`-splitter* - with a sensible default.

* the sensible default could be: `X`-split-index = `y`-split-index for train, `X`-split-index = `y`-train-plus-test, in predict/test.
* from a software engineering perspective this is how we could achieve it:
    * `evaluate` gets another argument, `cv_X`. If not passed, it defaults as above.
    * the default would be achieved by a compositor around splitters, `XcvFromYcvAllVarsKnown`
    * the user can also specify variables that are known in the future, in this case `cv_X` would be an iterable or `pd.Index` with those.
    * internally, this is achieved by a splitter compositor, `XcvFromYcvSomeVarsKnown(vars_known)`. The user can also construct this.

What do you think, @felipeangelimvieira?

**Comment by fkiraly** [comment]
reported behaviour is confirmed on windows, current `main`, python 3.11.

**Comment by fkiraly** [comment]
FYI @tcuongd, @hazrulakmal, @marrov due to the benchmarking topic.

**Comment by felipeangelimvieira** [comment]
I'd like to take a step back to ensure we're on the same page. Even after creating different cv strategies for X and y, I think there's a key aspect of sktime's splitters that might need to be addressed:
_Shouldn't the Splitters return dates/timepoints instead of integer positions_? I understand that scikit-learn's splitters return the integer position, but in the context of time series forecasting, using iloc could potentially lead to issues such as the bug in evaluate.

As I'm fairly new to this package, I'm unsure if there has been a previous discussion on this matter...

**Comment by fkiraly** [comment]
> Shouldn't the Splitters return dates/timepoints instead of integer positions?
> I'm unsure if there has been a previous discussion on this matter...

Not previous discussion, but I have also thought about this think `iloc` references make more sense, since a "split" is always applied to a data set.

Having said that, all splitters have both methods for `iloc` and `loc` indices - there's `split` and `split_loc`.
`loc` references can be easily obtained from `iloc` references given the data set, but not the other way round.

Regarding the bug, it is always possible to obtain `loc` references and apply them to the second object, but I think that's not a conceptual fix.

**Comment by fkiraly** [comment]
> Shouldn't the Splitters return dates/timepoints instead of integer positions? I understand that scikit-learn's splitters return the integer position, but in the context of time series forecasting, using iloc could potentially lead to issues such as the bug in evaluate.

But I think I see the direction of thinking, can you confirm?

You are saying:

* we could be using the splitter directly instead of the `_split` method
* and we should be using the `loc` indices to subset `X` instead of the logic in `_split`, that would fix the bug in your use case
* therefore the splitter should return `loc` indices in `split`

I agree with the first two points but not the third. But, as sasid, all splitters already return `loc` indices in `split_loc`, so we can simply use that instead of changing the interface of the splitters!

**Comment by felipeangelimvieira** [comment]
perfect! I totally agree with you. The 3rd point would be a huge change.
Do you need help fixing the `evaluate` function?

**Comment by fkiraly** [comment]
> Do you need help fixing the `evaluate` function?

That would be appreciated! I'm busy at work and might not have a lot of time until the release, so help would be great!

My work on this issue so far is here:
https://github.com/sktime/sktime/pull/4851
https://github.com/sktime/sktime/pull/4861
https://github.com/sktime/sktime/pull/4862

Your eyes would be appreciated on #4861, i.e., why does this fail after the refactor. My suspicion is, internally it wants the union of `X_train` and `X_test` for testing, so it might be fixable by combining it with #4862.

**Comment by fkiraly** [comment]
@felipeangelimvieira, I have been trying to construct a minimal failing example that does not use private functions, to certify for the bug and the fix. I ended up with this, based on your report.

Would appreciate if you could have a look to see whether (a) this is what you originally have been trying to do and (b) whether this is minimal.

```python

from sktime.transformations.hierarchical.aggregate import Aggregator
from sktime.forecasting.model_selection import ExpandingWindowSplitter
from sktime.forecasting.model_evaluation import evaluate
from sktime.forecasting.naive import NaiveForecaster
import pandas as pd
import numpy as np

# A multiindex with level 0 with as "A", and "B" as dates from 2020-01-01 to 2020-01-10
df = pd.DataFrame(
    index=pd.MultiIndex.from_product(
        [["A", "B"], pd.date_range("2020-01-01", "2020-01-10").to_period("D")]
    ),
    data={"target": np.arange(20) % 10},
).sort_index()
df = Aggregator().fit_transform(df)

y = df[df.index.get_level_values(-1) < "2020-01-08"]
X = df.copy()
cv = ExpandingWindowSplitter(initial_window=2, fh=[1], step_length=1)

f = NaiveForecaster()

evaluate(f, cv, y, X, error_score="raise")
```
