### ISSUE TITLE
[BUG] prophet seasonality condition_name columns should not be added as extra regressors

### ISSUE THREAD

**Issue by gmweaver** [sktime/sktime#4864]
**Describe the bug**

When adding regressors [here](https://github.com/sktime/sktime/blob/main/sktime/forecasting/base/adapters/_fbprophet.py#L106), all columns in `X` are added as regressors. I believe this should exclude any columns listed in `condition_name` of custom seasonalities (appears to be the case when using Prophet directly). 

Since regressors may be standardized, you can end up with a column type that breaks logic in underlying prophet seasonality features generator.

`TypeError: ufunc 'invert' not supported for the input types, and the inputs could not be safely coerced to any supported types according to the casting rule ''safe''`

**To Reproduce**

Modified Prophet example in documentation to include a custom seasonality with a `condition_name`.

```python
import random

from sktime.datasets import load_airline
from sktime.forecasting.fbprophet import Prophet

y = (
    load_airline()
    .to_timestamp(freq="M")
    .to_frame()
    .assign(test_condition=lambda df: random.choices([True, False], k=len(df)))
)

forecaster = Prophet(
    seasonality_mode="multiplicative",
    n_changepoints=int(len(y) / 12),
    add_country_holidays={"country_name": "Germany"},
    yearly_seasonality=True,
    add_seasonality={
        "name": "testing",
        "period": 7,
        "fourier_order": 20,
        "condition_name": "test_condition",
    },
)

forecaster.fit(y=y["Number of airline passengers"], X=y[["test_condition"]])
```

**Expected behavior**

Same behavior as using Prophet directly, columns used for `condition_name` are not added as regressors.

**Additional context**

N/A

**Versions**

0.20.0

**Comment by fkiraly** [comment]
Yes, seems like a bug in the interface - FYI @tcuongd

**Comment by fkiraly** [comment]
@gmweaver, the fix seems simple - just modifying that line.

Would you like to make a PR?

I wonder how we could test this to ensure it doesn't revert by accident later.
