### ISSUE TITLE
[BUG] `FeatureSelection.fit` always triggers `DataConversionWarning`

### ISSUE THREAD

**Issue by hliebert** [sktime/sktime#4881]
**Describe the bug**
Using FeatureSelection() in a pipeline triggers a warning.

```
DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)
```

**To Reproduce**
Just include FeatureSelection() in a pipeline.

```python
import numpy as np
from sklearn.ensemble import RandomForestRegressor
from sklearn.preprocessing import MinMaxScaler
from sktime.datasets import load_longley
from sktime.forecasting.base import ForecastingHorizon
from sktime.forecasting.compose import ForecastingPipeline, make_reduction
from sktime.transformations.series.adapt import TabularToSeriesAdaptor
from sktime.transformations.series.feature_selection import FeatureSelection

y, X = load_longley()
horizon = ForecastingHorizon(np.arange(1, 3), is_relative=True)

random_forest = RandomForestRegressor()
reduction_forecaster = make_reduction(random_forest, window_length=3, strategy="direct", windows_identical=False)

pipe = ForecastingPipeline(
    [
        ("min_max_scaler", TabularToSeriesAdaptor(MinMaxScaler())),
        ("feature_selector", FeatureSelection()),
        ("reduction_forecaster", reduction_forecaster),
    ]
)

pipe.fit(y, X, fh=horizon)
```

**Expected behavior**
No warnings.

**Versions**
<details>
System:
    python: 3.8.10 (tags/v3.8.10:3d8993a, May  3 2021, 11:48:03) [MSC v.1928 64 bit (AMD64)]
executable: C:\Program Files\python-3.8.10\python.exe
   machine: Windows-10-10.0.19044-SP0
Python dependencies:
          pip: 21.1.1
       sktime: 0.20.0
      sklearn: 1.2.2
       skbase: 0.4.6
        numpy: 1.23.5
        scipy: 1.10.1
       pandas: 1.5.3
   matplotlib: 3.7.2
       joblib: 1.3.1
  statsmodels: 0.14.0
        numba: 0.57.1
     pmdarima: 2.0.3
      tsfresh: None
   tensorflow: None
tensorflow_probability: None
</details>

**Comment by fkiraly** [comment]
Thanks for reporting!
The warning indicates directly what to do as a fix: https://github.com/sktime/sktime/pull/4883
