### ISSUE TITLE
[BUG] 60 seconds per core of unnecessary delay for pytest --collect-only execution 

### ISSUE THREAD

**Issue by tarpas** [sktime/sktime#4900]
**Describe the bug**
I followed the contributor installation instructions and executed `python -m pytest -n0 --collect-only` and the command took 1m30s to execute on may fairly fast computer. This is also related to: https://github.com/sktime/sktime/issues/2890#issuecomment-1188833581 and a little to: https://github.com/sktime/sktime/issues/2530

Upon profiling 60s of that was spent on line
https://github.com/sktime/sktime/blob/b61f2de7dc792db7d437f65a2dd65f51832011b4/sktime/utils/_testing/scenarios.py#L265
creating a string which is then thrown away.

![test4](https://github.com/sktime/sktime/assets/135344/35e44d01-f068-4035-b4db-48d682f96a8a)

**To Reproduce**
```
python -m pytest -n0 --collect-only
```

**Expected behavior**
Let's not create msg until it's needed. 
```
diff --git a/sktime/utils/_testing/scenarios.py b/sktime/utils/_testing/scenarios.py
index 449889d4..0949f0c6 100644
--- a/sktime/utils/_testing/scenarios.py
+++ b/sktime/utils/_testing/scenarios.py
@@ -262,11 +262,9 @@ def _check_dict_of_dict(obj, name="obj"):
     ------
     TypeError if obj is not dict of dict, with str keys
     """
-    msg = f"{obj} must be a dict of dict, with str keys"
-    if not isinstance(obj, dict):
-        raise TypeError(msg)
-    if not np.all([isinstance(x, dict) for x in obj.values()]):
-        raise TypeError(msg)
-    if not np.all([isinstance(x, str) for x in obj.keys()]):
-        raise TypeError(msg)
+
+    if not (isinstance(obj, dict) and
+            np.all([isinstance(x, dict) for x in obj.values()]) and
+            np.all([isinstance(x, str) for x in obj.keys()])):
+        raise TypeError(f"{obj} must be a dict of dict, with str keys")
     return obj
```  

**Additional context**

**Versions**
System:
    python: 3.9.16 | packaged by conda-forge | (main, Feb  1 2023, 21:38:11)  [Clang 14.0.6 ]
executable: /Users/tibor/miniforge3/envs/sktime-dev/bin/python3
   machine: macOS-13.3.1-arm64-arm-64bit

Python dependencies:
          pip: 23.2
       sktime: 0.20.1
      sklearn: 1.1.3
       skbase: 0.4.6
        numpy: 1.22.4
        scipy: 1.11.1
       pandas: 1.5.3
   matplotlib: 3.7.1
       joblib: 1.3.0
  statsmodels: 0.14.0
        numba: 0.57.1
     pmdarima: 1.8.5
      tsfresh: 0.20.0
   tensorflow: 2.13.0
tensorflow_probability: None

**Comment by fkiraly** [comment]
THANKS!

I'm puzzled though why this eats so much time!
Is there an easy explanation so I can understand what's going on?

There are so many places in `sktime` where we create messages like these, so now I'm suddenly very concerned...

**Comment by tarpas** [comment]
> I'm puzzled though why this eats so much time! Is there an easy explanation so I can understand what's going on?
> 
> There are so many places in `sktime` where we create messages like these, so now I'm suddenly very concerned...
I'm sure there is an explanation, I just don't have a great and clear one for you :). I assume the pandas dataframes going into the f string are big and __repr__ function of the dataframe is not that optimizied for high performance. (plus creating a string from millions of other small strings (and allocating the memory for them) in Python is slow)

If you struggle to read the profiling output (as I did at first) I'll be glad to  show you around :). 

In general and for the future, you should probably use profiler whenever you're not happy with performance. 

Also there is one new continuous benchmarking tool. The author will be at Europython, so if you're concerned about performance monitoring the performance of the tests then let's also talk to him: 
https://codspeed.io/

**Comment by fkiraly** [comment]
@art049, interesting! Are you around at EuroPython? I cannot find you on the discord.

Indeed it would be nice to have some key performances monitored in the CI, due to the nesting in the framework logic where minimal changes such as the one you unveiled (introducing an inconspicuous checker) may cause drops in performance.

**Comment by fkiraly** [comment]
according to the profiler, the second worst issue in the pytest collection are the fit/predict statements directly in the `test_probabilistic_metrics` module which are always executed when imported!

This is probably also called each time when `all-estimators` crawls the library, contributing to time lost in the fixture generation stage.

The fit/predict should go into fixtures or directly in the tests.

**Comment by fkiraly** [comment]
If we get rid of this, we are down to ca 10 sec then?

**Comment by tarpas** [comment]
Cool, so this seems to be really valuable. I'm glad.

> FYI, the full command afaik to generate the profile svg is
> 
> `py-spy record -o profile.svg -- python -m pytest -n0 --collect-only`

Notice that the executed command is always included on top of the generated svg chart :)

> 
> the `msg` should have contained `name` rather than `obj`!
> 

So what's the plan with the easy fixes? Feel free to close my PR and do your own fixes.

**Comment by fkiraly** [comment]
> So what's the plan with the easy fixes? Feel free to close my PR and do your own fixes.

I've committed that to your PR, if you don't mind - this gives the credit the right way round, and is also a sensible combination of fixes imo.

**Comment by tarpas** [comment]
> I've committed that to your PR, if you don't mind - this gives the credit the right way round, and is also a sensible combination of fixes imo.

I saw afterwards, sure, thanks! So I'm done. Let me know if I should do anything else.

**Comment by fkiraly** [comment]
Thanks a lot! If you're in the flow, I've been having a hard time with profiling this example:

https://github.com/sktime/sktime/issues/3224#issuecomment-1383145512

I've narrowed it down and have a direction of attack that I'll try out on the sprint week-end, but would be appreciative of another pair of eyes.
