### ISSUE TITLE
[ENH] Adapter to pytorch-forecasting

### ISSUE THREAD

**Issue by benHeid** [sktime/sktime#4923]
Analog to #2860 and #1624, we should discuss if we write an adapter for pytorch-forecasting.

Pros:
* Implements multiple state of the art DL forecasters.

Cons:
* Not sure if it is useful to support multiple frameworks that basically do the same (e.g. gluonts, pytorch-forcasting, ...)

**Comment by pranavvp16** [comment]
I have started to work on pytorch-forecasting adapter for sktime to support models from pytorch-forecasting. My question was, There is no mention of any parameter like `h` or `fh`, what I found that looks similar to `ForecastingHorizon` is the parameter `max_prediction_lenght` [here](https://pytorch-forecasting.readthedocs.io/en/latest/data.html). So will passing the integer obtained from fh.to_relative()[-1], is the correct approach or the parameter `max_prediction_lenght` denotes something else. This is inspired from neuralforecast adapter where `fh.to_relative()[-1]` is passed to param `maximum_forecast_horizon` param in [neuralforecast](https://github.com/pranavvp16/sktime/blob/main/sktime/forecasting/base/adapters/_neuralforecast.py#L222)

**Comment by fkiraly** [comment]
Yes, I suppose that is the right way. Then, at th end, you may have to subset the result to `fh`.

**Comment by Xinyu-Wu-0000** [comment]
Comment for assignment.

**Comment by Xinyu-Wu-0000** [comment]
About probabilistic forecast of pytorch-forecasting models:

DeepAR, NHiTS and TemporalFusionTransformer can perform quantile forecast, but NBeats can not.

If we want to perform quantile forecast, `QuantileLoss` has to be used in `fit`.

After checking the source code of pytorch-forecasting, I found the way to use different quantiles in `fit` and `predict` by passing `mode_kwargs={"use_metric": False, "quantiles": [0.1, 0.5, 0.9]}` to overwrite the quantiles in `QuantileLoss`. However, I am not sure whether it's correct mathematically in sktime perspective. In pytorch-forecasting, a function called `to_quantiles` is used to convert network prediction into a quantile prediction. Is it real probabilistic forecast?

<details>
<summary>code to test quantile forecast in pytorch-forecasting</summary>

```py
import numpy as np
import pandas as pd
from lightning.pytorch import Trainer
from pytorch_forecasting import (
    DeepAR,
    MultiLoss,
    NBeats,
    NHiTS,
    QuantileLoss,
    TemporalFusionTransformer,
    TimeSeriesDataSet,
)

model_class = DeepAR
max_prediction_length = 2

n_timeseries = 100
time_points = 100
data = pd.DataFrame(
    data={
        "target": np.random.rand(time_points * n_timeseries),
        "time_varying_known_real_1": np.random.rand(time_points * n_timeseries),
        "time_idx": np.tile(np.arange(time_points), n_timeseries),
        "group_id": np.repeat(np.arange(n_timeseries), time_points),
    }
)

print(data)

training_cutoff = data["time_idx"].max() - max_prediction_length
training_dataset = TimeSeriesDataSet(
    data=data[lambda x: x.time_idx <= training_cutoff],
    time_idx="time_idx",
    target="target",
    group_ids=["group_id"],
    time_varying_unknown_reals=["target"],
    time_varying_known_reals=(
        ["time_varying_known_real_1"] if model_class != NBeats else []
    ),
    max_prediction_length=max_prediction_length,
)

validation_dataset = TimeSeriesDataSet.from_dataset(
    training_dataset,
    data,
    stop_randomization=True,
    predict=True,
)

training_data_loader = training_dataset.to_dataloader(train=True)

validation_data_loader = validation_dataset.to_dataloader(train=False)

forecaster = model_class.from_dataset(
    training_dataset,
    log_val_interval=-1,
    # output_size=7,
    # loss=QuantileLoss(),
)

pytorch_trainer = Trainer(
    accelerator="cpu",
    max_epochs=5,
    min_epochs=2,
    limit_train_batches=10,
)

pytorch_trainer.fit(
    forecaster,
    train_dataloaders=training_data_loader,
    val_dataloaders=validation_data_loader,
)

best_model_path = pytorch_trainer.checkpoint_callback.best_model_path
best_model = model_class.load_from_checkpoint(best_model_path)
predictions = best_model.predict(
    validation_data_loader,
    mode="quantiles",
    mode_kwargs={"use_metric": False, "quantiles": [0.1, 0.5, 0.9]},
)
print(predictions)
print(predictions.size())
```

</details>

<details>
<summary>`to_quantiles` function in `BaseModel` of pytorch-forecasting</summary>

```py
    def to_quantiles(self, out: Dict[str, Any], use_metric: bool = True, **kwargs):
        """
        Convert output to quantiles using the loss metric.

        Args:
            out (Dict[str, Any]): output of network where "prediction" has been
                transformed with :py:meth:`~transform_output`
            use_metric (bool): if to use metric to convert for conversion, if False,
                simply take the quantiles over ``out["prediction"]``
            **kwargs: arguments to metric ``to_quantiles`` method

        Returns:
            torch.Tensor: quantiles of shape batch_size x timesteps x n_quantiles
        """
        # if samples are output directly take quantiles
        if not use_metric:
            # todo: support classification
            if isinstance(self.loss, MultiLoss):
                out = [
                    Metric.to_quantiles(loss, out["prediction"][idx], quantiles=kwargs.get("quantiles", loss.quantiles))
                    for idx, loss in enumerate(self.loss)
                ]
            else:
                out = Metric.to_quantiles(
                    self.loss, out["prediction"], quantiles=kwargs.get("quantiles", self.loss.quantiles)
                )
        else:
            try:
                out = self.loss.to_quantiles(out["prediction"], **kwargs)
            except TypeError:  # in case passed kwargs do not exist
                out = self.loss.to_quantiles(out["prediction"])
        return out
```

</details>

@benHeid @fkiraly Could you kindly give some suggestions?
