### ISSUE TITLE
[DOC] Developer documentation - confusions between development version install and developer setup

### ISSUE THREAD

**Issue by julia-kraus** [sktime/sktime#4933]
#### Describe the issue linked to the documentation

I'm a developer who'd like to start contributing to sklearn. When setting up my developer setup, I stumbled over the documentation
https://www.sktime.net/en/stable/installation.html

I now figured out that there are three different installations:

1. Install a release version, which is explained clearly
2. Install a developer version (without wanting to contribute, so no fork necessary)
3. Install a whole developer setup (with creating your own fork)

#### Suggest a potential alternative/fix
It would be helpful to define these three installation cases in the beginning. And following have these three cases as headlines.
It would give the doc more structure.

**Comment by fkiraly** [comment]
Yes, excellent point!

Looking at it, I agree with you, it is not entirely clear that end state for developer install and dev setup are different.

In fact, getting from a developer install to the dev setup (with fork) can be more confusing than starting with the dev setup in the first place, as it requires pointing the local clone to the fork, from the origin.

Another point that was pointed out by a participant of the community days, the instructions are also inconsistent on whether you need `all_extras` or not, for the developer setup. It is perhaps even better not to install all soft dependencies for devlopment, as these slow down the tests (and test collection) considerably.

**Comment by julia-kraus** [comment]
Hello! I would like to take that issue as my starting issue. So we should recommend the installation without `all_extras` and make a side note for the extras? In which case should we recommend the all_extras?

**Comment by fkiraly** [comment]
Yes, I would start without `all_extras` as the base requirement.

`all_extras` should be recommended for running the full test suite, including all soft dependencies - but will not be required for most developer scenarios.
