### ISSUE TITLE
[DOC] Developer installation - conda environment

### ISSUE THREAD

**Issue by Verogli** [sktime/sktime#4934]
#### Describe the issue linked to the documentation

I followed the installation instruction on how to set up the development environment using conda. The documentation proposes a pip install command including the installation of all soft dependencies with the attribute "all_extras" 
(`pip install -e .[all_extras,dev]`).

This is in not needed for every kind of contribution. Following the steps in the section "Development versions" , no attribute "all_extras" proposed for the pip install command 
(`pip install --editable .[dev]`).

#### Suggest a potential alternative/fix

To gain more clarity and consistency, the documentation should use the same pip install command for both types of virtual development environments -  created with pipenv or conda.
Probably it would be helpful to specify in the documentation, in which cases "all_extras" need to be installed.

**Comment by fkiraly** [comment]
Yes, agreed!

I would actually not make `all_extras` a requirement for the default setup install, but mention "if you also want soft dependencies" (option to install them one-by-one, or all of them)

I think this is a good first issue for the documentation!
