### ISSUE TITLE
[BUG] SingleWindowSplitter failed to return iloc reference split for hierachical datatypes

### ISSUE THREAD

**Issue by hazrulakmal** [sktime/sktime#4972]
**Describe the bug**

`SingleWindowSplitter` encounters the error below when a hierarchical datatype is passed, even with the simplest example. This raises a question of whether the splitters are actually being tested for hierarchical mtype format. The [docstring](https://www.sktime.net/en/stable/api_reference/auto_generated/sktime.forecasting.model_selection.SingleWindowSplitter.html#sktime.forecasting.model_selection.SingleWindowSplitter.split) indicates that one can pass hierarchical mtype into them.

**To Reproduce**

```python
from sktime.utils._testing.hierarchical import _make_hierarchical
from sktime.forecasting.model_selection import SingleWindowSplitter

y_hierarchical= _make_hierarchical(hierarchy_levels=(2, 3), min_timepoints=12, max_timepoints=12, random_state=0)
splitter = SingleWindowSplitter(fh=[1,2], window_length=10)
list(splitter.split(y_hierarchical)) 
```

Output
```
TypeError: unsupported operand type(s) for *: 'NoneType' and 'int'
```

**Full Traceback**
<details>

Traceback (most recent call last):
File "c:\Users\hazru\Desktop\github\sktime\sktime\_contrib\temp\test-forecastingcv.py", line 6, in <module>
list(splitter.split(y_synthetic))
File "C:\Users\hazru\Desktop\github\sktime\sktime\forecasting\model_selection\_split.py", line 386, in split
for train, test in split(y_index):
File "C:\Users\hazru\Desktop\github\sktime\sktime\forecasting\model_selection\_split.py", line 434, in _split_vectorized
train_inst, test_inst = zip(*split_inst)
File "C:\Users\hazru\Desktop\github\sktime\sktime\forecasting\model_selection\_split.py", line 1325, in _split
window_length = y.freq * window_length
</details>

**Expected behavior**

It should return iloc references to a train & test split of y_hierarchical

**Additional context**

**Versions**
<details>

</details>

**Comment by hazrulakmal** [comment]
Update: It turns out that the problem lies on misalignment of datatype argument inputs. if **y** is a **datetime** datatype and **window_length** is an **int**, `SingleWindowSplitter` will use information about y index `freq` so that it can identifies correctly where to split the y (through addition/subtraction of datetime datatype) However, if the freq is not available (due to unintended loss during data preprocessing into sktime datatypes which is what happen in `_make_hierachical` or it's not being declared anywhere in the first place) then `SingleWindowSplitter` will fail and throw an error as above. 

Solutions
1. Infer `freq` of the series using `pd.infer_freq` function and add a warning message that the inference is being done internally.

**Comment by fkiraly** [comment]
That is strange - why is the frequency even required for the SingleWindowSplitter? Logic-wise, it shouldn´t be, as the logic is just a greater/smaller comparison.

**Comment by hazrulakmal** [comment]
When the user passes y with datetime index and window_length as an integer, the splitter requires the frequency to get the training and test window. To get this, it needs to find the start of a window from a cutoff point, subtraction is required. However, datetime cannot be subtracted from an integer (timestamp - int) because there is no information about the unit of the integer, such as hour or day.

**Comment by fkiraly** [comment]
Hm, I see.

One thing I'm realizing, I have seen this problem so many times - time stamp or index minus integer.

We have also been forced to move to `pandas.Index`-based time stamps, since `freq` was dropped from time-like elements and is only in the index since a recent `pandas` version.

Would it be beneficial to write a utility for adding offset to index, for any sensible combination of time and int-like?

May be out of scope for solving this bug though.

**Comment by hazrulakmal** [comment]
a workaround for the problem above is to use time-like arguments for the splitter as follow

```python
import pandas as pd
from sktime.utils._testing.hierarchical import _make_hierarchical
from sktime.forecasting.model_selection import SingleWindowSplitter

fh = pd.Timedelta(2, unit="D")  # or offsets format pd.offsets.Day(2)
window_length = pd.Timedelta(10, unit="D") # or offsets format pd.offsets.Day(10)
y_hierarchical= _make_hierarchical(hierarchy_levels=(2, 3), min_timepoints=12, max_timepoints=12, random_state=0)
splitter = SingleWindowSplitter(fh=fh, window_length=window_length )
list(splitter.split(y_hierarchical)

**Comment by hazrulakmal** [comment]
> Would it be beneficial to write a utility for adding offset to index, for any sensible combination of time and int-like?

does the utility function created in #5009 account for it?
