### ISSUE TITLE
[BUG] Wrong result for `predict_residuals` of`TransformedTargetForecaster` on training data

### ISSUE THREAD

**Issue by benHeid** [sktime/sktime#4993]
**Describe the bug**
If `predict_residuals` is called  of a `TransformedTargetForecaster` on the training data, the results seems to be wrong. My guess it that internally, the  `self._y` of the `TransformedTargetForecaster` is used to calculate the residuals instead of the transformed target data. 

**To Reproduce**

```python
from datasets import load_longley
from forecasting.model_selection import temporal_train_test_split
from forecasting.sarimax import SARIMAX
from transformations.series.difference import Differencer

method = "predict_residuals"
y, X = load_longley()
y_train, y_test, X_train, X_test = temporal_train_test_split(y, X)
pipe = Differencer() * SARIMAX()
pipe.fit(y=y_train.to_frame(), X=X_train, fh=[1, 2, 3, 4])
result = pipe.predict_residuals()
result_test = pipe.predict_residuals(y=y_test, X=X_test)
```

In this example, result_test looks like residuals. However, result is far higher and not the residuals.

**Expected behavior**

Also on the training data the residuals should be calculated of the TransformedTargetForecaster applied on the training data.

**Comment by fkiraly** [comment]
My suspicion is that this combines two issues:

* `predict_residuals` without args computes the in-sample residuals on `y_train`
* `Differencer` may produce counterintuitive results in-sample https://github.com/sktime/sktime/issues/4965

As said, this is an unverified guess.

**Comment by benHeid** [comment]
Indeed, there is a problem with the `Differencer`. Additionally, I just realised that when calling `predict_residuals` no `inverse_transform` is executed. I suppose that this is intended. However, perhaps it would be worth a remark somewhere in the Docs.

**Comment by fkiraly** [comment]
>  I just realised that when calling predict_residuals no inverse_transform is executed. I suppose that this is intended

I don't get that - how is it not executed? Should `predict_residuals` not call `predict` which calls `_predict` which calls `inverse_transform`?

**Comment by benHeid** [comment]
> > I just realised that when calling predict_residuals no inverse_transform is executed. I suppose that this is intended
> 
> I don't get that - how is it not executed? Should `predict_residuals` not call `predict` which calls `_predict` which calls `inverse_transform`?

Sorry, I confused myself, because I implemented it wrong in the graphpipeline... Everything is correctly called. The `inverse_transform` is called and the `_predict` of the inner estimator.

**Comment by fkiraly** [comment]
so, is this still a problem then or can we close it?

**Comment by benHeid** [comment]
We can close if #4998 is merged

**Comment by fkiraly** [comment]
but isn't #4998 fixing #4965, and this issue is also due to #4965?

**Comment by benHeid** [comment]
> but isn't #4998 fixing #4965, and this issue is also due to #4965?

Only partial.... It seems that there is another problem with having multiple lags. I will investigate it..
