### ISSUE TITLE
[BUG] MCDCNNClassifier.fit runs only 1 training epoch

### ISSUE THREAD

**Issue by pseudomo** [sktime/sktime#4996]
Despite n_epochs being set to 200, only one training epoch will be executed here:

```python
from sktime.classification.deep_learning.mcdcnn import MCDCNNClassifier
from keras.losses import binary_crossentropy

model = MCDCNNClassifier(n_epochs=200, batch_size=64, loss=binary_crossentropy, random_state=42, metrics=['binary_accuracy'])
model.fit(x_train, y_train)
```

The problem is that model.n_epochs is not passed to self.model_.fit in MCDCNNClassifier._fit (mcdcnn.py):

```python
    def _fit(self, X, y):
        ...

        self.history = self.model_.fit(
            X,
            y_onehot,
            epochs=self.n_epochs, **#<<<-----------------THIS LINS IS MISSING #**
            batch_size=self.batch_size,
            verbose=self.verbose,
            callbacks=self.callbacks_,
        )

        return self
```

**Comment by fkiraly** [comment]
Thanks for the report!

The fix seem simple, and you've identified the problem - so, would appreciate a fix PR!

**Comment by pseudomo** [comment]
@fkiraly ,
I've submitted the pull request

**Comment by fkiraly** [comment]
@pseudomo, I think you never made a PR to sktime proper, but only to your personal fork?

Could you kindly make a PR to sktime?

**Comment by pseudomo** [comment]
> @pseudomo, I think you never made a PR to sktime proper, but only to your personal fork?
> 
> Could you kindly make a PR to sktime?

@fkiraly, I am sorry, I've accidentally created the pull request to my own fork repo
Please, see the new pull request
