### ISSUE TITLE
[DOC] in `ForecastingGridSearchCV` and forecaster tuner docstrings, improve description of `scoring` parameter

### ISSUE THREAD

**Issue by TeoSkondras** [sktime/sktime#5020]
#### In ForecastingGridSearchCV, it is not well specified what the scoring attribute possible values are...

For example:

gscv = ForecastingGridSearchCV(
    forecaster=pipe_x,
    param_grid=[{
        "forecaster__forecaster__estimator__n_components": [1,2,3,4]
    }
    ],
    cv=cv,
    n_jobs=-1,
    scoring="neg_mean_absolute_error")

TypeError: scoring parameter of ForecastingGridSearchCV must be an sktime metric, descendant ofBaseMetric, or a callable with signature (y_true: 1D np.ndarray, y_pred: 1D np.ndarray) -> float, assuming np.ndarrays being of the same length, and lower being better.

**Comment by fkiraly** [comment]
Done, would appreciate a look whether this adds clarity, @TeoSkondras.
I also included a line of code that lets you list all the metrics available.

**Comment by fkiraly** [comment]
Other question: since you expected strings to work - should we make strings a valid argument type, too?

**Comment by TeoSkondras** [comment]
@fkiraly Your pull request fixes the doc perfectly; thanks!
Regarding the string functionality, I think that in sklearn this is their approach regarding param grid scoring, if you want to follow the same principle its fine, if not I am perfectly ok with the solution you gave. It is up to you

**Comment by TeoSkondras** [comment]
@fkiraly another good thing would be to allow more than one metric, ex. r2 and mae. t would be really useful!

**Comment by hazrulakmal** [comment]
> @fkiraly another good thing would be to allow more than one metric, ex. r2 and mae. t would be really useful!

relates to #3508

**Comment by fkiraly** [comment]
> Regarding the string functionality, I think that in sklearn this is their approach regarding param grid scoring, if you want to follow the same principle its fine, if not I am perfectly ok with the solution you gave. It is up to you

Thinking about it

**Comment by fkiraly** [comment]
@TeoSkondras, draft PR for alias strings in the tuners are here: https://github.com/sktime/sktime/pull/5058
