### ISSUE TITLE
[BUG] StatsForecastAutoCES: predict() got an unexpected keyword argument 'level'

### ISSUE THREAD

**Issue by arnaujc91** [sktime/sktime#5024]
**Describe the bug**

StatsForecastAutoCES model complains about `TypeError: predict_in_sample() got an unexpected keyword argument 'level'` when `.predict()` is called after `.fit()`

**To Reproduce**
```python
from sktime.forecasting.statsforecast import StatsForecastAutoCES
from sktime.datasets import load_airline

y = load_airline()

forecaster = StatsForecastAutoCES(season_length=12)
forecaster.fit(y)

forecaster.predict(fh=[1,2,3])

```

**Additional context**

```
Traceback (most recent call last):
  File "/lib/python3.9/site-packages/IPython/core/interactiveshell.py", line 3508, in run_code
    exec(code_obj, self.user_global_ns, self.user_ns)
  File "<ipython-input-17-4d83c1149447>", line 1, in <module>
    forecaster.predict(fh=[1,2,3])
  File "/lib/python3.9/site-packages/sktime/forecasting/base/_base.py", line 404, in predict
    y_pred = self._predict(fh=fh, X=X_inner)
  File "/lib/python3.9/site-packages/sktime/forecasting/base/adapters/_generalised_statsforecast.py", line 192, in _predict
    out_of_sample_point_predictions = self._predict_in_or_out_of_sample(
  File "/lib/python3.9/site-packages/sktime/forecasting/base/adapters/_generalised_statsforecast.py", line 92, in _predict_in_or_out_of_sample
    predictions = self._forecaster.predict(
TypeError: predict() got an unexpected keyword argument 'level'
```

**Versions**
statsforecast 1.4.0 version
M1 Mac chip.

@yarnabrina

**Comment by yarnabrina** [comment]
Hi @arnaujc91, it's not really a bug. These models were added in `sktime` in May I think, and since v1.5.0 `statsforecast` support `level` arguments for `AutoCES`. You can see it in the [release notes](https://github.com/Nixtla/statsforecast/releases/tag/v1.5.0), and this is the relevant [PR](https://github.com/Nixtla/statsforecast/pull/394).

**Comment by yarnabrina** [comment]
@fkiraly should we update a lower bound on `1.5.0`? `0.5.2` is more than a year old.

**Comment by arnaujc91** [comment]
Ok i see, i have v. 1.4.0 and there is not working, that is a problem actually because when you use, for example the [ForecastingGridSearchCV](https://www.sktime.net/en/latest/api_reference/auto_generated/sktime.forecasting.model_selection.ForecastingGridSearchCV.html) class, it automatically uses the method `predict` and the error shows up. So somehow would be great if an error shows up asking to update the version of statsforecast or sth, i could not figure out why this was happening, if it was because of your code or statsforecast code.

**Comment by fkiraly** [comment]
how about we change the adapter to check whether the level arg is present, and only pass it then?

Some people will have older `statsforecast` versions, e.g., since private pypi mirrors may lag behind newer releases.

**Comment by fkiraly** [comment]
alternatively, there is no need to raise the lower bound for `statsforecast` if this is estiator specific - we can simply add the `1.5.0` bound to the estimator. Although it does come from the adapter, so perhaps my first suggestion is better?

**Comment by arnaujc91** [comment]
Sure, i think we could do a try/catch exception and then depending if the error is thrown we pass it or not. I guess that would work.

**Comment by fkiraly** [comment]
agree, @arnaujc91 - except that I always prefer explicit condition checking above try/catch, that's better style.

In this case, it would be via `inspect.signature`.

Would you like to make a PR?
Assuming @yarnabrina agrees to this change proposal to the adapter.
The offending line is the one that passes `level`, as in your traceback.

**Comment by arnaujc91** [comment]
Sounds good! I had no idea about the existence of [inspect.signature](https://docs.python.org/3/library/inspect.html), thanks for sharing!

We can go for that one then

**Comment by fkiraly** [comment]
> Sounds good! I had no idea about the existence of [inspect.signature](https://docs.python.org/3/library/inspect.html), thanks for sharing!

It's really useful if you frequently write interfaces to inconsistent patterns...

**Comment by yarnabrina** [comment]
> Assuming @yarnabrina agrees to this change proposal to the adapter.

Unfortunately, I don't. I disagree with first suggestion, and not very enthusiastic about second. I'll give my reasoning below.

Whether `level` exists or not will change the tags (e.g. `capability:pred_int`) as well. Suggestion 1 will then require presence of  `statsforecast` in init to update tags dynamically, if I'm not wrong. Do we want that?

I don't have anything against suggestion 2, except I am not sure all other statsforecast estimators in sktime support all other versions between 0.5.2 and 1.4.0, by which I mean suporting all features that sktime is using them for. Also, there has been change in major version from 0 to 1, and I'll prefer to update the lower bound.

My suggestion is to update lower bound now in `pyproject.toml` (one time activity) and specify in estimator dependency as well. In future if new estimators are added that were absent in previous versions, we'll specify as such. But I'm unclear what to do if the behaviour changes for existing estimators in future.

**Comment by fkiraly** [comment]
> Suggestion 1 will then require presence of statsforecast in init to update tags dynamically, if I'm not wrong. Do we want that?

If it happens after `super.__init__`, it's fine, since the `super.__init__` call raises the exception "statsforecast not present".

More generally, I think the adapter should be able to cope with statsforecast estimators that do not have the `level` argument. It claims to be a general adapter, so it should cover both cases of estimators with and without prediction interval capability.

> My suggestion is to update lower bound now

That would not deal with a potential estimator that is added later that doesn't have `level`. That could happen, no?

**Comment by yarnabrina** [comment]
From the release note linked above:

> [FEAT] AutoCES prediction intervals in https://github.com/Nixtla/statsforecast/pull/394 (now StatsForecast is fully probabilistic)

I doubt Nixtla will want to change this, and I think they will maintain same API.

But it's better to be safe (and I get ehe general argument), so @arnaujc91 can continue with the `inspect` check as discussed above.

**Comment by fkiraly** [comment]
Ok - but please contradict me if you still genuinely disagree, @yarnabrina!
We should optimally go with a consensus after convincing rather than you being "talked into" an option...
