### ISSUE TITLE
[BUG] `NaiveForecaster` is returning null predictions when `sp>1` for non-daily dataset

### ISSUE THREAD

**Issue by yarnabrina** [sktime/sktime#5032]
# Reprex

```python
import numpy
import pandas

from sktime.forecasting.naive import NaiveForecaster


def count_null_predictions(frequency: str, sp: int) -> int:
    sample_dates = pandas.date_range(start="2001-01-01", periods=30, freq=frequency)
    sample_values = numpy.random.default_rng(seed=0).random(size=len(sample_dates))

    sample_dataset = pandas.Series(sample_values, index=sample_dates)

    model = NaiveForecaster(sp=sp)
    model.fit(sample_dataset)

    predictions: pandas.Series = model.predict(fh=[1, 2, 3])
    null_predictions_count = predictions.isna().sum()

    return null_predictions_count


print(count_null_predictions("D", 1))  # 0
print(count_null_predictions("D", 2))  # 0

print(count_null_predictions("2D", 1))  # 0
print(count_null_predictions("2D", 2))  # 2

print(count_null_predictions("W", 1))  # 0
print(count_null_predictions("W", 2))  # 3

print(count_null_predictions("2W", 1))  # 0
print(count_null_predictions("2W", 2))  # 3

print(count_null_predictions("M", 1))  # 0
print(count_null_predictions("M", 2))  # 3

print(count_null_predictions("2M", 1))  # 0
print(count_null_predictions("2M", 2))  # 3
```

# Expectation

I expected all predictions to be non-null. If there is some special check where it is unable to predict, it should have raised error, or at least throw warning instead of predicting nulls silently.

# Version

```pycon
>>> from sktime import show_versions; show_versions()

System:
    python: 3.10.12 (main, Jul  5 2023, 18:54:27) [GCC 11.2.0]
executable: /path/to/venv/bin/python
   machine: Linux-5.15.90.1-microsoft-standard-WSL2-x86_64-with-glibc2.35

Python dependencies:
          pip: 23.2.1
       sktime: 0.21.0
      sklearn: 1.3.0
       skbase: 0.4.6
        numpy: 1.24.4
        scipy: 1.11.1
       pandas: 2.0.3
   matplotlib: 3.7.2
       joblib: 1.3.1
  statsmodels: 0.14.0
        numba: 0.57.1
     pmdarima: 2.0.3
      tsfresh: None
   tensorflow: None
tensorflow_probability: None
```

**Comment by fkiraly** [comment]
Reproduced on current `main`, python 3.11, windows.

Very odd, I thought the tests explicitly check sp=2 as well as expected output.

**Comment by benHeid** [comment]
The main problem seems to be the different `..index.astype("int64)` in `_pivot_sp`. In general, these calls do not return consecutive integer values as probably assumed by the call in line `146` in `seasonality.py` (at least I think this is assumed):

```python
    df_pivot = pd.pivot_table(
        data=df,
        index=ix // sp,  # Upper level
        columns=ix % sp,  # Lower level
        dropna=False,
    )
```

**Comment by fkiraly** [comment]
so, would sorting solve this?

**Comment by benHeid** [comment]
I don't think so. The issue is that for a ts with index 13:00, 13:30, 14:00 .... astype(int) returns ....00, ....30, ....90. So I suppose that the internal frequency is determining how the cast by astype(int) is working. The simplest multiplication of sp by the frequency is also not directly solving the issue but the resulting pivot table looks better.

**Comment by fkiraly** [comment]
hm, I have an idea - in `TrendFoecaster`, we are using `_get_X_numpy_int_from_pandas` to coerce any `pandas` index to integer.

This then avoids dealing with indices internally, and at the end one can overwrite indices with expected index.

**Comment by benHeid** [comment]
Mhm perhaps this would reduce a bit of the code duplications, but the adaption of the sp is still necessary.
