### ISSUE TITLE
[ENH] skip training and prediction of `forecaster_X` in `ForecastX` if `forecaster_y` has `ignores-exogeneous-X` as `True`

### ISSUE THREAD

**Issue by yarnabrina** [sktime/sktime#5040]
As of now, `ForecastX` trains and predicts `forecaster_X` always, irrespective of the model specified as `forecaster_y`. But if the endogenous model lacks the capability of using exogenous features, this training and prediction is of no use, and can/should be skipped.

Enhancement Proposal:

1. check tag of `forecaster_y` in `__init__`.
2. if `True`, continue as it is.
3. if `False`, return `forecaster_y` as it is.

Based on my understanding, (3) above should not cause any issue becuase of same API format for all forecasters and pased exogenous features will be ignored.

Optional suggestions:

1. add an argument which will control whether to raise an error, throw a warning, or do nothing.

Documentation issue (unrelated):

1. `forecaster_X` is documented as optional argument which uses `forecaster_y` when not provided explicitly. But this needs to be provided as `None` in that case as it is a positional argument, and can not be skipped in the call altogether.

**Comment by fkiraly** [comment]
>  this training and prediction is of no use, and can/should be skipped.

Makes sense.

Question, should a warning be raised as well in this case?

Because the user is doing something that is superfluous in this case.

Now, I'm not sure how confusing or problematic such a warning would be in a case of tuning over the inner forecaster where some forecasters ignore `X` and some don't.

**Comment by fkiraly** [comment]
> if False, return forecaster_y as it is.

That wouldn't work - even if it would work, it would violate the `sklearn` interface assumptions, since `forecaster_y` has different parameters from `self`.

Instead, we can skip the `X`-fitting and let the forecaster behave as a delegator to `forecaster_y`.
