### ISSUE TITLE
[ENH] remove private methods from parameters of `ProximityForest`, `ProximityTree`, `ProximityStump`

### ISSUE THREAD

**Issue by fkiraly** [sktime/sktime#5042]
For mysterious reasons, the estimators `ProximityForest`, `ProximityTree`, `ProximityStump` have their private methods with algorithm logic as *parameters* (i.e., `__init__` arguments) rather than private methods.

The parameters in question are:
* `setup_distance_measure`
* `get_distance_measure`
* `find_stump`
* `get_exemplars`
* `get_gain`

As parameters, these are more or less useless and confusing, since nowhere it is documented what contract the functions need to fulfil, in a case where the user would want to deviate from the default - and there are no examples of non-defaults.

Therefore, we should just remove these odd parameters and turn them into references to the methods in the package.

In the case of `get_gain`, which defaults to `gini_gain`, it might be worth thinking carefully about retaining it, although this might be too much work in the first instance.

I do not think anyone has been using these arguments, due to their obscure nature making it near-impossible to come up with a sensible non-default.
Therefore, I think we can skip the deprecation that we would otherwise need when changing `__init__` parameters.

Good first issue, as it doesn't really require to know what the methods do, in order to refactor the classes cleanly.

**Comment by fnhirwa** [comment]
Hello @fkiraly is this task still open for contribution?
If so, I'd like to work on it 😊
