### ISSUE TITLE
[BUG] get_window not working as expected with Pandas DF

### ISSUE THREAD

**Issue by arnaujc91** [sktime/sktime#5047]
**Describe the bug**
`get_window` from:
```python

from sktime.datatypes._utilities import get_window

```
Not working as expected:

```

line 485, in get_window
    win_start_excl = cutoff - window_length
  File "pandas/_libs/tslibs/timestamps.pyx", line 493, in pandas._libs.tslibs.timestamps._Timestamp.__sub__
  File "pandas/_libs/tslibs/timestamps.pyx", line 461, in pandas._libs.tslibs.timestamps._Timestamp.__add__
TypeError: Addition/subtraction of integers and integer-arrays with Timestamp is no longer supported.  Instead of adding/subtracting `n`, use `n * obj.freq`

```

**To Reproduce**
```python
from sktime.datatypes._utilities import get_window
from sktime.utils._testing.hierarchical import _make_hierarchical

y_hierarchical = _make_hierarchical(hierarchy_levels=(2, 3), min_timepoints=12, max_timepoints=12, random_state=0)

get_window(y_hierarchical, 4)
```

**Expected behavior**
(cutoff - window_length - lag, cutoff - lag)

**Additional context**
I think it has to do with the index of the DataFrame.

**Versions**
0.21.0

This is related to issues #4943, #4972 and PR #5009.

**Comment by hazrulakmal** [comment]
I reckon this is not a bug but a wrong use of input formats. `get_window`'s docstring says as follows

> window_length : int or timedelta, optional, default=-inf
must be int if obj is int indexed, timedelta if datetime indexed length of the window to slice to. Default = window of infinite size

since your index is time-like, you should use timedelta as follows
```python
from sktime.datatypes._utilities import get_window
from sktime.utils._testing.hierarchical import _make_hierarchical

y_hierarchical = _make_hierarchical(hierarchy_levels=(2, 3), min_timepoints=12, max_timepoints=12, random_state=0)
window_length = pd.Timedelta(5, unit="D") # or you can also use pandas offsets format, pd.offsets.Day(5
get_window(y_hierarchical,  window_length)
```

**Comment by arnaujc91** [comment]
True, going to close the issue. Thanks for the clarification.

**Comment by fkiraly** [comment]
Well, you could argue that it's not expected according to the docstrings - but you could also argue that the function should be extended, for some downstream use.

Though this clarifies that we would indeed need to extend the function.
