### ISSUE TITLE
[ENH] Allow YfromX to handle missing data

### ISSUE THREAD

**Issue by eenticott-shell** [sktime/sktime#5061]
**Is your feature request related to a problem? Please describe.**
YfromX should be able to handle missing data as long as the estimator passed to it is able to. We can change the tag to read the missing data capability of the estimator.

**Comment by fkiraly** [comment]
I think a plain change in the tag is already fine. This seems like a bug.

**Comment by eenticott-shell** [comment]
Ahh perfect, that change is pushed then I'll open it from draft. To note, I did try a dynamic tag but I wasn't able to use `self.set_tag(allow-missing-data=True)` because it didn't like hyphens in the variable name, is this another bug? I think this is the only tag containing hyphens.

**Comment by fkiraly** [comment]
> because it didn't like hyphens in the variable name, is this another bug

Not a bug strictly speaking, but a known inconvenience, see:
https://github.com/sktime/sktime/issues/1397
(help with this appreciated!)

The usual workaround is `self.set_tag(**{"allow-missing-data"=True})`
