### ISSUE TITLE
[BUG] readthedocs build failing with `AttributeError("'TocTree' object has no attribute 'get_toctree_ancestors'")`

### ISSUE THREAD

**Issue by fkiraly** [sktime/sktime#5117]
Readthedocs builds are erroring out with `sphinx.errors.ThemeError: An error happened in rendering the page about.
Reason: AttributeError("'TocTree' object has no attribute 'get_toctree_ancestors'")`, since yesterday, I think?

I can identify no immediate reason why they would.

This seems high priority as it prevents us from updating documentation.

**Comment by fkiraly** [comment]
Might be due to the `sphinx 7.2.0` release 12 hours ago, so attempted fix adds an upper bound: https://github.com/sktime/sktime/pull/5118

**Comment by fkiraly** [comment]
Update: that fixes it, though we should still understand what we need to do to make our doc build compatible with 7.2.0 and above.

**Comment by yarnabrina** [comment]
This is definitely caused by the new Sphinx release: https://github.com/sphinx-doc/sphinx/issues/11608

There's a new release as well, going to try in a new MNT PR.
