### ISSUE TITLE
[BUG] - TransformedTargetForecaster with Arima can't fit a transformer taking series as input and returning pd.Dataframe with multiple series

### ISSUE THREAD

**Issue by DaneLyttinen** [sktime/sktime#5128]
**Describe the bug**

When using a custom decomposition transformer which takes a single time series input and produces multiple in a Pandas dataframe format, used in conjunction with the TransformedTargetForecaster as a pipeline and the Arima model as the forecaster, will produce the following error when making predictions:
    raise ValueError("input must be univariate pd.DataFrame, with one column")
ValueError: input must be univariate pd.DataFrame, with one column

**To Reproduce**

```python
import pandas as pd
import numpy as np
from sktime.forecasting.arima import ARIMA
from sktime.forecasting.compose import TransformedTargetForecaster
from sktime.forecasting.model_evaluation import evaluate
from sktime.forecasting.model_selection import ExpandingWindowSplitter
from sktime.performance_metrics.forecasting import MeanSquaredError

from vmd_specifc.VmdTransformer import VmdTransformer
#. Time Domain 0 to T
T = 1000
fs = 1/T
t = np.arange(1,T+1)/T
freqs = 2*np.pi*(t-0.5-fs)/(fs)

#. center frequencies of components
f_1 = 2
f_2 = 24
f_3 = 288

#. modes
v_1 = (np.cos(2*np.pi*f_1*t))
v_2 = 1/4*(np.cos(2*np.pi*f_2*t))
v_3 = 1/16*(np.cos(2*np.pi*f_3*t))

f = v_1 + v_2 + v_3 + 0.1*np.random.randn(v_1.size)
data = pd.Series(f)

pipe = TransformedTargetForecaster(steps=[
    ("vmd transformer", VmdTransformer()),
    ("forecaster", ARIMA())
])
# the below commented section also show the same problem
# y = data[:(round((len(data) / 100) * 70))]
# pipe.fit(y)
# preds = pipe.predict(fh=[1,2,3,4,5,6])
cv = ExpandingWindowSplitter(step_length=2, fh=2,
                             initial_window=(round((len(data) / 100) * 70)) )
cv_df = evaluate(error_score='raise', forecaster=pipe, y=data, cv=cv, strategy="refit",
                 return_data=True,
                 scoring=MeanSquaredError(square_root=True))

```

**Expected behavior**

A separate Arima model should be fit on each column of the returned pandas data frame, and the model should not throw an error.
**Additional context**

The link to the custom VmdTransformer pull request will be given here when created, or mentioned in the comments.
**Versions**
<details>

System:
    python: 3.8.10 (tags/v3.8.10:3d8993a, May  3 2021, 11:48:03) [MSC v.1928 64 bit (AMD64)]
executable: C:\Users\Dane\AppData\Local\Microsoft\WindowsApps\PythonSoftwareFoundation.Python.3.8_qbz5n2kfra8p0\python.exe
   machine: Windows-10-10.0.19045-SP0

Python dependencies:
          pip: 23.0
       sktime: 0.21.0
      sklearn: 1.2.1
       skbase: 0.4.6
        numpy: 1.22.4
        scipy: 1.10.0
       pandas: 1.5.3
   matplotlib: 3.3.4
       joblib: 1.2.0
  statsmodels: 0.13.2
        numba: 0.55.2
     pmdarima: 2.0.2
      tsfresh: 0.20.0
   tensorflow: None
tensorflow_probability: 0.19.0
</details>

**Comment by fkiraly** [comment]
Thanks! I have seen the pull request #5129, and left some comments there.

There are a small number of issues with the tags, so let's see whether those solve the matter - if not, we can then use the repaired transformer in #5129 for debugging.

**Comment by fkiraly** [comment]
I think I found the problem, you set the tag `"skip-inverse-transform": False,` - that prevents application of `inverse_transform` at the end, which produces a `pd.DataFrame` with more, and different, columns for `y` as seen at the start of `fit` of the `TransformedTargetForecaster`.
