### ISSUE TITLE
[BUG] `ForecastingGridSearchCV` does not save `best_forecaster_`, `cv_results_` and other properties for multivariate time series

### ISSUE THREAD

**Issue by SmirnGregHM** [sktime/sktime#5143]
**Describe the bug**

`ForecastingGridSearchCV` does not save `best_forecaster_`, `cv_results_` and other properties for multivariate time series.
**To Reproduce**

This works:
```python
y = pd.DataFrame(index=pd.date_range("2021-01-01", "2021-01-10"),
                 data={"a": [1, 2, 3, 4, 5, 6, 7, 8, 9, 10], 
                       "b": [-1, -2, -3, -4, -5, -6, -7, -8, -9, -10]})
forecasters = NaiveForecaster(window_length=5)

cv = ExpandingWindowSplitter(fh=2, initial_window=5, step_length=1)
forecaster_param_grid = {"strategy": ["mean", "drift"]}

pipeline = ForecastingGridSearchCV(
    forecasters, cv=cv,
    param_grid=forecaster_param_grid,
    error_score='raise'
)
display(pipeline.fit(y[["a"]]).predict(fh=np.arange(1, 5)))
display(pipeline.best_params_)
display(pipeline.cv_results_)
```
<img width="1438" alt="image" src="https://github.com/sktime/sktime/assets/121803583/dff16974-dc07-497f-89a5-b18927780097">

This does not:
```python
y = pd.DataFrame(index=pd.date_range("2021-01-01", "2021-01-10"),
                 data={"a": [1, 2, 3, 4, 5, 6, 7, 8, 9, 10], 
                       "b": [-1, -2, -3, -4, -5, -6, -7, -8, -9, -10]})
forecasters = NaiveForecaster(window_length=5)

cv = ExpandingWindowSplitter(fh=2, initial_window=5, step_length=1)
forecaster_param_grid = {"strategy": ["mean", "drift"]}

pipeline = ForecastingGridSearchCV(
    forecasters, cv=cv,
    param_grid=forecaster_param_grid,
    error_score='raise'
)
display(pipeline.fit(y).predict(fh=np.arange(1, 5))). # change here
display(pipeline.best_params_)
display(pipeline.cv_results_)
```
Fit is performed well, but the properties are not available
<img width="678" alt="image" src="https://github.com/sktime/sktime/assets/121803583/73229209-6a2b-4831-9d85-b3f3c555ebff">

**Expected behavior**

`best_params_`. `cv_results_` etc are available for multivariate series too.

**Versions**
<details>

System:
    python: 3.8.13 (default, Oct 19 2022, 17:54:22)  [Clang 12.0.0 ]
executable: /Users/grigorii/opt/miniconda3/envs/hcem_test/bin/python
   machine: macOS-10.16-x86_64-i386-64bit

Python dependencies:
          pip: 22.3
       sktime: 0.22.0
      sklearn: 1.0.2
       skbase: 0.4.6
        numpy: 1.24.4
        scipy: 1.9.3
       pandas: 1.4.4
   matplotlib: 3.5.3
       joblib: 1.2.0
        numba: 0.57.1
  statsmodels: 0.13.4
     pmdarima: 1.8.5
statsforecast: 1.5.0
      tsfresh: None
      tslearn: None
        torch: None
   tensorflow: None
tensorflow_probability: None
</details>

Thanks a lot for such an awesome package!

**Comment by fkiraly** [comment]
Hm, this is an interesting one - I am not sure whether this is a bug.

Currently, the tuning forecasters vectorize over columns (variables) if and only if the wrapped forecaster does.

That is, the tuning happens per variable, if the forecaster inside is also applied per variable.

The best parameter is per column (variable), and can be found in the attribute `forecasters_`, which is a `pd.DataFrame` with the tuned forecasters being entries - these have `best_params_` etc.

Now, the question is - is this expected or counterintuitive? That is, should a direct application of grid search always select the same parameter for all columns, and have a single `best_params_` attribute?

**Comment by fkiraly** [comment]
(if it's counterintuitive, it would be a bug, or at least bug-like)

**Comment by SmirnGregHM** [comment]
@fkiraly thanks a lot for a quick answer!

I do AutoML with `MultiplexForecaster`. My expectation is that when I do so, the same model will be chosen for all the components of the multivariate time series. For example, if I choose between `NaiveForecaster(window_length=5, strategy="mean")` and `Prophet()` I want to see both components behaving either very simple or rather complex. Also, I expected the same interface for univariate and multivariate series. But now I also see your reasoning, and it might indeed be beneficial to find various hyperparameter combinations for various components in some scenarios.

My suggestion would be to have a separate input (`global_param_grid`?) for hyperparameters to be selected globally, and leave `param_grid` to be selected per-series as it is happening now.

Alternatively, add a field to CV classes which would set one or another behavior, with the current one being the default.

**Comment by fkiraly** [comment]
I see, @SmirnGregHM, that's a pretty strong argument - interface consistency, or, more precisely, the current setup violates it.

I would agree with your argumentation in favour of making the interface uniform, and to ensure that columns behave like rows - same parameter everywhere.

I also want to ping @yarnabrina who is also working on autoML use cases.

Now, regarding the solution, I think adding more parameters to the tuners is a solution, but not the bets solution. Instead, users who want to tune columns independently would stick the grid search estimator into `ColumnEnsembleTransformer` - no additional arguments needed to any existing estimator.

**Comment by fkiraly** [comment]
for the bugfixing board: I now agree that this is a bug.

**Comment by fkiraly** [comment]
@SmirnGregHM, if you'd like to test - feedback would be appreciated. The proposed fix is in https://github.com/sktime/sktime/pull/5145
