### ISSUE TITLE
[BUG] `statsforecast` interface failures since `statsforecast 1.6.0`

### ISSUE THREAD

**Issue by fkiraly** [sktime/sktime#5150]
It would appear that `statsforecast 1.6.0`, recently released, removed the `parallel` arg from some estimators, causing failures.

The scope and extent of the failures is not entirely clear due to differential testing.
It will be clear from this PR that runs all tests on all estimators: https://github.com/sktime/sktime/pull/5083

FYI @yarnabrina, @luca-miniati, and @arnaujc91 due to recent work on the adapter.

related:

* maintenance PR to introduce `<1.6.0` bound https://github.com/sktime/sktime/pull/5149
* discussion on defensive version bounds https://github.com/sktime/sktime/issues/1480 (which `statsforecast` did not happen to have, unfortunately)

**Comment by fkiraly** [comment]
in order to not break anything for our users (like `statsforecast` did), we ought to check whether the `parallel` arg is there, and pass it only then; raise a warning if the user passes sth but the underlying `statsforecast` version does not have it.

FYI @arnaujc91, this is oddly similar to the case you are dealing with.

Perhaps we should do the same with all estimator arguments - pass them if and only if they are present in the underlying estimator; if not, and the user passes sth, raise a warning.

**Comment by yarnabrina** [comment]
Should we rewrite (if required) init method of valid parameters in StatsForecast as of now? Do we need specific approval from Nixtla for the same, as they interfaced it originally?

**Comment by yarnabrina** [comment]
> Perhaps we should do the same with all estimator arguments - pass them if and only if they are present in the underlying estimator; if not, and the user passes sth, raise a warning

This seems too much, does it not? Most of the forecasters take a good amount of parameters. If we add checks for existence of all of those with i spect everywhere, won't that be massive?

**Comment by fkiraly** [comment]
> Should we rewrite (if required) init method of valid parameters in StatsForecast as of now? Do we need specific approval from Nixtla for the same, as they interfaced it originally?

It should be fine if we leave the set of parameters and just ensure it doesn't break under the hood for 1.6.X. That is, having the parameter in general, but raise a warning that it is no longer passed, if `statsforecast>=1.6.0`.

& we should ping @FedericoGarza

**Comment by fkiraly** [comment]
> If we add checks for existence of all of those with i spect everywhere, won't that be massive?

Two or three fast list comprehensions, I thought - but pehaps it's overkill, and we won't notice future interface changes?

**Comment by yarnabrina** [comment]
I assumed you meant we check all arguments to init, initate_forecaster, fit, predict, etc. methods (names may vary) of each and every forecaster dependency packages, and we only use a method if esupported by installed version and pass an argument if available in installed version. This seemed massive.

I (confidently) think I misunderstood you. Can you please explain what was your suggestion?

**Comment by fkiraly** [comment]
> I (confidently) think I misunderstood you. Can you please explain what was your suggestion?

Apologies, I was not very clear.

I meant, in `_initiate_forecaster` or a similar method, we inspect the `statsforecast` class. We pass those and only those params from `self` to the `statsforecast` class to construct that an inspect call finds.

**Comment by fkiraly** [comment]
@yarnabrina - are these resolved?

**Comment by fkiraly** [comment]
yes, looks like it - FYI @arnaujc91
