### ISSUE TITLE
[ENH] refactor `DateTimeFeatures` tests to `pytest` fixtures

### ISSUE THREAD

**Issue by fkiraly** [sktime/sktime#5155]
The tests in `transformations.series.tests.test_date` for the `DateTimeFeatures` transformer should be refactored to use proper `pytest` fixtures. The massive `pytest` decorator should be split up and/or refactored.

Also see PR https://github.com/sktime/sktime/pull/5154 for fixing issues with the soft dependency isolation.

**Comment by fkiraly** [comment]
@adamkells, the problem is in two places:

* the massive decorater starting line 147, as you say
* the decorator references variables which are written directly into the module scope, starting line 16. This generation should all move into pytest fixtures, and optimally not require calls `fit` and `transform` where this can be avoided.

**Comment by adamkells** [comment]
@fkiraly I have opened a draft PR [here](https://github.com/sktime/sktime/pull/5397). (Apologies, I initially opened it as a full PR). Can you confirm if the reformat meets the brief?

**Comment by fkiraly** [comment]
Yes, this looks great!

I did not know you could do this with `pytest` classes, thanks for teaching me this!

**Comment by adamkells** [comment]
Great! I've converted from draft to ready for review
