### ISSUE TITLE
[BUG] `NaiveForecaster` has `ignores-exogeneous-X` tag value as `False`

### ISSUE THREAD

**Issue by yarnabrina** [sktime/sktime#5160]
**To Reproduce**

```pycon
>>> from sktime.forecasting.naive import NaiveForecaster
>>> NaiveForecaster().get_tag("ignores-exogeneous-X")
False
```

**Expected behavior**

The value is expected to be `True`, as exogenous features are not supposed to be used for "naive" forecasting.

**Comment by fkiraly** [comment]
ah, you are right - I concur. Should be an easy fix, are you going to PR?
