### ISSUE TITLE
[BUG] fix logic for multiple scorers in `evaluate`

### ISSUE THREAD

**Issue by fkiraly** [sktime/sktime#5167]
I looked at the logic for multiple scorers in `evaluate` and it is in essence broken - this seems to date back to the PR that originally claimed to add functionality to compute multiple scores, see https://github.com/sktime/sktime/pull/3883.

The nature of the breakage is as follows:

* if a list of scorers are passed, then only the first one is run through the entire machinery (!) - this includes crucial logic such as selecting the right predict method based on the scorer type, e.g., probabilistic, point prediction etc. The current logic inserts `scoring[0]` everywhere in the list case and does not touch the code otherwise.
* for the remaining scorers, evaluation happens separately, in the part that says "final formatting of results DataFrame". This part, in fact, does not just reformat, but runs the scoring loop for all other scorers - but omits crucial logic as mentioned above, so it will break for probabilistic scores or those requiring special arguments.

As a consequence, this also breaks logic of the tuning estimators that internally use `evaluate`.

What should happen is that `_evaluate_window` computes multiple scores, and takes multiple `scoring` arguments.

The final part of the code that does results formatting should do that and only that.

FYI @hazrulakmal due to the benchmarking topic and your recent work on this.

**Comment by hazrulakmal** [comment]
> What should happen is that _evaluate_window computes multiple scores, and takes multiple scoring arguments.

Yeah I agree, I think this is what should happen. I can take this up if you don't mind? I believe that handling the storage of different prediction types is also a problem here if the list of scores contains a mix of different performance metric types.

The simplest solution to consider is to only accept a list of the same performance metric types, such as all probabilistic or all point predictions. This way, the current solution will still work but may not be as flexible.

**Comment by fkiraly** [comment]
> The simplest solution to consider is perhaps to only accept a list of the same performance metric types, such as all probabilistic or all point predictions. This way, the current code will still work but may not be as flexible.

Personally, I would modify this - the aggregated performances are floats, so that can stay as is. And, as long as the predictions are stored in some kind of container where their format does not matter - that would solve the format issue too?
