### ISSUE TITLE
[ENH] Implement AutoTheta

### ISSUE THREAD

**Issue by mloning** [sktime/sktime#517]
**Describe the solution you'd like**
Translate code from the [R implementation](https://github.com/vangspiliot/AutoTheta) into Python. 

**Describe alternatives you've considered**
Consider implementing it as part of statsmodels rather than sktime and then interface it in sktime.

**Comment by jordanrmerrick** [comment]
I'm implementing this now, I should be posting a pull request within a week or so!

**Comment by mloning** [comment]
Great @jordanrmerrick, I'm looking forward to that! For testing we should compare it with some results from the R version.

**Comment by unna97** [comment]
hi @jordanrmerrick, are you still working in this?

**Comment by jordanrmerrick** [comment]
I am! Finishing finals in school took more time than I anticipated so progress has been slower, but I'm submitting a PR tioday or tomorrow.

**Comment by Aman027** [comment]
@mloning Can I work on this issue?

**Comment by Aditya-Sihmar** [comment]
I think this has already been implemented in PR #198. @mloning, please confirm. If this PR fulfil the objectives of this issue, I suggest we should close it.

**Comment by mloning** [comment]
Hi @Aditya-Sihmar, I think PR #198 implemented Theta, this issue is about AutoTheta. 

@Aman027 @Aditya-Sihmar would love to see a translation to Python. 

@satya-pattnaik may also be able to help with the implementation and testing against the R version.

**Comment by Aditya-Sihmar** [comment]
They mentioned the same paper in its documentation that's why I asked. I will have a look into it again. 
@mloning how you want AutoTheta to be implemented. Shall I implement it as an independent function or shall I update the Theta method itself?

**Comment by unna97** [comment]
@Aditya-Sihmar  @Aman027  I have parts of the R code translated. Will be happy to share if it's useful. Also happy to pair code.

**Comment by mloning** [comment]
I'd prefer a separate class for `AutoTheta` - this seems to be the current pattern (e.g. `ARIMA` and `AutoARIMA`).

**Comment by Aditya-Sihmar** [comment]
Thanks @unna97, It would be really helpful.

Ok @mloning I will start working on it right away.

**Comment by Aditya-Sihmar** [comment]
While solving this issue I got stuck at a place.
``` R
 outtest <- naive(input, h=fh)$mean
```
This is a simple naive forecaster so I implemented it in python ignoring the shape of the output data. I am just predicting the future values not their shape but turns out their shape also matters later down the stage. I tried to find a function in python that takes shape also into consideration but didn't find any. I am not sure what to do next. Is there any function out there that I am missing or should I implement that function myself?

**Comment by mloning** [comment]
@Aditya-Sihmar what do you mean by "predicting the future values not their shape", isn't the shape queryable from the predicted array of values? We have a `NaiveForecaster` in sktime if that helps. 

I would suggest you open a draft PR, that way we can take a look at the code you have written already (it doesn't have to be polished or complete in any way).

**Comment by Aditya-Sihmar** [comment]
Thank You @mloning, I will try that out. I will make the draft pull request by tomorrow, just need to do some changes before drafting the PR.

**Comment by fkiraly** [comment]
resolved by interfacing `statsforecast` in PR https://github.com/sktime/sktime/pull/4539
