### ISSUE TITLE
[BUG] BaseRegressor should allow one-column `pd.DataFrame` as `y`

### ISSUE THREAD

**Issue by benHeid** [sktime/sktime#5177]
**Describe the bug**

The BaseRegressor's fit method performs the type coercion only for X and not for y. Thus calling a Regressor with a one-dimensional data frame as y fails.

**To Reproduce**

```python
from sktime.regression.distance_based import KNeighborsTimeSeriesRegressor
import numpy as np

knn = KNeighborsTimeSeriesRegressor()

# The following statement works
knn.fit(pd.DataFrame(np.random.normal(0, 1, (100, 5)), index=pd.MultiIndex.from_product([range(50), range(2)])),
        pd.Series(np.random.normal(0, 1, 50))
        )

# The following statement fails  
knn.fit(pd.DataFrame(np.random.normal(0, 1, (100, 5)), index=pd.MultiIndex.from_product([range(50), range(2)])),
        pd.DataFrame(np.random.normal(0, 1, 50))
        )
```

**Expected behavior**

Both statements should work and the one-dimensional y is converted to a series internally.

**Comment by fkiraly** [comment]
Hm, it's maybe less a but than a missing feature - the feature being "regressors (and classifiers?) should accept one-column `pd.DataFrame` as a valid `y`".

Also, based on our recent discussion, we should possibly also admit multivariate `y`, and broadcast in the base case? (one regressor/classifier per column)

**Comment by fkiraly** [comment]
Mid-term, I think we want to move to a `check_is_scitype` for the `"Table"` scitype. In-principle, we should allow multivariate `y` - and broadcast in case the regressor is univariate.
