### ISSUE TITLE
[BUG] ColumnSelect missing tag`"skip-inverse-transform"`

### ISSUE THREAD

**Issue by benHeid** [sktime/sktime#5205]
**Describe the bug**

The ColumnSelect is missing the tag  `"skip-inverse-transform"`. Thus, a TransformedTargetForecaster subsetting the `y` input will fail when calling predict.

**To Reproduce**

```python
from sktime.forecasting.naive import NaiveForecaster
from sktime.transformations.series.subset import ColumnSelect
from sktime.datasets import load_longley
y = load_longley()[1][["GNP", "UNEMP"]]
fc = ColumnSelect(["GNP"]) * NaiveForecaster()
fc.fit(y)
fc.predict(fh=[1])
```

**Expected behavior**

I would expect that the forecast is performed only on the selected time series without raising an error.

**Additional context**

This would be fixed by just adding the tag `skip-inverse-transform` to ColumnSelect.

**Comment by fkiraly** [comment]
Ah, that's an oversight.

Although, why would you chain a `ColumnSelect` in a `TransformedTargetForecaster`, would that not result in a forecast of less variables than the original data?

Either way, I suppose it's not an unreasonable use case. Let's add the tag and the failing example as a one-off test?
