### ISSUE TITLE
[BUG] `Pipeline` not exported in `sktime.pipeline`

### ISSUE THREAD

**Issue by ujohn33** [sktime/sktime#5229]
**Current behavior:**

When trying to import the `Pipeline` class from the `sktime.pipeline` module, the following error is raised:

```
ImportError: cannot import name 'Pipeline' from 'sktime.pipeline' (/Users/evgenygenov/miniforge3/envs/synthhouse/lib/python3.9/site-packages/sktime/pipeline/__init__.py)
```

**Expected behavior:**

The `Pipeline` class should be successfully imported from the `sktime.pipeline` module.

**Steps to reproduce:**

1. Install `sktime` package.
2. Try to import `Pipeline` class from `sktime.pipeline` module.

**Environment:**

- Operating system: macOS
- Processor: ARM
- Python version: 3.9.18
- Installed conda packages: (see list above)

**Additional context:**

This error occurs on a macOS machine with an ARM processor. The error message suggests that the `Pipeline` class cannot be found in the `sktime.pipeline` module.

from sktime import show_versions; show_versions()

System:
    python: 3.9.18 | packaged by conda-forge | (main, Aug 30 2023, 03:53:08)  [Clang 15.0.7 ]
executable: [/Users/evgenygenov/miniforge3/envs/synthhouse/bin/python](https://file+.vscode-resource.vscode-cdn.net/Users/evgenygenov/miniforge3/envs/synthhouse/bin/python)
   machine: macOS-12.5.1-arm64-arm-64bit

Python dependencies:
          pip: 23.2.1
       sktime: 0.22.0
      sklearn: 1.3.0
       skbase: 0.5.1
        numpy: 1.22.4
        scipy: 1.11.2
       pandas: 2.0.3
   matplotlib: 3.7.3
       joblib: 1.3.2
        numba: None
  statsmodels: None
     pmdarima: None
statsforecast: None
      tsfresh: None
      tslearn: None
        torch: None
   tensorflow: None
tensorflow_probability: None
[/Users/evgenygenov/miniforge3/envs/synthhouse/lib/python3.9/site-packages/_distutils_hack/__init__.py:33](https://file+.vscode-resource.vscode-cdn.net/Users/evgenygenov/miniforge3/envs/synthhouse/lib/python3.9/site-packages/_distutils_hack/__init__.py:33): UserWarning: Setuptools is replacing distutils.
  warnings.warn("Setuptools is replacing distutils.")

**Comment by hazrulakmal** [comment]
[`Pipeline`](https://www.sktime.net/en/latest/api_reference/auto_generated/sktime.pipeline.pipeline.Pipeline.html#sktime.pipeline.pipeline.Pipeline) hasn't been officially released yet. It's in the development branch. If you wanna use it now, you have to install the development version as stated [here](https://www.sktime.net/en/latest/installation.html).

@fkiraly @yarnabrina I suggest we change the `latest` version in the doc to the `dev` version instead to avoid confusion.

**Comment by yarnabrina** [comment]
@hazrulakmal are you by chance suggesting something like https://github.com/sktime/sktime/issues/4677?

I tried to show at least a banner, but couldn't make it work because of my lack of knowledge of css/javascript/html etc. The issue appears closed incorrectly, if you want to fix it please feel free.

**Comment by fkiraly** [comment]
Yes, but the error is still valid with the dev version, it is missing from the init. FYI @benHeid
