### ISSUE TITLE
[ENH] Add Cyclical/Trigonometric Encoding of DateTimeFeatures

### ISSUE THREAD

**Issue by benHeid** [sktime/sktime#5237]
**Is your feature request related to a problem? Please describe.**
Currently, DateTimeFeatures are encoded numerically: E.g. January=1, February=2, December=12. 

However, in several domains January is more similar to December than to July. E.g., in the energy domain if you are comparing the heating demand. In the northern hemisphere, it is likely that the heating demand is similar for December and January but differs clearly between January and July. 
However, the current encoding does not reflect this. In the current encoding, the distance between January=1 and December=12 is higher than between January=1 and July=7. 

Thus, I would like to have an option to encode the DateTimeFeature trigonometric or cyclical. 

**Describe the solution you'd like**
Add a flag that encodes the DatetimeFeatures cyclical.

E.g. month of the year would be encoded with:

```
month_sin = np.sin(np.pi * 2 * (numerical_month) / 12))
month_cos = np.cos(np.pi * 2 * (numerical_month) / 12))
```

The vector (month_sin, month_cos) has the requested similarity properties. 

**Describe alternatives you've considered**
Instead of extending the DateTimeFeatures, a new Transformer could be added.

**Additional context**
This is especially important for deep learning based methods:
https://www.kaggle.com/code/avanwyk/encoding-cyclical-features-for-deep-learning

**Comment by fkiraly** [comment]
This looks like the same as `FourierFeatures`, although afaik it primarily looks at the `iloc` index rather than `loc` (which you might be implying)

**Comment by benHeid** [comment]
It is the same as FourierFeatures. Thus, I am closing this issue
