### ISSUE TITLE
[ENH] `scipy.curve_fit` based forecaster

### ISSUE THREAD

**Issue by benHeid** [sktime/sktime#5238]
**Is your feature request related to a problem? Please describe.**
In scipy there exist the `curve_fit` method. This takes a function, x, and y data and some initial parameters. If x are time series indexes this can be used to perform forecasting: 

**Describe the solution you'd like**
Example usage would looks like that:
```python
def sine_3(x,amplitude, phase, offset, amplitude2, amplitude3, phase2):
    sbase = np.sin(x * (1 / 365 / 24 * np.pi * 4) + phase) * amplitude + offset 
    s1 = amplitude2 * x * (np.sin(x* (1 / 365 / 24 * np.pi * 2) + (365* 24* np.pi)+ phase2) + 1)
    s2 = amplitude3 * x * (np.sin(x* (1 / 365 / 24 * np.pi * 2) + phase2) - 1)
    return sbase + s1 + s2


function = FunctionForecaster(function=sine_3, initial_params=[3 * np.std(rolling_mean) / (2 ** 0.5), 
                                         0, 
                                         rolling_mean.mean(),
                                         10,
                                         1,
                                         1])

function.fit(rolling_mean)
function.predict(fh=ForecastingHorizon(y_test.index, is_relative=False))
```

During the `fit`, `curve_fit` is used to detect the best parameters. During `predict`, the found parameters and the fh are used to forecast the time series. 

**Describe alternatives you've considered**
* Implement a new forecaster.
* Extend TrendForecaster (idea from @fkiraly)

**Additional context**

The fit code would look as follows: 

```python
def fit(y, X, fh):
        t = ForecastingHorizon(y.index, is_relative=False).to_relative(pd.DatetimeIndex([self._y.index[0]], name=self.cutoff.name, freq=self.cutoff.freq))
    
        self.params_ = curve_fit(self.function, list(t), y.values, self.initial_params)
        return self
```
and the predict code as:
```python

def predict(fh, X):
        t = fh.to_relative(pd.DatetimeIndex([self._y.index[0]], name=self.cutoff.name, freq=self.cutoff.freq))
        return pd.Series(self.function(np.array(t), 
                             *self.params_[0]), index=pd.DatetimeIndex(fh.to_absolute(self.cutoff)))

```

Note using `[self._y.index[0]]` as cutoff  in `to_relative` has the effect that the x values used in the function are natural numbers.

**Comment by fkiraly** [comment]
> Describe alternatives you've considered
> Implement a new forecaster.
> Extend `TrendForecaster` (idea from @fkiraly)

FYI, looking at your PR and the code, I think writing a new estimator is probably the better solution.
