### ISSUE TITLE
[ENH] add unit tests for change point and segmentation plotting functions

### ISSUE THREAD

**Issue by benHeid** [sktime/sktime#5248]
Currently, there is no unit test for:
* plot_time_series_with_profiles 
* plot_time_series_with_change_points

We should add unittests for these plot methods.

Perhaps, we should also move them to utils/plotting.py. Currently, they are located at annotations/plotting/utils.py

_Originally posted by @fkiraly in https://github.com/sktime/sktime/issues/5246#issuecomment-1721581788_

**Comment by adamkells** [comment]
Will take this one if no one already started. Should get to it over weekend.

**Comment by fkiraly** [comment]
Done by @adamkells in https://github.com/sktime/sktime/pull/5509
