### ISSUE TITLE
[MNT] CI error: "Unable to resolve action `codecov/codecov-action@v4`"

### ISSUE THREAD

**Issue by fkiraly** [sktime/sktime#5257]
All CI now errors out, with

Unable to resolve action `codecov/codecov-action@v4`, unable to find version `v4`

Unclear what is going on there, we did not update that recently?

**Comment by yarnabrina** [comment]
This is the issue I guess:

https://github.com/codecov/codecov-action/issues/1089

**Comment by fkiraly** [comment]
ouch. I suppose we need to be more cautious with dependabot...

**Comment by fkiraly** [comment]
I suppose that explains it and there is no further action needed
