### ISSUE TITLE
[ENH] allow multivariate `y` in time series classifiers and regressors, broadcast if estimator is only univariate

### ISSUE THREAD

**Issue by fkiraly** [sktime/sktime#5286]
I think we should:

* allow multivariate `y` in time series classifiers and regressors, and
* introduce a `scitype:y` tag similar to forecasters that tells us whether the estimator is genuinely multivariate
* broadcast `y` prediction if the estimator is not genuinely multivariate

We could do this in different PR; the steps would be:

* replace `y` checks in `BaseClassifier` and `BaseRegressor` by a formulaic `check_is_scitype` check for the `"Table"` scitype (the checker function is in `datatypes`)
* get from that check whether `y` is multivariate
* use `VectorizedDF.vectorize_est` to broadcast across columns of `y` if the estimator is not multivariate but multivariate `y` is received (in a first step, this could simply raise an error, a second PR could introduce broadcasting and tests)

Related: https://github.com/sktime/sktime/issues/5177

Potentially a good first issue for more software minded contributors.

**Comment by Vasudeva-bit** [comment]
I shall go through this and try to fix it.

**Comment by fkiraly** [comment]
ok, it's a moderate challenge, but I'm sure you are up to it (thanks for the arch forecaster!)

Let us know in discord/dev-chat of any blockers or questions!

**Comment by tom123277** [comment]
### **Proposed Implementation**
Hello! I've had a quick read through of the above, here are my thoughts, and areas I think need clarifying. I have only addressed the first part, for sake of simplicity. 

@fkiraly, if you could take the time, I'd appreciate it if you could please review this and give your feedback for my understanding. Given I am new to the codebase I want to ensure I fully understand the workflow. :)

1.  > allow multivariate `y` in time series classifiers and regressors

I think that this requires a change to the `"capability:multivariate": False,` tag in `BaseClassifier` and `BaseRegressor,` setting this tag to `True`. We can grant the class the capability to accept multivariate, then handle y appropriately after the fact. 

^Is there further documentation available on the _tags key value pairs?

2. >introduce a `scitype:y` tag similar to forecasters that tells us whether the estimator is genuinely multivariate

Change the tags in `BaseClassifier` and `BaseRegressor` classes, to accept both univariate and multivariate `y` with `"scitype:y": "both",`. This should mean that all derived classes of these two will also accept both `y` types.

3. >broadcast y prediction if the estimator is not genuinely multivariate

OK, so it sounds like we need some sort of `if...else` here, where we query the type of `y` which has been passed into the class, and if it is univariate, we broadcast the `y` prediction. 

^What does "broadcast" mean in this case? Is this just returning from the `predict` method? If so, what should happen if `y` _is_ multivariate?

**Comment by fkiraly** [comment]
I think this is already implemented by @Vasudeva-bit, you can test by passing a multivariate `y` to any estimator, see https://github.com/sktime/sktime/pull/5408

We should probably have closed the issue.
