### ISSUE TITLE
[ENH] Replace Attrs with Dataclasses

### ISSUE THREAD

**Issue by Alex-JG3** [sktime/sktime#5290]
### Is your feature request related to a problem? Please describe.

The `attrs` package is used in only two places across the entire repository: `sktime/annotation/ggs.py` and `sktime/annotation/igts.py`. Since it is not widely used throughout the package, perhaps we should replace it with `dataclasses` and remove the `attrs` optional dependency dependency.

#### Describe the solution you'd like

* Remove the `get_GGS` method since isolating `attrs` will no longer be needed. https://github.com/sktime/sktime/blob/main/sktime/annotation/ggs.py#L49.
* Remove the `get_IGTS` method since isolating `attrs` will no longer be needed. https://github.com/sktime/sktime/blob/main/sktime/annotation/igts.py#L104.
* Remove `attrs` as a dependency.

#### All current features used from `attrs` appear to have equivalents in `dataclasses`

* `attrs.field(init=False, default=1)` is equivalent to `dataclasses.field(init=False, default=1)`.
* `attrs.asdict` is equivalent `dataclasses.asdict`.

There may be subtle differences between `attrs` and `dataclasses` that are hard for me to see without implementing the changes.

#### What do we lose from using `dataclasses` instead of `attrs`

* `attrs` classes automatically implement a default `__eq__` method, `dataclasses` do not. I don't think comparing instances of the GGS or IGTS models is going to be high priority for most users so I think this is an acceptable loss. Happy to hear otherwise.
* The `attrs` package can do data validation and type checking but this feature is not currently being used in `sktime`. See the `Validators` section of the `attrs` documentation `https://www.attrs.org/en/stable/init.html#validators`.

#### Additional comments

At a glance, the `attrs`/`dataclass` style looks quite far away from the usual tagging style elsewhere in `sktime`. I think removing the `attrs` dependency is worthwhile for the time begin but more work will need to be done to bring it more in line with the rest of `sktime`.

**Comment by fkiraly** [comment]
Agree, very useful suggestion! Helps to reduce dependency footprint, and will probably help structuring the annotation module.
