### ISSUE TITLE
[BUG] latest releases of `sktime` and `statsforecast` are incompatible because of argument differences

### ISSUE THREAD

**Issue by yarnabrina** [sktime/sktime#5295]
## MCVE

```python
from sktime.datasets import load_airline
from sktime.forecasting.statsforecast import StatsForecastAutoARIMA

StatsForecastAutoARIMA().fit(load_airline())
```

## Error

```pycon
>>> from sktime.datasets import load_airline
>>> from sktime.forecasting.statsforecast import StatsForecastAutoARIMA
>>> 
>>> StatsForecastAutoARIMA().fit(load_airline())
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/anirban/sktime-fork/sktime/forecasting/base/_base.py", line 348, in fit
    self._fit(y=y_inner, X=X_inner, fh=fh)
  File "/home/anirban/sktime-fork/sktime/forecasting/base/adapters/_generalised_statsforecast.py", line 108, in _fit
    self._forecaster = self._instantiate_model()
  File "/home/anirban/sktime-fork/sktime/forecasting/base/adapters/_generalised_statsforecast.py", line 73, in _instantiate_model
    params = self._get_validated_statsforecast_params()
  File "/home/anirban/sktime-fork/sktime/forecasting/base/adapters/_generalised_statsforecast.py", line 58, in _get_validated_statsforecast_params
    for sktime_param in sktime_params.keys():
RuntimeError: dictionary changed size during iteration
>>>
```

## Environment

```txt
sktime==0.23, statsforecast==1.5  # working
sktime==0.23, statsforecast==1.6  # failing
```

## Related

#5112, #5149, #5150, #5215, #5207

**Comment by yarnabrina** [comment]
@arnaujc91 I suppose line 60 in the for loop is affecting the size?

https://github.com/sktime/sktime/blob/c5ea83afd718e4bd7026c2bb4fdda35f28ae990c/sktime/forecasting/base/adapters/_generalised_statsforecast.py#L53-L69

**Comment by fkiraly** [comment]
I thought we resolved that?

Unfortunately not, it looks like we forgot to bump the bound and test.

Very much related: https://github.com/sktime/sktime/issues/5292

**Comment by arnaujc91** [comment]
Hi @yarnabrina  i think it could be solved doing:

```python
for sktime_param in list(sktime_params.keys()): 
    if sktime_param not in statsforecast_params: 
        sktime_params.pop(sktime_param) 
        if sktime_param not in sktime_default_params: 
            warn( 
                f"Keyword argument '{sktime_param}' will be omitted as it is" 
                f" not found in the __init__ method " 
                f"from {self._get_statsforecast_class()}. " 
                f"Check your statsforecast version" 
                f"to find out the right API parameters." 
            ) 
return sktime_params


```

instead

**Comment by arnaujc91** [comment]
@fkiraly , @yarnabrina , let me do a fast PR tomorrow and we solve it. Did not see that one coming.

**Comment by yarnabrina** [comment]
It's a different error, but also seems to be from the latest release of `statsforecast`. Please find the logs [here](https://github.com/sktime/sktime/actions/runs/6290833989/job/17078629509?pr=5314).

> AttributeError: 'StatsForecastBackAdapter' object has no attribute 'prediction_intervals'

@luca-miniati Can you please take a look? It seems that the expectation is that `trend_forecaster` should have `prediction_intervals` attribute for conformal intervals.

**Comment by fkiraly** [comment]
@yarnabrina, how does the `TrendForecaster` relate to this? That is not dependent on `statsmodels` but `sktime` native?

**Comment by yarnabrina** [comment]
`trend_forecaster` is an argument of `MSTL` class in `statsforecast`, not talking about the `sktime`'s estimator. This argument is used for predict trend, and seasonality is dealt in `MSTL` with `STL` from `statsmodels`.

Ref. https://github.com/Nixtla/statsforecast/blob/33c2a0a9b30d279bafa1cbdbbe90635be096ebd4/statsforecast/models.py#L4848-L4855

**Comment by fkiraly** [comment]
ah, I see - thanks.

The problem is therefore possibly with the back-adapter? For composites in another framework, you need an adapter and a back-adapter, in order to make them composable with components in `sktime`.

Quite unfortunate that the `statsforecast` interfaces are so unstable that the half-life of the two-way adaptation was just a single minor version...
