### ISSUE TITLE
[DOC] fix formatting of `pre-commit install` in contributor documentation

### ISSUE THREAD

**Issue by fkiraly** [sktime/sktime#5308]
The following paragraph in the code quality checks section
https://www.sktime.net/en/latest/developer_guide/continuous_integration.html#code-quality-checks
formats badly and should be fixed:

![image](https://github.com/sktime/sktime/assets/7985502/26d6cb91-f4de-43ec-9c0f-f9a38e09c720)

In the repository, the location is in the `rst` file of the same name.

**Comment by alhridoy** [comment]
Hi @fkiraly assign me for that. I would love to work on it.

**Comment by alhridoy** [comment]
Hi @fkiraly I made changes to the doc. Would you check my PR?
