### ISSUE TITLE
[ENH] Improve linter check speed by using Ruff

### ISSUE THREAD

**Issue by hazrulakmal** [sktime/sktime#5316]
**Is your feature request related to a problem? Please describe.**

During the community meetup last week, I showcased [`Ruff`](https://docs.astral.sh/ruff/), an extremely fast Python linter, written in Rust. People love `Ruff` for its speed and it has more than 17k stars on GitHub and is extremely actively developed and used in major open-source projects. 

It can be used to substitute some of the existing linters (also comes with pre-commit configurations) that we use such as:
1. Flake8 with plugins such as flake8-bugbear and flake8-print
2. isort
3. pyupgrade
4. pydocstyle

`Ruff` claimed that we can use it to replace the list above. How much it entirely has a one-to-one copy may be questionable. Maybe we can test it out first and see how much it will make changes to the existing codebase.

We have three options if we wanna make ruff as part of dev setup
1. Make `ruff` part of the dev dependency so `ruff` will be run in the background as developers make changes in the codebase.
2. Add `ruff` in the pre-commit configuration and remove those linters that can be replaced. 
3. both, option 1 and 2 together.

**Comment by hazrulakmal** [comment]
This proposal requires agreements from the core developers so tagging @yarnabrina @benHeid @fkiraly @achieveordie for visibility.

**Comment by fkiraly** [comment]
Good first issue then?

`ruff` seems to be sufficiently popular that a generic contributor using it for their work could try migrating

**Comment by yarnabrina** [comment]
Sure, should be straightforward.

However, I should note that unless it's added with very specific configurations, please be ready for a huge amount of changes.

**Comment by fkiraly** [comment]
> However, I should note that unless it's added with very specific configurations, please be ready for a huge amount of changes.

Let's not discourage anyone!

It will be a *fun* and *educational* activity, and friendly core developers being there for you in case you have any questions :-)

**Comment by kurayami07734** [comment]
Please assign me to this issue

**Comment by fkiraly** [comment]
great, thanks!
welcome to this fun and educational activity :-)

Kindly join the discord https://pepy.tech/project/sktime and ping us on the dev-chat channel if you need any help!

**Comment by fkiraly** [comment]
@fnhirwa, can you comment so I can assign you?

**Comment by fnhirwa** [comment]
Yes you can assign me to this item
