### ISSUE TITLE
[DOC] `plot_series` docstring should document the `ax` argument and the figure that is plotted

### ISSUE THREAD

**Issue by fkiraly** [sktime/sktime#5323]
The `plot_series` docstring does not but should document:

* the `ax` argument
* the figure that is plotted

A good example for this does not exist in `sktime` as far as I can find, but one can look at `plot_crossplot_std` in `skpro` for some inspiration (or docstring copy-paste).

**Comment by ShreeshaM07** [comment]
Hello, I started working on this issue . Since I am new to open source any suggestions would be helpful.
