### ISSUE TITLE
[BUG] Dockerized tests not running

### ISSUE THREAD

**Issue by kurayami07734** [sktime/sktime#5352]
**Describe the bug**
Tests provided in the dockerfiles fail to run.

**To Reproduce**
Build from the image and try to run the test

```bash
make dockertest
```

**Expected behavior**
Test suite should run

**Actual behavior**
docker run -it sktime-py38:latest /bin/bash
root@b41d07668e7b:/usr/src/sktime# make test
rm -rf testdir
mkdir -p testdir
cp .coveragerc testdir
cp setup.cfg testdir
python -m pytest
i=================================================================================== test session starts ====================================================================================
platform linux -- Python 3.8.16, pytest-7.4.2, pluggy-1.3.0
Using --randomly-seed=52466984
rootdir: /usr/src/sktime
configfile: setup.cfg
plugins: randomly-3.15.0, anyio-4.0.0, cov-4.1.0, xdist-3.3.1, dash-2.13.0, timeout-2.1.0
timeout: 600.0s
timeout method: signal
timeout func_only: False
ready: 4/4 workerserror: Could not access 'remotes/origin/main'
error: Could not access 'remotes/origin/main'
error: Could not access 'remotes/origin/main'
error: Could not access 'remotes/origin/main'

**Additional context**
Running dockerfiles based on python 3.8, 3.10, 3.11 also fail in a similar manner

**Versions**
Using v0.23.0

**Comment by yarnabrina** [comment]
Possibly caused by https://github.com/sktime/sktime/pull/5019

**Comment by fkiraly** [comment]
my suspicion is, the problem is when it is running `sktime.utils.git_diff.is_module_changed`, and it does not find the `git` branch and the exception is a different one from that is caught - e.g., `git` is not present.

Do you know which exception it is?

**Comment by fkiraly** [comment]
> Possibly caused by https://github.com/sktime/sktime/pull/5019

Yes, most definitely. There is a safeguard though if the branch is not found, it just defaults to testing everything, so I wonder why there is an exception that is not caught.
