### ISSUE TITLE
[ENH] DirectTabularRegressionForecaster does not have the capability to return prediction intervals

### ISSUE THREAD

**Issue by Ram0nB** [sktime/sktime#5357]
**Is your feature request related to a problem? Please describe.**
DirectTabularRegressionForecaster does not have the capability to return:

predict_interval
predict_var
predict_proba
predict_quantiles
Yet all are mentioned as part of the methods available.

**Describe the solution you'd like**
Integration of these features to the class

**Describe alternatives you've considered**
Creating a custom reducer that includes any or all of them.

**Additional context**
Similar issue (#5198) and solution (#5271)

![image](https://github.com/sktime/sktime/assets/45173421/b5b38b0c-c830-4b9d-b987-1c2241474f03)

For my use case, I want to use multiple tabular quantile regressors to create a quantile forecast. To do so, I created a Skpro probabilistic regressor that wraps multiple quantile regressors and uses them to create a quantile prediction with the predict_quantiles method. Would you be interested in having that multiple quantile probabilistic regressor integrated in Skpro?

**Comment by fkiraly** [comment]
> For my use case, I want to use multiple tabular quantile regressors to create a quantile forecast. To do so, I created a Skpro probabilistic regressor that wraps multiple quantile regressors and uses them to create a quantile prediction with the predict_quantiles method. Would you be interested in having that multiple quantile probabilistic regressor integrated in Skpro?

@Ram0nB, absolutely, that's a great idea!
It would be appreciated if you create the appropriate issue in `skpro`.

Related PR which already do sth similar on the `sktime` side with a reducer: https://github.com/sktime/sktime/pull/5271, the equivalent upgrade for `DirectTabularRegressionForecaster would be the second step.

**Comment by fkiraly** [comment]
Solved in https://github.com/sktime/sktime/pull/5536, forgot to close this issue.
