### ISSUE TITLE
[ENH] update base docker images

### ISSUE THREAD

**Issue by achieveordie** [sktime/sktime#5359]
We should consider updating the base images of all docker files. The current base image is bullseye and I suggest upgrading it to bookworm, which is the current stable Debian version.

@yarnabrina has also made two excellent suggestions, which I'm currently in favor of:
1. Not mentioning the patch versions to ensure that we always get the latest one.
2. Using slim versions of the base image to reduce the overall size of the created image. We might have to manually install a few required packages but once we have the necessary packages, it should take minimal effort to maintain the dockerfiles.

Overall, I consider this as an easy and quick win.

Edit: I missed one of the points that @yarnabrina mentioned [here](https://github.com/sktime/sktime/pull/5356#issuecomment-1746594692), it was to consider using `all_extras_pandas2` instead of `all_extras`. I don't have an opinion on this yet but we should also discuss it in this issue.

**Comment by fkiraly** [comment]
there's also this which prevents them from running at all:
https://github.com/sktime/sktime/issues/5352

**Comment by deysanjeeb** [comment]
hi can you assign this issue to me, I can work on this.

**Comment by fkiraly** [comment]
thanks for contributing, all yours!
