### ISSUE TITLE
[BUG] Example of AlignerDTWNumba fails

### ISSUE THREAD

**Issue by benHeid** [sktime/sktime#5363]
**Describe the bug**
The example of `AlignerDTWNumba` is not working.

**To Reproduce**

See example from https://www.sktime.net/en/stable/api_reference/auto_generated/sktime.alignment.dtw_numba.AlignerDtwNumba.html#sktime.alignment.dtw_numba.AlignerDtwNumba
```python
from sktime.utils._testing.series import _make_series
from sktime.alignment.dtw_numba import AlignerDtwNumba
X0 = _make_series()  
X1 = _make_series()  
d = AlignerDtwNumba(weighted=True, derivative=True)  
align = d.fit([X0, X1]).get_alignment()  
```

is failing with: 

```
TypeError: {'df-list': 'X[i] must pd.DataFrame, but found other types at i=[0, 1]', 'numpy3D': "X must be a numpy.ndarray, found <class 'list'>", 'pd-multiindex': "X must be a pd.DataFrame, found <class 'list'>", 'nested_univ': "X must be a pd.DataFrame, found <class 'list'>"}

```

**Expected behavior**
I think this example should work with a series too. 
**Additional context**

**Versions**
<details>

System:
    python: 3.8.10 (default, May 26 2023, 14:05:08)  [GCC 9.4.0]
executable: /home/ws/bi4372/PycharmProjects/sktime/venv/bin/python
   machine: Linux-5.4.0-162-generic-x86_64-with-glibc2.29
Python dependencies:
          pip: 23.2.1
       sktime: 0.23.0
      sklearn: 1.3.1
       skbase: 0.5.2
        numpy: 1.24.4
        scipy: 1.10.1
       pandas: 2.0.3
   matplotlib: None
       joblib: 1.3.2
        numba: 0.58.0
  statsmodels: None
     pmdarima: None
statsforecast: None
      tsfresh: None
      tslearn: None
        torch: None
   tensorflow: None
tensorflow_probability: None

</details>

**Comment by benHeid** [comment]
Note this bug is not currently found in the runs of the CI since the test is skipped...

**Comment by fkiraly** [comment]
Hm, I see - it does not work because "list of series" is not a panel mtype, only "List of `pd.DataFrame`" is.
The easiest fix, without changing supported in-memory types, is hence to ensure that the example uses `pd.DataFrame`.
