### ISSUE TITLE
[BUG] `numba` related failures on main from `tslearn` `lcss`

### ISSUE THREAD

**Issue by fkiraly** [sktime/sktime#5367]
On main, it seems we have the following `numba` related failures:

```
During: resolving callee type: type(CPUDispatcher(<function _local_squared_dist at 0x14fc267a0>))
During: typing of call at /Users/runner/hostedtoolcache/Python/3.10.13/x64/lib/python3.10/site-packages/tslearn/metrics/dtw_variants.py (1421)
```

This is not related to the recent newer `numba` release as we did not upgrade yet.

For test runs with the failures, see here: https://github.com/sktime/sktime/actions/runs/6424459407/job/17445296470?pr=5083

**Comment by benHeid** [comment]
I am supposing that the following is the relevant part of the error message:

```
  >>> iadd(float64, array(float64, 1d, C))
 
There are 18 candidate implementations:
  - Of which 16 did not match due to:
  Overload of function 'iadd': File: <numerous>: Line N/A.
    With argument(s): '(float64, array(float64, 1d, C))':
   No match.
  - Of which 2 did not match due to:
  Operator Overload in function 'iadd': File: unknown: Line unknown.
    With argument(s): '(float64, array(float64, 1d, C))':
   No match for registered cases:
    * (int64, int64) -> int64
    * (int64, uint64) -> int64
    * (uint64, int64) -> int64
    * (uint64, uint64) -> uint64
    * (float32, float32) -> float32
    * (float64, float64) -> float64
    * (complex64, complex64) -> complex64
    * (complex128, complex128) -> complex128

During: typing of intrinsic-call at /Users/runner/hostedtoolcache/Python/3.8.18/x64/lib/python3.8/site-packages/tslearn/metrics/dtw_variants.py (20)
```

To me, it seems that the error is always caused by `dtw_variants`. Have you observed the error somewhere else too?

**Comment by BensHamza** [comment]
I guess the error is caused when running this test : 
```
from sktime.dists_kernels.lcss import LcssTslearn
from sktime.utils._testing.scenarios_transformers_pairwise import TransformerPairwisePanelTransformAsymm
from sktime.dists_kernels.tests.test_all_dist_kernels import TestAllPanelTransformers

scenario = TransformerPairwisePanelTransformAsymm()
estimator_instance = LcssTslearn(global_constraint='sakoe_chiba', sakoe_chiba_radius=2)
testallpaneltransformers = TestAllPanelTransformers()
testallpaneltransformers.test_pairwise_transformers_panel(estimator_instance,scenario)
```

**Comment by benHeid** [comment]
Exactly, a small code snippet to reproduce the error is:

```python
from sktime.datasets import load_unit_test
from sktime.dists_kernels.lcss import LcssTslearn

X, _ = load_unit_test(return_type="pd-multiindex")  # doctest: +SKIP
d = LcssTslearn()  # doctest: +SKIP
distmat = d.transform(X)  # doctest: +SKIP
```

I tested it also with commit d4a0dc3f (I think this is the last one before the release 0.23.0. There, this error also exists. However, I could not find out the exact dependencies of the state of this commit, thus it is not fully reproducing the state three weeks ago.


### Observations:

The method `pwtrafo(X, X2, **params)` in `ts_learn` is called with a list containing a two-dimensional array. Further, the method `lcss` in `dtw_variants.py` of `tslearn` is calling `njit_lcss` with arrays that have the shape (42,24,1). Interestingly, the call of `njit_lcss` would work if the array has the shape (42,24).  The docstring of `njit_lcss` says that the shape of the series should be `shape = (sz1,)`. 

### Open Questions:
*  why is the shape (42,24) working?
*  why do we have not previously observed it?

### Possible fix
* Try to change the shape. However, I do not know if this leads still to correct results!

**Comment by fkiraly** [comment]
> I could not find out the exact dependencies of the state of this commit, thus it is not fully reproducing the state three weeks ago.

I'm 95% percent sure I ran the full test suite with pre-0.23.0 most recent deps and it passed.

I am also 99% percent sure the error was there when dependabot bumped `numba` - because I run the full suite with updated numba and the error was there, so in comparison to the pre-0.23.0 I incorrectly concluded the errors were caused by the `numba` bump, in this issue here that reported the failures first: https://github.com/sktime/sktime/issues/5298

**Comment by fkiraly** [comment]
> why do we have not previously observed it?

still a mystery to me, given the above.

> why is the shape (42,24) working?

I do not know - maybe @rtavenard knows?

**Comment by fkiraly** [comment]
I think we are on the right track! I will check whether we can isolate this for lcss as @BensHamza suggests.

In this case, the fix of @benHeid should get applied to lcss and we report the interface non-compliance to `tslearn`.

**Comment by fkiraly** [comment]
update:

* failure seems indeed isolated to `LcssTslearn`, as @BensHamza has identified
* @benHeid fix (applied to `tslearn` adapter class) works for `LcssTslearn` but seems to cause failures in other distances

Therefore, a potential fix is to move @benHeid's fix down to `LcssTslearn`. This may cause logic bugs but makes the tests pass.

We should investigate with `tslearn` whether this is an interface problem or another bug in `tslearn`. I opened an issue here: https://github.com/tslearn-team/tslearn/issues/483

**Comment by benHeid** [comment]
I have done some further examinations and took another look into the API of tslearn.

* tslearn states that the time series are two dimensional with the first dimension being the time and the second being the features (https://tslearn.readthedocs.io/en/stable/gettingstarted.html#time-series-format)
* I have reproduced the currently failing example  in #5368 Code below. Observations:
    * Without the fix in #5368 the numba error will occur again.
    * The shape of the X1 and X2 is (4, 4, 5). Obviously in this case the reshaping in my proposed fix fails. However, this shape is not compatible to tslearn at all. according to the point above.
    
```python
from sktime.datatypes import convert_to
from sktime.datasets import load_unit_test
from sktime.dists_kernels.lcss import LcssTslearn
from sktime.utils._testing.panel import make_transformer_problem

X, _ = load_unit_test(return_type="pd-multiindex")  # doctest: +SKIP

estimator = LcssTslearn()
X1_list_df = make_transformer_problem(
    n_instances=4, n_columns=4, n_timepoints=5, random_state=1, return_numpy=False
)
X2_list_df = make_transformer_problem(
    n_instances=5, n_columns=4, n_timepoints=5, random_state=2, return_numpy=False
)

X1_num_pan = convert_to(X1_list_df, to_type="numpy3D")
X2_num_pan = convert_to(X2_list_df, to_type="numpy3D")


estimator.transform(X1_list_df, X2_list_df)
```

**Comment by benHeid** [comment]
I have done some further examinations and took another look into the API of tslearn.

* tslearn states that the time series are two dimensional with the first dimension being the time and the second being the features (https://tslearn.readthedocs.io/en/stable/gettingstarted.html#time-series-format)
* I have reproduced the currently failing example  in #5368 Code below. Observations:
    * Without the fix in #5368 the numba error will occur again.
    * The shape of the X1 and X2 is (4, 4, 5). Obviously in this case the reshaping in my proposed fix fails. However, this shape is not compatible to tslearn at all. according to the point above.
    
```python
from sktime.datatypes import convert_to
from sktime.datasets import load_unit_test
from sktime.dists_kernels.lcss import LcssTslearn
from sktime.utils._testing.panel import make_transformer_problem

X, _ = load_unit_test(return_type="pd-multiindex")  # doctest: +SKIP

estimator = LcssTslearn()
X1_list_df = make_transformer_problem(
    n_instances=4, n_columns=4, n_timepoints=5, random_state=1, return_numpy=False
)
X2_list_df = make_transformer_problem(
    n_instances=5, n_columns=4, n_timepoints=5, random_state=2, return_numpy=False
)

X1_num_pan = convert_to(X1_list_df, to_type="numpy3D")
X2_num_pan = convert_to(X2_list_df, to_type="numpy3D")


estimator.transform(X1_num_pan , X2_num_pan )
``` 

So I suppose that tslearn is not supporting our panel data.

**Comment by fkiraly** [comment]
@yarnabrina, that's not 100% true, `tslearn` does support panel data to some extent, and confusion is due to `tslearn`'s docs which does not document this properly.

Some estimators, mostly the metrics, do support panel data, in this case the third numpy dimension is expected to be instance.

However, unfortunately, not all metrics do, and `tslearn` do not test this systematically, nor does it document the expected type properly. That's why the adapter knows two cases, a plain ("cdist", 3D) and a vectorized case (2D with loop).

Back then, I manually tested which cases are supported by which metric.

I now remember that at 0.23.0 we removed this distinction since `tslearn` closed a bug report of mine which, as I read it, rendered all metrics compatible with panel - but that is not true as we see, and `lcss` is the exception.

Hence my experimental fix https://github.com/sktime/sktime/pull/5378

**Comment by fkiraly** [comment]
> However, this shape is not compatible to tslearn at all.

FYI re that, the adapter covers multiple distances and kernels. As with all test suites, the same data is passed to the metric, and the adapter passes the same data to all `tslearn` metrics too. Out of a handful, only `lcss` fails.

**Comment by yarnabrina** [comment]
> @yarnabrina, that's not 100% true, tslearn does support panel data to some extent, and confusion is due to tslearn's docs which does not document this properly.

Did you mean @benHeid by any chance? Not sure where do I come in this discussion, not using either of `tslearn` or `numba`?

**Comment by benHeid** [comment]
@fkiraly I see thanks for the explanations 😊

**Comment by fkiraly** [comment]
> Did you mean @benHeid by any chance?

Yes, I meant @benHeid. I did not want to imply by any means that you are isomorphic :-), it's just there's this dropdown menu when you type the "at" symbol, it is quite small, and at the top appear the most frequent contributors, so it is easy to misclick either way.

**Comment by fkiraly** [comment]
My conjecture on the lcss patch in `tslearn` being faulty, and the issue caused by careless revert of the `sktime` sided bugfix patch seems to be validated:
https://github.com/sktime/sktime/issues/5367

What I will hence do, is merge #5367 with your fix, @benHeid , then merge to main swiftly as the failure is on main.
