### ISSUE TITLE
[ENH] F-Stat as an optional quality measure for ShapeletTransformClassifier

### ISSUE THREAD

**Issue by Anton-Bolenius** [sktime/sktime#5399]
**Is your feature request related to a problem? Please describe.**
Hills et al 2014 claim F-stat measure is both faster and more discriminative  than information gain. It would be nice to have it as an option for the classifier and the transforms in general.

**Describe the solution you'd like**
Add quality_measure as a parameter to the shapelet-related classes, add f-stat as an option next to information_gain (and other quality measures ideally) and replace uses and calculations of the information gain with the quality measure given from the parameter. Now the classes seem to all be hard coded to use information gain.

**Comment by fkiraly** [comment]
Hm, the `sktime` shapelet transform, `ShapeletTransform`, does indeed not support anova f-stat. It is also quite old code which is no longer maintained by its authors.

I see two options here, not mutually exclusive:

* the `pyts` shapelet transform has f-stat as an option next to entropy. We could simply interface `pyts`, it has a number of nice transformers and other estimators that could be interesting. The extension template `transformer_supersimple` should provide a quick starting point for this.
* as the `ShapeletTransform` is abandoned by its authors, someone could pick it up and add f-stat as a criterion. I suppose this would require adding one level of abstraction with regards to the criterion, at any point where `binary_entropy` and related utilities are called.

Would you like to pick up either of these?

**Comment by fkiraly** [comment]
adding the good first issue for the solution pathway "interfacing `pyts`"

**Comment by Abhay-Lejith** [comment]
I'd like to work on the first option of interfacing `pyts`. Any pointers and other examples I could look to for a reference would be really helpful.

**Comment by fkiraly** [comment]
Sure!

The class `RocketPyts` is an example of interfacing a transformer from `pyts`. I would expect the pattern to be easily adaptable - of course there could be complications, as `pyts` interfaces are relatively new, but wouldn't expect any.

**Comment by Abhay-Lejith** [comment]
Ok so I make a new folder called `shapelet_transform` in transformations/panel and put `shapelet_transform.py` in it along with the new `shapelet_transform_pyts.py` that I will be making. Is this correct or any naming conventions I should follow?

**Comment by fkiraly** [comment]
Yes, that's how I would do it - plus an `__init__` which exports the classes from both, to make sure we don't breka any existing imports. I would also make the new `py` files, private, i.e., starting with an underscore, e.g., `_shapelet_transform.py`.
