### ISSUE TITLE
[ENH] `AutoTS` adapter

### ISSUE THREAD

**Issue by fkiraly** [sktime/sktime#5406]
`AutoTS` is a popular autoML library centered around an all-in-one forecaster class of the same name.
https://winedarksea.github.io/AutoTS/build/html/source/intro.html#autots
It would be nice to have an `sktime` conformant interface for it.

I think this is a good first issue and can be solved via the `forecaster_supersimple` extension template.
https://www.sktime.net/en/latest/developer_guide/add_estimators.html

An advanced version - which I would separate out and not consider a good first issue - would be back-adaptation which allows to use `sktime` forecasters as `autots` autoML component forecasters, although I'm not sure how easy or realistic it is (I think: possible but difficult as there is no explicit interface specification I can find).

**Comment by D0rs4n** [comment]
That seems like a perfect entry-point for a newcomer like me, and no-one seems to be interested, so I'd like to tackle this issue!

**Comment by YelenaYY** [comment]
Hi @fkiraly , it seems this issue is still pending, may I work on it?

**Comment by fkiraly** [comment]
yes, there is already a draft PR #5948, but it seems stalled.

It is only 1 month ago, so might be worth checking with @MBristle if he is still working on it. My baseline assumption would be that he isn't, but would reply within the next day or so if he is.

Options are to start from scratch or take the current state of #5948 over the finish line.

**Comment by fkiraly** [comment]
> Lately, it was hard to catch time to bring it over the finish line. I ll try to jump back on it on friday.

Should we try that?
Also, if you foresee you won't find time, you could also join this Friday's meet-up and explain to other contributors who do what the "last steps" are you'd need help with?

**Comment by YelenaYY** [comment]
Sounds good! I will look other good for first issues. Please let me know if any further assistance needed. Thank you @fkiraly @MBristle

**Comment by fkiraly** [comment]
Implemented in https://github.com/sktime/sktime/pull/5948
