### ISSUE TITLE
[ENH] Plotting confidence intervals

### ISSUE THREAD

**Issue by aiwalter** [sktime/sktime#541]
**Is your feature request related to a problem? Please describe.**
Plotting confidence intervalls with the current plot function `from sktime.utils.plotting import plot_series` is not well suitable in case all lines are very close, see picture.

![image](https://user-images.githubusercontent.com/29627036/102230635-6d7cd180-3eed-11eb-82b1-54bbc9f73bac.png)

**Describe the solution you'd like**
Plot like this would be great, with the points as an option ideally. The function could just receive the DataFrame `pred_int` from `y_pred, pred_int = model.predict(fh=fh, return_pred_int=True)
` as an input so this is already well structured and named.

![image](https://user-images.githubusercontent.com/29627036/102231098-e419cf00-3eed-11eb-97ab-9101f6eaa195.png)

**Comment by mloning** [comment]
Yes we could add an `pred_int=None` input argument to `plot_series` with the same time index as one of the other series. As you say, it'd optionally accept a `pd.DataFrame` and plot the intervals.

**Comment by timcashion** [comment]
I'd love to take this on!

**Comment by aiwalter** [comment]
@timcashion cool, I have just seen that in examples `01_forecasting.ipynb` at the end there  is a plot like I proposed. So basically you could just copy this into the function :)

**Comment by aiexplorations** [comment]
1. Would it be a good idea to have CIs at different confidence levels (say, 90%, 95%, 99%) also graphically represented in these plots? 
2. Would it also be good to have a related feature to store the CIs in the forecast as series (series of tuples, or as individual columns)?

**Comment by fkiraly** [comment]
@aiwalter, @timcashion, one of the ideas in the sktime ecosystem was to use interval and distribution returns compatible with the skpro (probabilistic prediction) toolbox https://github.com/alan-turing-institute/skpro 
Unfortunately skpro has gone on hiatus after the disappearance of its maintainer half a year ago - any appetite for taking parts of the development/prototyping on with the ultimate aim of getting nice probabilistic returns for sktime?

**Comment by aiwalter** [comment]
@aiexplorations 
1. We would have to fit multiple models  because most models can only return CIs for a single alpha value. But actually it could work to accept also a list like `alpha = [0.95, 0.9, 0.5]` and loop 3 times over `_fit()` and `predict()`.
2. I think this would change the API because currently `predict()` is returning a `pd.Series` and no `pd.DataFrame`. A better solution could be to return the prediction also when doing `predict(return_pred_int=True)`. Or you can just merge the results of `predict()` and `predict(return_pred_int=True)`? 

@fkiraly thanks for mentioning, I think for now I will rather continue with contributing to `sktime` :)

**Comment by mloning** [comment]
Re 2. if `return_pred_int=True`, both the point predictions (`pd.Series`) and intervals (`pd.DataFrame`) are returned

**Comment by fkiraly** [comment]
>@fkiraly thanks for mentioning, I think for now I will rather continue with contributing to sktime :)

@aiwalter, if you look at the roadmap, it is a necessary pre-condition for time-to-event modelling
https://github.com/alan-turing-institute/sktime/blob/master/docs/source/roadmap.rst
(last paragraph)

So it would count as a contribution to sktime :)

**Comment by John42506176Linux** [comment]
Hello, I was curious what was the progress with this issue and if it would be ok if I could work on this issue.

**Comment by mloning** [comment]
Hi @John42506176Linux - yes there's an open PR here which needs some fixing: https://github.com/alan-turing-institute/sktime/pull/545

**Comment by sral85** [comment]
Hello everybody,
I would like to work on this issue. Is it ok? 
I think I can have a look at the already existing pull-requests and refactor some parts of them.

**Comment by fkiraly** [comment]
Yes, absolutely, @sral85!

Kindly refer to the base class documentation of `predict_quantiles` and `predict_interval` (here https://github.com/alan-turing-institute/sktime/blob/main/sktime/forecasting/base/_base.py or in the API reference) for the new format in which prediction intervals are returned.

Would also appreciate a proposal of function signatures to discuss in this thread before implementation.

**Comment by sral85** [comment]
@fkiraly: I would like to hear your comments on the following proposal:

The current definition of the function plot_series looks like this:
`
def plot_series(
    *series, labels=None, markers=None, x_label=None, y_label=None, ax=None)
`

As already mentioned in the first comment: I would add support for the plotting of quantiles / confidence intervals by including additional arguments:

- `quantiles`: Dataframe returned by the predict_quantiles method
- `intervals`: Dataframe returned by the predict_interval method

By providing a dataframe via `quantiles` additional line plots will be generated. By providing a dataframe via `intervals ` area-plots will be generated.

I suppose that it is desired to specify arguments to change the look of the line plots of the quantiles / area plots of the intervals (markers / labels / ...). The original function already is equipped with a lot of parameters, hence I don't want to introduce these parameters directly into the function definition, but extract them via **kwargs. Extensive documention of possible parameters will be provided.

To sum everything up I propose the following way:
`
def plot_series(
    *series, labels=None, markers=None, x_label=None, y_label=None, ax=None, quantiles = None, intervals = None, **kwargs)
`

The following parameters will be handled via kwargs to handle the labels / markers of the plot:
- labels_quantiles
- labels_intervals
- markers_quantiels
- markers_intervals

**Comment by fkiraly** [comment]
@sral85, thanks, makes a lot of sense!

Minor points:
* the output of `predict_interval` is a special case of the output of `predict_quantiles`, so I'd recommend you only include one pair of arguments, because you could always pass the `predict_interval` output as a `predict_quantiles` output.
* could you be more specific on how you would like to plot the quantiles? E.g., will they be always the same colour as the series, and a funnel plot? Or dotted lines?

Feel free to make a PR - you could start with a draft PR that includes only the docstring of the extended function, and post a picture of an example, or, alternatively, go start implementing right away.

**Comment by kailkuhn** [comment]
Hi everyone,

I'm not really an expert on the topic, but could someone explain to me why the intervals that are calculated using the  **predict_interval** function does not become more uncertain (higher variance) depending on how far in the future the predicted value lies? It doesn't make so much sense to me that uncertainty is constant when predicting many future values of a timeseries.

Thanks

**Comment by aiwalter** [comment]
@kailkuhn can you open a discussion for this with a reproducible code? This issue is about plotting only

**Comment by fkiraly** [comment]
> I'm not really an expert on the topic, but could someone explain to me why the intervals that are calculated using the predict_interval function does not become more uncertain (higher variance) depending on how far in the future the predicted value lies? It doesn't make so much sense to me that uncertainty is constant when predicting many future values of a timeseries.

Yes, please open a new issue and provide code. This sounds like a bug or a problem with the specific estimator.

**Comment by fkiraly** [comment]
closed by https://github.com/sktime/sktime/pull/3825
