### ISSUE TITLE
[MNT] address GHA deprecation messages

### ISSUE THREAD

**Issue by fkiraly** [sktime/sktime#5410]
We should try to address the GHA deprecation message that are consistently raised:

![image](https://github.com/sktime/sktime/assets/7985502/adba7e99-e428-4eb4-b118-2388a5cc51b9)

**Comment by yarnabrina** [comment]
Is it okay to address this as part of #5304? I can create a new job as a pre-requisite for the new test jobs I added?

**Comment by fkiraly** [comment]
sure! that might make most sense, synergy-wise.
