### ISSUE TITLE
[BUG] RecursiveTabularRegressionForecaster for hierarchical data

### ISSUE THREAD

**Issue by anvithats** [sktime/sktime#5440]
**Describe the bug**

I encountered the following error while using the RecursiveTabularRegressionForecaster for hierarchical data.
The error message: "AttributeError: 'VectorizedDF' object has no attribute 'copy'."

**To Reproduce**

```python
from sktime.datasets import load_forecastingdata
from sktime.forecasting.model_selection import ExpandingGreedySplitter
from sktime.forecasting.all import RecursiveTabularRegressionForecaster
from lightgbm import LGBMRegressor

loaded_data, meta_data = load_forecastingdata('m1_monthly_dataset', replace_missing_vals='NAN', value_column_name='series_value', return_type='pd_multiindex_hier', extract_path=None)

#convert the loaded_data['timestamp'] into correct format

splitter = ExpandingGreedySplitter(18, folds=1)
y_train, y_test = list(splitter.split_series(loaded_data))[0]
fh = np.arange(1, 19)

forecaster=RecursiveTabularRegressionForecaster(estimator=LGBMRegressor(), pooling='global')
y_pred = forecaster.fit_predict(y=y_train, fh=fh)

smape = MeanAbsolutePercentageError(symmetric=True)(y_test, y_pred)

```

**Expected behavior**

**Additional context**

**Versions**
<details>

</details>

**Comment by fkiraly** [comment]
I cannot reproduce the issue, can you add your python versions?

I replaced the lightgbm with an sklearn linear regressor:

```python
from sktime.datasets import load_forecastingdata
from sktime.forecasting.model_selection import ExpandingGreedySplitter
from sktime.forecasting.all import RecursiveTabularRegressionForecaster
from sktime.performance_metrics.forecasting import MeanAbsolutePercentageError
from sklearn.linear_model import LinearRegression

loaded_data, meta_data = load_forecastingdata('m1_monthly_dataset', replace_missing_vals='NAN', value_column_name='series_value', return_type='pd_multiindex_hier', extract_path=None)

#convert the loaded_data['timestamp'] into correct format

splitter = ExpandingGreedySplitter(18, folds=1)
y_train, y_test = list(splitter.split_series(loaded_data))[0]
fh = np.arange(1, 19)

forecaster=RecursiveTabularRegressionForecaster(estimator=LinearRegression(), pooling='global')
y_pred = forecaster.fit_predict(y=y_train, fh=fh)

smape = MeanAbsolutePercentageError(symmetric=True)(y_test, y_pred)
```

For me, this code fails, but with `AttributeError: 'pandas._libs.tslibs.offsets.MonthBegin' object has no attribute '_period_dtype_code'`

**Comment by anvithats** [comment]
from sktime.datasets import load_forecastingdata
from sktime.forecasting.model_selection import ExpandingGreedySplitter
from sktime.forecasting.all import RecursiveTabularRegressionForecaster
from sktime.performance_metrics.forecasting import MeanAbsolutePercentageError
from sklearn.linear_model import LinearRegression
import pandas as pd
import numpy as np

loaded_data, meta_data = load_forecastingdata('m1_monthly_dataset', replace_missing_vals='NAN', value_column_name='series_value', return_type='pd_multiindex_hier', extract_path=None)

#convert the loaded_data['timestamp'] into correct format
y = loaded_data.reset_index()
y['timestamp'] = pd.to_datetime(y['timestamp']).dt.to_period('M')
y = y.set_index(['series_name', 'timestamp'])

splitter = ExpandingGreedySplitter(18, folds=1)
y_train, y_test = list(splitter.split_series(y))[0]
fh = np.arange(1, 19)

forecaster=RecursiveTabularRegressionForecaster(estimator=LinearRegression(), pooling='global')
y_pred = forecaster.fit_predict(y=y_train, fh=fh)

smape = MeanAbsolutePercentageError(symmetric=True)(y_test, y_pred)

can you try this?

**Comment by anvithats** [comment]
>Can you try this instead?

>from sktime.datasets import load_forecastingdata
>from sktime.forecasting.model_selection import ExpandingGreedySplitter
>from sktime.forecasting.all import RecursiveTabularRegressionForecaster
>from sktime.performance_metrics.forecasting import MeanAbsolutePercentageError
>from sklearn.linear_model import LinearRegression
>import pandas as pd
>import numpy as np

>loaded_data, meta_data = load_forecastingdata('m1_monthly_dataset', replace_missing_vals='NAN', value_column_name='series_value', return_type='pd_multiindex_hier', extract_path=None)

>#convert the loaded_data['timestamp'] into correct format
>y = loaded_data.reset_index()
>y['timestamp'] = pd.to_datetime(y['timestamp']).dt.to_period('M')
>y = y.set_index(['series_name', 'timestamp'])

>splitter = ExpandingGreedySplitter(18, folds=1)
>y_train, y_test = list(splitter.split_series(y))[0]
>fh = np.arange(1, 19)

>forecaster=RecursiveTabularRegressionForecaster(estimator=LinearRegression(), pooling='global')
>y_pred = forecaster.fit_predict(y=y_train, fh=fh)

>smape = MeanAbsolutePercentageError(symmetric=True)(y_test, y_pred)

**Comment by fkiraly** [comment]
Can you kindly post this as a python code block? Like you did at the top.

**Comment by anvithats** [comment]
> Can you kindly post this as a python code block? Like you did at the top.

Done!!

**Comment by fkiraly** [comment]
I think the reason is a combination of two bugs:

* `predict` orders the sequence of the indices differently from `fit`, it should not change these. It is ordered by alphabet instead, i.e., T99 is the last instance index in `y_pred`, but T617 is the last instance index in `y_train`
* this leads the metrics to end up with different index input, which triggers an error in the logic in `_check_consistent_input`

Workaround is sorting the multi-index lexicographically, i.e., using `y.sort_index()`

**Comment by fkiraly** [comment]
update: not a workaround, this also fails

```python

from sktime.datasets import load_forecastingdata
from sktime.forecasting.model_selection import ExpandingGreedySplitter
from sktime.forecasting.all import RecursiveTabularRegressionForecaster
from sktime.performance_metrics.forecasting import MeanAbsolutePercentageError
from sklearn.linear_model import LinearRegression
import pandas as pd
import numpy as np

loaded_data, meta_data = load_forecastingdata('m1_monthly_dataset', replace_missing_vals='NAN', value_column_name='series_value', return_type='pd_multiindex_hier', extract_path=None)

#convert the loaded_data['timestamp'] into correct format
y = loaded_data.reset_index().sort_index()
y['timestamp'] = pd.to_datetime(y['timestamp']).dt.to_period('M')
y = y.set_index(['series_name', 'timestamp']).sort_index()

splitter = ExpandingGreedySplitter(18, folds=1)
y_train, y_test = list(splitter.split_series(y))[0]
fh = np.arange(1, 19)

forecaster=RecursiveTabularRegressionForecaster(estimator=LinearRegression(), pooling='global')
y_pred = forecaster.fit_predict(y=y_train, fh=fh)

smape = MeanAbsolutePercentageError(symmetric=True)(y_test, y_pred)
```

**Comment by fkiraly** [comment]
Utility to further diagnose the "wrong index" issue:
https://github.com/sktime/sktime/pull/5501
