### ISSUE TITLE
[BUG] MSTL documentation is misleading after 0.24.0 release

### ISSUE THREAD

**Issue by ArturDragunov** [sktime/sktime#5454]
**Describe the bug**

Up until the recent version, MSTL had a note that it can't inverse. The same note is still present in STLTransformer: STLTransformer can not inverse_transform on indices not seen in fit(). This means that for pipelining, the Deseasonalizer or Detrender must be used instead of STLTransformer. This creates a misleading situation for the users who could have assumed that MSTL can inverse_transform. 
**To Reproduce**

```python
from sktime.datasets import load_airline
import pandas as pd
from sktime.forecasting.naive import NaiveForecaster
from sktime.forecasting.compose import TransformedTargetForecaster
from sktime.transformations.series.detrend.mstl import MSTL
from sktime.transformations.series.impute import Imputer
from sktime.forecasting.model_evaluation import evaluate
from sktime.forecasting.model_selection import ExpandingWindowSplitter


y = load_airline()
y.index = pd.PeriodIndex(y.index, freq="d")
data = pd.DataFrame(y)

for i in range(1, 4):
    data['Lag_' + str(i)] = data[y.name].shift(i)
data.dropna(inplace=True)
    
X = data.drop(columns=y.name)
y = data[y.name]

pipe = TransformedTargetForecaster(steps=[
    ("imputer", Imputer(method="mean")),
    ("deseasonalizer", MSTL(periods=[7])),
    ("forecaster", NaiveForecaster(strategy="drift")),
])

cv = ExpandingWindowSplitter(initial_window=15, step_length=6, fh=[1, 2, 3])
results = evaluate(forecaster=pipe, X=X, y=y, cv=cv) #, error_score='raise')
results

```
FitFailedWarning: 
                In evaluate, fitting of forecaster TransformedTargetForecaster failed,
                you can set error_score='raise' in evaluate to see
                the exception message. Fit failed for len(y_train)=15.
                The score will be set to nan.
                Failed forecaster with parameters: TransformedTargetForecaster(steps=[('imputer', Imputer(method='mean')),
                                   ('deseasonalizer', MSTL(periods=[7])),
                                   ('forecaster',
                                    NaiveForecaster(strategy='drift'))]).
                
  result = _evaluate_window(
test_MeanAbsolutePercentageError | fit_time | pred_time | len_train_window | cutoff
-- | -- | -- | -- | --
NaN | 0.018867 | 0.009660 | 15 | NaT
NaN | 0.015766 | 0.007032 | 21 | NaT
NaN | 0.016762 | 0.010788 | 27 | NaT
NaN | 0.014447 | 0.007028 | 33 | NaT

**Expected behavior**

Ideally, MSTL should have an inverse_transform feature available. Otherwise, the documentation description should change.

**Versions**
sktime 0.24.0

</details>

**Comment by fkiraly** [comment]
Hm, both STL and MSTL should be able to inverse transform in theory.

I know the feature was added for STL in one of the recent versions so the `STLTransformer` docstring should be updated at least.

**Comment by ArturDragunov** [comment]
@fkiraly I have a small typo in the issue. I was playing with different versions and forgot to change from 0.23.0 to 0.24.0. The error logs have changed but the output is still the same that MSTL can not inverse_transform on indices not seen in fit(). I will see the changes in the source code for STLTransformer. Will experiment with it.

FitFailedWarning: 
                In evaluate, fitting of forecaster TransformedTargetForecaster failed,
                you can set error_score='raise' in evaluate to see
                the exception message.
                Fit failed for the 0-th data split, on training data y_train with
                cutoff NaT, and len(y_train)=15.
                The score will be set to nan.
                Failed forecaster with parameters: TransformedTargetForecaster(steps=[('imputer', Imputer(method='mean')),
                                   ('deseasonalizer', MSTL(periods=[7])),
                                   ('forecaster',
                                    NaiveForecaster(strategy='drift'))]).


System:
    python: 3.11.4 (main, Jul  5 2023, 14:15:25) [GCC 11.2.0]
   machine: Linux-6.2.0-34-generic-x86_64-with-glibc2.37

Python dependencies:
          pip: 23.1.2
       sktime: 0.24.0
      sklearn: 1.3.0
       skbase: 0.6.0
        numpy: 1.25.2
        scipy: 1.11.1
       pandas: 2.0.3
   matplotlib: 3.7.1
       joblib: 1.3.0
        numba: None
  statsmodels: 0.14.0
     pmdarima: None
statsforecast: None

**Comment by fkiraly** [comment]
I updated the docstring for https://github.com/sktime/sktime/pull/5455.

I looked at MSTL, my intention is just to replicate the STL `inverse_transform`, then it can be used in a transformer pipeline (as a decomposition transformer). The docstring and usage would then be the same.

**Comment by fkiraly** [comment]
Update for `MSTL` is here: https://github.com/sktime/sktime/pull/5457

I also noticed that the decomposition does not give individual components, I opened an issue here https://github.com/sktime/sktime/issues/5458 to track that we should add this as an option for use in a transformed target forecasting pipeline.
