### ISSUE TITLE
[BUG] `HierarchyEnsembleForecaster` returns unexpected predictions if data has only one hierarchy level and forecasters specified by node

### ISSUE THREAD

**Issue by geronimos** [sktime/sktime#5489]
**Describe the bug**

The `HierarchyEnsembleForecaster` returns unexpected predictions if the hierarchy has only one level and different forecasters are specified per node (`by=node`).

**To Reproduce**
The code snippet below is similar to the examples in the [documentation](https://www.sktime.net/en/latest/api_reference/auto_generated/sktime.forecasting.compose.HierarchyEnsembleForecaster.html) but with only one level instead of two and only 3 bottom nodes instead of 7.

```python
from sktime.forecasting.compose import HierarchyEnsembleForecaster
from sktime.forecasting.naive import NaiveForecaster
from sktime.forecasting.trend import PolynomialTrendForecaster, TrendForecaster
from sktime.utils._testing.hierarchical import _bottom_hier_datagen
y = _bottom_hier_datagen(
        no_bottom_nodes=3,
        no_levels=1,
        random_seed=123
)
y.groupby(["l1_agg"]).sum().index

# Example of by = 'node'
forecasters = [
    ('trend', TrendForecaster(), [("__total")]),
    ('poly', PolynomialTrendForecaster(degree=2), [('l1_node01')]),
]
forecaster = HierarchyEnsembleForecaster(
                forecasters=forecasters,
                by='node', default=NaiveForecaster()
)
forecaster.fit(y, fh=[1, 2, 3])
y_pred = forecaster.predict()
y_pred
```
*Output:*
<table border="1" class="dataframe">
  <thead>
    <tr style="text-align: right;">
      <th></th>
      <th></th>
      <th>passengers</th>
    </tr>
    <tr>
      <th>l1_agg</th>
      <th>timepoints</th>
      <th></th>
    </tr>
  </thead>
  <tbody>
    <tr>
      <th rowspan="3" valign="top">__total</th>
      <th>1961-01</th>
      <td>9024.895980</td>
    </tr>
    <tr>
      <th>1961-02</th>
      <td>9075.494395</td>
    </tr>
    <tr>
      <th>1961-03</th>
      <td>9126.092810</td>
    </tr>
    <tr>
      <th rowspan="6" valign="top">l1_node01</th>
      <th>1961-01</th>
      <td>497.671704</td>
    </tr>
    <tr>
      <th>1961-01</th>
      <td>432.000000</td>
    </tr>
    <tr>
      <th>1961-02</th>
      <td>501.352085</td>
    </tr>
    <tr>
      <th>1961-02</th>
      <td>432.000000</td>
    </tr>
    <tr>
      <th>1961-03</th>
      <td>505.046482</td>
    </tr>
    <tr>
      <th>1961-03</th>
      <td>432.000000</td>
    </tr>
    <tr>
      <th rowspan="3" valign="top">l1_node02</th>
      <th>1961-01</th>
      <td>5893.819230</td>
    </tr>
    <tr>
      <th>1961-02</th>
      <td>5893.819230</td>
    </tr>
    <tr>
      <th>1961-03</th>
      <td>5893.819230</td>
    </tr>
    <tr>
      <th rowspan="3" valign="top">l1_node03</th>
      <th>1961-01</th>
      <td>1919.395692</td>
    </tr>
    <tr>
      <th>1961-02</th>
      <td>1919.395692</td>
    </tr>
    <tr>
      <th>1961-03</th>
      <td>1919.395692</td>
    </tr>
  </tbody>
</table>
</div>

**Expected behavior**
*Output:*
<div>
<table border="1" class="dataframe">
  <thead>
    <tr style="text-align: right;">
      <th></th>
      <th></th>
      <th>passengers</th>
    </tr>
    <tr>
      <th>l1_agg</th>
      <th>timepoints</th>
      <th></th>
    </tr>
  </thead>
  <tbody>
    <tr>
      <th rowspan="3" valign="top">__total</th>
      <th>1961-01</th>
      <td>9024.895980</td>
    </tr>
    <tr>
      <th>1961-02</th>
      <td>9075.494395</td>
    </tr>
    <tr>
      <th>1961-03</th>
      <td>9126.092810</td>
    </tr>
    <tr>
      <th rowspan="3" valign="top">l1_node01</th>
      <th>1961-01</th>
      <td>497.671704</td>
    </tr>
    <tr>
      <th>1961-02</th>
      <td>501.352085</td>
    </tr>
    <tr>
      <th>1961-03</th>
      <td>505.046482</td>
    </tr>
    <tr>
      <th rowspan="3" valign="top">l1_node02</th>
      <th>1961-01</th>
      <td>5893.819230</td>
    </tr>
    <tr>
      <th>1961-02</th>
      <td>5893.819230</td>
    </tr>
    <tr>
      <th>1961-03</th>
      <td>5893.819230</td>
    </tr>
    <tr>
      <th rowspan="3" valign="top">l1_node03</th>
      <th>1961-01</th>
      <td>1919.395692</td>
    </tr>
    <tr>
      <th>1961-02</th>
      <td>1919.395692</td>
    </tr>
    <tr>
      <th>1961-03</th>
      <td>1919.395692</td>
    </tr>
  </tbody>
</table>
</div>

**Additional context**
The predictions for the node `l1_node01` are duplicated. The first occurrences are the predictions from `PolynomialTrendForecaster`. The second occurrences are predictions of the `NaiveForecaster` which is configured as default. If using two hierarchy levels as in the documentation the predictions are as expected (i.e., no duplicates from the default predictor).

I tried to stay close to the example in the doc. However, maybe I am just using the `HierarchyEnsembleForecaster` class wrong.

**Versions**

System:
    python: 3.11.5 | packaged by conda-forge | (main, Aug 27 2023, 03:35:23) [Clang 15.0.7 ]
executable: ../anaconda3/envs/sktime311/bin/python
   machine: macOS-14.0-x86_64-i386-64bit

Python dependencies:
          pip: 23.2.1
       sktime: 0.24.0
      sklearn: 1.3.0
       skbase: 0.5.1
        numpy: 1.25.2
        scipy: 1.11.2
       pandas: 2.0.3
   matplotlib: 3.7.2
       joblib: 1.3.2
        numba: None
  statsmodels: 0.14.0
     pmdarima: 2.0.3
statsforecast: None
      tsfresh: None
      tslearn: None
        torch: None
   tensorflow: None
tensorflow_probability: None

**Comment by fkiraly** [comment]
Yes, looks like a bug - FYI @VyomkeshVyas.

@geronimos, do you have further information on the exact condition? Does this always happen for a single node?

**Comment by geronimos** [comment]
I experienced the behavior for the following conditions:
1. (One hierarchy level only) AND (Specify more than one forecaster in the list `forecasters`)
2. (One hierarchy level only) AND (Specifying all forecasters in `forecasters` while having set `default=None`)

Condition 2 results in an error. I think it relates to the reported bug, because if the data has more than 1 hierarchy level, setting `default=None` does not result in an error if all forecasters are specified in the `forecasters` list correctly.

Below is another example showing the behavior on condition 1. The duplicates occur for all forecasters specified in `forecasters` except the first tuple in the list.

```python
# Example of by = 'node'
forecasters = [
    # ('trend', TrendForecaster(), [('__total'), ('l1_node01'), ('l1_node02'), ('l1_node03')]),
    ("trend", TrendForecaster(), ["l1_node01"]),
    ("polytrend", PolynomialTrendForecaster(), ["l1_node02", "l1_node03"]),
    ("naive", NaiveForecaster(), ["__total"]),
]
forecaster = HierarchyEnsembleForecaster(
    forecasters=forecasters, by="node", default=NaiveForecaster()
)
forecaster.fit(y, fh=[1, 2, 3])
y_pred = forecaster.predict()
y_pred
```

*Output:*

<table border="1" class="dataframe">
  <thead>
    <tr style="text-align: right;">
      <th></th>
      <th></th>
      <th>passengers</th>
    </tr>
    <tr>
      <th>l1_agg</th>
      <th>timepoints</th>
      <th></th>
    </tr>
  </thead>
  <tbody>
    <tr>
      <th rowspan="6" valign="top">__total</th>
      <th>1961-01</th>
      <td>8245.214923</td>
    </tr>
    <tr>
      <th>1961-01</th>
      <td>8245.214923</td>
    </tr>
    <tr>
      <th>1961-02</th>
      <td>8245.214923</td>
    </tr>
    <tr>
      <th>1961-02</th>
      <td>8245.214923</td>
    </tr>
    <tr>
      <th>1961-03</th>
      <td>8245.214923</td>
    </tr>
    <tr>
      <th>1961-03</th>
      <td>8245.214923</td>
    </tr>
    <tr>
      <th rowspan="3" valign="top">l1_node01</th>
      <th>1961-01</th>
      <td>472.944444</td>
    </tr>
    <tr>
      <th>1961-02</th>
      <td>475.601628</td>
    </tr>
    <tr>
      <th>1961-03</th>
      <td>478.258812</td>
    </tr>
    <tr>
      <th rowspan="6" valign="top">l1_node02</th>
      <th>1961-01</th>
      <td>6452.372049</td>
    </tr>
    <tr>
      <th>1961-01</th>
      <td>5893.819230</td>
    </tr>
    <tr>
      <th>1961-02</th>
      <td>6488.620061</td>
    </tr>
    <tr>
      <th>1961-02</th>
      <td>5893.819230</td>
    </tr>
    <tr>
      <th>1961-03</th>
      <td>6524.868074</td>
    </tr>
    <tr>
      <th>1961-03</th>
      <td>5893.819230</td>
    </tr>
    <tr>
      <th rowspan="6" valign="top">l1_node03</th>
      <th>1961-01</th>
      <td>2099.579486</td>
    </tr>
    <tr>
      <th>1961-01</th>
      <td>1919.395692</td>
    </tr>
    <tr>
      <th>1961-02</th>
      <td>2111.272705</td>
    </tr>
    <tr>
      <th>1961-02</th>
      <td>1919.395692</td>
    </tr>
    <tr>
      <th>1961-03</th>
      <td>2122.965924</td>
    </tr>
    <tr>
      <th>1961-03</th>
      <td>1919.395692</td>
    </tr>
  </tbody>
</table>
</div>

Referring to condition #2, I tried the following:
```python
# Example of by = 'node'
forecasters = [
    ("trend", TrendForecaster(), [('__total'), ('l1_node01'), ('l1_node02'), ('l1_node03')]),
]
forecaster = HierarchyEnsembleForecaster(
    forecasters=forecasters, by="node", default=None
)
forecaster.fit(y, fh=[1, 2, 3])
y_pred = forecaster.predict()
y_pred
```
*Output:*
```shell

File ~/opt/anaconda3/envs/sktime311/lib/python3.11/site-packages/sktime/forecasting/base/_base.py:383, in BaseForecaster.fit(self, y, X, fh)
    381 # we call the ordinary _fit if no looping/vectorization needed
    382 if not vectorization_needed:
--> 383     self._fit(y=y_inner, X=X_inner, fh=fh)
    384 else:
    385     # otherwise we call the vectorized version of fit
    386     self._vectorize(\"fit\", y=y_inner, X=X_inner, fh=fh)

File ~/opt/anaconda3/envs/sktime311/lib/python3.11/site-packages/sktime/forecasting/compose/_hierarchy_ensemble.py:186, in HierarchyEnsembleForecaster._fit(self, y, X, fh)
    183 x = X
    185 # check forecasters
--> 186 self.forecasters_ = self._check_forecasters(y, z)
    187 self.fitted_list = []
    189 if y.index.nlevels == 1:

File ~/opt/anaconda3/envs/sktime311/lib/python3.11/site-packages/sktime/forecasting/compose/_hierarchy_ensemble.py:583, in HierarchyEnsembleForecaster._check_forecasters(self, y, z)
    581     z_nds_not_found = z.index.droplevel(-1).unique().difference(nodes_tx)
    582     if self.default is None and len(z_nds_not_found) > 0:
--> 583         raise ValueError(
    584             f\"One estimator per node required. Following nodes of \"
    585             f\"data are missing estimator : {list(z_nds_not_found)}\"
    586         )
    588 return forecasters

ValueError: One estimator per node required. Following nodes of data are missing estimator : ['__total', 'l1_node01', 'l1_node02', 'l1_node03']"
```

I hope this gives further insight. Please let me know if not.

**Comment by fkiraly** [comment]
Note to devs: it is strange that the tests do not detect this, as it should be detectable through duplication of indices. The tests usually check that the actual index is the expected, so it seems the test cases for the forecasters do not cover the bug.
