### ISSUE TITLE
[ENH] FourierFeatures more periodicity options

### ISSUE THREAD

**Issue by Ram0nB** [sktime/sktime#5512]
## Is your feature request related to a problem? Please describe.

The current implementation of Sktime's FourierFeatures states the following:

> 
> Fourier Series terms can be used as explanatory variables for the cases of multiple
> seasonal periods and or complex / long seasonal periods [1]_, [2]_. For every
> seasonal period, $sp$ and fourier term $k$ pair there are 2 fourier
> terms sin_sp_k and cos_sp_k:
> - sin_sp_k = $sin(\frac{2 \pi k t}{sp})$
> - cos_sp_k = $cos(\frac{2 \pi k t}{sp})$
> 
> Where $t$ is the number of time steps elapsed from the beginning of the time
> series.

> Parameters
> 
> sp_list : List[float]
> - list of seasonal periods

This implementation however poses a serious limitation when the user is interested in periodicity that occurs with different interval lengths. Some examples:
- monthly
    - can differ in length due to different number of days per month
- yearly
    - can differ in length due to leap year

## Describe the solution you'd like
In addition to expressing periodicity as the number of timesteps, we give the user the option to define periodicity as a pandas period alias or as a column name in the input data. The enhanced docstring is as follows:

> 
> Fourier Series terms can be used as explanatory variables for the cases of multiple
> seasonal periods and or complex / long seasonal periods [1]_, [2]_. For every
> seasonal period, $sp$ and fourier term $k$ pair there are 2 fourier
> terms sin_sp_k and cos_sp_k:
> - sin_sp_k = $sin(\frac{2 \pi k t}{sp})$
> - cos_sp_k = $cos(\frac{2 \pi k t}{sp})$
> 
> Where $t$ is the elapsed time since the beginning of the seasonal period and
> $sp$ the total time of the seasonal period.

> Parameters
> 
> sp_list : List[float or str]
> - List of seasonal periods. A float defines the length of the seasonality starting at the beginning of the time series in number of timesteps. A string should match the column name in X that contains the $t/sp$ values or should match a pandas period alias: https://pandas.pydata.org/pandas-docs/stable/user_guide/timeseries.html#period-aliases

See the #5513 for the implementation of the proposed solution.

## Describe alternatives you've considered
None, as the proposed solution:
- is easy to understand for the user
- offers great flexibility for the user
- does not change the current functionality in any way

**Comment by fkiraly** [comment]
Nice idea!
Yes, offsets can be irregular like leap days and such.

Minor thing: I would clarify the options by replacing the long docstring paragraph for `sp_list` by a bullet point list.
