### ISSUE TITLE
[ENH] de-duplicate time series forest from `series_as_features` and `classification`

### ISSUE THREAD

**Issue by fkiraly** [sktime/sktime#5520]
It seems there is significant code duplication in the time series forests in `series_as_features` and `classification`, this should be deduplicated. Given that `series_as_features` is deprecated and to be moved to other modules, we should primarily check whether there is any logic in `series_as_features` that isn't already in `classification`.

If there isn't, we can just delete the location imo, as it seems absolutely non-obvious. Or, we can do a safer deprecation with import from `classification` and warning.

The two locations are:

* `classification.interval_based._tsf`
* `series_as_features.base.estimators.interval_based._tsf` (I did not know this existed and this is quite weird, e.g., why is it in the base module)

My suspicion is that at some point a copy-paste error or click-and-move error happened, otherwise I cannot explain why an estimator like TSF would be in a base module.

FYI @YHallouard

**Comment by YHallouard** [comment]
Hi @fkiraly, 

Is it me or is it already done ? It seems that only one TSF in he project in classification.interval_based._tsf 
Am I wrong ?

**Comment by fkiraly** [comment]
It's moved, not deduplicated: https://github.com/sktime/sktime/pull/5751

Though after looking at it, I wonder whether further efforts are meaningful or desirable.

Seems like two separate implementations - unfortunately, the one that claims to be modular isn't really modular to the user.

**Comment by YHallouard** [comment]
Yes this is what I wanted to tell you in that [com](https://github.com/sktime/sktime/pull/5338#issuecomment-1747770472). 

The main difference is that the implementation of the TSF which is based on this paper creates a variable space (random interval + feature extraction) per tree. With the RandomIntervalFeatureExtractor, a RandomForestClassifier estimator and a suitable feature extractor, we will produce something similar except that the variable space will be shared by the entire forest.

**Comment by fkiraly** [comment]
ok, so I suppose we can close this?

**Comment by YHallouard** [comment]
Yes I think so
