### ISSUE TITLE
[BUG] new CI elements named "validate code quality"

### ISSUE THREAD

**Issue by fkiraly** [sktime/sktime#5523]
The new CI is great, but it shows up as "validate code quality workflow" in the "actions" tab, which seems to imply that all of it is just about code quality.

Not sure why this is the case, seems like a bug combined with some GHA naming convention. Not too consequential but likely confusing.

**Comment by fkiraly** [comment]
FYI @yarnabrina

**Comment by yarnabrina** [comment]
The new Ci works in this way:

1. Code quality workflow is triggered with the meaningful name.
2. If and only if it passes, it triggers testing workflows from this workflow itself. So their name appears as child of parent one.

This explains why it's shown as you described, but I don't know what to change it to and how. If you have any suggestions, please let me know. 

Old CI didn't have this as every new job was copy pasting similar code blocks.

**Comment by fkiraly** [comment]
My optimal solution changes the appearance here:
![image](https://github.com/sktime/sktime/assets/7985502/947ca038-b155-4510-9b5b-5ee43ed73c39)

to something similar to "test by module"

**Comment by fkiraly** [comment]
resolved in https://github.com/sktime/sktime/pull/5713
