### ISSUE TITLE
[ENH] new CI not covered by `cancel` workflow

### ISSUE THREAD

**Issue by fkiraly** [sktime/sktime#5525]
Previously, updates to a PR would cancel jobs arising from previous versions immediately before starting new jobs.

This does not seem to extend to the new CI, which can lead to a large amount of jobs being triggered

FYI @yarnabrina.

**Comment by yarnabrina** [comment]
I am aware and it is intentional from my part. Old CI uses it only for install and test workflow and not for others as well, and the action itself recommends not using it and switch to newer GHA keywords.

My plan was to explore this after old vs new and etc. CI discussions are over.

**Comment by fkiraly** [comment]
> My plan was to explore this after old vs new and etc. CI discussions are over.

Ok - don't think it's a "vs" discussion imo. My priority in this is not reducing case coverage.

**Comment by yarnabrina** [comment]
@fkiraly can we close this? It's covered by #6074 I think.

**Comment by fkiraly** [comment]
yes, agree
