### ISSUE TITLE
[ENH] Add support for custom joblib backends

### ISSUE THREAD

**Issue by SmirnGregHM** [sktime/sktime#5535]
**Is your feature request related to a problem? Please describe.**
I use databricks as an MLOps platform, and databricks is based on Apache Spark. Joblib does not support spark out-of-the-box, but there is an official extension https://github.com/joblib/joblib-spark. Since f2820e1aa4d2b2c5cf509acc44005ef0ba3d8da7, I can't simply do `.fit(..., backend='spark')`. Joblib supports custom backends, and other users might want to use them as well.

**Describe the solution you'd like**
Something like:
```python

if backend in backend_dict:
    backend_name = backend_dict[backend] 
else:
    try:
        joblib.Parallel(backend=backend)
        # backend is registered in joblib
        backend_name = 'joblib'
        # optionally: backend_dict[backend] = 'joblib'
    except:
        # backend is not found in joblib
        pass

para_fun = para_dict[backend_name] 

``` 
https://github.com/sktime/sktime/blob/80470f800223894ce09c00fab26864b8bbc67c57/sktime/utils/parallel.py#L61-L62

**Describe alternatives you've considered**
* I did not find a documented interface to list all available backends in joblib. Internally, they use `joblib.parallel.BACKENDS`. But as it is not documented thus can be unstable, I suggest `try...except`. 
* `backend_name` can be passed in addition to `backend`, and only `None` default value would use the `backend_dict`

As always, thank you for maintaining this awesome package!

**Comment by fkiraly** [comment]
@SmirnGregHM, I see, currently this is not possible because the `backend` parameter is the only one you cannot pass to `joblib`, via the common parallelization backend, right?

**Comment by fkiraly** [comment]
You are aware though that the standard `joblib` backends can be addressed and configured via the `backend` and `backend_params` parameters, or the `set_config` counterpart, in parallelized hierarchical fitting, grid search, and the like?

**Comment by fkiraly** [comment]
Attempted fix here: https://github.com/sktime/sktime/pull/5537

Apologies, I was not aware that previously, arbitrary `backend`-s could be used, including 3rd party ones. It was certainly not documented, or tested.

Would appreciate your opinion on #5537, and how to test it. #5537 adds the possibility in every place parallelization is used via the common backend.

**Comment by fkiraly** [comment]
Another option would be to have just one backend string, `"joblib"`, and leave the `joblib` backend choice as a key `"backend"`, in `backend_params`. Or, would that be too confusing, since we have two layers of backends, and two parameters called `backend`?
