### ISSUE TITLE
[BUG] reducers remove index name from `pd.Series`

### ISSUE THREAD

**Issue by fkiraly** [sktime/sktime#5540]
The reducers remove index names from `pd.Series`, i.e., they are not present in `predict` outputs.
See this test run: https://github.com/sktime/sktime/actions/runs/6777533759

In my opinion, they should be as in the `fit` input.

However, the current tests check against them being removed, as opposed to them being preserved (`test_list_reduction`, `test_direct_reduction`, `test_recursive_reduction`), which seems odd.

The reason why the runs are failing is that I have replaced the reducer index generation logic with generic logic from `ForecastingHorizon`, and it now clashes with the tested expectation.

Surely that is a bug, in the test? But then again, someone must have thought something when creating the check.

**Comment by ShreeshaM07** [comment]
Does this issue still need to be addressed I see that the `index_names` is already being checked  by `check_eval(y_pred.index.names, index_names)` . Is it still failing the tests?

**Comment by fkiraly** [comment]
Hm, I am guessing this has been superseded by more stringent tests.

The scenario `ForecasterFitPredictUnivariateNoXLongFh` contains a `pd.Series` with a `name`, and `test_predict_series_name_preserved` explicitly tests for this, added in #4157.

I would say this is a case of the bug report being not closed by accident, closing.

**Comment by fkiraly** [comment]
Thanks for bringing this up and checking, @shreesham07!
