### ISSUE TITLE
[BUG] ValueError: Input X contains NaN when global forecasting 

### ISSUE THREAD

**Issue by kostasek** [sktime/sktime#5558]
**Describe the bug**

There seems to be a strange problem when I try to use certain columns of my dataset in a global forecasting model since I get a ValueError: Input X contains NaN even though my data set does not contain any nan. In certain cases it works as it is supposed to but in other cases it raises an Error (see pictures). I have checked the lengths of the data and seem fine. 
Unfortunately, the dataset is not publicly available so I cannot upload the code. Any idea why is this happening?

![1](https://github.com/sktime/sktime/assets/78386537/ae18dffa-592a-409a-b560-c50e28a9ff03)
![2](https://github.com/sktime/sktime/assets/78386537/dca0f317-d4d4-4ccd-9556-5dbbbc52c914)
![3](https://github.com/sktime/sktime/assets/78386537/e9718b11-9436-4164-b884-017a33b0dbab)
![4](https://github.com/sktime/sktime/assets/78386537/af6f0f3e-8833-4ee7-978c-3a7b72f02105)
![5](https://github.com/sktime/sktime/assets/78386537/b6d001c2-f397-4618-9738-55592960b5a9)
![6](https://github.com/sktime/sktime/assets/78386537/a0eeb2a1-2bc9-4166-8ff3-bd19db8c604a)
![7](https://github.com/sktime/sktime/assets/78386537/fa642a2f-7fe8-4f6f-aa1c-e7699182b868)
![8](https://github.com/sktime/sktime/assets/78386537/c9cc346d-5939-42c6-ae8c-11ca8509b8c8)
![9](https://github.com/sktime/sktime/assets/78386537/64fc786a-c02d-4bd7-a075-7b46447689ee)
![10](https://github.com/sktime/sktime/assets/78386537/bc2da4ae-bd41-4f39-ad65-dee93241561f)
![11](https://github.com/sktime/sktime/assets/78386537/c505ecf8-49c2-4423-adb8-571f0272cd9d)

**To Reproduce**

```python
<Paste your code here>
```

**Expected behavior**

**Additional context**

**Versions**
<details>

0.24.1

</details>

**Comment by fkiraly** [comment]
FYI @benHeid, does this perhaps have to do with the shifting?

Also, @kostasek, are you able to reproduce the issue with dummy data of the same shape? E.g., just generate data frames with random entries and try to run your code.

**Comment by kostasek** [comment]
I just figured out that I had selected the column twice, so the problem arised from that. Sorry for the inconvenience!

**Comment by fkiraly** [comment]
no worries, thanks for reporting!
