### ISSUE TITLE
[BUG] behaviour of new CI changed suddenly

### ISSUE THREAD

**Issue by yarnabrina** [sktime/sktime#5559]
As observed in https://github.com/sktime/sktime/pull/5447 and https://github.com/sktime/sktime/pull/5339, new CI is not behaving as it was during the original PR and it's diagnostic ones. It seems to have changed the behaviour ever since the introduction of the new modifications.

Observations about `.github/workflows/test_components.yml` from both the PR's:

1. `detect` job works successfully and detect what all component needs to be tested.
2. `test` job does not even get detected by the CI, but it should run for detected components.
3. This does not happen for `detect_components_without_extras` + `test_components_without_extras` combination.

Possibilities (just guesses at this point):

1. similar names have some conflicts?
2. small typo somewhere?
3. change in GHA behaviour?
4. change in action behaviour?

**Comment by fkiraly** [comment]
hm, should we try a revert for diagnosis?

**Comment by yarnabrina** [comment]
Yes, probably. If you take a look at the dependabot PR's, the jobs to validate extra is also skipped, but that should have trigger all those 100+ jobs to test the installs. Do you know if something significant have changed recently in GHA or in sktime configuration somewhere?

The only thing I can remember is that these all of these were working fine before I changed the condition to trigger jobs only if code quality checks pass. Earlier, all worked fine (at least based on number of jobs and logs).
