### ISSUE TITLE
[BUG] ConformalInterval Memory Usage

### ISSUE THREAD

**Issue by benHeid** [sktime/sktime#5569]
**Describe the bug**
Disclaimer: Not sure if really a bug or more a request.

Currently, the ConformalInterval is not very memory efficient, since it constructs internally a dataframe with the size of len(time series) x len(time series) (line 420). However, the matrix represented by this dataframe is sparse for two reasons:
1. It is an upper triangular matrix by definition.
2. Due to the `sample_frac` parameter, multiple rows will stay completely empty. 

Thus, I would propose to use a sparse matrix here instead of a normal dataframe. Thus, the definition of the dataframe would need to be replaced with: 

```python
residuals_matrix = pd.DataFrame.sparse.from_spmatrix(scipy.sparse.csr_array((len(full_y_index), len(full_y_index))), 
                                                             index=full_y_index, columns=full_y_index)
```

**Comment by benHeid** [comment]
Small experiment to show the difference/effect:

```python
import pandas as pd
import time 
import sys
import scipy

t0 = time.time()
df_sparse = pd.DataFrame.sparse.from_spmatrix(scipy.sparse.csr_array((10000, 10000)), index=range(10000), columns=range(10000))
print("Time to create sparse df:", time.time() - t0, "seconds")

t0 = time.time()
df_dense = pd.DataFrame(index=range(10000), columns=range(10000))
print("Time to create dense df:", time.time() - t0, "seconds")

print("Size of sparse df:", sys.getsizeof(df_sparse), "bytes")
print("Size of dense df:", sys.getsizeof(df_dense), "bytes")
```

**Output**

```
Time to create sparse df: 1.962019443511963 seconds
Time to create dense df: 5.920591592788696 seconds
Size of sparse df: 164 bytes
Size of dense df: 3200000164 bytes
```

**Comment by fkiraly** [comment]
Makes sense!

Originally, `sample_frac` was not an option, if I remember, so it was not designed for sparsity.

FYI @bethrice44 who worked on these and other extension features.
(I suppose you had only moderately small datasets so the memory issue was not noticeable)
