### ISSUE TITLE
[BUG] `ForecastingHorizon.to_absolute` is loosing tz information from `cutoff`

### ISSUE THREAD

**Issue by benHeid** [sktime/sktime#5584]
**Describe the bug**
The `to_absolute` method from `ForecastingHorizon` does not keep the `tz` information from `cutoff`.

**To Reproduce**

```python
cutoff = pd.Timestamp("2020-01-01", tz="utc")
fh_absolute = ForecastingHorizon(range(100), freq="h").to_absolute(cutoff)
print(fh_absolute[0].tz, cutoff.tz)
# Output: None, UTC
```

**Expected behavior**
The time zone information is kept

**Comment by fkiraly** [comment]
this may be a previous instance, which might contain a fix in the instance of a single forecaster:

https://github.com/sktime/sktime/pull/5464

**Comment by fkiraly** [comment]
I am just adding a link to this relevant resource:
https://xkcd.com/2867/
