### ISSUE TITLE
[BUG] `StatsForecastBackAdapter` incorrectly passes `1-coverage` as `StatsForecast` level

### ISSUE THREAD

**Issue by sd2k** [sktime/sktime#5586]
**Describe the bug**

I'm not 100% sure if this is just working as intended since it's pretty explicit in the code (see [here](https://github.com/sktime/sktime/blob/df21a0c0275ebf28deb30efac5d469c9f0d178e3/sktime/forecasting/base/adapters/_generalised_statsforecast.py#L507) and [here](https://github.com/sktime/sktime/blob/df21a0c0275ebf28deb30efac5d469c9f0d178e3/sktime/forecasting/base/adapters/_generalised_statsforecast.py#L535)), but it seems the `StatsForecastBackAdapter` is taking the coverage argument passed by the user and passing it to StatsForecast as `level=1-coverage`. So doing something like this:

```python
import pandas as pd

from sktime.datasets import load_airline
from sktime.forecasting.base import ForecastingHorizon
from sktime.forecasting.statsforecast import StatsForecastMSTL

y = load_airline()

model = StatsForecastMSTL(season_length=[12])
model.fit(y)
fh_index = pd.PeriodIndex(pd.date_range("1961-01", periods=36, freq="M"))
fh = ForecastingHorizon(fh_index, is_relative=False)
model.predict_interval(fh, coverage=0.95)
```

actually passes `level=[5.0]` to StatsForecast.

**To Reproduce**

See failing test case added to [this fork](https://github.com/sktime/sktime/compare/main...sd2k:sktime:statsforecast-mstl-level-coverage-error)

**Expected behavior**

I _think_ that the level should be passed through as-is, but I may be missing something 🤔 

**Additional context**

N/A

**Versions**
<details>
System:
    python: 3.11.1 (main, Dec 28 2022, 11:29:27) [Clang 14.0.0 (clang-1400.0.29.202)]
executable: /Users/ben/.pyenv/versions/sktime/bin/python
   machine: macOS-14.1.1-arm64-arm-64bit

Python dependencies:
          pip: 22.3.1
       sktime: 0.24.1
      sklearn: 1.3.2
       skbase: 0.6.1
        numpy: 1.26.2
        scipy: 1.11.4
       pandas: 2.1.3
   matplotlib: 3.8.2
       joblib: 1.3.2
        numba: 0.58.1
  statsmodels: 0.14.0
     pmdarima: None
statsforecast: 1.6.0
      tsfresh: None
      tslearn: None
        torch: None
   tensorflow: None
tensorflow_probability: None
</details>

**Comment by fkiraly** [comment]
FYI @luca-miniati

**Comment by fkiraly** [comment]
So, I tested the same code with another statsforecast forecaster:

```python
import pandas as pd

from sktime.datasets import load_airline
from sktime.forecasting.base import ForecastingHorizon
from sktime.forecasting.statsforecast import StatsForecastAutoARIMA

y = load_airline()

model = StatsForecastAutoARIMA.create_test_instance()
model.fit(y)
fh_index = pd.PeriodIndex(pd.date_range("1961-01", periods=36, freq="M"))
fh = ForecastingHorizon(fh_index, is_relative=False)

should_be_wider = model.predict_interval(fh, coverage=0.95)
should_be_narrower = model.predict_interval(fh, coverage=0.05)
```

In this case, the intervals are the right way round narrow/wide!

This indicates there is an inconsistency either in `statsforecast` itself, or something specific about how MSTL is interfaced (which seems more unlikely since we use a general adapter).

**Comment by fkiraly** [comment]
As discussed in #5587, the locus seems to be `StatsForecastBackadapter`, not `statsforecast`.
