### ISSUE TITLE
[BUG] MiniRocketMultivariate Transformation - runtimeerror: found different number of instances in transform than in fit. number of instances seen in fit: 793; number of instances seen in transform: 199

### ISSUE THREAD

**Issue by tmh2606** [sktime/sktime#5606]
**Describe the bug**,
Trying to apply a transformation to the test set, but it spits an error - runtimeerror: found different number of instances in transform than in fit. number of instances seen in fit: 793; number of instances seen in transform: 199

**To Reproduce**
Making 5 splits in the outer nested cross-validation loop. 
X_train.shape = (10000, 65)
X_train.shape = (4000, 65) 

Outer_minirocket = MiniRocketMultivariate() 
Outer_minirocket.fit(X_train) 
X_train_trans = Outer_minirocket.transform(X_train) 
X_test_trans = Outer_minirocket.transform(X_test)

**Expected behavior**
--> the expectation was that sktime would not be sensitive to the size of the train/test set

**Versions**
I tried both under 0.21.0 and 0.24.0

**Comment by fkiraly** [comment]
@tmh2606, afaik this is intended behaviour - vanilla rocket fits parameters (like kernels etc) *per individual series*, in transform it hten uses these parameters for feature extraction.

If you want to fit/transform at the same time for each individual series, e.g., in classification, wrap the estimator in `FitInTransform` - this is at least how it is currently designed.

Do you think it is sufficient to explain this in the docs, as rocket is often used in TSC in the `FitInTransform` way, or should we even give them a parameter?

I have added explanation to the documentation here: https://github.com/sktime/sktime/pull/5621, would appreciate feedback
