### ISSUE TITLE
[BUG] Series-to-panel plus series-to-series TransformerPipeline does not work

### ISSUE THREAD

**Issue by jiayuanteng** [sktime/sktime#5624]
**Describe the bug**
I am reporting an error that I received when I tried chaining STLBoostrapTransformer with Imputer in TransformerPipeline. Let me know if you need any other information. Thanks!
**To Reproduce**

```python
from sktime.transformations.series.impute import Imputer
from sktime.transformations.compose import ColumnwiseTransformer
from sktime.forecasting.compose import TransformedTargetForecaster
from sktime.transformations.compose import TransformerPipeline
from sktime.forecasting.naive import NaiveForecaster
from sklearn.pipeline import make_pipeline
from sktime.forecasting.compose import EnsembleForecaster
from sktime.transformations.series.adapt import PandasTransformAdaptor
from sktime.datasets import load_airline
from sktime.transformations.bootstrap import STLBootstrapTransformer
from sktime.forecasting.compose import BaggingForecaster
 
y = load_airline()
bagging =STLBootstrapTransformer(4, sp = 4)  
bootstrap_trafo = STLBootstrapTransformer(4, sp = 4) * Imputer(method="nearest")
bootstrap_trafo.fit_transform(y)
```

**Expected behavior**
Error message is below

![Screenshot 2023-12-14 at 9 59 14 AM](https://github.com/sktime/sktime/assets/27443463/bf7adb74-28f2-4146-aca3-565055fe4a71)

**Additional context**
Chaining STLBoostrapTransformer and Imputer works with make_pipeline. 

```python
y = load_airline()
bagging =STLBootstrapTransformer(4, sp = 4)  
imputer = Imputer(method="nearest")
bootstrap_trafo_mp = make_pipeline(bagging, imputer)
 
bootstrap_trafo_mp.fit_transform(y)
```

![Screenshot 2023-12-14 at 10 50 40 AM](https://github.com/sktime/sktime/assets/27443463/63d7be1e-fe29-4377-b24c-44f801541d3e)

**Versions**
<details>

</details>

**Comment by fkiraly** [comment]
Thanks for reporting!

The fact that it works with make_pipeline is helpful and puzzling, since afaik internally it calls the dunder.

**Comment by fkiraly** [comment]
The reason was, the `transform-output` tag is not correctly inferred. I think I fixed this in the linked PR.

**Comment by fkiraly** [comment]
Comments about the tag system and inference would be very appreciated, it looks like this can be improved.
