### ISSUE TITLE
[BUG] `plot_windows` is creating two figures

### ISSUE THREAD

**Issue by benHeid** [sktime/sktime#5635]
**Describe the bug**
The method `plot_windows` is generating two plots. One empty and one with the splits

**To Reproduce**
See also https://github.com/sktime/sktime-tutorial-pydata-global-2023/blob/main/notebooks/02_forecasting.ipynb

```python
from sktime.split import ExpandingWindowSplitter
from sktime.utils import plot_windows
import numpy as np
import pandas as pd
y = pd.DataFrame(np.linspace(1,10, 100))
cv = ExpandingWindowSplitter(fh=range(1, 6 + 1), initial_window=12, step_length=1)
_ = plot_windows(cv, y)
```

**Expected behavior**
Only one plot is created showing the windows

**Additional context**

The problem is that in line 452 and 466 a new figure is created. Probably, the lines from 466 should be moved to the line 452.

**Comment by learningfreak6609** [comment]
Hey, I want to work on this issue. Please assign me this issue.

**Comment by benHeid** [comment]
> Hey, I want to work on this issue. Please assign me this issue.

Hi, for this issue there is already an open Pull Request. There are further issues labelled as good first issue: https://github.com/sktime/sktime/issues?page=2&q=is%3Aissue+is%3Aopen+label%3A%22good+first+issue%22

So if you would like to work on an other issue. I am happy to help :)
