### ISSUE TITLE
[BUG] convert to period bug in `_StatsModelsAdapter`

### ISSUE THREAD

**Issue by ciaran-g** [sktime/sktime#5641]
**Describe the bug**

For panel data with datetime indexes, converting datetimes to period index causes an error in the predict stage in the `_StatsModelsAdapter` models

**To Reproduce**

```python
from sktime.datasets import load_airline
from sktime.forecasting.exp_smoothing import ExponentialSmoothing
import pandas as pd
y = load_airline()

# create dummy index with hourly timestamps and panel data by hour of day
y.index = pd.date_range(start='1960-01-01', periods=len(y.index), freq='H')
y.index.names = ["datetime"]
y.name = "passengers"
y = y.to_frame()
y['hour_of_day'] = y.index.hour
y = y.reset_index().set_index(['hour_of_day', 'datetime']).sort_index()

forecaster = ExponentialSmoothing(
    trend='add', sp=1
)  
forecaster.fit(y)
forecaster.predict(fh=[1])

```

**Expected behavior**

For each panel predict one step ahead

**Additional context**

I will address this issue 👍 

**Versions**
<details>

Python dependencies:
          pip: 23.1.2
       sktime: 0.24.1
      sklearn: 1.2.2
       skbase: 0.6.1
        numpy: 1.24.3
        scipy: 1.10.1
       pandas: 2.0.2
   matplotlib: None
       joblib: 1.2.0
        numba: None
  statsmodels: 0.14.0
     pmdarima: 2.0.3
statsforecast: None
      tsfresh: None
      tslearn: None
        torch: None
   tensorflow: None
tensorflow_probability: None

**Comment by fkiraly** [comment]
We should add a test for all forecasters - that could be done in `utils._testing.scenarios_forecasting`, in `forecasting_scenarios_extended`
