### ISSUE TITLE
[BUG] repeated use of `nd.array` in `sktime` codebase

### ISSUE THREAD

**Issue by yarnabrina** [sktime/sktime#5643]
There are 3 different modules which document types using `nd.array`

![image](https://github.com/sktime/sktime/assets/39331844/54c70fe3-e47d-4f7a-9096-7cf0715ca516)

The first two are part of docstrings in `classification` component, and are relatively old codebase. The rest are very recent changes as part of addition of ARCH features.

I am thinking that these are normal typos of `np.ndarray`, but I noted that there are no test failures anywhere, even though `sktime/registry/_tags.py` does not document `nd.array` as supported type of `X_inner_mtype`. Also there are a lot of `nd` in `dists_kernels` module, though there it _may_ mean `n-dimension` there (not certain). So I am wondering is there some other package or internal object that is helping in these `nd.array` definitions, or are these indeed mistakes?

CC: @fkiraly @Vasudeva-bit

**Comment by fkiraly** [comment]
I can explain why the wrong tag value does not lead to an error:

* in tag checking, the respective tags are only checked for "list of string" type, not for the specific values. This makes adding new mtypes easy, although it leads to not spotting this
* the logic in internal conversion is "if supported, pass unconverted; if not supported, convert to first supported mtype in the list, of same scitype".
    * this does not lead to error, as `np.array` is not an outcome of type checking
    * so it will always be ignored, as it is not an mtype belonging to any possile data's scitype

Not sure whether the tag andn input checkingn logic needs change, and if yes, how. Perhaps the most obvious candidate is to narrow type checking for the tag, by linking it to the list of all mtypes, for possible values.

**Comment by yarnabrina** [comment]
Ok, there are thress parts I suppose:

1. fix typos in the modules -> I've opened PR #5645 for this one.
2. fix typo in the tag module, as `np.array` is not a type, but `np.ndarray` is -> Should I change it, or can it affect a lot more things than a typo bug fix PR?
3. (possibly) enhancement of type check -> This needs discussion I guess.

**Comment by fkiraly** [comment]
updated #5645 with 2, if you are ok with it
