### ISSUE TITLE
[ENH] feature importance capability tag for time series classifiers

### ISSUE THREAD

**Issue by jmwhyte** [sktime/sktime#5649]
There do not seem to be many sktime classifiers which can produce feature importances. Searching the docs to find them does not seem very efficient, and this information may change over time.

It would be nice if sktime's `all_tags()` had a boolean-valued tag for something like "Can provide feature_importances?", to assist the user in finding suitable functions.

**Comment by fkiraly** [comment]
That's a nice idea! (as discussed on discord)

I think this is a good first issue, with two steps:

* introduce a new tag `capability:feature_importance` in `registry._tags`
* add the tag to `BaseClassifier` - I suppose `BaseRegressor` also makes sense. The default should be `False`.
* it should also be added to the extension template in `extension_templates`
* then someone needs to go through the list of classifiers and set the tag for `True` to the small number of classifiers that do have this feature...

**Comment by fkiraly** [comment]
FYI @YHallouard, you might be one of the contributors with the best view of which classifiers do have this, or not

**Comment by YHallouard** [comment]
@fkiraly, I'll be quite busy until February, I'll take a look at this in this period for sur :)
