### ISSUE TITLE
[ENH] multiplexer classifier and regressors

### ISSUE THREAD

**Issue by fkiraly** [sktime/sktime#5655]
For autoML with classifiers and regressors, a multiplexer like `MultiplexForecaster` would be useful.

The code can easily be adapted, as there already is a `_DelegatedClassifier` etc.

Originally suggested by @jmwhyte on discord.

**Comment by ksharma6** [comment]
I'd like to work on this @fkiraly . I'm pretty new to the project as well as open-source, which file should I be working on to add the `MultiplexForecaster`?

**Comment by fkiraly** [comment]
The `MultiplexForecaster` already exists, and so does the `MultiplexClassifier`, but you could add a `MultiplexRegressor`?

Simply follow the pattern, it should live in `sktime.regression.compose._multiplexer`.

**Comment by tanish1729** [comment]
Hello @fkiraly! I would love to take up work on this issue if there's still something to be done.

**Comment by fkiraly** [comment]
apologies, I believe @ksharma6 is already working on this, above.

How about a multiplexer for time series distances (`BasePairwiseTransformerPanel`), or probability distirbutions (`BaseDistribution`)?

**Comment by tanish1729** [comment]
Alright. I took a look if there were any existing issues raised for `BasePairwiseTransformerPanel`   and there is just a very old discussion from 2021. I can try implementing the `transform`  function for the class because as I understand, it has been left to the user to define their own transform.

**Comment by fkiraly** [comment]
Hm, I would use the `_DelegatedPairwiseTransformerPanel` and copy the multiplexer pattern from `MultiplexForecaster` - that way, you do not need to implement `_transform` and `_inverse_transform`.

Might not be the "best" good first issue since there is no explicit recipe for it, feel free to have a look around for sth else if you prefer.

**Comment by tanish1729** [comment]
Makes sense. I dont see anything open as of now. 

For this, by "copy the multiplexer pattern" are you referring to what is described here 

![image](https://github.com/sktime/sktime/assets/92108099/3f91d764-297f-4f24-b4d0-3236c47badfa)

And we use the wrapped estimator from `_DelegatedPairwiseTransformerPanel`  on the multiplexer pattern?

Apologies if im missing something but I could start working on this if i had more clarity

**Comment by fkiraly** [comment]
yes, I am referring to the implementation where the multiplexer inherits from the delegator for the specific base class.

**Comment by iaryangoyal** [comment]
@fkiraly is there anything in which is could work?
