### ISSUE TITLE
[DOC] Code quallity check fails for `examples/blog_posts/Overview_of_sktime_functionalities_for_forecasting.ipynb`

### ISSUE THREAD

**Issue by yarnabrina** [sktime/sktime#5683]
Code quality checks is failing for `examples/blog_posts/Overview_of_sktime_functionalities_for_forecasting.ipynb` added in #5604.

1. Old CI in original PR (https://github.com/sktime/sktime/actions/runs/7314998485/job/19928205187)
2. New CI in original PR (https://github.com/sktime/sktime/actions/runs/7314998490/job/19928205191)
3. New CI in `main` branch (https://github.com/sktime/sktime/actions/runs/7371485322/job/20058924081)

This is going to block `test_all.yml` in its first step for all future scheduled runs.

FYI @fkiraly @onyekaugochukwu

**Comment by fkiraly** [comment]
Yes, I was aware when I merged - I thought linting only checks diffs, as there are further instances with incomplete linting?
(I also thought, fine for a notebook, as it is 3rd party, and in this case it is better to be as close to original as possible)

**Comment by yarnabrina** [comment]
Yes, code quality checks in old CI used to check just files that are modified in the PR. However, in new CI it also runs on schedule on `main` branch, where there is no concept of difference. Hence, #5427 introduced two types of quality checks: only on differences in PR, and on everything in `main`.

PR

https://github.com/sktime/sktime/blob/2f62af57bb46162e351667814c5afafc6f11574f/.github/workflows/test_code_quality.yml#L19-L23

CRON

https://github.com/sktime/sktime/blob/2f62af57bb46162e351667814c5afafc6f11574f/.github/workflows/test_all.yml#L19-L20

**Comment by fkiraly** [comment]
I see!

My rationale for keeping the notebook as-is is "being in sync with third party", i.e., "it's a third-party artefact", and "linting would be forking", and "forking makes updates more difficult".

Would it make sense to except the `blog_posts` subfolder from linting tests in the CRON?

**Comment by yarnabrina** [comment]
Yes, it does make sense, but by same logic, do we need `run-blogpost-examples` job then? Would we not want to keep original outputs (and errors/warnings if any for demonstration purposes) unchanged?

Also, I don't know how to ignore a specific folder with `pre-commit`. I know how to pass all using `--all-files` or specific files with `--files`. I do not know of an `exclude` type option, and list every single file in the repository (except a few) seems too long a command, even if it's supported.

Another option is to disable code quality check altogether for CRON. That's easily doable and will allow to keep potential "bad-quality" codes in the repository, but I don't like this.

**Comment by fkiraly** [comment]
> Would we not want to keep original outputs (and errors/warnings if any for demonstration purposes) unchanged?

I don't get what you are asking. Where are "original outputs" being changed?

> Also, I don't know how to ignore a specific folder with pre-commit.

That must exist, although I also do not know how.

**Comment by yarnabrina** [comment]
Handled via #5925
