### ISSUE TITLE
[ENH] Relax pin on tslearn

### ISSUE THREAD

**Issue by DManowitz** [sktime/sktime#5684]
**Is your feature request related to a problem? Please describe.**
A clear and concise description of what the problem is.

As noted in PR #4819, tslearn 0.6.0 added an explicit requirement on pytorch.  However, as of tslearn 0.6.1, that requirement has been removed.

**Describe the solution you'd like**
A clear and concise description of what you want to happen, ideally taking into consideration the existing toolbox design, classes and methods.

It seems that the pin on tslearn should be >=0.5.2,!=0.6.0 instead of <0.6.0,>=0.5.2.

**Describe alternatives you've considered**

**Additional context**

**Comment by fkiraly** [comment]
There should also be an upper bound, so `<0.7.0, !=0.6.0, >=0.5.2` then?

Pull request would be much appreciated!

That will trigger the tests whether the `0.6.X` versions are fine with the `sktime` general interfaces.

**Comment by DManowitz** [comment]
Do you want me to just create a branch in this repo, or create a fork first?

**Comment by fkiraly** [comment]
> Do you want me to just create a branch in this repo, or create a fork first?

Fork (branch) and PR - you do not have write access (only core developers), so that's the only way it would work.
