### ISSUE TITLE
[MNT] Pandas groupby(axis=1) will be deprecated in a future version, affects `EnsembleForecaster`

### ISSUE THREAD

**Issue by ninedigits** [sktime/sktime#5701]
Fixes https://github.com/sktime/sktime/issues/5701

Effected code:
https://github.com/sktime/sktime/blob/40c8e4fb285f7b0a08cad32ca2866b5a495b2865/sktime/forecasting/compose/_ensemble.py#L367-L369

The warning triggered:
```FutureWarning: DataFrame.groupby with axis=1 is deprecated. Do `frame.T.groupby(...)` without axis instead.```

Issue is discussed on the Pandas github: 

- https://github.com/pandas-dev/pandas/issues/56226
- https://github.com/pandas-dev/pandas/issues/51203

**Comment by ninedigits** [comment]
This code block passes the unit tests and avoids triggering the deprecation warning, but involves a lot more lines and isn't nearly as elegant as the original solution:

```python3
        def agg_merge(df, aggfunc, weights, label):
            """
            Custom aggregation and transformation for a given DataFrame.
            Transposes the DataFrame, applies aggregation, and sets new column names.
            """
            aggregated_df = pd.DataFrame(_aggregate(df.T, aggfunc, weights))
            aggregated_df.columns = [label]
            return aggregated_df

        # Group by the second level of the index and apply the custom aggregation function
        # Then combine all the aggregated DataFrames
        grouped_dfs = [agg_merge(df_group, self.aggfunc, self.weights, label_group) for label_group, (_, df_group) in
                       enumerate(y_pred.T.groupby(level=1))]
        y_pred = pd.concat(grouped_dfs, axis=1)
```

**Comment by fkiraly** [comment]
Thanks for reporting!

Regarding the alternative, could this also work?

```python
y_pred = y_pred.T.groupby(level=1).T.agg( 
     _aggregate, self.aggfunc, self.weights 
 ) 
```

Either way, a pull request with your "best guess solution" would be appreciated!
We have been dealing with these warnings for a while.

**Comment by ninedigits** [comment]
Tried all variations of that, I didn't see any solutions that would be as elegant as the original. People were complaining about that on the pandas github, but the developers argued that transforms were complex and shouldn't be performed under the hood, and that keeping `axis=1` solution would require a lot of additional maintenance. I added the PR here: https://github.com/sktime/sktime/pull/5707
