### ISSUE TITLE
[ENH] Adding a parameter to forecasters from statsmodels to control verbosity of output

### ISSUE THREAD

**Issue by tvdboom** [sktime/sktime#5712]
**Is your feature request related to a problem? Please describe.**
Some forecasters (such as SARIMAX) that are direct wrappers of statsmodels forecasters, print multiple messages when fitting the model (see image for an example). There is currently no way of controling the level of the printed output.

![image](https://github.com/sktime/sktime/assets/32366550/d1d152b3-c3c6-40ba-969c-fac678c20ebc)

**Describe the solution you'd like**
It would be nice to have a parameter `verbose` to control the level of verbosity. The stasmodels implementation has a parameter called `disp` (see https://www.statsmodels.org/dev/generated/statsmodels.tsa.statespace.sarimax.SARIMAX.fit.html#statsmodels.tsa.statespace.sarimax.SARIMAX.fit) that can do this, but there is currently no way of accessing this parameter from the sktime implementation.

**Comment by fkiraly** [comment]
Hm, we need to be careful about whether this parameter was added in a recent version (the parameter interfaces are not very stable), apart from that it should be possible to add it in `_GeneralisedStatsforecastAdapter`.

FYI @yarnabrina.

@tvdboom, would you be open to try contribute this (possibly with pointers where to add and how to handle unstable interfaces)?

**Comment by tvdboom** [comment]
The `disp` parameter seems to be available at least since version 0.8. I'll make a PR, bit first we need to agree on the API. My idea was to add a boolean parameter to the constructor of the sktime models called `verbose`, that is passed internnally to `disp` in the `fit` method of the statsmodel model. Does this sound reasonable?

**Comment by fkiraly** [comment]
Agreed with @yarnabrina.

Regarding the naming, I have no strong opinion, though I would slightly go with @tvdboom's suggestion, as there are certain parameters that occur in many estimators, and a case can be made to ensure their names are consistent across.

Examples:
* `random_state`
* `sp`, "seasonal periodicity"
* parallelization backend strings
* and `verbose`

**Comment by tvdboom** [comment]
@fkiraly you mentioned `_GeneralisedStatsForecastAdapter` but I see that SARIMAX (which is the model for my use case) actually inherits from `_StatsModelsAdapter`. What's the difference? Should both be adjusted?

**Comment by fkiraly** [comment]
Apologies, I see what is going on here - I got confused in the first place, sorry.

You were referring to a model from `statsmodels`, not `statsforecast` - this is also why the adapters are different, these are two packages. The confusion is due to similar names, and both packages offering ARIMA type models natively.

I suppose one should revisit `_StatsModelsAdapter` then - I think `_GeneralisedStatsForecastAdapter` is currently more robust and more cleanly designed, but of course they adapt two different packages, so the adaptation logic has to remain distinct.

**Comment by tvdboom** [comment]
After some research I discovered that many of the sktime wrappers for `statsmodels` models already implement this feature using the `disp` parameter in the constructor (examples are DynamicFactor, AutoETS, VARMAX). To not break with the current API, I just added the `disp` parameter to the SARIMAX model, where it was missing.

**Comment by fkiraly** [comment]
> To not break with the current API, I just added the `disp` parameter to the SARIMAX model, where it was missing.

Yes, that makes a lot of sense for reasons of consistency.
