### ISSUE TITLE
[ENH] expose fitted params for `statsforecast` forecasters via `get_fitted_params`

### ISSUE THREAD

**Issue by fkiraly** [sktime/sktime#5720]
We should ensure that `statsforecast` estimators expose their fitted parameters through `get_fitted_params`. For that, parameters need to be written in `_fit`, to attributes ending in underscore.

The changes should be done in the `_GeneralisedStatsforecastAdapter`, but useful "good first issue" contributions would already be to check where the parameters are stored in `statsforecast`, e.g., where does Auto-ARIMA store its fitted parameters?

---

Asked by @holderhe in #931:

> how about the `StatsForecastAutoARIMA` ? how can i retrieve parameter for evaluation like AIC, etc. ?

I think this is not currently supported, but could be done easily by writing these to attributes ending in underscore aftere the fit.

FYI @yarnabrina due to authorship of the `statsforecast` adapter.

**Comment by yarnabrina** [comment]
Duplicate/Superset of #6342 ?

**Comment by fkiraly** [comment]
yes, superset of #6342

**Comment by fkiraly** [comment]
@holderhe, @jiayuanteng, @yarnabrina, does PR https://github.com/sktime/sktime/pull/6349 make the parameters accessible that you want?

**Comment by jiayuanteng** [comment]
Yes!

**Comment by fkiraly** [comment]
Well, that's good to hear.

I thought is was something more involved, but it turns out the forwarding was just missing.

**Comment by fkiraly** [comment]
(removing "good first issue" since resolved)

**Comment by jiayuanteng** [comment]
No worries. May is fine. I appreciate that you are working on it😄 Just to confirm - will the May release cover the issue #931 i.e., expose AIC, BIC, estimated coefficients in auto aroma function?

**Comment by fkiraly** [comment]
if #6349 solves it and does not cause problems, then yes, it will be in one of the May releases.

**Comment by yarnabrina** [comment]
I am very confused, how does this PR solve the fitted parameters for you @jiayuanteng ? I thought you wanted to get which (p,d,q) combination won as part of AutoARIMA, is that not the case? This PR is not going to expose those if I am not wrong. There is no logic that I can find that creates `p_`, `d_`, `q_` etc. attributes.

**Comment by jiayuanteng** [comment]
> No worries. May is fine. I appreciate that you are working on it😄 Just to confirm - will the May release cover the issue #931 i.e., expose AIC, BIC, estimated coefficients in auto aroma function?
> 

@yarnabrina got it. I hope I didn't misunderstand. yeah I wanted to get estimated coefficients and AIC etc. I asked above and @fkiraly confirmed that could be done. Separately, I found a thread on stackoverflow that shows a way to get AIC etc from statsforecast auto ARIMA, the model specification is confusing though (see the comment section to the top answer)

https://stackoverflow.com/questions/75290492/how-to-get-model-specification-paramters-for-models-estimated-with-nixtlas-stat

**Comment by fkiraly** [comment]
@jiayuanteng, does the PR solve it for you or not, now?

@yarnabrina, I thought that, if the `statsforecast` estimator already stored this as underscored attributes, then `get_fitted_params` would not see it, because there is no attribute forwarding. The PR solves it, in a case where `statsforecast` does this, by forwarding the attribs.

**Comment by yarnabrina** [comment]
@jiayuanteng Thanks for your link. We do not use `StatsForecast` class directly, and we use the algorithm instances directly. They also seem to have this `model_` property, but its format seems to vary a lot. I created a issue on Nixtla repo, hopefully we shall know from that.

https://github.com/Nixtla/statsforecast/issues/829
