### ISSUE TITLE
[BUG] Setting random state in BaggingForecaster does not work

### ISSUE THREAD

**Issue by jiayuanteng** [sktime/sktime#5728]
**Describe the bug**
I want to reproduce forecast with Bagging Forecaster. I use STLBoostrapTransfomer in BaggingForecaster. 

I set random_state in STLBoostrapTransformer. But for some reason, random state defined is NOT passed into BaggingForecaster. As a result, synthetic time series generated by STLBoostrapTransformer change. When I re-run the code my predictions from Bagging Forecaster change.

**To Reproduce**
I set random_state to 1234 in STLBoostrapTransformer and Imputer (this does not matter and what matters is STLBoostrapTransformer). When I call fit method, random_state is 1234.

```python
from sktime.transformations.series.impute import Imputer
from sktime.forecasting.naive import NaiveForecaster
from sktime.forecasting.statsforecast import StatsForecastAutoARIMA
from sktime.datasets import load_airline

y = load_airline()
transformer = STLBootstrapTransformer(4, sp =12, random_state = 1234) * Imputer(method="nearest", random_state=1234)
 
bagging = BaggingForecaster(transformer, NaiveForecaster())
bagging.fit(y)
```
![Screenshot 2024-01-10 at 9 04 40 PM](https://github.com/sktime/sktime/assets/27443463/a375f298-6af1-4000-a88f-253abd95212f)

When I call predict, random_state is different. This means, synthetic time series generated by STLBoostrapTransformer change and my predictions change when I rerun the code.  

```python

bagging.predict(fh = [1,2,3,4,5])
bagging.get_fitted_params()['bootstrap_transformer']

```
![Screenshot 2024-01-10 at 9 07 10 PM](https://github.com/sktime/sktime/assets/27443463/d02991a7-db57-497e-9a43-006f81416281)

**Additional context**
Random_state works when running STLBoostrapTransformer alone 
```
y = load_airline()
transformer = STLBootstrapTransformer(4, sp =12, random_state = 1234) * Imputer(method="nearest", random_state=1234)
 
transformer.fit(y)
```
![Screenshot 2024-01-10 at 9 10 32 PM](https://github.com/sktime/sktime/assets/27443463/0c139a41-65a6-4b8e-9d2c-8ec4d030ee65)

**Versions**
running sktime == 0.25.0

</details>

**Comment by fkiraly** [comment]
Hm, I've reproduced this on current `main`, windows, python 3.11. The seed in the fitted parameter seems random.

**Comment by jiayuanteng** [comment]
@fkiraly would you be able to set random state fixed and reproduce the forecast with bagging forecaster?

**Comment by fkiraly** [comment]
The reason are below lines in the constructor.

Oddly, the `BaggingForecaster` overwrites random states of components with its own. If it is not specified, this will be a random number.

I think the `set_random_state` lines should just be removed:

```python
        self.random_state_ = check_random_state(self.random_state)
        set_random_state(self.bootstrap_transformer_, random_state=self.random_state_)
        set_random_state(self.forecaster_, random_state=self.random_state_)
```

**Comment by jiayuanteng** [comment]
@fkiraly thanks a lot for looking into it.
