### ISSUE TITLE
[DOC] Inconsistency in documented `TimeSeriesForestClassifier` locations, sktime 0.25.0 docs

### ISSUE THREAD

**Issue by jmwhyte** [sktime/sktime#5740]
I've seen that you can import TimeSeriesClassifier from subdirectories of sktime.classification, either interval_based or interval_based._tsf. Are these the same classifier? 

The question is motivated by what I saw here: https://www.sktime.net/en/latest/api_reference/auto_generated/sktime.classification.interval_based.TimeSeriesForestClassifier.html 
where there is the text: "This is an intentionally stripped down, non configurable version for use as a hive-cote component. For a configurable tree based ensemble, see sktime.classifiers.ensemble.TimeSeriesForestClassifier". 

This makes it sound as though there are two forms of `TimeSeriesForestClassifier` available for use. Is this still correct?

Also, sktime 0.25.0 returns an error if you try `from sktime.classifiers.ensemble import TimeSeriesForestClassifier`. Even changing classifiers to classification in the command above doesn't help. It seems some location has changed.

It would be good to have clarity about any variants of `TimeSeriesForestClassifier` that are available for use in the current sktime, and where to look in the docs for information.

**Comment by fkiraly** [comment]
Thanks fo reporting!

* the module starting with underscore is private, so should not be dirctly accessed
* the note sems outdated and ought to be fixed, though not sure what exactly it should change to

**Comment by fkiraly** [comment]
Fixed, here: https://github.com/sktime/sktime/pull/5741

What is odd, the module was never called `classifiers` afaik, this mus have been a mistake in the original docstring.

**Comment by jmwhyte** [comment]
> * the module starting with underscore is private, so should not be directly accessed

In this case, the underscore form should not appear in the `all_estimators()` output, especially when the other (recommended) version does not appear in that output? Otherwise, users might just use the form of estimator they see output in this "encyclopaedia" of methods?

**Comment by fkiraly** [comment]
> In this case, the underscore form should not appear in the `all_estimators()` output, especially when the other (recommended) version does not appear in that output?

Interesting, where does it appear?

If you convert a class to str, afaik it will always appear with its full path.

**Comment by jmwhyte** [comment]
You can see  what I describe after
```
from sktime.registry import all_estimators
all_estimators('classifier')
```
Starting from 
"('Arsenal', sktime.classification.kernel_based._arsenal.Arsenal)"
there are many paths with the `_` shown.

**Comment by fkiraly** [comment]
yes, I see - that's because the second element in the tuple is a class. When converted to string, the full path is always shown. Not sure how to change that.

`str(all_estimators('classifier')[0][1])` gives `<class 'sktime.classification.kernel_based._arsenal.Arsenal'>`
