### ISSUE TITLE
[BUG] WindowSummarizer unexpected NaN

### ISSUE THREAD

**Issue by Ram0nB** [sktime/sktime#5781]
**Describe the bug**

With Sktime 0.25.0 the WindowSummarizer returns unexpected missing values.

**To Reproduce**

```python
import numpy as np
import pandas as pd
from sktime.transformations.series.summarize import WindowSummarizer

df = pd.DataFrame(np.arange(10))
transformer = WindowSummarizer(lag_feature={"mean": [[-1, 1], [-1, 2]]}, n_jobs=1)
df_transformed = transformer.fit_transform(df)

print(df_transformed)
```

**Expected behavior**

value 0.5 in 1st row 2nd column rather than NaN

**Additional context**

**Versions**
<details>

System:
    python: 3.10.12 | packaged by Anaconda, Inc. | (main, Jul  5 2023, 19:01:18) [MSC v.1916 64 bit (AMD64)]
executable: [c:\Users\ramon.bussing\AppData\Local\anaconda3\envs\enerfore-dev\python.exe](file:///C:/Users/Ram0nB/AppData/Local/anaconda3/envs/enerfore-dev/python.exe)
   machine: Windows-10-10.0.19044-SP0

Python dependencies:
          pip: 23.2.1
       sktime: 0.25.0
      sklearn: 1.3.0
       skbase: 0.6.1
        numpy: 1.22.4
        scipy: 1.8.1
       pandas: 2.1.1
   matplotlib: None
       joblib: 1.3.2
        numba: None
  statsmodels: 0.14.0
     pmdarima: None
statsforecast: None
      tsfresh: None
      tslearn: None
        torch: None
   tensorflow: None
tensorflow_probability: None

</details>

**Comment by benHeid** [comment]
I can reproduce this behavior. The reason for this behavior is that in the function `_window_feature` in summarize.py first shift is called on the DataFrame and then the rolling feature is calculated. 
More specifically, this issue arises since shift is not extending the index. Thus, I assume it would be better to first calculate the rolling feature and do the shifting afterwards.

**Comment by ShreeshaM07** [comment]
I'd like to start working on this issue. Is just switching the order of `shift` and `rolling` in `_window_feature` in summarize.py going to solve the issue of returning NaN?

**Comment by benHeid** [comment]
> I'd like to start working on this issue. Is just switching the order of `shift` and `rolling` in `_window_feature` in summarize.py going to solve the issue of returning NaN?
> 
> 
Thank you that you are working on that. 

I assume that this fixes the issue. But this needs to be tested with the code that is producing the error. 

Btw. I assigned you to the issue

**Comment by ShreeshaM07** [comment]
I tried switching the `shift` and `rolling` in `_window_feature` in summarize.py . It now works for the code snippet `1` but does not work for `2`.
1)
df = pd.DataFrame(np.arange(10))
transformer = WindowSummarizer(lag_feature={"mean": [[-1, 1], [-1, 2]]}, n_jobs=1)
df_transformed = transformer.fit_transform(df)

print(df_transformed)

2)

kwargs = {
    "lag_feature": {
        "lag": [1],
        "mean": [[1, 3], [3, 6]],
        "std": [[1, 4]],
    }
}

transformer = WindowSummarizer(**kwargs)
y_transformed = transformer.fit_transform(y_train)

y_transformed.head(10)

But when i try to run  like in `./sktime/examples/01c_forecasting_hierarchical_global.ipynb` it runs into an Error.

"./sktime/sktime/transformations/series/summarize.py", line 460, in _window_feature
    raise ValueError("Input Z must be either a DataFrame or a Series.")
`ValueError: Input Z must be either a DataFrame or a Series.`

Even though y_train is a DataFrame. Could you please help me out.

![Screenshot from 2024-02-28 22-13-00](https://github.com/sktime/sktime/assets/120820143/f0fc16c2-bb95-41eb-b0b1-51d806e078fb)
![Screenshot from 2024-02-28 22-12-33](https://github.com/sktime/sktime/assets/120820143/150c880d-2d64-4712-aff2-384bb20473fe)

**Comment by benHeid** [comment]
I will look at your PR today. Could you ensure that your branch is uptodate.

**Comment by sahusiddharth** [comment]
@benHeid, would you mind if I give it a try?

**Comment by sahusiddharth** [comment]
Hello, @fkiraly and @benHeid

I think, I have narrowed down what is causing the hierarchal error, Can you tell me what needs to be done if we receive a hierarchal data frame as an input?

**Comment by fkiraly** [comment]
@sahusiddharth, an easy way to generate hierarchical data for testing is 

```python
from sktime.utils._testing.hierarchical import _make_hierarchical
y = _make_hierarchical()
```
