### ISSUE TITLE
[BUG] `SARIMAX` fails when `X` is passed in `predict` but not used in `fit`

### ISSUE THREAD

**Issue by yarnabrina** [sktime/sktime#5789]
## Minimal Reproducible Example

```pycon
>>> 
>>> from sktime.datasets import load_longley
>>> from sktime.forecasting.sarimax import SARIMAX
>>> from sktime.split import temporal_train_test_split
>>> 
>>> y, X = load_longley()
>>> 
>>> y_train, _, _, X_test = temporal_train_test_split(y, X)
>>> 
>>> forecaster = SARIMAX()
>>> 
>>> forecaster.fit(y_train)
SARIMAX()
>>> 
>>> # works
>>> forecaster.predict(fh=[1, 2, 3, 4])
1959    66061.176439
1960    65682.034815
1961    65363.883253
1962    65096.910677
Freq: A-DEC, Name: TOTEMP, dtype: float64
>>> 
>>> # fails
>>> forecaster.predict(fh=[1, 2, 3, 4], X=X_test)
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/anirban/sktime-fork/sktime/forecasting/base/_base.py", line 412, in predict
    y_pred = self._predict(fh=fh, X=X_inner)
  File "/home/anirban/sktime-fork/sktime/forecasting/base/adapters/_statsmodels.py", line 108, in _predict
    ind_drop = self._X.index
AttributeError: 'NoneType' object has no attribute 'index'
>>> 
```

## Expectation

I was expecting no failures, and identical behaviour in both cases. I do get that behaviour if I try with `sktime.forecasting.arima.ARIMA`.

## Version

Operating System: Ubuntu 22.04.3 LTS (WSL)
Python: 3.10.12
Sktime: e51ec2472a

**Comment by Abhay-Lejith** [comment]
On looking into this issue, I found that the error was initially because of this code snippet
```python
if X is not None:
    ind_drop = self._X.index
    X = X.loc[~X.index.isin(ind_drop)]
    # Entire range of the forecast horizon is required
    X = X.iloc[: (fh_int[-1] + 1)]  # include end point
```
Since we are not passing any X in fit, `self._X` is None and it does not have an index attribute. This could be solved by simply adding an if condition to check if self._X is None or not and then dropping the indices accordingly.
However this fix throws another error when run :
```python
ValueError                                Traceback (most recent call last)
Cell In[3], line 1
----> 1 forecaster.predict(fh=[1, 2, 3,4],X=X_test)

File ~/sktime/sktime/forecasting/base/_base.py:444, in BaseForecaster.predict(self, fh, X)
    442 # we call the ordinary _predict if no looping/vectorization needed
    443 if not self._is_vectorized:
--> 444     y_pred = self._predict(fh=fh, X=X_inner)
    445 else:
    446     # otherwise we call the vectorized version of predict
    447     y_pred = self._vectorize("predict", X=X_inner, fh=fh)

File ~/sktime/sktime/forecasting/base/adapters/_statsmodels.py:121, in _StatsModelsAdapter._predict(self, fh, X)
    118     X = X.iloc[: (fh_int[-1] + 1)]  # include end point
    120 if "exog" in inspect.signature(self._forecaster.__init__).parameters.keys():
--> 121     y_pred = self._fitted_forecaster.predict(start=start, end=end, exog=X)
    122 else:
    123     y_pred = self._fitted_forecaster.predict(start=start, end=end)

File ~/anaconda3/envs/sktime-dev/lib/python3.10/site-packages/statsmodels/base/wrapper.py:113, in make_wrapper.<locals>.wrapper(self, *args, **kwargs)
    111     obj = data.wrap_output(func(results, *args, **kwargs), how[0], how[1:])
    112 elif how:
--> 113     obj = data.wrap_output(func(results, *args, **kwargs), how)
    114 return obj
...
    644     # endpoint, but does not know what the calling methods may
    645     # specifically require.
    646     updated_mat = np.asarray(kwargs[name])

ValueError: Model has time-invariant design matrix, so cannot provide an extended matrix.
```

This error is coming from a method within the `statsmodels` source code. I am not very familiar with what exactly happens in SARIMAX but are we sure that in order to pass exog args in predict, they do not have to be passed in fit first?

**Comment by yarnabrina** [comment]
My expectation was that this should be handled by the base class itself. The expectation came from this:

https://github.com/sktime/sktime/blob/64e90aae0deb51ad89c2e29ef56607e533a7c984/extension_templates/forecasting.py#L114-L117

I interpreted this that even if user pass X only in predict, base will set that to None before forwarding it to _predict.

**Comment by Abhay-Lejith** [comment]
It looks like the tag being False isn't setting the X passed in predict to None conditionally when X is not passed in fit. On the other hand it cannot be set to True as exogeneous features cannot be ignored in all cases. Simply adding an if check just before passing the exog X to the predict method seems to work.
```python
if "exog" in inspect.signature(self._forecaster.__init__).parameters.keys():
    if (self._X is None):
        X = None
    y_pred = self._fitted_forecaster.predict(start=start, end=end, exog=X)
else:
    y_pred = self._fitted_forecaster.predict(start=start, end=end)
```
Is this solution satisfactory or should we go about it some other way?

**Comment by Abhay-Lejith** [comment]
> My expectation was that this should be handled by the base class itself. The expectation came from this:
> 
> https://github.com/sktime/sktime/blob/64e90aae0deb51ad89c2e29ef56607e533a7c984/extension_templates/forecasting.py#L114-L117
> 
> I interpreted this that even if user pass X only in predict, base will set that to None before forwarding it to _predict. And even for models supporting exogenous features in general but not in a particular case, it'll still set it as None.

Also, how do you display code in this manner?

**Comment by yarnabrina** [comment]
> Is this solution satisfactory or should we go about it some other way?

For this particular issue in `sktime`, adding a new if-else is sufficient. Though I do have a concern for the code snippet you shared, as I am trying to think when will `self._X` be `None` but `exog` if check will pass. In my understanding `exog` will be available only if `X` was passed in the `fit` call. I haven't checked it now, so you may want to confirm this before the bugfix PR.

---

> how do you display code in this manner?

It's really simple to do, but may be a bit trickier to explain in writing.

1. When you go to a repository in Github and open a text file, you see the line numbers on left.
2. Clicking on a line number selects that line and updates the URL.
3. If you want to select a range of line, you can either edit the URL to add another line or shift-click on the end of the line range.
4. Using this URL (2 or 3) in issues or pull requests in the same repository displays it in that fashion.
5. If you want to link line(s) of a particular commit, you can click on the ellipses (`...`) and generate a permalink to the commit.

Let me know if this text description makes sense or not.

**Comment by fkiraly** [comment]
silly question: why should passing `X_test` work if `X_train` has not been passed? Are there models that can make use of `X_test`?

**Comment by yarnabrina** [comment]
My expectation is it should not fail. Obviously the fitted model will not be able to use that as a feature, but my expectation is that it should not fail and it should work without error.

As of now, the signature of the function allows users to pass X always as an optional argument, irrespective of signature of fit. So I think predict should not fail if user's call is compatible with that signature.

(I do not remember what exactly I was trying to face this, so can not give an actual situation.)
