### ISSUE TITLE
[BUG] "test everything" workflow fails at linting

### ISSUE THREAD

**Issue by fkiraly** [sktime/sktime#5794]
It would appear that the "test everything" CRON workflow fails at linting, at some unlinted files, and does not test anything in addition:
https://github.com/sktime/sktime/actions/runs/7597688422

FYI @yarnabrina

**Comment by yarnabrina** [comment]
This is not a CI bug. It's caused by https://github.com/sktime/sktime/issues/5683.

**Comment by yarnabrina** [comment]
I do not know how to exclude files, and also do not know how to list all files in the repository excluding a specific one. If you know, please use the `--files` argument of `pre-commit` and it'll then be done.

Also, I'll be curious to know if a very long list of files is even supported or not, as sometime `ls *.pyc | xargs rm` type command fails for me if the list is very long.

**Comment by fkiraly** [comment]
well, but with CI it is like that - we have to go with wht we *can* implement, not a desired state that we couldn't figure out how to enable. E.g., we can't switch off coverage in the current CI if the regular CRON does not pick up the coverage.

**Comment by fkiraly** [comment]
> only other possibility I can think of is to remove that job entirely

What about linting only diffs, like in the main current CI? Just copy-paste that?
