### ISSUE TITLE
[ENH] multivariate time series regression with `sktime `

### ISSUE THREAD

**Issue by ozkanuysal** [sktime/sktime#5821]
Hi everyone ı have a question for sktime multivariate problem.We try to solve multivariate regression predict but we can't use sktime.In the other hand we can predict,  Univariate time series classification with sktime,  we know we can use multivariate with classification but we try to use in Regression problem how we can do it is there anyone know ?

**Comment by fkiraly** [comment]
This should now be possible, at least framework-wise.

You can list classifiers and regressors capable of multivariate input by filtering for the tag `capability:multivariate`.

Multivariate output is also suppoted, either via automatic broadcasting across outputs, or genuinely via estimators that have the tag `capability:multioutput`.
