### ISSUE TITLE
[MNT] switch to `_check_soft_depedencies` for all version checks through the same entry point

### ISSUE THREAD

**Issue by yarnabrina** [sktime/sktime#5866]
should we use `_check_soft_depedencies` to ensure we route all version checks through the same entry point?

_Originally posted by @fkiraly in https://github.com/sktime/sktime/pull/5858#discussion_r1470265925_

**Comment by fkiraly** [comment]
Do you know how many checks by other means there are?

I do not count sth like `_check_estimator_deps`, since that calls `_check_soft_depedencies` internally.

**Comment by yarnabrina** [comment]
I meant checks with `__version__` atrributes directly.

![image](https://github.com/sktime/sktime/assets/39331844/9574b2d4-6543-4cca-bb3d-5938875cf764)

It's not very high, but there are some 10-15 instances of this.

**Comment by fkiraly** [comment]
Question - are there architectural benefits to switch? Given that `_check_soft_dependencies` is also just looking at `__version__`, in a case where the package is present.

**Comment by yarnabrina** [comment]
Probably not, and direct check is probably more readable for new developers, new in the sense of familiarity with sktime codebase.

**Comment by fkiraly** [comment]
ok, should we close this then?
