### ISSUE TITLE
[BUG] use of LabelEncoder leads to failure of scitype

### ISSUE THREAD

**Issue by yarnabrina** [sktime/sktime#5867]
## Reproducible Example

```python
import numpy
import pandas
from sklearn.preprocessing import LabelEncoder, StandardScaler
from sktime.forecasting.arima import ARIMA
from sktime.transformations.series.subset import ColumnSelect

different_series = ["A", "B"]
different_dates = pandas.date_range(start="2000-01-01", end="2000-03-31", freq="D")

number_of_series = len(different_series)
number_of_timesteps = len(different_dates)

random_generator = numpy.random.default_rng(seed=0)

different_values = [1, 2, 3]

sample_data = {
    "series": numpy.repeat(different_series, number_of_timesteps),
    "dates": numpy.tile(different_dates, number_of_series),
    "P": random_generator.standard_normal(size=number_of_series * number_of_timesteps),
    "Q": random_generator.choice(
        different_values, size=number_of_series * number_of_timesteps, replace=True
    ),
    "R": random_generator.standard_exponential(size=number_of_series * number_of_timesteps),
}

sample_dataset = pandas.DataFrame(data=sample_data)
sample_dataset = sample_dataset.set_index(["series", "dates"])

pipeline = (ColumnSelect(columns=["Q"]) * LabelEncoder()) ** (StandardScaler() * ARIMA())
pipeline.fit(sample_dataset[["P"]], X=sample_dataset[["Q", "R"]])
```

## Error

```
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/path/to/environment/lib/python3.10/site-packages/sktime/forecasting/base/_base.py", line 380, in fit
    self._fit(y=y_inner, X=X_inner, fh=fh)
  File "/path/to/environment/lib/python3.10/site-packages/sktime/forecasting/compose/_pipeline.py", line 494, in _fit
    X = t.fit_transform(X=X, y=y)
  File "/path/to/environment/lib/python3.10/site-packages/sktime/transformations/base.py", line 658, in fit_transform
    return self.fit(X, y).transform(X, y)
  File "/path/to/environment/lib/python3.10/site-packages/sktime/transformations/base.py", line 458, in fit
    X_inner, y_inner = self._check_X_y(X=X, y=y)
  File "/path/to/environment/lib/python3.10/site-packages/sktime/transformations/base.py", line 1115, in _check_X_y
    iterate_y = _most_complex_scitype(y_inner_scitype, y_scitype)
  File "/path/to/environment/lib/python3.10/site-packages/sktime/transformations/base.py", line 942, in _most_complex_scitype
    return _most_complex_scitype(scitypes)
  File "/path/to/environment/lib/python3.10/site-packages/sktime/transformations/base.py", line 944, in _most_complex_scitype
    raise ValueError("no series scitypes supported, bug in estimator")
ValueError: no series scitypes supported, bug in estimator
```

## Expectation

I expected that ARIMA will be fitted with two regressor: Q and R, where Q is the encoded version of original Q.

## Version

Operating System: macOS Sonoma 14.3
Python: 3.10.12
sktime: 0.25.1

**Comment by yarnabrina** [comment]
FYI @fkiraly, @benHeid , I think I tried something equivalent to this in the past, a few months before, but now it is failing. Do we not support categorical/text values at all?

Also while creating the reproducible, I noticed that I can not use `different_values = ["x", "y", "z"]`. It fails with `TypeError` during scitype check, and this seems to be the underlying error:

```pycon
>>> 
>>> sample_dataset
                          P  Q         R
series dates                            
A      2000-01-01  0.125730  z  2.529163
       2000-01-02 -0.132105  x  1.062790
       2000-01-03  0.640423  z  1.458715
       2000-01-04  0.104900  y  2.213437
       2000-01-05 -0.535669  z  1.880996
...                     ... ..       ...
B      2000-03-27  1.028854  z  1.756927
       2000-03-28 -1.934960  x  0.085557
       2000-03-29 -0.239937  z  0.217971
       2000-03-30 -0.204522  x  0.881417
       2000-03-31 -1.042860  z  1.766432

[182 rows x 3 columns]
>>> 
>>> from sktime.datatypes import check_raise
>>> 
>>> check_raise(sample_dataset, "pd_multiindex_hier")
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/Users/aniray1/conda-environments/forecast/lib/python3.10/site-packages/sktime/datatypes/_check.py", line 278, in check_raise
    raise TypeError(msg)
TypeError: input should not have column of 'object' dtype
>>> 
```

**Comment by fkiraly** [comment]
Yes, as per current specification, `object` `dtype`-d columns are not supported.

We recently relaxed that for `Table` scitypes, but not for the time series scitypes.

In your example, thee pipeline will raise the error, even though internally it would run through.

I would suggst to relax the requirement, I agree it is maybe too strict (we did away with it for `Table` for similar reasons).

One would have to remove the lines `if "object" in obj.dtypes.values:` and following. Do you want to check whether that fits your use case? If yes, I would  be in favour of the chage.

**Comment by fkiraly** [comment]
PS: let me know if you have any issus with `sktim 0.26.0`, I see you are on 0.25.1.

**Comment by yarnabrina** [comment]
> Yes, as per current specification, `object` `dtype`-d columns are not supported.
> 
> We recently relaxed that for `Table` scitypes (when refactoring classification `y` which is categorical), but not for the time series scitypes.
> 
> In your example, the pipeline will raise the error, even though internally it would run through.
> 
> I would suggst to relax the requirement, I agree it is maybe too strict (we did away with it for `Table` for similar reasons).
> 
> One would have to remove the lines `if "object" in obj.dtypes.values:` and following. Do you want to check whether that fits your use case? If yes, I would be in favour of the change. (we should also add your code as a test)
> 
> An alterative option would be to add a config to disable checks, but that feels a bit hacky.

I'd definitely want to add this support. Not sure what I checked last time, but now it's bothering me for work. I definitely want to add at least minimal support of categorical variables so encoded versions of those (label/ordinal) can be used.

I'd also prefer to have a way to use one hot encoding (or anything that transforms series to dataframes), but especially in the way I use it, it's very difficult to use that with sktime pipeline as of now. I haven't checked the graphical pipeline though, but that will probably be even more difficult.

**Comment by yarnabrina** [comment]
> PS: let me know if you have any issues with `sktim 0.26.0`, I see you are on 0.25.1.

I didn't have a specific reason yesterday, it was just that I haven't updated till then in my office environment. Tried that today, and 2/3 automated pipelines failed. Now all these pipelines have too many different configurations to create dynamic pipelines, so I am not sure yet exactly what is the issue. I'll report back about that soon.

**Comment by fkiraly** [comment]
> Tried that today, and 2/3 automated pipelines failed. 

Hm, that is really strange. As usual, diff betwen 0.25.last and 0.26.0 are minimal, only containing changes that are considered risky for breaking downstream. Guess we did a good job in putting the latter into the bucket for 0.26.0...

Ther are imo only two PR that could cauase problems, #5817 and #5776 (out of 5 total in 0.26.0).

**Comment by fkiraly** [comment]
> I'd definitely want to add this support.

So, please go ahead! Remove the check and add your case as test case, perhaps more.

**Comment by yarnabrina** [comment]
> Hm, that is really strange. As usual, diff betwen 0.25.last and 0.26.0 are minimal, only containing changes that are considered risky for breaking downstream. Guess we did a good job in putting the latter into the bucket for 0.26.0...

No, actually yesterday our pipelines had 0.25.0. The version I posted above is for my office laptop, not in the deployed version. So, something may have happened in 0.25.0 vs 0.25.1 as well.

**Comment by fkiraly** [comment]
are you not doing pre-test or staging before you deploy?

Either way, if it is "something `mi_index` as you wrote elsewhere, I suspect https://github.com/sktime/sktime/issues/5681

**Comment by yarnabrina** [comment]
I think it's an effect if that, but it's more complicated error scenario. I
debugged and found that the error occurs if the model is trained with
0.25.0 and prediction uses 0.25.1. This particular situation happened with
us in an unfortunate imagePullPolicy specification, but I think it means
the patch release 0.25.1 was not compatible with the previous release?

Let me know if you'll consider this as a bug, I have a small enough script
to reproduce over two different python kernels.

**Comment by fkiraly** [comment]
I think it is more of a design issue, opened one here: https://github.com/sktime/sktime/issues/5870

The requirement - so far not on the radar - is inter-version compatibility of serialized estimators.

**Comment by yarnabrina** [comment]
@fkiraly can you confirm if your suggestion for "object" dtype was for both issues or not?

In the original issue with `LabelEncoder`, I faced this:

> ValueError: no series scitypes supported, bug in estimator

And, then I also noted another observation for string column, where I got this:

> TypeError: input should not have column of 'object' dtype

If I comment out "object" checks in Series and Panel `scitype` checks, the second issue is gone (I'll create a PR tonight), but the first issue remains. Is this in line with your expectation?

**Comment by fkiraly** [comment]
> Is this in line with your expectation?

No, can you kindly explain or link to the first issue? I probably missed sth there. Optimally, the explanation/link has conditions and isolates the first issue frorm the second one.

**Comment by yarnabrina** [comment]
> can you kindly explain or link to the first issue?

https://github.com/sktime/sktime/issues/5867#issue-2107768571

**Comment by fkiraly** [comment]
Thanks.
I can confirm the bug, and it is coming from `LabelEncoder` being wrapped into `TabularToSeriesAdaptor` by coercion.

The deeper reason seems to be that two things come together:

* `LabelEncoder.fit` has an argument `y`, and only `y`. That is an `sklearrn` contract unknown to me, and the various adapters do not take this into account.
* broadcasting kicks in on your data since it is `Panel`, and `BaseTransformer` tries to broadcast over `y`, because `LabelEncoder` is recognized as having a `y` argument.

How this interaction exactly breaks, is not clear - what seems relevant though is to understand the `sklearn` contract with `y` args only. Is it specified somewhere? I thought that could never happen, having a `y` without an `X`.

**Comment by yarnabrina** [comment]
Searching on `sklearn` repo shows some discussions what other people have faced before. The behaviour seems to be present exclusively for these three estimators:

https://scikit-learn.org/stable/modules/preprocessing_targets.html

**Comment by fkiraly** [comment]
Can you link to some of these discussions?

Silly question, why is it not just a transformer with `X`, and then there is some generic way to apply it to `y`?

We did face the same question in `sktime`, on applying transformers to `X` vs `y`, and even some developers had difficulties wrapping their head around the fact that transformers had a `X` argument in `fit`, but a transformer can also be applied to `y` via the `TransformedTargetForecaster`, and doesn't need to have the argument `y` in `fit`.

From an API design perspective, making a distinction here purely based on what it is later applied to, seems bad and wasteful, as in long-term consequence this would result in two copies of every transformer, one for applying it to `X` and one for applying it to `y`.

**Comment by yarnabrina** [comment]
> Can you link to some of these discussions?

Here are two links. There are more, and usually these are just closed saying `LabelEncoder` is never supposed to be used on `X`.

https://github.com/scikit-learn/scikit-learn/issues/12720
https://github.com/scikit-learn/scikit-learn/issues/3956

**Comment by fkiraly** [comment]
How odd.

Looks like design not fully thought through, but they keep it around for historica reasons?
Woud it not be easy to fix by giving it a second, optional `X` argument?

**Comment by yarnabrina** [comment]
While we discuss about how to support LabelEncoder (the only viable idea I have is have our own with dummy X), how is it handled currently by other users? I haven't used time series classification/regression myself, but are categorical columns not very common there?

I thought I'll try OneHotEncoder for the dummy example above just to see what happens, but got another mtype error.

```pycon
>>> pipeline = (ColumnSelect(columns=["Q"]) * OneHotEncoder()) ** (StandardScaler() * ARIMA())
>>> pipeline.fit(sample_dataset[["P"]], X=sample_dataset[["Q", "R"]])
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/anirban/sktime-fork/sktime/forecasting/base/_base.py", line 380, in fit
    self._fit(y=y_inner, X=X_inner, fh=fh)
  File "/home/anirban/sktime-fork/sktime/forecasting/compose/_pipeline.py", line 494, in _fit
    X = t.fit_transform(X=X, y=y)
  File "/home/anirban/sktime-fork/sktime/transformations/base.py", line 676, in fit_transform
    return self.fit(X, y).transform(X, y)
  File "/home/anirban/sktime-fork/sktime/transformations/base.py", line 593, in transform
    Xt = self._vectorize("transform", X=X_inner, y=y_inner)
  File "/home/anirban/sktime-fork/sktime/transformations/base.py", line 1366, in _vectorize
    Xts = X.vectorize_est(
  File "/home/anirban/sktime-fork/sktime/datatypes/_vectorize.py", line 630, in vectorize_est
    ret = parallelize(
  File "/home/anirban/sktime-fork/sktime/utils/parallel.py", line 72, in parallelize
    ret = para_fun(
  File "/home/anirban/sktime-fork/sktime/utils/parallel.py", line 92, in _parallelize_none
    ret = [fun(x, meta=meta) for x in iter]
  File "/home/anirban/sktime-fork/sktime/utils/parallel.py", line 92, in <listcomp>
    ret = [fun(x, meta=meta) for x in iter]
  File "/home/anirban/sktime-fork/sktime/datatypes/_vectorize.py", line 679, in _vectorize_est_single
    est_i_result = est_i_method(**args_i)
  File "/home/anirban/sktime-fork/sktime/transformations/base.py", line 604, in transform
    X_out = self._convert_output(Xt, metadata=metadata)
  File "/home/anirban/sktime-fork/sktime/transformations/base.py", line 1230, in _convert_output
    raise TypeError(
TypeError: _transform output of <class 'sktime.transformations.series.adapt.TabularToSeriesAdaptor'> does not comply with sktime mtype specifications. See datatypes.MTYPE_REGISTER for mtype specifications. Returned error message: ["obj must be a pandas.DataFrame, found <class 'numpy.ndarray'>", "obj must be a pandas.Series, found <class 'numpy.ndarray'>", 'obj must be 1D or 2D numpy.ndarray, but found 0D']. Returned object:   (0, 2)    1.0
  (1, 0)        1.0
  (2, 2)        1.0
  (3, 1)        1.0
  (4, 2)        1.0
  (5, 2)        1.0
  (6, 1)        1.0
  (7, 1)        1.0
  (8, 2)        1.0
  (9, 1)        1.0
  (10, 2)       1.0
  (11, 0)       1.0
  (12, 2)       1.0
  (13, 1)       1.0
  (14, 2)       1.0
  (15, 1)       1.0
  (16, 0)       1.0
  (17, 0)       1.0
  (18, 1)       1.0
  (19, 2)       1.0
  (20, 0)       1.0
  (21, 1)       1.0
  (22, 1)       1.0
  (23, 0)       1.0
  (24, 1)       1.0
  :     :
  (66, 1)       1.0
  (67, 2)       1.0
  (68, 0)       1.0
  (69, 2)       1.0
  (70, 2)       1.0
  (71, 2)       1.0
  (72, 0)       1.0
  (73, 0)       1.0
  (74, 1)       1.0
  (75, 0)       1.0
  (76, 0)       1.0
  (77, 0)       1.0
  (78, 0)       1.0
  (79, 2)       1.0
  (80, 2)       1.0
  (81, 1)       1.0
  (82, 2)       1.0
  (83, 1)       1.0
  (84, 0)       1.0
  (85, 0)       1.0
  (86, 0)       1.0
  (87, 2)       1.0
  (88, 1)       1.0
  (89, 0)       1.0
  (90, 0)       1.0
>>>
```

I ran this on your latest [commit](https://github.com/sktime/sktime/pull/5886/commits/11a93c3d538d22301327a84655da97a4e54cadf2) on object dtype support PR. I don't know if it's a new/different issue.

**Comment by fkiraly** [comment]
can you try to `set_config(**{"output_conversion": "off})`, and run `check_is_mtype` or `check_is_scitype` manually? I will try improving the informativeness of the error messages.

**Comment by fkiraly** [comment]
any new insights?

**Comment by yarnabrina** [comment]
Sorry, forgot to comment back. Using `set_config` manually worked, but I didn't get enough time to find what it's doing and how do I apply in my automated pipeline code automatically.

Also, not related to this issue, but one of my older complains, transformers like one hot encoder (which take a series and return a dataframe of multiple columns) are very difficult (to me impossible as I never succeeded) to work with in automated pipelines involving FeatureUnion and ForecastX.

**Comment by fkiraly** [comment]
> Also, not related to this issue, but one of my older complains, transformers like one hot encoder (which take a series and return a dataframe of multiple columns) are very difficult (to me impossible as I never succeeded) to work with in automated pipelines involving FeatureUnion and ForecastX.

How about an example in a new issue, to see how we can improve user experience?

**Comment by Abhay-Lejith** [comment]
@fkiraly @yarnabrina , these are my findings regarding this bug. ( I am referring to the bug mentioned in the very first message in this issue)
In the `_check_X_y` method, `get_tag` seems to incorrectly return the value of the `y_inner_mtype` tag of the `TabularToSeriesAdaptor`. Though set to `None`, it returns `numpy1D` which leads to the scitype error.
https://github.com/sktime/sktime/blob/2387e12003699d217772f6f678746f8c58d198d4/sktime/transformations/base.py#L983-L987

To sum it up, get_tag in line 985 is returning numpy1D instead of None. 

Modifications I made to the code for debugging:
```python
# retrieve supported mtypes
print(self)
X_inner_mtype = _coerce_to_list(self.get_tag("X_inner_mtype"))
y_inner_mtype = _coerce_to_list(self.get_tag("y_inner_mtype"))

X_inner_scitype = mtype_to_scitype(X_inner_mtype, return_unique=True)
y_inner_scitype = mtype_to_scitype(y_inner_mtype, return_unique=True)

print(y_inner_mtype)
print(y_inner_scitype)
```
Output after running the code for reproducing the bug.( present in the first message in this issue)
```
ColumnSelect(columns=['Q'])
ColumnSelect(columns=['Q'])
['None']
[None]
TabularToSeriesAdaptor(transformer=LabelEncoder())
TabularToSeriesAdaptor(transformer=LabelEncoder())
['numpy1D']
['Table']
```

**Comment by fkiraly** [comment]
I see - `y` should be mapped onto `X`. So we need to treat the case where the transformer has only `y` and no `X`.

I think in line 165, we need to check that `self._trafo_has_param_and_default(method, "X")`, and only then set the tag?

We should also add a test.

**Comment by Abhay-Lejith** [comment]
I see now, I didn't notice that the tag was being changed in `__init__`. I'll work on the fix now.
