### ISSUE TITLE
[DOC] Typo in documentation

### ISSUE THREAD

**Issue by jbemis99** [sktime/sktime#5878]
on
https://www.sktime.net/en/stable/examples/AA_datatypes_and_datasets.html#Section-1.1.1:-Time-series---the-%22pd.DataFrame%22-mtype

structure convention: obj.index must be monotonous, and one of

I believe should be:
must be monotonic

Searching the documentation for monotonous finds 6 occurrences.

**Comment by fkiraly** [comment]
Thanks! Pull requests are always appreciated!

**Comment by eduardojp26** [comment]
I can fix this

**Comment by eduardojp26** [comment]
I have opened a new PR with the suggested reviews

**Comment by Kunal9027** [comment]
is this request is open

**Comment by fkiraly** [comment]
ah, this is done but did not get closed by accident, because the original PR was closed and then replaced by this one: https://github.com/sktime/sktime/pull/5946 - which got merged, but by accident not linked to this issue.
