### ISSUE TITLE
[DOC] displaying tags on estimator pages and estimator table

### ISSUE THREAD

**Issue by fkiraly** [sktime/sktime#5905]
It would be nice to display key tags on estimator pages, and optionally in the estimator table.

not sure how to go about this though - design discussion.

**Comment by yarnabrina** [comment]
Related to https://github.com/sktime/sktime/issues/4713? Plus other links you have added there.

**Comment by fkiraly** [comment]
Yes, this is indeed a duplicate - #4713 covers the API reference, #1930 covers the estimator table.

Must have been cryptomnesia.
