### ISSUE TITLE
[BUG] `deep_equals` breaks when comparing `ForecastingHorizon`-s of different length

### ISSUE THREAD

**Issue by MBristle** [sktime/sktime#5915]
**Describe the bug**

Comparing a ForecastingHorizon using the deep_equals with different lengths results in an error.

**To Reproduce**

```python
(Pdb) deep_equals(ForecastingHorizon([1,2,3,4]),ForecastingHorizon([1,2,3,4]))
True
(Pdb) deep_equals(ForecastingHorizon([1,2,3,4]),ForecastingHorizon([1,2,3,44]))
False
(Pdb) deep_equals(ForecastingHorizon([1,2,3,4]),ForecastingHorizon([1,2,3]))
*** ValueError: Lengths must match to compare
(Pdb) deep_equals(ForecastingHorizon([1,2,3,4]),ForecastingHorizon([1,2,3,4,5]))
*** ValueError: Lengths must match to compare
```

**Expected behavior**
```python
(Pdb) deep_equals(ForecastingHorizon([1,2,3,4]),ForecastingHorizon([1,2,3,4]))
True
(Pdb) deep_equals(ForecastingHorizon([1,2,3,4]),ForecastingHorizon([1,2,3,44]))
False
(Pdb) deep_equals(ForecastingHorizon([1,2,3,4]),ForecastingHorizon([1,2,3]))
False
(Pdb) deep_equals(ForecastingHorizon([1,2,3,4]),ForecastingHorizon([1,2,3,4,5]))
False
```

**Additional context**
Further, if the deep_equal method is the preferred method to compare the ForecastingHorizon, it is unclear why logic is not implemented in the `__equals__()` method such that the same behavior is used to compare two forecasting objects. 

Naively, I would expect the following behavior:
```python
(Pdb) ForecastingHorizon([1,2,3,4]) == ForecastingHorizon([1,2,3,4])
True
(Pdb) ForecastingHorizon([1,2,3,4]) == ForecastingHorizon([1,2,3,44])
False
(Pdb) ForecastingHorizon([1,2,3,4]) == ForecastingHorizon([1,2,3])
False
(Pdb) ForecastingHorizon([1,2,3,4]) == ForecastingHorizon([1,2,3,4,5])
False
```

current behavior:
```python
(Pdb) ForecastingHorizon([1,2,3,4]) == ForecastingHorizon([1,2,3,4])
array([ True,  True,  True,  True])

(Pdb) ForecastingHorizon([1,2,3,4]) == ForecastingHorizon([1,2,3,44])
array([ True,  True,  True, False])

(Pdb) ForecastingHorizon([1,2,3,4]) == ForecastingHorizon([1,2,3])
*** ValueError: operands could not be broadcast together with shapes (4,) (3,)

(Pdb) ForecastingHorizon([1,2,3,4]) == ForecastingHorizon([1,2,3,4,5])
*** ValueError: operands could not be broadcast together with shapes (4,) (5,)

```

**Versions**
Branch: main at 0c134d58

System:
    python: 3.10.13 (main, Sep 11 2023, 08:16:02) [Clang 14.0.6 ]
executable: /Users/<USER>/anaconda3/envs/sktime-dev/bin/python
   machine: macOS-14.2.1-arm64-arm-64bit

Python dependencies:
          pip: 23.3.1
       sktime: 0.26.0
      sklearn: 1.3.2
       skbase: 0.7.1
        numpy: 1.26.3
        scipy: 1.10.1
       pandas: 2.1.4
   matplotlib: None
       joblib: 1.3.2
        numba: None
  statsmodels: 0.14.1
     pmdarima: None
statsforecast: None
      tsfresh: None
      tslearn: None
        torch: 2.1.0.post100
   tensorflow: None
tensorflow_probability: None

**Comment by fkiraly** [comment]
@MBristle, thanks for flagging this!

Regarding your observation: yes, adding a length check seems sensible. Odd that this never came up - the location to implement it would be `sktime.utils.deep_equals._deep_equals._fh_equals_plugin`.

Regarding your question why we do not just implement the "equals" dunder properly: this would indeed be the nicest and most idiomatic way. Unfortunately often equality has to be done externally (that's why `deep_equals` exists), because more direct ways lead to trouble.

For `ForecastingHorizon`, I had the same question a while ago, and it led to this PR: https://github.com/sktime/sktime/pull/3079

Turns out there is some obscure hash magic working, related to inheritance from `pandas`, and `pandas` having two simultaneous problems of (a) defaulting to equality per entry, not equality of the entire object, and (b) `pandas` not implementing a `__hash__` dunder, despite implementing a hash method (just not as a dunder).

This gets one down a rabbit hole which ultimately got me stuck. If you have ideas how to save the PR #3079 without domino effects, we would be thankful.

More generally, a rework which reduces or removes the direct inheritance from `pandas` might be a nice long-term goal.

**Comment by fkiraly** [comment]
> Additional request for documentation update: deep_equals seems to be missing from read the docs.

Do we want to advertise it as a public utility? It is mainly for tests, the versio that is meat to be "public" is the one in `scikit-base`.

I would be curious what you are using it for, @MBristle.

**Comment by MBristle** [comment]
@fkiraly, I was playing around with an FH comparison (and ran into the issues described above -  basically, I wanted to make sure that the FH does not change for an EstimatorAdapter between fit and predict  -  as that was given as a property of the original implementation ). Then I looked a bit through the code base to see how the FH comparison was done in other places and came across the deep_equals().

**Comment by fkiraly** [comment]
I see! The `BaseForecaster` boilerplate should take care that the `fh` is not mutated once passed, so any further information on the problem you were investigating would be appreciated.

Either way, let us know if you want to fix it (might be a small fun PR if you've already looked there and gets credit/badges), otherwise it's a quick fix ofr us.

**Comment by MBristle** [comment]
Ok, had a quick look.

So, from my point of view, the issue should be solved in the `_fh_equals_plugin`. However this is implemented in the sktime and the skbase repo. It turns out that calling the deep_equal() plugin calls the function of the skbase repo and not the one of the sktime. I wrote a quick test (not super elaborated and not at the right place) and a fix (which needs to be applied in both repos). I propose I make a PR, and @fkiraly, you can decide then if this is the right way.

**Comment by fkiraly** [comment]
> However this is implemented in the sktime and the skbase repo.

Oh, I see.
Could we add the fix in both places then?

The reason the plugin lives in both places is that `deep_equals` was monolithic, so as part of the refactor, the plugin structure first had to be introduced in `scikit-base`, so multiple dependent packages could then migrate custom modifications to their own plugins. As a step sometime in the future, the plugins for dependent packages will be removed from `scikit-base`.

It is strange though that the `scikit-base` plugins are called first, should it not be the other way round?

For testing, it should suffice to add examples of different length in `EXAMPLES`, in `test_deep_equals`.

**Comment by MBristle** [comment]
> Could we add the fix in both places then?

Sure, that should work, and that is how I tested it locally.

>  As a step sometime in the future, the plugins for dependent packages will be removed from scikit-base.

So basically this solves the issue with the plugin.  The issue is caused by using lists. 
In the deep_equals_custom() function in skbase we iterate over all plugins. The list of plugins at that point is the list of plugins defined in skbase + the plugins passed to the deep_equal():


```
    # call deep_equals_custom with default plugins
    plugins_default = [
        _numpy_equals_plugin,
        _pandas_equals_plugin,
        # _fh_equals_plugin,
    ]

    if plugins is not None:
        plugins_inner = plugins_default + plugins
    else:
        plugins_inner = plugins_default
  ```

therefore the list looks something like: `[ _numpy_equals_plugin,
        _pandas_equals_plugin,
         _fh_equals_plugin,        _numpy_equals_plugin,
        _pandas_equals_plugin,
        _fh_equals_plugin,]`, where the first `_fh_equals_plugin` comes from the base repo, and the second one is the one passed as a parameter to the deep_equals functions from time.
        
        I would suggest removing the _fh_equals_plugin from the base as it is anyways specific to the time series, imo.

**Comment by MBristle** [comment]
I just had a quick check. To fix the issue, only the base part needs adjustment. The sktime part is never called, and, in my opinion, can be removed if not used elsewhere.

**Comment by fkiraly** [comment]
This is now fixed via https://github.com/sktime/skbase/pull/290 and #5954
