### ISSUE TITLE
[BUG] TDistribution pdf does not consider location/scale

### ISSUE THREAD

**Issue by ivarzap** [sktime/sktime#5918]
**Describe the bug**
The location/scale (mu/sigma) are not considered at all in methods: pdf, log_pdf, cdf or ppf

For example, the case pdf:

```    
def pdf(self, x):
        """Probability density function."""
        d = self.loc[x.index, x.columns]
        pdf_arr = gamma((d._df + 1) / 2)
        pdf_arr = pdf_arr / (np.sqrt(np.pi * d._df) * gamma(d._df / 2))
        pdf_arr = pdf_arr * (1 + x**2 / d._df) ** (-(d._df + 1) / 2)
        return pd.DataFrame(pdf_arr, index=x.index, columns=x.columns)
```

Here, in line 6, instead of x**2 one should use ((x - d._mu)/d._sigma)**2

sktime version 0.25.1

**Comment by fkiraly** [comment]
Yes, you are right - FYI @Alex-JG3. I also apologize, I reviewed and did not notice.

Would you like to make a PR with the suggested fixes?

I think most methods are correct if `mu` is 0 and `sigma` is 1 - so we can fix quickly by:

* `pdf`: subtracting `self._mu` from `x` at the start, dividing by `self._sigma`
* `log_pdf`: subtracting `self._mu` from `x` at the start, subtracting `og` of `self._sigma`
* `cdf`: subtracting `self._mu` from `x` at the start
* `ppf`: adding `self_mu` to the result

**Comment by fkiraly** [comment]
(let us know if you'd prefer someone else fixing this - I just thought since you've aready identified most fixes)

**Comment by ivarzap** [comment]
I think that, to the proposed solution, one has to make the changes:

- `self` -> `d`
- `pdf`: `x` -> `(x-d._mu)/d._sigma` and normalize the result dividing by d._sigma
- `log_pdf`: same substitution for `x` as in `pdf` and substract `np.log(d._sigma)` from the result
- `cdf`: same substitution for `x` as in `pdf`
- `ppf`: `ppf` -> `d._sigma * ppf + d._mu`

**Comment by fkiraly** [comment]
yes, agreed, except the first one I do not understand. What do you mean by `self` -> `d`?

**Comment by ivarzap** [comment]
> yes, agreed, except the first one I do not understand. What do you mean by `self` -> `d`?

For the quoted code as it is now:
```
def pdf(self, x):
        """Probability density function."""
        d = self.loc[x.index, x.columns]
        pdf_arr = gamma((d._df + 1) / 2)
        pdf_arr = pdf_arr / (np.sqrt(np.pi * d._df) * gamma(d._df / 2))
        pdf_arr = pdf_arr * (1 + x**2 / d._df) ** (-(d._df + 1) / 2)
        return pd.DataFrame(pdf_arr, index=x.index, columns=x.columns)
```

you claim that one has to:

- subtracting `self._mu` from `x` at the start

I claim that it should be:

- subtracting `d._mu` from `x` and multiplying the result by `d._sigma` at the start

**Comment by ivarzap** [comment]
I am preparing a pull request with all these changes

**Comment by fkiraly** [comment]
> I claim that it should be:

Yes, of course, you are right.
