### ISSUE TITLE
[BUG] TDistribution computes incorrectly variance 

### ISSUE THREAD

**Issue by ivarzap** [sktime/sktime#5919]
**Describe the bug**

TDistribution does not use scale (sigma) for variance computation

```    
def var(self):
...
        df_arr = self._df.copy()
        df_arr = df_arr.astype(np.float32)
        df_arr[df_arr <= 2] = np.inf
        mask = (df_arr > 2) & (df_arr != np.inf)
        df_arr[mask] = df_arr[mask] / (df_arr[mask] - 2)
        return pd.DataFrame(df_arr, index=self.index, columns=self.columns)
```

one should correct the previous to last line to:

```
df_arr[mask] = self._sigma** 2 * df_arr[mask] / (df_arr[mask] - 2)
```

sktime version 0.25.1

**Comment by fkiraly** [comment]
Agreed with diagnosis and proposed solution - would you like to contribute this as a PR?

**Comment by ivarzap** [comment]
> Agreed with diagnosis and proposed solution - would you like to contribute this as a PR?

Ok. I will.
