### ISSUE TITLE
[MNT] add codecov token in Github secrets and use in CI

### ISSUE THREAD

**Issue by yarnabrina** [sktime/sktime#5922]
Recently codecov got an update, and after that our CI seems unable to push the coverage reports. This was first noted in #5896.

Ref. https://github.com/sktime/sktime/pull/5891/checks

![image](https://private-user-images.githubusercontent.com/39331844/303093967-74d709c1-6b93-406b-ac9e-11bbb5b6ba8a.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDc1NDE0MjUsIm5iZiI6MTcwNzU0MTEyNSwicGF0aCI6Ii8zOTMzMTg0NC8zMDMwOTM5NjctNzRkNzA5YzEtNmI5My00MDZiLWFjOWUtMTFiYmI1YjZiYThhLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAyMTAlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMjEwVDA0NTg0NVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTg2OTJkOGFiYmE3NzI5MzFhN2JjMTViZGI0ZWRiYWM3Zjk2Y2UzM2JlMGE4MTljMTBiOWJiN2QxYjRmZTQzZDYmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.erti4h0sNKZnmlOV268075zoKqX3sehxf7RJHtwq-M4)

Ref. https://github.com/sktime/sktime/actions/runs/7806282782

![image](https://private-user-images.githubusercontent.com/39331844/303094418-6837bcd1-1471-4bd2-b3be-187c9c23dd1d.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDc1NDE0MjUsIm5iZiI6MTcwNzU0MTEyNSwicGF0aCI6Ii8zOTMzMTg0NC8zMDMwOTQ0MTgtNjgzN2JjZDEtMTQ3MS00YmQyLWIzYmUtMTg3YzljMjNkZDFkLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAyMTAlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMjEwVDA0NTg0NVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTU3MzFjMDNiZjcwMDQxMWMzY2JjYTE4ZWU0ZGU0ODIwNTE4MmNlZmZjNjhhOWYyYzYwZDNlMGVmMjM2ZWU5NjcmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.PKbIiWyPINQJHOO2Pzqd_5eb9JWgmgiXA0_TZpf4lFI)

Ref. https://github.com/sktime/sktime/actions/runs/7806282782/job/21292552170#step:11:34

![image](https://private-user-images.githubusercontent.com/39331844/303094738-ea00b413-ebaa-4b94-9495-2834561e6c54.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDc1NDE0MjUsIm5iZiI6MTcwNzU0MTEyNSwicGF0aCI6Ii8zOTMzMTg0NC8zMDMwOTQ3MzgtZWEwMGI0MTMtZWJhYS00Yjk0LTk0OTUtMjgzNDU2MWU2YzU0LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAyMTAlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMjEwVDA0NTg0NVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTBmYWY3ZDFlMWU2Mjg1ODM4YTQzNWQxN2YzYThlZGE5ZDc5ZjQ2OTllODRmYmNjNjBhZTU2Yjg2Njg2ZTMyYTQmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.N-K6oPhheZ7JU0MiLFaj9EyiOSgukTHnPXml_DUOn1Q)

The possible solution is likely to add a token in CI.

Ref. https://about.codecov.io/blog/january-product-update-updating-the-codecov-ci-uploaders-to-the-codecov-cli/

![image](https://github.com/sktime/sktime/assets/39331844/502d37dd-69d5-45fa-98c3-8f85cf4e56f3)

**Comment by fkiraly** [comment]
does it say how to generate this token, where you looked?

**Comment by yarnabrina** [comment]
For my personal repositories, I can see easily when I log in to codecov
with my account.

It's listed in step 2 here.

https://docs.codecov.com/docs/quick-start

**Comment by fkiraly** [comment]
just looking into this - while I we do, do you know how only full test runs get uploaded to codecov? Currently coverage is underestimated due to the subsampling of estimators.

**Comment by fkiraly** [comment]
I've added the token now, name is `CODECOV_TOKEN`

**Comment by yarnabrina** [comment]
> I've added the token now, name is CODECOV_TOKEN

Ok, I can give it a try in a new CI PR, but may be it's better to wait for your final CI to merge first. It's likely to have conflicts otherwise.

> do you know how only full test runs get uploaded to codecov?

I thought I addressed in my original version of "new CI" with flags only. I could see different values for different runs. For example, only test-all workflow will use the `complete` flag, while everything else (i.e. all normal CI runs) will use `incomplete` flag. If you are seeing same values, my guess is due to the fact test-all now always fails becuase of the blog notebook lint fail reason. I still don't know how to skip a specific file, so right now that workflow is being useless.

**Comment by fkiraly** [comment]
> If you are seeing same values, my guess is due to the fact test-all now always fails becuase of the blog notebook lint fail reason.

I see, thanks for reminding me. Indeed, this is another thing that makes no sense about the CRON tests.

Let's just disable `pre-commit` and trust that regular diff-based testing in the normal PR is enogh. Further explanation here:
https://github.com/sktime/sktime/pull/5925
