### ISSUE TITLE
[ENH] proper crediting of interface classes - how to credit author(s) of interfaced class

### ISSUE THREAD

**Issue by fkiraly** [sktime/sktime#5938]
In our recent rework of the estimator table, I stumbled upon a problem:

how to credit the authors of the interfaced class? In many cases, the `sktime` estimator is a thin wrapper, as opposed to `sktime` native classes where the entire logic lives in `sktime`.

In the estimator table, the author name appears prominently, but additional information as in the docstring does not.
Currently, we credit authors of the interfaced packaged, and a reference to it is usualy the first or second line.

However, a user seeing the estimator tables does *not* get to see these lines, ony the author/maintainer information.

How should we solve this?

Some options:

* one more tag for authors of interfaced artefacts
* simply credit authors of the interfaced class in the `authors` tag

**Comment by fkiraly** [comment]
FYI @benHeid, @yarnabrina, @sktime/core-developers, thoughts?

**Comment by yarnabrina** [comment]
Can you please give an example of what you would like to show but currently not possible? Say, with `AutoARIMA` from `pmdarima`?

**Comment by fkiraly** [comment]
`tgsmith61591`, `ksunkaexp`, I suppose? Or, a link to alkaline-ml.

Not that it is not possible to add these to authors, my issue is that the credits are not visible in the estimator table as well as they are in the docstring, so I'm wondering whether - and if yes what - we should do here.

**Comment by fkiraly** [comment]
How about the following rule: if the class is an 1:1 interface, or mostly that, then the `"authors"` tag should credit authors of the upstream class?

**Comment by yarnabrina** [comment]
This makes perfect sense, but I will note an observation:

1. this is possibly recursive, e.g pmdarima adapter author in sktime, pmdarima author (and/or maintainer, need not be same), original R code author (in this case from forecasts, not applicable for all adapters), original research paper author (applicable most of the times).

2. not everyone may be aware of them while contributing code in sktime, for example admittedly I didn't know who all to give credict to except Hyndman from the above recursive list.

**Comment by fkiraly** [comment]
> this is possibly recursive, e.g pmdarima adapter author in sktime, pmdarima author (and/or maintainer, need not be same), original R code author (in this case from forecasts, not applicable for all adapters), original research paper author (applicable most of the times).

Hmmm.

* re research paper author, we have (a) excluded that from `"authors"` explicitly, but require it in `References`, so that "recursion" does not apply to the `"authors"` field.
* re adapter, my proposed policy would be to end at the first point which is not an 1:1 interface (or mostly so). Since `pmdarima` adds substantial logic above `statsmodels`, it is fair to copy their author credits, and refer to the docs for mor granular citation practice.

I would argue from this being similar in scientific citation practice, where we apply to code logic (not methodological content, that's covered in `References`).

* if you copy-paste a paper, all credits are due to the original authors
* of you copy-paste and reformat, you would still give all credits to the original authors but not to the copy-editor
* if you copy-paste parts and add significant new parts, credits go to authors of both, with clear statement who wrote what. I think that's the situation with an adapter, since adaptation logic is added.
* if you cite but not copy-paste, and produce new content on top, credits go only to the authors of the new content, while citations are assumed to be precise and exhaustive. This is the case with sth like `pmdarima` being based on `statsmodels`, but adding auto-ml features on top.

**Comment by fkiraly** [comment]
> not everyone may be aware of them while contributing code in sktime, for example admittedly I didn't know who all to give credict to except Hyndman from the above recursive list.

Well, for 1:1 interfaces it should be easy to look up - and if not, we can still look out for this as core devs.

**Comment by fkiraly** [comment]
(policy to credit upstream authors in `authors` field has been adopted)
