### ISSUE TITLE
[MNT] CI is failing on `main`

### ISSUE THREAD

**Issue by yarnabrina** [sktime/sktime#5940]
CI on `main` is failing for 2 of the latest commits in exact same jobs:

1. 17e438222c507cb7db2ed4662e2e29d0666c3e2c
2. 4986b43052dae47c6ae7a559900c941ef435291a

The jobs are:

1. Install and test / detect changes (push)
2. Install and test / base / detect (push) 
3. Install and test / module / detect (push) 
4. Install and test / other / detect (push)

All of them are failing with this:

```shell
Get current git ref
  /usr/bin/git branch --show-current
  fatal: not a git repository (or any of the parent directories): .git
Error: The process '/usr/bin/git' failed with exit code 128
```

Questions:

1. Why is it failing on `main` only, but pull requests are passing?
2. Why did it not fail with this before #5785?

FYI @fkiraly

**Comment by fkiraly** [comment]
That is very odd.

Is it perhaps related to these failures in the new CI:
https://github.com/sktime/sktime/issues/5706#issuecomment-1879682843

which we discussed but afaik never diagnosed?

**Comment by yarnabrina** [comment]
I don't think it's same error. Now it explicitly says `git` is missing. Can we add a checkout step before just in case?

(I do not have an explanation why, it's just what I saw as suggested in issues in action repository. It was working for us earlier, so it's just a guess.)

**Comment by fkiraly** [comment]
the simplest solution might be, restore previous state for merges to `main`, leave status quo for PR CI? That would multiply workflows though.

**Comment by yarnabrina** [comment]
![image](https://github.com/sktime/sktime/assets/39331844/6b73b268-77cf-4af0-9791-aad97ef5e8fa)

It worked.
