### ISSUE TITLE
[BUG] `FourierFeatures` does not work as expected in `ForecastingPipeline`

### ISSUE THREAD

**Issue by albahhar** [sktime/sktime#5975]
**Describe the bug**

Using FourierFeatures in a forecasting pipeline does not produce the same results as using FourierFeatures separately then passing the features to a forecaster. The pipeline produces a flat forecast while the result should not be flat. 

**To Reproduce**

```python
import pandas as pd
import numpy as np

from sktime.forecasting.base import ForecastingHorizon
from sktime.forecasting.compose import ForecastingPipeline, TransformedTargetForecaster
from sktime.forecasting.statsforecast import StatsForecastAutoARIMA
from sktime.transformations.compose import YtoX
from sktime.transformations.series.exponent import SqrtTransformer
from sktime.transformations.series.fourier import FourierFeatures
from sktime.utils.plotting import plot_series
import matplotlib.pyplot as plt


dates = pd.date_range(start="2024-01-01", end="2024-04-01", freq="1H")
calls_per_minute_low = 100 * 60
calls_per_minute_high = 500 * 60
calls = pd.Series(
    index=dates,
    data=np.random.randint(low=calls_per_minute_low, high=calls_per_minute_high, size=len(dates))
)


fh = ForecastingHorizon(values=range(1, 168+1), is_relative=True, freq="H")

arima = StatsForecastAutoARIMA(sp=1,d=0,D=0)

fourier = FourierFeatures(sp_list=[24, 24*7], fourier_terms_list=[10, 5])
fourier.fit(calls)
X_train = fourier.transform(calls)
future = pd.Series(data=1, index=fh.to_absolute_index(calls.index.max()))
X_pred = fourier.transform(future)
pred_arima = arima.fit_predict(y=calls, X=X_train, X_pred=X_pred, fh=fh)

fourierArimax = ForecastingPipeline([
    YtoX(),
    FourierFeatures(sp_list=[24, 24*7], fourier_terms_list=[10, 5]),
    StatsForecastAutoARIMA(sp=1,d=0,D=0),
])

pred_fourierArimax = fourierArimax.fit_predict(y=calls, fh=fh)

fig, ax = plot_series(calls.tail(168), pred_arima, pred_fourierArimax, labels=["calls", "Arima", "FourierArimaxPipeline"])
plt.show()
```

**Expected behavior**

pipeline should produce the same forecast as no pipeline code.

**Additional context**

Here is a plot for clarity
![image](https://github.com/sktime/sktime/assets/24213087/39930d58-3be4-4e7e-b8d1-75d910d64dee)

**Versions**
<details>

</details>

**Comment by fkiraly** [comment]
minor added info: the index type does not seem ot matter.

**Comment by fkiraly** [comment]
found the reason: if `X` is `None`, the `ForecastingPipeline` ignores its transformers, no matter what.

Under current circumstances, passing a dummy `X` is a workaround, but this is unintuitive. Let's see what happens if we allow a `None` `X` to pass.

**Comment by fkiraly** [comment]
Proposed solution:

* `X=None` is not ignored but passed on to transformer chain
* transformers are allowed to take `X=None` as input
* `YfromX` considers `X=None` as valid input , if not already

**Comment by fkiraly** [comment]
What is odd though that the ARIMA model produces constant predictions - are there maybe two bugs here?

**Comment by albahhar** [comment]
I think both models produce constant predictions. The variations in the first model are due to the Fourier terms which are not present in the second model. This is just my guess though.
