### ISSUE TITLE
[ENH] Add options for short names in catch22

### ISSUE THREAD

**Issue by julnow** [sktime/sktime#5981]
**Is your feature request related to a problem? Please describe.**
The original catch22 package (and pycatch22 as well) introduced short names option, saving the name of variable into a column (instead of 1,2 etc.). It would be very useful to implement here as well.

**Describe the solution you'd like**
A solution would be similar to https://github.com/DynamicsAndNeuralSystems/pycatch22/commit/6c9cb078dd76006d8faaf547e9dbe7a98fda1859, but I'd need to understand better where the column are named after transformation in this case

**Comment by julnow** [comment]
I'd be happy to impalement it, but I'd need for context as how the names are picked for final columns

**Comment by fkiraly** [comment]
nice idea!

To point out, there are actually two catch22 estimators: `Catch22`, which is a reimplementation, and `Catch22Wrapper`, which is a direct interface to `pycatch22` - which of the two are you are referring to?

Possibly related: point 3 in https://github.com/sktime/sktime/issues/2254

**Comment by fkiraly** [comment]
In `Catch22`, the column naming happens in `_transform_case` - implicitly, in the line `c22[dim + n] = self._get_feature_fun(feature)(*args)`, where a value is written.

I think this could be done more elegantly, and the long if/else could be replaced.

In `Catch22Wrapper`, the names are coming directly from `pycatch22`.

**Comment by julnow** [comment]
@fkiraly okay, I'll try and look at it once I'm free!

**Comment by fkiraly** [comment]
FYI @anniegbryant

**Comment by fkiraly** [comment]
@julnow, I've looked into `Catch22Wrapper`, it had a lot of legacy code internally related to looping over an outdated data container, I've refactored it here to be more easily readable: https://github.com/sktime/sktime/pull/5983

This should now be a very direct interface to `pycatch22`.
I've also added a `col_names` arg which allows to control return columns.

I have *not* dealt with short names, this would have to enter at the start, i.e., parsing user options, and at the end, i.e., as an option for column names - feel free to look into that, I am not going to for now.

Starting off the branch #5983 should hopefully make things easier, and avoid you having to deal with legacy data types.

**Comment by julnow** [comment]
@fkiraly oh I already started working on numba implementation in 'Catch22Extractor'
Here's PL (the naming part itself still in progress, but I simplified the current implementation with many if elses) https://github.com/sktime/sktime/pull/5989

**Comment by fkiraly** [comment]
ah, that's the other estimator, so that's perfectly fine!
