### ISSUE TITLE
[DOC] Bullet point not rendered properly on feature_selection.py

### ISSUE THREAD

**Issue by oleeviyababu** [sktime/sktime#5993]
#### Describe the issue linked to the documentation

Under Time series transformations (https://www.sktime.net/en/latest/api_reference/transformations.html) in 
FeatureSelection , bullet point is not rendered properly for “feature-importances” under the  FeatureSelection class.

**Comment by fkiraly** [comment]
good spot! Thanks for fixing.

**Comment by oleeviyababu** [comment]
Thankyou @fkiraly
