### ISSUE TITLE
[ENH] `NeuralForecastRNN` should auto-detect `freq`

### ISSUE THREAD

**Issue by fkiraly** [sktime/sktime#6003]
Right now, a `freq` argument needs to be passed to the constructor of `NeuralForecastRNN`, and it will raise exception if not.

To my understanding, this must always be identical with the `freq` of the data (as `pandas`  coerced),
Therefore, this information is available in `fit`, so why not have a default setting of `"auto"`, in which case `fh.freq` is used? This would also be deprecation safe, as an arg without default would get one.

**Comment by fkiraly** [comment]
FYI @yarnabrina

**Comment by yarnabrina** [comment]
I replied to your comment in the PR, but I think it got lost in later conversations.

I'm not sure if I understand how to use `fh.freq` always. If user passes a relative `fh`, say `[1, 6, 12]`, will that object always have a `freq` attribute? May be that is handled in `BaseForecaster` or in `ForecastingHorizon`, but I'm not very familiar with those.
