### ISSUE TITLE
[ENH] Allow `return_n_best_forecasters` in  `ForecastingGridSearchCV ` to be -1 (select all forecasters)

### ISSUE THREAD

**Issue by arnaujc91** [sktime/sktime#6027]
**Is your feature request related to a problem? Please describe.**
I would like the class `ForecastingGridSearchCV ` to have a possibility to return ALL forecasters. Right now we have the `return_n_best_forecasters ` argument in the API which lets you choose how many forecasters you want to return

**Describe the solution you'd like**
I would like to pass -1 to `return_n_best_forecasters ` and automatically get back all the forecasters fit.

This is just an idea that i think would be helpful.

**Comment by fkiraly** [comment]
sounds like a good idea to me - we should do it in all the other forecasting tuners too, and not forget to update docstrings.

Marking this a good first issue since I think it's a nicely defined entry contribution.

**Comment by fkiraly** [comment]
> I'm new here, so I don't know how assignments work here

Semi-formal - you can consider yourself assigned if you post on the issue and a core dev comments.

We track assignments more strictly (kanban board, assigned developers) only for intensive workstreams, but these last typically only through the summer period, which starts with GSoC and internships.

So: all yours!

**Comment by fkiraly** [comment]
PS: you can even make a contribution or PR without announcement if you want, of course it is "safer" to open an issue and describe the proposed work before, to avoid things like duplication or design incompatibilities.
