### ISSUE TITLE
[BUG] "cancel on push" workflow runs after impacted "install and test"

### ISSUE THREAD

**Issue by fkiraly** [sktime/sktime#6036]
Good first issue for people experienced with GitHub Actions.

The "cancel on push" workflow runs after "install and test", severely compromising its usefulness.

In a situation like current, where there are regularly periods in which more CI are queued than can simultaneously run, this leads to significant parts of the "install and test" running before the cancellation of them gets triggered.

Notably, this causes significant test load to be carried out that - by how the logic currently stands - in jobs that are intended to be eventually cancelled, hence this is completely superfluous.

The logic issue comes from the limitation of maximal simultaneous workers. This can lead to workers that the "cancel on push" job is meant to cancel getting priority over the "cancel on push" job, triggered later.

The obvious solution is ensuring that, out of the two jobs triggered, "cancel on push" is always executed first, or at least with prioity before any other workers are assigned to "install and test".

Is there a way to give "cancel on push" absolute priority before anything else?

**Comment by fkiraly** [comment]
I think this is the right resource:
https://docs.github.com/en/actions/using-workflows/workflow-syntax-for-github-actions#concurrency

So the solution would probably be:

* remove the `cancel.yml` workflow entirely
* add an appropriate `concurrency` flag to the "install and test" workflow, ensuring that only PR from the same branch (and not, say, everything), gets cancelled

**Comment by wub53** [comment]
Hi @fkiraly , would love to take up this issue !

**Comment by fkiraly** [comment]
thanks - all yours!

**Comment by fkiraly** [comment]
@MEMEO-PRO, @yarnabrina  - looks like it worked! Nice!
