### ISSUE TITLE
[MNT] Test failures on `main` due to `deep_equals` failing on `sklearn` `RandomForestRegressor.__len__`

### ISSUE THREAD

**Issue by yarnabrina** [sktime/sktime#6048]
I trigger `test all` workflow to test #6041 attempt, and there are plenty of failures. These look like genuine failures.

Link: https://github.com/sktime/sktime/actions/runs/8120198495

Example: `AttributeError: 'RandomForestClassifier' object has no attribute 'estimators_'`

FYI @fkiraly @benHeid

**Comment by fkiraly** [comment]
it would be good to see package versions - could you add "show dependencies" steps to these, like in `test.yml`?

```

      - name: Show dependencies
        run: python -m pip list
```

I'll look into these - since these are `deep_equals` related, it might be `skbase 0.7.4`, and specifically related to https://github.com/sktime/skbase/pull/290, although I do not see how. I also thought we tested this.

FYI @MBristle

**Comment by fkiraly** [comment]
Here's the MRE:

```python
from sklearn.ensemble import RandomForestRegressor
from sktime.utils.deep_equals import deep_equals

deep_equals(RandomForestRegressor(), RandomForestRegressor())
```

**Comment by fkiraly** [comment]
Yes, I see, this is indeed `skbase 0.7.4` related, and to https://github.com/sktime/skbase/pull/290.

The reason is, in some tests we are comparing `RandomForestRegressor` instances before running `fit`. The `deep_equals` utility now has a check for `len`, used only if the object has it.

However, `len(RandomForestRegressor())` causes an exception if it has not been fit.

More generally, It seems we cannot assume that `hasattr(obj, "__len__")` is sufficient to guarantee that `len(obj)` will not break.

The solution would be, in `skbase`, to replace the check by a `safe_len`, which gives -1 in case of exception, or similar.

**Comment by fkiraly** [comment]
Learning 2: we need to run *the full test suite*, not just incremental tests, with `skbase`, before releasing the new `skbase` version.

**Comment by fkiraly** [comment]
So, the idea to fix:

```python
def safe_len(x):
    if hasattr(x, "__len__"):
        try:
            x_len = len(x)
        except Exception:
            return -1
    return -1
```

This works:

```python
from sklearn.ensemble import RandomForestRegressor
from sktime.utils.deep_equals import deep_equals

safe_len(RandomForestRegressor())
```

**Comment by yarnabrina** [comment]
Here's the `pip list` output: https://github.com/sktime/sktime/actions/runs/8120198495/job/22197293663#step:3:359

I think you added these as part of your two CI PR's.

---

Sorry, can't help on len things, not familiar with their inner workings.

**Comment by fkiraly** [comment]
the `pip list` is not shown in the job you linked - not sure why it is the case?

**Comment by fkiraly** [comment]
`skbase` bug report: https://github.com/sktime/skbase/issues/302

**Comment by fkiraly** [comment]
It would be very much appreciated if you could give the fix a review: https://github.com/sktime/skbase/pull/303

**Comment by yarnabrina** [comment]
> the `pip list` is not shown as a separate step in the job you linked - not sure why it is the case?

The installation happens as part of action, not of workflow but one level deeper.

---

Fix looks okay to me but quite a few CI hobs were failing.

**Comment by fkiraly** [comment]
> The installation happens as part of action, not of workflow but one level deeper.

I see - can we move it up to be more findable?

**Comment by fkiraly** [comment]
> Fix looks okay to me but quite a few CI hobs were failing.

But all tracks back to the same last steps.

**Comment by yarnabrina** [comment]
I didn't add these steps originally for this specific reason of lack of visibility, but probably there's some way. I don't know readily, have to think.

**Comment by fkiraly** [comment]
I mean, all exceptions come from the same place, so the fix should take care of them.

**Comment by fkiraly** [comment]
FYI @MBristle - perhaps you have sth to add, as you were relying on `deep_equals`?

**Comment by fkiraly** [comment]
resolved as a failure - @yarnabrina, what are your opinions on actions? E.g., pulling versions, adding tests either in `sktime` or `skbase`?

**Comment by yarnabrina** [comment]
If possible (I don't know), we should try to trigger test all workflow automatically if skbase release workflow is triggered. Triggering workflow in different repository is possible in Gitlab, so I suppose Github supports as well. If that's done, it'll prevent us from making a skbase release that will break sktime.

I don't know what other unit tests can be added in either of the two repositories, so can't suggest. My only other suggestion will be to update in pyproject.toml amd in meta.yaml in conda-forge that never ever resolve to versions X and Y of skbase.

**Comment by fkiraly** [comment]
> If that's done, it'll prevent us from making a skbase release that will break sktime.

I used to do that for all major releases, until `scikit-base` got reasonably stable. We have a similar PR for `sklearn` #4611.

I'm not sure how one would do that automatically, but it's perhaps also worth doing this in advance for major releases of other core deps - `pandas` breaks things frequently, and `sklearn` occasionally has issues.

**Comment by fkiraly** [comment]
Should we open a new issue to automate this, and have a dashboard that flashes a red light when any `main` or pre-release starts causing failures?

**Comment by yarnabrina** [comment]
For automated approach,  here's a reference 

https://github.com/orgs/community/discussions/26323

Closing this issue as resolved.
