### ISSUE TITLE
[BUG] Tests failing on main after recent `tensorflow` and `mlflow` releases

### ISSUE THREAD

**Issue by yarnabrina** [sktime/sktime#6094]
Ref. https://github.com/sktime/sktime/actions/runs/8211839419

FYI @achieveordie for mlflow error

> FAILED sktime/utils/tests/test_mlflow_sktime_model_export.py::test_cnn_model_save_and_load[pickle] - ValueError: Invalid filepath extension for saving. Please add either a `.keras` extension for the native Keras format (recommended) or a `.h5` extension. Use `tf.saved_model.save()` if you want to export a SavedModel for use with TFLite/TFServing/etc. Received: filepath=/tmp/pytest-of-runner/pytest-0/popen-gw0/test_cnn_model_save_and_load_p0/model/model/keras.
FAILED sktime/utils/tests/test_mlflow_sktime_model_export.py::test_cnn_model_save_and_load[cloudpickle] - ValueError: Invalid filepath extension for saving. Please add either a `.keras` extension for the native Keras format (recommended) or a `.h5` extension. Use `tf.saved_model.save()` if you want to export a SavedModel for use with TFLite/TFServing/etc. Received: filepath=/tmp/pytest-of-runner/pytest-0/popen-gw2/test_cnn_model_save_and_load_c0/model/model/keras.

FYI @fkiraly for classification error

> FAILED sktime/classification/tests/test_base.py::test_deep_estimator_full[object-adamax] - TypeError: 'list' object is not callable

**Comment by achieveordie** [comment]
Thanks, I'll take a look at it

**Comment by fkiraly** [comment]
second one looks `tensorflow` related.

**Comment by benHeid** [comment]
First one seems also tensorflow related. A few hours ago version `2.16.1` was released. Now it requires that the file ending is either `.keras` or `.h5`

**Comment by benHeid** [comment]
I think I spotted the error. I try to create a fast PR..

**Comment by yarnabrina** [comment]
Multiple failures in test-all from this tensorflow issue 

https://github.com/sktime/sktime/actions/runs/8218120067

**Comment by benHeid** [comment]
The linked PR #6098 should fix them.
