### ISSUE TITLE
[MNT] change cycle for renaming `cINNForecaster` to `CINNForecaster`

### ISSUE THREAD

**Issue by geetu040** [sktime/sktime#6120]
This issue tracks the change cycle for renaming
- `cINNForecaster` to `CINNForecaster` in `sktime.forecasting.conditional_invertible_neural_network`
- `cINNNetwork` to `CINNNetwork` in `sktime.networks.cinn`

The change cycle will be implemented in 3 steps with each version as follow:

- [x] 0.28.0
  - [x] create aliases
    - [x] `CINNForecaster = cINNForecaster`
    - [x] `CINNNetwork = cINNNetwork`
  - [x] create deprecation warning

- [x] 0.29.0
  - [x] rename class
    - [x] `cINNForecaster` to `CINNForecaster`
    - [x] `cINNNetwork` to `CINNNetwork`
  - [x] update deprecation message
  - [x] switch the aliases
    - [x] `cINNForecaster = CINNForecaster`
    - [x] `cINNNetwork = CINNNetwork`

- [x] 0.30.0
  - [x] remove aliases altogether
  - [x] remove deprecation warning

**Comment by fkiraly** [comment]
yes, that's how I would do it.

We need to check with @benHeid first whether he is ok with this renaming.

Typically, the release manager(s) make the changes directly at the release, searching for comments of the form `# TODO: 0.28.0`

**Comment by fkiraly** [comment]
another question I'm now wondering about is why `pre-commit` did not pick up the name. Usually the linters are very aggressive, and I am surprised that it did not shout when a class was not [`UpperCamelCase`](https://en.wikipedia.org/wiki/Camel_case).

**Comment by geetu040** [comment]
> We need to check with @benHeid first whether he is ok with this renaming.

yes sure, we'll wait

> `pre-commit` did not pick up the name.

Also I found that in documentation `CINNForecaster` was used instead of `cINNForecaster`

**Comment by benHeid** [comment]
Mhm. I would prefer to stay with the current style since the acronym cINN stands for conditional Invertible Neural Network and is mostly written cINN. However, I have no strong opinion towards this. Thus, if you prefer a renaming I wouldn't block it.

**Comment by fkiraly** [comment]
Well, we would be in violation of PEP 8 and the punishment is Guido von Rossum visiting us in our nightmares:
https://peps.python.org/pep-0008/#class-names

I therefore strongly prefer `UpperCamelCase`. We can use the original capitalization in the docstring, for recognizability?

(we've merged the estimator already and the opposition period has elapsed, so if you feel strongly enough that it should stay so, that's how it stays, and also I will not mind)

**Comment by benHeid** [comment]
Ok then let's rename

**Comment by fkiraly** [comment]
⌚ 0.29.0
