### ISSUE TITLE
[ENH]: Enhanced Demo Loading with Classification Experiment Integration.

### ISSUE THREAD

**Issue by imSanko** [sktime/sktime#6129]
**Describe the solution you'd like**
The problem is to create a function, `demo_loading`, that demonstrates the loading of datasets for univariate and multivariate problems. The function should iterate over a list of datasets, load each dataset, and then print the shapes of the training and testing data. Additionally, the code includes logic to handle command-line arguments for running a classification.

**Describe alternatives you've considered**
The alternative could be to separate the dataset loading and the classification experiment into two separate functions. This would make the code more modular and easier to understand. Another alternative could be to use a configuration file or environment variables to specify the parameters for the classification experiment, instead of relying on command-line arguments.

**Additional context**
 The `demo_loading` function to include running a classification experiment with the loaded datasets. The provided code already includes the logic to handle command-line arguments for running the classification experiment, which is a good approach for flexibility and automation.

**Comment by fkiraly** [comment]
This issue is setting off detectors which think the entire text is most likely AI generated.

Closing hence - please do not submit AI generated issues.

Please let us know if you think this is a mistake.
