### ISSUE TITLE
[DOC] [BUG] Different directory structures between examples and docs/source/examples

### ISSUE THREAD

**Issue by duydl** [sktime/sktime#6148]
#### Describe the issue linked to the documentation

Properly related to #3246. Mention in #6128. 

As discussed in some other threads before, each notebook in examples is manually linked to docs/source/examples with a different folder structure. Below the full list of notebooks that are added to examples but not linked, found with a script: 
 
03_transformers.ipynb
Overview_of_sktime_functionalities_for_forecasting.ipynb
mlflow.ipynb
03b_forecasting_transformers_pipelines_tuning.ipynb
02c_classification_multivariate_inceptiontime.ipynb
00_sktime_intro.ipynb
03a_transformers_cheat_sheet.ipynb
04_benchmarking_v2.ipynb
02b_classification_multivariate_lstmfcn.ipynb 

In addition, because some notebook have image references from examples/img. After being linked they could no longer find the images i.e https://www.sktime.net/en/stable/examples/annotation/segmentation_with_clasp.html in the second section. 

#### Suggest a potential alternative/fix

Refractor root/examples and add a function in either pre-commit or conf.py to link the whole folder to docs.

**Comment by fkiraly** [comment]
That would be great! I've been wondering why not all of the notebooks are displayed!
