### ISSUE TITLE
[DOC] Missing #contributors Channel Mentioned in Developer Guide

### ISSUE THREAD

**Issue by shankariraja** [sktime/sktime#6162]
In the SKtime documentation, specifically the developer guide document, it instructs new developers to sign up for the developer Discord and say hello in the #contributors channel. However, upon checking the Discord server, there is no #contributors channel available.

This discrepancy might confuse new contributors who are trying to engage with the community and seek assistance. To improve the onboarding experience for developers, I suggest  updating the documentation to reflect the correct channel name or procedure for new contributors to introduce themselves.

<img width="549" alt="Screenshot 2024-03-18 220555" src="https://github.com/sktime/sktime/assets/125146652/b794437d-952d-4cb8-86b3-c0b33183ada1">

**Comment by fkiraly** [comment]
yes, this is pointing to the wrong channel.

General welcome/hello is `#lobby`, other relevant channels for are `#help-desk` (usage, how-to) and `#dev-chat` (new contributors, development/maintenance)
