### ISSUE TITLE
[BUG] Unusual if statement in _lower_bounding_numba.py

### ISSUE THREAD

**Issue by albertoazzari** [sktime/sktime#6166]
**Describe the bug**
 If statement with same code in both branches

**To Reproduce**
 See def create_shape_on_matrix, specifically lines 63-68 

**Expected behavior**
 In the else statement, I would expect ceil and floor to be exchanged

**Versions**
0.27.0

System:
    python: 3.12.0 (v3.12.0:0fb18b02c8, Oct  2 2023, 09:45:56) [Clang 13.0.0 (clang-1300.0.29.30)]
executable: /path
   machine: macOS-14.4-arm64-arm-64bit

Python dependencies:
          pip: 24.0
       sktime: 0.27.0
      sklearn: 1.4.1.post1
       skbase: 0.7.5
        numpy: 1.26.4
        scipy: 1.12.0
       pandas: 2.1.4
   matplotlib: 3.8.3
       joblib: 1.3.2
        numba: 0.59.0
  statsmodels: None
     pmdarima: None
statsforecast: None
      tsfresh: None
      tslearn: None
        torch: None
   tensorflow: None
tensorflow_probability: None
Backend MacOSX is interactive backend. Turning interactive mode on.

</details>

**Comment by fkiraly** [comment]
Thanks for reporting, @albertoazzari!

What I can easily verify is that the if/else statement in its current form is redundant, so there is a bug.

What I don't get - and I also have to say, I do no fully understand the specification of the function (the docstring is incomplete), why floor/ceil should be switched after the halfway point. Explanation would be appreciated.

Also, feel free to open a PR - if you do that, improvement of the docstring would also be appreciated, e.g., saying in math or more precisely what this function is doing to the bounding matrix.

**Comment by albertoazzari** [comment]
Thanks @fkiraly for the quick answer, my claim for the else branch is somewhat a speculation.  In the last few days, I read the paper for the sakoe-chiba band (see https://ieeexplore.ieee.org/document/1163055) and I did not find any clarification about the change after the halfway point. It could be useful maybe try to understand how different implementations handle or do not handle this problem.

**Comment by fkiraly** [comment]
Now this may be just me, but I don't see any indication in the Sakoe/Chiba paper that would even hint at doing the case distinction.

We could simply remove if/else and replace it by one of the identical branches, that also wouldn't change the logic.

**Comment by albertoazzari** [comment]
I agree.

**Comment by fkiraly** [comment]
Why did you then say:

> In the else statement, I would expect ceil and floor to be exchanged 

Could you explain?

**Comment by fkiraly** [comment]
would you like to make the PR?
