### ISSUE TITLE
[BUG] `TemporianTransformer` fails on windows

### ISSUE THREAD

**Issue by fkiraly** [sktime/sktime#6169]
Currently, `TemporianTransformer` fails on windows.

This is due to a known bug in `temporian`, see #5956.

Opening this issue to track.

**Comment by ianspektor** [comment]
Tagging @javiber @achoum who will be taking care of fixing the bug in Temporian and removing the restriction here

**Comment by fkiraly** [comment]
fixed through `temporian` update
