### ISSUE TITLE
[BUG] Imputer imputes too many pd-multiindex missing values

### ISSUE THREAD

**Issue by Ram0nB** [sktime/sktime#6224]
**Describe the bug**

The Imputer supports the "ffill" and "bfill" methods. The documentation states that only one of these methods will be applied when choosing one, but this is not the case.

Moreover, when imputing pd-multiindex data, the "ffill" after the "bfill" (and vice versa) will be done on global level rather than instance level.

**To Reproduce**

```python
import numpy as np
from sktime.datatypes import get_examples
from sktime.transformations.series.impute import Imputer

df = get_examples(mtype="pd-multiindex")[0]
df.iloc[3:6,:] = np.nan

df_imp = Imputer(method="ffill").fit_transform(df)

print(df)
print(df_imp)
```

Which outputs:

```
                      var_0  var_1
instances timepoints              
0         0             1.0    4.0
          1             2.0    5.0
          2             3.0    6.0
1         0             NaN    NaN
          1             NaN    NaN
          2             NaN    NaN
2         0             1.0   42.0
          1             2.0    5.0
          2             3.0    6.0
                      var_0  var_1
instances timepoints              
0         0             1.0    4.0
          1             2.0    5.0
          2             3.0    6.0
1         0             1.0   42.0
          1             1.0   42.0
          2             1.0   42.0
2         0             1.0   42.0
          1             2.0    5.0
          2             3.0    6.0
```

**Expected behavior**

I expect the missing values not to be imputed since one instance is entirely missing.

**Additional context**

When looking at the following lines we can see the issue
https://github.com/sktime/sktime/blob/e0e66f1e847d1bed06fbea0a511b666eae8f895d/sktime/transformations/series/impute.py#L226-L272
- Only in the case of a multiindex, after "ffill" is applied to a grouped pandas dataframe on instance level, "bfill" will be applied to the entire dataframe.
- Only in the case of a multiindex, after "bfill" is applied to a grouped pandas dataframe on instance level, "ffill" will be applied to the entire dataframe.

Suggested fix:
- To keep the imputation behavior only per instance level, line 239 and 243 should therefore also impute on the grouped dataframe.
- The documentation should state that ffill and bfill will be applied after every method.

**Versions**
<details>

System:
    python: 3.10.14 | packaged by Anaconda, Inc. | (main, Mar 21 2024, 16:20:14) [MSC v.1916 64 bit (AMD64)]
executable: [c:\Users\ramon.bussing\AppData\Local\anaconda3\envs\enerfore\python.exe](file:///C:/Users/Ram0nB/AppData/Local/anaconda3/envs/enerfore/python.exe)
   machine: Windows-10-10.0.22621-SP0

Python dependencies:
          pip: 23.3.1
       sktime: 0.27.1
      sklearn: 1.4.1.post1
       skbase: 0.7.5
        numpy: 1.26.4
        scipy: 1.12.0
       pandas: 2.1.4
   matplotlib: None
       joblib: 1.3.2
        numba: None
  statsmodels: 0.14.1
     pmdarima: 2.0.4
statsforecast: None
      tsfresh: None
      tslearn: None
        torch: None
   tensorflow: None
tensorflow_probability: None
</details>

**Comment by fkiraly** [comment]
Ah, indeed! So you'd need to group it again before the `bfill`, right?

Would you like to open a PR with a fix? Seems like the correct diagnosis already!

**Comment by Ram0nB** [comment]
> Ah, indeed! So you'd need to group it again before the `bfill`, right?
> 
> Would you like to open a PR with a fix? Seems like the correct diagnosis already!

Exactly! I'm happy to do so, I'll pick it up tomorrow.

**Comment by fkiraly** [comment]
Excellent.

Regarding the doc/logic mismatch, the standard way to address this is to change the doc, not the logic - to avoid to break currently working code.

**Comment by cedricdonie** [comment]
As a side-note, I'm not sure whether this is the best way to check for presence of a MultiIndex.
https://github.com/sktime/sktime/blob/e0e66f1e847d1bed06fbea0a511b666eae8f895d/sktime/transformations/series/impute.py#L180
https://github.com/sktime/sktime/blob/e0e66f1e847d1bed06fbea0a511b666eae8f895d/sktime/transformations/series/impute.py#L233

Sometimes, `isinstance` can be really slow. Checking that `index.nlevels > 1` might be more performant and also cover cases where a 1-level MultiIndex is included.

Just putting the thought out there in case the resulting PR touches this code... But maybe worth opening a new issue for?

https://stackoverflow.com/questions/21081042/detect-whether-a-dataframe-has-a-multiindex
