### ISSUE TITLE
[BUG] `unequal_length` clusterer bugs out in unequal data set

### ISSUE THREAD

**Issue by ggjx22** [sktime/sktime#6276]
**Describe the bug**
`TimeSeriesKMeansTslearn` is a clusterer which is able to be fitted with unequal length of time series within a data set (according to tags). But it does not seems to be doing what is it suppose to do. Possible bug/wrong usage/missing preprocessing step?

**To Reproduce**
```python
from sktime.datasets import load_acsf1
from sktime.registry import all_estimators
from sktime.clustering.k_means._k_means_tslearn import TimeSeriesKMeansTslearn
RANDOM_STATE= 2
no_of_unknown_clusters = 5

# import data
X, _ = load_acsf1(return_type='pd-multiindex')

# remove last 10 rows from the last appliance to simulate unequal time series 
X_mod = X.iloc[:-10]

# instantiate clusterer which can handle unequal time series
# all_estimators('clusterer', as_dataframe=True, filter_tags={'capability:unequal_length': True})
unequal_clst = TimeSeriesKMeansTslearn(n_clusters=no_of_unknown_clusters, n_jobs=-1, random_state=RANDOM_STATE)

# fit the clusterer
unequal_clst.fit(X_mod) # error
```

```
---------------------------------------------------------------------------
ValueError                                Traceback (most recent call last)
Cell In[119], line 18
     15 unequal_clst = TimeSeriesKMeansTslearn(n_clusters=no_of_unknown_clusters, n_jobs=-1, random_state=RANDOM_STATE)
     17 # fit the clusterer
---> 18 unequal_clst.fit(X_mod)

File c:\Users\agpgago\data-science\forecast-wizard-test\venv\lib\site-packages\sktime\clustering\base.py:110, in BaseClusterer.fit(self, X, y)
    107 # reset estimator at the start of fit
    108 self.reset()
--> 110 X = self._check_clusterer_input(X)
    112 multithread = self.get_tag("capability:multithreading")
    113 if multithread:

File c:\Users\agpgago\data-science\forecast-wizard-test\venv\lib\site-packages\sktime\clustering\base.py:422, in BaseClusterer._check_clusterer_input(self, X, enforce_min_instances)
    420 unequal = not X_metadata["is_equal_length"]
    421 self._check_capabilities(missing, multivariate, unequal)
--> 422 return convert_to(
    423     X,
    424     to_type=self.get_tag("X_inner_mtype"),
    425     as_scitype="Panel",
    426 )

File c:\Users\agpgago\data-science\forecast-wizard-test\venv\lib\site-packages\sktime\datatypes\_convert.py:263, in convert_to(obj, to_type, as_scitype, store, store_behaviour, return_to_mtype)
    260 from_type = infer_mtype(obj=obj, as_scitype=as_scitype)
...
    610 X_values = X_coerced.values
--> 611 X_3d = X_values.reshape(n_instances, n_timepoints, n_columns).swapaxes(1, 2)
    613 return X_3d

ValueError: cannot reshape array of size 291990 into shape (200,1460,1)
```

For the above to work, I actually have to align the time period of all time series into the same range in order for the clusterer to work. Doesn't that defeat the purpose of having a clusterer that works for unequal length time series.
```python
from sktime.transformations.panel.padder import PaddingTransformer

clst_pipe = PaddingTransformer() * unequal_clst
clst_pipe.fit(X_mod) # no errors
```

**Expected behavior**
Fitted clusterer on multiple time series which are unequal in length

**Versions**
<details>

```bash
System:
    python: 3.10.9 | packaged by Anaconda, Inc. | (main, Mar  1 2023, 18:18:15) [MSC v.1916 64 bit (AMD64)]
executable: [c:\Users\agpgago\data-science\forecast-wizard-test\venv\Scripts\python.exe](file:///C:/Users/agpgago/data-science/forecast-wizard-test/venv/Scripts/python.exe)
   machine: Windows-10-10.0.19042-SP0

Python dependencies:
          pip: 23.3.2
       sktime: 0.28.0
      sklearn: 1.4.1.post1
       skbase: 0.7.2
        numpy: 1.26.4
        scipy: 1.12.0
       pandas: 2.1.4
   matplotlib: 3.8.3
       joblib: 1.3.2
        numba: 0.58.1
  statsmodels: 0.14.1
     pmdarima: 2.0.4
statsforecast: 1.7.3
      tsfresh: 0.20.2
      tslearn: 0.6.3
        torch: None
   tensorflow: 2.15.0
tensorflow_probability: None
```
</details>

**Comment by fkiraly** [comment]
Explanation why the tests did not catch this: there were no unequal length test scenarios for clustering, unlike for classificatoin. I'll fix that too.

**Comment by weenerplasticsgroup** [comment]
@fkiraly 
Bug does not seem fixed I have:
```python
from pydoc import locate
from sktime.registry import all_estimators
from sktime.datasets import load_acsf1

# create test data set
RANDOM_STATE= 2
no_of_unknown_clusters = 5
X, _ = load_acsf1(return_type='pd-multiindex')
# remove last 10 rows from the last appliance to simulate unequal time series 
X_mod = X.iloc[:-10]


for model in all_estimators(estimator_types="clusterer", filter_tags="capability:unequal_length"):
    sys.stdout = orig_stdout
    obj = model[1]
    unequal_clst = locate(".".join([obj.__module__, obj.__name__]))
    try:
        unequal_clst().fit(X=X_mod) 
        print(f"{obj.__name__} did not fail")
    except TypeError:
        print(f"{obj.__name__} failed on typeerror")
    except ValueError as e:
         print(f"{obj.__name__} failed on {e}")
```
This gives, eveything fails.
```bash
ClustererPipeline failed on typeerror
SklearnClustererPipeline failed on typeerror
TimeSeriesDBSCAN failed on typeerror
TimeSeriesKMeans failed on The data has unequal length series, this clusterer cannot handle unequal length series
TimeSeriesKMeansTslearn failed on The data has unequal length series, this clusterer cannot handle unequal length series
TimeSeriesKMedoids failed on The data has unequal length series, this clusterer cannot handle unequal length series
TimeSeriesKShapes failed on The data has unequal length series, this clusterer cannot handle unequal length series
TimeSeriesKernelKMeans failed on The data has unequal length series, this clusterer cannot handle unequal length series
TimeSeriesLloyds failed on typeerror
```

**Comment by jonathan-legrand** [comment]
Hello,
I have the same issue with DBSCAN and dtw distance. I am using sktime version 0.29.0 :
```python

import numpy as np
import pandas as pd
from sktime.datatypes import check_raise
from sktime.clustering.dbscan import TimeSeriesDBSCAN
from sktime.dists_kernels.compose_from_align import DistFromAligner
from sktime.alignment.dtw_numba import AlignerDtwNumba

# Generate synthetic data with unequal length
rng = np.random.default_rng()
N = 10
observations = []
index = []
for individual in range(N):
    n_observations = rng.integers(2, 16)
    for timepoint in range(n_observations):
        observation = rng.normal()
        observations.append(observation)
        index.append((individual, timepoint))

index = pd.MultiIndex.from_tuples(index, names=["individual", "timepoint"])
X = pd.DataFrame(observations, index=index, columns=["observations"])
check_raise(X, mtype="pd-multiindex")

# Fit clusterer
distance = DistFromAligner(AlignerDtwNumba())
clst = TimeSeriesDBSCAN(distance=distance, eps=0.5)
assert distance.get_tag('capability:unequal_length')
assert clst.get_tag('capability:unequal_length')

clst.fit(X)

```
This raises a ValueError : 
`ValueError: elements of obj must have same length and columns`

**Comment by fkiraly** [comment]
sorry, did not see the original message. Let me check whether the bug is still there.

**Comment by fkiraly** [comment]
> @fkiraly Bug does not seem fixed I have, note that it is linked to [sktime/skbase#327](https://github.com/sktime/skbase/issues/327)
> 
> ```python
> from pydoc import locate
> from sktime.registry import all_estimators
> from sktime.datasets import load_acsf1
> 
> # create test data set
> RANDOM_STATE= 2
> no_of_unknown_clusters = 5
> X, _ = load_acsf1(return_type='pd-multiindex')
> # remove last 10 rows from the last appliance to simulate unequal time series 
> X_mod = X.iloc[:-10]
> 
> 
> for model in all_estimators(estimator_types="clusterer", filter_tags="capability:unequal_length"):
>     sys.stdout = orig_stdout # fixes stdout bug
>     obj = model[1]
>     unequal_clst = locate(".".join([obj.__module__, obj.__name__]))
>     try:
>         unequal_clst().fit(X=X_mod) 
>         print(f"{obj.__name__} did not fail")
>     except TypeError:
>         print(f"{obj.__name__} failed on typeerror")
>     except ValueError as e:
>          print(f"{obj.__name__} failed on {e}")
> ```
> 
> This gives, eveything fails.
> 
> ```shell
> ClustererPipeline failed on typeerror
> SklearnClustererPipeline failed on typeerror
> TimeSeriesDBSCAN failed on typeerror
> TimeSeriesKMeans failed on The data has unequal length series, this clusterer cannot handle unequal length series
> TimeSeriesKMeansTslearn failed on The data has unequal length series, this clusterer cannot handle unequal length series
> TimeSeriesKMedoids failed on The data has unequal length series, this clusterer cannot handle unequal length series
> TimeSeriesKShapes failed on The data has unequal length series, this clusterer cannot handle unequal length series
> TimeSeriesKernelKMeans failed on The data has unequal length series, this clusterer cannot handle unequal length series
> TimeSeriesLloyds failed on typeerror
> ```

@weenerplasticsgroup, I think the above is not a bug, it is unintuitive behaviour of `all_estimators`. If you `filter_tags` by tag name, it returns all estimators that have the tag, no matter the value.

This is discussed here: https://github.com/sktime/skbase/issues/326 and will be changed in `skbase 0.9.0` so that your code works as expected.

**Comment by fkiraly** [comment]
@jonathan-legrand, I see, this is a valid bug, although a different one than the one in the original post.

The problem is, some alignment algorithms are not capable of dealing with unequal length data, that includes the `AlignerDtwNumba`. More generally, it will lead to confusing error messages and discrepant tags.

This should be addressed, by introducing a tag for alignment algorithms, and ensuring that an appropriate error message is being raised.

For your code, you could use as a workaround:

* the aligner from `dtw-python`, `AlignerDTW`, this can deal with unequal length data
* using one of the following dtw distances directly: `DtwPythonDist` (`dtw-python`), or `DtwDistTslearn` (`tslearn`) for the distance

**Comment by jonathan-legrand** [comment]
Indeed that fixed it for me, thank you very much!

**Comment by fkiraly** [comment]
Great to hear.

I've added some input checks to aligners - turns out they did not have any - in this PR: https://github.com/sktime/sktime/pull/6486

The "distance from aligner" compositor will now also copy the tag from the aligner, so the user feedback should be clear.

**Comment by ggjx22** [comment]
> Indeed that fixed it for me, thank you very much!

hello @jonathan-legrand I am also trying to use `TimeSeriesDBSCAN` to cluster my own dataset, do you mind sharing your solution that works for you? I was trying to replicate your code but getting `TypeError: 'AlignerDTW' object is not callable`. Pretty sure my implementation is wrong and I could not find any examples for this.

Here is my implementation:
```python
dist = AlignerDTW(dist_method=DtwPythonDist())
clst = TimeSeriesDBSCAN(distance=dist)
```

**Comment by jonathan-legrand** [comment]
Hello @ggjx22 ,
You don't need to use an aligner if you are using `DtwPythonDist`, you can directly pass it to the clusterer :
```python
clst = TimeSeriesDBSCAN(distance=DtwPythonDist())
```
Another possibility is to replace the `AlignerDtwNumba` by `AlignerDtw` in my code, but I think the first solution is simpler if you don't need to do anything special with the aligner.
