### ISSUE TITLE
[ENH] Composition forecaster that clusters time series and forecasts by cluster

### ISSUE THREAD

**Issue by ggjx22** [sktime/sktime#6279]
**Is your feature request related to a problem? Please describe.**
Currently, there is no feature which estimates (provides) indicators based on past behavior or trends of a time series data set. Visual inspection is required before deciding how to best choose the appropriate preprocessing and model in order to produce forecast, be in direct or recursive. 

**Describe the solution you'd like**
To have a feature which estimate the forecastability of a time series by labeling them as smooth, erratic, lumpy, intermediate, unclassified (or just integer based labels. Same as what the clusterers of `sktime` are providing now via `get_fitted_params`). There are already existing studies that shows can this can be implemented for demand forecasting. But this may lead to misclassification if data contains both positive and negative values (see calculation from links below). Maybe passing the data through a `MinMaxScaler` solves the issue, any thoughts?

- [Measurement of ADI and CV²](https://frepple.com/blog/demand-classification/)

Another website discussing measurement for forecastability:
- [Approximate Entropy and Sample Entropy](https://ming-zhao.github.io/Business-Analytics/html/docs/time_series/stationarity.html)

Finally base on the result this feature provides, the user decides whether and how to preprocess, aggregate multiple time series to increase forecastability, or model the data, etc.

**Comment by fkiraly** [comment]
I think this is a very interesting question how one would support this on a framework level, as it links clustering and forecasting!

Let's consider the following algorithm:

1. first, apply a clusterer to a panel of time series, sorting them into categories like lumpy, erratic, chewie, etc.
2. then, apply a different forecaster per category
3. possibly, on the above, tune which forecaster is appled on which category, or the parameters of the clusterer

To deal with this programmatically, I think we need:

* a compositor that allows to take a "grouping" from a clusterer or primitives transformer, and applies a forecaster by class/category, similar to `HierarchyEnsembleForecaster`
* possibly, polymorphism for clusterers that are capable of producing labels, to behave as to-primitives transformers
* the concrete estimator that @ggjx22 is suggesting, to categorize time series into different categories

The compositor, and the concrete estimator might be nicely defined contribution projects.

**Comment by ggjx22** [comment]
@fkiraly If you are suggesting an overall pipeline then it looks about right. What I hope the feature will give me are labels or scores that indicates forecastability, which in the case of the code above, comes from `TsCategorizer`. 

For example, the air passenger dataset has high forecastability, through some calculation a label or score is given. Whereas another label or low score for a dataset which does not have any historical seasonal/trend patterns that a model can extrapolate.

**Comment by fkiraly** [comment]
do you have any references or proposed estimators that could be implemented here? The design allows different clusterers or transformations to be passed as `grouper`.

**Comment by ggjx22** [comment]
Unfortunately no at this current moment

**Comment by marrov** [comment]
Oh this sounds very interesting! I've hacked my way around this same problem in the past (with ADI/CV2 for demand forecasting), albeit in a more ad hoc basis. Love the idea of supporting the workflow at a framework level. Maybe I could help out? Just subscribed to the issue. I think this would be a very nice addition to `sktime` as it also showcases the power of a complete framework for time series (i.e., being able to string together clustering with forecasting) is much more valuable than a library with just forecasting algorithms.

**Comment by fkiraly** [comment]
Nice, @marrov!

Would you like to give it a try?
I would start by inheriting from `BaseForecaster`, ignoring `_HeterogenousMetaEstimator` for the start, and going by the extension template.

I'd make the arguments a clusterer and a `dict` of forecasters.

The main alternative I see, is starting with a `_HeterogenousMetaEstimator` instead, and have a list of pairs instead of a `dict`. Perhaps that's better because closer to existing patterns?

Perhaps `HierarchyEnsembleForecaster` is the closest, to that.

**Comment by fkiraly** [comment]
FYI @VyomkeshVyas, because of `HierarchyEnsembleForecaster`

**Comment by galvangoh** [comment]
Hello @marrov or anyone with the relevant experience. Would like to seek your advices since you have worked with ADI/CV2 before. In cases where there could be negative demand, what will you do when calculating the CV? The positive and negative values will cancel out each other. If you take the absolute values of the time series, will it lead to misclassification?

For my case, I am trying to borrow this concept in demand forecasting for a quick and dirty approach to analysis time series in the financial space - accounts with positive and negative values represent credit/debit. Clustering as an analysis approach will make more sense here but I am currently running into unequal length issues.

**Comment by ggjx22** [comment]
Hello @marrov or anyone with the relevant experience. Would like to seek your advices since you have worked with ADI/CV2 before. In cases where there could be negative demand, what will you do when calculating the CV? The positive and negative values will cancel out each other. If you take the absolute values of the time series, will it lead to misclassification?

For my case, I am trying to borrow this concept in demand forecasting for a quick and dirty approach to analysis time series in the financial space - accounts with positive and negative values represent credit/debit. Clustering as an analysis approach will make more sense here but I am currently running into unequal length issues.

**Comment by fkiraly** [comment]
@ggjx22, may I ask what does "negative demand" mean in your case? If we talk about sales, the numbers are by definition positive, except if you take product returns or refunds into account (where a return ends up in a different time bin than the sale), but that´s more of an artefact than "genuine" negatives.

**Comment by ggjx22** [comment]
@fkiraly For my case, think of "negative demand" as transactional values being debited (incoming funds) or credited (outgoing funds) depending on the nature of the account. See sample plot attached.

![image](https://github.com/sktime/sktime/assets/134523967/83293204-19e3-4914-a5a5-a6e3658cd58d)

**Comment by fkiraly** [comment]
I see. adi/cov are summaries for event or count processes, and your data seems marked event, i.e., "transaction happens" plus "value of transaction"

I can think of a few options off the opt of my head:

* apply adi/cv to transaction count, that's an integer
* apply to absolute value
* use a measure of skew/kurtosis appropriate for distributions with mean close to zero, e.g., sample skew or kurtosis, or normalized variants

One question - would you like to contribute an adi/cv transformation to `sktime`? I don't think there's one available except through composition or generic `pandas`?

Also, out of interest: 2020 spike is probably covid, but what is 2016? US elections?

**Comment by fkiraly** [comment]
added issue with specification of a transformation: https://github.com/sktime/sktime/issues/6286

**Comment by ggjx22** [comment]
> One question - would you like to contribute an adi/cv transformation to `sktime`? I don't think there's one available except through composition or generic `pandas`?

I can try but I have no experience with open source contributions. Also it may take some time for me to warm up due to work commitments.

> Also, out of interest: 2020 spike is probably covid, but what is 2016? US elections?

Hmm, not sure about that, I wasn't with the company during then. I could ask but it would just be one of the many unique one-off occurrence. Could also be data quality issues. 

Aside to that, if an outlier exist during any of the cross validated folds backtesting, if treated (say, drop and interpolated), will that be introducing some form of bias training to the model? Assuming you do not know if those spikes will be happen again for the next x months (forecast horizon). I find this topic very subjective when discussing with people from the business, they would think the model training procedure is based off "fake" actual data.

**Comment by fkiraly** [comment]
> I wasn't with the company during then. I could ask but it would just be one of the many unique one-off occurrence

No worries, it's not necessary for any techincal discussion. I was just curious.

> Aside to that, if an outlier exist during any of the cross validated folds backtesting, if treated (say, drop and interpolated), will that be introducing some form of bias training to the model?

Many time series models assume stationarity or a similar type of "continuous regime" to function.

There is no way any model can deal with "black swan" events, i.e., unique, consequential changes to the system state that have not occurred before, except by flagging that they are occurring.

Imo the safest is to have a component that detects departure from previously observed data ranges, and using that as a recommender on how well the model can be trusted (or not).

**Comment by fkiraly** [comment]
No, I mean an algorithm subroutine. That is, you have an algorithm that forecasts, but it also has a warning routine that tells you when it believes forecasts are getting unreliable.

**Comment by shlok191** [comment]
@fkiraly, Can I work on this issue? Thank you!

**Comment by fkiraly** [comment]
Yes, absolutely! All yours!

@ggjx22, ADI-CV feature is implemented in #6336 and will be in the next release.
