### ISSUE TITLE
[BUG] Images are broken on https://www.sktime.net/en/stable/examples/forecasting/01c_forecasting_hierarchical_global.html

### ISSUE THREAD

**Issue by chrism2671** [sktime/sktime#6283]
**Describe the bug**
https://www.sktime.net/en/stable/examples/forecasting/01c_forecasting_hierarchical_global.html
<img width="1040" alt="image" src="https://github.com/sktime/sktime/assets/456541/d1b90f2d-a8f9-4f92-baab-e055ef48af2e">

**Comment by yarnabrina** [comment]
The image seems to load correctly here:

https://github.com/sktime/sktime/blob/main/examples/01c_forecasting_hierarchical_global.ipynb

If I remember correctly, @duydl was working on some notebook reorganization PR's, though they are not merged yet. Do you have any suggestions?

**Comment by duydl** [comment]
#6250 is meant to fix this. Though when addressing a review I accidentally revert a fix. Should work after a re-merge.

**Comment by yarnabrina** [comment]
@chrism2671 I've merged #6210 and hopefully this should be fixed on `main` branch now (corresponding to `latest`). Closing this issue for now, but please let us know if you face any more issues with this.
