### ISSUE TITLE
[BUG] Version 0.28.0 `conda` release, all extras dep set `sktime-all-extras`, does not install on windows due to broken `pycatch22` specification identifier

### ISSUE THREAD

**Issue by tm-slavik57** [sktime/sktime#6304]
**Describe the bug**
Seems like version 0.28.0 causes issues for conda
```
$ conda env update --file environment.yml 
Collecting package metadata (repodata.json): | WARNING conda.core.index:push_record(234): Skipping conda-forge/win-64::sktime-0.28.0-py310h5588dad_0 due to InvalidSpec: >=0.4,<0.4.4,
WARNING conda.core.index:push_record(234): Skipping conda-forge/win-64::sktime-0.28.0-py311h1ea47a8_0 due to InvalidSpec: >=0.4,<0.4.4,
WARNING conda.core.index:push_record(234): Skipping conda-forge/win-64::sktime-0.28.0-py38haa244fe_0 due to InvalidSpec: >=0.4,<0.4.4,
WARNING conda.core.index:push_record(234): Skipping conda-forge/win-64::sktime-0.28.0-py39hcbf5309_0 due to InvalidSpec: >=0.4,<0.4.4,
done
Solving environment: failed

InvalidVersionSpec: Invalid version '>=0.4,<0.4.4,': cannot join single expression
```

I've also opened an issue to conda about it because it seems like it's a conda issue: https://github.com/conda/conda/issues/13802

**To Reproduce**
1. Create a file called `environment.yml` with this content:
```
name: CondaInvalidSpecDebug
channels:
  - anaconda
  - conda-forge
  - pytorch

dependencies:
  - sktime=0.28.0
```

2. Run the following command:
```
conda env create --file environment.yml
```

** Extra context **
Seems like this line causes the issue: 
```
  "pycatch22>=0.4,<0.4.4",
```
https://github.com/sktime/sktime/blob/31dd08f10a942f9034a71c0bcf3bffc4e158cb57/pyproject.toml#L213C3-L213C27

**Comment by tm-slavik57** [comment]
It seems like the windows dependcies were uploaded with invalid spec for the `pycatch22`, it has an extra comma in the end:
```
('pykalman >=0.9.5', 'pmdarima >=1.8.0,!=1.8.1,<3.0.0', 'stumpy >=1.5.1', 'pycatch22 >=0.4,<0.4.4,', 'prophet >=1.1', 'scikit-posthocs >=0.6.5', 'filterpy >=1.4.5', 'pystan ==2.19.1.1', 'pyod >=0.8.0', 'statsmodels >=0.12.1', 'tbats >=1.1.0', 'hmmlearn >=0.2.7', 'numba >=0.53', 'tslearn >=0.5.2,<0.7.0', 'seaborn >=0.11.0', 'kotsu >=0.3.1', 'tsfresh >=0.17.0', 'gluonts >=0.9.0', 'esig ==0.9.7', 'statsforecast >=0.5.2,<1.8.0', 'matplotlib-base >=3.3.2')
```

Can you reupload it with fixed dependencies list?

**Comment by fkiraly** [comment]
I see, this is the "all extras" version, I presume?

FYI @benfulcher, @jmoo2880, who maintain the `pycatch22` package.

I believe this is a bug directly in that package and should be raised there?
https://github.com/DynamicsAndNeuralSystems/pycatch22

**Comment by fkiraly** [comment]
Fix opened here: https://github.com/conda-forge/sktime-feedstock/pull/118

**Comment by fkiraly** [comment]
I'm not that experienced with conda-forge - will this fix the issue with 0.28.0, or only from the next version onwards?

**Comment by fkiraly** [comment]
I also suppose it is unrelated to this?
https://github.com/sktime/sktime/pull/5670

FYI @yarnabrina

**Comment by fkiraly** [comment]
(perhaps off-topic, have we reported the incompatibility of 0.4.4 with windows directly with `pycatch22`?)

**Comment by tm-slavik57** [comment]
> I'm not that experienced with conda-forge - will this fix the issue with 0.28.0, or only from the next version onwards?

I'm not sure about it as well, but it seems like even when installing other versions and not 0.28.0 directly it prints the warnings. Seems like conda is loading all the possible versions for the dependencies resolution phase.

Perhaps the windows version 0.28.0 should be reuploaded or removed from conda-forge to avoid these warnings

**Comment by fkiraly** [comment]
How odd. It is also strange how all the checks passed - windows installs are explicitly being tested before each release, and need to pass.

**Comment by tm-slavik57** [comment]
@fkiraly 
you can see the specific configurations I have for conda in this bug report I opened for conda:
https://github.com/conda/conda/issues/13802

**Comment by fkiraly** [comment]
I think if there's relevance beyond `sktime` (i.e., not just maintainer error in creating the conda-forge recipe), it's more likely with `conda-forge` than `conda`, but this is just a guess.

I've pinged the `conda-forge` maintainers on the PR: https://github.com/conda-forge/sktime-feedstock/pull/118

**Comment by tm-slavik57** [comment]
> Fix opened here: [conda-forge/sktime-feedstock#118](https://github.com/conda-forge/sktime-feedstock/pull/118)

Will this PR replace the 0.28.0 version on conda-forge or does it require a new version?

**Comment by tm-slavik57** [comment]
@fkiraly 
Perpahs this should be considered to update the 0.28.0 metadata: https://conda-forge.org/docs/maintainer/updating_pkgs/#removing-broken-packages

**Comment by tm-slavik57** [comment]
A patch in this spirit can be added to this repo: https://github.com/conda-forge/conda-forge-repodata-patches-feedstock

Under `recipe/patch_yaml/sktime.yaml`
```
if:
  name: sktime
  version_in: ["0.28.0"]
  artifact_in: 
      - "sktime-0.28.0-py311h1ea47a8_0.conda"
      - "sktime-0.28.0-py38haa244fe_0.conda"
      - "sktime-0.28.0-py39hcbf5309_0.conda"
then:
  - replace_depends:
      old: pycatch22 >=0.4,<0.4.4,
      new: pycatch22 >=0.4,<0.4.4
```

More details can be found here: https://github.com/conda-forge/conda-forge-repodata-patches-feedstock/blob/main/recipe/README.md

**Comment by fkiraly** [comment]
hm, that's useful to know!

Would you like to open a PR, given that you have already investigated how to do this?

**Comment by tm-slavik57** [comment]
> hm, that's useful to know!
> 
> Would you like to open a PR, given that you have already investigated how to do this?

I can try, my first time doing this, hope not to brake things for you guys

**Comment by fkiraly** [comment]
>  hope not to brake things for you guys

No need to worry about that - it's anyway someone else merging.

**Comment by yarnabrina** [comment]
> I also suppose it is unrelated to this? #5670
> 
> FYI @yarnabrina

We faced issues with pip installs, so I think conda problems are unrelated.

A question to @tm-slavik57 : have you observed this only from 0.28, or for older releases as well?

**Comment by yarnabrina** [comment]
@tm-slavik57 I've merged the PR on feedstock, let's try in some time to see if that affects anything on windows.

Also it seems that line got specifically added in 0.28.0 as per git history, so older ones probably be okay.

@fkiraly do you know exactly what do the tests on conda forge PR perform? Are those tests or those just build sone artefacts? Sorry if it's a dumb question.

**Comment by fkiraly** [comment]
> @fkiraly do you know exactly what do the tests on conda forge PR perform? Are those tests or those just build sone artefacts? Sorry if it's a dumb question.

As per my understanding, this is specified in `meta.yml`, `test` directives:
https://conda-forge.org/docs/maintainer/adding_pkgs/#testing-python-packages

This means, currently we are testing that:

* the package installs successfully
* various modules can be imported without exception raised

Also, per my understanding, currently, no further tests are being run on `conda-forge`, but they are covered already in the main directory.

As minor improvements, we could run the minimal `nosoftdeps` test, or `pip check`.

**Comment by yarnabrina** [comment]
> How odd. It is also strange how all the checks passed - windows installs are explicitly being tested before each release, and need to pass.

I think your above link explains why import tests passed. The checks are only importing the top level components, but all our soft dependencies are isolated and never get called without instantiation of dependent estimators. So, `pycatch22` was never used during testing.

https://github.com/conda-forge/sktime-feedstock/blob/beaf1be952878c6541fbb107e17112ab51b4f31a/recipe/meta.yaml#L72-L88

**Comment by fkiraly** [comment]
I'm not sure whether this is a solid explanation, could you check my reasoning that it is not?

The failure occurs, according to @tm-slavik57, already at *environment setup*, at installation.

That is, even if the package is no being imported, if the failure occurs, it should be triggered when the CI tries to install all requirements.

**Comment by yarnabrina** [comment]
I understand what you mean, but unfortunately I'm not aware of the details of test process (for instance, 
how these are installed for testing etc.) so can't comment.

However, I'll note that it doesn't always fail during installation as per this, so the possibility is open (but not certain as you correctly pointed out).

Ref. https://github.com/conda/conda/issues/13802#issuecomment-2058964628

**Comment by fkiraly** [comment]
> Ref. https://github.com/conda/conda/issues/13802#issuecomment-2058964628

Yes, I saw that - but that is a valid (potential) explanation.

I do not think your proposed mechanism is an explanation, unless you postulate that imported packages are installed at runtime (which I'd doubt).

**Comment by tm-slavik57** [comment]
After https://github.com/conda-forge/conda-forge-repodata-patches-feedstock/pull/706 was merged, I checked and installing version 0.28.0 now works fine so I think this bug can now be closed.

**Comment by tm-slavik57** [comment]
> Thanks, @tm-slavik57!
> 
> Feel free to add yourself to the `sktime` contributors register (the `all-contributorsrc` file in the repo) with the `maintenance` badge!

😄 thanks but this is my work user so I'm not going to use this user forever

**Comment by fkiraly** [comment]
Feel free to add any usernames you'd like (as long as they are added by this acct)
