### ISSUE TITLE
[ENH] Bollinger bands

### ISSUE THREAD

**Issue by fkiraly** [sktime/sktime#6320]
I noticed `sktime` has some tools for smoothing, but not the popular Bollinger bands used in trading.

While one can be of different opinion on the estimator, I think it is popular enough to have it in the "smoothing" section.

It should be a good first issue, given the simple nature of the estimator it should be straightforward to implement from scratch, using `pandas` or `numpy` directly.
Some thoughts:

* the `q` of the moving average should be a parameter
* the `remember_data` tag should be true, since stream use will require to remember previous data for computing the bands. So, transform should try to retrieve remembered data, and subset it to the range required to comput bands for indices in the input.

**Comment by ishanpai** [comment]
Picking up this issue as my my first issue.
