### ISSUE TITLE
[ENH] extracting fitted parameters from `StatsForecastAutoARIMA`

### ISSUE THREAD

**Issue by jiayuanteng** [sktime/sktime#6342]
**Is your feature request related to a problem? Please describe.**

Hi, I notice that when I run StatsForecastAutoARIMA, I cannot get the estimated parameters. Is there a way for users to get the estimated parameters and model specification? 

When you run the code below, output is blank.

```python
from sktime.forecasting.statsforecast import StatsForecastAutoARIMA
from sktime.datasets import load_airline
 
y = load_airline()
stats_arima_sktime =  StatsForecastAutoARIMA(max_p = 2, max_q = 2, sp = 12)
stats_arima_sktime.fit_predict(y, fh = [1,2,3,4, 5])
 
stats_arima_sktime.get_fitted_params()

                                                                                                                                                     
```
![Screenshot 2024-04-26 at 12 42 01 PM](https://github.com/sktime/sktime/assets/27443463/484ba93c-767a-4377-abfd-66c7598e9174)

**Describe the solution you'd like**
If not available, is it possible to add the estimated parameters? Thank you!

**Comment by fkiraly** [comment]
Looks like a bug, as `get_fitted_params` is indeed the programmatic way to get these.

Can you kindly provide your `sktime` and other versions, via `show_versions`?

Also pinging @yarnabrina as the author of the `statsforecast` facing adapters.

**Comment by jiayuanteng** [comment]
Sure. sktime version is 0.26.0

**Comment by fkiraly** [comment]
I remember some updates and bugfixes to the `statsforecast` adapter since then - could you try on 0.28.0?

**Comment by yarnabrina** [comment]
It's not there, as I couldn't find a way to get best parameters through some public methods. This was requested earlier too, but don't have the issue number.

@jiayuanteng if you are familiar on how to extract these for all auto-* models of statsforecast, or just AutoARIMA, that'd be awesome to have that contribution.

**Comment by fkiraly** [comment]
Moved to feature request, then

**Comment by fkiraly** [comment]
superset of https://github.com/sktime/sktime/issues/5720, merging issues
