### ISSUE TITLE
[BUG] logic problem with new CI - coverage of `TestAllEstimators` and `TestAllObjects` incorrect

### ISSUE THREAD

**Issue by fkiraly** [sktime/sktime#6352]
I think there is a bug in the new CI. The coverage is not affected since "old CI" is still running.

The issue occurs when, say, a forecaster changes.

The new CI will then trigger tests in `sktime.forecasting`, but not in `sktime.tests` which contains `TestAllEstimator`.
So, we run the forecaster specific tests for the changed forecaster, but not the object and estimator specific tests.

FYI @yarnabrina, is there a way to fix this?
The "one liner" to "run all tests for estimator X" is `check_estimator` - however, this is intentionally avoided in the original setup as an entry point since this distributes less well across workers, via `pytest-xdist`.

**Comment by fkiraly** [comment]
The "opposite case" is where there are changes in "other" modules, as well as in a forecaster. The `TestAllEstimators` test for that forecaster then runs in the "other" test job, not in the "module/forecasters" bucket:
https://github.com/sktime/sktime/actions/runs/8861405811/job/24333294008?pr=6348

**Comment by yarnabrina** [comment]
I just commented in Discord as well, this job is not coming from "other" case in new CI. It's coming from old CI relying on the Makefile, specifically this line is being called to run the tests:

https://github.com/sktime/sktime/blob/3156135c0ecbe689782aa88fbb866c2019fbc934/.github/workflows/test.yml#L298

New CI jobs will have been called by this line instead:

https://github.com/sktime/sktime/blob/3156135c0ecbe689782aa88fbb866c2019fbc934/.github/workflows/test_other.yml#L66-L82

**Comment by fkiraly** [comment]
Sorry, wrong link:
https://github.com/sktime/sktime/actions/runs/8861405811/job/24334091449?pr=6348

This is coming from "other" in new CI, screenshot:
![image](https://github.com/sktime/sktime/assets/7985502/5c35646c-1b80-480e-9654-139896f985cd)

**Comment by fkiraly** [comment]
The solution could be, to run `tests` in all "module" tests, that will at least ensure that the estimator/object tests are run for changed forecasters.

We cannot turn them off in "other", as estimators may live in "other" modules. But that will trigger only if an "other" and a "module" estimator is changed in the same PR, so perhaps low incidence.

**Comment by yarnabrina** [comment]
I've created PR #6353, please take a look. But based on sample runs on my laptop, this is going to make new CI significantly slower, even the test collection part. For example, the times before and after the change for forecasting with just test collection (`--co` flag) is 21.85 seconds (43669 tests) vs 314.01 seconds (79603 tests).

**Comment by fkiraly** [comment]
Only test collection?

Before we merge then, can we diagnose where this is coming from?

**Comment by fkiraly** [comment]
I just checked construction times with the code below. It looks like construction is not the culprit, most likely.
Most estimators construct instantaneously, there are some which need 10s of milliseconds which is probably too long.

```python
from sktime.utils.validation._dependencies import _check_estimator_deps
from sktime.registry import all_estimators

ests = all_estimators(return_names=False)

def _measure_init_time(cls, params=None):
    from time import time

    start = time()
    try:
        cls(**params)
    except Exception:
        pass
    end = time()
    return end - start

times = []

for est in ests:
    if _check_estimator_deps(est, severity="none"):
        params = est.get_test_params()
        if not isinstance(params, list):
            params = [params]
        for param in params:
            times.append((est, _measure_init_time(est, param)))
```

**Comment by yarnabrina** [comment]
Just in case it's device or OS specific, what are the times for you for the above reported cases? I used these commands:

```python
# pre-PR
python -m pytest sktime/forecasting --co

# post-PR
python -m pytest sktime/forecasting sktime/tests --co
```

**Comment by yarnabrina** [comment]
> I just checked construction times with the code below. It looks like construction is not the culprit, most likely.
> Most estimators construct instantaneously, there are some which need 10s of milliseconds which is probably too long (but does not explain collection). It could of course be that I am missing something in a soft dependency I do not have installed.

I think construction or soft dependencies do not affect the above two commands I shared. I am not 100% confident though.

**Comment by fkiraly** [comment]
I ran the first commands on main, python 3.11, windows - I cancelled it after 10 minutes.

That is very odd.

**Comment by fkiraly** [comment]
what are your timings?

**Comment by fkiraly** [comment]
I think we are getting closer - I updated the issue https://github.com/sktime/sktime/issues/6344 with the problem description. I will now run a profiler on the test collection which takes too long.

**Comment by yarnabrina** [comment]
> For example, the times before and after the change for forecasting with just test collection (`--co` flag) is 21.85 seconds (43669 tests) vs 314.01 seconds (79603 tests).

These are my times. But I wonder why's mine so much faster than yours!!

Idea: I don't have pytest-xdist or other plugins installed so disabled those in configuration (setup.cfg). Can you try that once?

**Comment by yarnabrina** [comment]
> I also note how strange tihs is, because isn't 600s the stanard timeout for pytest collect?

Yes, it's configured in setup.cfg. My guess is it is for test execution, not for collection. Don't know how to check that.

**Comment by fkiraly** [comment]
That is very odd. 20 sec are more in line with the times from this older issue: https://github.com/sktime/sktime/issues/4900

**Comment by fkiraly** [comment]
should we move the test times discussion to here? https://github.com/sktime/sktime/issues/6344
