### ISSUE TITLE
[BUG] conversion to nested_univ is unexpected

### ISSUE THREAD

**Issue by weenerplasticsgroup** [sktime/sktime#6411]
**Describe the bug**
conversion to nested_univ is unexpected

**To Reproduce**
I start with this table
```python
from sktime.datatypes import get_examples
X = get_examples(mtype="pd-multiindex", as_scitype="Panel")[0]
X_trafo = X.reset_index(level=0, drop=True).rename(columns=dict(map(reversed, enumerate(X.columns)))).stack().to_frame().groupby(level=[0,1]).first()
X_trafo
```
<div>
<table border="1" class="dataframe">
  <thead>
    <tr style="text-align: right;">
      <th></th>
      <th></th>
      <th>0</th>
    </tr>
    <tr>
      <th>timepoints</th>
      <th></th>
      <th></th>
    </tr>
  </thead>
  <tbody>
    <tr>
      <th rowspan="2" valign="top">0</th>
      <th>0</th>
      <td>1</td>
    </tr>
    <tr>
      <th>1</th>
      <td>4</td>
    </tr>
    <tr>
      <th rowspan="2" valign="top">1</th>
      <th>0</th>
      <td>2</td>
    </tr>
    <tr>
      <th>1</th>
      <td>5</td>
    </tr>
    <tr>
      <th rowspan="2" valign="top">2</th>
      <th>0</th>
      <td>3</td>
    </tr>
    <tr>
      <th>1</th>
      <td>6</td>
    </tr>
  </tbody>
</table>
</div>
Now I convert to nested_univ

```python
from sktime.datatypes import convert_to
X_new = convert_to(X_trafo, "nested_univ")
X_new
```

<div>
<table border="1" class="dataframe">
  <thead>
    <tr style="text-align: right;">
      <th></th>
      <th>0</th>
    </tr>
    <tr>
      <th>timepoints</th>
      <th></th>
    </tr>
  </thead>
  <tbody>
    <tr>
      <th>0</th>
      <td>0    1
1    4
Name: 0, dtype: int64</td>
    </tr>
    <tr>
      <th>1</th>
      <td>0    2
1    5
Name: 0, dtype: int64</td>
    </tr>
    <tr>
      <th>2</th>
      <td>0    3
1    6
Name: 0, dtype: int64</td>
    </tr>
  </tbody>
</table>
</div>

**Expected behavior**
This is unexpected, I have  4 values where I expect two

I expect
Time 0  series 1 4
Time 1  series 2 5
etc.

**Additional context**

This example is very similar but does not give the unexpected result

```python
from sktime.datatypes import convert_to
from sktime.datasets import load_arrow_head
X, _ = load_arrow_head(return_X_y=True)
X_new = convert_to(X, to_type="pd-multiindex").swaplevel()
convert_to(X_new.sort_index(), to_type="nested_univ")
```

**Versions**
sktime 2.9

</details>

**Comment by fkiraly** [comment]
This is just how it prints out, there are actually only two values inside, in the `pd.Series` inside the cell.

It prints the index values, e.g., [0, 1] in the top left cell, next to the series values, e.g., [1, 4] in the top left cell.

PS, we do no longer recommend using the `nested_univ` specification, because `pandas 2` no longer supports the commands that would render manipulation of the container easy, and it is not in a supported `pandas` API.

**Comment by hstarmans** [comment]
I tested it with X.iloc[0].values and ended up with four, but will check again tomorrow

**Comment by fkiraly** [comment]
?? ok, let me run it. I was pretty sure it is just printing. Give me a sec.

**Comment by fkiraly** [comment]
Yes, it's just printing, e.g.,

```python
X_new.iloc[0, 0]
```
gives
```
0    1
1    4
Name: 0, dtype: int64
```

and
```python
X_new.iloc[0, 0].shape
```
is
```
(2,)
```

anyway, `nested_univ` is dodgy anyway, not just in printing, I recommend not using it.

**Comment by weenerplasticsgroup** [comment]
ok. there is no issue
