### ISSUE TITLE
[BUG] Performance Metric: multilevel="raw_values" with either multioutput="uniform_average" or custom weights for multioutput

### ISSUE THREAD

**Issue by kdekker-private** [sktime/sktime#6413]
**Describe the bug**
Performance metric classes do not work when using the combination multilevel="raw_values" with either multioutput="uniform_average" or custom weights for multioutput.

**To Reproduce**

Using MeanAbsoluteError, but the error does not remain to this class.

```python
import numpy as np
from sktime.performance_metrics.forecasting import MeanAbsoluteError
y_true = np.array([[0.5, 1], [-1, 1], [7, -6]])
y_pred = np.array([[0, 2], [-1, 2], [8, -5]])
mae = MeanAbsoluteError(multilevel="raw_values", multioutput="uniform_average")
mae(y_true, y_pred)
mae_custom_multitoutput_weights = MeanAbsoluteError(multilevel="raw_values", multioutput=[0.4,0.6])
mae_custom_multitoutput_weights(y_true, y_pred)
```

Output: 

ValueError: DataFrame constructor not properly called!

**Expected behavior**
Both the output of mae and mae_custom_multitoutput_weights with custom multioutput weights should not throw an error.

**Additional context**
It seems like the wrapper class around the inner metric function fails to coerse the evaluations in the expected output format.

**Versions**
0.28.0

**Comment by fkiraly** [comment]
confirmed on current `main`, windows, python 3.11.

Note to devs: we need to check why this combination of inputs is not tested.

**Comment by fkiraly** [comment]
I am noting that the data in question has no hierarchy levels, as it is a "plain" series data container.

Still, the metric should not crash, so the coercion should be fixed.
