### ISSUE TITLE
[BUG] `CNNClassifier` and `CNNRegressor` do not accept `filter_sizes` argument listed in docstring

### ISSUE THREAD

**Issue by narimanabdi** [sktime/sktime#6436]
**init method  parameter error**

In the CNNRegressor class, according to its docstring, there is a parameter termed "filter_sizes" to change the size of CNN filters. but when we want to initialize an object from this class with this parameter, the "unexpected keyword argument" error for __init__() method will be raised.

**Comment by fkiraly** [comment]
This is indeed a bug, it should be passed on.

**Comment by fkiraly** [comment]
Fix here: https://github.com/sktime/sktime/pull/6452
