### ISSUE TITLE
[MNT] keras/transformers installation error on python 3.8-3.11 in CI

### ISSUE THREAD

**Issue by fkiraly** [sktime/sktime#6445]
It seems that `keras` and `transformers` have some incompatibiliy and fail with installation on 3.11 CI and lower.

Example: https://github.com/sktime/sktime/actions/runs/9134142708/job/25119213085?pr=6442

I suppose it has to do with a recent release?

FYI @benHeid

**Comment by benHeid** [comment]
Transformers is not supporting Keras 3. It seems that a new check was added in the transformers version that was released yesterday.

However, I am bit confused why Keras is installed if transformers is installed even if there is a version specified. 

For now, I would propose to pin the version of transformers to < 4.41.0

**Comment by fkiraly** [comment]
> For now, I would propose to pin the version of transformers to < 4.41.0

ok - PR?
