### ISSUE TITLE
[BUG] In clustering averaging_method = 'dba' crashed

### ISSUE THREAD

**Issue by jacktang** [sktime/sktime#6469]
**Describe the bug**

In clustering example, the `averaging_method` set to `dba`, the program is crashed.

**To Reproduce**

```python
k_means = TimeSeriesKMeans(
    n_clusters=6,  # Number of desired centers
    init_algorithm="forgy",  # Center initialisation technique
    max_iter=10,  # Maximum number of iterations for refinement on training set
    metric="euclidean",  
    averaging_method="dba",  # Averaging technique to use
    random_state=1,
)
```

**Expected behavior**

**Additional context**

**Versions**
<details>

</details>

**Comment by fkiraly** [comment]
Thanks for reporting. Could you add imports and some dummy data so we can easily reproduce the issue?

**Comment by jacktang** [comment]
It is weird that I can't reproduce it any more :(, I will reopen it if I can reproduce the bug.
