### ISSUE TITLE
[ENH] categorical feature support: input checking - column type encoding by the `__dataframe__` protocol

### ISSUE THREAD

**Issue by fkiraly** [sktime/sktime#6470]
Thinking about apsects of the design for categorical feature support (umbrella issue: https://github.com/sktime/sktime/issues/6109), I realized that we need to have access to the information "which columns are categorical". Given how we adapt multiple data container formats (mtypes), and support planned in future for, e.g., `polars`, we should have a central interface point where we can query this.

My suggestion, to avoid lots of case distinctions at the consumption points, is creation of a central interface point at input checking time, using the `datatypes` checkers:

* the `check` fields for `Series`, `Panel`, `Hierarchical` mtypes are extended by a `feature_kind` field, this is a tuple of `__dataframe__` `DtypeKind` enum values (e.g., `DtypeKind.CATEGORICAL` etc). Reference: https://data-apis.org/dataframe-protocol/latest/API.html
* in relevant estimators, on `fit` checks, this is written to self as `feature_kind_in_`, similar to `feature_names_in_`
* a check for "has categorical features?" can then be performed by checking whether `DtypeKind.CATEGORICAL` is in the `feature_kind_in_`.

FYI @Abhay-Lejith, @pranavvp16, @yarnabrina.

I would also suggest some communication between @Abhay-Lejith and @pranavvp16  - @Abhay-Lejith is focusing on categorical feature support, while @pranavvp16 is currently diving into the `datatypes` module and is probably the one with the freshest working knowledge of it.

**Comment by Abhay-Lejith** [comment]
So I've been working on the `feature_kind` field in series datatype checks.
One issue is with `2D numpy` arrays. The dtype attribute only contains the dtype which can hold all values in the array. i.e there is no differentiating by column. 

One possible solution is to check the dtype of the first value of each column and store that in `feature_kind`. But this would assume that the rest of the column has the same dtype. Ideally that should be the case but in case it might not be, are there any already existing checks to see if all values in a column have the same dtype?

@fkiraly @yarnabrina  Any other ideas?

**Comment by Abhay-Lejith** [comment]
One more clarification, in `feature_kind`, are we just storing the dtypes as `float64` ,  `int32` etc or are we trying to do it like above with the `DtypeKind` enum values ?

**Comment by fkiraly** [comment]
> So I've been working on the `feature_kind` field in series datatype checks. One issue is with `2D numpy` arrays. The dtype attribute only contains the dtype which can hold all values in the array. i.e there is no differentiating by column.

> @fkiraly @yarnabrina Any other ideas?

Yes, I think in the numpy case you automatically always have float type, if it passes the `sktime` checks, i.e., `FLOAT` (2). This is somewhat boring for that datatype, as it cannot represent categorical, but we should still return a vector of `FLOAT` for consistency.

> One more clarification, in `feature_kind`, are we just storing the dtypes as `float64` ,  `int32` etc or are we trying to do it like above with the `DtypeKind` enum values ?

It should be the `DtypeKind` enum values, that's the exchange standard.
