### ISSUE TITLE
[BUG] `TimeSeriesForestRegressor` failure - Parameter `self.criterion`  does not exist in `TimeSeriesForestRegressor`

### ISSUE THREAD

**Issue by ksharma6** [sktime/sktime#6472]
**Describe the bug**
When using the `TimeSeriesForestRegressor` as a test case for a Time Series Regression GridSearchCV implementation (see https://github.com/sktime/sktime/pull/6118) , the following error occured when testing PR against test suite :

`AttributeError: 'TimeSeriesForestRegressor' object has no attribute 'criterion'`

**To Reproduce**
When testing against `test-nosoftdeps`, Time Series Regression GridSearchCV implementation failed 1 test and triggered the attribute error.

Implementation can be found below:
https://gist.github.com/ksharma6/a34eecb4d0f5ed5fcf43ffd464be4fa8

**Expected behavior**
Expected TSRGridSearchCV implemetation to pass test suite.

**Additional context**
`TimeSeriesForestRegressor` inherits its base class from `sklearn` and there may have been a recent change to said base class trigerring this error. A potential solution may be to implement `TimeSeriesForestRegressor`  natively, using sktime's base regressor.

Please run the following code snippet and paste the output here:
![bug report](https://github.com/sktime/sktime/assets/142558351/83798088-a25b-4efc-a2c0-46bcf56ba13b)

**Comment by fkiraly** [comment]
There might be a temporary fix for this, I think we've seen this in `TimeSeriesForestClassifier`: writing `self.criterion` in `__init__`.

What worries me a bit is that we did not pick this up in the tests. Should the regressor not break on its own, when we run `check_estimator` on it?
