### ISSUE TITLE
[BUG] Differencer is producing `SettingWithCopyWarning`

### ISSUE THREAD

**Issue by benHeid** [sktime/sktime#6480]
**Describe the bug**
The differencer is producing `SettingWithCopyWarning` when embedded in a ForecastingPipeline on which predict_interval/quantile is called... Which is a bit annoying, especially if the difference is part of a benchmarking pipeline. Since this is producing a lot of warnings in the terminal.

**To Reproduce**

```python
from sktime.datasets import load_airline
from sktime.transformations.series.difference import Differencer
from sktime.transformations.series.detrend import Deseasonalizer
from sktime.forecasting.naive import NaiveForecaster

y = load_airline()
forecaster = Differencer() * Deseasonalizer() * NaiveForecaster()
forecaster.fit(y)
forecaster.predict_interval(fh=range(12))
```

**Expected behavior**
No warning

**Additional context**
The error is raised by the Differencer and I suppose in the inverse call. Trying to replicate it without a forecaster leads to an error. But shows the error message too:

```python
from sktime.datasets import load_airline
from sktime.transformations.series.difference import Differencer
y = load_airline()
diff = Differencer().fit(y.to_frame()[:100])
y2 = pd.concat([y,y], keys=["T1", "T2"], axis=1)
y2.columns = pd.MultiIndex.from_arrays([["Number of airline passengers", "Number of airline passengers"], ["T1", "T1"], ["Lower", "Upper"]])
diff.inverse_transform(y2[102:])
```

´´

**Comment by fkiraly** [comment]
do you know which line exactly is causing this?

**Comment by benHeid** [comment]
difference.py line 159

**Comment by fkiraly** [comment]
commit history blames you...

It may be solved by decluttering the assignment?
General rule, if you have indentations without loops or conditionals, that's a code smell and suggests simplification, e.g., splitting into multiple assignments.

I would split things up into three assigned variables, and then see whether this persists?
