### ISSUE TITLE
[BUG] `ForecastingHorizon` `M` and `Y` `freq` incompatibility with `pandas >=2.2.0`

### ISSUE THREAD

**Issue by eccabay** [sktime/sktime#6499]
**Describe the bug**
For frequencies `2M`, `1Y`, and `2Y`, both `AutoARIMA.predict()` and `VARMAX.predict()` error claiming the frequency is invalid. 

**To Reproduce**
```python
import numpy as np
import pandas as pd
from sktime.forecasting.arima import AutoARIMA
from sktime.forecasting.base import ForecastingHorizon

datetime_ = pd.date_range("1/1/1870", periods=20, freq="2Y")

X = pd.DataFrame(range(20), index=datetime_)
y = pd.Series(np.sin(np.linspace(-8 * np.pi, 8 * np.pi, 20)), index=datetime_)

fh_ = ForecastingHorizon([i + 1 for i in range(len(y[15:]))], is_relative=True)

a_clf = AutoARIMA(maxiter=10)
clf = a_clf.fit(X=X[:15], y=y[:15])
clf.predict(fh=fh_, X=X[15:])
```

**Versions**
pandas >= 2.2.0
sktime >= 0.28.1

**Comment by fkiraly** [comment]
The frequencies that appear here in the chain when converting to and back:

* `2Y` converts to `2YE-DEC`. When attenpting `to_period(`2YE-DEC`) in `to_absolute`, `_coerce_to_period`, `pandas` complains that it wants `2YE-DEC`, in failure 1.
* if we fix that, failure 2 occurs - in the conversion back `to_relative`, we get `YS-JAN is not supported as period frequency`

WHY, `pandas`, WHY

**Comment by fkiraly** [comment]
Fix for failure 1, but currently unclear how we should address failure 2: https://github.com/sktime/sktime/pull/6500

**Comment by fkiraly** [comment]
What would help a lot, @eccabay, @yarnabrina and @sktime/core-developers, is a working example where we convert the above `datetime_` into a `pd.PeriodIndex`, add  `[1, 2, 3]` to the last index to obtain the next three horizon timetstamps, and convert back into a `pd.DatetimeIndex`.

I seem to be unable to write this code even outside the `ForecastingHorizon` - at least from `pandas 2.2.0` onwards...

**Comment by fkiraly** [comment]
failures confirmed on windows, python 3.11, current `main`. Condition is indeed `pandas >= 2.2.0`

**Comment by fkiraly** [comment]
EVIL

```python
import pandas as pd

d = pd.date_range("1/1/1870", periods=20, freq="Y")

d_period = d.to_period()
print(d_period.freq)  # Y-DEC

d_timestamp_again = d_period.to_timestamp()
print(d_timestamp_again.freq)  # YS-JAN
```

**Comment by fkiraly** [comment]
This code works on `<2.2.0` but fails on `>=2.2.0`

<2.2.0

```python
import pandas as pd

d = pd.date_range("1/1/1870", periods=20, freq="Y")

d_period = d.to_period(freq="Y")
print(d_period.freq)  # <YearEnd: month=12>

d_timestamp_again = d_period.to_timestamp(freq="Y")
print(d_timestamp_again.freq)  # <YearEnd: month=12>
```

**Comment by fkiraly** [comment]
warning-free code on `pandas 2.2.2`:

```python
import pandas as pd

d = pd.date_range("1/1/1870", periods=20, freq="YE")

d_period = d.to_period(freq="Y")
print(d_period.freq)  # <YearEnd: month=12>

d_timestamp_again = d_period.to_timestamp(freq="Y")
print(d_timestamp_again.freq)  # <YearEnd: month=12>
```

Why does the last statement have to be `"Y"`? Breaks with `"YE"`

**Comment by fkiraly** [comment]
I found a way to perhaps sidestep the issue: using `freq` objects instead of strings.

The strings have become inconsistent between timestamp/period case, but the objects are still consistent.

So, internally using the objects might be a way around this.

The MRE runs successfully with the fix https://github.com/sktime/sktime/pull/6500 - but I would not surprised if it breaks something else somewhere...
