### ISSUE TITLE
[BUG] `PyKanForecaster` `TypeError: 'NoneType' object is not subscriptable`

### ISSUE THREAD

**Issue by narencastellon** [sktime/sktime#6505]
**Describe the bug**

When I am using the `forecaster = PyKANForecaster()` and then I want to train my model it produces the following error see the image

`TypeError: 'NoneType' object is not subscriptable`

The `PyKANForecaster()` function does not have in its description the parameters that should be used, for example"

 grids: Any | None = None,
 model_params: Any | None = None,
 fit_params: Any | None = None,

It is not known how to use those parameters, what type of object should be included to include them.

**To Reproduce**

```
from sktime.forecasting.pykan_forecaster import PyKANForecaster
forecaster = PyKANForecaster()
forecaster.fit(y = df, fh = range(1, 24, 1) )
```

<img width="959" alt="Captura de pantalla 2024-05-31 a las 7 50 08 a  m" src="https://github.com/sktime/sktime/assets/71158095/36119f92-16c8-43a1-bd6c-17f34322b467">

**Comment by narencastellon** [comment]
Now, the error is resolved by adding the grid parameter,

```
forecaster = PyKANForecaster( grids= [5,5])
forecaster.fit(y = df, fh = range(1, 24, 1) )
forecaster.predict( )
```

but what is the grid parameter?
What values ​​does it carry? what type of value? what type of structure?
How could I add a good value to the grip to optimize and make the model more precise?

**Comment by fkiraly** [comment]
This is not yet released, right?

FYI @benHeid, we should fix this to avoid releasing with a bug, and add an empty param set in testing, too.

**Comment by fkiraly** [comment]
Fix here: https://github.com/sktime/sktime/pull/6506
