### ISSUE TITLE
[ENH] Enable parallel execution of ForecastingBenchmarks

### ISSUE THREAD

**Issue by benHeid** [sktime/sktime#6559]
**Is your feature request related to a problem? Please describe.**
Currently, in the ForecastingBenchmark each forecaster on each cv fold is evaluated separately. I would propose to enable options for parallel execution to fasten it up.

**Describe the solution you'd like**
When initializing the benchmarking, one can pass options for parallelization that are then provided to the `evaluate method`.

**Comment by Spinachboul** [comment]
I would want to work on this issue! 
@benHeid 
Could you tell me which method are we thinking to invoke parallelization 
I was thinking using `concurrent.features`

**Comment by fkiraly** [comment]
`sktime` supports multiple backends via `sktime.utils.parallel`.

I would suggest, let's try to wrap up your current PR before you take on this? The location for this would be anyway where you also add the progress bar.
