### ISSUE TITLE
[BUG] ValueError: <QuarterBegin: startingMonth=10> is not supported as period frequency

### ISSUE THREAD

**Issue by achoum** [sktime/sktime#6572]
**Describe the bug**

I am unsure if this is a bug or an issue in my code. I'm submitting this here following Franz's recommendation.

The `predict` function fails with the following error:

```
ValueError: <QuarterBegin: startingMonth=10> is not supported as period frequency
```

**To Reproduce**

```python
# Download tourism.csv from:
# https://www.kaggle.com/datasets/luisblanche/quarterly-tourism-in-australia

# Imports
import pandas as pd
from sktime.forecasting.naive import NaiveForecaster
from sktime.transformations.hierarchical.aggregate import Aggregator
from sktime.transformations.hierarchical.reconcile import Reconciler
from sktime.forecasting.base import ForecastingHorizon
from sktime.forecasting.arima import AutoARIMA
from sktime.forecasting.arima import ARIMA

# Load and prepare dataset
raw_ds = pd.read_csv("tourism.csv", parse_dates=["Quarter"])
raw_ds = raw_ds[raw_ds["State"] == "South Australia"] # Simplify
raw_ds = raw_ds[raw_ds["Purpose"] == "Visiting"] # Simplify
del raw_ds["State"]
del raw_ds["Unnamed: 0"]
del raw_ds["Purpose"]
raw_ds = raw_ds.set_index(["Region", "Quarter"]).sort_index()

# Fit and generate predictions with a HTS pipeline.
model = Aggregator() * ARIMA() * Reconciler(method="ols")
model.fit(raw_ds)

model.predict(fh=ForecastingHorizon( [0], is_relative=True))
```

The last line fails with the error:

```
ValueError: <QuarterBegin: startingMonth=10> is not supported as period frequency
```

Here is a notebook containing the code and execution logs: https://colab.research.google.com/drive/1XVbL9pUs3SVrwyiek3ejZFdBVmrddiES?usp=sharing

**Expected behavior**

`predict` returns predictions.

**Additional context**

- Using Pandas 2.2.2
- Bug possibly related to https://github.com/sktime/sktime/issues/6499
- The dataset contains datetime timestamps. Replacing them with integers solves the issue.

**Versions**

<details>
System:
    python: 3.11.8 (main, Feb  7 2024, 21:52:08) [GCC 13.2.0]
executable: /usr/local/google/home/gbm/my_venv/bin/python3
   machine: Linux-6.6.15-2rodete2-amd64-x86_64-with-glibc2.37

Python dependencies:
          pip: 23.3
       sktime: 0.30.1
      sklearn: 1.4.2
       skbase: 0.8.0
        numpy: 1.23.5
        scipy: 1.13.1
       pandas: 2.2.2
   matplotlib: 3.8.4
       joblib: 1.3.2
        numba: 0.59.1
  statsmodels: 0.14.2
     pmdarima: 2.0.4
statsforecast: 1.7.5
      tsfresh: None
      tslearn: None
        torch: 2.1.2+cu121
   tensorflow: 2.16.1
tensorflow_probability: None

</details>

**Comment by fkiraly** [comment]
Here is a simpler option to trigger the error, the cause is in `ForecastingHorizon.to_absolute`:

```python
from sktime.datasets import load_airline
from sktime.forecasting.base import ForecastingHorizon
from sktime.forecasting.naive import NaiveForecaster

y = load_airline()
y.index = y.index.to_timestamp()

forecaster = NaiveForecaster(strategy="last")
forecaster.fit(y, fh=fh)

fh = ForecastingHorizon([0], is_relative=True)
fh.to_absolute(forecaster.cutoff)
```

**Comment by fkiraly** [comment]
The deeper reason is, suppose we have a `pandas` index
`PeriodIndex(['1960-12'], dtype='period[M]')`, it cannot be converted to `<MonthBegin>` `freq` (anymore?) in `pandas`.

```python
from sktime.datasets import load_airline

y = load_airline()
y.index = y.index.to_timestamp()

import pandas as pd

ix = pd.PeriodIndex(["1960-12"], freq="M")
ix.to_timestamp(freq=y.index.freq)  # triggers the same error
```

This is very strange, since originally we have dealt with a `<MonthBegin>` index.

**Comment by fkiraly** [comment]
ok, I am starting to think, this is clearly a bug in `pandas`.
We already have a test that checks exactly this round trip, namely,

```python
def test_pandas22_freq(freq):
    """Test that to_absolute and to_relative conversions work with all freqs.

    Failure cas in bug #6499.
    """
    fh = ForecastingHorizon([1, 2, 3])

    datetime_ = pd.date_range("1/1/1870", periods=20, freq=freq)
    cutoff = datetime_[[-1]]
    cutoff.freq = datetime_.freq

    fh.to_absolute(cutoff)  # failure 1
    fh.to_absolute(cutoff).to_relative(cutoff)  # failure 2
```

Why it did not catch this: the `freq` looped only over `["Y", "2Y", "M", "3M", "YE", "2YE", "ME", "3ME"]`, but the error above occurs for `"MS"` (!).

There is no conceivable reason why this round trip should fail specifically for `"MS"`.

Knowing this, PR https://github.com/sktime/sktime/pull/6574 should patch over the failure while we we investigate further, I will raise a bug issue in `pandas`.

**Comment by fkiraly** [comment]
`pandas` issue raised here: https://github.com/pandas-dev/pandas/issues/58974

**Comment by fkiraly** [comment]
From the conversation in the `pandas` repo, indeed seems like a `pandas` bug.
