### ISSUE TITLE
[BUG] `sklearn.utils._param_validation.InvalidParameterError` thrown when using `max_iter` parameter in various regressors

### ISSUE THREAD

**Issue by julian-fong** [sktime/sktime#6582]
**Describe the bug**
```
sklearn.utils._param_validation.InvalidParameterError: The 'max_iter' parameter of BayesianRidge must be an int in the range [1, inf). Got None instead.
```
This error occurs when using the `max_iter` parameter in various regression methods. It seems like `None` is being set as the default and sklearn introduced a new validation to disallow `None` as a possible value

**To Reproduce**

To reproduce:
use the check_estimator functionality on a regressor. Note that this requires the latest version of scikit-learn
```
from skpro.regression.linear import BayesianRidge
from skpro.utils.estimator_checks import check_estimator

check_estimator(BayesianRidge)
```

**Versions**
<details>
Requires sklearn version 1.5

**Comment by julian-fong** [comment]
meant to create this on skpro whoops

**Comment by fkiraly** [comment]
> meant to create this on skpro whoops

Can be moved between repos of the org
