### ISSUE TITLE
[ENH] ensure pipelines between changepoint/anomaly annotators, transformers, and other estimators integrate seamlessly

### ISSUE THREAD

**Issue by fkiraly** [sktime/sktime#6591]
We should ensure that pipelines between annotators, transformers, and other estimators integrate seamlessly.

We should cover:

* concatenating annotation estimators with transformations
* concatenating them with other estimator types
* dunders

It is also a good question what should happen by default.

FYI @benHeid, @Alex-JG3, @hstarmans - what would be your expectation?

I think:

### transformation * annotator = annotator

`t * cpd`

fit: fits `t`, then transforms data via `t`, then fits `cpd` on the result; trafo/predict: transforms data via `t`, then applies `cpd` to the result

### annotator * anything else = same as transformation * anything else

`cpd * other`

fit: fits `cpd`, then transforms data via `cpd`, then fits `other` on the result; trafo/predict: transforms data via `cpd`, then applies `other` to the result

### annotator * annotator = annotator

`cpd1 * cpd2`

fit: fits `cpd1`, then transforms data via `cpd1`, then fits `cpd2` on the result; trafo/predict: transforms data via `cpd1`, then applies `cpd2` to the result

### summary

In all cases, the annotators behave like:

* transformers, via `transform`, if they are in any position except last
* annotators, if they are in the last position

## Implementation

* I think annotators should all have as a secondary scitype `transformer`
* we ensure that various pipelines accept annotators where they accept transformers
* for annotators, we need to add a pipeline that applies when the last element is an annotator
* the dunders need to be updated for correct dispatch

**Comment by Alex-JG3** [comment]
@fkiraly, these expectations make sense to me. One point of difficulty I see here is `BaseSeriesAnnotator`'s limited support for numpy arrays for `X` and `y`. The current methods for converting between `dense -> sparse`/`segments -> change points`/etc relie heavily on `X` and `y` being dataframes or series.

For this particular issue, do we need better defaults in `BaseSeriesAnnotator` for numpy arrays?

**Comment by hstarmans** [comment]
@fkiraly, I would also like the possibility to slice in the pipline..  differences I noted with sklearn;
   - slicing in pipeline seems easier in sklearn
   - accessing pipeline step by name or index 
   - image of pipeline looks better

**Comment by fkiraly** [comment]
Thx for the input. Slicing and image is understood.

Can you explain what you mean by "accessing pipeline step"? E.g., can you give a reference?

**Comment by hstarmans** [comment]
@fkiraly, apologies for late reply, below I give an example of accessing pipeline steps via its name

```python
from sklearn.pipeline import make_pipeline
from sklearn.cluster import KMeans
from sklearn.decomposition import PCA
from sklearn.preprocessing import StandardScaler
pipe = make_pipeline(StandardScaler(), PCA(2), KMeans(2))
```
You can access the named steps as follows
```python
pipe.named_steps['standardscaler']
```
Which allows
```python
import numpy as np
import pandas as pd
samples = 20
features = 3
base_dct = {"Time": range(samples), "Machine": [1]*samples}
for feat in range(features):
    base_dct[f'feat{feat}'] = np.random.randint(np.random.randint(3,10,size=1), size=samples)

X = pd.DataFrame(base_dct).set_index(['Machine', 'Time'])
pipe.fix(X)
pipe.named_steps['standardscaler'].transform(X)
```

**Comment by hstarmans** [comment]
@fkiraly, I would expect to end up with a pipeline type which would be similar to an ordered list or dictionary.
I think it it strange that the operation make_pipeline(transformer), I end up with a transformer.
I guess the following gives transformer, but would expect pipeline.

transformer * annotator * transformer
