### ISSUE TITLE
[ENH] Adding ForecastingOptunaSearchCV for hyper-parameter tuning for forecasting

### ISSUE THREAD

**Issue by gareth-brown-86** [sktime/sktime#6618]
Related: #4188

**Is your feature request related to a problem? Please describe.**
While sktime provides a ForecastingGridSearchCV, ForecastingRandomizedSearchCV and ForecastingSkoptSearchCV for grid search, there's a need for more sophisticated and efficient hyper-parameter optimization methods. The lack of integration with advanced optimization libraries like Optuna limits the ability to perform more complex and efficient hyper-parameter searches.

**Describe the solution you'd like**
I propose the addition of a ForecastingOptunaSearchCV class to sktime's forecasting module. This class would leverage Optuna for hyper-parameter optimization, providing a more efficient and flexible way to find the best parameters for forecasting models. The interface should be similar to the existing ForecastingGridSearchCV, allowing users to easily switch between grid search and Optuna-based optimization without significant changes to their code.

**Describe alternatives you've considered**
An alternative would be to manually integrate Optuna with sktime models outside of the sktime framework. While this works, this approach lacks the convenience and integration benefits of having a dedicated class within sktime. 

**Additional context**
One interface to optuna is the Ask-and-Tell Interface[](https://optuna.readthedocs.io/en/stable/tutorial/20_recipes/009_ask_and_tell.html#ask-and-tell-interface) which means you ask optuna for what parameters to use for a given trial, evaluate them, then provide optuna the results, eg in sudocode:
```python 
            trial = study.ask(self.param_grid)  # pass the pre-defined distributions.
            params = {name: trial.params[name] for name, v in self.param_grid.items()}
            forecaster.set_params(**params)
            out = evaluate(
                forecaster,
                cv,
                y,
                X,
                strategy=self.strategy,
                scoring=scoring,
                error_score=self.error_score,
            )
            out = out.filter(items=[scoring_name, "fit_time", "pred_time"], axis=1)
            out = out.mean().add_prefix("mean_")

            study.tell(trial, out[f"mean_{scoring_name}"])
```
The way to pass information of the parameters to optuna, is done through passing distributions, for instance:
```python
params_distributions = {
    # "forecaster": [NaiveForecaster()],
    "forecaster__window_length": optuna.distributions.IntDistribution(2, 6),
    "forecaster__strategy": optuna.distributions.CategoricalDistribution(
        ("drift", "last", "mean")
    ),
    "imputer__method": optuna.distributions.CategoricalDistribution(("mean", "median")),
}
```

**Comment by gareth-brown-86** [comment]
@mk406
@fkiraly

**Comment by fkiraly** [comment]
FYI @yarnabrina, @benHeid

**Comment by fkiraly** [comment]
Sounds great!

The parameters of the class would more or less be the same as for `ForecastingGridSearchCV`, right?

**Comment by gareth-brown-86** [comment]
> Sounds great!
> 
> The parameters of the class would more or less be the same as for `ForecastingGridSearchCV`, right?

I think there will be some additional parameters to control the options in optuna (which there are a few).
I question if we should keep the parameter passing variable as param_grid. I think it would be more accurate to call it param_dist, but I like keeping the same parameter names as gridsearch. What do you think?

**Comment by fkiraly** [comment]
`ForecastingRandomSearchCV` has `param_dist`, since `optuna` is sampling based optimization, I would aim for consistency with its interface instead, in my opinion.

**Comment by gareth-brown-86** [comment]
I have a question on how we can clean up this interface and allow it to use a lot of the methods of the base class.
If I understand correctly, ideally we could just implement the _run_search, and most of the other parts would just use the base class methods. 

The main two parts I see is:
1) how can we create something like the ParameterSampler from the ask-tell interface
 ```python
       study = optuna.create_study(direction="minimize")
        for _ in range(self.n_evals):
            trial = study.ask(self.param_grid)  # pass the pre-defined distributions.
            params = {name: trial.params[name] for name, v in self.param_grid.items()}

            meta = {}
            meta["forecaster"] = self.forecaster
            meta["y"] = y
            meta["X"] = X
            meta["cv"] = cv
            meta["strategy"] = self.strategy
            meta["scoring"] = scoring
            meta["error_score"] = self.error_score
            meta["scoring_name"] = scoring_name

            out = _fit_and_score(params, meta)
            study.tell(trial, out[f"mean_{scoring_name}"])

        params_list = [trial.params for trial in study.trials]

        results = study.trials_dataframe()
```
2) Given that we need the results from trial n to find the parameters from trail n+1, how would the 'parallelize' within evaluate_candidates work? 

Any ideas?

**Comment by gareth-brown-86** [comment]
Tasks that need to be done:

- [ ] Add the _get_score method
- [ ] Add docstring to class
- [ ] Allow it to work with a list of param_dist and not just the dictionary

**Comment by gareth-brown-86** [comment]
@fkiraly I think I now have a mostly working version, that definitely needs some refactoring. (https://github.com/mk406/sktime/pull/4)

I have moved my code to a _run_search, but because I am not using the evaluate_candidate function, I need to completely redefine _fit. Additionally, I have needed to pass all the variable (eg x, Y, score,cv) because evaluate_candidate already had access to them, so were not needed to be passed in the base class.

My first suggestion that comes to mind to simplify would be to move evaluate_candidate to be a method of the class, and pass meta to it, so the base class of _evaluate_candidate and _run_search would change to recieve meta as an argument. Do you have any ideas?

**Comment by fkiraly** [comment]
I will comment on the code about the structure.

**Comment by fkiraly** [comment]
I'm somewhat confused about the code. Looking at `optuna`, would the simplest code not look like this?
https://github.com/optuna/optuna-examples/blob/main/sklearn/sklearn_optuna_search_cv_simple.py

So, I would expect that a user passes a `param_distribution`, not a grid like in sklearn grid search.
Here is the `sklearn` code: https://github.com/optuna/optuna-integration/blob/main/optuna_integration/sklearn/sklearn.py
I think it is atrociously complicated... so maybe a different approach could help.

Here's the syntax I suggest.

users pass a partial objective, of the form

```python
def param_dist(trial):
    x = trial.suggest_float("x", -100, 100)
    y = trial.suggest_categorical("y", [-1, 0, 1])
    return {"x": x, "y":y}
```

This is a parameter of the estimator.

Then, inside the class, in `_fit`, we do

```python
study = optuna.create_study(directions=["minimize"])`

def objective(trial):
    params = param_dist(trial)
    inst = self.estimator.clone().set_params(**params)
    res = evaluate(inst, metric, y, X)[metric_column]
    return res

study.optimize(objective, n_trials=500, timeout=1)
self.best_estimator_ = self.estimator.clone().set_params(**study.best_trial.params)
```

Do you think this would work?

give or take some variables and function signatures that have to be corrected.

**Comment by gareth-brown-86** [comment]
> I'm somewhat confused about the code. Looking at `optuna`, would the simplest code not look like this? https://github.com/optuna/optuna-examples/blob/main/sklearn/sklearn_optuna_search_cv_simple.py
> 
> So, I would expect that a user passes a `param_distribution`, not a grid like in sklearn grid search. Here is the `sklearn` code: https://github.com/optuna/optuna-integration/blob/main/optuna_integration/sklearn/sklearn.py I think it is atrociously complicated... so maybe a different approach could help.
> 
> Here's the syntax I suggest.
> 
> users pass a partial objective, of the form
> 
> ```python
> def param_dist(trial):
>     x = trial.suggest_float("x", -100, 100)
>     y = trial.suggest_categorical("y", [-1, 0, 1])
>     return {"x": x, "y":y}
> ```
> 
> This is a parameter of the estimator.
> 
> Then, inside the class, in `_fit`, we do
> 
> ```python
> study = optuna.create_study(directions=["minimize"])`
> 
> def objective(trial):
>     params = param_dist(trial)
>     inst = self.estimator.clone().set_params(**params)
>     res = evaluate(inst, metric, y, X)[metric_column]
>     return res
> 
> study.optimize(objective, n_trials=500, timeout=1)
> self.best_estimator_ = self.estimator.clone().set_params(**study.best_trial.params)
> ```
> 
> Do you think this would work?
> 
> give or take some variables and function signatures that have to be corrected.

Regarding your first point, around passing param_distribution, that is the approach I had gone with. If you do that approach (ie set up the distributions upfront and pass them), then I think the easiest interface is the as-tell with define-and-run shown (here)[https://optuna.readthedocs.io/en/stable/tutorial/20_recipes/009_ask_and_tell.html#define-and-run].

I think the ask-tell interface makes it quite simple, this is the only optuna part:

```python
           study = optuna.create_study(direction="minimize")
           for _ in range(self.n_evals):
                trial = study.ask(param_grid_dict)
                params = {
                    name: trial.params[name] for name, v in param_grid_dict.items()
                }

                out = _fit_and_score(params, meta)

                study.tell(trial, self._get_score(out, scoring_name))
```


Regarding passing a function, that is something I didnt consider. It makes the interface here quite different from all the other parameter search interfaces. I think both approaches would work.

**Comment by gareth-brown-86** [comment]
@fkiraly Either approach I think could be wrapped away, so that it could deliver the same shape dataframe that is expected in the base class from _run_search. So if we managed to change it so that we can encapsulate everything within   _run_search, then we could use the base class _fit (which would make the changes quite small)

**Comment by fkiraly** [comment]
> Regarding your first point, around passing param_distribution, that is the approach I had gone with.

I see, that makes sense. Can you then kindly explain to me why you are checking for dict or list of dict? Is that how you pass distributions to `optuna`? I thought you were going with a grid approach.

**Comment by fkiraly** [comment]
Ah, I see, now I understand. Apologies, I was confused - this is how you pass the distribution - snippet from your code:

```python
param_grid = {
    "scaler__transformer__with_scaling": optuna.distributions.CategoricalDistribution(
        (True, False)
    ),
    "forecaster": optuna.distributions.CategoricalDistribution(
        (STLForecaster(), ThetaForecaster())
    ),
```

Sorry for being confused.

In that case, I think this way of invoking it:

```python
           study = optuna.create_study(direction="minimize")
           for _ in range(self.n_evals):
                trial = study.ask(param_grid_dict)
                params = {
                    name: trial.params[name] for name, v in param_grid_dict.items()
                }

                out = _fit_and_score(params, meta)

                study.tell(trial, self._get_score(out, scoring_name))
```

is the best one, we should not split up `meta` here. Why: because the above code generalizes much more easily to other learning tasks! What changes is `_fit_and_score` and the fields of `meta`, but nothing else.

**Comment by gareth-brown-86** [comment]
> > Regarding your first point, around passing param_distribution, that is the approach I had gone with.
> 
> I see, that makes sense. Can you then kindly explain to me why you are checking for dict or list of dict? Is that how you pass distributions to `optuna`? I thought you were going with a grid approach.

The only reason I wanted to be able to pass lists of dictionaries, would be to allow it to handle this example:
https://www.sktime.net/en/v0.30.1/examples/03b_forecasting_transformers_pipelines_tuning.html#1)-ForecastingGridSearchCV

```python
    param_grid=[
        {
            "scaler__transformer__with_scaling": [True, False],
            "forecaster": [NaiveForecaster()],
            "forecaster__strategy": ["drift", "last", "mean"],
            "forecaster__sp": [4, 6, 12],
        },
        {
            "scaler__transformer__with_scaling": [True, False],
            "forecaster": [STLForecaster(), ThetaForecaster()],
            "forecaster__sp": [4, 6, 12],
        },
    ],
```

**Comment by gareth-brown-86** [comment]
> Ah, I see, now I understand. Apologies, I was confused - this is how you pass the distribution - snippet from your code:
> 
> ```python
> param_grid = {
>     "scaler__transformer__with_scaling": optuna.distributions.CategoricalDistribution(
>         (True, False)
>     ),
>     "forecaster": optuna.distributions.CategoricalDistribution(
>         (STLForecaster(), ThetaForecaster())
>     ),
> ```
> 
> Sorry for being confused.
> 
> In that case, I think this way of invoking it:
> 
> ```python
>            study = optuna.create_study(direction="minimize")
>            for _ in range(self.n_evals):
>                 trial = study.ask(param_grid_dict)
>                 params = {
>                     name: trial.params[name] for name, v in param_grid_dict.items()
>                 }
> 
>                 out = _fit_and_score(params, meta)
> 
>                 study.tell(trial, self._get_score(out, scoring_name))
> ```
> 
> is the best one, we should not split up `meta` here. Why: because the above code generalizes much more easily to other learning tasks! What changes is `_fit_and_score` and the fields of `meta`, but nothing else.

What's are next steps? I still have one step I want to do, to allow maximisation and minimisation of the score. 
Plus getting the tests working.

**Comment by fkiraly** [comment]
> The only reason I wanted to be able to pass lists of dictionaries, would be to allow it to handle this example:

I don't think you need to handle parameter grids like from the `ForecastingGridSearchCV`, I think it's better if we focus on the `optina` distribution specifications. Are you writing your own code to translate this to `CategorialDitsribution`? In that case, we would need to maintain the conversion code, which might end up breaking. I think it's better the closer we are to the `optuna` specifications, but I do not have a strong opinion on *also* (as opposed ot *instead*) supporting grid-search like specification syntax.

**Comment by fkiraly** [comment]
> What's are next steps? I still have one step I want to do, to allow maximisation and minimisation of the score.
Plus getting the tests working.

1-3 in any order, then 4:

1. ensure code formatting checks pass, see here on how to set these up locally: https://www.sktime.net/en/latest/developer_guide/coding_standards.html
2. ensure `check_estimator` checks pass on the new estimator, asusming a good coverage of parameter choices in `get_test_params`
3. ensure docstring is complete
4. review by `sktime` core devs - if the above are green, it will be most likely merged soon after.

**Comment by gareth-brown-86** [comment]
> > The only reason I wanted to be able to pass lists of dictionaries, would be to allow it to handle this example:
> 
> I don't think you need to handle parameter grids like from the `ForecastingGridSearchCV`, I think it's better if we focus on the `optuna` distribution specifications. Are you writing your own code to translate this to `CategorialDitsribution`? In that case, we would need to maintain the conversion code, which might end up breaking. I think it's better the closer we are to the `optuna` specifications, but I do not have a strong opinion on _also_ (as opposed ot _instead_) supporting grid-search like specification syntax.

No I was planning on keeping to the same way of passing the distributions, for example:
```python
param_grid = [
    {
        "scaler__transformer__with_scaling": CategoricalDistribution([True, False]),
        "forecaster": CategoricalDistribution([NaiveForecaster()]),
        "forecaster__strategy": CategoricalDistribution(["drift", "last", "mean"]),
        "forecaster__sp": IntDistribution(4, 12),
    },
    {
        "scaler__transformer__with_scaling": CategoricalDistribution([True, False]),
        "forecaster": CategoricalDistribution([STLForecaster(), ThetaForecaster()]),
        "forecaster__sp": IntDistribution(4, 12),
    },
]
```
But if you dont think this way is valuable to pass the distributions, I can easily change it

**Comment by fkiraly** [comment]
I see - your plan makes absoute sense, let's merge it like that
