### ISSUE TITLE
[MNT] address deprecation of `pydocstyle`

### ISSUE THREAD

**Issue by fkiraly** [sktime/sktime#6636]
`pydocstyle` - used in `sktime` precommits - has been deprecated by its maintainers last year for reasons not entirely clear.

They recommend to transition to `ruff`.

FYI @sktime/core-developers

**Comment by fnhirwa** [comment]
> `pydocstyle` - used in `sktime` precommits - has been deprecated by its maintainers last year for reasons not entirely clear.
> 
> They recommend to transition to `ruff`.
> 
> FYI @sktime/core-developers

I would help to integrate `ruff` into our pre-commit

**Comment by fkiraly** [comment]
that would be great!
