### ISSUE TITLE
[BUG] TypeError: country_holidays() got an unexpected keyword argument 'categories'

### ISSUE THREAD

**Issue by galenseilis** [sktime/sktime#6672]
**Describe the bug**

Ran [this example](https://www.sktime.net/en/stable/api_reference/auto_generated/sktime.transformations.series.holiday.CountryHolidaysTransformer.html#r36194f8f65d7-1):

```python
from sktime.transformations.series.holiday import CountryHolidaysTransformer
from sktime.datasets import load_airline
y = load_airline()
y_t = CountryHolidaysTransformer("US").fit_transform(y)  
y_t.dtype  
y_t.sum()  
y_t.name  
```

Got the error:

```python
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/galen/.local/lib/python3.10/site-packages/sktime/transformations/base.py", line 707, in fit_transform
    return self.fit(X, y).transform(X, y)
  File "/home/galen/.local/lib/python3.10/site-packages/sktime/transformations/base.py", line 612, in transform
    Xt = self._transform(X=X_inner, y=y_inner)
  File "/home/galen/.local/lib/python3.10/site-packages/sktime/transformations/series/holiday/country_holidays.py", line 142, in _transform
    holidays_data = country_holidays(
TypeError: country_holidays() got an unexpected keyword argument 'categories'
```

**Versions**

```python
>>> sktime.__version__
'0.30.1'
>>> holidays.__version__
'0.21.13'
```

```bash
$ lsb_release -a
No LSB modules are available.
Distributor ID: Ubuntu
Description:    Ubuntu 22.04.4 LTS
Release:        22.04
Codename:       jammy
$ python --version
Python 3.10.12
```

**Comment by fkiraly** [comment]
@fnhirwa, you have looked at the `HolidayTransformer` recently - any ideas?

**Comment by yarnabrina** [comment]
https://github.com/sktime/sktime/blob/04644f723db767ca4020678bb0482d7b08d30420/pyproject.toml#L209

@galenseilis you are using an older version of holidays than we officially support. The transformer was written with new arguments from newer version.

**Comment by fnhirwa** [comment]
> @fnhirwa, you have looked at the `HolidayTransformer` recently - any ideas?

This example is working from my end it seems to be a version issue as mentioned by @yarnabrina

**Comment by galenseilis** [comment]
@yarnabrina Thank you for looking into that. I can confirm that updating the holidays package resolved the issue.
