### ISSUE TITLE
[BUG] Failure propagating tag requires_y in transformer pipelines.

### ISSUE THREAD

**Issue by kdekker-private** [sktime/sktime#6674]
**Describe the bug**
When building more complex transformer/forecasting pipelines, the propagation of y for transformation is not succesfull.

Found in:
- TransformerPipeline 
- Pipeline (GraphPipeline implementation)

The tag "requires_y" is always false. I do not know if this issue is present in more transformers, but I am aware of these.

**To Reproduce**

The example below adds a TransformerPipeline inside a ForecastingPipeline.
It is not the most realistic use case, but shows the bug.

```python
from sktime.datasets import load_airline
from sktime.transformations.compose import YtoX, TransformerPipeline
from sktime.transformations.series.fourier import FourierFeatures
from sktime.forecasting.statsforecast import StatsForecastAutoARIMA
from sktime.forecasting.compose import ForecastingPipeline

# data with no exogenous features
y = load_airline()

# create a pipeline with Fourier features and ARIMA
pipe_1 = ForecastingPipeline(
    [
            TransformerPipeline(steps = [ YtoX(),
            FourierFeatures(sp_list=[24, 24 * 7], fourier_terms_list=[10, 5])]),
            StatsForecastAutoARIMA()  
    ]
)  

# fit and forecast, using Fourier features as exogenous data
pred_1 = pipe_1.fit_predict(y, fh=[1, 2, 3, 4, 5])  
requires_y = pipe_1.steps[0].get_tag("requires_y", False)

# Predict without preprocessing
pred_2 = StatsForecastAutoARIMA().fit_predict(y, fh=[1, 2, 3, 4, 5])  

pred_1 != pred_2
```

**Expected behavior**

1. pred_1 != pred_2 should be true for all timepoints as the preprocessing should affect the predictions learned.
2. requires_y should be True as YtoX is used inside as transformer.

**Versions**
0.30.1

**Comment by fkiraly** [comment]
Question, can I ask you to clarify 2: the `requires_y` dynamic tag should be True for which component?

**Comment by kdekker-private** [comment]
For TransformerPipeline. Similarly also if TransformerPipeline would be replaced with Pipeline(GraphPipeline).

**Comment by fkiraly** [comment]
Ok, thanks.

Some comments:

* `pred_1 == pred_2` is actually expected, because in `FourierFeatures` you do not set `keep_original_columns`, so it will replace the columns from `YtoX`. This is the default behaviour so in `FeatureUnion` you do not accidentally duplicate columns.
* https://github.com/sktime/sktime/pull/6692 should solve the tags issue for `TransformerPipeline`.
* the issue for the graphical pipeline is not solved by 6692, FYI @benheid

**Comment by kdekker-private** [comment]
Thanks for acknowledging the bug.

@fkiraly Regarding your first point is I think not true. There is no preprocessing for the exogenous variables for pred_2 and for pred_1 there should be some exogenous variables as you push y to X.

Run for example below without the TransformerPipeline. This is a non-bug version that runs correct.

```python
from sktime.datasets import load_airline
from sktime.transformations.compose import YtoX
from sktime.transformations.series.fourier import FourierFeatures
from sktime.forecasting.statsforecast import StatsForecastAutoARIMA
from sktime.forecasting.compose import ForecastingPipeline

# data with no exogenous features
y = load_airline()

# create a pipeline with Fourier features and ARIMA
pipe_1 = ForecastingPipeline(
    [
            YtoX(),
            FourierFeatures(sp_list=[24, 24 * 7], fourier_terms_list=[10, 5]),
            StatsForecastAutoARIMA()  
    ]
)  

# fit and forecast, using Fourier features as exogenous data
pred_1 = pipe_1.fit_predict(y, fh=[1, 2, 3, 4, 5])  
requires_y = pipe_1.steps[0].get_tag("requires_y", False)

# Predict without preprocessing
pred_2 = StatsForecastAutoARIMA().fit_predict(y, fh=[1, 2, 3, 4, 5])  

pred_1 != pred_2

```

**Comment by fkiraly** [comment]
> for pred_1 there should be some exogenous variables as you push y to X.

Disagree, because `FourierFeatures` with the defaut setting deletes said pushed y by overide.

Can you please confirm whether my reasoning is correct, and contradict me again if you think I am wrong?

**Comment by kdekker-private** [comment]
> > for pred_1 there should be some exogenous variables as you push y to X.
> 
> Disagree, because `FourierFeatures` with the defaut setting deletes said pushed y by overide.
> 
> Can you please confirm whether my reasoning is correct, and contradict me again if you think I am wrong?

A I wasn't aware FourierFeatures overrides. Clear.

**Comment by fkiraly** [comment]
added clarification to the docs: https://github.com/sktime/sktime/pull/6834
