### ISSUE TITLE
[BUG] Croston cannot handle exogenous variables.

### ISSUE THREAD

**Issue by kdekker-kdr4** [sktime/sktime#6675]
**Describe the bug**
Croston cannot handle exogenous variables, but is marked as if it can.

**To Reproduce**
Example returns the tag "ignores-exogeneous-X".

```python
from sktime.forecasting.croston import Croston

Croston.get_class_tag("ignores-exogeneous-X")
```

**Expected behavior**
The returned tag "ignores-exogeneous-X" should be True and not False.

**Versions**
0.30.1

**Comment by fkiraly** [comment]
Agreed - very easy fix, would you (or someone else) like to fix it with a PR?

**Comment by Spinachboul** [comment]
@fkiraly 
I would like to work on this issue
Kindly assign this one to me..
Thanks

**Comment by Spinachboul** [comment]
@kdekker-private 
The issue lies since the parameter `ignores-exogeneous-X` is by default set to **True**

**Comment by fkiraly** [comment]
Yes, so you need to override the default in the concrete class, by adding it to the dict there.
