### ISSUE TITLE
[ENH] Allow pandas like X_inner_mtype for TabularSeriesAdapter

### ISSUE THREAD

**Issue by kdekker-private** [sktime/sktime#6680]
**Is your feature request related to a problem? Please describe.**
When wrapping a scikit-learn (or scikit-learn like) transformer with TabularSeriesAdapter the data passed during fit and transform is a numpy nd.array for Series scitype forecasting.
This allows for less flexibility in the transformer that is wrapper.

- Data types are coerced to float.
- Column names become inaccessible.
    - If the number of columns grow due to the transformer, the TabularSeriesAdapter is not able to define correcty the new column names.

**Describe the solution you'd like**
The option to allow pandas like X_inner_mtype, such as pd.DataFrame for Series forecasting. 

**Describe alternatives you've considered**
I do not know an alternative. Needed to coerse data myself and retranslating them back inside the TabularSeriesAdapter. E.g. datetime like values. Also needed to accept column names are not correctly send back.

**Comment by fkiraly** [comment]
Oh, I see - the adapter is from a time where `sklearn` did not have the extent of support for `pandas` it has today. We should certainly upgrade that, perhaps even make `pandas` the default after deprecation.

**Comment by fkiraly** [comment]
Implemented in https://github.com/sktime/sktime/pull/6752 - testing and feedback would be appreciated, i.e., does this meet your use case requirements?

Contribution of integration testing code for your use case would also be appreciated - posting here and I will move to the PR, or making a dependent PR.

**Comment by kdekker-private** [comment]
Yes this solution suffices for me. Thanks.
