### ISSUE TITLE
[ENH] Add TinyTimeMixer as Foundation Model

### ISSUE THREAD

**Issue by benHeid** [sktime/sktime#6698]
https://github.com/ibm-granite/granite-tsfm/blob/main/notebooks/tutorial/ttm_tutorial.ipynb

We should try to directly enable all of there three models if possible: https://huggingface.co/collections/ibm-granite/granite-time-series-models-663a90c6a2da73482bce3dc6

**Comment by fkiraly** [comment]
added here too: https://github.com/sktime/sktime/issues/6177

**Comment by pranavvp16** [comment]
I'm starting to work on this as MOIRAI is currently on hold due to issues with license and installation

**Comment by geetu040** [comment]
@pranavvp16 I had also started working on this, sorry for mentioning late. But I have not done much yet and won't mind switching to something else if you prefer working on this.

**Comment by fkiraly** [comment]
I have now assigned @geetu040 for the time being, as @pranavvp16 has said in direct message that he would be continuing on moirai
