### ISSUE TITLE
[ENH] Hosting moirai weights (old permissive license) on hugging face

### ISSUE THREAD

**Issue by pranavvp16** [sktime/sktime#6748]
Currently the old weights of `MOIRAI` are hosted under my account with the repo name `Pranavv/fork-moirai`, they need to be shifted to sktime org on hugging face with specific model cards. Opening this issue to track hosting of all variations of MOIRAI under sktime org.

**Comment by fkiraly** [comment]
I think you have write access on the `sktime` hugging face org already, but kindly let me know if this is incorrect and/or you need further access.

**Comment by pranavvp16** [comment]
The respective old weights of MOIRAI with all variations are fetched under my username, along with commits.
* [small](https://huggingface.co/Pranavv/moirai-small/tree/temp)
* [base](https://huggingface.co/Pranavv/moirai-base/tree/main)
* [large](https://huggingface.co/Pranavv/moirai-large/tree/main)

I plan to push them to sktime org's HF once I have updated the `README.md` with sktime example and docs for the model card. Which is dependant on PR #6299 
FYI : @benHeid

**Comment by pranavvp16** [comment]
I have uploaded the weights on hugging face and wanted a feedback on the README of [model](https://hackmd.io/@TxN8vTB0T6aexuvfRxlqhQ/SkMAFaxs0),

**Comment by fkiraly** [comment]
left some comments, and I see you already addressed them

**Comment by pranavvp16** [comment]
> left some comments, and I see you already addressed them

is it good to go now ??

**Comment by fkiraly** [comment]
Yes, from my side - thought you already published it

**Comment by pranavvp16** [comment]
Closing this, #6299 has been merged, also the `README.md` for model card has been updated at hf.
[sktime/moirai](https://huggingface.co/sktime/moirai-1.0-R-large)
