### ISSUE TITLE
[ENH] time series segmentation via clustering - reduction of time series segmentation to tabular clustering

### ISSUE THREAD

**Issue by fkiraly** [sktime/sktime#6750]
A simple reduction strategy for time series segmenters: pool the samples, and apply an `sklearn` clusterer that has a `transform` method. The different segments are the different clusters.

The syntax would be sth like `ClusterSegmenter(my_clusterer)`.

**Comment by Ankit-1204** [comment]
Hey, I am new to Open source. Can i work on this?

**Comment by Ankit-1204** [comment]
@fkiraly I made the changes requested, could you take a look?

**Comment by fkiraly** [comment]
of course, thanks!

**Comment by Ankit-1204** [comment]
@fkiraly Hi, the last tests actually failed, checking the summary it was related to a dumb mistake I made, 
`self.n_instances, self.n_timepoints = X.shape` , I treated the input data as only being dataframe, I have added 
```
if isinstance(X, pd.Series):
            X = X.to_frame()
```
it was able to handle the problem on my device. sorry that i was a silly mistake.

**Comment by fkiraly** [comment]
not a silly mistake - the annotation interface is not fully consolidated, we are working on that! FYI @Alex-JG3 (see other PR)

**Comment by fkiraly** [comment]
No problem, this is not bothering me!

The way to check your implementation would be using `check_estimator`, see here:
https://www.sktime.net/en/latest/developer_guide/add_estimators.html#using-the-check-estimator-utility

**Comment by Ankit-1204** [comment]
> No problem, this is not bothering me!
> 
> The way to check your implementation would be using `check_estimator`, see here: https://www.sktime.net/en/latest/developer_guide/add_estimators.html#using-the-check-estimator-utility

Got it, Thanks! 
All the test cases were successful, however it still shows 'Changes Requested', is there something that I missed?

**Comment by fkiraly** [comment]
I think this is great! Just needed some days to get to the review.
