### ISSUE TITLE
[BUG] CV calculation is incorrect in ADICVTransformer class

### ISSUE THREAD

**Issue by sbhobbes** [sktime/sktime#6755]
**Describe the bug**
Coefficient of Variation (CV) should be calculated as the sigma of non-zero values squared over the mu of non-zero values squared; however, in the implementation here, it's being calculated as the variance of non-zero values (Which should correctly correspond to sigma squared) over the number of non-zero values, making the denominator incorrect.

This blog post contains a short description of the calculations and approach: https://frepple.com/blog/demand-classification/

Source code reference:
https://github.com/sktime/sktime/blob/cd769b1769be67888213bfff522e1ea86f71eaef/sktime/transformations/series/adi_cv.py#L167

Discord reference:
https://discord.com/channels/1075852648688930887/1075852648948973642/1261316663991861273

**To Reproduce**
Following the blog post example, here's the code to produce an incorrect ADI, CV, and Classification:

```python
import numpy as np
import pandas as pd
from datetime import datetime
from sktime.transformations.series.adi_cv import ADICVTransformer

transformer = ADICVTransformer()
periods = pd.date_range(start=datetime(2023, 1, 1), end=datetime(2023, 12, 1), freq='MS')
series = [6, 5, 0, 9, 2, 0, 14, 0, 0, 21, 0, 17]
df = pd.DataFrame({'series': series}, index=periods)

adi_cv = transformer.fit_transform(df)
print(adi_cv)
```

output:
|adi	|cv2	|class|
|:----|:-----|:----|
|2.0	|6.897959	|lumpy

**Expected behavior**
The output should look like this:
|adi	|cv2	|class|
|:----|:-----|:----|
|1.71|0.37	|intermittent

**Additional context**

**Versions**
[c:\Users\sbhobbes\Anaconda3\envs\apf\Lib\site-packages\statsforecast\core.py:27](file:///C:/Users/sbhobbes/Anaconda3/envs/apf/Lib/site-packages/statsforecast/core.py:27): TqdmWarning: IProgress not found. Please update jupyter and ipywidgets. See https://ipywidgets.readthedocs.io/en/stable/user_install.html
  from tqdm.autonotebook import tqdm

System:
    python: 3.11.7 | packaged by conda-forge | (main, Dec 23 2023, 14:27:59) [MSC v.1937 64 bit (AMD64)]
executable: [c:\Users\sbhobbes\Anaconda3\envs\apf\python.exe](file:///C:/Users/sbhobbes/Anaconda3/envs/apf/python.exe)
   machine: Windows-10-10.0.19042-SP0

Python dependencies:
          pip: 23.3.2
       sktime: 0.30.2
      sklearn: 1.4.0
       skbase: 0.8.1
        numpy: 1.26.3
        scipy: 1.12.0
       pandas: 2.2.2
   matplotlib: 3.8.2
       joblib: 1.3.2
        numba: 0.59.1
  statsmodels: 0.14.1
     pmdarima: 2.0.4
statsforecast: 1.7.5
      tsfresh: None
      tslearn: None
        torch: 2.3.1+cpu
   tensorflow: None
tensorflow_probability: None

</details>

**Comment by fkiraly** [comment]
copying summary of comments from discord here for reference:

* the ADI may be right or not depending on definition. The original Syntetos/Boylan paper does not contain a formula, implementations relying on interpretations of imprecise English. WIthin these boundaries, the current formula may be considered "correct", but we may choose to replace this, see below.
* the CV2 formula is clearly incorrect, I overlooked this in review. The denominator should be the mean value, not the number of values.

### ADI formula

ADI is defined as "average waiting time for next non-zero value". There are perhaps three main ways to do this, assuming there are N non-zero values, at integer indices `i1`, ..., `iN`, within an array of total length `L`

* start counting at `i1` until `iN`. The average length would then be `(iN - i1) / (N - 1)`
* pool the zeroes at the trims (after `iN` and before `i1`) into a single period, and start counting from the start, or cirularly. The average length would then be `L / N`.
* ignore the trims, but start counting at `i1` until `iN`. That gives the current formula, `L / (N-1)`.

All formulae give approximatly the same result, and the same result in a limit where we let `L` go to infinity under weak stationarity assumptions on waiting times.

Concluding, perhaps we should use formula 2 as a default, and add an parameter, e.g., `adi_trim_handling` that allows users to select one of the formulae?

**Comment by fkiraly** [comment]
FYI @shlok191

**Comment by sbhobbes** [comment]
Incidentally, I have been looking for curriculum from Hyndman or others on the ADI calculation, but haven't been able to find anything black and white yet.  I'll keep digging.

**Comment by sbhobbes** [comment]
I am seeing some indications that P = ADI in the original paper.

**Comment by fkiraly** [comment]
what is P?

**Comment by sbhobbes** [comment]
It also doesn't seem to be clearly defined in the paper, it's just referenced as the "average period between positive demand."  I'm just going to try to implement your recommended parameterized approach.

**Comment by shlok191** [comment]
Just got caught up on the conversation. I remember running into similar troubles with there not being a clear formula of ADI (inside or outside the paper). I agree with the dual approach though! @sbhobbes, let me know if you'd like me to help out in anyway and thanks again!

**Comment by shlok191** [comment]
Just got caught up on the conversation. I remember running into similar troubles with there not being a clear formula of ADI (inside or outside the paper). I agree with the dual approach though! @sbhobbes, let me know if you'd like me to help out in anyway and thanks again!

**Comment by sbhobbes** [comment]
Sounds great, thanks! I had it mostly worked out this morning and then hit issues with getting the pre-commit hooks to work, wound up being an issue with my company firewall/VPN. I got that worked out tonight and was able to push back to my fork. I need to write some more unit tests since I changed quite a bit with the additional parameter. But I'll send you what I've got so far.

**Comment by sbhobbes** [comment]
Here's my commit on my forked copy, let me know if you have trouble viewing it or any questions. I need to go back through the doctrings and unit tests, as I mentioned, but I think this functionality should be roughly what we're looking for. 

https://github.com/sbhobbes/sktime/commit/0b980527b2dd2131abade6cb38c331e09539dee7

**Comment by fkiraly** [comment]
Can you open a pull request? That's easier to review. If it's not done yet, you can mark it as a draft PR.
