### ISSUE TITLE
[DOC] various documentation issues

### ISSUE THREAD

**Issue by ceroper** [sktime/sktime#6775]
#### Describe the issue linked to the documentation

I'm looking at this tutorial: https://www.sktime.net/en/latest/examples/01c_forecasting_hierarchical_global.html.

Overall it's very helpful!
I think there might be a typo here:
"structure convention: obj.index must be monotonous, and one of Int64Index, RangeIndex, DatetimeIndex, PeriodIndex."

I also had a question about this portion:

"sktime distinguishes as abstract scientific data types for time series (=”scitypes”):
Series type = one time series (uni or multivariate)
Panel type = collection of multiple time series, flat hierarchy
Hierarchical type = hierarchical collection of time series, as above"

The reference material linked in this doc suggests that the types of time series are grouped type and hierarchical type: https://otexts.com/fpp2/gts.html

Would you say that panel type is the same as grouped type?

#### Suggest a potential alternative/fix

"structure convention: obj.index must be monotonic, and one of Int64Index, RangeIndex, DatetimeIndex, PeriodIndex."

"sktime distinguishes as abstract scientific data types for time series (=”scitypes”):
Series type = one time series (uni or multivariate)
Panel type = collection of multiple time series, flat hierarchy, also sometimes called grouped type
Hierarchical type = hierarchical collection of time series, as above"

**Comment by fkiraly** [comment]
Agree with "monotonic", this typo probably exists in multiple other places in the code base as well, perhaps a bulk search might be useful here.

> Would you say that panel type is the same as grouped type?

In the terminology of fpp2, grouped are combinations of multiple hierarchies, so grouped is strictly more general than hierarchical. Panel is a subcase of hierarchical, with a single group, and a single hierarchy level. So, panel is not the same as grouped, but a simple subcase of hierarchical.
