### ISSUE TITLE
[ENH] Add sampler with seed argument to ForecastingOptunaSearchCV

### ISSUE THREAD

**Issue by bastisar** [sktime/sktime#6778]
Related: #6618 

**Is your feature request related to a problem? Please describe.**
While sktime now provides a Optuna driven hyperparameter optimization method via `ForecastingOptunaSearchCV`, there is no way of setting a seed for Optuna which results non reproducible results when using `ForecastingOptunaSearchCV` even if a seed is set for the corresponding model.

**Describe the solution you'd like**
`ForecastingOptunaSearchCV` should accept a [sampler](https://optuna.readthedocs.io/en/stable/reference/samplers/index.html#module-optuna.samplers) as an argument. This way, first, the seed problem can be solved, and second, more flexibility is provided concerning the sampler the user wants to leverage.

**Describe alternatives you've considered**
For now, `ForecastingOptunaSearchCV` leverages the default parameters of `create_study` therefore `TPESampler` is used. If not changing this behaviour we could just handover a seed to the sampler, to keep it in line with `ForecastingRandomizedSearchCV` and `ForecastingSkoptSearchCV`, we could go with the argument `random_state` for seed in the sample

**Additional context**
New argument sampler with default:

`sampler = optuna.samplers.TPESampler(seed=42)`

Hand over sampler in code lines [ForecastingOptunaSearchCV](https://github.com/sktime/sktime/blob/fecfe92c9f6e8f1379978e6df2569046c82e2920/sktime/forecasting/model_selection/_tune.py#L1910) like:

`study = optuna.create_study(direction="minimize", sampler=sampler)`

**Comment by fkiraly** [comment]
Sounds like an excellent idea!

FYI @gareth-brown-86, @mk406

Would you like to open a draft PR with your suggestion, @bastisar?

**Comment by bastisar** [comment]
@fkiraly yes I'm on it 👍

**Comment by gareth-brown-86** [comment]
Definitely a good idea and happy to have a look over the implementation.

@fkiraly perhaps we should release it with the changes needed to define if we are maximising or minimising the score?

**Comment by fkiraly** [comment]
> @fkiraly perhaps we should release it with the changes needed to define if we are maximising or minimising the score?

Sure! There is a mostly regular monthly release schedule, and whenever it is ready it can go in the next release.

The two changes do not seem to be too interdependent, so in-principlke we could release separately if one of the two takes longer.
