### ISSUE TITLE
[BUG] pyKAN with version 1.* is not working

### ISSUE THREAD

**Issue by benHeid** [sktime/sktime#6784]
**Describe the bug**

PykanForecaster with pykan version 0.1.* is raising errors. Version 0.0.* is working 0.2.* needs to be tested. 

Probably adapt to new interface and set a version bound.

**Comment by fkiraly** [comment]
Do we need to introduces version bounds in the estimator dependencies?

**Comment by benHeid** [comment]
Yes. To support the newest version, we might even need to change the code a bit. I have to check version 0.2.*
