### ISSUE TITLE
[ENH] link to docs from estimator `__repr__`

### ISSUE THREAD

**Issue by fkiraly** [sktime/sktime#6812]
`sklearn` has implemented a nice feature where the html repr links to the sklearn docs.

We should also replicate this - probably it suffices to override the html `__repr__` in `BaseObject.

Good first issue since we can template off `sklearn`.

**Comment by fkiraly** [comment]
all yours!

Some side info, the default `__repr__` is inherited from `scikit-base`, here: https://github.com/sktime/skbase/blob/7204953254fad046f6a62b1b7b477588c2cc3be0/skbase/base/_base.py#L812

However, we should override - at least for now - in `sktime`, since a generic object will not have docs to link to, and `sktime` has docs to link to.

To generate a link to the docs page, we already do this on the estimator search page, the magic logic is here:
https://github.com/sktime/sktime/blob/80c9eed218bac737dd4ca17a43d86a344236aaa4/docs/source/conf.py#L507

This could be factored out into a function in `utils`, which would then provide the link to the estimator search as well as to the estimator boxes.

**Comment by mateuszkasprowicz** [comment]
@fkiraly, some questions:

1. For docs link generation, do we prefer a separate [MixIn class as in sklearn](https://github.com/rcap107/scikit-learn/blob/4ee853de23be4bd65e0f18690521c114e71f6d4a/sklearn/utils/_estimator_html_repr.py#L398) or just a function for now?
2. Override those [skbase.base.BaseObject's methods](https://github.com/sktime/skbase/blob/7204953254fad046f6a62b1b7b477588c2cc3be0/skbase/base/_base.py#L873-L902) in sktime's BaseEstimator?
3. Sklearn uses [this inconspicuous function parse_version](https://github.com/rcap107/scikit-learn/blob/4ee853de23be4bd65e0f18690521c114e71f6d4a/sklearn/externals/_packaging/version.py#L65) to establish proper package version (to be inserted into a docs link). In fact, behind it there's ~600 lines of code borrowed from https://github.com/pypa/packaging, which makes this version parsing compliant with historical PEP 440 for version identification. Do we want to have it as well?

**Comment by fkiraly** [comment]
> For docs link generation, do we prefer a separate MixIn class as in sklearn or just a function for now?

I would make it a mixin, that makes it easier to push it up the inheritance tree if needed.

> Override those skbase.base.BaseObject's methods in sktime's BaseEstimator?

I would override in `sktime` `BaseObject`. This inherits from `skbase` `BaseObject` which has its own `__repr__` (based on an older version of sklearn's display)

> Sklearn uses this inconspicuous function parse_version to establish proper package version (to be inserted into a docs link). In fact, behind it there's ~600 lines of code borrowed from https://github.com/pypa/packaging, which makes this version parsing compliant with historical PEP 440 for version identification. Do we want to have it as well?

`packaging` is a core dependency of `sktime`, so why not use packaging here instead of forking it? It is core since - unlike `sklearn` - we manage estimators as mini-packages.

**Comment by mateuszkasprowicz** [comment]
thanks @fkiraly 

In `sklearn` the html representation (with a link) is created through [`estimator_html_repr()`](https://github.com/rcap107/scikit-learn/blob/4ee853de23be4bd65e0f18690521c114e71f6d4a/sklearn/utils/_estimator_html_repr.py#L317-L331). Its equivalent in `sktime` is [`_object_html_repr()`](https://github.com/sktime/skbase/blob/7204953254fad046f6a62b1b7b477588c2cc3be0/skbase/base/_pretty_printing/_object_html_repr.py#L345) from `skbase`. Wouldn't it make more sense to update `skbase`'s `_object_html_repr()` according to sklearn implementation instead of creating it from scratch in `sktime`?

**Comment by fkiraly** [comment]
I would do it in `sktime` first, since it would require less syncing across releases of different packages.

One of the problems is with linking to the documentation. An `skbase` `BaseObject` does not have a natural documentation location, so we would have to think about an API mechanism to retrieve this from scratch.

Unless you have a full picture on how you would update what, I'd suggest we implement a working version in `sktime` first, and then in a second go abstract it up the dependency tree to `skbase`.

**Comment by mateuszkasprowicz** [comment]
okay, I have a working prototype. will push the changes for review soon. one more questions though:
perhaps alongside adding the link to docs we can update the CSS style template just as sklearn did - what do you think? I think it's more dark/light theme friendly.

![image](https://github.com/user-attachments/assets/3b3ba2a0-92de-4c20-b0ae-031c29c4e6b2)

**Comment by fkiraly** [comment]
> perhaps alongside adding the link to docs we can update the CSS style template just as sklearn did - what do you think?

Sure, why not! Consistency makes sense.

**Comment by fkiraly** [comment]
implemented in https://github.com/sktime/sktime/pull/6876!
