### ISSUE TITLE
[ENH] `feature_kind` and `dtypekind_dfip` for polars mtype

### ISSUE THREAD

**Issue by pranavvp16** [sktime/sktime#6815]
The recent PR #6490 has introduced two new metadict fields i.e `feature_kind` and `dtypekind_dfip` for mtypes. This needs to be added to polars mtype and corresponding scitypes metadict.

FYI @Abhay-Lejith

**Comment by Abhay-Lejith** [comment]
I'm not really familiar with polars but I'll have a look. 
Is it blocking your pr currently? In case you need a temporary fix, you can assign a list of `DtypeKind.FLOAT` to the metadata (list length = number of columns in df).

**Comment by Abhay-Lejith** [comment]
I'm not really familiar with polars but I'll have a look.
Is this blocking your pr currently? If you need a temporary fix, you can assign a list of 'DtypeKind.FLOAT' to the metadata with the length of the list = number of columns in df.

**Comment by Abhay-Lejith** [comment]
I'm not really familiar with polars but I think it should be fairly simple for you to infer the metadata from the polars df.
Please take a look at the `dask_to_pd.py` and `_dtypekind.py` files for an example.
Basically you need to get a list containing the dtype of each column. Then convert these dtypes to the corresponding `DtypeKind` values using `_pandas_dtype_to_kind()` - this list gets stored in `dtypekind_dfip`. This list again simplified by passing it into `_get_feature_kind()` and this is stored in `feature_kind`. 

One doubt I have is whether the `_pandas_dtype_to_kind()` will work for polars, i.e will the pandas utility functions also identify the dtypes used in the polars df.
Please check and let me know if you need any clarifications.

**Comment by fkiraly** [comment]
FYI, polars has dtypes like pandas, the same principle applies - PR appreciated!

https://docs.pola.rs/api/python/stable/reference/datatypes.html
https://docs.pola.rs/api/python/stable/reference/dataframe/api/polars.DataFrame.dtypes.html

**Comment by pranavvp16** [comment]
I added a new function similar to `_pandas_dtype_to_kind` for polars, with polars specific datatypes

**Comment by pranavvp16** [comment]
@fkiraly we can close this as #6485 has been merged addressing this issue too.

**Comment by fkiraly** [comment]
ah yes, it should have been linked - using keywords like "fixes #abcd" does that and automatically closes the issue if the PR gets merged.
