### ISSUE TITLE
[ENH] add SCINet forecaster

### ISSUE THREAD

**Issue by fkiraly** [sktime/sktime#6831]
Feature request to add SCINet: https://github.com/cure-lab/SCINet

There is no package release for this, only the research grade repository, so this would mean either:

* help progress source repo to package and direct interface (1st or 2nd party)
* copy code to an `sktime` native estimator, ensure to acknowledge authors (this option is probably easier)

Developer guide for adding estimators: https://www.sktime.net/en/latest/developer_guide/add_estimators.html

**Comment by Sohaib-Ahmed21** [comment]
I have started work on this issue and will try to open draft PR soon.

**Comment by Sohaib-Ahmed21** [comment]
I have started work on this issue and will try to open draft PR soon.

**Comment by fkiraly** [comment]
Great, thanks!

**Comment by Prtm2110** [comment]
Hello, I've noticed that this issue hasn't had any recent activity and was wondering if it would be okay for me to take over and work on it?

**Comment by Sohaib-Ahmed21** [comment]
> Hello @fkiraly , I've noticed that this issue hasn't had any recent activity and was wondering if it would be okay for me to take over and work on it?

I have worked on this issue and still active on it. It's my first issue so took some time but I will open PR soon. You may review that and help me there. Thanks!
