### ISSUE TITLE
[ENH] add `statsforecast` MFLES model

### ISSUE THREAD

**Issue by fkiraly** [sktime/sktime#6854]
`statsforecast` recently added the MFLES model to their library - we should add an interface, too.

The recipe should be simple, taking any existing estimator that inherits from `_GeneralisedStatsForecastAdapter` as a template.

Link to MFLES: https://github.com/Nixtla/statsforecast/blob/main/statsforecast/mfles.py

"adding estimator" guide: https://www.sktime.net/en/latest/developer_guide/add_estimators.html

**Comment by yarnabrina** [comment]
Probably part of #4643

**Comment by fkiraly** [comment]
I see - #4643 shoul the have a wishlist of "todos" - right now it looks like a done issue, since it lacks refereces to the individual models

**Comment by yarnabrina** [comment]
Yes, we can. Added a checkbox there, kindly take a look.

**Comment by fkiraly** [comment]
superseded by https://github.com/sktime/sktime/issues/4643

**Comment by tblume1992** [comment]
Excited that ya'll are adding MFLES, let me know if you need any assistance with the port, the Nixtla version is based on my original code!
