### ISSUE TITLE
[ENH] Run annotator output conversion methods on all annotators

### ISSUE THREAD

**Issue by Alex-JG3** [sktime/sktime#6895]
**Is your feature request related to a problem? Please describe.**

In `sktime/annotation/tests/test_base.py`, there is a small test suite for the output conversion methods like `test_sparse_to_dense`. All annotators should be able to do these conversions so these tests should be run on all annotators.

**Describe the solution you'd like**

Thanks to #6843, we should be able to move a subset of the tests from `sktime/annotation/tests/test_base.py` to `sktime/annotation/tests/test_all_annotators.py`.

Alternatively, we could pass the set of annotators directly to the tests in `sktime/annotation/tests/test_all_annotators.py`. It looks like this approach is popular in other parts of sktime for example https://github.com/Alex-JG3/sktime/blob/6d1829fff0b824bf76c4f7142b8185f8a2dc3e9a/sktime/forecasting/tests/test_window_forecasters.py#L33.

@fkiraly, it would be good to get your guidance here on which approach you think is better.

**Comment by fkiraly** [comment]
would it not be best if we test the conversion methods in isolation, and then the outputs of all annotators, separately and in addition, in `TestAllAnnotators`?
