### ISSUE TITLE
[ENH] Add Subsequence Extraction Transformer to `sktime.transformations` module

### ISSUE THREAD

**Issue by wirrywoo** [sktime/sktime#6901]
**Is your feature request related to a problem? Please describe.**

It would be useful to implement a series-to-series transformer which extracts a subsequence of specified window length having some desired property with respect to an aggregate function. This enhancement should aim to address problems like the following:

- Given a sequence $(x_1, x_2, ..., x_n)$, find a $k$ - length subsequence such that the average value of $(x_j, x_{j+1}, ..., x_{j+k-1})$ is maximal.

**Describe the solution you'd like for `SubsequenceExtractionTransformer`**

**Behaviour:**
- Identifies all subsequences of provided window length and returns the subsequence with the desired property.

**Hyper-parameters:** (Tentative but happy to consider better naming conventions and add support for more values beyond the specified supported values)
- [ ] `window_size` should be a positive integer less than the input sequence length. Returns error if `window_size` is greater than input sequence length
- [ ] `aggregate` is a function parameter mapping each identified subsequence to one aggregate value for comparison purposes. Defaults to taking the mean if no parameter value is supplied.
- [ ] `method` is a string that compares all aggregate values to each other and decides which subsequence to return. Defaults to "max", but should also support "min".

**Describe alternatives you've considered**

Similar to the output of `TruncationTransformer`:

```
import numpy as np
import pandas as pd

np.random.seed(1)
test = [np.random.randint(100, size = s) for s in np.random.randint(low= 5, high = 20, size=10)]
df = pd.DataFrame(test).T

result = TruncationTransformer(lower = 0, upper = 3).fit_transform(df)
```

the output of `SubsequenceExtractionTransformer` should be:

```
import numpy as np
import pandas as pd

window_size = 3

np.random.seed(1)
test = [np.random.randint(100, size = s) for s in np.random.randint(low= 5, high = 20, size=10)]
df = pd.DataFrame(test).T

upper = df.rolling(window_size).mean().idxmax() + 1
lower = upper - window_size

truncation_transformers = list(map(lambda indices: TruncationTransformer(*indices), zip(lower, upper)))
result = pd.concat(list(map(lambda s: s[0].fit_transform(s[1][1]).reset_index(drop=True), zip(truncation_transformers, df.T.iterrows()))),axis=1)
result.index.name = 'timepoints'

## Should generate using the following call (**args to be finalized):
## result = SubsequenceExtractionTransformer(**args).fit_transform(df)
```

**Additional context**

Given `df` defined as: 
![image](https://github.com/user-attachments/assets/5fc3ee5e-5d48-4ae7-b49f-8f0655cd1b84)

the output of `TruncationTransformer` from the above code sample should be:
![image](https://github.com/user-attachments/assets/5b3bc6e4-9016-4b94-a5a9-c8e2b97188f9)

and the output of `SubsequenceExtractionTransformer` from the above code sample should be:
![image](https://github.com/user-attachments/assets/ad100118-0799-4e81-a84a-b20470c086c3)

**Comment by fkiraly** [comment]
Idea: what if `aggregate` could also be a transformer? users can pass functions, but also `sktime` or `sklearn` transformations.

**Comment by wirrywoo** [comment]
> Idea: what if `aggregate` could also be a transformer? users can pass functions, but also `sktime` or `sklearn` transformations.

I'm thinking that `aggregate` should be a function $f$ that maps subsequences to a scalar value ($f: (x_1, ..., x_m) \to \mathbb{R}$). This may include using [`functools.partial`](https://docs.python.org/3/library/functools.html#partial-objects) to support functions with specified hyperparameters (like $p$ in [generalized means](https://en.wikipedia.org/wiki/Generalized_mean)). Are there any `sktime` or `sklearn` transformations that do this?

You can assign this issue to me as well. Thank you!
