### ISSUE TITLE
[ENH] improvements for html repr of estimators

### ISSUE THREAD

**Issue by fkiraly** [sktime/sktime#6903]
There are two major (but not breaking) issues with the current html representation of estimators, from `__repr__`:

1. Pipelines render left-to-right rather than top-to-bottom.

I am not sure how to fix this, the best would be to add a tag that somehow controls this for a given composite. See display below for the `ForecastingPipeline`.

```python
from sktime.forecasting.compose import ForecastingPipeline

ForecastingPipeline.create_test_instance()
```
yields 
![image](https://github.com/user-attachments/assets/51009021-6147-4a95-a9ac-6815273c125a)

2. The html display does not seem to correctly display dropdowns for multiple nested estimators across packages.

An example of this is the following estimator composite which has an sklearn estimator inside an skpro estimator, inside an sktime estimator:

```python
from sktime.forecasting.compose import DirectTabularRegressionForecaster
fs = DirectTabularRegressionForecaster.create_test_instances_and_names()
fs[0][2]
```

Interestingly, the sklearn estimator is displayed, but not the skpro estimator:
![image](https://github.com/user-attachments/assets/f9e94d03-e4a8-44d2-9271-983d1c307b98)

**Comment by mateuszkasprowicz** [comment]
Solve both issues:

> 1. Pipelines render left-to-right rather than top-to-bottom.

![image](https://github.com/user-attachments/assets/79b4e825-5644-4479-b1ae-c53ed94f2eca)

> 2. The html display does not seem to correctly display dropdowns for multiple nested estimators across packages.
![image](https://github.com/user-attachments/assets/48f0562e-2a5c-46ba-abb9-8e760490ddff)

Small changes for `_get_visual_block` and adding `_sk_visual_block_` method to `_Pipeline` cherrypicked from `sklearn` were enough.

On the other hand, while working on this I noticed an issue with the doc link I worked on. I made a wrong assumption that the [fallback doc link](https://github.com/sktime/sktime/blob/80c9eed218bac737dd4ca17a43d86a344236aaa4/docs/source/conf.py#L510) always exists. For example: `ForecastingPipeline` link created that way is `https://www.sktime.net/en/v0.31.0/api_reference/auto_generated/sktime.forecasting.compose._pipeline.ForecastingPipeline.html` and returns 404. The correct one is `https://www.sktime.net/en/v0.31.0/api_reference/auto_generated/sktime.forecasting.compose.ForecastingPipeline.html`. But that's for another issue I guess. Related to #6812 and #6876.

**Comment by fkiraly** [comment]
> I made a wrong assumption that the [fallback doc link](https://github.com/sktime/sktime/blob/80c9eed218bac737dd4ca17a43d86a344236aaa4/docs/source/conf.py#L510) always exists.

I think you did not see my pointer to the "magic code" that does this correctly, and I did not spot this in your PR!

See here for the full magic code, this should be used from both locations.

https://github.com/sktime/sktime/issues/6812#issuecomment-2243891263

**Comment by fkiraly** [comment]
> Solve both issues:

Nice!

Do you think we can do this with a tag, instead of overriding `_sk_visual_block_`, that seems quite tedious for developers.

E.g., a tag like `display:blocks` which can have values `"auto"` (defaults to single if one component, parallel if multiple), `"single"`, `"sequential"`, etc?

**Comment by mateuszkasprowicz** [comment]
> > I made a wrong assumption that the [fallback doc link](https://github.com/sktime/sktime/blob/80c9eed218bac737dd4ca17a43d86a344236aaa4/docs/source/conf.py#L510) always exists.
> 
> I think you did not see my pointer to the "magic code" that does this correctly, and I did not spot this in your PR!
> 
> See here for the full magic code, this should be used from both locations.
> 
> [#6812 (comment)](https://github.com/sktime/sktime/issues/6812#issuecomment-2243891263)

Initially I thought that the `primaryURL` is just a neater version of `fallbackURL` that always exists.
https://github.com/sktime/sktime/blob/2369991b38ca0317493ec83180919111b454bf80/docs/source/estimator_overview.md?plain=1#L324C1-L325C1
But from what I understand it's the case when just one of them is correct. How can we predetermine which one is right? Underscore in the parent module name?

**Comment by mateuszkasprowicz** [comment]
And just a note that `sktime.pipeline.Pipeline` will require a different `_sk_visual_block_` method as well. Not sure how it fits with the current design. But that's for a future I guess.
![image](https://github.com/user-attachments/assets/6a5124f4-abc5-40bb-b420-18fcc494525e)

**Comment by fkiraly** [comment]
yes, probably - I believe @benHeid and @ArthrowAbstract are working on this.

**Comment by fkiraly** [comment]
> > > I made a wrong assumption that the [fallback doc link](https://github.com/sktime/sktime/blob/80c9eed218bac737dd4ca17a43d86a344236aaa4/docs/source/conf.py#L510) always exists.
> > 
> > 
> > I think you did not see my pointer to the "magic code" that does this correctly, and I did not spot this in your PR!
> > See here for the full magic code, this should be used from both locations.
> > [#6812 (comment)](https://github.com/sktime/sktime/issues/6812#issuecomment-2243891263)
> 
> Initially I thought that the `primaryURL` is just a neater version of `fallbackURL` that always exists. https://github.com/sktime/sktime/blob/2369991b38ca0317493ec83180919111b454bf80/docs/source/estimator_overview.md?plain=1#L324C1-L325C1 But from what I understand it's the case when just one of them is correct. How can we predetermine which one is right? Underscore in the parent module name?

I believe so. I also think the "magic code" linked in this post
https://github.com/sktime/sktime/issues/6812#issuecomment-2243891263
always results in a (and , in this case, the unique) valid URL - have you seen it?

**Comment by mateuszkasprowicz** [comment]
https://github.com/sktime/sktime/blob/main/docs%2Fsource%2Festimator_overview.md#L324-L337

If the primary URL is accessible, it navigates there; otherwise, it redirects to a fallbackUrl in case of a failed response or error. I feel like __if we can__ reliably obtain a correct URL for each object we might want to change this logic.

**Comment by fkiraly** [comment]
Oh, I see, may I confirm what you are saying, can you please check my understanding:

you would want to have an exact condition for when the one or the other case applies, which is not a flag calculated in the current "magic code", instead a redundant `fetch` is carried out, which is wasteful because you think we could infer the correct URL before doing any `fetch`.

Is my understanding correct?

If so, then the algorithm for the path would be as follows:

1. take the path of the class, `path`, in `sktime`, e.g., `sktime.forecasting.compose._column_ensemble.ColumnEnsembleForecaster`
2. remove all submodules starting with an underscore from the path to obtain a reduced path string `path_reduced`, e.g., `sktime.forecasting.compose.ColumnEnsembleForecaster`
3. The URL is 
`f"https://www.sktime.net/en/stable/api_reference/auto_generated/{path_reduced}.html"`

I asked a chatbot to write code for this, this might be useful (if it is not incorrect)

```python
def remove_substrings_after_underscore(input_string):
    # Split the string by '.'
    substrings = input_string.split('.')
    
    # Find the index of the first substring starting with '_'
    index_to_remove = None
    for i, substring in enumerate(substrings):
        if substring.startswith('_'):
            index_to_remove = i
            break
    
    # If an underscore substring is found, remove it and all subsequent substrings except the last one
    if index_to_remove is not None:
        substrings = substrings[:index_to_remove] + substrings[-1:]
    
    # Join the remaining substrings back together with '.'
    result_string = '.'.join(substrings)
    
    return result_string
```

**Comment by mateuszkasprowicz** [comment]
> Is my understanding correct?
Yes, that was exactly my point

Will push the changes tomorrow
