### ISSUE TITLE
[BUG] Prophet's get_fitted_params() raises an error when timeseries is a constant

### ISSUE THREAD

**Issue by felipeangelimvieira** [sktime/sktime#6982]
**Describe the bug**

I've verified that this error happens in a really specific scenario where the timeseries is a constant. In that case, the parameter `k` of the forecaster is an array 1 dimension, while `_get_fitted_params` of `_ProphetAdapter` assumes it comes in a two dimensional array and fails when running:

```python
self._forecaster.params[name][0][0]
```

I can submit a PR tomorrow to fix that minor issue. Replacing it with `self._forecaster.params[name].flatten()[0]` may solve the bug.

**To Reproduce**

```python

from sktime.forecasting.fbprophet import Prophet
import pandas as pd
y  = pd.DataFrame(index=pd.period_range(start="2022-01", periods=18, freq="Q"),
             data={"value": 0})
# By removing the comment from the line below
# the error disappears
#y.iloc[-1] = 1

forecaster = Prophet(freq="Q").fit(y)
forecaster.get_fitted_params()
```

**Expected behavior**
The fitted params of the model

**Additional context**

**Versions**
<details>
System:
    python: 3.11.8 (main, Feb  6 2024, 21:21:21) [Clang 15.0.0 (clang-1500.1.0.2.5)]
executable: [...sktime-tutorial-euroscipy2024/.venv/bin/python](https://file+.vscode-resource.vscode-cdn.net/.../sktime-tutorial-euroscipy2024/.venv/bin/python)
   machine: macOS-14.4.1-arm64-arm-64bit

Python dependencies:
          pip: 24.1
       sktime: 0.32.1
      sklearn: 1.5.1
       skbase: 0.8.2
        numpy: 1.26.4
        scipy: 1.14.0
       pandas: 2.2.2
   matplotlib: 3.9.2
       joblib: 1.4.2
        numba: None
  statsmodels: 0.14.2
     pmdarima: 2.0.4
statsforecast: None
      tsfresh: None
      tslearn: None
        torch: None
   tensorflow: None
tensorflow_probability: None

</details>

**Comment by fkiraly** [comment]
Hm, what a weird and specific case.

This sounds as a bug in `prophet` to me, I would recommend to report it there - "type consistency of outputs" is a strong universal design principle for which there are barely good reasons to deviate.

I would guess this is sth about misuse of a too general coercion, or singular matrices.
