### ISSUE TITLE
[BUG] TimeSeriesDBSCAN cannot handle unequal length time series despite being explicitly able to

### ISSUE THREAD

**Issue by chirag03k** [sktime/sktime#6993]
**Describe the bug**
`TimeSeriesDBSCAN` does not support unequal length clusters despite explicitly having the capability.

**To Reproduce**
```python
# data
ts1 = pd.Series(data=[1,2,3,5,6,9], index=[0,1,2,3,4,5])
ts2 = pd.Series(data=[1,2,6,3,6,1,3,0,3,4,3], index=[0,1,3,5,8,7,10,12,15,19,21])
ts3 = pd.Series(data=[1,5,6], index=[0,2,5])
data_df = pd.DataFrame()
data_df["Series"] = [ts1, ts2, ts3]

dist = EditDist(distance="twe")

twe_model =TimeSeriesDBSCAN(dist)
twe_model.fit(data_df)
```

**Expected behavior**
`TimeSeriesDBSCAN` clusters should be returned despite the unequal length time series. According to the [estimator overview](https://www.sktime.net/en/stable/estimator_overview.html#filter=clusterer&tags=%7B%22capability%3Amultivariate%22%3Afalse%2C%22capability%3Aunequal_length%22%3Atrue%2C%22capability%3Amissing_values%22%3Afalse%2C%22capability%3Acontractable%22%3Afalse%2C%22python_dependencies%22%3Afalse%2C%22authors%22%3Atrue%2C%22maintainers%22%3Atrue%7D), unequal length time series are supported by this model. However, attempting to fit this model results in a `ValueError` : (`ValueError: The data has unequal length series, this clusterer cannot handle unequal length series`). 

**Additional context**
Note that running `twe_model.get_class_tags()` results in
```
{'python_version': None,
 'python_dependencies': None,
 'env_marker': None,
 'object_type': 'clusterer',
 'X_inner_mtype': ['pd-multiindex', 'numpy3D'],
 'capability:multivariate': True,
 'capability:unequal_length': True,
 'capability:missing_values': True,
 'capability:multithreading': False,
 'authors': 'fkiraly',
 'maintainers': 'sktime developers'}
```
implying that unequal length time series are supported by this model.

In issue #6989, this was a documentation issue. Here, it seems that this is not cause by documentation because it appears very clear that this should be supported. My guess is that I'm doing something incorrect, or that a feature has changed.

**Versions**
<details>

</details>

**Comment by chirag03k** [comment]
It turns out that this is because the `EditDistance` cannot support unequal length distances.

**Comment by fkiraly** [comment]
Yes, correct - in composites like `TimeSeriesDBSCAN`, the capability may depend on the components. There is an open question how to signpost this. I think @pranavvp16 wanted to open an issue but this has not happened yet (likely due to the long weekend), so I'll do it to make sure there is a link to that here: https://github.com/sktime/sktime/issues/6994
