### ISSUE TITLE
[BUG] `nested_univ` to `pd.multtiindex` conversion returns wrong index names 

### ISSUE THREAD

**Issue by pranavvp16** [sktime/sktime#7025]
**Describe the bug**
while converting `nested_univ` to `pd.multiindex` the time index is hardcoded to be `timepoints` 

```python
    if isinstance(store, dict) and "index_names" in store.keys():
        instance_index = store["index_names"][0]
        time_index = store["index_names"][1]
    else:
        instance_index = obj.index.names[0]
        time_index = "timepoints"
```

**Expected behavior**
It should return `None` if name doesn't exist, or actual name if the nested series index has a name

**Comment by fkiraly** [comment]
Yes, I think the correct behaviour is *not* always setting `timepoints`,  but actually taking the `index.name` of any nested `pd.Series` in the container.
