### ISSUE TITLE
[ENH] TransformSelectForecaster could be able to fit global/panel forecasters

### ISSUE THREAD

**Issue by felipeangelimvieira** [sktime/sktime#7050]
**Describe the solution you'd like**
There is a paper [1] that indicates that the performance of global models (such as a regressor with reduction) is enhanced when a different model is fitted by clusters of similar timeseries.  Currently `TransformSelectForecaster` cannot do that.

**Describe alternatives you've considered**
`TransformSelectForecaster` has mtype `pd.DataFrame` and the categorizer is fit-transformed internally for each series. We could change the mtype to multiindex, apply the categorizer to the panel and then fit-predict the forecasters.

**Additional context**

[1] Semenoglou, Artemios-Anargyros, et al. "Investigating the accuracy of cross-learning time series forecasting methods." International Journal of Forecasting 37.3 (2021): 1072-1084.

**Comment by fkiraly** [comment]
Interesting idea!

My guess is that most users will expect by default the "apply per every series in the group" behaviour, but applying a panel forecaster to *all series in a group simultaneously* also makes a lot of sense!

What I would do is steer the behaviour via an argument `pooling` that can be `"local"` or `"global"`, or similar, an alternative name could be `apply_to` and similar.

FYI @shlok191, this transformer seems to become quite popular 😄 - thoughts on the above?

**Comment by felipeangelimvieira** [comment]
I believe that the users would expect as default behaviour the behaviour of the forecasters selected for the category. Example: if a lightgbm with reduction is used for a certain category, and exponential smoothing to another, I may expect that the first fits globaly and the upcasting is used with exponential smoothing.

**Comment by felipeangelimvieira** [comment]
What do you think about it, Franz? I could help implementing this.

**Comment by fkiraly** [comment]
brilliant idea! I think this could work:

* as an extension to `TransformSelectForecaster`
* a new forecaster, e.g., `GroupedForecaster`

In the first case, we need to make sure we stay downwards compatible, that would probably mean sth like introducing a switch that allows the user to select the global/local behaviour, and default needs to be local. This could be changed later, but then would need change/deprecation management due to "do not break working code", see https://www.sktime.net/en/latest/developer_guide/deprecation.html#deprecation-policy

**Comment by shlok191** [comment]
@fkiraly, Sorry about the late reply. I just saw this! @felipeangelimvieira, thanks for the great idea! I am very glad that the `TransformSelectForecaster` is proving to be useful to the sktime community. I do not have much bandwidth available at the moment, but please let me know if I can provide any clarification or assistance with the `TransformSelectForecaster` or with any of the needed enhancements!

**Comment by felipeangelimvieira** [comment]
@shlok191  Thank you very much, your code is very friendly and clear, I'm currently implementing another class to handle global/panel forecasters, based on your `TransformSelectForecaster` implementation (#7066)
