### ISSUE TITLE
[DOC] Steps misnumbered in Installation guide

### ISSUE THREAD

**Issue by Saptarshi-Bandopadhyay** [sktime/sktime#7052]
#### Describe the issue linked to the documentation
Step 3 of the Installation guide for the Developer versions could have been misnumbered as Step 2.

As at first it says - 
"Step 1 - git clone the sktime repository, the latest version or an earlier version. 
Step 2 - ensure build requirements are satisfied 
Step 3 - pip install the package from a git clone, with the editable parameter.
Detail instructions for all steps are given below. For brevity, we discuss steps 1 and 3 first; step 2 is discussed at the end, as it will depend on the operating system."

But after this the 'pip install with editable parameter' is present in the -
"Step 2 - building sktime from source"

#### Suggest a potential alternative/fix

Step 2 should be renumbered to Step 3.
And potentially "Building binary packages and installers" could be numbered as Step 2.

Do correct me if I'm wrong. 
Thank you ☺️

**Comment by fkiraly** [comment]
Looks indeed like a typo, thanks for reporting! Fix would be appreciated via PR!

**Comment by Saptarshi-Bandopadhyay** [comment]
Hey, I'm trying to send a PR but having some issues with building the docs locally, I've described my issue in detail in the "Working-group-chat  --> dev" channel in discord

Alternatively I can describe the issue here too, please let me know if it would be more helpful :)

**Comment by Saptarshi-Bandopadhyay** [comment]
here's the issue

I have installed the extra dependencies for building documentation by running 
```pip install --editable .[docs]```

then I run 
```make html```

but I get this error 
```PandocMissing in examples/00_sktime_intro.ipynb:
Pandoc wasn't found.
Please check that pandoc is installed:
https://pandoc.org/installing.html
```

even though pandoc is not mentioned in the dependencies listed in pyproject.toml

I've also tried installing sphinx-autobuild and running 
```make autobuild```

this also results in the same

**Comment by fkiraly** [comment]
@duydl's reply from discord:

Pandoc is a dependency of nbsphinx and needs to be installed separately
https://nbsphinx.readthedocs.io/en/0.2.15/installation.html#pandoc

**Comment by Saptarshi-Bandopadhyay** [comment]
Got it! Thanks :)
