### ISSUE TITLE
[BUG] evaluate function not giving scoring values when reconciler forecaster is used

### ISSUE THREAD

**Issue by SaiRevanth25** [sktime/sktime#7107]
**Describe the bug**
 evaluate function is not returning scoring values when used with reconciler forecaster

**To Reproduce**

```python
from sktime.datasets._hierarchical_demo import load_hierarchical_sales_toydata
from sktime.forecasting.model_evaluation import evaluate
from sktime.performance_metrics.forecasting import MeanAbsolutePercentageError
from sktime.split import ExpandingWindowSplitter
from sktime.forecasting.reconcile import ReconcilerForecaster
from sktime.forecasting.compose import make_reduction
from sklearn.ensemble import RandomForestRegressor

dataset = load_hierarchical_sales_toydata()

regressor = RandomForestRegressor(n_estimators=200)
forecaster = make_reduction(regressor, strategy='recursive', pooling='global')
reconciler = ReconcilerForecaster(forecaster, method = "td_fcst")

cv = ExpandingWindowSplitter(initial_window=40, step_length=7, fh=np.arange(1, 7))

results = evaluate(
    forecaster=reconciler,
    y=dataset,
    cv=cv,
    scoring=[MeanAbsolutePercentageError()],
)
```
![image](https://github.com/user-attachments/assets/31d4ca51-731a-4490-9dce-a05c1776721d)

**Expected behavior**
 scoring values should be present

**Comment by fkiraly** [comment]
I think the underlying reason might be this:

https://github.com/sktime/sktime/issues/4557

**Comment by SaiRevanth25** [comment]
as in #4767 
> the Reconciler and ReconcilerForecaster should have an option whether the "total" levels are preserved, or removed at the end.


Adding a parameter, let's say`total` , to the reconciler forecaster which when False, returns the dataframe without the dunder levels

```
if not total:
    n= df.index.get_slice_bound(label='__total', side='left')
    return df[:n]
```

**Comment by fkiraly** [comment]
yes, that would be a solution to the integration issue.

Still, the issue remains for the metrics, but we cna deal with that separately.
