### ISSUE TITLE
[BUG] KANForecaster fails with newest version (2.6.0)

### ISSUE THREAD

**Issue by benHeid** [sktime/sktime#7116]
**Describe the bug**
In the CI (https://github.com/sktime/sktime/actions/runs/10824795191/job/30045061812) the fit of the KANForecaster fails due to `TypeError: MultKAN.fit() got an unexpected keyword argument 'device'`, since the device is not a key word of fit anymore. Now it is a parameter of `__init__`

**Comment by fkiraly** [comment]
I thought this passed in tests previously?

**Comment by benHeid** [comment]
In which tests?

**Comment by fkiraly** [comment]
The `test-all` suite we run before releases - I think this is because that does not run the `test-full` but just module tests, where the deep learning dependencies are not installed?
