### ISSUE TITLE
[BUG]`sktime` doesn't work with older versions of polars 

### ISSUE THREAD

**Issue by vedantag17** [sktime/sktime#7128]
**Describe the bug**

`polars` version on colab is set as 0.20.2 which cause sktime to crash.  

**To Reproduce**

```python
import polars as pl
pl.show_versions()
```

**Expected behavior**
The latest version of Polars should be installed via the command.

**Additional context**
A similar issue was raised before, yet after the changes merged the problem persists.
The issue can be found at: https://github.com/sktime/sktime/issues/7056

**Versions**

-  Details

```--------Version info---------
Polars:               0.20.2
Index type:           UInt32
Platform:             Linux-6.1.85+-x86_64-with-glibc2.35
Python:               3.10.12 (main, Jul 29 2024, 16:56:48) [GCC 11.4.0]

----Optional dependencies----
adbc_driver_manager:  <not installed>
cloudpickle:          2.2.1
connectorx:           <not installed>
deltalake:            <not installed>
fsspec:               2024.6.1
gevent:               <not installed>
matplotlib:           3.7.1
numpy:                1.26.4
openpyxl:             3.1.5
pandas:               2.1.4
pyarrow:              14.0.2
pydantic:             2.9.1
pyiceberg:            <not installed>
pyxlsb:               <not installed>
sqlalchemy:           2.0.34
xlsx2csv:             <not installed>
xlsxwriter:           <not installed>```
</details>

**Comment by pranavvp16** [comment]
Thanks for reporting

@fkiraly I tried replicating this issue, seems #7056 didn't fix the issue as `0.20.2` bypasses the bound in `check_soft_dependancies`. We should change the bound to `polars>=1.0.0` ,cause the strict parameter was introduced from version `1.0.0`

**Comment by fkiraly** [comment]
This is coming from tests only, so with "clean" architecture should not cause crashes. I think the pattern we have used for the example fixtures is too brittle and risky, putting them just on the module level. We need to wrap the examples as proper fixture objects which isolate all soft dependencies.

A prototype for this has been added here: https://github.com/sktime/skpro/pull/458

I could refactor this way quickly with copy-paste, this would hopefully the issue, and any future problems like this.

**Comment by fkiraly** [comment]
stupid question, the docs seem to imply that the `strict` argument is present in 0.20.0 onwards
https://docs.pola.rs/api/python/version/0.20/reference/dataframe/index.html

Is the reason for the crash different?

**Comment by pranavvp16** [comment]
> stupid question, the docs seem to imply that the `strict` argument is present in 0.20.0 onwards
> https://docs.pola.rs/api/python/version/0.20/reference/dataframe/index.html
> 
> Is the reason for the crash different?

No the reason for the crash is the strict parameter, I don't know why it's present in the docs of version `0.20.0`. I tried to replicate it in Google Collab. 

https://colab.research.google.com/drive/1I8HBtCniWB2cvDu7nqKfHCsVeeAjXe0o?usp=sharing

**Comment by fkiraly** [comment]
Is there any way we can test the condition "package runs on colab", e.g., just the minimal test suite?

That would require some programmatic way to get the colab dependencies.

**Comment by pranavvp16** [comment]
> Is there any way we can test the condition "package runs on colab", e.g., just the minimal test suite?
> 
> That would require some programmatic way to get the colab dependencies.

yes upgrading polars version at Google Collab successfully imports sktime

**Comment by fkiraly** [comment]
no, I mean, as part of the CI

**Comment by pranavvp16** [comment]
okay understood, that's a good idea. I will have to look at it. 

I tried doing a pip freeze and get the Collab dependencies in a file ![requirements.txt](https://github.com/user-attachments/files/17040466/requirements.txt)


These are bunch of dependencies !

**Comment by fkiraly** [comment]
I started here with the refactor: https://github.com/sktime/sktime/pull/7133

> I tried doing a pip freeze and get the Collab dependencies in a file requirements.txt

`pip freeze` will not work programmatically, as this will step out of sync as soon as `colab` update one of their dependencies - which is what has triggered this bug report, since originally I think `polars` was at 0.18.0 which was fine, and now we are at 0.20.0, which moves into the region where this bug exists.

**Comment by vedantag17** [comment]
The colab has upgraded its version of `polars` to `1.6.0`  that fixes the issue

**Comment by fkiraly** [comment]
Well, I suppose that fixes the colab problem, but not the incompatibility with that narrow version range, so lets keep the issue open until that is repaired too
