### ISSUE TITLE
[BUG] predict_interval fails as not supported even though capability:pred_int set to True. (Related to PR #6424)

### ISSUE THREAD

**Issue by ericjb** [sktime/sktime#7145]
When running the code below, the following error is produced.
RuntimeError: PolynomialTrendForecaster does not implement probabilistic forecasting, but "capability:pred_int" flag has been set to True incorrectly. This is likely a bug, please report, and/or set the flag to False.

```python
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import matplotlib.style as style

from sktime.forecasting.trend import PolynomialTrendForecaster
from sktime.forecasting.base import ForecastingHorizon
from sktime.utils import plot_series

N = 500
# Create a DataFrame with random elements from N(0,1)
data = np.random.normal(0, 1, N)
date_index = pd.date_range(start='1970-01-01', periods=N, freq='D')

df = pd.DataFrame(data, index=date_index, columns=['x'])

forecaster = PolynomialTrendForecaster(degree=2, prediction_intervals=True)
forecaster.fit(df)
fh = ForecastingHorizon([1,2,3,4,5,6], is_relative=True)

pred_values = forecaster.predict(fh)
pred_interval = forecaster.predict_interval(fh, coverage=[0.95])
_, ax = plot_series(sales, fitted_values, pred_values, pred_interval=pred_interval)
plt.show()
```

**Comment by fkiraly** [comment]
Quick clarification: is this a bug on your branch? Since on main, the forecsater indeed does not implement `predict_proba`, so the error message is correct.

**Comment by ericjb** [comment]
I don't think the error message is correct, based on previous email correspondence with you. 
Here is a step-by-step of what I did so you can decide for yourself. I performed this exercise just now.
1. create a fresh virtual environment and do a pip install sktime, matplotlib, seaborn, ipykernel
2. replace the production version of forecasting/trend/_polynomial_trend_forecaster.py with the version from PR #6424
3. run the source code below in VS Code in an interactive window. It works fine and the plot comes up including prediction intervals.
4. delete from forecasting/trend/_polynomial_trend_forecaster.py the method _predict_quantiles. (Based on your earlier review comments that this function does nothing different than base predict_quantiles, which is true. I did nothing to this function.)
5. redo step 3. It fails with the error: 
 RuntimeError: PolynomialTrendForecaster does not implement probabilistic forecasting, but "capability:pred_int" flag has been set to True incorrectly. This is likely a bug, please report, and/or set the flag to False

When I mentioned this in the past you said it seemed to be a bug and to issue a new PR which you then asked I switch to an issue. 

Here's the source code to use:

```
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import matplotlib.style as style

from sktime.forecasting.trend import PolynomialTrendForecaster
from sktime.forecasting.base import ForecastingHorizon
from sktime.utils import plot_series

N = 500
# Create a DataFrame with random elements from N(0,1)
data = np.random.normal(0, 1, N)
date_index = pd.date_range(start='1970-01-01', periods=N, freq='D')

df = pd.DataFrame(data, index=date_index, columns=['x'])

forecaster = PolynomialTrendForecaster(degree=2, prediction_intervals=True)
forecaster.fit(df)
fh = ForecastingHorizon([1,2,3,4,5,6], is_relative=True)

pred_values = forecaster.predict(fh)
pred_interval = forecaster.predict_interval(fh, coverage=[0.95])
_, ax = plot_series(df['x'], pred_values, pred_interval=pred_interval)
plt.show()
```

**Comment by fkiraly** [comment]
> I don't think the error message is correct, based on previous email correspondence with you.

Sorry, I did not see the email (I am travelling with restricted access), it would be great if you could use GitHub exclusively for working on this bug.
