### ISSUE TITLE
[BUG] ForecastingHorizon.to_absolute() does not support freq is '2T'

### ISSUE THREAD

**Issue by tianjiqx** [sktime/sktime#7170]
**Describe the bug**

**To Reproduce**

```python

from sktime.forecasting.base import ForecastingHorizon
import numpy as np
import pandas as pd
from pandas import PeriodIndex
from pandas._libs.tslibs.period import Period

fh_range = np.arange(1, 4)

freq = '2T'
fh = ForecastingHorizon(fh_range, is_relative=True)
cutoff = PeriodIndex(['2024-09-26 17:24'], dtype='period[2T]', name='_time')
# cutoff = Period('2024-09-26 17:24', freq='2T')

fh = fh.to_absolute(cutoff)

print(fh)
# acutal: ForecastingHorizon(['2024-09-26 17:25', '2024-09-26 17:26', '2024-09-26 17:27'], dtype='period[2T]', is_relative=False)
# expected: ForecastingHorizon(['2024-09-26 17:26', '2024-09-26 17:28', '2024-09-26 17:30'], dtype='period[2T]', is_relative=False)

```

**Expected behavior**

expected: ForecastingHorizon(['2024-09-26 17:26', '2024-09-26 17:28', '2024-09-26 17:30'], dtype='period[2T]', is_relative=False)

**Additional context**

I suspect that due to `_coerce_cutoff_to_index` enforcing the use of PeriodIndex instead of Period, it is not able to handle intervals such as `2T`.

```python
    def _coerce_cutoff_to_index(self, cutoff):
        """Coerces cutoff to pandas index, and updates self.freq with cutoff."""
        self.freq = cutoff
        if not isinstance(cutoff, pd.Index):
            cutoff = pd.Index([cutoff])
        return cutoff

```

In earlier versions, such as sktime==0.13.4, the test case worked well. Is there any recommended way to do this now?

**Versions**

sktime==0.33.1

<details>

</details>

**Comment by fkiraly** [comment]
Hm, it might be related to various `pandas 2` issues with multiple frequencies.

I thought we had addressed them, see #6245

Do you know of a workaround? One workaround is `reset_index` and avoid the issue, though that may be problematic for feature extraction that uses the calendar date.

**Comment by fkiraly** [comment]
that works? That would be great!

We would very much appreciate a pull request, then all the tests will run and we will see if all the other test cases run through as well.

More long-term, we will probably need to build the `ForecastingHorizon` up from scratch.

**Comment by tianjiqx** [comment]
> I want to directly use the arithmetic properties of the Period type to add relative time intervals.我想直接使用Period类型的算术属性来添加相对时间间隔。 just like： 就像： ![image](https://private-user-images.githubusercontent.com/7732802/371132286-925ad4f2-947c-4710-9317-89873d8c73d2.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjczNTI0NjgsIm5iZiI6MTcyNzM1MjE2OCwicGF0aCI6Ii83NzMyODAyLzM3MTEzMjI4Ni05MjVhZDRmMi05NDdjLTQ3MTAtOTMxNy04OTg3M2Q4YzczZDIucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MDkyNiUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDA5MjZUMTIwMjQ4WiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9YmYxMGUxYWY2M2M4ZjA3NWIzYmM5ZmJjZTAzYzNhZjMzNGNhYWM5MTFmZDEwYzU1ODA1Yzk4YTQ2OGU4ZTViZiZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QifQ.vulFQ4GP-tEuR9T7USE35KeX_N9J2gjF8_T6AIMPPMM)
> 
> use `cutoff.tolist()` convert PeriodIndex to Period使用`cutoff.tolist（）`将PeriodIndex转换为Period

Yes, this will work like the previous version using Period (sktime==0.13.4).

**Comment by tianjiqx** [comment]
> that works? That would be great!这样行吗那就太好了！
> 
> We would very much appreciate a pull request, then all the tests will run and we will see if all the other test cases run through as well.我们将非常感谢一个pull request，然后所有的测试都会运行，我们将看到所有其他测试用例是否也会运行。
> 
> More long-term, we will probably need to build the `ForecastingHorizon` up from scratch.从更长远的角度来看，我们可能需要从头开始构建`ForecastingHorizon`。

ok, I try it
