### ISSUE TITLE
[ENH] `TimesFMForecaster` dependencies should depend on `use_source_package`

### ISSUE THREAD

**Issue by fkiraly** [sktime/sktime#7202]
In my opinion, the `TimesFMForecaster` dependencies should depend on `use_source_package`, as follows:

* if `use_source_package=False`, the default dependencies, of the vendor lib should be used
* if `use_source_package=True`, then there should be *no dependencies*, as the user needs to handle the source package installation. In particular, a modified source package may have less or other dependencies.

The dependencies would be set dynamically via `set_tags` in the `__init__` - this needs to happen before the `super` call to avoid the checks.

FYI @geetu040, comments appreciated, what do you think?

**Comment by fkiraly** [comment]
> I would suggest we put `timesfm` as the dependency here

I was thinking about that and arrived at the conclusion that the `use_source_package` dep set should be empty. Why: A user may have a fork or local content that is not the official package, or another package that provides the `timesfm` folder.

Alternatively, how about 3 settings? One for `timesfm` package, one for the `sktime` fork, and a third where the user deactivates the dep checks on their own risk?

**Comment by geetu040** [comment]
> A user may have a fork or local content that is not the official package

Thats actually a good consideration, but I have to add another point here.
if they release another version on pypi, that is going to break the current implementation inside sktime (I am talking about the inference, not the fork), so putting `timesfm` with a version bound can save this from future disruption.

If we want to consider both points, this looks like a good solution
> Alternatively, how about 3 settings? One for `timesfm` package, one for the `sktime` fork, and a third where the user deactivates the dep checks on their own risk?
