### ISSUE TITLE
[BUG] Inconsistent Behavior of Reconciliation Strategies with `return_totals=False`

### ISSUE THREAD

**Issue by SaiRevanth25** [sktime/sktime#7211]
**Describe the bug**
 PR #7208 - In the Reconciler Forecaster, when the return_totals parameter is set to `False` , only the `min_shrink` strategy works as expected, while the other reconciliation strategies do not seem to function correctly.

**Comment by fkiraly** [comment]
What is the exact failure when the strategy is something else?

**Comment by SaiRevanth25** [comment]
the `__total` levels are still present in the dataframe returned

**Comment by fkiraly** [comment]
Yes, but you added code for removing them - so I would think, the most important bit is checking whether that code is executed, and if not, why; if yes, why it does not remove the levels.

**Comment by SaiRevanth25** [comment]
The strategies which are used from [transformations/hierarchical/reconcile](https://github.com/sktime/sktime/blob/main/sktime/transformations/hierarchical/reconcile.py#L102) are already reconciled, so the DataFrame is returned directly in these cases. As a result, the code I wrote to remove the `dunder` levels is not being triggered. Fixed it now!!

**Comment by fkiraly** [comment]
Where is the fix? Would you be able to link the PR?

**Comment by SaiRevanth25** [comment]
Fixed it in the PR https://github.com/sktime/sktime/pull/7208
