### ISSUE TITLE
[DOC] `MOIRAIForecaster` is not showing up in the API documentation

### ISSUE THREAD

**Issue by benHeid** [sktime/sktime#7217]
#### Describe the issue linked to the documentation

https://www.sktime.net/en/latest/api_reference/auto_generated/sktime.forecasting.moirai_forecaster.MOIRAIForecaster.html

#### Suggest a potential alternative/fix

Add the forecaster to the rst file

**Comment by fkiraly** [comment]
@Dehelaan, thanks for your attempt to fix it!

What you need to do though, is ensure your fork is up-to-date - in the GitHub web API, you can click the "update fork" button on your fork.
