### ISSUE TITLE
[BUG] DartsLinearRegression fails instead of giving warning message

### ISSUE THREAD

**Issue by wilsonnater** [sktime/sktime#7224]
**Describe the bug**
`DartsLinearRegressionModel` fails when a warning should be raised

**To Reproduce**

```python
from sktime.datasets import load_airline
from sktime.forecasting.darts import DartsLinearRegressionModel
y = load_airline()
forecaster = DartsLinearRegressionModel(output_chunk_length=6,likelihood="quantile",quantiles=[0.33,0.5,0.67])
forecaster.fit(y=y)
```
ouput:
```
TypeError: warn() got an unexpected keyword argument 'message'
```

**Expected behavior**
A python warning message saying:
```
"Setting multi_models=True with quantile regression may cause issues. Consider using multi_models=False."
```

**Additional context**
It looks like this is the wrong key word arguments were passed into warn (`message` instead of `msg`) at [line 595](https://github.com/sktime/sktime/blob/0f75b7ad0dce8b722c81fe49bb9624de20cc4923/sktime/forecasting/darts.py#L595) and [line 369](https://github.com/sktime/sktime/blob/0f75b7ad0dce8b722c81fe49bb9624de20cc4923/sktime/forecasting/darts.py#L369)

If you are okay with it, I could give a PR for this.

**Versions**
Python dependencies:
          pip: 23.2.1
       sktime: 0.33.1
      sklearn: 1.5.2
       skbase: 0.8.3
        numpy: 1.26.4
        scipy: 1.14.1
       pandas: 2.1.2
   matplotlib: 3.8.1
       joblib: 1.4.2
        numba: 0.60.0
  statsmodels: 0.14.4
     pmdarima: 2.0.4
statsforecast: 1.7.8
      tsfresh: 0.20.3
      tslearn: None
        torch: None
   tensorflow: 2.16.2

**Comment by fkiraly** [comment]
FYI @fnhirwa

**Comment by fnhirwa** [comment]
Nice catch, the keyword passed to the `warn` function is supposed to be `msg` instead of `message`.
I am going to open a PR for this.
