### ISSUE TITLE
[ENH] Radial Basis Functions

### ISSUE THREAD

**Issue by ncooder** [sktime/sktime#7253]
Add radial basis functions for Time series transformations based on:
https://github.com/koaning/scikit-lego/blob/main/sklego/preprocessing/repeatingbasis.py

**Comment by ncooder** [comment]
@fkiraly No, it is a different feature. Please refer to:
https://skforecast.org/0.13.0/faq/cyclical-features-time-series.html#

**Comment by fkiraly** [comment]
I see! `FourierFeatures` is a template that one can use for the transformation though.

**Comment by phoeenniixx** [comment]
Hi @fkiraly and @ncooder, I read about this function and studied a lit more about them like in this [paper](https://www.sciencedirect.com/science/article/abs/pii/S0164070420301361)
 It is about the RBF ANNs and ig we can use them as well to study time series. what do you think?
 Or is it already implemented here? Not sure about that 😅

I also implemented the transformer class for the radial basis functions that for now uses gaussian (which is implemented in the `scikit-lego` implementation @ncooder provided), I also added multiquadratic and inverse-multiquadratic as well, as they also uses same variables, I can add more if you want..

I want to raise a PR for this, but not sure where to put them, should it be in `tranformations.series`? or something else?

**Comment by MarkusSagen** [comment]
Also had a request regarding this and could not quite make the `scikit-lego` class work within the sktime framework 

If there's anything I could help out with this, I'll love to help out too 🙂

**Comment by fkiraly** [comment]
@MarkusSagen, @phoeenniixx, no, RBF is no timplemented yet in `sktime`.

PR would be appreciated, the place to put it woulc be `transformations.series`, in a file with appropriate name, e.g., `basisfun`?
