### ISSUE TITLE
[BUG] Prophet is falsely tagged as "can't handle missing values"

### ISSUE THREAD

**Issue by Garve** [sktime/sktime#7266]
**Describe the bug**
Prophet has the tag `handles-missing-data == False`, but it can handle missing values.

**To Reproduce**
```python
from sktime.forecasting.fbprophet import Prophet
import pandas as pd


y = pd.Series([1, 2, 3, 4, np.nan, 6])
p = Prophet()
p.fit(y)
```

**Expected behavior**
A trained model.

**Versions**
0.33.1

**Comment by fkiraly** [comment]
Seems like an easy fix - could you correct the tag in the estimator?

**Comment by Garve** [comment]
Hi! Yes, very, the PR is open already. Feels a bit cheap though. 😆

**Comment by fkiraly** [comment]
Not cheap - there's the fix itself, and then there's recognizing that there was a problem in the first place. Both are part of the contribution, and in this case the latter is very non-trivial.
