### ISSUE TITLE
[BUG] `ExpandingCutoffSplitter` index out of bounds when `step_length` > 1 and used with `evaluate`

### ISSUE THREAD

**Issue by ninedigits** [sktime/sktime#7289]
**Describe the bug**

This bug occurs in the ExpandingCutoffSplitter class when the step_length parameter is greater than 1 and is used in conjunction with the evaluate function. Specifically, an "index out of bounds" error is triggered, suggesting that the internal indexing logic doesn't handle the step size correctly under these conditions, leading to an attempt to access data outside of the valid index range.

**To Reproduce**

This test case fails under the current version
```python
def test_expandingcutoff_step_length_and_evaluate():
    """Test fh as list with _check_cv"""
    from sktime.forecasting.model_evaluation import evaluate
    from sktime.forecasting.naive import NaiveForecaster
    y = _make_series(n_timepoints=15, random_state=42, index_type="period")
    cutoff = y.index[10]
    fh = [1]
    cv = ExpandingCutoffSplitter(cutoff=cutoff, fh=fh, step_length=3)

    forecaster = NaiveForecaster()
    evaluate(
        forecaster,
        cv,
        strategy="refit",
        y=y,
        return_data=True,
    )
```

**Expected behavior**

There should not be an index out of bounds error here
**Additional context**

**Versions**
<details>

</details>

**Comment by fkiraly** [comment]
Yes, the same error can be provoked without `evaluate`, namely via

```python
list(cv.split_series(y))
```

**Comment by fkiraly** [comment]
The intermediate reason is that a train split that ends at iloc "15" and a test split that contains "16" is generated, see

```python
list(cv.split(y))
```

therefore the internal logic must be broken.

Reproduced on current `main`.

**Comment by ninedigits** [comment]
@fkiraly I have a fix here: https://github.com/sktime/sktime/pull/7290

![image](https://github.com/user-attachments/assets/13657236-71d0-453a-b154-48e9fb9d3261)

**Comment by fkiraly** [comment]
yes, that's it. PR appreciated!

Though I am now concerned, why did the tests not pick this up? The test `test_split_series` should have done the testing here.
