### ISSUE TITLE
[ENH] add `skchange` estimators to `sktime` registry

### ISSUE THREAD

**Issue by fkiraly** [sktime/sktime#7351]
The `skchange` estimators should be added to the `sktime` estimator registry.

This can be done via the placeholder record pattern also used for `Prophetverse`.

For a tutorial on the pattern, see the corresponding notebook from the EuroSciPy 2024 workshop.
https://github.com/sktime/sktime-tutorial-euroscipy2024

The folder to add should be a subfolder of `detection`, possibly in a single `skchange` subfolder. Imports from that subfolder will redirect the imports to `skchange`, i.e., there are no mirror classes but redirected imports only. Presence in an `sktime` subfolder will also allow the estimator overview to be populated with the imported estimators.

FYI @mtveten, any preferences on folder structure? It could be a flat structure.

**Comment by ShivamJ07** [comment]
Interested

**Comment by fkiraly** [comment]
Great, thanks!

For the pattern, kindly follow `HierarchicalProphet` - and inherit from `sktime` `BaseDetector`.

If there are any tags that we need in `sktime`, please flag in https://github.com/sktime/sktime/issues/7374.

**Comment by fkiraly** [comment]
FYI @ShivamJ07, @tveten may end up renaming some of the estimators - we should use the long term end state names in `sktime` to avoid having to deprecate. Here is the issue: https://github.com/NorskRegnesentral/skchange/issues/30

Though I would say, please prepare this still with current names, until @tveten replies (which may not happen before the next release).

**Comment by Tveten** [comment]
Here's the PR for renaming https://github.com/NorskRegnesentral/skchange/pull/35. It has been merged, but it's not in a release yet.

@ShivamJ07
