### ISSUE TITLE
[ENH] rename `"series-annotator"` scitype to `"detector"`

### ISSUE THREAD

**Issue by fkiraly** [sktime/sktime#7352]
In line with the general rationale of https://github.com/sktime/sktime/issues/7295, we should rename the `"series-annotator"` scitype to `"detector"`.

To ensure downwards compatibility though, it is best to simply *add* the `"detector"` scitype in the list of scitypes (turning str into a list ot str), in the tag `object_type`. This will ensure that queries using the old name will still work, while queries with the new name start working, allowing us to transition to using the latter, new queries in tutorials, primary internal access patterns, etc.

**Comment by jgyfutub** [comment]
can I work on this issue?

**Comment by fkiraly** [comment]
Sure!

This one is a bit special though, we were planning to do this with the Waterloo Diabetes project.

However, this issue should be quick and there are many other items, so you would be helping out rather than taking someone´s work. It would be great if you could have a PR ready by Nov 6, so it does not delay scheduling on the Diabetes project - otherwise someone from there will pick it up.

**Comment by jgyfutub** [comment]
@fkiraly ok so shall I just rename `series-annotator` to `detector` where ever I find it in the repo?

**Comment by fkiraly** [comment]
Not everywhere - I think *estimators* should get it as an additional tag to preserve downwards compatibility. In other places, we add a second copy, and then add notes to remove the duplicates in 0.37.0.
