### ISSUE TITLE
[DOC] Binary Segmentation Estimator webpage missing

### ISSUE THREAD

**Issue by AriVagelatos-KSO** [sktime/sktime#7371]
#### Describe the issue linked to the documentation

The link from the estimator overview page ( https://www.sktime.net/en/stable/estimator_overview.html ) to Binary Segmentation is :
https://www.sktime.net/en/stable/api_reference/auto_generated/sktime.annotation.bs.BinarySegmentation.html
which is returning a 404 not found.

**Comment by fkiraly** [comment]
Yes, indeed, well spotted - it is missing from `docs/source/api_reference/detection.rst`. It would be great if you could add it, "follow the pattern" style, in a pull request!
