### ISSUE TITLE
[ENH] add detector specific tags to the tag registry and tags API reference

### ISSUE THREAD

**Issue by RobotPsychologist** [sktime/sktime#7374]
**Is your feature request related to a problem? Please describe.**
Add detector-specific tags to the tag registry and tags API reference.

**Describe the solution you'd like**

- Detector specific tags added to [docs/source/api_reference/tags.rst](https://github.com/sktime/sktime/blob/37d601786c27fbaed084dc6b79194c6d5554f648/docs/source/api_reference/tags.rst)
- Detector specific tags added to [sktime/registry/_tags.py](https://github.com/sktime/sktime/blob/37d601786c27fbaed084dc6b79194c6d5554f648/sktime/registry/_tags.py)

**Additional context**
This enhancement is facilitated by the bg_control team, the issue for their project is found here:
* https://github.com/RobotPsychologist/bg_control/issues/106
* https://github.com/RobotPsychologist/bg_control/issues/127
* HackMD document
* Extensions Template
* BaseClass Extensions
    * sktime
    * skchange
* Capability tags do not yet exist in some cases.

**Comment by RobotPsychologist** [comment]
@liya-zhu please comment on this task so that @fkiraly can assign you.

**Comment by liya-zhu** [comment]
I’d like to be assigned 😃
