### ISSUE TITLE
[ENH] Create special case of EnsembleForecaster that consists of N copies of identical forecaster to facilitate hyperparameter tuning

### ISSUE THREAD

**Issue by ericjb** [sktime/sktime#7407]
Convergence of ML models such as Neural Nets is affected by the initial (random) weights. This effect is often mitigated by creating an ensemble of N instances of the ML model, where each is fitted using different initial weights. This creates a problem when trying to tune hyperparameters of the underlying ML model (e.g. the number of hidden layers in the Neural Net). There is no easy way to require that the same parameter value (e.g. the number of hidden layers) is used for each instance within the ensemble.

An ideal solution, possibly, would be the ability to set a flag that the Ensemble consists of N copies of the same forecaster. When this flag is set, parameters of each instance would be set identically. Hyperparameter tuning, e.g. via grid search, should then be easy to formulate. As importantly, hyperparameter tuning would be efficient, in the sense that the search is restricted to cases where all instances get the same parameter value.

**Comment by fkiraly** [comment]
Great idea! I would suggest a minimal extension to the specification syntax, where a third element can be passed in name/estimator tuples, namely `(name: str, estimator: BaseForecaster, count: int)`.

This is supprorted out of the box by `_HeterogenousEnsembleForecaster`, the parent class, and needs to be adapted in the place where the internal estimator list is constructed.
