### ISSUE TITLE
[BUG] HierarchyEnsembleForecaster `forecasters_` attribute does not contain fitted forecasters

### ISSUE THREAD

**Issue by felipeangelimvieira** [sktime/sktime#7418]
**Describe the bug**
The `HierarchyEnsembleForecaster` has an attribute `forecasters_` which is not fitted, and does not follow the convention in other estimators to have this attribute as a dataframe/list of fitted estimators. Instead, there is a `fitted_list` attribute with them.

**To Reproduce**

```python
from sktime.forecasting.compose import HierarchyEnsembleForecaster
from sktime.forecasting.naive import NaiveForecaster
from sktime.forecasting.trend import PolynomialTrendForecaster, TrendForecaster
from sktime.utils._testing.hierarchical import _bottom_hier_datagen

y = _bottom_hier_datagen(no_bottom_nodes=7, no_levels=2, random_seed=123)

# Example of by = 'level'
forecasters = [("naive", NaiveForecaster(), 0), ("trend", TrendForecaster(), 1)]
forecaster = HierarchyEnsembleForecaster(
    forecasters=forecasters, by="level", default=PolynomialTrendForecaster(degree=2)
)
forecaster.fit(y, fh=[1, 2, 3])
[m.is_fitted for _, m, _ in forecaster.forecasters_]
```
**Expected behavior**
Expected behaviour would be an output [True, True, True] from the code above

**Additional context**

I noticed that different estimators have forecasters_ in varying structures: some as a list of tuples, others as a simple list, and in cases of automatic broadcasting or vectorization, as a dataframe. Could this potentially be standardized in the future?

**Versions**
<details>

System:
executable: [.../app-IMrWfz3g-py3.9/bin/python)

Python dependencies:
          pip: 23.1.2
       sktime: 0.30.2
      sklearn: 1.5.2
       skbase: 0.8.3
        numpy: 1.26.4
        scipy: 1.13.1
       pandas: 1.5.3
   matplotlib: 3.6.3
       joblib: 1.4.2
        numba: 0.60.0
  statsmodels: 0.14.4
     pmdarima: 2.0.4
statsforecast: 1.7.8
      tsfresh: None
      tslearn: None
        torch: None
   tensorflow: None
tensorflow_probability: None
</details>

**Comment by Spinachboul** [comment]
@felipeangelimvieira 
Hi! I want to be assigned for this issue, I reviewed the code, noticed the `forecasters_` is not populated properly with the fitted models during the fitting process, and would like to fix the bug!

**Comment by felipeangelimvieira** [comment]
Hi @Spinachboul ! It seems that @sanskarmodi8  has already started working on this topic.

**Comment by Spinachboul** [comment]
oh ok! Is there any other issue I can be mapped to?

**Comment by felipeangelimvieira** [comment]
@Spinachboul  One issue that I saw other day and it seems that no one is assigned yet is #7363. It is also pretty interesting

**Comment by fkiraly** [comment]
I found out the deeper issue while looking at @ericjb's PR https://github.com/sktime/sktime/pull/7424 - the class, like a few others, inherits from `_HeterogeneousEnsembleForecaster` which does set the `_steps_fitted_attr` attribute, nor populates it with the fitted forecasters. All descendants of this class have hte problem.

I think the class needs to be reworked a bit to add that feature, and it should be fine.
