### ISSUE TITLE
[BUG] InceptionTimeClassifier implementation is incomplete (Ensemble of Inception classifiers missing)

### ISSUE THREAD

**Issue by skinan** [sktime/sktime#7453]
**Description**

The original paper of InceptionTime  ([InceptionTime: Finding AlexNet for Time Series Classification](https://link.springer.com/article/10.1007/s10618-020-00710-y)) by Hassan Ismail Fawaz et al. states that the proposed InceptionTime model is an ensemble of 5 inception networks. However, the current implementation of the **[InceptionTimeClassifier](https://www.sktime.net/en/latest/api_reference/auto_generated/sktime.classification.deep_learning.InceptionTimeClassifier.html#)** API adopts the code, only from the **Classifier_Inception** class from [inception.py ](https://github.com/hfawaz/InceptionTime/blob/master/classifiers/inception.py) file (original codebase of the paper). But this version ([inception.py](https://github.com/hfawaz/InceptionTime/blob/master/classifiers/inception.py)) of the file only contains the non-ensemble way or implementation for a single inception network. To make it work like the originally proposed version of **InceptionTime**, an ensemble of 5 inception network is recommended by the original authors and this implementation can be found in the [nne.py](https://github.com/hfawaz/InceptionTime/blob/master/classifiers/nne.py) file from the original code base of InceptionTime model. Also, please check the [main.py](https://github.com/hfawaz/InceptionTime/blob/master/main.py) from the original code base (average prediction of 5 Inception network classifiers or models is considered as the outcome of the final proposed InceptionTime model)

**Reference**
```python
class InceptionTimeClassifier(n_epochs=1500, batch_size=64, kernel_size=40, n_filters=32, use_residual=True, use_bottleneck=True, bottleneck_size=32, depth=6, callbacks=None, random_state=None, verbose=False, loss='categorical_crossentropy', metrics=None)
```
[[ **API Source of sktime Implementation of InceptionTimeClassifier class**]](https://github.com/sktime/sktime/blob/main/sktime/classification/deep_learning/inceptiontime.py#L15-L249)

**Summary**
**InceptionTime** model is an ensemble of _several_ **Inception** networks, but the current sktime implementation only has a single Inception network in the name of InceptionTime model ([InceptionTimeClassifier](https://www.sktime.net/en/latest/api_reference/auto_generated/sktime.classification.deep_learning.InceptionTimeClassifier.html#)). 

**_I request kind and generous attention to this issue from the sktime developers._ Thanks for your great efforts !**

**Comment by fkiraly** [comment]
Thanks for reporting, @skinan!

May I ask a few questions:

* in the original code by hfawaz, where would you set the "5" from the ensemble of 5 inception time networks?
* would the ensemble you are looking at be the same as using the `BaggingClassifier` with `n_estimators=5`, `bootstrap=False`, and `estimator` the `InceptionTimeClassifier` instance?

For fixing, I would suggest to do these separately:
* adding an explanation to the docstring of `InceptionTimeClassifier` that this is just a single instance
* possibly: adding a second estimator that has the ensemble, possibly aliasing the `BaggingClassifier` composition?

**Comment by skinan** [comment]
@fkiraly , The `BaggingClassifier` with`n_estimators=5`, `bootstrap=False` using `InceptionTimeClassifier` as `estimator` should work fine in this case. I think adding an **explanation or NOTE** that the `InceptionTimeClassifier` here, is just a single instance and accordingly updating the example with `BaggingClassifier` wrapper around should be the best solution for now.
Would you suggest I create a pull request to fix that in the docstring? Thank you for your kind response.

**Comment by skinan** [comment]
@fkiraly , The `BaggingClassifier` with`n_estimators=5`, `bootstrap=False` using `InceptionTimeClassifier` as `estimator` should work fine in this case. I also think that adding an **explanation or NOTE** that the `InceptionTimeClassifier` here, is just a single instance and accordingly updating the example with `BaggingClassifier` wrapper, should be the best solution for now. The second solution might not needed as the first the one is quite straightforward solution at this stage.

So, can you confirm if I should create a pull request to fix that in the docstring? Thank you for your kind response.


> Thanks for reporting, @skinan!
> 
> May I ask a few questions:
> 
> * in the original code by hfawaz, where would you set the "5" from the ensemble of 5 inception time networks?
> * would the ensemble you are looking at be the same as using the `BaggingClassifier` with `n_estimators=5`, `bootstrap=False`, and `estimator` the `InceptionTimeClassifier` instance?
> 
> For fixing, I would suggest to do these separately:
> * adding an explanation to the docstring of `InceptionTimeClassifier` that this is just a single instance
> * possibly: adding a second estimator that has the ensemble, possibly aliasing the `BaggingClassifier` composition?
