### ISSUE TITLE
[ENH] refactor test class registry into type registry

### ISSUE THREAD

**Issue by fkiraly** [sktime/sktime#7493]
It is easier to maintain the test class registry as part of the type registry, as it is essentially a pointer type -> base class.

Suggested refactor:
* add a new class method `get_test_class` to the classes in `registry._base_classes`
* move the information from `get_test_class_registry` in there, and replace the internals of `get_test_class_registry` by a programmatic query of the `registry._base_classes`.

**Comment by jgyasu** [comment]
hi, can I be assigned to this issue?

**Comment by fkiraly** [comment]
sure!

**Comment by fkiraly** [comment]
Update: I am planning to do this as I need this for a metrics rework.

Have you already started, @jgyasu? If so, please open a PR with your current state and you will be credited.

**Comment by jgyasu** [comment]
@fkiraly I haven't. I tried understanding their codes and how they are organised but then got busy with the `SplineTrendForecaster` re-implementation with the `_DelegatedForecaster`. So please go ahead with it since it will take me time to understand and work and I assume this is something rather important.

**Comment by fkiraly** [comment]
ok, sure, I will wrap this up then.

For the `DelegatedForecaster` option, I was going to look at @Dehelaan´s PR and try to merge it - but if you are looking into it, feel free to make a PR to @Dehelaan´s PR then. Credit will go to you both.

**Comment by jgyasu** [comment]
> ok, sure, I will wrap this up then.
> 
> For the `DelegatedForecaster` option, I was going to look at @Dehelaan´s PR and try to merge it - but if you are looking into it, feel free to make a PR to @Dehelaan´s PR then. Credit will go to you both.

Making a PR to Dehelaan's PR won't require me to have write access to his repo? Correct me if I am wrong
