### ISSUE TITLE
[BUG] base framework does not recognize `python 3.11.0rc1` as compatible with `python_version` tag `>=3.8`

### ISSUE THREAD

**Issue by manuel-munoz-aguirre** [sktime/sktime#7517]
**Describe the bug**
When trying to import a StatsForecast model in python 3.11.0.rc1, the following error shows up:
```python
ModuleNotFoundError: StatsForecastAutoTheta requires python version to be >=3.8, but system python version is 3.11.0rc1 (main, Aug 12 2022, 10:02:14) [GCC 11.2.0].
```
This happens within the context of Databricks runtime 15.4 ML which is using 3.11.0rc1.

**To Reproduce**
```python
%pip install sktime==0.35.0 statsforecast==1.7.8
dbutils.library.restartPython()
```
```python
from sktime.forecasting.statsforecast import StatsForecastAutoTheta
StatsForecastAutoTheta()
```

**Expected behavior**
A model instance should be created without import errors due to the version since 3.11.0rc1 >= 3.8

**Additional context**
It seems like the comparison fails here. Reproduced this locally with the `sys.version` output string (`'3.11.0rc1 (main, Aug 12 2022, 10:02:14) [GCC 11.2.0]'`) generated in the Databricks compute instance. Unsure if this is an intended behavior or not due to it being a rc python version. Splitting the string works correctly and "3.11.0rc1" is correctly parsed but it seems that the comparison fails. https://github.com/sktime/sktime/blob/6271cb731044428cdc2390d809e6fd458a6b3924/sktime/utils/dependencies/_dependencies.py#L366-L371

**Versions**
<details>

System:
    python: 3.11.0rc1 (main, Aug 12 2022, 10:02:14) [GCC 11.2.0]

Python dependencies:
          pip: 23.2.1
       sktime: 0.35.0
      sklearn: 1.3.0
       skbase: 0.11.0
        numpy: 1.23.5
        scipy: 1.11.1
       pandas: 1.5.3
   matplotlib: 3.7.2
       joblib: 1.2.0
        numba: 0.57.1
  statsmodels: 0.14.0
     pmdarima: 2.0.4
statsforecast: 1.7.8
      tsfresh: None
      tslearn: None
        torch: 2.3.1+cpu
   tensorflow: 2.16.1

</details>

**Comment by fkiraly** [comment]
Hm, it seems this comes direcly from `packaging`, which we rely on for managing the estimator dependencies?

That is, `"3.11.0rc1" in SpecifierSet(">3.8")`?

Also, why is your databricks still on `3.11.0rc1`? That is a release candidate rather than a full release, and not recommended for stability reasons. It is also about 6 years old...

**Comment by fkiraly** [comment]
Here is the root cause:

```python
from packaging.specifiers import SpecifierSet

"3.11.0rc1" in SpecifierSet(">3.8")  # results in False
```

Quite odd - but surely there is a good reason this results in `False`, given that `packaging` is a standard package which has almost base python status?

**Comment by fkiraly** [comment]
@manuel-munoz-aguirre, would you mind checking here on the issue tracker and opening an issue if you do not find anything useful upon quick search?

https://github.com/pypa/packaging

**Comment by manuel-munoz-aguirre** [comment]
15.4 LTS is the most recent LTS runtime from Databricks (where they specify in the docs that it's 3.11.0, https://docs.databricks.com/en/release-notes/runtime/15.4lts.html#system-environment); but when running in the actual cluster, `sys.version` outputs `Python 3.11.0rc1`. 

I'll raise the issue over there. Thanks for the fast response!

**Comment by fkiraly** [comment]
Great, thanks! Kindly link this issue in the `packaging` issue.

Also, it does surprise me that the latest LTS runtime from Databricks is a 6 year old release candidate version, not even one of the actual stable releases. This seems like such a reliability/stability and security risk.

**Comment by manuel-munoz-aguirre** [comment]
Seems like there's a [flag to control for pre-releases](https://packaging.pypa.io/en/latest/specifiers.html#packaging.specifiers.SpecifierSet).

```python
from packaging.specifiers import SpecifierSet

specifier = SpecifierSet(">3.8", prereleases=True)
result = "3.11.0rc1" in specifier
print(result)
```

or directly inferred thru the tag (unsure if this is the correct way to do it):
```python
specifier = SpecifierSet(">=3.8rc")
result = "3.11.0rc1" in specifier
print(result)
```

**Comment by manuel-munoz-aguirre** [comment]
Sounds good! I'll be away for a couple of weeks though so I'll tag here @Abelarm who might be interested in helping out with this one.
