### ISSUE TITLE
[DOC] Multiplexer may not be picking the best model

### ISSUE THREAD

**Issue by ngupta23** [sktime/sktime#821]
**Describe the bug**
Multiplexer Forecaster may not be picking the best model

**To Reproduce**
From [example notebook](https://github.com/alan-turing-institute/sktime/blob/v0.6.0/examples/01_forecasting.ipynb) in v0.6

**Expected behavior**
Individual models pick ETS as the better model (from ETS and Naive), but Multiplexer picks Naive as the better model. I would have expected ETS to be picked.

**Additional context**

![image](https://user-images.githubusercontent.com/33585645/115124335-3ac01400-9f87-11eb-88b2-372ecb7fe7f0.png)

**Versions**
<details>
sktime 0.6
</details>

**Comment by fkiraly** [comment]
pinging @aiwalter and @koralturkk who were working on the multiplexer

**Comment by aiwalter** [comment]
@ngupta23 @fkiraly 
I think this is not a bug, but rather a bad configuration of the example. There is no `fh` given in the `cv`, that is why it is by default `1`, also the `window_length` of `30` is not appropriate for the monthly data. Following works:
```python
cv = SlidingWindowSplitter(initial_window=int(len(y_train) * 0.5), window_length=36, fh = [1,2,3,4,5,6,7,8,9,10,11,12])
```
It looks ok to me now. Also the `ets` model can be better by using...
```python
ExponentialSmoothing(trend="add", seasonal="additive", sp=12)
```
Will update the notebook, also the code highlighting in the description has to be fixed. Will open a PR for this.

**Comment by fkiraly** [comment]
I think this is superseded by changes in the multiplexer and grid search. @ngupta23, kindly reopen and comment if this is still unresolved.
