### ISSUE TITLE
[ENH] Nested `get_fitted_params` and `summary` interface

### ISSUE THREAD

**Issue by fkiraly** [sktime/sktime#971]
This is a feature suggestion arising from discussion in #877, #931, #942.

I suggest two new/refactored interface points:
* `summary` which is attached to `BaseObject` (as in post-merge #877)
* `get_fitted_params` which is attached to `sktime`'s (not `scikit-learn`'s) `BaseEstimator`

Update: it is probably better than the more convoluted suggestion below if the returns of both are `dict` and behave just like `get_params`. Any logic for retrieval should be provided in there, or a private version `_get_fitted_params`, rather than in "populate" functions.
 
---
Old API suggestion

Both should behave precisely like `scikit-learn`'s `get_params`, except that parameters are looked up in dedicated dictionaries `reports` and `fitted_params` rather than in self-attributes that correspond to `__init__` named arguments.

`fit` or `__init__` could populate these dictionaries, this could happen by `_populate_fitted_params` and `_populate_summary` private interfaces called at the end of `fit` (the non-private with the "plumbing" logic), which is specific to individual estimators/objects, or directly in `_fit` (not sure which is the better convention?).

For functionality, I think we can copy-paste `scikit-learn`'s `get_params` code here, and adapt it by making the change in where parameters are being retrieved. This would ensure nested access, which for example `get_fitted_params` doesn't have at current.

What do you think?
@mloning, @aiwalter, @RNKuhns, @ltsaprounis

**Comment by fkiraly** [comment]
Minor point: if you agree, what should be the name for the method retrieving information like AIC, R-squared, etc? `get_reports`, `inspect`, `inspect_reports`, `inspect_model`, `report_model`, `get_report_params`, `ishmael`, ...?

**Comment by mloning** [comment]
If reports are populated in `fit`, it should be attached to the `BaseEstimator` rather than `BaseObject` as not all objects will have a `fit` method. Or do you have other kinds of information in mind that other objects may have?

As to the naming:
* `inspect` seems too general given that we have `get_fitted_params`
* the terms `report` and `model` aren't used anywhere else, but `get_report` seems understandable
* `get_summary` may be an alternative, that's used in `statsmodels` already

**Comment by fkiraly** [comment]
>get_summary may be an alternative, that's used in statsmodels already

Alright, agree with the suggestion that's not on my list.

>If reports are populated in fit, it should be attached to the BaseEstimator rather than BaseObject as not all objects will have a fit method. Or do you have other kinds of information in mind that other objects may have?

Well, good question where the responsibility to create the summaries should lie. Retreival, though, I think should go in `BaseEstimator` or `BaseObject`, since it needs to be nested.

**Comment by fkiraly** [comment]
Addendum: `statsmodels` actually uses `summary`, not `get_summary`, so I suppose we should stick to calling the "reporting" method `summary`.

**Comment by fkiraly** [comment]
We have consolidated the design idea in `get_fitted_params`, and with PR https://github.com/sktime/sktime/pull/3077 this now has a nested interface too. Done!
