### ISSUE TITLE
Type aliasing

### ISSUE THREAD

**Issue by TonyBagnall** [sktime/sktime#973]
include unified and standardised type aliasing for forecasting, clustering and classification, started by @ABostrom 

https://github.com/alan-turing-institute/sktime/pull/964

**Comment by fkiraly** [comment]
hm, I don't think this is a good first issue! This requires intimate knowledge of the existing codebase and the scitype taxonomy...

**Comment by TonyBagnall** [comment]
Feel free to change the tag, Aaron has a first version based on the forecasting one

**Comment by fkiraly** [comment]
So, @ABostrom, @chrisholder, @jambo6, @TonyBagnall, @aiwalter, @mloning, I wanted to hear your opinion on a suggestion how to deal with descriptive type hints and type checks in one.

What I would propose is that our base class `fit` etc look like as follows (below without conversion etc), in the example of the forecaster base class:

```python

@scitype_decorator
def fit(X: Series, Y: Series):
    
    X = check(X)
    Y = check(Y)

    stuff(X,Y)

    self._fit(X.inner, Y.inner)
```

About the ingredients above:
* `Series` is a custom type, or perhaps better class that denotes `scitype`, not machine type
* what `scitype_decorator` does is wrap `X` and `Y` in the declarative type (ligh-weight wrapper), and does part of what `check_series` does: it annotates `X`, `Y`, with the machine type. E.g.,: `X = Series(X)`, which moves `X` to `X.inner`
* `check` inspects `X` for validity, and adds a `X.scitype = "DataFrame"` or similar annotation. So after `check`, we know that `X` is valid, and we can read the scitype and the mtype using `X.scitype` and `X.mtype`.
* the remaining `stuff` has access to these declarative type annotations. It could be compatibility checks, conversions, etc.

This proposal has some adtanvages:

* type annotation in the base class and the user docstrings will be with the "scientific type"
* the scientific type of any object is inspectable, per declarative annotation
* we have a consistent way, across modules, to track and inspect alias mtypes for the same scitype
* this could be eaily combined with a central "register" location of scitypes, mtypes, and/or a central location for validity checking, and the conversions module as sketched in #980

**Comment by chrisholder** [comment]
I like the look of this a lot @fkiraly. 

My only comment is (and Im sure this isn't final anyways) is the naming of the type 'Series' to me that implies a pandas Series. I ran into this issue of not knowing what to call my type describing pandas numpy and the other potential input types for clustering and ended up landing on:

`NumpyOrDF = Union[DataFrame, NumpyArray]`

Which equally isn't a good name :joy: . 

So my only question is why isn't the
```
    X = check(X)
    Y = check(Y)
```
inside the decorator (potentially you're just leaving it in fit for consistency)? Is this something we'd want to enforce as you're already mutating X in the decrator.

**Comment by fkiraly** [comment]
> I ran into this issue of not knowing what to call my type describing pandas numpy and the other potential input types for clustering and ended up landing on:

We could call it `TimeSeries`? Or `scitype-series` or `ScitypeSeries`, i.e., preface all the type hints with "scitype".

>why isn't the inside the decorator

For consistency is one reason, but also you may want to feed arguments to it depending on tags, and that's easier to read if it's explicit. In that situation, I thought it's better if the decorator logic does not depend on tags or other attributes of the host class, only arguments of the function it's applied to.

More generally, one should be able to read the code in `fit` without knowing that the decorator "wraps" `X` and `Y`, interpreting it purely as helping the type annotation.

**Comment by chrisholder** [comment]
I like ScitypeSeries personally

**Comment by TonyBagnall** [comment]
I like TimeSeries myself

**Comment by RNKuhns** [comment]
I also like TimeSeries, but would we also need to note the type of TimeSeries data, since it is the Scitype? 

UnivariateTimeSeries, MultivariateTimeSeries, PanelTimeSeries?

**Comment by fkiraly** [comment]
@RNKuhns, I'm not sure whether we need the difference univariate vs multivariate, but of course we will a separate type for panel.

Why do I think we may not need uni vs multivariate: I don't think it's that much of a difference in terms of type; the uni vs multivariate capability would also be handled by tags, and type conversion would happen in `fit`. So I don't see a place where we would pass this information as part of a type.

**Comment by ABostrom** [comment]
@fkiraly I agree with you on the differenatiation of uni and multi. 

I think separating them can make it harder down the line. Estimator, transformers etc should state whether they can handle this type of data. 

For example in TSML, the transformers have a fallback position where they just perform the transformation across each dimension etc. 
We could have a similar fallback position for univariate estimators whereby we ensemble on the dimensions?

**Comment by TonyBagnall** [comment]
I think things have moved on from here, and it conflates with other issues, really I just meant by this issue was to have return types where simple

**Comment by fkiraly** [comment]
obsolete due to `datatypes` framework
